"use client";
import{useEffect,useRef,useState}from"react";
import{changeGroomingBooking,loadRescheduleRequest,payRescheduleDifference,rescheduleDifferenceOffer,rescheduleRefusal,rescheduleRequestMessage,rescheduleRequestSettled,rescheduleSuccessMessage,type GroomingChangePreview,type RescheduleDifferenceOffer}from"../../../lib/grooming-booking-change-client";
import{openMobileRazorpayCheckout}from"../../../lib/mobile/razorpay";
import{checkoutReturnUrl}from"../../../lib/customer-checkout-client";
import{formatIndiaDateTime}from"../../../lib/india-time";
import styles from"./grooming-customer-booking.module.css";
const rupees=(amount:number)=>`₹${amount.toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const when=(iso:string)=>formatIndiaDateTime(iso,{fallback:"the new time"});
/** How long the time is still held, as m:ss. */
export function holdCountdown(holdExpiresAt:number,now:number){const seconds=Math.max(0,Math.floor((holdExpiresAt-now)/1000));return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;}

/** The dearer-time step: what it costs, what happens next, the customer's approval and the pay button. */
export function RescheduleDifferencePanel({offer,toStart,accepted,busy,holdExpiresAt,now,onAccept,onPay,onChooseAnother}:{offer:RescheduleDifferenceOffer;toStart:string;accepted:boolean;busy:boolean;holdExpiresAt:number|null;now:number;onAccept:(value:boolean)=>void;onPay:()=>void;onChooseAnother:()=>void}){
 return <section aria-label="Pay the difference for the new time"><h4>{when(toStart)} costs {rupees(offer.difference)} more</h4>
  <p>Your booked price is {rupees(offer.bookedAmount)} and the new time costs {rupees(offer.newSlotAmount)}. Your booking has not been moved and nothing has been charged yet.</p>
  <p className={styles.note}>When you pay {rupees(offer.difference)}, we hold the new time for {offer.holdMinutes} minutes and move your booking as soon as Razorpay confirms the payment. Your booking total becomes {rupees(offer.newTotalAmount)}. If we cannot move your booking, the {rupees(offer.difference)} is refunded to your original payment method.</p>
  {holdExpiresAt!==null&&holdExpiresAt>now&&<p role="status">We are holding this time for you for another {holdCountdown(holdExpiresAt,now)}.</p>}
  <label className={styles.consent}><input type="checkbox" checked={accepted} disabled={busy} onChange={event=>onAccept(event.target.checked)}/><span>I agree to pay {rupees(offer.difference)} more to move my booking to {when(toStart)}.</span></label>
  <button type="button" disabled={busy||!accepted} onClick={onPay}>{busy?"Opening secure payment…":`Pay ${rupees(offer.difference)} and move`}</button>
  <button type="button" disabled={busy} onClick={onChooseAnother}>Choose another time instead</button>
 </section>;
}

export default function GroomingRescheduleForm({preview,customerId,onChanged,onRefresh}:{preview:GroomingChangePreview;customerId:string;onChanged:(message:string)=>void;onRefresh:()=>void}){
 const[date,setDate]=useState(""),[time,setTime]=useState(""),[reason,setReason]=useState(""),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[needsRefresh,setNeedsRefresh]=useState(false);const sending=useRef(false);
 const[offer,setOffer]=useState<{offer:RescheduleDifferenceOffer;toStart:string}|null>(null),[payAccepted,setPayAccepted]=useState(false),[holdExpiresAt,setHoldExpiresAt]=useState<number|null>(null),[waitingFor,setWaitingFor]=useState(""),[watching,setWatching]=useState(""),[notice,setNotice]=useState(""),[now,setNow]=useState(()=>Date.now());
 // The hold countdown ticks only while a time is held.
 useEffect(()=>{if(holdExpiresAt===null)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[holdExpiresAt]);
 const changed=useRef(onChanged);useEffect(()=>{changed.current=onChanged;},[onChanged]);
 // After paying: poll until the booking has moved, a refund is raised, or the hold lapsed. After a closed or
 // failed checkout the same check runs quietly with the pay button still offered: a UPI payment approved in
 // another app can still arrive while the time is held.
 const polled=waitingFor||watching;
 useEffect(()=>{if(!polled)return;const quiet=!waitingFor;let active=true,attempts=0;const tick=async()=>{attempts++;try{const status=await loadRescheduleRequest(polled);if(!active)return;if(rescheduleRequestSettled(status.request.status)){active=false;setWaitingFor("");setWatching("");setHoldExpiresAt(null);setOffer(null);const message=rescheduleRequestMessage(status,rupees,when);if(status.request.status==="applied")changed.current(message);else{setError("");setNotice(message);}return;}}catch{/* keep polling; the next read may succeed */}if(active&&attempts>=60){active=false;if(quiet){setWatching("");return;}setWaitingFor("");setOffer(null);setHoldExpiresAt(null);setNotice("Razorpay has not confirmed your payment yet. Do not pay again: your booking moves automatically once the payment is confirmed, or the amount is refunded. Refresh this page later to see the result.");}};const timer=setInterval(()=>{if(active)void tick();},3000);void tick();return()=>{active=false;clearInterval(timer);};},[polled,waitingFor]);
 if(!preview.reschedule.allowed)return null;
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(sending.current||needsRefresh||!accepted||reason.trim().length<8||!date||!time)return;const start=new Date(`${date}T${time}:00+05:30`);if(!Number.isFinite(start.getTime())||start.getTime()<=Date.now()){setError("Choose a future date and time in IST.");return;}const end=new Date(start.getTime()+preview.durationMinutes*60000);sending.current=true;setBusy(true);setError("");setNotice("");setOffer(null);setPayAccepted(false);setWatching("");
  try{const result=await changeGroomingBooking({bookingId:preview.bookingId,customerId,action:"reschedule",reason:reason.trim(),scheduledStart:start.toISOString(),scheduledEnd:end.toISOString(),expectedConsentRevision:preview.consentRevision});if(result.bookingId!==preview.bookingId||result.scheduledStart!==start.toISOString()||result.scheduledEnd!==end.toISOString())throw new Error("The new schedule could not be verified. Refresh your booking before trying again.");onChanged(rescheduleSuccessMessage(result));}
  catch(problem){const difference=rescheduleDifferenceOffer(problem);if(difference){setOffer({offer:difference,toStart:start.toISOString()});setError("");}else{const refusal=rescheduleRefusal(problem);setError(refusal.message);setAccepted(false);if(!refusal.canChooseAnotherTime)setNeedsRefresh(true);}}finally{sending.current=false;setBusy(false);}
 };
 const pay=async()=>{if(!offer||sending.current||!payAccepted)return;sending.current=true;setBusy(true);setError("");setNotice("");
  try{
   const checkout=await payRescheduleDifference({bookingId:preview.bookingId,customerId,requestId:offer.offer.requestId,expectedDifference:offer.offer.difference,expectedConsentRevision:offer.offer.consentRevision,idempotencyKey:`reschedule-pay:${offer.offer.requestId}:${Date.now()}`});
   setHoldExpiresAt(checkout.holdExpiresAt);setNow(Date.now());
   const result=await openMobileRazorpayCheckout({keyId:checkout.keyId,orderId:checkout.orderId,amountPaise:checkout.amountPaise,currency:"INR",name:"PawSpace Grooming",description:"Difference for your new appointment time",notes:{booking_id:preview.bookingId,service:"grooming",stage:"reschedule_difference",reschedule_request_id:checkout.requestId},callbackUrl:checkoutReturnUrl(preview.bookingId),timeoutSeconds:checkout.checkoutTimeoutSeconds},checkout.locks);
   if(!result.success){const closed=result.code==="USER_DISMISSED"||result.code==="PAYMENT_FAILED";setError(closed?`${result.description} Your booking has not been moved. If you did complete the payment, we move your booking as soon as Razorpay confirms it; otherwise you can pay again while we hold the time.`:`${result.description} Your booking has not been moved.`);if(closed)setWatching(checkout.requestId);return;}
   setWatching("");setNotice("Payment received by Razorpay. Moving your booking now - do not pay again.");
   // The receipt is checked by PawSpace, which asks Razorpay directly when the signed webhook is late.
   await fetch("/api/customer-checkout",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm",bookingId:preview.bookingId,orderId:result.orderId,paymentId:result.paymentId,signature:result.signature})}).catch(()=>null);
   setWaitingFor(checkout.requestId);
  }catch(problem){const refusal=rescheduleRefusal(problem);setError(refusal.message);setOffer(null);setHoldExpiresAt(null);setAccepted(false);if(!refusal.canChooseAnotherTime)setNeedsRefresh(true);}finally{sending.current=false;setBusy(false);}
 };
 return <form className={styles.cancelForm} aria-label="Reschedule booking" onSubmit={submit}><h3>Choose a new appointment</h3><p>Your service duration stays {preview.durationMinutes} minutes. All times are India Standard Time (IST).</p><p className={styles.note}>If the new time costs the same or less, your price stays the same. If it costs more, your booking is not moved and nothing is charged until you approve and pay the difference; we then hold the new time for 10 minutes while you pay. If your groomer is busy at that time, another available groomer in your area may take the booking.</p><><label>New appointment date<input type="date" required value={date} disabled={busy||needsRefresh||Boolean(waitingFor)} onChange={event=>{setDate(event.target.value);setAccepted(false);setOffer(null);}}/></label><label>New appointment time (IST)<input type="time" required step={900} value={time} disabled={busy||needsRefresh||Boolean(waitingFor)} onChange={event=>{setTime(event.target.value);setAccepted(false);setOffer(null);}}/></label><label>Reason for changing the appointment<textarea required minLength={8} maxLength={1000} value={reason} disabled={busy||needsRefresh||Boolean(waitingFor)} onChange={event=>setReason(event.target.value)}/></label><label className={styles.consent}><input type="checkbox" checked={accepted} disabled={busy||needsRefresh||Boolean(waitingFor)} onChange={event=>setAccepted(event.target.checked)}/><span>I accept the displayed terms and request this new time, subject to provider availability.</span></label>{offer&&!waitingFor&&<RescheduleDifferencePanel offer={offer.offer} toStart={offer.toStart} accepted={payAccepted} busy={busy} holdExpiresAt={holdExpiresAt} now={now} onAccept={setPayAccepted} onPay={()=>void pay()} onChooseAnother={()=>{setOffer(null);setPayAccepted(false);setHoldExpiresAt(null);setWatching("");}}/>}{waitingFor&&<p role="status">Waiting for Razorpay to confirm your payment for the new time. Do not pay again.</p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{needsRefresh?<button type="button" onClick={onRefresh}>Refresh rescheduling terms</button>:!offer&&!waitingFor&&<button type="submit" disabled={busy||!accepted||!date||!time||reason.trim().length<8}>{busy?"Checking and updating…":"Confirm new appointment"}</button>}</></form>;
}
