import Link from"next/link";import Image from"next/image";import styles from"./premium-marketing.module.css";
export type ServiceCard={title:string;description:string;href:string;image?:string;eyebrow?:string};
export type ProofItem={value:string;label:string};
export type PackageCard={name:string;price?:string;description?:string;items:string[];featured?:boolean;badge?:string;href?:string};
export type Faq={q:string;a:string};
export const verifiedProof:ProofItem[]=[{value:"At-home care",label:"Comfortable, familiar surroundings for your pet"},{value:"Verified people",label:"Every caregiver identity-checked before their first visit"},{value:"Real updates",label:"Photos and progress, not just a chat message"},{value:"PawSpace support",label:"One connected customer and care record"}];
export const services:ServiceCard[]=[
 {title:"Pet Grooming",description:"Doorstep dog and cat grooming with clear packages and care instructions.",href:"/services/grooming",image:"/assets/banners/grooming-groomer-action.jpg"},
 {title:"Cat Grooming",description:"Gentle, cat-specific grooming packages designed around feline handling.",href:"/services/cat-grooming",image:"/assets/banners/grooming-bag-shihtzu.jpg"},
 {title:"Dog Training",description:"Structured at-home programmes with trainer-led goals and progress.",href:"/services/training"},
 {title:"Pet Boarding",description:"Home-style stays with host details, routines and care updates.",href:"/services/boarding",image:"/assets/stays/indiranagar-home.webp"},
 {title:"Pet Sitting",description:"Care at home for visits, day sitting and overnight needs.",href:"/services/sitting",image:"/assets/stays/sitter-care-update.webp"},
 {title:"Dog Walking",description:"Scheduled walks with care notes and GPS-supported operations.",href:"/services/walking",image:"/assets/banners/walking-street.jpg"},
 {title:"Fresh Food",description:"Fresh-food planning and delivery journeys for eligible customers.",href:"/services/fresh-food"},
 {title:"Pet Relocation",description:"Guided domestic and international relocation support.",href:"/services/relocation"},
 {title:"Pet Taxi",description:"Tracked pickup and drop, currently available by request as we expand this service.",href:"/services/taxi",image:"/assets/banners/taxi-car-window.jpg"},
 {title:"Doorstep Vet",description:"Veterinary care enquiries and coordination - diagnosis always stays with a qualified vet.",href:"/services/vet"},
];
export function MarketingShell({children}:{children:React.ReactNode}){return <main className={styles.page}><div className={styles.utility}>Pet care built around trust, visible service quality and connected customer support.</div><header className={styles.header}><div className={styles.headerInner}><Link className={styles.brand} href="/discover"><span className={styles.brandMark}>🐾</span>PawSpace</Link><nav className={styles.nav}><Link href="/discover">Home</Link><Link href="/services">Services</Link><Link href="/about">About</Link><Link href="/dog-breeds/beagle">Pet guides</Link><Link href="/contact">Contact</Link><Link href="/careers">Become a caregiver</Link><Link className={styles.headerCta} href="/mobile-app">Book care</Link></nav><Link className={`${styles.primary} ${styles.mobileOnly}`} href="/mobile-app">Book</Link></div></header>{children}<SiteCta/><Footer/></main>}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <div className={styles.breadcrumbs}>{items.map((item,i)=><span key={`${item.label}-${i}`}>{i?" › ":""}{item.href?<Link href={item.href}>{item.label}</Link>:item.label}</span>)}</div>}
export function Hero({eyebrow,title,accent,description,image,imageAlt,badgeTitle,badgeText,primaryLabel="Book care",primaryHref="/mobile-app",secondaryLabel="Explore services",secondaryHref="/services",locationSearch=false}:{eyebrow:string;title:string;accent:string;description:string;image?:string;imageAlt?:string;badgeTitle?:string;badgeText?:string;primaryLabel?:string;primaryHref?:string;secondaryLabel?:string;secondaryHref?:string;locationSearch?:boolean}){return <section className={styles.hero}><div><span className={styles.eyebrow}>🐾 {eyebrow}</span><h1>{title} <em>{accent}</em></h1><p>{description}</p>{locationSearch?<form className={styles.locationBox} action="/mobile-app"><input aria-label="Your area in Bengaluru" name="area" placeholder="Enter your area in Bengaluru"/><button>Find care</button></form>:<div className={styles.actions}><Link className={styles.primary} href={primaryHref}>{primaryLabel}</Link><Link className={styles.secondary} href={secondaryHref}>{secondaryLabel}</Link></div>}</div><div className={styles.heroVisual}>{image?<Image src={image} alt={imageAlt||badgeTitle||"PawSpace pet care"} fill sizes="(max-width: 900px) 100vw, 50vw" style={{objectFit:"cover"}} priority/>:null}{badgeTitle?<div className={styles.heroBadge}><b>{badgeTitle}</b><span>{badgeText}</span></div>:null}</div></section>}
export function ProofStrip({items=verifiedProof}:{items?:ProofItem[]}){return <section className={styles.proof}><div className={styles.proofInner}>{items.map(item=><div className={styles.proofItem} key={item.value}><b>{item.value}</b><span>{item.label}</span></div>)}</div></section>}
export function SectionHeader({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){return <div className={styles.sectionHeader}>{eyebrow?<span className={styles.eyebrow}>{eyebrow}</span>:null}<h2>{title}</h2>{description?<p>{description}</p>:null}</div>}
export function ServiceGrid({items=services}:{items?:ServiceCard[]}){return <section className={styles.section}><SectionHeader eyebrow="Complete care" title="One PawSpace relationship, multiple pet-care needs." description="Explore focused service pages, then move into the connected customer booking experience when you are ready."/><div className={styles.grid4}>{items.map(item=><article className={styles.card} key={item.title}><div className={styles.cardMedia}>{item.image?<Image src={item.image} alt={`${item.title} by PawSpace`} fill sizes="(max-width: 900px) 50vw, 25vw" style={{objectFit:"cover"}}/>:null}</div><div className={styles.cardBody}>{item.eyebrow?<small className={styles.eyebrow}>{item.eyebrow}</small>:null}<h3>{item.title}</h3><p>{item.description}</p><Link className={styles.cardLink} href={item.href}>Explore {item.title} →</Link></div></article>)}</div></section>}
export function TrustSection({image="/assets/stays/sitter-profile.webp",imageAlt="PawSpace pet care professional",title="Care should feel personal, transparent and easy to trust.",checks}:{image?:string;imageAlt?:string;title?:string;checks:{title:string;text:string}[]}){return <section className={styles.section}><div className={styles.trust}><div className={styles.trustVisual}><Image src={image} alt={imageAlt} fill sizes="(max-width: 900px) 100vw, 50vw" style={{objectFit:"cover"}}/></div><div><span className={styles.eyebrow}>Why PawSpace</span><h2>{title}</h2><div className={styles.checkList}>{checks.map(item=><div className={styles.check} key={item.title}><i>✓</i><div><b>{item.title}</b><span>{item.text}</span></div></div>)}</div></div></div></section>}
export type Testimonial={quote:string;service:string};
export const realTestimonials:Testimonial[]=[];
export function Testimonials({items=realTestimonials}:{items?:Testimonial[]}){if(!items.length)return null;return <section className={styles.section}><SectionHeader eyebrow="Real customer reviews" title="What pet parents actually say." description="Genuine excerpts from our Google reviews - not written for the website."/><div className={styles.grid3}>{items.map(item=><article className={styles.card} key={item.quote.slice(0,40)}><div className={styles.cardBody}><p style={{fontStyle:"italic"}}>&ldquo;{item.quote}&rdquo;</p><small style={{color:"var(--ps-muted)",fontWeight:800}}>— Google review · {item.service}</small></div></article>)}</div><p style={{textAlign:"center",marginTop:18,fontSize:13,color:"var(--ps-muted)"}}>See all reviews on <a href="https://www.google.com/search?q=pawspace" target="_blank" rel="noopener noreferrer" style={{color:"var(--ps-green)",fontWeight:800}}>Google</a>.</p></section>}
export function Steps({items}:{items:{title:string;text:string}[]}){return <section className={styles.section}><SectionHeader eyebrow="How it works" title="A clear journey from discovery to care."/><div className={styles.steps}>{items.map((item,i)=><article className={styles.step} key={item.title}><strong>{i+1}</strong><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>}
export function Packages({title="Choose the right care option",items}:{title?:string;items:PackageCard[]}){return <section className={styles.section}><SectionHeader eyebrow="Packages" title={title} description="Package information should stay simple, comparable and aligned to the current booking system. Final availability and price are confirmed in the booking flow."/><div className={styles.packages}>{items.map(item=><article key={item.name} className={`${styles.package} ${item.featured?styles.packageFeatured:""}`}>{item.badge?<span className={styles.packageBadge}>{item.badge}</span>:null}<h3>{item.name}</h3>{item.description?<p>{item.description}</p>:null}{item.price?<div className={styles.packagePrice}>{item.price}</div>:null}<ul>{item.items.map(x=><li key={x}>{x}</li>)}</ul><Link className={styles.primary} href={item.href||"/mobile-app"}>Continue to booking</Link></article>)}</div></section>}
export function Faqs({items}:{items:Faq[]}){return <section className={styles.section}><SectionHeader eyebrow="Questions" title="Frequently asked questions"/><div className={styles.faq}>{items.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>}
export function QuickFacts({items}:{items:{label:string;value:string}[]}){return <section style={{maxWidth:1180,margin:"18px auto 0",padding:"0 20px"}}><div className={styles.quickFacts}>{items.map(item=><div className={styles.quickFact} key={item.label}><small>{item.label}</small><b>{item.value}</b></div>)}</div></section>}
export function DidYouKnow({text}:{text:string}){return <div className={styles.didYouKnow}><span className={styles.eyebrow}>💡 Did you know?</span><p>{text}</p></div>}
function SiteCta(){return <section className={styles.cta}><div className={styles.ctaInner}><div><h2>Give your pet care that stays connected.</h2><p>Explore services, choose the right care journey and keep bookings, updates and support in one PawSpace experience.</p></div><div className={styles.actions}><Link className={styles.secondary} href="/mobile-app">Open customer app</Link><Link className={styles.secondary} href="/contact">Talk to PawSpace</Link></div></div></section>}
function Footer(){return <footer className={styles.footer}><div className={styles.footerInner}><div><div className={styles.footerBrand}>🐾 PawSpace</div><p>Pet care designed around trusted people, clear service journeys and connected customer support.</p></div><div><h3>Services</h3><Link href="/services/grooming">Grooming</Link><Link href="/services/training">Training</Link><Link href="/services/boarding">Boarding</Link><Link href="/services/sitting">Sitting</Link><Link href="/services/walking">Walking</Link></div><div><h3>Company</h3><Link href="/about">About</Link><Link href="/careers">Become a caregiver</Link><Link href="/contact">Contact</Link><Link href="/business">Business hub</Link></div><div><h3>Customer</h3><Link href="/mobile-app">Customer app</Link><Link href="/account">Account</Link><Link href="/contact">Help & support</Link><Link href="/services">All services</Link></div></div><div className={styles.copyright}>© PawSpace. All rights reserved.</div></footer>}
export function JsonLd({data}:{data:Record<string,unknown>|Record<string,unknown>[]}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
