import{authError}from"../../../lib/server-auth";
import{governedJsonError}from"../../../lib/governed-http-error";
import{assignLeadOwner}from"../../../lib/lead-owner-identity";
import{assignLead}from"../../../lib/lead-assignment-governance";
import{startLeadSlaClock}from"../../../lib/lead-sla-governance";
import{startWhatsAppAiLead}from"../../../lib/whatsapp-ai-lead-orchestration";
import{ensureLeadIntakeAdAttribution,normalizeLeadAdAttribution,recordLeadIntakeAdAttribution}from"../../../lib/lead-intake-ad-attribution";
import{ensurePublicLeadOutboundTables,planPublicLeadIdentity,publicLeadIdentityStatements}from"../../../lib/public-lead-outbound";
// Public, unauthenticated lead-capture endpoint. Staff CRM remains separately authenticated.
async function getDatabase(){const{env}=await import("cloudflare:workers");return env.DB;}
type Row=Record<string,unknown>;
const crmAttributionColumns:[string,string][]=[["city_id","TEXT"],["team_code","TEXT"],["department_code","TEXT"],["gclid","TEXT"],["fbclid","TEXT"],["wbraid","TEXT"],["gbraid","TEXT"],["utm_source","TEXT"],["utm_medium","TEXT"],["utm_campaign","TEXT"],["utm_content","TEXT"],["utm_term","TEXT"],["campaign_id","TEXT"],["ad_id","TEXT"]];
async function ensureCrmAttributionColumns(db:D1Database){const info=await db.prepare("PRAGMA table_info(crm_contacts)").all<Row>(),existing=new Set(info.results.map(row=>String(row.name||"")));for(const[column,type]of crmAttributionColumns)if(!existing.has(column))await db.prepare(`ALTER TABLE crm_contacts ADD COLUMN ${column} ${type}`).run().catch(async error=>{const current=await db.prepare("PRAGMA table_info(crm_contacts)").all<Row>();if(!current.results.some(row=>String(row.name)===column))throw error;});}
async function ensureTables(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS crm_contacts (id TEXT PRIMARY KEY, name TEXT NOT NULL, primary_phone TEXT NOT NULL, secondary_phone TEXT, email TEXT, area TEXT, pet_names TEXT, pet_summary TEXT, stage TEXT NOT NULL DEFAULT 'New lead', owner TEXT DEFAULT 'Unassigned', source TEXT DEFAULT 'Website', lifetime_value REAL DEFAULT 0, next_action TEXT, opportunity TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS crm_activities (id TEXT PRIMARY KEY, contact_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, detail TEXT, created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS crm_tasks (id TEXT PRIMARY KEY, contact_id TEXT, title TEXT NOT NULL, owner TEXT NOT NULL, due_at INTEGER, priority TEXT DEFAULT 'Normal', status TEXT DEFAULT 'Open', created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS lead_work_items (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, source TEXT NOT NULL, service TEXT NOT NULL, owner TEXT NOT NULL, manager TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', stage TEXT NOT NULL DEFAULT 'day_1', work_day INTEGER NOT NULL DEFAULT 1, assigned_at INTEGER NOT NULL, first_action_due_at INTEGER NOT NULL, manager_alert_at INTEGER NOT NULL, first_action_at INTEGER, call_attempts INTEGER NOT NULL DEFAULT 0, whatsapp_attempts INTEGER NOT NULL DEFAULT 0, last_outcome TEXT, next_action_at INTEGER, recycle_at INTEGER, recycle_cycle INTEGER NOT NULL DEFAULT 0, opt_out INTEGER NOT NULL DEFAULT 0, converted_booking_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS public_contact_rate_limits (fingerprint TEXT PRIMARY KEY, window_started_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS public_contact_submissions (request_key TEXT PRIMARY KEY,payload_hash TEXT NOT NULL,contact_id TEXT NOT NULL,lead_id TEXT NOT NULL,owner TEXT NOT NULL,response_json TEXT,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS lead_governance_exceptions (lead_id TEXT PRIMARY KEY,contact_id TEXT NOT NULL,assignment_status TEXT NOT NULL,sla_status TEXT NOT NULL,reason TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
]);await Promise.all([ensureCrmAttributionColumns(db),ensureLeadIntakeAdAttribution(db),ensurePublicLeadOutboundTables(db)]);}
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}}),RATE_WINDOW_MS=10*60*1000,RATE_LIMIT=5;
function clean(value:unknown,max:number){return String(value??"").replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").trim().slice(0,max);}
function cityForArea(area:string){const value=area.toLowerCase();if(value.includes("hyderabad"))return"hyd";if(value.includes("mumbai"))return"mum";if(value.includes("pune"))return"pnq";if(value.includes("chennai"))return"maa";return"blr";}
async function fingerprintFor(request:Request){const ip=clean(request.headers.get("cf-connecting-ip"),80);if(!ip)throw governedJsonError({error:"Request origin could not be verified"},429);const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(ip));return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,"0")).join("");}
async function enforceAbuseGate(db:D1Database,request:Request,now:number){const fingerprint=await fingerprintFor(request),cutoff=now-RATE_WINDOW_MS;await db.prepare("INSERT OR IGNORE INTO public_contact_rate_limits (fingerprint,window_started_at,attempts,updated_at) VALUES (?,?,0,?)").bind(fingerprint,now,now).run();await db.prepare("UPDATE public_contact_rate_limits SET attempts=CASE WHEN window_started_at<? THEN 1 ELSE attempts+1 END,window_started_at=CASE WHEN window_started_at<? THEN ? ELSE window_started_at END,updated_at=? WHERE fingerprint=?").bind(cutoff,cutoff,now,now,fingerprint).run();const state=await db.prepare("SELECT attempts FROM public_contact_rate_limits WHERE fingerprint=?").bind(fingerprint).first<{attempts:number}>();if(!state||Number(state.attempts)>RATE_LIMIT)throw governedJsonError({error:"Too many contact requests. Please try again later."},429);}
type ContactReceipt={payload_hash:string;contact_id:string;lead_id:string;owner:string;response_json:string|null};
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,"0")).join("");}
async function readContactReceipt(db:D1Database,key:string,payloadHash:string){const row=await db.prepare("SELECT payload_hash,contact_id,lead_id,owner,response_json FROM public_contact_submissions WHERE request_key=?").bind(key).first<ContactReceipt>();if(row&&row.payload_hash!==payloadHash)throw governedJsonError({error:"This enquiry changed after submission. Review the details before sending a new enquiry.",code:"contact_submission_conflict"},409);return row;}
function receiptResponse(row:ContactReceipt){if(!row.response_json)return null;const result=JSON.parse(row.response_json)as Record<string,unknown>;return json({...result,duplicatePrevented:true},200);}
async function outboundStatus(db:D1Database,leadId:string){const queue=await db.prepare("SELECT status FROM outbound_routing_queue WHERE lead_id=? AND source_type='public_contact' ORDER BY created_at DESC LIMIT 1").bind(leadId).first<Row>();if(queue)return String(queue.status||"queued");const review=await db.prepare("SELECT id FROM public_contact_identity_reviews WHERE lead_id=? AND status='open' LIMIT 1").bind(leadId).first<Row>();return review?"identity_review":"not_queued";}

async function reconcileCanonicalLeadGovernance(db:D1Database,input:{leadId:string;contactId:string;legacyOwner:string;requestKey:string|null;now:number}){
 const result:{assignment:string;sla:string;owner:string;reason?:string}={assignment:"legacy_fallback",sla:"not_started",owner:input.legacyOwner};
 try{
  const assigned=await assignLead(db,{leadId:input.leadId,idempotencyKey:`public-contact:assignment:${input.leadId}`,reason:"new_lead",actorId:"public-contact",preferredEmployeeEmail:input.legacyOwner&&input.legacyOwner!=="Unassigned"?input.legacyOwner:null,asOf:input.now});
  const row=assigned.assignment as Row,canonicalOwner=String(row?.employee_email||"Unassigned");
  result.assignment=canonicalOwner==="Unassigned"?"fallback_queue":"canonical";result.owner=canonicalOwner;
  await db.batch([
   db.prepare("UPDATE crm_contacts SET owner=?,updated_at=? WHERE id=?").bind(canonicalOwner,input.now,input.contactId),
   db.prepare("UPDATE crm_tasks SET owner=? WHERE contact_id=? AND title='First response to new website lead' AND status='Open'").bind(canonicalOwner,input.contactId),
   db.prepare("UPDATE outbound_routing_queue SET context_json=json_set(context_json,'$.leadOwner',?),updated_at=? WHERE lead_id=? AND source_type='public_contact'").bind(canonicalOwner,input.now,input.leadId),
  ]);
  if(input.requestKey)await db.prepare("UPDATE public_contact_submissions SET owner=? WHERE request_key=?").bind(canonicalOwner,input.requestKey).run();
  try{await startLeadSlaClock(db,{leadId:input.leadId,clockType:"first_response",idempotencyKey:`public-contact:first-response:${input.leadId}`,actorId:"public-contact",asOf:input.now});result.sla="canonical";}
  catch(error){result.sla="policy_unavailable";result.reason=error instanceof Error?error.message:String(error);}
 }catch(error){result.reason=error instanceof Error?error.message:String(error);}
 if(result.assignment!=="canonical"||result.sla!=="canonical")await db.prepare("INSERT INTO lead_governance_exceptions (lead_id,contact_id,assignment_status,sla_status,reason,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(lead_id) DO UPDATE SET assignment_status=excluded.assignment_status,sla_status=excluded.sla_status,reason=excluded.reason,updated_at=excluded.updated_at").bind(input.leadId,input.contactId,result.assignment,result.sla,result.reason||null,Date.now(),Date.now()).run().catch(()=>{});
 return result;
}

export async function POST(request:Request){try{
 const db=await getDatabase();await ensureTables(db);const now=Date.now();await enforceAbuseGate(db,request,now);const body=await request.json()as Record<string,unknown>;if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"A valid enquiry is required"},400);if(body.requestId!==undefined&&(typeof body.requestId!=="string"||!/^[-A-Za-z0-9_]{16,128}$/.test(body.requestId)))return json({error:"A valid enquiry submission reference is required"},400);
 const nested=body.attribution&&typeof body.attribution==="object"&&!Array.isArray(body.attribution)?body.attribution as Record<string,unknown>:{};const value=(camel:string,snake:string)=>body[camel]??body[snake]??nested[snake]??nested[camel];
 const name=clean(body.name,80),phone=clean(body.phone,20),email=clean(body.email,160),area=clean(body.area||"Bangalore",80),petNames=clean(body.petNames||"Not shared",160),service=clean(body.service||"General enquiry",120),message=clean(body.message||"No message left",500),cityId=cityForArea(area),teamCode="sales",departmentCode="cc-sales";if(name.length<2)return json({error:"Please enter your name"},400);const phoneDigits=phone.replace(/\D/g,"");if(phoneDigits.length<10||phoneDigits.length>15||!/^[0-9+\s-]+$/.test(phone))return json({error:"Please enter a valid phone number"},400);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"Please enter a valid email address"},400);
 const attribution=normalizeLeadAdAttribution({gclid:clean(value("gclid","gclid"),180),fbclid:clean(value("fbclid","fbclid"),180),wbraid:clean(value("wbraid","wbraid"),180),gbraid:clean(value("gbraid","gbraid"),180),utmSource:clean(value("utmSource","utm_source"),120),utmMedium:clean(value("utmMedium","utm_medium"),120),utmCampaign:clean(value("utmCampaign","utm_campaign"),180),utmContent:clean(value("utmContent","utm_content"),180),utmTerm:clean(value("utmTerm","utm_term"),180),campaignId:clean(value("campaignId","campaign_id"),180),adId:clean(value("adId","ad_id"),180),landingUrl:clean(value("landingUrl","landing_url"),500)}),requestKey=body.requestId===undefined?null:await sha256(String(body.requestId)),payloadHash=await sha256(JSON.stringify([name,phone,email,area,petNames,service,message,body.whatsappConsent===true,attribution]));
 const saved=requestKey?await readContactReceipt(db,requestKey,payloadHash):null;if(saved){const replay=receiptResponse(saved);if(replay)return replay;}
 let id=saved?.contact_id??"",leadId=saved?.lead_id??`LEAD-${crypto.randomUUID()}`,assignedOwner=saved?.owner??"Unassigned",duplicatePrevented=Boolean(saved);const activityId=`ACT-${crypto.randomUUID()}`,taskId=`TASK-${crypto.randomUUID()}`,source=attribution.hasAttribution?`Website contact form / ${attribution.sourcePlatform}`:"Website contact form";
 if(!saved){const proposedId=`CU-${crypto.randomUUID()}`,identity=await planPublicLeadIdentity(db,{proposedCustomerId:proposedId,phone});id=identity.customerId;const ownership=await assignLeadOwner(db,{customerId:id,leadId,service,recordException:false,scope:{serviceCode:service,cityId,teamCode}});assignedOwner=ownership.owner;const activityDetail=JSON.stringify({serviceInterest:service,organizationalScope:{cityId,teamCode,departmentCode},adAttribution:attribution.hasAttribution?{gclid:attribution.gclid,fbclid:attribution.fbclid,wbraid:attribution.wbraid,gbraid:attribution.gbraid,utmSource:attribution.utmSource,utmMedium:attribution.utmMedium,utmCampaign:attribution.utmCampaign,utmContent:attribution.utmContent,utmTerm:attribution.utmTerm,campaignId:attribution.campaignId,adId:attribution.adId}:null});const statements:D1PreparedStatement[]=[
  db.prepare("INSERT INTO crm_contacts (id,name,primary_phone,secondary_phone,email,area,pet_names,pet_summary,stage,owner,source,lifetime_value,next_action,opportunity,city_id,team_code,department_code,gclid,fbclid,wbraid,gbraid,utm_source,utm_medium,utm_campaign,utm_content,utm_term,campaign_id,ad_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,primary_phone=excluded.primary_phone,email=COALESCE(excluded.email,crm_contacts.email),area=excluded.area,pet_names=excluded.pet_names,pet_summary=excluded.pet_summary,owner=excluded.owner,source=excluded.source,next_action=excluded.next_action,opportunity=excluded.opportunity,city_id=excluded.city_id,team_code=excluded.team_code,department_code=excluded.department_code,gclid=excluded.gclid,fbclid=excluded.fbclid,wbraid=excluded.wbraid,gbraid=excluded.gbraid,utm_source=excluded.utm_source,utm_medium=excluded.utm_medium,utm_campaign=excluded.utm_campaign,utm_content=excluded.utm_content,utm_term=excluded.utm_term,campaign_id=excluded.campaign_id,ad_id=excluded.ad_id,updated_at=excluded.updated_at").bind(id,name,phone,null,email||null,area,petNames,message,"New lead",assignedOwner,source,0,"Call within 10 minutes",service,cityId,teamCode,departmentCode,attribution.gclid,attribution.fbclid,attribution.wbraid,attribution.gbraid,attribution.utmSource,attribution.utmMedium,attribution.utmCampaign,attribution.utmContent,attribution.utmTerm,attribution.campaignId,attribution.adId,now,now),
  db.prepare("INSERT INTO crm_activities (id,contact_id,type,title,detail,created_at) VALUES (?,?,?,?,?,?)").bind(activityId,id,"lead_created","Contact form submission",activityDetail,now),
  db.prepare("INSERT INTO crm_tasks (id,contact_id,title,owner,due_at,priority,status,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(taskId,id,"First response to new website lead",assignedOwner,now+10*60*1000,"High","Open",now),
  db.prepare("INSERT INTO lead_work_items (id,customer_id,source,service,owner,manager,status,stage,work_day,assigned_at,first_action_due_at,manager_alert_at,call_attempts,whatsapp_attempts,next_action_at,recycle_cycle,opt_out,created_at,updated_at) VALUES (?,?,?,?,?,?,'active','day_1',1,?,?,?,0,0,?,0,0,?,?)").bind(leadId,id,source,service,assignedOwner,"Sales Manager",now,now+10*60000,now+30*60000,now,now,now),
 ];if(attribution.hasAttribution)statements.push(db.prepare("INSERT INTO lead_intake_ad_attribution (id,contact_id,lead_id,source_platform,gclid,fbclid,wbraid,gbraid,click_id,utm_source,utm_medium,utm_campaign,utm_content,utm_term,campaign_id,ad_id,landing_url,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(`ATTR-${crypto.randomUUID().slice(0,12).toUpperCase()}`,id,leadId,attribution.sourcePlatform,attribution.gclid,attribution.fbclid,attribution.wbraid,attribution.gbraid,attribution.clickId,attribution.utmSource,attribution.utmMedium,attribution.utmCampaign,attribution.utmContent,attribution.utmTerm,attribution.campaignId,attribution.adId,attribution.landingUrl,JSON.stringify({capturedAtIntake:true,origin:"public_contact"}),now,now));if(!ownership.resolved)statements.push(db.prepare("INSERT INTO lead_owner_mapping_exceptions (id,scope,customer_id,lead_id,requested_owner,reason,resolved_at,resolved_by,created_at) VALUES (?,?,?,?,NULL,?,NULL,NULL,?)").bind(`LOE-${crypto.randomUUID()}`,"assignment_at_creation",id,leadId,"No active lead-assignment member could be resolved for this lead",now));statements.push(...publicLeadIdentityStatements(db,{plan:identity,contactId:id,leadId,name,phone,email:email||null,cityId,owner:assignedOwner,service,whatsappConsent:body.whatsappConsent===true,now}).statements);if(requestKey)statements.unshift(db.prepare("INSERT INTO public_contact_submissions (request_key,payload_hash,contact_id,lead_id,owner,response_json,created_at) VALUES (?,?,?,?,?,NULL,?)").bind(requestKey,payloadHash,id,leadId,assignedOwner,now));try{await db.batch(statements);}catch(error){const concurrent=requestKey?await readContactReceipt(db,requestKey,payloadHash):null;if(!concurrent)throw error;const replay=receiptResponse(concurrent);if(replay)return replay;id=concurrent.contact_id;leadId=concurrent.lead_id;assignedOwner=concurrent.owner;duplicatePrevented=true;}}
 let whatsappAi:Record<string,unknown>;try{whatsappAi=await startWhatsAppAiLead(db,{leadId,contactId:id,idempotencyKey:`lead-created:${leadId}`,consentGranted:body.whatsappConsent===true,consentSource:"website_contact_checkbox",consentEvidenceRef:body.whatsappConsent===true?"public-contact-whatsapp-consent-v1":"",actorId:"public-contact",assignedTo:assignedOwner,cityId});}catch{whatsappAi={status:"failed",reason:"internal_automation_error",externalDelivery:false,marketing:false};}
 if(attribution.hasAttribution){try{await recordLeadIntakeAdAttribution(db,{contactId:id,leadId,threadId:clean(whatsappAi.thread_id,120)||null,origin:"public_contact",gclid:attribution.gclid,fbclid:attribution.fbclid,wbraid:attribution.wbraid,gbraid:attribution.gbraid,utmSource:attribution.utmSource,utmMedium:attribution.utmMedium,utmCampaign:attribution.utmCampaign,utmContent:attribution.utmContent,utmTerm:attribution.utmTerm,campaignId:attribution.campaignId,adId:attribution.adId,landingUrl:attribution.landingUrl,now});}catch(error){await db.prepare("INSERT INTO crm_activities (id,contact_id,type,title,detail,created_at) VALUES (?,?,?,?,?,?)").bind(`ACT-${crypto.randomUUID()}`,id,"attribution_mirror_failed","Ad attribution downstream mirror failed",clean(error instanceof Error?error.message:String(error),400),Date.now()).run().catch(()=>{});}}
 const governance=await reconcileCanonicalLeadGovernance(db,{leadId,contactId:id,legacyOwner:assignedOwner,requestKey,now});assignedOwner=governance.owner;
 const result={ok:true,leadId,attributionBound:attribution.hasAttribution,attributionType:attribution.sourcePlatform,organizationalScope:{cityId,teamCode,departmentCode},governance,outbound:{status:await outboundStatus(db,leadId),owner:assignedOwner},whatsappAi:{status:whatsappAi.status,reason:whatsappAi.reason}};if(requestKey&&whatsappAi.status!=="processing"&&whatsappAi.status!=="failed")await db.prepare("UPDATE public_contact_submissions SET response_json=? WHERE request_key=? AND payload_hash=? AND response_json IS NULL").bind(JSON.stringify(result),requestKey,payloadHash).run();return json({...result,duplicatePrevented},duplicatePrevented?200:201);
}catch(error){return authError(error,"Unable to submit your enquiry - please try again");}}
