import{authError,database,requireCustomerOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{createFoodOrder,ensureFoodGovernanceTables}from"../../../lib/food-governance";
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
/* A booking may FILL a saved contact field; it may NEVER blank one.
 * No booking client sends `email`, and step 4's "Alternative Phone Number" posts "" when the customer
 * leaves it alone, so both absent spellings are normalised to NULL HERE - at the binding site, once,
 * for every statement in the batch - and the COALESCE in the conflict clause reads that NULL as "keep
 * what is stored". Normalising at the bind rather than in SQL also keeps "" out of the FIRST insert,
 * so a stored contact is either real or NULL and never an empty string a later COALESCE cannot tell
 * from a real one. A booking that DOES carry a contact still lands: it is not NULL, so COALESCE takes it. */
const optionalContact=(value:unknown):string|null=>{const text=typeof value==="string"?value.trim():"";return text.length?text:null};
function sameOriginWrite(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin Food order blocked",{status:403})}
export async function POST(request:Request){try{sameOriginWrite(request);const body=await request.json() as {idempotencyKey?:string;quoteId?:string;customer?:{id?:string;name?:string;primaryPhone?:string;secondaryPhone?:string;email?:string};cityId?:string;zoneId?:string},idempotencyKey=String(body.idempotencyKey||"").trim(),quoteId=String(body.quoteId||"").trim(),customerId=String(body.customer?.id||"").trim(),cityId=String(body.cityId||"blr"),zoneId=String(body.zoneId||"blr-east");if(!idempotencyKey||!quoteId||!customerId||!body.customer?.name||!body.customer?.primaryPhone)return json({error:"Food quote, request identity and customer identity are required"},400);const db=await database(),actor=await resolveActor(request);await requireCustomerOwnership(db,actor,customerId);await ensureFoodGovernanceTables(db);const now=Date.now();await db.prepare("CREATE TABLE IF NOT EXISTS canonical_customers (id TEXT PRIMARY KEY,city_id TEXT NOT NULL,name TEXT NOT NULL,primary_phone TEXT NOT NULL,secondary_phone TEXT,email TEXT,source TEXT NOT NULL DEFAULT 'uat_customer_app',consent_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)").run();await db.prepare("INSERT INTO canonical_customers (id,city_id,name,primary_phone,secondary_phone,email,source,consent_json,created_at,updated_at) VALUES (?,?,?,?,?,?, 'uat_customer_app',?, ?,?) ON CONFLICT(id) DO UPDATE SET city_id=excluded.city_id,name=excluded.name,primary_phone=excluded.primary_phone,secondary_phone=COALESCE(excluded.secondary_phone,canonical_customers.secondary_phone),email=COALESCE(excluded.email,canonical_customers.email),updated_at=excluded.updated_at").bind(customerId,cityId,body.customer.name,body.customer.primaryPhone,optionalContact(body.customer.secondaryPhone),optionalContact(body.customer.email),JSON.stringify({serviceUpdates:true,marketing:false}),now,now).run();const result=await createFoodOrder(db,{idempotencyKey,quoteId,customerId,cityId,zoneId,actorId:actor.email});await securityAudit(db,actor,"food.order.create","food_order",String(result.orderId),"completed",{quoteId,inventoryMode:result.inventoryMode,productionInventoryVerified:false,liveMoney:false,duplicatePrevented:Boolean(result.duplicatePrevented)});return json({data:result},result.duplicatePrevented?200:201)}catch(error){return authError(error,"Unable to create canonical Food order")}}
