import assert from "node:assert/strict";
import { test } from "node:test";
import { defaultPreference, enrollJourney, requestOtp, runDueJourneys, runJourney, verifyOtp } from "../src/crm-automation.js";
import { MemoryRepository } from "../src/repository.js";

test("OTP is hashed, single-use and rate limited",async()=>{const repository=new MemoryRepository();(process.env as Record<string,string>).NODE_ENV="test";const requested=await requestOtp(repository,"+91 98765 43418","booking_confirmation");assert.equal(requested.developmentCode?.length,6);assert.ok(!JSON.stringify(repository.otpChallenges).includes(requested.developmentCode!));const verified=await verifyOtp(repository,requested.challengeId,requested.developmentCode!);assert.equal(verified.verified,true);await assert.rejects(()=>verifyOtp(repository,requested.challengeId,requested.developmentCode!),/already used/);await requestOtp(repository,"+91 98765 43418","login");await requestOtp(repository,"+91 98765 43418","login");await assert.rejects(()=>requestOtp(repository,"+91 98765 43418","login"),/Too many OTP requests/);});

test("15-day reminder remains active and schedules the next run",async()=>{const repository=new MemoryRepository();await repository.upsertCommunicationPreference(defaultPreference("cus_10428"));const enrollment=await enrollJourney(repository,{customerId:"cus_10428",journeyCode:"care_15_day",nextRunAt:"2026-08-04T00:00:00.000Z"});const result=await runJourney(repository,enrollment,"2026-08-04T00:00:00.000Z");assert.equal(result.status,"queued");assert.equal(repository.notifications[0]?.templateCode,"care_due_15_day");assert.equal(repository.enrollments[0]?.status,"active");assert.equal(repository.enrollments[0]?.nextRunAt,"2026-08-19T00:00:00.000Z");});

test("marketing journey is suppressed when customer has not consented",async()=>{const repository=new MemoryRepository();await repository.upsertCommunicationPreference(defaultPreference("cus_10428"));const enrollment=await enrollJourney(repository,{customerId:"cus_10428",journeyCode:"app_adoption",nextRunAt:"2026-08-04T00:00:00.000Z"});const result=await runJourney(repository,enrollment,"2026-08-04T00:00:00.000Z");assert.equal(result.status,"suppressed");assert.equal(repository.notifications.length,0);});

test("service recovery opens a 30-minute SLA ticket",async()=>{const repository=new MemoryRepository();await enrollJourney(repository,{customerId:"cus_10428",journeyCode:"service_recovery",nextRunAt:"2026-08-04T00:00:00.000Z",metadata:{bookingId:"book_1",summary:"Provider waiting for 30 minutes"}});const run=await runDueJourneys(repository,"2026-08-04T00:00:00.000Z");assert.equal(run.evaluated,1);assert.ok(run.results[0]?.ticketId);assert.equal(repository.tickets[0]?.priority,"high");assert.equal(repository.tickets[0]?.slaDueAt,"2026-08-04T00:30:00.000Z");});
