import assert from "node:assert/strict";
import { test } from "node:test";
import type { Booking, CommunicationPreference } from "../src/domain.js";
import { evaluateCommunicationPolicy, Lane3Error, LocationTracker, runAiAssistant, ServiceProofStore, voiceSafetyState } from "../src/lane3.js";

const booking=(providerId="provider_1"):Booking=>({id:"booking_1",legacyIds:[],idempotencyKey:"booking_key",cityId:"blr",zoneId:"hsr",customerId:"customer_1",petIds:["pet_1"],serviceCode:"grooming",packageCode:"routine",addonCodes:[],scheduledStart:"2026-08-23T10:00:00.000Z",scheduledEnd:"2026-08-23T12:00:00.000Z",status:"assigned",channel:"customer_app",totalAmount:1149,providerId,createdBy:"customer_1",createdAt:"2026-08-23T09:00:00.000Z",updatedAt:"2026-08-23T09:00:00.000Z"});
const at=new Date("2026-08-23T10:05:00.000Z");
const assertCode=(fn:()=>unknown,code:string)=>assert.throws(fn,(error:unknown)=>error instanceof Lane3Error&&error.code===code);

test("GPS accepts only fresh valid coordinates from the assigned provider and dedupes retries",()=>{const tracker=new LocationTracker();const input={bookingId:"booking_1",providerId:"provider_1",latitude:12.9121,longitude:77.6446,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"loc_1",permissionGranted:true};const first=tracker.update(booking(),input,at);const retry=tracker.update(booking(),input,at);assert.deepEqual(retry,first);const view=tracker.customerView(booking(),false,at);assert.equal(view.available,true);assert.equal(view.trackingReady,false);assert.equal(view.reason,"MAPS_NOT_CONFIGURED");});

test("GPS rejects wrong provider invalid coordinates stale location denied permission and idempotency conflict",()=>{const tracker=new LocationTracker();assertCode(()=>tracker.update(booking(),{bookingId:"booking_1",providerId:"provider_2",latitude:12,longitude:77,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"wrong"},at),"PROVIDER_NOT_ASSIGNED");assertCode(()=>tracker.update(booking(),{bookingId:"booking_1",providerId:"provider_1",latitude:91,longitude:77,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"bad"},at),"INVALID_COORDINATES");assertCode(()=>tracker.update(booking(),{bookingId:"booking_1",providerId:"provider_1",latitude:12,longitude:77,capturedAt:"2026-08-23T09:40:00.000Z",idempotencyKey:"stale"},at),"STALE_LOCATION");assertCode(()=>tracker.update(booking(),{bookingId:"booking_1",providerId:"provider_1",latitude:12,longitude:77,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"denied",permissionGranted:false},at),"LOCATION_PERMISSION_DENIED");const valid={bookingId:"booking_1",providerId:"provider_1",latitude:12,longitude:77,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"same"};tracker.update(booking(),valid,at);assertCode(()=>tracker.update(booking(),{...valid,longitude:78},at),"IDEMPOTENCY_CONFLICT");});

test("GPS provider switching invalidates the old provider and accepts the newly assigned provider",()=>{const tracker=new LocationTracker();tracker.update(booking("provider_1"),{bookingId:"booking_1",providerId:"provider_1",latitude:12,longitude:77,capturedAt:"2026-08-23T10:03:00.000Z",idempotencyKey:"before_switch"},at);const switched=booking("provider_2");assert.equal(tracker.customerView(switched,true,at).available,false);assertCode(()=>tracker.update(switched,{bookingId:"booking_1",providerId:"provider_1",latitude:12,longitude:77,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"old_provider"},at),"PROVIDER_NOT_ASSIGNED");const current=tracker.update(switched,{bookingId:"booking_1",providerId:"provider_2",latitude:12.1,longitude:77.1,capturedAt:"2026-08-23T10:04:00.000Z",idempotencyKey:"new_provider"},at);assert.equal(current.providerId,"provider_2");});

test("media proof fails closed without storage and rejects wrong provider or invalid object references",()=>{const unavailable=new ServiceProofStore(false);assertCode(()=>unavailable.submit(booking(),{providerId:"provider_1",kind:"before",objectRef:"media://proof/before.jpg",idempotencyKey:"proof_1"},at),"MEDIA_STORAGE_NOT_CONFIGURED");const store=new ServiceProofStore(true);assertCode(()=>store.submit(booking(),{providerId:"provider_2",kind:"before",objectRef:"media://proof/before.jpg",idempotencyKey:"proof_2"},at),"PROOF_PROVIDER_MISMATCH");assertCode(()=>store.submit(booking(),{providerId:"provider_1",kind:"before",objectRef:"javascript:alert(1)",idempotencyKey:"proof_3"},at),"INVALID_OBJECT_REF");assert.equal(store.completionState("booking_1").completionAllowed,false);});

test("media proof dedupes retries and completion remains closed until every mandatory proof exists",()=>{const store=new ServiceProofStore(true);const before=store.submit(booking(),{providerId:"provider_1",kind:"before",objectRef:"media://proof/before.jpg",idempotencyKey:"proof_before"},at);assert.equal(store.submit(booking(),{providerId:"provider_1",kind:"before",objectRef:"media://proof/before.jpg",idempotencyKey:"proof_before"},at).id,before.id);assert.deepEqual(store.completionState("booking_1"),{completionAllowed:false,missingProof:["after"]});store.submit(booking(),{providerId:"provider_1",kind:"after",objectRef:"media://proof/after.jpg",idempotencyKey:"proof_after"},at);assert.deepEqual(store.completionState("booking_1"),{completionAllowed:true,missingProof:[]});});

const preference:CommunicationPreference={customerId:"customer_1",serviceUpdates:true,reminders:true,marketing:false,channels:["whatsapp","sms","email"],quietHoursStart:"22:00",quietHoursEnd:"07:00",reminderCadence:"every_15_days",updatedAt:"2026-08-23T00:00:00.000Z"};
test("communications enforce consent opt-out quiet hours and frequency caps",()=>{assert.deepEqual(evaluateCommunicationPolicy({preference,channel:"whatsapp",purpose:"marketing",at:new Date("2026-08-23T12:00:00.000Z"),sentInLast24Hours:0}),{allowed:false,reason:"MARKETING_OPTED_OUT"});assert.deepEqual(evaluateCommunicationPolicy({preference:{...preference,channels:["email"]},channel:"sms",purpose:"service",at:new Date("2026-08-23T12:00:00.000Z"),sentInLast24Hours:0}),{allowed:false,reason:"CHANNEL_OPTED_OUT"});assert.deepEqual(evaluateCommunicationPolicy({preference,channel:"email",purpose:"service",at:new Date("2026-08-23T23:00:00.000Z"),sentInLast24Hours:0}),{allowed:false,reason:"QUIET_HOURS"});assert.deepEqual(evaluateCommunicationPolicy({preference,channel:"email",purpose:"service",at:new Date("2026-08-23T12:00:00.000Z"),sentInLast24Hours:3}),{allowed:false,reason:"FREQUENCY_CAP"});assert.deepEqual(evaluateCommunicationPolicy({preference,channel:"email",purpose:"service",at:new Date("2026-08-23T12:00:00.000Z"),sentInLast24Hours:1}),{allowed:true,reason:"ALLOWED"});});

test("AI fails closed for missing provider malformed empty timeout and tool failure",async()=>{assert.equal((await runAiAssistant({configured:false,action:"answer",prompt:"help"})).reason,"AI_NOT_CONFIGURED");assert.equal((await runAiAssistant({configured:true,action:"answer",prompt:"help"},async()=>({bad:true}))).reason,"AI_MALFORMED_RESPONSE");assert.equal((await runAiAssistant({configured:true,action:"answer",prompt:"help"},async()=>({text:"   "}))).reason,"AI_EMPTY_RESPONSE");assert.equal((await runAiAssistant({configured:true,action:"answer",prompt:"help",timeoutMs:5},async()=>new Promise(resolve=>setTimeout(()=>resolve({text:"late"}),30)))).reason,"AI_TIMEOUT");assert.equal((await runAiAssistant({configured:true,action:"answer",prompt:"help"},async()=>{throw new Error("tool failed");})).reason,"AI_TOOL_OR_PROVIDER_FAILURE");});

test("AI high-impact actions always require human approval and emit an audit trace",async()=>{for(const action of ["refund","payment","payout","pricing_change","outbound_contact","customer_merge","provider_assignment","campaign_activation"] as const){const result=await runAiAssistant({configured:true,action,prompt:"do it"},async()=>({text:"proposed action"}));assert.equal(result.status,"ok");assert.equal(result.humanApprovalRequired,true);assert.equal(result.canExecute,false);assert.match(result.auditTraceId,/^ai_[a-f0-9]{16}$/);}});

test("voice is disabled safely by default and cannot dial without provider configuration",()=>{assert.deepEqual(voiceSafetyState({NODE_ENV:"test"}),{enabled:false,configured:false,safe:true,canDial:false,reason:"VOICE_DISABLED"});assert.deepEqual(voiceSafetyState({NODE_ENV:"test",VOICE_TELEPHONY_ENABLED:"true"}),{enabled:true,configured:false,safe:true,canDial:false,reason:"VOICE_PROVIDER_NOT_CONFIGURED"});assert.deepEqual(voiceSafetyState({NODE_ENV:"test",VOICE_TELEPHONY_ENABLED:"true",VOICE_PROVIDER_API_KEY:"test-key"}),{enabled:true,configured:true,safe:true,canDial:true,reason:"CONTROLLED_TEST_ONLY"});});
