"use client";
/* eslint-disable @next/next/no-img-element */
import Link from"next/link";import{FormEvent,useEffect,useMemo,useRef,useState}from"react";import styles from"./crm.module.css";import TestSyncPanel from"../components/test-sync-panel";import CriticalErrorBoundary from"../components/critical-error-boundary";import RevenueEnginePanel from"./revenue-engine-panel";import LiveChatPanel from"./live-chat-panel";
import TrainingBookingLink from "./training-booking-link";
import{apiRequest}from"../../lib/api-fetch";
import StaffModule from "../components/staff-workspace/StaffModule";
type View="customers"|"revenue"|"chat";
type Contact={id:string;name:string;initials:string;phone:string;secondary:string;area:string;pets:string;petMeta:string;stage:string;owner:string;source:string;lifetime:number|null;lifetimeBasis:string;latestBookingId:string|null;next:string;opportunity:string};
const nav:{id:View;label:string;icon:string}[]=[{id:"customers",label:"Customers & pets",icon:"◉"},{id:"revenue",label:"Revenue & CX engine",icon:"₹"},{id:"chat",label:"WhatsApp Live Chat",icon:"💬"}];
function toContact(row:Record<string,unknown>):Contact{return{id:String(row.id),name:String(row.name),initials:String(row.name).split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase(),phone:String(row.primary_phone),secondary:row.secondary_phone?String(row.secondary_phone):"Not added",area:row.area?String(row.area):"Bengaluru",pets:row.pet_names?String(row.pet_names):"Pet",petMeta:row.pet_summary?String(row.pet_summary):"Profile to complete",stage:row.stage?String(row.stage):"New lead",owner:row.owner?String(row.owner):"Unassigned",source:row.source?String(row.source):"Website",lifetime:row.lifetime_value==null?null:Number(row.lifetime_value),lifetimeBasis:String(row.lifetime_value_basis||"unavailable"),latestBookingId:row.latest_booking_id?String(row.latest_booking_id):null,next:row.next_action?String(row.next_action):"Call within 10 minutes",opportunity:row.opportunity?String(row.opportunity):"Discover requirement"}}
export default function CrmPage(){const[view,setView]=useState<View>("customers");const[contacts,setContacts]=useState<Contact[]>([]);const[selectedId,setSelectedId]=useState("");const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState("");const[search,setSearch]=useState("");const[query,setQuery]=useState("");const[segment,setSegment]=useState("All customers");const[modal,setModal]=useState(false);const[leadSaving,setLeadSaving]=useState(false);const[leadError,setLeadError]=useState("");const leadLock=useRef(false);const[toast,setToast]=useState("");const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2300)};
/* The list is capped at 100 by updated_at, so filtering the fetched array could never find a lead
 * outside that page - the reported "lead not found in CRM". The typed query now goes to the server,
 * which searches the whole table; the client filter below still runs, so segment narrowing and
 * instant feedback on the loaded rows are unchanged. Debounced so typing is not a request per key. */
useEffect(()=>{const id=setTimeout(()=>setQuery(search.trim()),250);return ()=>clearTimeout(id)},[search]);
useEffect(()=>{let active=true;apiRequest(`/api/crm${query?`?search=${encodeURIComponent(query)}`:""}`,{cache:"no-store"},{timeoutMs:15000}).then(r=>{const body=(r.body||{}) as {contacts?:Array<Record<string,unknown>>;error?:string};if(!r.ok)throw new Error(body.error||"CRM records could not load - check your access");return body.contacts||[]}).then(rows=>{if(!active)return;const saved=rows.map(toContact);setContacts(saved);setSelectedId(current=>current||saved[0]?.id||"");setLoadError("")}).catch(e=>{if(active)setLoadError(e instanceof Error?e.message:"CRM records could not load")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query]);
/* The rows the API returns carry masked names and phones ("U•• S• L• R•", "+91 ••••••0556"), so
 * re-filtering them against what the operator typed matched nothing and the list read "0 shown"
 * for a contact the server had just found. Once the debounced query has reached the server, its
 * result set IS the search result; only the segment narrowing still applies here. */
const filtered=useMemo(()=>contacts.filter(c=>{const q=search.trim().toLowerCase();const serverSearched=query.trim().toLowerCase()===q;const hit=!q||serverSearched||`${c.name} ${c.phone} ${c.pets} ${c.id}`.toLowerCase().includes(q);const seg=segment==="All customers"||(segment==="Follow-up due"&&c.stage==="Follow-up")||(segment==="High value"&&(c.lifetime??0)>20000)||(segment==="At risk"&&c.stage==="At risk");return hit&&seg}),[contacts,search,query,segment]);
const selected=useMemo(()=>contacts.find(c=>c.id===selectedId)||filtered[0]||contacts[0]||null,[contacts,filtered,selectedId]);
async function addLead(e:FormEvent<HTMLFormElement>){e.preventDefault();if(leadLock.current)return;leadLock.current=true;setLeadSaving(true);setLeadError("");try{const fd=new FormData(e.currentTarget);const body={name:String(fd.get("name")),primaryPhone:String(fd.get("phone")),petNames:String(fd.get("pet")),service:String(fd.get("service")),source:"Manual CRM",stage:"New lead",whatsappConsent:fd.get("whatsappConsent")==="yes",whatsappConsentSource:"staff_recorded_customer_request",whatsappConsentEvidence:String(fd.get("whatsappConsentEvidence")||"")};let id:string,assignedOwner:string,automationStatus:string;try{const res=await apiRequest("/api/crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)},{timeoutMs:20000});const data=(res.body||{}) as {id?:string;assignedOwner?:string;whatsappAi?:{status?:string};error?:string};if(!res.ok||!data.id){setLeadError(data.error||"The save was not confirmed. Search CRM before retrying to avoid a duplicate.");return;}id=data.id;assignedOwner=data.assignedOwner||"Unassigned";automationStatus=String(data.whatsappAi?.status||"blocked");}catch{setLeadError("The response was not confirmed. The lead may already be saved. Search CRM before retrying to avoid a duplicate.");return;}const c:Contact={id,name:body.name,initials:body.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase(),phone:body.primaryPhone,secondary:"Not added",area:"Bengaluru",pets:body.petNames,petMeta:"Profile to complete",stage:"New lead",owner:assignedOwner,source:"Manual CRM",lifetime:0,lifetimeBasis:"no_recognized_bookings",latestBookingId:null,next:"Call within 10 minutes",opportunity:body.service};setContacts(x=>[c,...x]);setSelectedId(id);setModal(false);setView("customers");notify(automationStatus==="queued"?"Lead saved and WhatsApp AI response queued":"Lead saved; staff follow-up remains active")}finally{leadLock.current=false;setLeadSaving(false);}}
const title=nav.find(n=>n.id===view)?.label;
return <StaffModule><main className={styles.shell}><div style={{gridColumn:"1 / -1",padding:"8px 16px",background:"var(--staff-warning-bg, #fff4d9)",fontSize:13}}>Legacy CRM screen. Lifetime value here is computed from recognised bookings, the same rule Customer 360 uses, so the two screens always agree. <Link href="/team/sales" style={{fontWeight:700}}>Open Team Sales</Link> for the canonical Customer 360 + Revenue Intelligence version.</div><details data-staff-context="true"><summary>CRM views and status</summary><aside className={styles.sidebar}><Link href="/admin" className={styles.brand}><img src="/assets/pawspace-logo.jpeg" alt="PawSpace"/><span>CRM</span></Link><div className={styles.workspace}><span>PAWSPACE WORKSPACE</span><strong>Bangalore Operations</strong></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?styles.active:""} onClick={()=>setView(n.id)}><i>{n.icon}</i><span>{n.label}</span></button>)}</nav><div className={styles.integrations}><span>TEST SYSTEMS · PRODUCTION READY: NO</span><p><i></i> Customer records: persistent CRM database</p><p><i></i> Revenue engine: persistent UAT records</p><p className={styles.pending}><i></i> Live delivery integrations · locked</p></div></aside></details><section className={styles.main}><header><div><p>PAWSPACE CUSTOMER OPERATING SYSTEM</p><h1>{title}</h1></div><div><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, phone or pet"/></label><button onClick={()=>setModal(true)}>＋ Add lead</button></div></header><TestSyncPanel surface="crm" />
{view==="revenue"&&<CriticalErrorBoundary name="CRM revenue table" resetHref="/crm"><RevenueEnginePanel notify={notify}/></CriticalErrorBoundary>}
{view==="chat"&&<CriticalErrorBoundary name="CRM live chat table" resetHref="/crm"><LiveChatPanel notify={notify}/></CriticalErrorBoundary>}
{view==="customers"&&<section className={styles.customerLayout}><div className={styles.customerList}><div className={styles.customerTools}><select value={segment} onChange={e=>setSegment(e.target.value)}><option>All customers</option><option>Follow-up due</option><option>High value</option><option>At risk</option></select><span>{filtered.length} shown</span></div>{loadError&&<p role="alert" style={{padding:14,color:"var(--staff-danger, #8c2f22)"}}>{loadError}</p>}{loading&&!loadError&&<p style={{padding:14}}>Loading CRM records…</p>}{!loading&&!loadError&&contacts.length===0&&<p style={{padding:14}}>No CRM contacts yet. Use “Add lead” to create the first record.</p>}{filtered.length>0&&<div className={styles.customerHead}><span>Customer</span><span>Relationship</span><span>Next best action</span></div>}<CriticalErrorBoundary name="CRM customer table" resetHref="/crm"><CustomerRows contacts={filtered} selectedId={selected?.id||""} onSelect={setSelectedId}/></CriticalErrorBoundary></div><aside className={styles.customer360}>{!selected?<p style={{padding:16}}>Select a customer to see the record.</p>:<><div className={styles.profileHead}><span>{selected.initials}</span><div><small>{selected.id}</small><h2>{selected.name}</h2><p>{selected.phone} · {selected.area}</p></div></div><div className={styles.overview}><div className={styles.petCard}><span>🐾</span><div><small>REGISTERED PETS</small><strong>{selected.pets}</strong><p>{selected.petMeta}</p></div></div><dl><div><dt>Primary number</dt><dd>{selected.phone}</dd></div><div><dt>Secondary</dt><dd>{selected.secondary}</dd></div><div><dt>Lead source</dt><dd>{selected.source}</dd></div><div><dt>Relationship owner</dt><dd>{selected.owner}</dd></div><div><dt>Stage</dt><dd>{selected.stage}</dd></div><div><dt>Lifetime value</dt><dd>{selected.lifetime==null?"Unavailable":`₹${selected.lifetime.toLocaleString("en-IN")}`}<br/><small style={{color:"var(--staff-muted, #746b7d)"}}>{selected.lifetimeBasis==="recognized_bookings"?"From recognised bookings":selected.lifetimeBasis==="unavailable"?"Bookings could not be read":"No recognised booking yet"}</small></dd></div><div><dt>Latest booking</dt><dd>{selected.latestBookingId||"No canonical booking yet"}</dd></div></dl></div><div className={styles.nextBar}><div><span>NEXT ACTION</span><strong>{selected.next}</strong></div><div style={{display:"flex",gap:12,alignItems:"center"}}><Link href={`/assisted-booking?customerId=${encodeURIComponent(selected.id)}`} style={{fontWeight:800,fontSize:13}}>Book this customer →</Link>{/training/i.test(selected.opportunity)&&<TrainingBookingLink name={selected.name} phone={selected.phone}/>}<Link href="/team/sales" style={{fontWeight:700,fontSize:13}}>Open canonical 360 →</Link></div></div></>}</aside></section>}
</section>{modal&&<div className={styles.modalBack}><form className={styles.modal} onSubmit={addLead}><button type="button" onClick={()=>setModal(false)}>×</button><span>NEW CRM LEAD</span><h2>Create customer opportunity</h2><label>Customer name<input name="name" required minLength={2} maxLength={80} placeholder="Full name"/></label><label>Primary mobile<input name="phone" type="tel" required inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10} placeholder="10-digit number"/></label><label>Pet name<input name="pet" required placeholder="Pet name"/></label><label>Interested service<select name="service"><option>Grooming</option><option>Dog Training</option><option>Boarding</option><option>Pet Sitting</option><option>Fresh Food</option><option>Pet Taxi</option><option>Dog Walking</option><option>Relocation</option></select></label><label style={{display:"flex",gap:8,alignItems:"flex-start"}}><input name="whatsappConsent" value="yes" type="checkbox"/> Customer explicitly requested a WhatsApp response for this enquiry.</label><label>Consent evidence/reference<input name="whatsappConsentEvidence" placeholder="Call ID, message ID or written note reference"/></label>{leadError&&<p role="alert">{leadError}</p>}<button type="submit" disabled={leadSaving}>{leadSaving?"Saving lead...":"Save lead & create follow-up"}</button><small>WhatsApp starts only with explicit evidence and an approved template. Otherwise the staff task remains active.</small></form></div>}{toast&&<div className={styles.toast}>✓ {toast}</div>}</main></StaffModule>}

function CustomerRows({contacts,selectedId,onSelect}:{contacts:Contact[];selectedId:string;onSelect:(id:string)=>void}){return <>{contacts.map(c=><button key={c.id} className={selectedId===c.id?styles.selectedCustomer:""} onClick={()=>onSelect(c.id)}><div className={styles.identity}><i>{c.initials}</i><div><strong>{c.name}</strong><small>{c.phone} · {c.area}</small></div></div><div><span className={`${styles.stage} ${styles[c.stage.replaceAll(" ","").toLowerCase()]||""}`}>{c.stage}</span><small>{c.pets} · {c.source}</small></div><div><strong>{c.next}</strong><small>{c.opportunity}</small></div></button>)}</>}
