"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./revenue-engine.module.css";

type Tab="revenue"|"leads"|"rnr"|"tickets"|"leaderboard"|"command";
type Opportunity={id:string;rank:number;customer_name?:string;pet_names?:string;reason:string;opportunity_type:string;score:number;expected_revenue:number;margin_percent:number;suggested_offer:string;preferred_channel:string;owner:string;status:string;due_at:number};
type Lead={id:string;customer_id:string;customer_name?:string;pet_names?:string;service:string;source:string;owner:string;manager:string;status:string;stage:string;work_day:number;first_action_due_at:number;manager_alert_at:number;call_attempts:number;whatsapp_attempts:number;last_outcome?:string;recycle_at?:number;recycle_cycle:number};
type Ticket={id:string;customer_name?:string;booking_id?:string;category:string;priority:string;subject:string;detail:string;owner:string;manager:string;sla_due_at:number;status:string;escalation_level:number;customer_status:string};
type Leader={id:string;employee_name:string;target_revenue:number;eligible_revenue:number;collections:number;conversions:number;renewals:number;sla_percent:number;rnr_percent:number;refunds:number;incentive_amount:number;rank:number;status:string};
type Delivery={id:string;entity_id:string;channel:string;provider:string;template_code:string;consent_status:string;delivery_status:string;created_at:number};
type Report={id:string;period_type:string;status:string;generated_at:number;recipients_json:string};
type Ops={id:string;booking_id:string;vertical:string;owner:string;scheduled_end_at:number;status:string;service_evidence?:string;payment_confirmed:number;provider_settlement_ready:number;exception_reason?:string;escalation_level:number};
type Closure={closure_date:string;status:string;checklist:Record<string,{done:boolean;note:string}>;variance_amount:number;escalation_level:number};
type Payload={stats:{revenue100:number;expectedRevenue:number;slaBreaches:number;rnrComplete:number;openTickets:number;escalatedTickets:number;reopened:number;teamRevenue:number;teamIncentive:number;opsBlocked:number};sourceStatus:Record<string,string>;opportunities:Opportunity[];leads:Lead[];tickets:Ticket[];leaderboard:Leader[];deliveries:Delivery[];reports:Report[];closure:Closure;ops:Ops[]};
const money=(value:number)=>`₹${Number(value||0).toLocaleString("en-IN")}`;
const time=(value:number)=>new Date(value).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
const closeLabels:Record<string,string>={online_cash_collections:"Online & cash collections",unmatched_payments:"Unmatched payments",refunds:"Refunds",provider_payouts:"Provider payouts",expenses_bills:"Expenses & bills",bank_ledger_variance:"Bank / ledger variance"};

export default function RevenueEnginePanel({notify}:{notify:(message:string)=>void}){
  const[tab,setTab]=useState<Tab>("revenue"),[data,setData]=useState<Payload|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/revenue-crm",{cache:"no-store"});if(!response.ok)throw new Error(await response.text());setData(await response.json() as Payload)},[]);
  useEffect(()=>{let active=true;fetch("/api/revenue-crm",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error(await response.text());return response.json() as Promise<Payload>}).then(payload=>{if(active)setData(payload)}).catch(()=>{if(active)setError("Revenue engine could not load. Check your CRM access.")});return()=>{active=false}},[]);
  async function act(action:string,body:Record<string,unknown>={},success="Saved"){setBusy(action+String(body.id||body.leadId||""));setError("");try{const response=await fetch("/api/revenue-crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...body})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Action failed");await load();notify(success)}catch(reason){setError(reason instanceof Error?reason.message:"Action failed")}finally{setBusy("")}}
  const rnrLeads=useMemo(()=>data?.leads.filter(lead=>!['closed','converted','cold_exhausted'].includes(lead.status))||[],[data]);
  if(!data)return <section className={styles.loading}>{error||"Preparing today’s governed revenue worklist…"}</section>;
  const tabs:[Tab,string][]=[["revenue","Revenue 100"],["leads","Lead lifecycle"],["rnr","Mandatory RNR"],["tickets","Tickets"],["leaderboard","Incentives"],["command","7 PM control"]];
  return <div className={styles.engine}>
    <section className={styles.hero}><div><span>REVENUE, CRM & CUSTOMER EXPERIENCE ENGINE</span><h2>Every lead worked. Every service closed. Every rupee accounted for.</h2><p>Persistent UAT records · automated controls · company-wide operating visibility</p></div><div className={styles.heroStatus}><i></i><span>Automation active</span><small>Live provider delivery needs credentials</small></div></section>
    <section className={styles.metrics}>
      <article><span>Daily Revenue 100</span><strong>{data.stats.revenue100}/100</strong><small>{money(data.stats.expectedRevenue)} opportunity</small></article>
      <article className={data.stats.slaBreaches?styles.risk:""}><span>Lead SLA breaches</span><strong>{data.stats.slaBreaches}</strong><small>{data.stats.reopened} leads reopened</small></article>
      <article><span>Team eligible revenue</span><strong>{money(data.stats.teamRevenue)}</strong><small>{money(data.stats.teamIncentive)} incentive</small></article>
      <article className={data.stats.opsBlocked?styles.risk:""}><span>Ops awaiting closure</span><strong>{data.stats.opsBlocked}</strong><small>{data.stats.openTickets} open CX tickets</small></article>
    </section>
    <nav className={styles.tabs}>{tabs.map(item=><button key={item[0]} className={tab===item[0]?styles.active:""} onClick={()=>setTab(item[0])}>{item[1]}</button>)}</nav>
    {error&&<div className={styles.error}>{error}</div>}
    {tab==="revenue"&&<section className={styles.workspace}>
      <header><div><span>RANKED EACH MORNING</span><h3>Today’s 100 best revenue actions</h3><p>Renewal, repeat, cross-sell, win-back, abandoned booking and payment signals ranked with margin guardrails.</p></div><button disabled={Boolean(busy)} onClick={()=>act("generate_daily_100",{},"Daily Revenue 100 refreshed")}>↻ Refresh list</button></header>
      <div className={styles.tableHead}><span>Rank & customer</span><span>Why now</span><span>Recommended action</span><span>Value</span><span>Owner</span><span>Action</span></div>
      <div className={styles.rows}>{data.opportunities.map(item=><article className={styles.opportunity} key={item.id}><div className={styles.person}><b>#{item.rank}</b><span><strong>{item.customer_name||item.id}</strong><small>{item.pet_names||"Customer record"} · score {item.score}</small></span></div><div><strong>{item.reason}</strong><small>{item.opportunity_type.replaceAll("_"," ")} · {item.margin_percent}% margin</small></div><div><strong>{item.suggested_offer}</strong><small>{item.preferred_channel} · due {time(item.due_at)}</small></div><div><strong>{money(item.expected_revenue)}</strong><small>Expected</small></div><div><strong>{item.owner}</strong><small>{item.status.replaceAll("_"," ")}</small></div><button disabled={item.status==="completed"||Boolean(busy)} onClick={()=>act(item.status==="ready"?"claim_opportunity":"complete_opportunity",{id:item.id},item.status==="ready"?"Opportunity claimed":"Revenue action completed")}>{item.status==="ready"?"Start":item.status==="completed"?"Done":"Complete"}</button></article>)}</div>
    </section>}
    {tab==="leads"&&<section className={styles.workspace}>
      <header><div><span>10-MINUTE ACTION · 30-MINUTE ESCALATION · 30/60/90-DAY REOPENING</span><h3>Automatic ownership, rotation and recycling</h3><p>Three working days, mandatory outreach, then governed 30, 60 and 90-day reopening until conversion, opt-out or exhaustion.</p></div><div className={styles.headerActions}><button disabled={Boolean(busy)} onClick={()=>act("run_sla",{},"SLA monitor completed")}>Run SLA</button><button disabled={Boolean(busy)} onClick={()=>act("run_reopening",{},"Due leads reopened")}>Run reopening</button></div></header>
      <div className={styles.leadGrid}>{data.leads.map(lead=><article className={`${styles.leadCard} ${lead.status==="sla_breached"?styles.breached:""}`} key={lead.id}><header><div><span>{lead.id}</span><h4>{lead.customer_name||lead.customer_id}</h4><p>{lead.pet_names||"Pet"} · {lead.service} · {lead.source}</p></div><em>{lead.status.replaceAll("_"," ")}</em></header><dl><div><dt>Owner</dt><dd>{lead.owner}</dd></div><div><dt>Work cycle</dt><dd>Day {lead.work_day}/3 · reopen {lead.recycle_cycle}/3</dd></div><div><dt>First action</dt><dd>{time(lead.first_action_due_at)}</dd></div><div><dt>Manager alert</dt><dd>{time(lead.manager_alert_at)}</dd></div></dl><div className={styles.attemptProgress}><span>Calls <b>{lead.call_attempts}/3</b></span><span>WhatsApp <b>{lead.whatsapp_attempts}/3</b></span></div><footer><button disabled={lead.work_day>=3||Boolean(busy)} onClick={()=>act("advance_day",{leadId:lead.id},"Lead rotated")}>Rotate day</button><button disabled={Boolean(busy)} onClick={()=>setTab("rnr")}>Work lead</button></footer></article>)}</div>
    </section>}
    {tab==="rnr"&&<section className={styles.workspace}>
      <header><div><span>MANDATORY CONTACT POLICY</span><h3>Three calls + three WhatsApp attempts</h3><p>Cold is locked until all six attempts and three working days are complete. Consent withdrawal or invalid contact stops promotion immediately.</p></div></header>
      <div className={styles.rnrList}>{rnrLeads.map(lead=><article key={lead.id}><div className={styles.rnrIdentity}><span>{lead.id}</span><strong>{lead.customer_name||lead.customer_id}</strong><small>{lead.owner} · day {lead.work_day} · {lead.stage.replaceAll("_"," ")}</small></div><Attempt label="☎ Calls" count={lead.call_attempts} onClick={()=>act("log_attempt",{leadId:lead.id,channel:"call",outcome:"RNR"},"Call attempt recorded")} disabled={Boolean(busy)}/><Attempt label="◉ WhatsApp" count={lead.whatsapp_attempts} onClick={()=>act("log_attempt",{leadId:lead.id,channel:"whatsapp",outcome:"RNR"},"WATI delivery queued")} disabled={Boolean(busy)}/><div className={styles.rnrActions}><button disabled={Boolean(busy)} onClick={()=>act("log_attempt",{leadId:lead.id,channel:"call",outcome:"Connected"},"Connection recorded")}>Connected</button><button disabled={lead.call_attempts<3||lead.whatsapp_attempts<3||lead.work_day<3||Boolean(busy)} onClick={()=>act("mark_cold",{leadId:lead.id},"Lead scheduled for next reopen")}>Cold + recycle</button></div></article>)}</div>
    </section>}
    {tab==="tickets"&&<section className={styles.workspace}>
      <header><div><span>ONE CUSTOMER EXPERIENCE QUEUE</span><h3>Tickets, refunds and escalations</h3><p>Complaint, delay, no-show, quality, refund, payment, reschedule, safety and technical issues share one SLA-controlled record.</p></div></header>
      <TicketForm busy={Boolean(busy)} onCreate={(body)=>act("create_ticket",body,"Customer ticket created")}/>
      <div className={styles.ticketList}>{data.tickets.map(ticket=><article key={ticket.id} className={styles.ticket}><header><div><span>{ticket.id} · {ticket.category}</span><h4>{ticket.subject}</h4><p>{ticket.customer_name||"Customer"}{ticket.booking_id?` · ${ticket.booking_id}`:""}</p></div><em className={styles[ticket.priority]}>{ticket.priority}</em></header><p>{ticket.detail}</p><dl><div><dt>Owner</dt><dd>{ticket.owner}</dd></div><div><dt>SLA due</dt><dd>{time(ticket.sla_due_at)}</dd></div><div><dt>Escalation</dt><dd>Level {ticket.escalation_level}</dd></div><div><dt>Customer sees</dt><dd>{ticket.customer_status}</dd></div></dl><footer><button disabled={ticket.status==="resolved"||Boolean(busy)} onClick={()=>act("update_ticket",{id:ticket.id,status:"in_progress"},"Ticket in progress")}>Take ownership</button><button disabled={ticket.status==="resolved"||Boolean(busy)} onClick={()=>act("update_ticket",{id:ticket.id,status:"resolved",resolution:"Customer contacted and agreed resolution completed",rootCause:"Process handoff",evidence:"UAT resolution note"},"Ticket resolved")}>Resolve</button></footer></article>)}</div>
    </section>}
    {tab==="leaderboard"&&<section className={styles.workspace}>
      <header><div><span>COMPANY-WIDE VISIBILITY</span><h3>Sales incentives and live leaderboard</h3><p>Only collected, service-completed revenue qualifies. Refunds are deducted and SLA/RNR compliance remain visible guardrails.</p></div></header>
      <div className={styles.podium}>{data.leaderboard.slice(0,3).map(person=><article key={person.id} className={person.rank===1?styles.winner:""}><span>#{person.rank}</span><h4>{person.employee_name}</h4><strong>{money(person.eligible_revenue)}</strong><small>{money(person.incentive_amount)} incentive</small></article>)}</div>
      <div className={styles.leaderTable}><div><b>Rank</b><b>Employee</b><b>Eligible revenue</b><b>Collections</b><b>Conversion</b><b>SLA / RNR</b><b>Incentive</b></div>{data.leaderboard.map(person=><div key={person.id}><span>#{person.rank}</span><strong>{person.employee_name}</strong><span>{money(person.eligible_revenue)} / {money(person.target_revenue)}</span><span>{money(person.collections)}</span><span>{person.conversions} sales · {person.renewals} renewals</span><span>{person.sla_percent}% / {person.rnr_percent}%</span><strong>{money(person.incentive_amount)}</strong></div>)}</div>
    </section>}
    {tab==="command"&&<section className={styles.commandGrid}>
      <article className={styles.controlCard}><header><div><span>AUTOMATED 7 PM REPORTS</span><h3>Daily, weekly and monthly command report</h3></div><button disabled={Boolean(busy)} onClick={()=>act("generate_7pm_reports",{},"7 PM reports generated")}>Generate now</button></header><p>Leads, SLA, revenue, RNR, tickets, Ops risks, refunds and Accounts closure are snapshotted to Founder and managers.</p><div className={styles.miniList}>{data.reports.length?data.reports.map(report=><div key={report.id}><strong>{report.period_type}</strong><span>{time(report.generated_at)}</span><em>{report.status.replaceAll("_"," ")}</em></div>):<small>Scheduled for 7:00 PM IST</small>}</div></article>
      <article className={styles.controlCard}><header><div><span>MANDATORY ACCOUNTS CLOSE</span><h3>{data.closure.closure_date} · {data.closure.status}</h3></div><em className={data.closure.status==="submitted"?styles.ok:styles.warn}>{data.closure.status}</em></header><p>All six checks are required. A non-zero variance needs a note before submission.</p><div className={styles.checkList}>{Object.entries(closeLabels).map(([key,label])=><button key={key} className={data.closure.checklist[key]?.done?styles.checked:""} onClick={()=>act("toggle_close_item",{key},`${label} updated`)}><i>{data.closure.checklist[key]?.done?"✓":"○"}</i><span>{label}</span></button>)}</div><button className={styles.primary} disabled={Boolean(busy)||data.closure.status==="submitted"} onClick={()=>act("submit_accounts_close",{varianceAmount:0,note:"UAT day close reconciled"},"Accounts day closure submitted")}>Submit mandatory day closure</button></article>
      <article className={`${styles.controlCard} ${styles.wide}`}><header><div><span>OPS COMPLETION ENFORCEMENT</span><h3>No work order closes without evidence</h3></div><button disabled={Boolean(busy)} onClick={()=>act("enforce_ops",{},"Ops SLA enforcement completed")}>Run enforcement</button></header><p>Service evidence, customer update, payment confirmation and provider settlement readiness are mandatory. Overdue work escalates into CX tickets.</p><div className={styles.opsList}>{data.ops.map(item=><div key={item.id} className={item.escalation_level?styles.opsRisk:""}><span><strong>{item.booking_id}</strong><small>{item.vertical} · {item.owner}</small></span><span><b>{item.status.replaceAll("_"," ")}</b><small>Due {time(item.scheduled_end_at)} · escalation {item.escalation_level}</small></span><button disabled={item.status==="completed"||Boolean(busy)} onClick={()=>act("complete_ops",{id:item.id,evidence:"UAT service photos and completion note",customerUpdated:true,paymentConfirmed:true,settlementReady:true},"Operations record completed")}>{item.status==="completed"?"Closed":"Complete with evidence"}</button></div>)}</div></article>
      <article className={`${styles.controlCard} ${styles.wide}`}><header><div><span>LIVE DELIVERY READINESS</span><h3>WATI, SMS and telephony control</h3></div></header><div className={styles.connectorGrid}>{Object.entries(data.sourceStatus).filter(([key])=>["wati","sms","telephony"].includes(key)).map(([key,value])=><div key={key}><strong>{key.toUpperCase()}</strong><span>{value}</span><em>Consent · template · retry · webhook ready</em></div>)}</div><div className={styles.deliveryList}>{data.deliveries.slice(0,8).map(event=><div key={event.id}><strong>{event.channel} · {event.template_code}</strong><span>{event.entity_id}</span><em>{event.delivery_status.replaceAll("_"," ")}</em></div>)}</div></article>
    </section>}
    <section className={styles.connectorNote}><strong>Delivery truth</strong><span>30/60/90 reopening, incentives, reports, Accounts closure and Ops enforcement run with persistent UAT records. WATI, SMS and calling actions remain UAT-queued; actual external delivery starts only after credentials, approved templates, consent verification and webhook testing.</span></section>
  </div>
}

function Attempt({label,count,onClick,disabled}:{label:string;count:number;onClick:()=>void;disabled:boolean}){return <div className={styles.channel}><span>{label}</span><b>{[0,1,2].map(index=><i className={index<count?styles.done:""} key={index}>{index<count?"✓":index+1}</i>)}</b><button disabled={count>=3||disabled} onClick={onClick}>{label.includes("WhatsApp")?"Queue WhatsApp":"Log RNR call"}</button></div>}
function TicketForm({busy,onCreate}:{busy:boolean;onCreate:(body:Record<string,unknown>)=>void}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);onCreate({category:fd.get("category"),priority:fd.get("priority"),subject:fd.get("subject"),detail:fd.get("detail"),bookingId:fd.get("bookingId"),owner:"CX Desk"});event.currentTarget.reset()}return <form className={styles.ticketForm} onSubmit={submit}><select name="category" aria-label="Ticket category"><option>Customer complaint</option><option>Provider delay/no-show</option><option>Service quality</option><option>Refund/payment</option><option>Reschedule/cancellation</option><option>Pet safety incident</option><option>Technical issue</option></select><select name="priority" aria-label="Priority"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></select><input name="bookingId" placeholder="Booking ID (optional)"/><input name="subject" required minLength={4} placeholder="What happened?"/><input name="detail" required minLength={8} placeholder="Customer impact and details"/><button disabled={busy}>＋ Create ticket</button></form>}
