import type{Metadata}from"next";import Link from"next/link";import{notFound}from"next/navigation";import styles from"../landing-pages.module.css";import{getMarketingLanding,marketingLandings}from"../../../lib/marketing-landing-content";

export function generateStaticParams(){return marketingLandings.map(item=>({slug:item.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const page=getMarketingLanding(slug);if(!page)return{};return{title:`${page.service} | PawSpace Marketing Review`,description:page.summary,robots:{index:false,follow:false}}}

export default async function MarketingLandingPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const page=getMarketingLanding(slug);if(!page)notFound();return <main className={styles.page} data-theme={page.theme}>
 <div className={styles.topbar}><span>🐾 PawSpace marketing review</span><span>Premium landing-page system</span><span>Final price & availability stay in PawSpace booking</span></div>
 <header className={styles.header}><Link href="/landing-pages" className={styles.brand}>🐾 PawSpace</Link><nav className={styles.nav}><a href="#why">Why PawSpace</a><a href="#process">How it works</a><a href="#packages">Packages</a><a href="#faq">FAQs</a><Link href="/mobile-app">Open customer app</Link></nav></header>
 <section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>🐾 {page.eyebrow}</span><h1>{page.title} <em>{page.accent}</em></h1><p>{page.summary}</p><div className={styles.proof}>{page.proof.map(item=><div key={item}><b>✓ {item}</b><span>Designed for transparent customer review</span></div>)}</div></div><div className={styles.heroSide}><div className={styles.formCard}><h2>{page.formTitle}</h2><p>This review form demonstrates the Webflow conversion structure. Final routing should connect to the governed PawSpace booking/contact flow.</p><form className={styles.formGrid} action="/mobile-app"><input aria-label="Phone number" name="phone" placeholder="Phone number"/><input aria-label="Area or location" name="area" placeholder="Area / location"/><select aria-label="Pet type" name="pet"><option>{page.pet}</option></select><button>{page.formCta}</button></form><p>🔒 Customer data, consent and downstream CRM handling must use the approved production integration.</p></div></div></section>
 <p className={styles.reviewNote}><b>REVIEW BUILD:</b> This is a marketing/advertising landing-page concept for Webflow transfer. It intentionally avoids treating mockup statistics, ratings, provider counts, discounts, pricing, WhatsApp availability or medical outcomes as production truth until those claims are approved and sourced.</p>
 <section className={styles.section} id="why"><div className={styles.sectionHead}><small>Why PawSpace</small><h2>Premium design that earns the next click.</h2><p>The layout follows the strongest parts of the supplied landing-page references: immediate service clarity, compact lead capture, trust framing, benefits, process, comparable packages and FAQ depth.</p></div><div className={styles.benefits}>{page.benefits.map((item,i)=><article className={styles.benefit} key={item.title}><div className={styles.icon}>{i+1}</div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
 <section className={`${styles.section} ${styles.sectionTint}`}><div className={styles.feature}><div className={styles.visual}/><div className={styles.featureCopy}><small className={styles.eyebrow}>Service story</small><h2>{page.featureTitle}</h2><p>{page.featureCopy}</p><div className={styles.bullets}>{page.featureBullets.map(item=><div key={item}><i>✓</i><span>{item}</span></div>)}</div></div></div></section>
 <section className={styles.section} id="process"><div className={styles.sectionHead}><small>How it works</small><h2>A four-step conversion flow customers can understand.</h2></div><div className={styles.steps}>{["Share your details","Review the right option","Confirm in PawSpace","Receive care & updates"].map((item,i)=><article className={styles.step} key={item}><strong>{i+1}</strong><h3>{item}</h3><p>{i===0?"Pet, location and service need.":i===1?"Compare the most relevant journey.":i===2?"Final price, availability and eligibility are resolved in the governed product.":"Keep the booking, updates and support connected."}</p></article>)}</div></section>
 <section className={`${styles.section} ${styles.sectionTint}`} id="packages"><div className={styles.sectionHead}><small>Packages</small><h2>Easy to compare. Hard to misunderstand.</h2><p>These cards communicate the commercial structure. Final published prices, discounts and inclusions must be supplied by the approved pricing source before Webflow launch.</p></div><div className={styles.packages}>{page.packages.map(item=><article className={`${styles.package} ${item.featured?styles.featured:""}`} key={item.name}>{item.featured?<span className={styles.badge}>Most relevant</span>:null}<h3>{item.name}</h3><p><b>Best for:</b> {item.bestFor}</p><ul>{item.items.map(x=><li key={x}>{x}</li>)}</ul><Link href="/mobile-app">Continue to PawSpace</Link></article>)}</div></section>
 {page.related.length?<section className={styles.section}><div className={styles.sectionHead}><small>Related campaigns</small><h2>Keep paid-search journeys tightly matched.</h2></div><div className={styles.related}>{page.related.map(slug=>{const related=getMarketingLanding(slug);return related?<article className={styles.relatedCard} key={slug}><small>{related.pet}</small><h3>{related.service}</h3><p>{related.title}</p><Link href={`/landing-pages/${slug}`}>Review landing page →</Link></article>:null})}</div></section>:null}
 <section className={styles.section} id="faq"><div className={styles.sectionHead}><small>FAQs</small><h2>Answer objections before the customer leaves.</h2></div><div className={styles.faq}>{page.faqs.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
 <footer className={styles.footer}><div><b>🐾 PawSpace</b><div>Marketing landing-page review system</div></div><div><Link href="/landing-pages">View all landing pages</Link> · <Link href="/discover">Premium website</Link> · <Link href="/mobile-app">Customer app</Link></div></footer>
 </main>}
