import{authError,authorize,securityAudit}from"../../../lib/server-auth";

async function database(){const{env}=await import("cloudflare:workers");return env.DB;}
const response=(data:unknown,status=200)=>Response.json(data,{status});
const scheduleRuleFields=new Set(["rating","qualityScore","model","providerId","zone","capacity"]);
const scheduleRuleOperators=new Set(["eq","neq","gte","lte","in","not_in"]);
function validScheduleRule(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return false;const rule=value as Record<string,unknown>,expected=rule.value;return typeof rule.code==="string"&&Boolean(rule.code.trim())&&typeof rule.field==="string"&&scheduleRuleFields.has(rule.field)&&typeof rule.operator==="string"&&scheduleRuleOperators.has(rule.operator)&&(typeof expected==="string"||(typeof expected==="number"&&Number.isFinite(expected))||(Array.isArray(expected)&&expected.every(item=>typeof item==="string")));}
const RULES_DDL="CREATE TABLE IF NOT EXISTS scheduling_rules (id TEXT PRIMARY KEY,name TEXT NOT NULL,service_code TEXT,city_id TEXT,zone_id TEXT,priority INTEGER NOT NULL DEFAULT 100,condition_json TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)";
async function ensureTables(db:D1Database){await db.batch([db.prepare(RULES_DDL),db.prepare("CREATE TABLE IF NOT EXISTS scheduling_rule_audit (id TEXT PRIMARY KEY,rule_id TEXT NOT NULL,action TEXT NOT NULL,before_json TEXT,after_json TEXT NOT NULL,actor_id TEXT NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_scheduling_rule_audit_rule ON scheduling_rule_audit(rule_id,created_at)")]);}
async function exists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first<{name?:string}>());}
const reasonOk=(value:unknown)=>String(value??"").trim().length>=5;
async function audit(db:D1Database,input:{ruleId:string;action:string;before:unknown;after:unknown;actorId:string;reason:string}){await db.prepare("INSERT INTO scheduling_rule_audit (id,rule_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.ruleId,input.action,input.before?JSON.stringify(input.before):null,JSON.stringify(input.after??{}),input.actorId,input.reason.trim(),Date.now()).run();}
export async function GET(request:Request){try{await authorize(request,"scheduling.view");const db=await database(),url=new URL(request.url),wantAudit=url.searchParams.get("audit")==="1";if(wantAudit){if(!await exists(db,"scheduling_rule_audit"))return response({data:[]});const rows=await db.prepare("SELECT * FROM scheduling_rule_audit ORDER BY created_at DESC LIMIT 100").all();return response({data:rows.results});}if(!await exists(db,"scheduling_rules"))return response({data:[]});const result=await db.prepare("SELECT * FROM scheduling_rules ORDER BY priority ASC,updated_at DESC").all();return response({data:result.results});}catch(error){return authError(error,"Unable to load scheduling rules");}}
export async function POST(request:Request){try{const actor=await authorize(request,"scheduling.manage"),db=await database();await ensureTables(db);const body=await request.json() as{name?:unknown;serviceCode?:string;cityId?:string;zoneId?:string;priority?:number;conditions?:unknown;reason?:string};if(typeof body.name!=="string"||!body.name.trim()||!Array.isArray(body.conditions)||body.conditions.length===0||!body.conditions.every(validScheduleRule))return response({error:"Rule name and valid conditions are required"},400);if(!reasonOk(body.reason))return response({error:"A clear change reason of at least 5 characters is required"},400);const id=`rule_${crypto.randomUUID().slice(0,12)}`,now=Date.now();await db.prepare("INSERT INTO scheduling_rules (id,name,service_code,city_id,zone_id,priority,condition_json,active,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,body.name.trim(),body.serviceCode??null,body.cityId??"blr",body.zoneId??null,body.priority??100,JSON.stringify(body.conditions),1,actor.email,now,now).run();const after=await db.prepare("SELECT * FROM scheduling_rules WHERE id=?").bind(id).first();await audit(db,{ruleId:id,action:"created",before:null,after,actorId:actor.email,reason:String(body.reason)});await securityAudit(db,actor,"scheduling.rule.create","scheduling_rule",id,"completed",{reason:body.reason});return response({data:{id,name:body.name,active:true}},201);}catch(error){return authError(error,"Unable to create scheduling rule");}}
export async function PATCH(request:Request){try{const actor=await authorize(request,"scheduling.manage"),db=await database();await ensureTables(db);const body=await request.json() as{id?:string;active?:unknown;name?:string;priority?:number;reason?:string};if(!body.id)return response({error:"Rule ID is required"},400);if(body.active!==undefined&&typeof body.active!=="boolean")return response({error:"Rule active must be a boolean"},400);if(!reasonOk(body.reason))return response({error:"A clear change reason of at least 5 characters is required"},400);const before=await db.prepare("SELECT * FROM scheduling_rules WHERE id=?").bind(body.id).first();if(!before)return response({error:"Scheduling rule not found"},404);await db.prepare("UPDATE scheduling_rules SET active=COALESCE(?,active),name=COALESCE(?,name),priority=COALESCE(?,priority),updated_at=? WHERE id=?").bind(body.active===undefined?null:body.active?1:0,body.name??null,body.priority??null,Date.now(),body.id).run();const after=await db.prepare("SELECT * FROM scheduling_rules WHERE id=?").bind(body.id).first();await audit(db,{ruleId:body.id,action:"updated",before,after,actorId:actor.email,reason:String(body.reason)});await securityAudit(db,actor,"scheduling.rule.update","scheduling_rule",body.id,"completed",{reason:body.reason});return response({data:{id:body.id,updated:true}});}catch(error){return authError(error,"Unable to update scheduling rule");}}
export async function DELETE(request:Request){try{const actor=await authorize(request,"scheduling.manage"),db=await database();await ensureTables(db);const url=new URL(request.url),id=url.searchParams.get("id"),reason=String(url.searchParams.get("reason")||"");if(!id)return response({error:"Rule ID is required"},400);if(!reasonOk(reason))return response({error:"A clear change reason of at least 5 characters is required"},400);const before=await db.prepare("SELECT * FROM scheduling_rules WHERE id=?").bind(id).first();if(!before)return response({error:"Scheduling rule not found"},404);await db.prepare("DELETE FROM scheduling_rules WHERE id=?").bind(id).run();await audit(db,{ruleId:id,action:"deleted",before,after:{deleted:true},actorId:actor.email,reason});await securityAudit(db,actor,"scheduling.rule.delete","scheduling_rule",id,"completed",{reason});return response({data:{id,deleted:true}});}catch(error){return authError(error,"Unable to delete scheduling rule");}}
