import{refuseUnlessGatewayPermits}from"../../../lib/api-gateway";
import{authError,database,requireCustomerOwnership,requirePermission,requireProviderOwnership,resolveActor,securityAudit,type AuthenticatedActor}from"../../../lib/server-auth";
import{findIdentityBinding}from"../../../lib/identity-binding";
import{hasPermission}from"../../../lib/platform-security";
import{getBoardingStay,listBoardingStays,mutateBoardingStay,type BoardingStayAction,type BoardingCarePlan}from"../../../lib/boarding-stay-lifecycle";
import{tryQualifyLinkedReferral}from"../../../lib/referral-booking-governance";

type Body={stayId?:string;action?:BoardingStayAction;idempotencyKey?:string;reason?:string;carePlan?:BoardingCarePlan;careEventType?:string;detail?:Record<string,unknown>;requestedEnd?:string};
const json=(value:unknown,status=200)=>Response.json(value,{status});
const providerActions=new Set<BoardingStayAction>(["accept","decline","check_in","care_event","host_unavailable","check_out"]);
const customerActions=new Set<BoardingStayAction>(["submit_care_plan","request_extension"]);
const evidenceCareEvents=new Set(["medication","photo_update","incident"]);

async function ownProviderId(db:D1Database,actor:AuthenticatedActor){if(actor.developmentPreview)return"host_maya_rohan";const binding=await findIdentityBinding(db,{identitySource:actor.identitySource,principalType:actor.principalType,principalKey:actor.principalKey,subjectType:"provider"});if(binding)return String(binding.subject_id);const legacy=await db.prepare("SELECT provider_id,status FROM provider_identity_links WHERE email=?").bind(actor.email).first<Record<string,unknown>>();return legacy&&legacy.status==="active"?String(legacy.provider_id):null;}
async function providerScope(db:D1Database,providerId:string){if(!providerId)return{providerId:null,cityId:null,zoneId:null};const row=await db.prepare("SELECT city_id,zone_id FROM boarding_host_profiles WHERE provider_id=?").bind(providerId).first<Record<string,unknown>>();return{providerId,cityId:row?String(row.city_id):null,zoneId:row?String(row.zone_id):null};}

export async function GET(request:Request){try{const url=new URL(request.url);let providerId=String(url.searchParams.get("providerId")||"").trim();const customerId=String(url.searchParams.get("customerId")||"").trim(),bookingId=String(url.searchParams.get("bookingId")||"").trim(),customerScope=url.searchParams.get("scope")==="customer";const db=await database(),actor=await resolveActor(request);
 if(customerScope){requirePermission(actor,"scheduling.book");if(!bookingId||providerId||customerId)return json({error:"Customer Boarding stay reads require only a booking ID"},400);const rows=await listBoardingStays(db,{bookingId});if(!rows.length)return json({data:[],scope:{providerId:null,cityId:null,zoneId:null,customerId:null,bookingId}});const ownedCustomerId=String((rows[0] as Record<string,unknown>).customer_id||"");await requireCustomerOwnership(db,actor,ownedCustomerId);return json({data:rows,scope:{providerId:null,cityId:null,zoneId:null,customerId:ownedCustomerId,bookingId}});}
 requirePermission(actor,"bookings.view");if(!providerId&&!customerId&&!bookingId){if(hasPermission(actor.permissions,"bookings.manage"))return json({error:"Staff requests require a provider, customer or booking filter"},400);providerId=String(await ownProviderId(db,actor)||"");if(!providerId)return json({error:"No active provider identity is linked to this session"},403);}if(providerId)await requireProviderOwnership(db,actor,providerId);if(customerId)await requireCustomerOwnership(db,actor,customerId);if(bookingId&&!providerId&&!customerId&&!hasPermission(actor.permissions,"bookings.manage")){const stay=(await listBoardingStays(db,{bookingId}))[0];if(!stay)return json({data:[],scope:{providerId:null,cityId:null,zoneId:null}});const provider=String((stay as Record<string,unknown>).host_provider_id||""),customer=String((stay as Record<string,unknown>).customer_id||"");try{await requireProviderOwnership(db,actor,provider);}catch{await requireCustomerOwnership(db,actor,customer);}}const rows=await listBoardingStays(db,{providerId:providerId||undefined,customerId:customerId||undefined,bookingId:bookingId||undefined}),scope=providerId?await providerScope(db,providerId):{providerId:null,cityId:null,zoneId:null};return json({data:rows,scope:{...scope,customerId:customerId||null,bookingId:bookingId||null}});}catch(error){return authError(error,"Unable to load Boarding stays");}}

export async function POST(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const body=await request.json() as Body,stayId=String(body.stayId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!stayId||!action||!idempotencyKey)return json({error:"Stay, action and idempotency key are required"},400);if(action==="care_event"&&evidenceCareEvents.has(String(body.careEventType||"")))return json({error:"Medication, photo proof and incidents must use the governed Boarding proof workflow"},409);const db=await database(),actor=await resolveActor(request),stay=await getBoardingStay(db,stayId);if(!stay)return json({error:"Boarding stay not found"},404);const providerId=String(stay.host_provider_id),customerId=String(stay.customer_id),staff=hasPermission(actor.permissions,"bookings.manage");if(action==="no_show"){requirePermission(actor,"bookings.manage");}else if(providerActions.has(action)){requirePermission(actor,"bookings.view");if(!staff)await requireProviderOwnership(db,actor,providerId);}else if(customerActions.has(action)){if(!staff){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,customerId);}}else return json({error:"Unsupported Boarding stay action"},400);const result=await mutateBoardingStay(db,{stayId,action,actorId:actor.email,idempotencyKey,reason:body.reason,carePlan:body.carePlan,careEventType:body.careEventType,detail:body.detail,requestedEnd:body.requestedEnd});let referral:unknown={applicable:false,status:"not_applicable"};if(action==="check_out"&&String((result as Record<string,unknown>).status)==="completed"){try{referral=await tryQualifyLinkedReferral(db,{bookingId:String(stay.booking_id),actorId:actor.email});}catch(error){referral={applicable:true,status:"review_required",reason:error instanceof Error?error.message:"Referral qualification requires review"};}}await securityAudit(db,actor,`boarding.stay.${action}`,"boarding_stay",stayId,"completed",{bookingId:stay.booking_id,providerId,customerId,staffOverride:staff,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented),referral});return json({data:result,referral},String((result as Record<string,unknown>).status)==="ops_escalation"?202:200);}catch(error){return authError(error,"Unable to update Boarding stay");}}
