import{aiToolRegistrySnapshot,confirmAiToolExecution,prepareAiToolExecution,type AiToolChannel,type AiToolIntent}from"../../../lib/ai-tool-registry";
import{autonomousBookingToolSnapshot,executeGovernedBookingCreate}from"../../../lib/autonomous-booking-tool";
import{authError,database,resolveActor,securityAudit}from"../../../lib/server-auth";

type Body={action?:"prepare"|"confirm";toolCode?:string;threadId?:string;customerId?:string;intent?:AiToolIntent;channel?:AiToolChannel;arguments?:Record<string,unknown>;idempotencyKey?:string;requestId?:string};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin AI tool write blocked",{status:403});}
function channel(value:string|null):AiToolChannel{if(value==="whatsapp"||value==="chat"||value==="voice")return value;throw new Response("Unsupported AI tool channel",{status:400});}
function intent(value:string|null):AiToolIntent{const allowed=new Set(["service_info","booking_create","booking_status","booking_change","subscription_wallet","coupon","support","refund_review","funeral_memorial","relocation","human_handoff","unknown"]);if(value&&allowed.has(value))return value as AiToolIntent;throw new Response("Unsupported AI tool intent",{status:400});}

export async function GET(request:Request){try{const actor=await resolveActor(request),db=await database(),url=new URL(request.url),customerId=url.searchParams.get("customerId")||"";if(!customerId)return json({error:"Customer is required"},400);const requestedIntent=intent(url.searchParams.get("intent")),requestedChannel=channel(url.searchParams.get("channel"));const data=await aiToolRegistrySnapshot(db,{actor,customerId,intent:requestedIntent,channel:requestedChannel});if(requestedIntent==="booking_create"&&requestedChannel==="voice")return json({data:{...data,registry:[autonomousBookingToolSnapshot(),...data.registry]}});return json({data});}catch(error){if(error instanceof Response)return error;return authError(error,"Unable to load governed AI tool registry");}}

export async function POST(request:Request){try{sameOrigin(request);const actor=await resolveActor(request),db=await database(),body=await request.json() as Body;if(body.action==="prepare"){if(!body.toolCode||!body.threadId||!body.customerId||!body.intent||!body.channel)return json({error:"Tool, thread, customer, intent and channel are required"},400);if(body.toolCode==="booking.create"){if(!body.idempotencyKey)return json({error:"booking.create requires an idempotency key"},400);const{env}=await import("cloudflare:workers");const data=await executeGovernedBookingCreate(db,env as unknown as Record<string,unknown>,{actor,customerId:body.customerId,threadId:body.threadId,channel:body.channel,intent:body.intent,arguments:body.arguments??{},idempotencyKey:body.idempotencyKey});await securityAudit(db,actor,"ai.tool.booking_create","ai_tool_request",typeof data.result==="object"&&data.result&&"bookingId"in data.result?String((data.result as Record<string,unknown>).bookingId):null,"completed",{toolCode:body.toolCode,status:data.status,executed:data.executed,autonomousExecution:data.autonomousExecution,humanApprovalRequired:data.humanApprovalRequired});return json({data},data.status==="human_exception"?202:200);}const data=await prepareAiToolExecution(db,{actor,toolCode:body.toolCode,threadId:body.threadId,customerId:body.customerId,intent:body.intent,channel:body.channel,arguments:body.arguments,idempotencyKey:body.idempotencyKey});await securityAudit(db,actor,"ai.tool.prepare","ai_tool_request","requestId"in data&&typeof data.requestId==="string"?data.requestId:null,"completed",{toolCode:body.toolCode,status:data.status,executed:data.executed,autonomousExecution:false});return json({data},data.status==="confirmation_required"?202:200);}if(body.action==="confirm"){if(!body.requestId)return json({error:"AI tool request ID is required for explicit confirmation"},400);const data=await confirmAiToolExecution(db,{actor,requestId:body.requestId});await securityAudit(db,actor,"ai.tool.confirm_execute","ai_tool_request",body.requestId,"completed",{status:data.status,executed:data.executed,autonomousExecution:false});return json({data});}return json({error:"Unsupported AI tool action"},400);}catch(error){if(error instanceof Response)return json({error:await error.text()},error.status);return authError(error,"Unable to execute governed AI tool");}}
