"use client";
/* eslint-disable @next/next/no-img-element */
import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import{createWalkingQuote,loadWalkingCatalogue,type WalkingPackage,type WalkingQuote}from"../../lib/walking-commercial-client";
import{Button}from"../components/ui";
import{reserveUatSchedule,type UatScheduleResult}from"../../lib/uat-scheduling-client";
import{createCanonicalWalkingBooking,type WalkingBookingResult}from"../../lib/walking-booking-client";
import styles from"./walking.module.css";

const walkers=[
 {providerId:"walk_nisha",name:"Nisha P.",initials:"NP",rating:"4.9",walks:"UAT governed",area:"Indiranagar",skills:["Large dogs","Leash handling","Senior care"],tone:"purple"},
 {providerId:"walk_kiran",name:"Kiran M.",initials:"KM",rating:"4.8",walks:"UAT governed",area:"Domlur",skills:["Puppies","High energy","Medication aware"],tone:"green"},
 {providerId:"walk_asha",name:"Asha R.",initials:"AR",rating:"5.0",walks:"UAT governed",area:"Koramangala",skills:["Reactive dogs","Solo walks","Senior care"],tone:"orange"},
];
const slots=[{label:"6:00 AM",hour:"06:00"},{label:"7:00 AM",hour:"07:00"},{label:"8:00 AM",hour:"08:00"},{label:"4:00 PM",hour:"16:00"},{label:"5:00 PM",hour:"17:00"},{label:"6:00 PM",hour:"18:00"}];
const dayOptions=[{label:"Mon",value:1},{label:"Tue",value:2},{label:"Wed",value:3},{label:"Thu",value:4},{label:"Fri",value:5},{label:"Sat",value:6},{label:"Sun",value:0}];
const dateOffset=(days:number)=>new Date(Date.now()+days*86_400_000).toISOString().slice(0,10);
const nextSelectedDate=(base:string,weekdays:number[])=>{const date=new Date(`${base}T12:00:00Z`);for(let i=0;i<8;i++){if(weekdays.includes(date.getUTCDay()))return date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+1)}return base};
const localInstant=(date:string,time:string)=>`${date}T${time}:00+05:30`;
const uatCustomer={id:"TST-101",name:"PawSpace UAT Customer",primaryPhone:"+919880222741",secondaryPhone:"+919880222742",email:"uat.customer@pawspace.test"};
const uatPet={sourceId:"TST-PET-BRUNO",name:"Bruno",species:"dog" as const,breed:"Golden Retriever",vaccinationStatus:"verified"};

export default function WalkingPage(){
 const[type,setType]=useState<"once"|"recurring">("recurring"),[duration,setDuration]=useState<30|60>(30),[selected,setSelected]=useState(walkers[0]),[slot,setSlot]=useState(1),[startDate,setStartDate]=useState(()=>dateOffset(3)),[weekdays,setWeekdays]=useState<number[]>([1,3,5]),[stage,setStage]=useState<"book"|"confirmed">("book"),[packages,setPackages]=useState<WalkingPackage[]>([]),[quote,setQuote]=useState<WalkingQuote|null>(null),[quoteLoading,setQuoteLoading]=useState(true),[quoteError,setQuoteError]=useState(""),[bookingLoading,setBookingLoading]=useState(false),[bookingError,setBookingError]=useState(""),[booking,setBooking]=useState<WalkingBookingResult|null>(null),[assignedProvider,setAssignedProvider]=useState<UatScheduleResult["provider"]|null>(null);
 const packageCode=duration===60?"walking-60":"walking-30",walkCount=type==="recurring"?weekdays.length:1,weekdayKey=weekdays.slice().sort((a,b)=>a-b).join(","),firstDate=type==="recurring"?nextSelectedDate(startDate,weekdays):startDate,scheduledStart=localInstant(firstDate,slots[slot].hour),scheduledEnd=new Date(new Date(scheduledStart).getTime()+duration*60_000).toISOString(),activePackage=useMemo(()=>packages.find(item=>item.package_code===packageCode),[packages,packageCode]);
 useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(cancelled)return;setQuoteLoading(true);setQuoteError("");setQuote(null);setBookingError("")});Promise.all([loadWalkingCatalogue({scheduledStart}),createWalkingQuote({packageCode,mode:type,petCount:1,walkCount,weekdays:type==="recurring"?weekdays:[],scheduledStart,scheduledEnd,paymentMode:"pay_after_service"})]).then(([catalogue,nextQuote])=>{if(cancelled)return;setPackages(catalogue.packages);setQuote(nextQuote)}).catch(error=>{if(cancelled)return;setQuoteError(error instanceof Error?error.message:"Unable to refresh canonical Dog Walking quote")}).finally(()=>{if(!cancelled)setQuoteLoading(false)});return()=>{cancelled=true}},[packageCode,type,walkCount,weekdayKey,weekdays,scheduledStart,scheduledEnd]);
 const quoteAmount=quote?.totalAmount,perWalk=quote?.perWalkAmount??activePackage?.amount_per_walk,caregiverName=assignedProvider?.name||selected.name;
 function toggleDay(day:number){setWeekdays(current=>current.includes(day)?current.length<=2?current:current.filter(value=>value!==day):[...current,day].sort((a,b)=>a-b))}
 async function finalizeBooking(){if(!quote||bookingLoading)return;setBookingLoading(true);setBookingError("");try{const groupId=`walk-${quote.quoteId}`,idempotencyKey=`walking:${quote.quoteId}:${uatCustomer.id}`,schedule=await reserveUatSchedule({clientRequestId:groupId,customerId:uatCustomer.id,petIds:[uatPet.sourceId],serviceCode:"dog_walking",cityId:"blr",zoneId:"blr-east",scheduledStart:quote.scheduledStart,scheduledEnd:quote.scheduledEnd,occurrences:quote.walkCount,weekdays:quote.mode==="recurring"?quote.weekdays:undefined,preferredProviderId:selected.providerId}),result=await createCanonicalWalkingBooking({idempotencyKey,groupId:schedule.groupId,walkingQuoteId:quote.quoteId,customer:uatCustomer,pets:[uatPet],cityId:"blr",zoneId:"blr-east",packageCode:quote.packageCode,packageName:quote.packageName,walkCount:quote.walkCount,weekdays:quote.weekdays,scheduledStart:quote.scheduledStart,scheduledEnd:quote.scheduledEnd,provider:schedule.provider,totalAmount:quote.totalAmount,amountDueNow:quote.amountDueNow,payment:{method:"payment_link",mode:"pay_after_service",detail:"UAT pay-after-each-completed-walk; no live capture"}});setAssignedProvider(schedule.provider);setBooking(result);const card=walkers.find(item=>item.providerId===schedule.provider.id);if(card)setSelected(card);setStage("confirmed");window.scrollTo(0,0)}catch(error){setBookingError(error instanceof Error?error.message:"Unable to create canonical Dog Walking booking")}finally{setBookingLoading(false)}}
 if(stage==="confirmed")return <main className={styles.shell}><header className={styles.header}><Link href="/"><img src="/assets/pawspace-logo.jpeg" alt="PawSpace"/></Link><span>✓ Canonical walk booking created</span></header><section className={styles.confirmed}><i>✓</i><p>{booking?.bookingId||"DOG WALKING UAT"}</p><h1>Bruno&apos;s canonical walk schedule is created.</h1><span>{quote?.walkCount||1} reserved walk{(quote?.walkCount||1)===1?"":"s"} · {duration} minutes · {caregiverName}</span><div><article><b>{selected.initials}</b><strong>{caregiverName}</strong><small>Canonical scheduler-owned walker · provider acceptance follows next</small></article><article><strong>Reserved sessions</strong><span>{booking?.sessions.length||0} canonical walk{(booking?.sessions.length||0)===1?"":"s"}</span><small>{booking?.sessions[0]?new Date(booking.sessions[0].scheduledStart).toLocaleString("en-IN"):"Schedule pending"}</small></article><article><strong>Commercial truth</strong><span>₹{Number(quoteAmount||0).toLocaleString("en-IN")}</span><small>₹0 due now · pay after each completed UAT walk</small></article></div><p>Booking, work order, payment intent and each reserved walk session share one canonical booking ID. No live money or GPS tracking has been activated.</p><button onClick={()=>setStage("book")}>Back to Walking</button>{booking?.bookingId?<Link href={`/walking/manage?bookingId=${encodeURIComponent(booking.bookingId)}`}>Manage walks</Link>:null}<Link href="/mobile-app">My PawSpace</Link></section></main>;
 return <main className={styles.shell}><header className={styles.header}><Link href="/"><img src="/assets/pawspace-logo.jpeg" alt="PawSpace"/></Link><nav><Link href="/taxi">Pet Taxi</Link><Link href="/boarding">Boarding</Link><Link href="/training">Training</Link><Link href="/mobile-app">My PawSpace</Link><Link href="/walker">Walker app</Link></nav></header><section className={styles.hero}><div><span>PAWSPACE DOG WALKING</span><h1>Every walk.<br/><em>Accountable from booking.</em></h1><p>Choose a preferred walker and routine. PawSpace verifies canonical price, roster, conflicts and provider capacity before creating the schedule.</p><div><b>✓ Server-owned price</b><b>✓ Canonical walker scheduling</b><b>✓ Pay after completed walk</b></div></div><aside>🦮</aside></section>
 <section className={styles.panel}><div className={styles.head}><div><p>BUILD BRUNO&apos;S ROUTINE</p><h2>How often should we walk?</h2></div><span>1 of 3</span></div><div className={styles.switch}><button className={type==="once"?styles.active:""} onClick={()=>setType("once")}>One-time walk</button><button className={type==="recurring"?styles.active:""} onClick={()=>setType("recurring")}>Recurring starter schedule</button></div><div className={styles.fields}><label>Pet<select><option>Bruno · Golden Retriever</option></select></label><label>Walk duration<select value={duration} onChange={event=>setDuration(Number(event.target.value) as 30|60)}><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label><label>Start from<input type="date" value={startDate} min={dateOffset(1)} onChange={event=>setStartDate(event.target.value)}/></label></div>{type==="recurring"&&<><div className={styles.days}>{dayOptions.map(day=><button className={weekdays.includes(day.value)?styles.active:""} key={day.label} onClick={()=>toggleDay(day.value)}>{day.label}</button>)}</div><p>Gate 1 reserves one walk on each selected weekday in this starter schedule. Ongoing subscription/renewal policy is not invented yet.</p></>}</section>
 <section className={styles.panel}><div className={styles.head}><div><p>CANONICAL TIME REQUEST</p><h2>Choose the walk start time</h2></div><span>2 of 3</span></div><div className={styles.slots}>{slots.map((item,index)=><button key={item.label} className={slot===index?styles.selected:""} onClick={()=>setSlot(index)}><strong>{item.label}</strong><small>Capacity verified on confirmation</small></button>)}</div></section>
 <section className={styles.panel}><div className={styles.head}><div><p>CARE MATCHING</p><h2>Choose a preferred walker</h2></div><span>3 of 3</span></div><div className={styles.walkers}>{walkers.map(walker=><button key={walker.providerId} className={selected.providerId===walker.providerId?styles.chosen:""} onClick={()=>setSelected(walker)}><i className={styles[walker.tone]}>{walker.initials}</i><div><span>{walker.rating} ★ · {walker.walks}</span><h3>{walker.name}</h3><p>{walker.area} · final assignment comes from canonical scheduling</p><div>{walker.skills.map(skill=><b key={skill}>{skill}</b>)}</div></div><strong>{perWalk!=null?`₹${Number(perWalk).toLocaleString("en-IN")}`:"—"}<small> / walk · same server price</small></strong></button>)}</div><div className={styles.instructions}><label>Walking & safety instructions<textarea defaultValue="Use the blue harness. Bruno can be excited near other large dogs; please keep a comfortable distance."/></label><label>Handover preference<select><option>Owner handover · governed verification comes in Gate 2</option><option>Approved building staff</option><option>Secure key access · policy pending</option></select></label></div></section><aside className={styles.checkout}><div><span>{type==="recurring"?`${walkCount}-walk starter schedule`:"One-time walk"} · {duration} min · preferred {selected.name}</span><strong>{quoteAmount!=null?`₹${quoteAmount.toLocaleString("en-IN")}`:"—"}</strong><em>{quoteLoading?"Refreshing canonical quote…":quoteError?quoteError:quote?`Quote ${quote.quoteId} · ₹0 due now · scheduler verifies final walker`:"Canonical quote unavailable"}</em></div><Button size="lg" disabled={!quote||quoteLoading||Boolean(quoteError)||bookingLoading} onClick={()=>void finalizeBooking()}>{bookingLoading?"Reserving canonical walks…":"Create canonical UAT schedule →"}</Button></aside>{bookingError&&<aside style={{position:"fixed",bottom:100,left:"50%",transform:"translateX(-50%)",zIndex:30,background:"#fff1f1",padding:12,borderRadius:10}}>{bookingError}</aside>}</main>;
}