import{authError,database,requireCustomerOwnership,requirePermission,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission}from"../../../lib/platform-security";
import{listFoodOrders,mutateFoodFulfilment,type FoodFulfilmentAction}from"../../../lib/food-fulfilment-governance";
type Body={orderId?:string;action?:FoodFulfilmentAction;idempotencyKey?:string;lotId?:string;dispatchReference?:string;handoverMethod?:"customer"|"building_staff";reason?:string};const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
/*
 * Cross-tenant read (PTJA W2-17-F02). requireCustomerOwnership used to run only when the caller supplied
 * `customerId`, so supplying `orderId` instead reached listFoodOrders with no ownership predicate and
 * served the identical row this handler had just refused for the customerId form - the guard was
 * attached to the request PARAMETER rather than to the record that comes back. Ownership is now checked
 * on every record actually returned, which is what the sibling walking / taxi / sitting lifecycle routes
 * already do. A holder of bookings.manage is unaffected; a caller without it sees only their own.
 */
export async function GET(request:Request){try{const url=new URL(request.url),orderId=String(url.searchParams.get("orderId")||"").trim(),customerId=String(url.searchParams.get("customerId")||"").trim(),scope=String(url.searchParams.get("scope")||"staff"),db=await database(),actor=await resolveActor(request);if(scope==="customer"){requirePermission(actor,"scheduling.book");if(!orderId||customerId)return json({error:"Customer Food reads require only an order ID"},400);const rows=await listFoodOrders(db,{orderId});if(!rows.length)return json({data:[]});await requireCustomerOwnership(db,actor,String((rows[0] as Record<string,unknown>).customer_id));return json({data:rows})}requirePermission(actor,"bookings.view");if(!orderId&&!customerId)return json({error:"Food fulfilment reads require order or customer scope"},400);const rows=await listFoodOrders(db,{orderId:orderId||undefined,customerId:customerId||undefined});if(!hasPermission(actor.permissions,"bookings.manage")){if(customerId)await requireCustomerOwnership(db,actor,customerId);for(const owner of new Set(rows.map(row=>String((row as Record<string,unknown>).customer_id||""))))await requireCustomerOwnership(db,actor,owner);}return json({data:rows})}catch(error){return authError(error,"Unable to load Food fulfilment")}}
export async function POST(request:Request){try{const body=await request.json() as Body,orderId=String(body.orderId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!orderId||!action||!idempotencyKey)return json({error:"Order, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request);requirePermission(actor,"bookings.manage");const result=await mutateFoodFulfilment(db,{orderId,action,actorId:actor.email,idempotencyKey,lotId:body.lotId,dispatchReference:body.dispatchReference,handoverMethod:body.handoverMethod,reason:body.reason});await securityAudit(db,actor,`food.fulfilment.${action}`,"food_order",orderId,"completed",{uatOnly:true,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented)});return json({data:result,uatOnly:true})}catch(error){return authError(error,"Unable to update Food fulfilment")}}
