import{authError,authorize,database,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{createPostServicePaymentRequest,ensurePaymentReconciliationTables,getPostServicePaymentRequest,linkSandboxGatewayOrder,processGatewayEvent}from"../../../lib/grooming-payment-reconciliation";
import{createSandboxOrder,createSandboxRefund}from"../../../lib/razorpay-sandbox-client";

type Input={action:"create_order"|"initiate_refund"|"link_order"|"simulate_event"|"request_after_service";bookingId:string;gatewayOrderId?:string;eventType?:"payment.authorized"|"payment.captured"|"payment.failed"|"order.paid"|"refund.created"|"refund.processed"|"refund.failed";eventId?:string;gatewayPaymentId?:string;gatewayRefundId?:string;amount?:number;currency?:string};
const json=(value:unknown,status=200)=>Response.json(value,{status});

export async function GET(request:Request){try{const bookingId=(new URL(request.url).searchParams.get("bookingId")||"").trim();if(!bookingId)return json({error:"Booking is required"},400);const actor=await resolveActor(request);requirePermission(actor,"bookings.view");const db=await database();const work=await db.prepare("SELECT provider_id FROM provider_work_orders WHERE booking_id=?").bind(bookingId).first<Record<string,unknown>>();if(!work)return json({error:"Provider work order not found"},404);await requireProviderOwnership(db,actor,String(work.provider_id));return json({data:await getPostServicePaymentRequest(db,{bookingId,providerId:String(work.provider_id)})});}catch(error){return authError(error,"Unable to load post-service payment request");}}

export async function POST(request:Request){try{
  const input=await request.json() as Input;if(!input.bookingId||!input.action)return json({error:"Booking and action are required"},400);const db=await database();await ensurePaymentReconciliationTables(db);
  if(input.action==="request_after_service"){const actor=await resolveActor(request);requirePermission(actor,"bookings.view");const work=await db.prepare("SELECT provider_id FROM provider_work_orders WHERE booking_id=?").bind(input.bookingId).first<Record<string,unknown>>();if(!work)return json({error:"Provider work order not found"},404);const providerId=String(work.provider_id);await requireProviderOwnership(db,actor,providerId);const{env}=await import("cloudflare:workers");const runtime=env as unknown as Record<string,unknown>;const data=await createPostServicePaymentRequest(db,runtime,{bookingId:input.bookingId,providerId,actorId:actor.email});await securityAudit(db,actor,"grooming.payment_request.create","booking",input.bookingId,"completed",{providerId,providerReference:data.providerReference,sandboxOnly:true,capturePerformed:false});return json({data},201);}
  const actor=await authorize(request,"payments.manage");const{env}=await import("cloudflare:workers");const runtime=env as unknown as Record<string,unknown>;if(String(runtime.PAWSPACE_PAYMENT_ENV||"sandbox").toLowerCase()!=="sandbox")return json({error:"Payment sandbox is disabled outside sandbox"},403);
  const payment=await db.prepare("SELECT id,amount,currency,status FROM booking_payments WHERE booking_id=?").bind(input.bookingId).first<Record<string,unknown>>();if(!payment)return json({error:"Canonical payment record not found"},404);

  if(input.action==="create_order"){
    const existing=await db.prepare("SELECT gateway_order_id FROM payment_gateway_links WHERE booking_id=? AND status='active'").bind(input.bookingId).first<Record<string,unknown>>();if(existing?.gateway_order_id)return json({data:{bookingId:input.bookingId,paymentId:String(payment.id),gatewayOrderId:String(existing.gateway_order_id),environment:"sandbox",duplicatePrevented:true}});
    if(!runtime.RAZORPAY_KEY_ID_SANDBOX||!runtime.RAZORPAY_KEY_SECRET_SANDBOX)return json({error:"configuration_required",detail:"Add Razorpay test-mode key ID and secret before creating a real sandbox order"},503);
    const order=await createSandboxOrder(runtime,{bookingId:input.bookingId,paymentId:String(payment.id),amount:Number(payment.amount||0),currency:String(payment.currency||"INR")});const gatewayOrderId=String(order.id);const result=await linkSandboxGatewayOrder(db,{bookingId:input.bookingId,gatewayOrderId,actorId:actor.email});await securityAudit(db,actor,"grooming.payment_sandbox.create_order","booking",input.bookingId,"completed",{gatewayOrderId,amount:payment.amount,currency:payment.currency});return json({data:{...result,environment:"sandbox",gatewayStatus:String(order.status||"created"),amountSubunits:Number(order.amount||0)}},201);
  }

  if(input.action==="initiate_refund"){
    if(!runtime.RAZORPAY_KEY_ID_SANDBOX||!runtime.RAZORPAY_KEY_SECRET_SANDBOX)return json({error:"configuration_required",detail:"Add Razorpay test-mode credentials before initiating a sandbox refund"},503);
    const link=await db.prepare("SELECT gateway_order_id,gateway_payment_id FROM payment_gateway_links WHERE booking_id=?").bind(input.bookingId).first<Record<string,unknown>>();if(!link?.gateway_payment_id)return json({error:"A captured Razorpay sandbox payment ID is required before refund"},409);
    const refund=await db.prepare("SELECT * FROM booking_refund_cases WHERE booking_id=? ORDER BY created_at DESC LIMIT 1").bind(input.bookingId).first<Record<string,unknown>>();if(!refund)return json({error:"Create and approve an internal refund case before gateway refund"},409);if(String(refund.status)==="processed")return json({data:{bookingId:input.bookingId,refundCaseId:String(refund.id),gatewayRefundId:refund.gateway_reference,status:"processed",duplicatePrevented:true}});
    const result=await createSandboxRefund(runtime,{bookingId:input.bookingId,paymentId:String(payment.id),gatewayPaymentId:String(link.gateway_payment_id),refundCaseId:String(refund.id),amount:Number(refund.amount||0)});const gatewayRefundId=String(result.id),now=Date.now();await db.prepare("UPDATE booking_refund_cases SET status='processing',gateway_reference=?,updated_at=? WHERE id=?").bind(gatewayRefundId,now,refund.id).run();await db.prepare("UPDATE payment_reconciliation_records SET gateway_status='refund_requested',reconciliation_status='pending_refund',updated_at=? WHERE payment_id=?").bind(now,payment.id).run();await securityAudit(db,actor,"grooming.payment_sandbox.initiate_refund","booking",input.bookingId,"completed",{refundCaseId:refund.id,gatewayRefundId,amount:refund.amount});return json({data:{bookingId:input.bookingId,refundCaseId:String(refund.id),gatewayRefundId,status:String(result.status||"processing"),environment:"sandbox"}},201);
  }

  if(input.action==="link_order"){
    const gatewayOrderId=(input.gatewayOrderId||`order_uat_${crypto.randomUUID().replaceAll("-","").slice(0,14)}`).trim();const result=await linkSandboxGatewayOrder(db,{bookingId:input.bookingId,gatewayOrderId,actorId:actor.email});await securityAudit(db,actor,"grooming.payment_sandbox.link_order","booking",input.bookingId,"completed",{gatewayOrderId});return json({data:{...result,environment:"sandbox",synthetic:true}},201);
  }

  if(!input.eventType)return json({error:"Event type is required"},400);const link=await db.prepare("SELECT gateway_order_id,gateway_payment_id FROM payment_gateway_links WHERE booking_id=?").bind(input.bookingId).first<Record<string,unknown>>();if(!link)return json({error:"Link a sandbox gateway order first"},409);
  const amount=Number.isFinite(Number(input.amount))?Number(input.amount):Number(payment.amount||0),eventId=(input.eventId||`evt_uat_${crypto.randomUUID().replaceAll("-","").slice(0,16)}`).trim(),gatewayPaymentId=(input.gatewayPaymentId||String(link.gateway_payment_id||`pay_uat_${crypto.randomUUID().replaceAll("-","").slice(0,14)}`)).trim(),gatewayRefundId=input.eventType.startsWith("refund.")?(input.gatewayRefundId||`rfnd_uat_${crypto.randomUUID().replaceAll("-","").slice(0,14)}`).trim():undefined;
  const result=await processGatewayEvent(db,{provider:"razorpay",environment:"sandbox",eventId,eventType:input.eventType,bookingId:input.bookingId,gatewayOrderId:String(link.gateway_order_id),gatewayPaymentId,gatewayRefundId,amountSubunits:Math.round(amount*100),currency:input.currency||String(payment.currency||"INR"),createdAt:Date.now(),signatureVerified:true,payloadHash:`uat:${eventId}`,detail:{source:"staff_sandbox_simulator",actor:actor.email}});await securityAudit(db,actor,"grooming.payment_sandbox.simulate","booking",input.bookingId,"completed",{eventId,eventType:input.eventType,result});return json({data:{eventId,eventType:input.eventType,result,environment:"sandbox",synthetic:true}},201);
}catch(error){return authError(error,"Unable to run Grooming payment sandbox");}}
