import{refuseUnlessGatewayPermits}from"../../../lib/api-gateway";
import{authError,database,requireCustomerOwnership,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission}from"../../../lib/platform-security";
import{getSittingBooking}from"../../../lib/sitting-lifecycle";
import{getSittingProofSnapshot,mutateSittingProof,type SittingProofAction,type SittingProofInput}from"../../../lib/sitting-proof-governance";

type Body=Omit<SittingProofInput,"actorId">;
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
const providerActions=new Set<SittingProofAction>(["prepare_media","record_update","record_medication","report_incident"]);
const staffActions=new Set<SittingProofAction>(["sandbox_finalize_media","record_media_scan","revoke_media","resolve_incident"]);
const customerActions=new Set<SittingProofAction>(["acknowledge_incident"]);

export async function GET(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const url=new URL(request.url),bookingId=String(url.searchParams.get("bookingId")||"").trim(),scope=String(url.searchParams.get("scope")||"provider");if(!bookingId)return json({error:"Booking ID is required"},400);const db=await database(),actor=await resolveActor(request),booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);if(scope==="customer"){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,String(booking.customer_id));}else if(hasPermission(actor.permissions,"bookings.manage")){requirePermission(actor,"bookings.view");}else{requirePermission(actor,"bookings.view");await requireProviderOwnership(db,actor,String(booking.provider_id));}const data=await getSittingProofSnapshot(db,bookingId);return json({data,scope,sandboxOnly:true});}catch(error){return authError(error,"Unable to load Sitting proof records");}}

export async function POST(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const body=await request.json() as Body,bookingId=String(body.bookingId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!bookingId||!action||!idempotencyKey)return json({error:"Booking, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request),booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);if(providerActions.has(action)){requirePermission(actor,"bookings.view");if(!hasPermission(actor.permissions,"bookings.manage"))await requireProviderOwnership(db,actor,String(booking.provider_id));}else if(customerActions.has(action)){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,String(booking.customer_id));}else if(staffActions.has(action)){requirePermission(actor,"bookings.manage");}else return json({error:"Unsupported Sitting proof action"},400);const result=await mutateSittingProof(db,{...body,bookingId,action,idempotencyKey,actorId:actor.email});await securityAudit(db,actor,`sitting.proof.${action}`,"canonical_booking",bookingId,"completed",{providerId:booking.provider_id,customerId:booking.customer_id,sandboxOnly:true,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented)});return json({data:result,sandboxOnly:true},action==="report_incident"?202:200);}catch(error){return authError(error,"Unable to update Sitting proof records");}}