import{authError,database,requireCustomerOwnership,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission}from"../../../lib/platform-security";
import{getSittingBooking}from"../../../lib/sitting-lifecycle";
import{getSittingProofSnapshot,mutateSittingProof,receiveSittingMediaUpload,type SittingProofAction,type SittingProofInput}from"../../../lib/sitting-proof-governance";
import{readPartnerProofUpload}from"../../../lib/partner-proof-upload";

type Body=Omit<SittingProofInput,"actorId">;
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
const providerActions=new Set<SittingProofAction>(["prepare_media","record_update","record_medication","report_incident"]);
const staffActions=new Set<SittingProofAction>(["sandbox_finalize_media","record_media_scan","revoke_media","resolve_incident"]);
const customerActions=new Set<SittingProofAction>(["acknowledge_incident"]);
const SITTING_UPLOAD_MAX_BYTES=10_000_000;

export async function GET(request:Request){try{const url=new URL(request.url),bookingId=String(url.searchParams.get("bookingId")||"").trim(),scope=String(url.searchParams.get("scope")||"provider");if(!bookingId)return json({error:"Booking ID is required"},400);const db=await database(),actor=await resolveActor(request),booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);if(scope==="customer"){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,String(booking.customer_id));}else if(hasPermission(actor.permissions,"bookings.manage")){requirePermission(actor,"bookings.view");}else{requirePermission(actor,"bookings.view");await requireProviderOwnership(db,actor,String(booking.provider_id));}const data=await getSittingProofSnapshot(db,bookingId);return json({data,scope,sandboxOnly:true});}catch(error){return authError(error,"Unable to load Sitting proof records");}}

export async function POST(request:Request){try{const body=await request.json() as Body,bookingId=String(body.bookingId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!bookingId||!action||!idempotencyKey)return json({error:"Booking, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request),booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);if(providerActions.has(action)){requirePermission(actor,"bookings.view");if(!hasPermission(actor.permissions,"bookings.manage"))await requireProviderOwnership(db,actor,String(booking.provider_id));}else if(customerActions.has(action)){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,String(booking.customer_id));}else if(staffActions.has(action)){requirePermission(actor,"bookings.manage");}else return json({error:"Unsupported Sitting proof action"},400);const result=await mutateSittingProof(db,{...body,bookingId,action,idempotencyKey,actorId:actor.email});await securityAudit(db,actor,`sitting.proof.${action}`,"canonical_booking",bookingId,"completed",{providerId:booking.provider_id,customerId:booking.customer_id,sandboxOnly:true,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented)});return json({data:result,sandboxOnly:true},action==="report_incident"?202:200);}catch(error){return authError(error,"Unable to update Sitting proof records");}}

/**
 * [PARTNER-02] The sitter's upload: PUT the photo bytes with the media id and single-use token that
 * prepare_media returned. The server measures the bytes against the prepared declaration and moves the
 * asset to quarantine, awaiting a staff scan decision (record_media_scan). Nothing here approves media.
 */
export async function PUT(request:Request){try{const db=await database(),actor=await resolveActor(request);requirePermission(actor,"bookings.view");const bookingId=String(new URL(request.url).searchParams.get("bookingId")||"").trim(),mediaId=String(request.headers.get("x-pawspace-media-id")||"").trim(),uploadToken=String(request.headers.get("x-pawspace-upload-token")||"").trim();if(!bookingId||!mediaId||!uploadToken)return json({error:"Booking ID, media ID and upload token are required"},400);const booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);await requireProviderOwnership(db,actor,String(booking.provider_id));const upload=await readPartnerProofUpload(request,SITTING_UPLOAD_MAX_BYTES),result=await receiveSittingMediaUpload(db,{bookingId,mediaId,uploadToken,...upload,actorId:actor.email});await securityAudit(db,actor,"sitting.proof.upload_media","canonical_booking",bookingId,"completed",{providerId:booking.provider_id,mediaId,sizeBytes:upload.bytes.byteLength,objectStored:result.objectStored,verifiedBy:"server_digest",sandboxOnly:true});return json({data:result,sandboxOnly:true});}catch(error){return authError(error,"Unable to upload Sitting proof photo");}}
