name = "pawspace-tech-platform"
main = "worker/index.ts"
compatibility_date = "2026-05-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["*/5 * * * *", "*/15 * * * *", "15 2 * * *", "30 2 * * *"]

[[ratelimits]]
name = "PUBLIC_API_RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 100
period = 60
