-- LOE closure: canonical D1 ownership for communications, AI conversations/handoffs and Haptik.
-- Runtime ensure*Tables guards remain temporarily as idempotent compatibility checks; deployment schema
-- ownership is now represented in the committed Drizzle migration chain.

CREATE TABLE IF NOT EXISTS communication_policies (id TEXT PRIMARY KEY,city_id TEXT NOT NULL,zone_id TEXT,enforcement_mode TEXT NOT NULL DEFAULT 'observe',quiet_start_hour INTEGER NOT NULL DEFAULT 21,quiet_end_hour INTEGER NOT NULL DEFAULT 8,promotional_cap_7d INTEGER NOT NULL DEFAULT 3,max_attempts INTEGER NOT NULL DEFAULT 5,retry_base_minutes INTEGER NOT NULL DEFAULT 5,active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,effective_from TEXT NOT NULL,effective_to TEXT,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_communication_policy_lookup ON communication_policies(city_id,zone_id,active,effective_from,effective_to);
CREATE TABLE IF NOT EXISTS communication_threads (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,booking_id TEXT,lead_id TEXT,ticket_id TEXT,status TEXT NOT NULL DEFAULT 'open',assigned_to TEXT,sla_due_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_communication_threads_customer ON communication_threads(customer_id,updated_at);
CREATE TABLE IF NOT EXISTS communication_participants (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,participant_type TEXT NOT NULL,participant_id TEXT NOT NULL,display_ref TEXT,role TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(thread_id,participant_type,participant_id));
CREATE TABLE IF NOT EXISTS communication_messages (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,booking_id TEXT,lead_id TEXT,ticket_id TEXT,direction TEXT NOT NULL,channel TEXT NOT NULL,purpose TEXT NOT NULL,template_key TEXT NOT NULL,payload_json TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,provider_reference TEXT,idempotency_key TEXT NOT NULL UNIQUE,policy_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_communication_messages_thread ON communication_messages(thread_id,created_at);
CREATE TABLE IF NOT EXISTS communication_outbox (message_id TEXT PRIMARY KEY,status TEXT NOT NULL,next_attempt_at INTEGER NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,max_attempts INTEGER NOT NULL,last_error TEXT,locked_at INTEGER,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS communication_message_delivery_events (id TEXT PRIMARY KEY,message_id TEXT NOT NULL,provider TEXT NOT NULL,event_id TEXT NOT NULL,event_type TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,UNIQUE(provider,event_id));
CREATE TABLE IF NOT EXISTS communication_dead_letters (id TEXT PRIMARY KEY,message_id TEXT NOT NULL,reason TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,resolved_at INTEGER,resolved_by TEXT);
CREATE TABLE IF NOT EXISTS communication_preferences (customer_id TEXT PRIMARY KEY,service_updates INTEGER,marketing INTEGER,preferred_channel TEXT,timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',source TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS customer_contact_preferences (customer_id TEXT PRIMARY KEY,marketing_consent INTEGER NOT NULL DEFAULT 0,service_consent INTEGER NOT NULL DEFAULT 1,whatsapp_consent INTEGER NOT NULL DEFAULT 0,sms_consent INTEGER NOT NULL DEFAULT 0,email_consent INTEGER NOT NULL DEFAULT 0,opt_out INTEGER NOT NULL DEFAULT 0,source TEXT NOT NULL DEFAULT 'customer',updated_by TEXT NOT NULL DEFAULT 'system',updated_at INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS ai_conversation_sessions (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL UNIQUE,customer_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ai_active',provider TEXT NOT NULL DEFAULT 'not_connected',provider_status TEXT NOT NULL DEFAULT 'not_connected',model_ref TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ai_conversation_turns (id TEXT PRIMARY KEY,session_id TEXT NOT NULL,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,input_message_id TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,channel TEXT NOT NULL,intent_code TEXT NOT NULL,intent_confidence REAL NOT NULL,context_id TEXT NOT NULL,provider TEXT NOT NULL,model_ref TEXT,output_text TEXT NOT NULL,latency_ms INTEGER NOT NULL DEFAULT 0,input_tokens INTEGER,output_tokens INTEGER,cost_minor INTEGER,policy_decision TEXT NOT NULL,outcome TEXT NOT NULL,handoff_reason TEXT,created_at INTEGER NOT NULL,completed_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ai_turn_reservations (idempotency_key TEXT PRIMARY KEY,owner_token TEXT NOT NULL,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,input_message_id TEXT NOT NULL,channel TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'processing',turn_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS ai_conversation_turn_thread_idx ON ai_conversation_turns(thread_id,created_at);
CREATE TABLE IF NOT EXISTS ai_handoffs (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,session_id TEXT,reason TEXT NOT NULL,confidence REAL,queue_code TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',summary_json TEXT NOT NULL,requested_by TEXT NOT NULL,taken_over_by TEXT,resumed_by TEXT,created_at INTEGER NOT NULL,taken_over_at INTEGER,resumed_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS ai_handoff_active_thread_idx ON ai_handoffs(thread_id) WHERE status IN ('queued','staff_active');
CREATE INDEX IF NOT EXISTS ai_handoff_queue_idx ON ai_handoffs(status,queue_code,created_at);
CREATE TABLE IF NOT EXISTS ai_handoff_events (id TEXT PRIMARY KEY,handoff_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_email TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS crm_contacts (id TEXT PRIMARY KEY,name TEXT NOT NULL,primary_phone TEXT NOT NULL,secondary_phone TEXT,email TEXT,area TEXT,pet_names TEXT,pet_summary TEXT,stage TEXT NOT NULL DEFAULT 'New lead',owner TEXT DEFAULT 'Unassigned',source TEXT DEFAULT 'Website',lifetime_value REAL DEFAULT 0,next_action TEXT,opportunity TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS lead_work_items (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,source TEXT NOT NULL,service TEXT NOT NULL,owner TEXT NOT NULL,manager TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',stage TEXT NOT NULL DEFAULT 'day_1',work_day INTEGER NOT NULL DEFAULT 1,assigned_at INTEGER NOT NULL,first_action_due_at INTEGER NOT NULL,manager_alert_at INTEGER NOT NULL,first_action_at INTEGER,call_attempts INTEGER NOT NULL DEFAULT 0,whatsapp_attempts INTEGER NOT NULL DEFAULT 0,last_outcome TEXT,next_action_at INTEGER,recycle_at INTEGER,recycle_cycle INTEGER NOT NULL DEFAULT 0,opt_out INTEGER NOT NULL DEFAULT 0,converted_booking_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS lead_work_items_customer_idx ON lead_work_items(customer_id,status,created_at);
CREATE TABLE IF NOT EXISTS lead_callbacks (id TEXT PRIMARY KEY,lead_id TEXT,phone TEXT NOT NULL,name TEXT,preferred_at INTEGER,reason TEXT,status TEXT NOT NULL DEFAULT 'requested',source TEXT NOT NULL,requested_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS haptik_lead_captures (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,crm_contact_id TEXT NOT NULL,lead_id TEXT NOT NULL,phone TEXT NOT NULL,name TEXT,service TEXT,city TEXT,source TEXT NOT NULL,qualification_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS haptik_callback_requests (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,callback_id TEXT NOT NULL,lead_id TEXT,phone TEXT NOT NULL,preferred_at INTEGER,reason TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS haptik_booking_requests (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,lead_id TEXT,phone TEXT NOT NULL,name TEXT,service_code TEXT NOT NULL,city_id TEXT,zone_id TEXT,preferred_slot TEXT,pet_name TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'requested',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS haptik_booking_requests_status_idx ON haptik_booking_requests(status,created_at);
CREATE TABLE IF NOT EXISTS haptik_outbound_calls (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,campaign TEXT NOT NULL,contact_id TEXT NOT NULL,phone TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',call_ref TEXT,reason TEXT,context_json TEXT NOT NULL DEFAULT '{}',requested_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_haptik_outbound_phone ON haptik_outbound_calls(phone,created_at);
CREATE INDEX IF NOT EXISTS idx_haptik_outbound_campaign ON haptik_outbound_calls(campaign,created_at);
CREATE TABLE IF NOT EXISTS haptik_outbound_readiness (campaign TEXT PRIMARY KEY,ready_count INTEGER NOT NULL DEFAULT 0,refreshed_at INTEGER NOT NULL);
