import{ensurePricingControlRuntime}from"../../../lib/pricing-control-runtime";
import{authError,authorize}from"../../../lib/server-auth";
type Db=Awaited<ReturnType<typeof database>>;
async function database(){const{env}=await import("cloudflare:workers");return env.DB;}
const response=(data:unknown,status=200)=>Response.json(data,{status});
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin pricing write blocked",{status:403});}
async function ensureSchema(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS service_packages (id text PRIMARY KEY NOT NULL,service_code text NOT NULL,package_code text NOT NULL UNIQUE,name text NOT NULL,description text NOT NULL,base_price real NOT NULL,currency text DEFAULT 'INR' NOT NULL,tax_inclusive integer DEFAULT 1 NOT NULL,slot_minutes integer NOT NULL,blocking_minutes integer NOT NULL,active integer DEFAULT 1 NOT NULL,version integer DEFAULT 1 NOT NULL,effective_from text NOT NULL,effective_to text,updated_by text NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS dynamic_pricing_rules (id text PRIMARY KEY NOT NULL,name text NOT NULL,service_code text NOT NULL,package_code text,city_id text,zone_id text,rule_type text NOT NULL,days_json text DEFAULT '[]' NOT NULL,start_time text,end_time text,effective_from text NOT NULL,effective_to text,adjustment_type text NOT NULL,adjustment_value real NOT NULL,coupon_policy text DEFAULT 'stackable' NOT NULL,priority integer DEFAULT 100 NOT NULL,status text DEFAULT 'draft' NOT NULL,version integer DEFAULT 1 NOT NULL,updated_by text NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS pricing_audit_events (id text PRIMARY KEY NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,action text NOT NULL,before_json text,after_json text NOT NULL,actor_id text NOT NULL,reason text NOT NULL,created_at integer NOT NULL)"),
]);}
// Legacy demo packages: their package_codes are not sent by any customer flow or quote lib
// (the live resolver is keyed by the canonical codes seeded in lib/pricing-control-runtime.ts),
// so they are seeded/kept INACTIVE - the panel must never show a dead knob as "Active".
const legacyDemoPackageIds=["pkg_groom_basic","pkg_groom_makeover","pkg_training_6","pkg_boarding","pkg_sitting"] as const;
const packages=[
 ["pkg_groom_basic","grooming","bath_basic","Bath & Basic (legacy demo)","Bath, hygiene care, nails, ears and minor trim",1899,120,150],
 ["pkg_groom_makeover","grooming","complete_makeover","Complete Makeover (legacy demo)","Bath & Basic plus full haircut and styling",2399,150,180],
 ["pkg_training_6","dog_training","puppy_foundation_6","Puppy Foundation · 6 sessions (legacy demo)","Six private doorstep training sessions",8999,60,105],
 ["pkg_boarding","boarding","standard_home_stay","Standard Home Boarding (legacy demo)","Verified host home with daily care updates",1299,1440,1440],
 ["pkg_sitting","pet_sitting","overnight_sitting","Overnight Pet Sitting (legacy demo)","In-home overnight care with updates",899,720,720],
]as const;
const rules=[
 ["rule_weekend_9","Weekend 9 AM priority slot","grooming",null,"weekend","[0,6]","09:00","11:00","percent",15,"stackable",10],
 ["rule_weekend_pm","Weekend afternoon saver","grooming",null,"weekend","[0,6]","13:00","17:00","percent",-10,"stackable",20],
 ["rule_weekday_value","Weekday value pricing","grooming",null,"weekday","[1,2,3,4,5]",null,null,"percent",-8,"stackable",30],
 ["rule_training_travel","Training travel-season offer","dog_training",null,"season","[]",null,null,"percent",-12,"stackable",20],
 ["rule_boarding_peak","Boarding peak-season uplift","boarding",null,"season","[]",null,null,"percent",25,"exclusive",20],
 ["rule_sitting_peak","Sitting peak-season uplift","pet_sitting",null,"season","[]",null,null,"percent",20,"exclusive",20],
]as const;
async function ensureSeed(db:Db){await ensureSchema(db);await ensurePricingControlRuntime(db);const today="2026-08-01",end="2026-12-31",now=Date.now();
 for(const row of packages)await db.prepare("INSERT OR IGNORE INTO service_packages (id,service_code,package_code,name,description,base_price,currency,tax_inclusive,slot_minutes,blocking_minutes,active,version,effective_from,effective_to,updated_by,updated_at) VALUES (?,?,?,?,?,?,'INR',1,?,?,0,1,?,NULL,'founder_seed',?)").bind(...row,today,now).run();
 // One-time idempotent demotion of legacy demo rows that were previously seeded active=1 and never
 // touched by an operator (operator edits change updated_by, so real decisions are preserved).
 await db.prepare(`UPDATE service_packages SET active=0 WHERE active=1 AND updated_by='founder_seed' AND id IN (${legacyDemoPackageIds.map(()=>"?").join(",")})`).bind(...legacyDemoPackageIds).run();
 for(const row of rules)await db.prepare("INSERT OR IGNORE INTO dynamic_pricing_rules (id,name,service_code,package_code,city_id,zone_id,rule_type,days_json,start_time,end_time,effective_from,effective_to,adjustment_type,adjustment_value,coupon_policy,priority,status,version,updated_by,updated_at) VALUES (?,?,?,?,'blr',NULL,?,?,?,?,?,?,?,?,?,?,'published',1,'founder_seed',?)").bind(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],today,row[2]==="grooming"?null:end,row[8],row[9],row[10],row[11],now).run();}
export async function GET(request:Request){try{await authorize(request,"pricing.view");const db=await database();await ensureSeed(db);const[p,r,a]=await Promise.all([db.prepare("SELECT * FROM service_packages ORDER BY service_code,name").all(),db.prepare("SELECT * FROM dynamic_pricing_rules ORDER BY priority,name").all(),db.prepare("SELECT * FROM pricing_audit_events ORDER BY created_at DESC LIMIT 20").all()]);return response({data:{packages:p.results,rules:r.results,audit:a.results}});}catch(error){return authError(error,"Pricing configuration failed");}}
export async function PATCH(request:Request){try{sameOrigin(request);const actor=await authorize(request,"pricing.manage");const db=await database();await ensureSeed(db);const body=await request.json()as{entity:"package"|"rule";id:string;changes:Record<string,unknown>;reason?:string};if(!body.id||!body.reason||body.reason.trim().length<5)return response({error:"Change reason of at least 5 characters is required"},400);const table=body.entity==="package"?"service_packages":"dynamic_pricing_rules";const allowed=body.entity==="package"?["name","description","base_price","slot_minutes","blocking_minutes","active","effective_from","effective_to"]:["name","days_json","start_time","end_time","effective_from","effective_to","adjustment_type","adjustment_value","coupon_policy","priority","status"];const before=await db.prepare(`SELECT * FROM ${table} WHERE id=?`).bind(body.id).first();if(!before)return response({error:"Pricing record not found"},404);const entries=Object.entries(body.changes).filter(([key])=>allowed.includes(key));if(!entries.length)return response({error:"No valid changes supplied"},400);const set=entries.map(([key])=>`${key}=?`).join(",");await db.prepare(`UPDATE ${table} SET ${set},version=version+1,updated_by=?,updated_at=? WHERE id=?`).bind(...entries.map(([,value])=>value),actor.email,Date.now(),body.id).run();const after=await db.prepare(`SELECT * FROM ${table} WHERE id=?`).bind(body.id).first();await db.prepare("INSERT INTO pricing_audit_events (id,entity_type,entity_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(`price_audit_${crypto.randomUUID().slice(0,12)}`,body.entity,body.id,"updated",JSON.stringify(before),JSON.stringify(after),actor.email,body.reason,Date.now()).run();return response({data:after});}catch(error){return authError(error,"Price update failed");}}
export async function POST(request:Request){try{sameOrigin(request);const actor=await authorize(request,"pricing.manage");const db=await database();await ensureSeed(db);const body=await request.json()as{name?:string;serviceCode?:string;packageCode?:string;cityId?:string;zoneId?:string;ruleType?:string;days?:number[];startTime?:string;endTime?:string;effectiveFrom?:string;effectiveTo?:string;adjustmentType?:string;adjustmentValue?:number;couponPolicy?:string;priority?:number};const cityId=String(body.cityId||"").trim(),zoneId=String(body.zoneId||"").trim();if(!body.name||!body.serviceCode||!cityId||!zoneId||!body.ruleType||!body.adjustmentType||body.adjustmentValue===undefined||!body.effectiveFrom)return response({error:"Complete rule details including city and zone are required"},400);const id=`price_rule_${crypto.randomUUID().slice(0,12)}`,now=Date.now();await db.prepare("INSERT INTO dynamic_pricing_rules (id,name,service_code,package_code,city_id,zone_id,rule_type,days_json,start_time,end_time,effective_from,effective_to,adjustment_type,adjustment_value,coupon_policy,priority,status,version,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',1,?,?)").bind(id,body.name,body.serviceCode,body.packageCode??null,cityId,zoneId,body.ruleType,JSON.stringify(body.days??[]),body.startTime??null,body.endTime??null,body.effectiveFrom,body.effectiveTo??null,body.adjustmentType,body.adjustmentValue,body.couponPolicy??"stackable",body.priority??100,actor.email,now).run();await db.prepare("INSERT INTO pricing_audit_events (id,entity_type,entity_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,NULL,?,?,?,?)").bind(`price_audit_${crypto.randomUUID().slice(0,12)}`,"rule",id,"created",JSON.stringify({name:body.name,serviceCode:body.serviceCode,cityId,zoneId,adjustmentType:body.adjustmentType,adjustmentValue:body.adjustmentValue,status:"draft"}),actor.email,"Rule created as draft",now).run();return response({data:{id,status:"draft"}},201);}catch(error){return authError(error,"Rule creation failed");}}
