"use client";
/* eslint-disable react-hooks/exhaustive-deps */
import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import styles from"./partner-mobile.module.css";

type Tab="home"|"jobs"|"track"|"earnings"|"profile";
type Job={bookingId:string;providerId:string;providerName:string;status:string;packageName:string;scheduledStart:string;scheduledEnd:string;zoneId:string;totalAmount:number;customer:{name:string;maskedPhone:string};pets:{name:string;breed:string}[]};
type RouteData={bookingId:string;destinationAddress:string;navigationUrl:string;providerLocation:{lat:number;lng:number;accuracyMeters?:number}|null;route?:{status:string;distanceMeters?:number;durationSeconds?:number;error?:string}};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const when=(s:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(s));
const km=(m?:number)=>`${((m||0)/1000).toFixed(1)} km`;
const mins=(s?:number)=>`${Math.max(1,Math.round((s||0)/60))} min`;

export default function PartnerMobile(){
 const[tab,setTab]=useState<Tab>("home"),[providerId,setProviderId]=useState(""),[jobs,setJobs]=useState<Job[]>([]),[selectedId,setSelectedId]=useState(""),[route,setRoute]=useState<RouteData|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[available,setAvailable]=useState(true);
 const selected=useMemo(()=>jobs.find(j=>j.bookingId===selectedId)||jobs[0]||null,[jobs,selectedId]);
 const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2200)};
 const loadJobs=async(id=providerId)=>{if(!id)return;const r=await fetch(`/api/partner-grooming-jobs?providerId=${encodeURIComponent(id)}`,{cache:"no-store"});const b=await r.json() as {jobs?:Job[];error?:string};if(!r.ok)throw new Error(b.error||"Unable to load jobs");const next=b.jobs||[];setJobs(next);setSelectedId(v=>v&&next.some(j=>j.bookingId===v)?v:(next[0]?.bookingId||""));};
 useEffect(()=>{let active=true;fetch("/api/identity-session",{cache:"no-store"}).then(async r=>{const b=await r.json() as {data?:{subjectType?:string;subjectId?:string};error?:string};if(!r.ok||b.data?.subjectType!=="provider"||!b.data.subjectId)throw new Error(b.error||"Verified provider identity required");return b.data.subjectId;}).then(async id=>{if(!active)return;setProviderId(id);await loadJobs(id);}).catch(e=>active&&setError(e instanceof Error?e.message:"Unable to load provider"));return()=>{active=false};},[]);
 const loadRoute=async()=>{if(!selected)return;setBusy(true);setError("");try{const r=await fetch(`/api/grooming-route?bookingId=${encodeURIComponent(selected.bookingId)}&providerId=${encodeURIComponent(selected.providerId)}`,{cache:"no-store"});const b=await r.json() as {data?:RouteData;error?:string};if(!r.ok||!b.data)throw new Error(b.error||"Route not available yet");setRoute(b.data);}catch(e){setError(e instanceof Error?e.message:"Unable to load route");}finally{setBusy(false)}};
 const captureGps=()=>{if(!selected)return;if(!navigator.geolocation){setError("Location is not supported on this device");return;}setBusy(true);setError("");navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch("/api/grooming-route",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId:selected.bookingId,providerId:selected.providerId,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMeters:p.coords.accuracy,capturedAt:p.timestamp})});const b=await r.json() as {data?:RouteData;error?:string};if(!r.ok||!b.data)throw new Error(b.error||"Unable to update GPS");setRoute(b.data);flash("GPS updated for this booking");}catch(e){setError(e instanceof Error?e.message:"Unable to update GPS");}finally{setBusy(false)}},e=>{setBusy(false);setError(e.message||"Location permission denied")},{enableHighAccuracy:true,timeout:15000,maximumAge:30000});};
 return <main className={styles.stage}>{notice&&<div className={styles.toast}>✓ {notice}</div>}<section className={styles.phone}>
  <header className={styles.top}><Link href="/partner" className={styles.brand}><b>paw</b><span>space</span><small>partner</small></Link><button className={styles.status} onClick={()=>{setAvailable(a=>{const next=!a;flash(next?"You are now available for jobs":"You are now offline. UAT does not stop live assignment yet.");return next;})}}><i/>{available?"Available":"Offline"}</button></header>
  <section className={styles.content}>
   {tab==="home"&&<><div className={styles.greeting}><small>PAWSPACE PARTNER</small><h1>Good morning 👋</h1><p>{providerId?`Provider ${providerId}`:"Resolving verified provider identity…"}</p></div><section className={styles.hero}><div><small>NEXT ASSIGNMENT</small><h2>{selected?.packageName||"No assignment yet"}</h2><p>{selected?`${selected.pets.map(p=>p.name).join(", ")} · ${selected.zoneId}`:"Your assigned work will appear here."}</p>{selected&&<><b>{when(selected.scheduledStart)}</b><button onClick={()=>{setTab("track");void loadRoute()}}>Start journey & tracking →</button></>}</div><span>⌖</span></section><div className={styles.metrics}><article><small>Today</small><b>{jobs.length}</b><span>jobs</span></article><article><small>Earnings</small><b>{money(jobs.reduce((s,j)=>s+j.totalAmount,0))}</b><span>assigned value</span></article><article><small>Rating</small><b>4.8 ★</b><span>verified</span></article></div><h3 className={styles.sectionTitle}>Today’s work</h3>{jobs.slice(0,3).map(j=><button key={j.bookingId} className={styles.jobCard} onClick={()=>{setSelectedId(j.bookingId);setTab("jobs")}}><div><small>{when(j.scheduledStart)}</small><b>{j.packageName}</b><span>{j.pets.map(p=>p.name).join(", ")} · {j.zoneId}</span></div><em>{j.status.replaceAll("_"," ")}</em></button>)}</>}
   {tab==="jobs"&&<><div className={styles.greeting}><small>ASSIGNED WORK</small><h1>Bookings</h1><p>Customer contact remains masked until the governed service workflow allows it.</p></div>{jobs.map(j=><button key={j.bookingId} className={`${styles.jobCard} ${selected?.bookingId===j.bookingId?styles.selected:""}`} onClick={()=>setSelectedId(j.bookingId)}><div><small>{when(j.scheduledStart)} → {when(j.scheduledEnd)}</small><b>{j.packageName}</b><span>{j.pets.map(p=>`${p.name}${p.breed?` · ${p.breed}`:""}`).join(" | ")}</span><span>{j.customer.name} · {j.customer.maskedPhone}</span></div><em>{j.status.replaceAll("_"," ")}</em></button>)}{selected&&<button className={styles.primary} onClick={()=>{setTab("track");void loadRoute()}}>Open GPS tracking</button>}</>}
   {tab==="track"&&<><div className={styles.greeting}><small>GPS & ETA</small><h1>Track journey</h1><p>Location is captured only when you tap the GPS button. Continuous background tracking is not enabled in UAT.</p></div>{selected?<><section className={styles.mapCard}><div className={styles.mapVisual}><span>YOU</span><i>••••••••••</i><b>PET</b></div><h2>{selected.packageName}</h2><p>{route?.destinationAddress||"Load the customer doorstep address for this booking."}</p>{route?.route?.status==="configured"&&<div className={styles.eta}><b>{mins(route.route.durationSeconds)}</b><span>{km(route.route.distanceMeters)} away</span></div>}<div className={styles.trackActions}><button disabled={busy} onClick={captureGps}>{busy?"Locating…":"Use my GPS & calculate ETA"}</button><button disabled={busy} onClick={()=>void loadRoute()}>Refresh route</button></div>{route?.navigationUrl&&<a href={route.navigationUrl} target="_blank" rel="noreferrer">Open turn-by-turn navigation ↗</a>}{route?.route?.status==="configuration_required"&&<small>Navigation is available; Google Routes ETA awaits the UAT server key.</small>}</section><section className={styles.safety}><b>Safety controls</b><span>✓ High-accuracy GPS requested</span><span>✓ Booking/provider identity scoped</span><span>✓ No financial penalty is triggered by GPS alone</span><span>✓ Customer phone stays masked</span></section></>:<div className={styles.empty}>No assigned booking available for tracking.</div>}</>}
   {tab==="earnings"&&<><div className={styles.greeting}><small>PARTNER FINANCE</small><h1>Earnings</h1><p>UAT figures only. No live payout or money movement.</p></div><section className={styles.wallet}><small>ASSIGNED SERVICE VALUE</small><h2>{money(jobs.reduce((s,j)=>s+j.totalAmount,0))}</h2><span>{jobs.length} current work orders</span></section>{jobs.map(j=><div key={j.bookingId} className={styles.earningRow}><span><b>{j.packageName}</b><small>{when(j.scheduledStart)}</small></span><strong>{money(j.totalAmount)}</strong></div>)}</>}
   {tab==="profile"&&<><div className={styles.profile}><div>AK</div><h1>Arjun Kumar</h1><p>Verified PawSpace partner</p><span>Groomer · Bengaluru</span></div><section className={styles.menu}>{["Availability & service zones","Identity & verification","Bank & payout details","Quality & reviews","Learning & certification","Help & support"].map(x=><button key={x} onClick={()=>flash(`${x} is managed in the full partner operations workspace below.`)}>{x}<span>›</span></button>)}</section><Link className={styles.desktopLink} href="/partner-app">Open full partner operations workspace</Link><div style={{display:"flex",gap:8,marginTop:8,fontSize:11}}><Link href="/groomer">Classic Groomer workspace</Link><Link href="/trainer">Classic Trainer workspace</Link></div></>}
   {error&&<div className={styles.error}>{error}</div>}
  </section>
  <nav className={styles.bottom}>{[["home","⌂","Home"],["jobs","▣","Jobs"],["track","⌖","Track"],["earnings","₹","Earnings"],["profile","○","Profile"]].map(([id,icon,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>{setTab(id as Tab);if(id==="track")void loadRoute()}}><i>{icon}</i><span>{label}</span></button>)}</nav>
 </section></main>;
}
