import test from "node:test";
import assert from "node:assert/strict";
import {installWorkersHooks} from "./helpers/module-hooks.mjs";
import {freshCountingD1} from "./helpers/d1-harness.mjs";
installWorkersHooks();
const governance=await import("../lib/intelligence/atlas-executive-governance.ts");
const executor=await import("../lib/intelligence/atlas-low-risk-executor.ts");
const now=2_000_000_000_000;
const proposal=(overrides={})=>({proposalId:"LOW-1",tenantId:"pawspace",domain:"ceo",objective:"Produce internal brief",actionCode:"brief.generate",summary:"Grounded internal brief",evidence:[{source:"canonical",observedAt:now-1000,value:1}],confidence:.95,expectedOutcome:"Founder sees internal brief",policyVersion:governance.DEFAULT_ATLAS_DECISION_POLICY.version,...overrides});

test("fresh zero-money internal draft is eligible for governed autonomy",()=>{const result=governance.evaluateAtlasProposal(proposal(),{now});assert.equal(result.risk,"low");assert.equal(result.disposition,"auto_execute_internal");assert.equal(result.autonomousExecution,true);assert.ok(result.reasons.includes("governed_internal_artifact_only"));});

test("low-risk executor persists one idempotent internal artifact and no external mutation",async()=>{const{sqlite,db}=freshCountingD1();const first=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal(),content:{body:"numbers only"},asOf:now});const second=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal(),content:{body:"different replay"},asOf:now+1});assert.equal(first.executed,true);assert.equal(first.externalMutation,false);assert.equal(second.duplicatePrevented,true);assert.equal(second.id,first.id);const row=sqlite.prepare("SELECT action_code,artifact_type,execution_mode,status FROM atlas_operating_artifacts").get();assert.equal(row.action_code,"brief.generate");assert.equal(row.artifact_type,"brief");assert.equal(row.execution_mode,"low_risk_internal_only");assert.equal(row.status,"generated");sqlite.close();});

test("proposal id reuse with changed governed inputs fails closed instead of replaying a stale artifact",async()=>{const{sqlite,db}=freshCountingD1();await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal(),content:{body:"first"},asOf:now});const changed=proposal({evidence:[{source:"canonical",observedAt:now-500,value:2}]});const error=await executor.executeAtlasLowRiskArtifact(db,{proposal:changed,content:{body:"changed"},asOf:now}).then(()=>null,e=>e);assert.equal(error instanceof Response,true);assert.equal(error.status,409);assert.match(await error.text(),/identity collision/);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM atlas_operating_artifacts").get().n,1);sqlite.close();});

test("operating kill switch pauses even eligible internal autonomy",async()=>{const{sqlite,db}=freshCountingD1();await executor.configureAtlasAutonomyEnvelope(db,{enabled:false,actorId:"founder@test",asOf:now});const error=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal(),content:{body:"paused"},asOf:now}).then(()=>null,e=>e);assert.equal(error.status,409);assert.match(await error.text(),/kill switch/);sqlite.close();});

test("hourly execution envelope fails closed at the configured cap",async()=>{const{sqlite,db}=freshCountingD1();await executor.configureAtlasAutonomyEnvelope(db,{maxExecutionsPerHour:1,actorId:"founder@test",asOf:now});await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"CAP-1"}),content:{body:"first"},asOf:now});const error=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"CAP-2"}),content:{body:"second"},asOf:now+1}).then(()=>null,e=>e);assert.equal(error.status,429);assert.match(await error.text(),/hourly/);sqlite.close();});

test("content envelope rejects oversized internal artifacts",async()=>{const{sqlite,db}=freshCountingD1();await executor.configureAtlasAutonomyEnvelope(db,{maxContentBytes:1024,actorId:"founder@test",asOf:now});const error=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"BIG-1"}),content:{body:"x".repeat(2000)},asOf:now}).then(()=>null,e=>e);assert.equal(error.status,413);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM atlas_operating_artifacts").get().n,0);sqlite.close();});

test("generated internal artifacts can be superseded without any external mutation",async()=>{const{sqlite,db}=freshCountingD1();const created=await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"ROLLBACK-1"}),content:{body:"draft"},asOf:now});const rolled=await executor.supersedeAtlasOperatingArtifact(db,{id:created.id,actorId:"founder@test",asOf:now+1});assert.equal(rolled.status,"superseded");assert.equal(rolled.externalMutation,false);assert.equal(sqlite.prepare("SELECT status FROM atlas_operating_artifacts WHERE id=?").get(created.id).status,"superseded");sqlite.close();});

test("successful low-risk execution creates no escalation",async()=>{const{sqlite,db}=freshCountingD1();await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"OK-ESC-0"}),content:{body:"ok"},asOf:now});assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM atlas_operating_escalations").get().n,0);sqlite.close();});

test("governed refusal creates an auditable escalation that can be acknowledged and resolved",async()=>{const{sqlite,db}=freshCountingD1();await executor.configureAtlasAutonomyEnvelope(db,{enabled:false,actorId:"founder@test",asOf:now});await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"ESC-1"}),content:{body:"blocked"},asOf:now}).then(()=>null,e=>e);const row=sqlite.prepare("SELECT id,reason_code,severity,human_attention,status FROM atlas_operating_escalations").get();assert.equal(row.reason_code,"autonomy_paused");assert.equal(row.severity,"critical");assert.equal(row.human_attention,1);assert.equal(row.status,"open");const acknowledged=await executor.updateAtlasOperatingEscalation(db,{id:row.id,status:"acknowledged",actorId:"founder@test",asOf:now+1});assert.equal(acknowledged.status,"acknowledged");const resolved=await executor.updateAtlasOperatingEscalation(db,{id:row.id,status:"resolved",actorId:"founder@test",asOf:now+2});assert.equal(resolved.status,"resolved");assert.equal(resolved.externalMutation,false);sqlite.close();});

test("repeated identical refusals coalesce into one open escalation",async()=>{const{sqlite,db}=freshCountingD1();await executor.configureAtlasAutonomyEnvelope(db,{enabled:false,actorId:"founder@test",asOf:now});for(let i=0;i<3;i++)await executor.executeAtlasLowRiskArtifact(db,{proposal:proposal({proposalId:"ESC-COALESCE"}),content:{body:"blocked"},asOf:now+i}).then(()=>null,e=>e);const rows=sqlite.prepare("SELECT occurrence_count,reason_code,status FROM atlas_operating_escalations").all();assert.equal(rows.length,1);assert.equal(rows[0].occurrence_count,3);assert.equal(rows[0].reason_code,"autonomy_paused");assert.equal(rows[0].status,"open");sqlite.close();});

test("money, external contact, provider assignment and campaign activation never enter low-risk executor",async()=>{const cases=[proposal({proposalId:"M",actionCode:"refund.issue",moneyMovement:true}),proposal({proposalId:"O",actionCode:"followup.draft",externalCommunication:true}),proposal({proposalId:"P",actionCode:"provider.assignment"}),proposal({proposalId:"C",actionCode:"campaign.activate"})];for(const item of cases){const evaluation=governance.evaluateAtlasProposal(item,{now});assert.equal(evaluation.autonomousExecution,false);const{sqlite,db}=freshCountingD1();const error=await executor.executeAtlasLowRiskArtifact(db,{proposal:item,content:{},asOf:now}).then(()=>null,e=>e);assert.equal(error instanceof Response,true);assert.equal(error.status,409);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM atlas_operating_artifacts").get().n,0);sqlite.close();}});
