import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
// Customer paths stay verify-first; legacy/server-attested captured scenarios retain evidence compatibility.
const stay=fs.readFileSync("app/mobile-app/stay-flow.tsx","utf8"),taxi=fs.readFileSync("app/mobile-app/taxi-flow.tsx","utf8"),canonical=fs.readFileSync("app/api/canonical-bookings/route.ts","utf8"),payment=fs.readFileSync("app/api/payment-order/route.ts","utf8"),boarding=fs.readFileSync("lib/boarding-governance.ts","utf8"),sitting=fs.readFileSync("lib/sitting-governance.ts","utf8"),taxiApi=fs.readFileSync("app/api/taxi-bookings/route.ts","utf8");
test("stay material controls are controlled and preserved",()=>{assert.doesNotMatch(stay,/defaultValue=|defaultChecked/);assert.match(stay,/value=\{startTime\}/);assert.match(stay,/healthSafetyNotes:medicalNotes/);assert.match(stay,/behaviourNotes:behaviourSafetyNotes/);assert.match(stay,/requirements/);assert.match(stay,/breed:p\.profile\?\.breed\|\|p\.breed/);assert.match(stay,/vaccinationStatus:p\.vaccinationStatus/);});
test("stay retries use normalized material identity and never self-claim capture",()=>{assert.doesNotMatch(stay,/bookingNonce|Date\.now\(\).*request/);assert.match(stay,/selectedPets\.slice\(\)\.sort\(\)/);assert.match(stay,/status:"created"/);assert.doesNotMatch(stay,/captureSittingQuoteSandbox|status:"captured"/);});
test("boarding and sitting use pending verify-first customer payment while preserving attested captured compatibility",()=>{assert.match(boarding,/paymentStatus!=="created"&&input\.paymentStatus!=="captured"/);assert.match(sitting,/paymentStatus!=="created"&&input\.paymentStatus!=="captured"/);assert.match(canonical,/if\(paymentStatusRecorded==="captured"\)sittingCapture=await requireSittingQuoteSandboxCapture/);assert.match(canonical,/paymentStatus:sittingCapture\?\.status\?\?paymentStatusRecorded/);assert.match(canonical,/sittingPaymentReference:sittingCapture\?\.reference/);});
test("provider work order carries care and safety snapshot",()=>{assert.match(canonical,/customerSelection:\{requirements:input\.pricing\.requirements/);assert.match(canonical,/healthSafetyNotes:input\.pricing\.healthSafetyNotes/);assert.match(canonical,/behaviourNotes:input\.pricing\.behaviourNotes/);});
test("taxi identity includes pet route locations zone and safety",()=>{for(const token of ["pet.id","coverage.cityId","coverage.zoneId","normalized(fresh.originLabel)","normalized(fresh.destinationLabel)","normalized(safetyNotes)","normalized(behaviourNotes)"])assert.match(taxi,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(taxiApi,/customerSelection:input\.safety/);});
test("Razorpay checkout is verify-first and webhook remains capture authority",()=>{assert.match(payment,/verifyRazorpayCheckoutSignature/);assert.match(payment,/awaiting_webhook_capture/);assert.doesNotMatch(payment,/UPDATE booking_payments SET status='captured'/);});