import test from"node:test";
import assert from"node:assert/strict";
import{DatabaseSync}from"node:sqlite";
import fs from"node:fs";

function makeD1(){const sqlite=new DatabaseSync(":memory:");const statement=(sql,args=[])=>({bind:(...bound)=>statement(sql,bound),first:async()=>sqlite.prepare(sql).get(...args)??null,run:async()=>{const info=sqlite.prepare(sql).run(...args);return{success:true,meta:{changes:Number(info.changes||0)}}},all:async()=>({results:sqlite.prepare(sql).all(...args)})});return{sqlite,db:{prepare:sql=>statement(sql),batch:async list=>{const out=[];for(const item of list)out.push(await item.run());return out}}};}
const controls=await import("../lib/control-runtime-switches.ts");
const post=path=>new Request(`https://uat.pawspace.in${path}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});
const get=path=>new Request(`https://uat.pawspace.in${path}`);

async function stopped(code,path){const{db}=makeD1();await controls.setControlRuntimeSwitch(db,{code,enabled:false,reason:"Founder emergency stop",actor:"founder@pawspace.test"});const result=await controls.runtimeControlBlock(db,post(path));assert.ok(result instanceof Response,`${code} must block ${path}`);assert.equal(result.status,503);const body=await result.json();assert.equal(body.control,code);assert.equal(body.code,"runtime_control_active");return db;}

test("all six emergency controls default enabled and require an audited reason",async()=>{const{db}=makeD1();const initial=await controls.listControlRuntimeSwitches(db);assert.equal(initial.length,6);assert.equal(initial.every(item=>item.enabled),true);await assert.rejects(()=>controls.setControlRuntimeSwitch(db,{code:"payment_writes",enabled:false,reason:"no",actor:"founder@pawspace.test"}),/reason of at least 5/i);assert.equal((await controls.listControlRuntimeSwitches(db)).find(item=>item.code==="payment_writes").enabled,true);});

test("payment stop blocks current customer checkout but preserves reads and provider recovery ingress",async()=>{const db=await stopped("payment_writes","/api/customer-checkout");assert.equal(await controls.runtimeControlBlock(db,get("/api/customer-checkout")),null);for(const path of["/api/razorpay-webhook","/api/razorpayx-webhook"])assert.equal(await controls.runtimeControlBlock(db,post(path)),null,`${path} remains available for signed provider recovery`);});

test("voice, messaging, marketing, assignment and scheduling stops cover today's governed write routes",async()=>{for(const [code,paths] of Object.entries({voice_outbound:["/api/voice-outbound","/api/ai-voice-uat"],communications_automation:["/api/crm-automation","/api/haptik-outbound"],marketing_writes:["/api/marketing-control","/api/content-controls"],provider_auto_assignment:["/api/provider-assignment-recovery","/api/provider-capacity-control"],scheduling_automation:["/api/uat-scheduling","/api/scheduling-rules"]})){for(const path of paths)await stopped(code,path)}});

test("unmatched writes and all provider callbacks are not accidentally converted into a global outage",async()=>{const{db}=makeD1();for(const item of controls.CONTROL_SWITCHES)await controls.setControlRuntimeSwitch(db,{code:item.code,enabled:false,reason:"Founder emergency stop",actor:"founder@pawspace.test"});assert.equal(await controls.runtimeControlBlock(db,post("/api/customer-profile")),null);for(const path of["/api/voice-provider-webhook","/api/webhooks/exotel/call-event","/api/whatsapp/meta-webhook","/api/email-provider-webhook","/api/dialler/callback"])assert.equal(await controls.runtimeControlBlock(db,post(path)),null);});

test("the current Worker enforces stops after authentication and before service/business mutation",()=>{const worker=fs.readFileSync(new URL("../worker/index.ts",import.meta.url),"utf8"),gateway=fs.readFileSync(new URL("../lib/api-gateway.ts",import.meta.url),"utf8"),panel=fs.readFileSync(new URL("../app/control/live-governance-panel.tsx",import.meta.url),"utf8");const auth=worker.indexOf("sessionAccess=await authorizePlatformSessionRequest"),stop=worker.indexOf("emergencyBlock=await runtimeControlBlock"),service=worker.indexOf("serviceBlock=await blockDisabledServiceRequest");assert.ok(auth>=0&&stop>auth&&service>stop,"Worker order must be authenticate -> emergency stop -> service business guard");assert.match(gateway,/\/api\/control-runtime-switches.*GET.*audit\.view.*settings\.manage/);assert.match(panel,/mode==="health"&&<EmergencyRuntimeControls\/>/);});
