import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {installWorkersHooks} from './helpers/module-hooks.mjs';
import {salesBriefWorld,asActor,ORIGIN} from './helpers/customer-sales-brief-fixture.mjs';
installWorkersHooks('__BRIEF_UI_DB__','__BRIEF_UI_ENV__');
const {GET}=await import('../app/api/customer-sales-brief/route.ts');
const {POST}=await import('../app/api/customer-sales-brief/overrides/route.ts');
const {createElement}=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');
const {default:CustomerSalesBrief,SalesBriefPanel,loadCustomerSalesBrief,saveCustomerSalesBriefOverride}=await import('../app/team/sales/customer-sales-brief.tsx');
const seeded=()=>salesBriefWorld('__BRIEF_UI_DB__','__BRIEF_UI_ENV__');
const request=(email,seen=[])=>async(url,init={})=>{seen.push({url:String(url),init});return init.method==='POST'?POST(asActor(email,String(url),{...init,headers:{...init.headers,origin:ORIGIN}})):GET(asActor(email,String(url)));};
const render=(response,onSave)=>renderToStaticMarkup(createElement(SalesBriefPanel,{response,onSave}));
test('staff panel uses actual canonical endpoint with dated layers and no automatic contact controls',async()=>{await seeded();const calls=[];const response=await loadCustomerSalesBrief('C','grooming','voice',request('founder@test.invalid',calls));const html=render(response,async()=>{});assert.match(html,/Customer lifecycle: Existing/);assert.match(html,/Current readiness: Warm/);assert.match(html,/Subscription potential/);assert.match(html,/Cross-sell potential/);assert.match(html,/IST/);assert.match(html,/Capture verified/);assert.match(html,/full payment unknown/);assert.match(html,/do not predict whether someone will buy/);assert.match(html,/sends no calls or messages/);assert.ok(!/href="(?:tel:|sms:|https:\/\/wa\.me)/.test(html));assert.match(html,/Save reviewed override/);assert.match(html,/Evidence and reason/);assert.equal(calls[0].init.cache,'no-store');assert.match(calls[0].url,/customerId=C&serviceCode=grooming&channel=voice/);});
test('role-restricted panel has no editable form and explains unavailable financial evidence',async()=>{await seeded();const response=await loadCustomerSalesBrief('C','grooming','voice',request('associate@test.invalid'));const html=render(response,async()=>{});assert.ok(!html.includes('<form'));assert.match(html,/Financial evidence is restricted for this role/);assert.match(html,/customer-management permission/);});
test('UI save helper writes only explained supported override and reloads the same audited brief',async()=>{const w=await seeded(),calls=[],req=request('founder@test.invalid',calls);await saveCustomerSalesBriefOverride({action:'set',customerId:'C',serviceCode:'grooming',dimension:'readiness',value:'hot',reason:'Reviewed request for booking quote',expiresAt:Date.now()+86400000},req);const response=await loadCustomerSalesBrief('C','grooming','voice',req);const html=render(response,async()=>{});assert.match(html,/Current readiness: Hot/);assert.match(html,/Reviewed request for booking quote/);assert.match(html,/expires/);assert.match(html,/Clear override with audit/);assert.equal(w.sqlite.prepare('SELECT count(*) n FROM crm_engine_audit_events').get().n,1);assert.equal(calls[0].url,'/api/customer-sales-brief/overrides');assert.equal(calls[0].init.method,'POST');assert.equal(JSON.parse(calls[0].init.body).action,'set');});
test('unknown sources and opt-out remain visible instead of optimistic offer or payment claims',async()=>{const w=await seeded();w.sqlite.exec('DROP TABLE payment_reconciliation_records');w.sqlite.exec('UPDATE communication_preferences SET marketing=0');const response=await loadCustomerSalesBrief('C','grooming','voice',request('founder@test.invalid'));const html=render(response,async()=>{});assert.match(html,/Payment evidence unavailable/);assert.match(html,/Marketing opt out/);assert.match(html,/Status: Suppressed/);assert.match(html,/offer eligibility: Unknown/);assert.ok(!html.includes('Capture verified'));});
test('component initial render offers scoped service/channel selectors, refresh and explicit loading',async()=>{await seeded();const html=renderToStaticMarkup(createElement(CustomerSalesBrief,{customerId:'C'}));assert.match(html,/Sales preparation/);assert.match(html,/Loading sales brief/);assert.match(html,/Refresh brief/);assert.match(html,/<label>Service/);assert.match(html,/<label>Contact channel/);assert.ok(!html.includes('Save reviewed override'));const page=readFileSync(new URL('../app/team/sales/page.tsx',import.meta.url),'utf8');assert.match(page,/<CustomerSalesBrief key=\{current.customerId\} customerId=\{current.customerId\}/);});
test('failed scope read/save helpers surface server refusal without treating it as successful',async()=>{await seeded();await assert.rejects(loadCustomerSalesBrief('OTHER','grooming','voice',request('associate@test.invalid')));await assert.rejects(saveCustomerSalesBriefOverride({action:'set',customerId:'C',serviceCode:'grooming',dimension:'readiness',value:'hot',reason:'Reviewed request for booking quote',expiresAt:Date.now()+86400000},request('associate@test.invalid')));});

test('an expired displayed brief does not keep claiming current hot readiness or contact eligibility',async()=>{await seeded();const response=await loadCustomerSalesBrief('C','grooming','voice',request('founder@test.invalid'));const html=renderToStaticMarkup(createElement(SalesBriefPanel,{response,asOf:response.data.generatedAt+6*60000}));assert.match(html,/Current readiness: Unknown/);assert.match(html,/Contact review expired/);assert.match(html,/Refresh this brief/);assert.ok(!html.includes('Eligible under the current recorded marketing policy'));});

test('subscription context distinguishes active entitlement from pending purchase and renewal potential',async()=>{const w=await seeded();for(const [id,status] of [['S-A','active'],['S-P','pending_payment']])w.sqlite.prepare('INSERT INTO customer_grooming_subscriptions VALUES(?,?,?,?,?,?,?,?,?)').run(id,'C','PLAN-'+id,status,Date.now()-1000,Date.now()+86400000,0,0,3);const response=await loadCustomerSalesBrief('C','grooming','voice',request('founder@test.invalid'));const html=render(response);assert.match(html,/Recorded Grooming subscriptions/);assert.match(html,/Active entitlement/);assert.match(html,/Pending payment/);assert.match(html,/Not an active entitlement/);assert.match(html,/pending subscription purchase is separate/);});
