import test from "node:test";
import assert from "node:assert/strict";
import{setupJourney,runCompletedJourney,routeCall,sessionCookie}from"./helpers/grooming-journey-harness.mjs";
async function fixture(t){
 const ctx=await setupJourney();t.after(ctx.close);const start=new Date(Date.now()+3*86400000);start.setUTCHours(3,30,0,0);
 const result=await runCompletedJourney(ctx,{customerId:"PREVIEW-CUSTOMER",customerName:"Preview parent",phone:"+919900000616",petSourceId:"PREVIEW-PET",petName:"Milo",cityId:"blr",zoneId:"blr-east",pincode:"560038",latitude:12.9716,longitude:77.5946,preferredProviderId:"groom_arun",groupId:"PREVIEW-GROUP",start:start.toISOString(),stopAfterCapture:false});
 result.customerCookie=await sessionCookie(ctx.db,"customer","PREVIEW-CUSTOMER","customer:PREVIEW-CUSTOMER");
 const path=`/api/customer-grooming-summary?bookingId=${encodeURIComponent(result.bookingId)}`;
 const read=(cookie=result.customerCookie)=>routeCall("../../app/api/customer-grooming-summary/route.ts","GET",path,null,cookie);
 return{...ctx,result,path,read};
}

test("completed customer care includes persisted notes and issued totals without internal fields",async t=>{const f=await fixture(t);const p=await f.read();assert.equal(p.status,200,JSON.stringify(p.body));const data=p.body.data;assert.equal(data.status,"completed");assert.ok(data.care.checklist.length);assert.ok(data.invoice.number);const invoice=f.sqlite.prepare("SELECT * FROM booking_invoices WHERE booking_id=?").get(f.result.bookingId);assert.equal(data.invoice.total,invoice.gross_amount);assert.equal(data.invoice.tax,invoice.tax_amount);assert.deepEqual(Object.keys(data).sort(),["bookingId","care","currency","invoice","packageName","payment","pets","provider","scheduledEnd","scheduledStart","status","total","tracking"]);assert.deepEqual(Object.keys(data.care).sort(),["checklist","notes"]);assert.deepEqual(Object.keys(data.provider).sort(),["id","model","name"]);assert.deepEqual(Object.keys(data.payment).sort(),["amount","method","mode","status"]);assert.ok(Array.isArray(data.pets));});
test("incomplete booking does not expose a premature care or invoice summary",async t=>{const f=await fixture(t);f.sqlite.prepare("UPDATE canonical_bookings SET status='assigned' WHERE id=?").run(f.result.bookingId);const p=await f.read();assert.equal(p.status,200);assert.equal(p.body.data.care,null);assert.equal(p.body.data.invoice,null);});
test("draft invoice and a mismatched invoice owner are not shown to the customer",async t=>{const f=await fixture(t);f.sqlite.prepare("UPDATE booking_invoices SET status='draft' WHERE booking_id=?").run(f.result.bookingId);assert.equal((await f.read()).body.data.invoice,null);f.sqlite.prepare("UPDATE booking_invoices SET status='issued',customer_id='OTHER' WHERE booking_id=?").run(f.result.bookingId);assert.equal((await f.read()).body.data.invoice,null);});
test("another customer cannot read completed care or invoice data",async t=>{const f=await fixture(t),other=await sessionCookie(f.db,"customer","OTHER-SUMMARY","customer:other-summary");const p=await f.read(other);assert.equal(p.status,403);assert.equal(p.body.data,undefined);});
test("customer summary gateway refuses provider sessions",async t=>{const f=await fixture(t),{authorizePlatformSessionRequest}=await import("../lib/session-api-gateway.ts"),cookie=await sessionCookie(f.db,"provider","groom_arun","provider:summary");const own=await authorizePlatformSessionRequest(new Request(`https://uat.pawspace.in${f.path}`,{headers:{cookie:f.result.customerCookie}}),f.db);assert.equal(own.permission,"scheduling.book");const denied=await authorizePlatformSessionRequest(new Request(`https://uat.pawspace.in${f.path}`,{headers:{cookie}}),f.db);assert.equal(denied.status,403);});

test("customer tracking projection never exposes raw provider telemetry and closes after completion",async t=>{const f=await fixture(t);const active=["on_the_way","arrived","in_service"];for(const status of active){f.sqlite.prepare("UPDATE canonical_bookings SET status=? WHERE id=?").run(status,f.result.bookingId);const p=await f.read();assert.equal(p.status,200);assert.deepEqual(Object.keys(p.body.data.tracking).sort(),["distanceKm","etaMinutes","state"]);assert.equal(JSON.stringify(p.body.data.tracking).includes("lat"),false);assert.equal(JSON.stringify(p.body.data.tracking).includes("lng"),false);assert.equal(JSON.stringify(p.body.data.tracking).includes("accuracy"),false);assert.equal(JSON.stringify(p.body.data.tracking).includes("event"),false);}f.sqlite.prepare("UPDATE canonical_bookings SET status='completed' WHERE id=?").run(f.result.bookingId);const done=await f.read();assert.deepEqual(done.body.data.tracking,{state:"ended",etaMinutes:null,distanceKm:null});});

test("stale ETA is not surfaced as live customer tracking",async t=>{const f=await fixture(t);f.sqlite.prepare("UPDATE canonical_bookings SET status='on_the_way' WHERE id=?").run(f.result.bookingId);const event=f.sqlite.prepare("SELECT id FROM universal_provider_location_events WHERE booking_id=? AND trust_state='accepted' ORDER BY server_received_at DESC LIMIT 1").get(f.result.bookingId);assert.ok(event?.id,"journey must have accepted GPS evidence");f.sqlite.prepare("UPDATE route_eta_snapshots SET stale_after=? WHERE booking_id=? AND origin_location_event_id=?").run(Date.now()-1,f.result.bookingId,event.id);const p=await f.read();assert.equal(p.status,200);assert.deepEqual(p.body.data.tracking,{state:"stale",etaMinutes:null,distanceKm:null});});

test("rejected or low-accuracy GPS never becomes live customer tracking",async t=>{const f=await fixture(t);f.sqlite.prepare("UPDATE canonical_bookings SET status='on_the_way' WHERE id=?").run(f.result.bookingId);f.sqlite.prepare("UPDATE universal_provider_location_events SET trust_state='low_accuracy',rejection_reason='accuracy_outside_approved_policy' WHERE booking_id=?").run(f.result.bookingId);const p=await f.read();assert.equal(p.status,200);assert.deepEqual(p.body.data.tracking,{state:"not_sharing",etaMinutes:null,distanceKm:null});});
