import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';
import {humanCallProfile,humanCallPrompt,HUMAN_CALL_ACCEPTANCE,evaluateHumanCallMetrics} from '../lib/elevenlabs-human-call-profile.mjs';
test('human call profiles expose the supported English agent model and comparison models',()=>{assert.equal(humanCallProfile('flash_v2').modelId,'eleven_flash_v2');assert.equal(humanCallProfile('flash_v2_5').modelId,'eleven_flash_v2_5');assert.equal(humanCallProfile('v3_conversational').modelId,'eleven_v3_conversational');assert.equal(humanCallProfile('v3_conversational').stability,0.45);assert.equal(humanCallProfile('v3_conversational').expressiveMode,true);assert.throws(()=>humanCallProfile('unknown'));});
test('phone prompt is interruption friendly and normalizes speech-hostile text',()=>{const p=humanCallPrompt('Existing PawSpace grounding.');for(const phrase of ['short spoken sentences','Ask one question at a time','Let the customer interrupt','rupee amounts','do not invent availability','warm, capable Indian customer-care colleague','do not repeat the same filler'])assert.match(p,new RegExp(phrase,'i'));assert.match(p,/Existing PawSpace grounding/);});
test('human call prompt tuning is idempotent and replaces the legacy robotic block',()=>{const legacy="Base grounding.\n\nYou are Maya, PawSpace's phone sales and service assistant. Sound like a capable human colleague, not a scripted bot. Old rules.";const once=humanCallPrompt(legacy),twice=humanCallPrompt(once);assert.equal((twice.match(/\[PawSpace human-call profile v2\]/g)||[]).length,1);assert.doesNotMatch(twice,/Sound like a capable human colleague/);assert.match(twice,/Base grounding/);});
test('acceptance evaluator pins human-call latency and barge-in targets',()=>{assert.equal(HUMAN_CALL_ACCEPTANCE.ordinaryReplyStartP95Ms,1500);assert.equal(evaluateHumanCallMetrics({replyStartP50Ms:700,replyStartP95Ms:1200,bargeInStopP95Ms:250,maxSilentGapMs:700}).pass,true);assert.equal(evaluateHumanCallMetrics({replyStartP50Ms:700,replyStartP95Ms:1900,bargeInStopP95Ms:250,maxSilentGapMs:700}).pass,false);});

test('tuning workflow checks out code and preserves existing agent configuration',()=>{const y=readFileSync(new URL('../.github/workflows/elevenlabs-provider-preflight.yml',import.meta.url),'utf8');assert.match(y,/tune-grooming-audio:[\s\S]*actions\/checkout@v4/);assert.match(y,/prompt:\{\.\.\.currentPrompt,prompt:humanCallPrompt/);assert.match(y,/tts:\{[\s\S]*\.\.\.currentTts/);assert.match(y,/turn:\{[\s\S]*\.\.\.currentTurn/);assert.match(y,/expressive_mode:profile\.expressiveMode===true/);assert.match(y,/max_duration_seconds:600/);});
test('tuning prioritizes PawSpace ASR keywords before a full existing keyword list',()=>{const y=readFileSync(new URL('../.github/workflows/elevenlabs-provider-preflight.yml',import.meta.url),'utf8');assert.match(y,/const pawspaceKeywords=\['PawSpace'[\s\S]*'UPI'\]/);assert.match(y,/const existingKeywords=Array\.isArray\(currentAsr\.keywords\)/);assert.match(y,/keywords:\[\.\.\.new Set\(\[\.\.\.pawspaceKeywords,\.\.\.existingKeywords\]\)\]\.slice\(0,100\)/);});
