import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {installWorkersHooks} from './helpers/module-hooks.mjs';
installWorkersHooks('__NDEMO_DB__','__NDEMO_ENV__');
const demo=await import('../lib/native-attended-demo.ts');
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const sql=readFileSync(new URL('../drizzle/0046_native_attended_demo_grants.sql',import.meta.url),'utf8');
const actor={email:'tester@pawspace.test',permissions:['settings.manage','customers.manage','communications.call']};
async function world(t){const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());sqlite.exec(sql);const stmt=(sql,args=[])=>({bind:(...a)=>stmt(sql,a),first:async()=>sqlite.prepare(sql).get(...args)||null,run:async()=>({meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}),all:async()=>({results:sqlite.prepare(sql).all(...args)})});const db={prepare:stmt,batch:async items=>{sqlite.exec('BEGIN');try{const r=[];for(const s of items)r.push(await s.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const env={PAWSPACE_DEPLOYMENT_ENV:'staging',PAWSPACE_PAYMENT_ENV:'sandbox',FORBID_PRODUCTION:'true',PAWSPACE_VOICE_PHONE_TESTS_PAUSED:'true',PAWSPACE_VOICE_ENV:'disabled',PAWSPACE_STAGING_BUILD_SHA:'a'.repeat(40),PAWSPACE_NATIVE_DEMO_DATABASE_ID:'staging-db',CF_VERSION_METADATA:{id:'version-a'},PAWSPACE_VOICE_UAT_ALLOWLIST:'9876500088',EXOTEL_API_KEY:'test',EXOTEL_API_TOKEN:'test',EXOTEL_SID:'test',EXOTEL_CALLER_ID:'test',EXOTEL_VOICE_APP_ID:'test',EXOTEL_WEBHOOK_SECRET:'test',AI:{run:async()=>{}},PAWSPACE_VOICE_STATUS_CALLBACK_URL:'https://staging.test/callback',PAWSPACE_VOICE_STREAM_URL:'wss://staging.test/voice/exotel/agentstream'};
const now=Date.now(),token='synthetic-demo-token-'.repeat(3);sqlite.prepare('INSERT INTO native_attended_demo_grants(id,token_hash,actor_id,customer_id,recipient_hash,release_sha,database_id,version_id,issued_at,expires_at,state) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('one',await digest(token),actor.email,'CUS',await digest('9876500088'),env.PAWSPACE_STAGING_BUILD_SHA,'staging-db','version-a',now,now+60000,'ready');return{sqlite,db,env,input:{grantId:'one',token,actor,customerId:'CUS',phone:'9876500088'}};}
test('atomic claim permits only one of two concurrent consumers and audits once',async t=>{const w=await world(t);const results=await Promise.allSettled([demo.claimNativeAttendedDemo(w.db,w.env,w.input),demo.claimNativeAttendedDemo(w.db,w.env,w.input)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM native_attended_demo_audit WHERE event=?').get('claimed').n,1);assert.equal(w.sqlite.prepare('SELECT state FROM native_attended_demo_grants').get().state,'claimed');});
for(const [name,patch] of Object.entries({production:{PAWSPACE_DEPLOYMENT_ENV:'production'},livePayments:{PAWSPACE_PAYMENT_ENV:'live'},unpaused:{PAWSPACE_VOICE_PHONE_TESTS_PAUSED:'false'},wrongRelease:{PAWSPACE_STAGING_BUILD_SHA:'b'.repeat(40)},wrongDB:{PAWSPACE_NATIVE_DEMO_DATABASE_ID:'other'},wrongVersion:{CF_VERSION_METADATA:{id:'other'}},multiRecipient:{PAWSPACE_VOICE_UAT_ALLOWLIST:'9876500088,9876500099'},missingProvider:{EXOTEL_WEBHOOK_SECRET:''},missingAI:{AI:null},wrongStreamPath:{PAWSPACE_VOICE_STREAM_URL:'wss://staging.test/unrelated'}}))test(name+' refuses without consuming',async t=>{const w=await world(t);await assert.rejects(demo.claimNativeAttendedDemo(w.db,{...w.env,...patch},w.input));assert.equal(w.sqlite.prepare('SELECT state FROM native_attended_demo_grants').get().state,'ready');});
for(const name of ['expired','revoked','wrong actor','wrong owner','wrong token'])test(name+' refuses admission',async t=>{const w=await world(t);if(name==='expired')w.sqlite.prepare('UPDATE native_attended_demo_grants SET issued_at=0,expires_at=1').run();if(name==='revoked')w.sqlite.prepare("UPDATE native_attended_demo_grants SET state='revoked'").run();const input={...w.input};if(name==='wrong actor')input.actor={...actor,email:'other@pawspace.test'};if(name==='wrong owner')input.customerId='OTHER';if(name==='wrong token')input.token='x'.repeat(64);await assert.rejects(demo.claimNativeAttendedDemo(w.db,w.env,input));});
test('provider uncertainty and failure do not release a consumed grant',async t=>{const w=await world(t);const c=await demo.claimNativeAttendedDemo(w.db,w.env,w.input);await demo.auditNativeAttendedDemo(w.db,c.callId,'provider_unknown');await assert.rejects(demo.claimNativeAttendedDemo(w.db,w.env,w.input));assert.equal(w.sqlite.prepare('SELECT state FROM native_attended_demo_grants').get().state,'claimed');});
test('native demo restriction survives expiry, revocation and missing grant',async t=>{const w=await world(t);const c=await demo.claimNativeAttendedDemo(w.db,w.env,w.input);for(const change of [()=>{},()=>w.sqlite.prepare("UPDATE native_attended_demo_grants SET state='revoked'").run(),()=>w.sqlite.exec('DROP TABLE native_attended_demo_grants')]){change();await assert.rejects(demo.assertNativeDemoBusinessAllowed(w.db,`THREAD-VOICE-${c.callId}`),e=>e instanceof Response&&e.status===403);}await demo.assertNativeDemoBusinessAllowed(w.db,'THREAD-ORDINARY');});

test('consumed grant cannot be rearmed, deleted, or replaced for the same release/recipient',async t=>{const w=await world(t);await demo.claimNativeAttendedDemo(w.db,w.env,w.input);assert.throws(()=>w.sqlite.prepare("UPDATE native_attended_demo_grants SET state='ready'").run());assert.throws(()=>w.sqlite.prepare('DELETE FROM native_attended_demo_grants').run());assert.throws(()=>w.sqlite.prepare("INSERT INTO native_attended_demo_grants SELECT 'another','another-token',actor_id,customer_id,recipient_hash,release_sha,database_id,version_id,issued_at,expires_at,'ready',NULL,NULL,NULL FROM native_attended_demo_grants").run());});
