import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {assertSourceOnlyAudioReceiptAmendment,assertUnusedAudioBudgetSourceAmendment,unusedAudioBudgetSourceAmendmentBatch} from '../scripts/prepare-next-audio-duration.mjs';
const id='next-ten-audio-additional-usd5-20261002',region='https://api.elevenlabs.io';
const old={sourceSha:'a'.repeat(40),validUntil:1791017991677,cap:10,evidenceReference:'fixed'},next={...old,sourceSha:'b'.repeat(40)},oldJson=JSON.stringify(old),newJson=JSON.stringify(next);
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE next_audio_budget(id TEXT PRIMARY KEY,cap_micros INTEGER,reserved_micros INTEGER,conversations INTEGER,receipt_json TEXT,expires_at INTEGER);CREATE TABLE next_audio_rate_evidence(id TEXT PRIMARY KEY,region TEXT,receipt_json TEXT);CREATE TABLE next_audio_batch_claims(budget_id TEXT);CREATE TABLE next_audio_leases(budget_id TEXT);CREATE TABLE next_audio_attempts(id TEXT);CREATE TABLE next_audio_speech_attempts(id TEXT);`);db.prepare('INSERT INTO next_audio_budget VALUES(?,10000000,0,0,?,?)').run(id,oldJson,old.validUntil);db.prepare('INSERT INTO next_audio_rate_evidence VALUES(?,?,?)').run(id,region,oldJson);return db;}
function apply(db){const batch=unusedAudioBudgetSourceAmendmentBatch(id,region,oldJson,newJson,old.validUntil);assert.equal(batch.length,2);db.exec('BEGIN');try{const changes=batch.map(q=>Number(db.prepare(q.sql).run(...q.params).changes));db.exec('COMMIT');return changes;}catch(e){db.exec('ROLLBACK');throw e;}}
const state=()=>({cap_micros:10000000,reserved_micros:0,conversations:0,receipt_json:oldJson,expires_at:old.validUntil});
test('preflight permits only source change on the identical unused allocation',()=>{assertSourceOnlyAudioReceiptAmendment(old,next,old.sourceSha);assertUnusedAudioBudgetSourceAmendment(state(),oldJson,old,{claims:0,attempts:0,leases:0});for(const patch of [{cap_micros:5000000},{reserved_micros:1},{conversations:1},{expires_at:old.validUntil+1},{receipt_json:'{}'}])assert.throws(()=>assertUnusedAudioBudgetSourceAmendment({...state(),...patch},oldJson,old,{claims:0,attempts:0,leases:0}),/unused allocation/);for(const key of ['claims','attempts','leases'])assert.throws(()=>assertUnusedAudioBudgetSourceAmendment(state(),oldJson,old,{claims:0,attempts:0,leases:0,[key]:1}),/unused allocation/);for(const patch of [{validUntil:old.validUntil+1},{cap:11},{evidenceReference:'changed'},{extra:1},{extra:undefined}])assert.throws(()=>assertSourceOnlyAudioReceiptAmendment(old,{...next,...patch},old.sourceSha),/cannot change/);});
test('actual SQLite atomic updates preserve every ledger field and change only both receipt sources',()=>{const db=fixture(),before=db.prepare('SELECT * FROM next_audio_budget').get();assert.deepEqual(apply(db),[1,1]);const after=db.prepare('SELECT * FROM next_audio_budget').get();assert.deepEqual({...after,receipt_json:before.receipt_json},{...before});assert.equal(after.receipt_json,newJson);assert.equal(db.prepare('SELECT receipt_json FROM next_audio_rate_evidence').get().receipt_json,newJson);assert.deepEqual(apply(db),[0,0],'repeat cannot refresh anything');db.close();});
for(const [name,mutation] of Object.entries({reserved:'UPDATE next_audio_budget SET reserved_micros=1',spent:'UPDATE next_audio_budget SET conversations=1',cap:'UPDATE next_audio_budget SET cap_micros=20000000',expiry:'UPDATE next_audio_budget SET expires_at=expires_at+1',budgetReceipt:"UPDATE next_audio_budget SET receipt_json='{}'",evidenceReceipt:"UPDATE next_audio_rate_evidence SET receipt_json='{}'",region:"UPDATE next_audio_rate_evidence SET region='other'",claim:`INSERT INTO next_audio_batch_claims VALUES('${id}')`,lease:`INSERT INTO next_audio_leases VALUES('${id}')`,modelAttempt:"INSERT INTO next_audio_attempts VALUES('attempt')",speechAttempt:"INSERT INTO next_audio_speech_attempts VALUES('attempt')"})){test(`atomic guard refuses ${name}, including state drift after preflight`,()=>{const db=fixture();db.exec(mutation);const before=[db.prepare('SELECT * FROM next_audio_budget').get(),db.prepare('SELECT * FROM next_audio_rate_evidence').get()];assert.deepEqual(apply(db),[0,0]);assert.deepEqual([db.prepare('SELECT * FROM next_audio_budget').get(),db.prepare('SELECT * FROM next_audio_rate_evidence').get()],before);db.close();});}
test('a failed second statement rolls back the first receipt update',()=>{const db=fixture(),batch=unusedAudioBudgetSourceAmendmentBatch(id,region,oldJson,newJson,old.validUntil);db.exec('BEGIN');assert.equal(Number(db.prepare(batch[0].sql).run(...batch[0].params).changes),1);assert.throws(()=>db.exec('UPDATE nonexistent_table SET x=1'));db.exec('ROLLBACK');assert.equal(db.prepare('SELECT receipt_json FROM next_audio_budget').get().receipt_json,oldJson);db.close();});
