import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";const read=p=>fs.readFileSync(p,"utf8");
test("People Gate 6 provides source-defined headcount attendance payroll incentive and expense metrics",()=>{const src=read("lib/people-reports.ts");for(const token of ["active_headcount","attendance_exceptions","payroll_net_pay","approved_incentive","expense_linkage","metricDefinitions"])assert.ok(src.includes(token),token);assert.match(src,/sourceDrilldownEnabled:true/);assert.match(src,/staticDemoCountersAccepted:false/);});
// `AND 1=0` was the sentinel a manager with no direct reports used to get. The scoped reads are now
// chunked (they were an unbounded IN list built from the roster, which 500'd past D1's parameter cap),
// and an empty scope returns no rows without issuing a query at all - the same invariant, one fewer
// round trip. Asserting the sentinel string was asserting the implementation; the invariant is that a
// manager with no reports sees nobody, which tests/people-reports-scope.test.mjs now executes.
test("People reports enforce manager direct-report scope instead of broad fallback",()=>{const src=read("lib/people-reports.ts");assert.match(src,/manager_employee_id=\?/);assert.match(src,/mode:\"manager\"/);assert.match(src,/if\(!scope\.employeeIds\.length\)return \[\] as Row\[\]/);assert.match(src,/managerScopeEnforced:true/);});
test("sensitive People report sections retain their own permissions",()=>{const src=read("lib/people-reports.ts"),api=read("app/api/people-reports/route.ts");assert.match(api,/authorize\(request,\"reports\.view\"\)/);assert.match(src,/payroll\.view/);assert.match(src,/incentives\.view/);assert.match(src,/attendance\.view/);assert.match(src,/finance\.view/);assert.match(src,/audit\.view/);assert.match(src,/sensitivePayrollPermissionGated:true/);assert.match(src,/sensitiveIncentivePermissionGated:true/);});
test("Gate 6 reports expose payroll variance team rollups and audit/source IDs without becoming authority",()=>{const src=read("lib/people-reports.ts");for(const token of ["teamRollups","variance","payrollApprovalEvents","incentiveApprovalEvents","attendanceIds","payrollResultIds","incentiveResultIds","expenseIds"])assert.ok(src.includes(token),token);assert.match(src,/payrollAuthority:false/);assert.match(src,/disciplinaryAuthority:false/);});
test("Gate 6 UI states UAT and production boundaries",()=>{const page=read("app/team/people/reports/page.tsx");assert.match(page,/Gate 6 productivity and audit reports/);assert.match(page,/Manager scope:<\/b> ENFORCED/);assert.match(page,/Static\/demo performance truth:<\/b> NO/);assert.match(page,/Production ready:<\/b> NO/);});
