import test from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {readFileSync} from "node:fs";

function locked(){assert.equal(process.env.PAWSPACE_PAYMENT_ENV,"sandbox");assert.equal(process.env.FORBID_PRODUCTION,"true");assert.equal(process.env.NODE_ENV,"test");assert.equal(process.env.APP_ENV,"staging");}
function plan(db,sql){return db.prepare(`EXPLAIN QUERY PLAN ${sql}`).all().map(row=>String(row.detail)).join("\n");}

test("performance audit is sandbox locked",()=>locked());

test("control-plane versioned mutations use CAS and deterministic conflict mapping",()=>{locked();const provider=readFileSync("app/api/provider-capacity-control/route.ts","utf8"),catalogue=readFileSync("lib/catalogue-governance.ts","utf8"),catalogueRoute=readFileSync("app/api/catalogue/route.ts","utf8"),plans=readFileSync("lib/subscription-plan-governance.ts","utf8"),planRoute=readFileSync("app/api/subscription-plans/route.ts","utf8");assert.match(provider,/WHERE id=\? AND version=\?/);assert.match(provider,/CONCURRENT_MODIFICATION/);assert.match(provider,/withRetryingD1Writes/);assert.match(catalogue,/WHERE id=\? AND version=\?/);assert.match(catalogue,/meta\?\.changes/);assert.match(catalogueRoute,/withRetryingD1Writes/);assert.match(catalogueRoute,/CONCURRENT_MODIFICATION[\s\S]*409/);assert.match(plans,/WHERE id=\? AND version=\?/);assert.match(plans,/meta\?\.changes/);assert.match(planRoute,/withRetryingD1Writes/);assert.match(planRoute,/CONCURRENT_MODIFICATION[\s\S]*409/);});

test("canonical booking GET collapses N+1 child reads into one batch",()=>{locked();const source=readFileSync("app/api/canonical-bookings/route.ts","utf8"),get=source.slice(source.indexOf("export async function GET"),source.indexOf("export async function POST"));assert.match(get,/await db\.batch\(\[/);assert.doesNotMatch(get,/for\(const row of rows\.results\)\{const \[pets,events\]=await Promise\.all/);assert.match(source,/idx_canonical_bookings_created/);assert.match(source,/idx_canonical_bookings_service_updated/);});

test("finance hot queries use composite indexes without temp sort trees",()=>{locked();const db=new DatabaseSync(":memory:");db.exec(`CREATE TABLE canonical_bookings(id TEXT PRIMARY KEY,service_code TEXT NOT NULL,updated_at INTEGER NOT NULL,created_at INTEGER NOT NULL);CREATE INDEX idx_canonical_bookings_service_updated ON canonical_bookings(service_code,updated_at DESC);CREATE INDEX idx_canonical_bookings_created ON canonical_bookings(created_at DESC);CREATE TABLE payment_reconciliation_exceptions(id TEXT PRIMARY KEY,payment_id TEXT,status TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE INDEX idx_payment_recon_status_payment ON payment_reconciliation_exceptions(status,payment_id);CREATE INDEX idx_payment_recon_status_created ON payment_reconciliation_exceptions(status,created_at DESC);`);const bookingPlan=plan(db,"SELECT * FROM canonical_bookings WHERE service_code='grooming' ORDER BY updated_at DESC LIMIT 200"),createdPlan=plan(db,"SELECT * FROM canonical_bookings ORDER BY created_at DESC LIMIT 100"),exceptionGroup=plan(db,"SELECT payment_id,COUNT(*) FROM payment_reconciliation_exceptions WHERE status='open' GROUP BY payment_id"),exceptionRecent=plan(db,"SELECT * FROM payment_reconciliation_exceptions WHERE status='open' ORDER BY created_at DESC LIMIT 50");assert.match(bookingPlan,/idx_canonical_bookings_service_updated/i);assert.match(createdPlan,/idx_canonical_bookings_created/i);assert.match(exceptionGroup,/idx_payment_recon_status_payment/i);assert.match(exceptionRecent,/idx_payment_recon_status_created/i);for(const detail of[bookingPlan,createdPlan,exceptionGroup,exceptionRecent])assert.doesNotMatch(detail,/USE TEMP B-TREE/i);});
