import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {ProductionConfigurationError,PRODUCTION_SERVICE_REGISTRY,assertProductionReadiness,collectProductionReadinessProblems} from "../lib/production-readiness-enforcement.mjs";

const goodBase={PAWSPACE_PRODUCTION_ENFORCE:"true",IDFY_API_KEY:"test-key",IDFY_ACCOUNT_ID:"test-account",IDFY_URL:"https://api.idfy.com/v3/tasks",IDFY_WEBHOOK_SECRET:"test-webhook-secret",PRODUCTION_R2_BUCKET_NAME:"pawspace-private-production",CLOUDFLARE_API_TOKEN:"test-cloudflare-token",CLOUDFLARE_ACCOUNT_ID:"test-cloudflare-account",PROVIDER_AGREEMENT_ESIGN_PRIVATE_KEY_PKCS8_B64:"private-key-material",PROVIDER_AGREEMENT_ESIGN_PUBLIC_KEY_SPKI_B64:"public-key-material",PROVIDER_AGREEMENT_ESIGN_KEY_ID:"provider-agreement-2026-01",META_WHATSAPP_ACCESS_TOKEN:"meta-token",META_WHATSAPP_APP_SECRET:"meta-app-secret",META_WHATSAPP_VERIFY_TOKEN:"meta-verify",INTERAKT_API_KEY:"interakt",INTERAKT_WEBHOOK_SECRET:"interakt-webhook",META_WHATSAPP_WABA_ID:"waba",META_WHATSAPP_PHONE_NUMBER_ID:"phone",PAWSPACE_PAYMENT_ENV:"live",RAZORPAY_KEY_ID:"rzp_live_realkey",RAZORPAY_KEY_SECRET:"rzp_live_secret_material",RAZORPAY_WEBHOOK_SECRET_LIVE:"whsec_live_material",PAWSPACE_PAYMENT_LIVE_APPROVED:"true"};
const healthyRegistry=[{id:"healthy",driver:"production_http",requiredSecrets:["SERVICE_SECRET"],requiredConfig:["SERVICE_URL"],handlers:[{name:"request",state:"implemented"}]}];

test("non-production profiles remain explicitly non-signable",()=>{assert.deepEqual(assertProductionReadiness({NODE_ENV:"test"},healthyRegistry),{ok:true,enforced:false,profile:"test",productionReady:false,zeroP0P1Blockers:false,releaseSignOffAllowed:false});});
test("PAWSPACE_PRODUCTION_ENFORCE=true activates the production guard",()=>{const result=assertProductionReadiness({PAWSPACE_PRODUCTION_ENFORCE:"true",SERVICE_SECRET:"s",SERVICE_URL:"https://service.example"},healthyRegistry);assert.equal(result.enforced,true);assert.equal(result.productionReady,true);assert.equal(result.zeroP0P1Blockers,true);assert.equal(result.releaseSignOffAllowed,true);});
test("production rejects mock or sandbox drivers",()=>{const registry=[{id:"database",driverEnv:"DATABASE_DRIVER",handlers:[{name:"connect",state:"implemented"}]}];assert.throws(()=>assertProductionReadiness({PAWSPACE_PRODUCTION_ENFORCE:"true",DATABASE_DRIVER:"memory"},registry),(error)=>error instanceof ProductionConfigurationError&&/mock or sandbox-only/.test(error.message));});
test("production rejects unbuilt handlers even when credentials are present",()=>{const registry=[{id:"documents",driver:"r2",handlers:[{name:"upload",state:"missing"}]}];assert.throws(()=>assertProductionReadiness({PAWSPACE_PRODUCTION_ENFORCE:"true"},registry),ProductionConfigurationError);});
test("private R2 storage is implemented but still requires deployment credentials and a production bucket",()=>{const storage=PRODUCTION_SERVICE_REGISTRY[1],problems=collectProductionReadinessProblems({PAWSPACE_PRODUCTION_ENFORCE:"true"},[storage]);for(const name of["CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID","PRODUCTION_R2_BUCKET_NAME"])assert.ok(problems.some(problem=>problem.includes(name)));assert.ok(!problems.some(problem=>/server_owned_secure_upload is missing/.test(problem)));});
test("production provider agreement e-sign requires asymmetric signing material and key identity",()=>{const esign=PRODUCTION_SERVICE_REGISTRY[2],problems=collectProductionReadinessProblems({PAWSPACE_PRODUCTION_ENFORCE:"true"},[esign]);for(const name of["PROVIDER_AGREEMENT_ESIGN_PRIVATE_KEY_PKCS8_B64","PROVIDER_AGREEMENT_ESIGN_PUBLIC_KEY_SPKI_B64","PROVIDER_AGREEMENT_ESIGN_KEY_ID"])assert.ok(problems.some(problem=>problem.includes(name)));assert.ok(!problems.some(problem=>/mock or sandbox-only|verified_digital_esign is mock/.test(problem)));});
test("canonical production registry can report all three sign-off booleans only when every dependency is declared",()=>{const result=assertProductionReadiness(goodBase);assert.equal(result.productionReady,true);assert.equal(result.zeroP0P1Blockers,true);assert.equal(result.releaseSignOffAllowed,true);});
test("the command-line production guard fails closed when a signing secret is absent",()=>{const env={...process.env,...goodBase};delete env.PROVIDER_AGREEMENT_ESIGN_PRIVATE_KEY_PKCS8_B64;const result=spawnSync(process.execPath,[new URL("../scripts/assert-production-readiness.mjs",import.meta.url).pathname],{env,encoding:"utf8"});assert.notEqual(result.status,0);assert.match(result.stderr,/PRODUCTION_CONFIGURATION_ERROR/);assert.match(result.stderr,/PROVIDER_AGREEMENT_ESIGN_PRIVATE_KEY_PKCS8_B64/);});

// --- Additive delta ported from the standalone gate: Razorpay payments, forbidden bypasses, placeholders ---
const razorpayService=PRODUCTION_SERVICE_REGISTRY.find(s=>s.id==="razorpay_payments");
const razorpayLiveEnv={PAWSPACE_PRODUCTION_ENFORCE:"true",PAWSPACE_PAYMENT_ENV:"live",RAZORPAY_KEY_ID:"rzp_live_realkey",RAZORPAY_KEY_SECRET:"rzp_live_secret_material",RAZORPAY_WEBHOOK_SECRET_LIVE:"whsec_live_material",PAWSPACE_PAYMENT_LIVE_APPROVED:"true"};

test("razorpay payments is a registered production service",()=>{assert.ok(razorpayService,"razorpay_payments must be in the registry");});
test("razorpay: an unset payment env is flagged as sandbox-only and not live",()=>{const problems=collectProductionReadinessProblems({PAWSPACE_PRODUCTION_ENFORCE:"true"},[razorpayService]);assert.ok(problems.some(p=>/mock or sandbox-only/.test(p)));assert.ok(problems.some(p=>/PAWSPACE_PAYMENT_ENV must be 'live'/.test(p)));});
test("razorpay: a fully-configured live payment service passes",()=>{assert.deepEqual(collectProductionReadinessProblems(razorpayLiveEnv,[razorpayService]),[]);});
test("razorpay: live mode missing a live credential is flagged",()=>{const env={...razorpayLiveEnv};delete env.RAZORPAY_KEY_SECRET;assert.ok(collectProductionReadinessProblems(env,[razorpayService]).some(p=>p.includes("RAZORPAY_KEY_SECRET")));});
test("razorpay: a rzp_test_ key in the live slot is flagged",()=>{assert.ok(collectProductionReadinessProblems({...razorpayLiveEnv,RAZORPAY_KEY_ID:"rzp_test_sandbox"},[razorpayService]).some(p=>/not a live key/.test(p)));});
test("razorpay: a live secret identical to its sandbox twin is flagged",()=>{assert.ok(collectProductionReadinessProblems({...razorpayLiveEnv,RAZORPAY_KEY_SECRET:"reused",RAZORPAY_KEY_SECRET_SANDBOX:"reused"},[razorpayService]).some(p=>/identical to RAZORPAY_KEY_SECRET_SANDBOX/.test(p)));});
test("razorpay: the live-approval double-gate must be true",()=>{const env={...razorpayLiveEnv};delete env.PAWSPACE_PAYMENT_LIVE_APPROVED;assert.ok(collectProductionReadinessProblems(env,[razorpayService]).some(p=>/PAWSPACE_PAYMENT_LIVE_APPROVED must be 'true'/.test(p)));});
test("forbidden dev/preview bypass flags are refused in a production profile",()=>{const problems=collectProductionReadinessProblems({PAWSPACE_PRODUCTION_ENFORCE:"true",PAWSPACE_LOCAL_PREVIEW:"on",SERVICE_SECRET:"s",SERVICE_URL:"https://service.example"},healthyRegistry);assert.ok(problems.some(p=>/forbidden non-production flag PAWSPACE_LOCAL_PREVIEW/.test(p)));});
test("a placeholder value in a required secret is refused",()=>{const problems=collectProductionReadinessProblems({PAWSPACE_PRODUCTION_ENFORCE:"true",SERVICE_SECRET:"changeme",SERVICE_URL:"https://service.example"},healthyRegistry);assert.ok(problems.some(p=>/looks like a placeholder/.test(p)));});
