import test from"node:test";
import assert from"node:assert/strict";
import fs from"node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const governance=read("lib/provider-commission-governance.ts"),route=read("app/api/partner-finance/route.ts"),ui=read("app/team/finance/partners/page.tsx"),bookings=read("app/api/canonical-bookings/route.ts");
test("canonical providers support direct full-time and commission engagement",()=>{assert.match(bookings,/model:\"full_time\"\|\"commission\"/);assert.match(governance,/EngagementModel=\"full_time\"\|\"commission\"/);});
test("commission profiles support fixed or percentage defaults",()=>{assert.match(governance,/CommissionMode=\"fixed\"\|\"percent\"/);assert.match(governance,/default_commission_mode/);assert.match(governance,/commissionAmount/);});
test("only completed commission work orders enter payout automation",()=>{assert.match(governance,/provider_model='commission'/);assert.match(governance,/b\.status='completed'/);});
test("commission override remains pre-confirmation only",()=>{assert.match(governance,/commission_source='order_override'/);assert.match(route,/override_order_commission/);assert.match(ui,/Override/);});
test("commission requires confirmation plus two approvals by three distinct actors",()=>{assert.match(governance,/Level 1 approval must be completed by a different approver than the commission confirmer/);assert.match(governance,/Level 2 approval must be completed by a different approver than the commission confirmer/);assert.match(governance,/allApprovalActorsDistinct:true/);});
test("commission payout governance owns escrow and sandbox gates",()=>{assert.match(governance,/reserveEscrowForProviderPayout/);assert.match(governance,/requireEscrowProviderReleaseForPayout/);assert.match(governance,/environment:\"sandbox\"/);assert.match(governance,/liveMoney:false/);});
test("provider finance writes remain protected",()=>{assert.match(route,/authorize\(request,\"finance\.manage\"\)/);assert.match(route,/securityAudit/);});

import { DatabaseSync } from "node:sqlite";
import { installWorkersHooks } from "./helpers/module-hooks.mjs";
installWorkersHooks("__COMM_DB__", "__COMM_ENV__");
function commD1(sqlite){const st=(sql,a)=>({bind:(...b)=>st(sql,b),first:async()=>sqlite.prepare(sql).get(...a)??null,run:async()=>{const i=sqlite.prepare(sql).run(...a);return{success:true,meta:{changes:Number(i.changes)}};},all:async()=>({results:sqlite.prepare(sql).all(...a)})});return{prepare:s=>st(s,[]),batch:async l=>{const o=[];for(const x of l)o.push(await x.run());return o;},exec:async s=>{sqlite.exec(s);return{count:0,duration:0};}};}
const MAKER="finance.maker@pawspace.in",CHECKER1="finance.checker1@pawspace.in",CHECKER2="finance.checker2@pawspace.in";
async function commissionWorld(){const sqlite=new DatabaseSync(":memory:");const db=commD1(sqlite);globalThis.__COMM_DB__=db;globalThis.__COMM_ENV__={PAWSPACE_PAYMENT_ENV:"sandbox",PAWSPACE_PAYMENT_LIVE_APPROVED:"false"};const mod=await import("../lib/provider-commission-governance.ts");await mod.ensureProviderCommissionTables(db);return{sqlite,db,mod};}
function seed(sqlite,bookingId){const now=Date.now();sqlite.exec(`CREATE TABLE IF NOT EXISTS canonical_bookings (id TEXT PRIMARY KEY,customer_id TEXT,city_id TEXT,zone_id TEXT,service_code TEXT,package_code TEXT,package_name TEXT,schedule_group_id TEXT,provider_id TEXT,scheduled_start TEXT,scheduled_end TEXT,status TEXT,channel TEXT,total_amount REAL,currency TEXT,pricing_json TEXT,created_by TEXT,created_at INTEGER,updated_at INTEGER);CREATE TABLE IF NOT EXISTS provider_work_orders (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,schedule_group_id TEXT,provider_id TEXT NOT NULL,provider_name TEXT,provider_model TEXT NOT NULL,service_code TEXT,scheduled_start TEXT,scheduled_end TEXT,occurrence_count INTEGER DEFAULT 1,status TEXT,created_at INTEGER,updated_at INTEGER);CREATE TABLE IF NOT EXISTS booking_lifecycle_events (id TEXT PRIMARY KEY,booking_id TEXT,event_type TEXT,actor_id TEXT,detail_json TEXT,occurred_at INTEGER,created_at INTEGER,sequence INTEGER);CREATE TABLE IF NOT EXISTS booking_payments (id TEXT PRIMARY KEY,booking_id TEXT,customer_id TEXT,amount REAL,currency TEXT,status TEXT);CREATE TABLE IF NOT EXISTS payment_reconciliation_records (payment_id TEXT PRIMARY KEY,captured_amount REAL,refunded_amount REAL);`);sqlite.prepare("INSERT OR REPLACE INTO canonical_bookings (id,customer_id,city_id,service_code,provider_id,status,total_amount,currency,created_at,updated_at) VALUES (?,?,?,?,?,'completed',?,?,?,?)").run(bookingId,"CUS-SOD","blr","pet_grooming","PRV-SOD",4000,"INR",now,now);sqlite.prepare("INSERT OR REPLACE INTO provider_work_orders (id,booking_id,provider_id,provider_name,provider_model,service_code,status,created_at,updated_at) VALUES (?,?,?,?,'commission',?,'completed',?,?)").run(`WO-${bookingId}`,bookingId,"PRV-SOD","SoD Provider","pet_grooming",now,now);sqlite.prepare("INSERT OR REPLACE INTO booking_payments VALUES (?,?,?,?,?,'captured')").run(`PAY-${bookingId}`,bookingId,"CUS-SOD",4000,"INR");sqlite.prepare("INSERT OR REPLACE INTO payment_reconciliation_records VALUES (?,?,0)").run(`PAY-${bookingId}`,4000);}
async function setupOrder(world,bookingId){seed(world.sqlite,bookingId);await world.mod.saveProviderCompensationProfile(world.db,{providerId:"PRV-SOD",engagementModel:"commission",commissionMode:"percent",commissionValue:20,reason:"segregation-of-duties fixture",actor:"finance.admin@pawspace.in"});await world.mod.syncCompletedCommissionOrders(world.db);await world.mod.confirmOrderCommission(world.db,{bookingId,actor:MAKER});}
test("EXECUTED: confirmer cannot act as L1 or L2 and L1 cannot act as L2",async()=>{const w=await commissionWorld(),bookingId="BK-SOD-REAL";await setupOrder(w,bookingId);await assert.rejects(()=>w.mod.approveOrderCommission(w.db,{bookingId,level:1,actor:MAKER}),/different approver than the commission confirmer/);const l1=await w.mod.approveOrderCommission(w.db,{bookingId,level:1,actor:CHECKER1});assert.equal(l1.status,"awaiting_approval_2");assert.equal(w.sqlite.prepare("SELECT state FROM escrow_custodial_accounts WHERE booking_id=?").get(bookingId).state,"CUSTODY_HELD");await assert.rejects(()=>w.mod.approveOrderCommission(w.db,{bookingId,level:2,actor:CHECKER1}),/different approver/);await assert.rejects(()=>w.mod.approveOrderCommission(w.db,{bookingId,level:2,actor:MAKER}),/different approver than the commission confirmer/);});
test("EXECUTED: distinct L2 still cannot queue payout before escrow provider release",async()=>{const w=await commissionWorld(),bookingId="BK-ESCROW-GATE";await setupOrder(w,bookingId);await w.mod.approveOrderCommission(w.db,{bookingId,level:1,actor:CHECKER1});await assert.rejects(()=>w.mod.approveOrderCommission(w.db,{bookingId,level:2,actor:CHECKER2}),/escrow_not_released_for_provider:CUSTODY_HELD/);assert.equal(w.sqlite.prepare("SELECT COUNT(*) n FROM provider_order_payouts WHERE booking_id=?").get(bookingId).n,0);});
test("EXECUTED: payout idempotency cannot cross booking ownership",async()=>{const w=await commissionWorld();await w.mod.ensureProviderCommissionTables(w.db);w.sqlite.exec("INSERT INTO provider_order_payouts (id,booking_id,provider_id,amount,currency,rail,environment,status,due_at,idempotency_key,created_by,created_at,updated_at) VALUES ('PX','OTHER','P',10,'INR','razorpayx','sandbox','queued_sandbox',0,'SHARED','x',0,0)");await setupOrder(w,"BK-IDEM");await w.mod.approveOrderCommission(w.db,{bookingId:"BK-IDEM",level:1,actor:CHECKER1});await assert.rejects(()=>w.mod.approveOrderCommission(w.db,{bookingId:"BK-IDEM",level:2,actor:CHECKER2,idempotencyKey:"SHARED"}));});
test("EXECUTED: non-vacuity",async()=>{const{db,mod}=await commissionWorld();assert.equal((await mod.syncCompletedCommissionOrders(db))>=0,true);const dash=await mod.getProviderCommissionDashboard(db);assert.equal(dash.policy.allApprovalActorsDistinct,true);});
