import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {installWorkersHooks,runWithWorkersDb} from './helpers/module-hooks.mjs';
installWorkersHooks('__CONTACT_RETRY_DB__','__CONTACT_RETRY_ENV__');
const route=await import('../app/api/public-contact/route.ts');
const owners=await import('../lib/lead-owner-identity.ts');
const assignment=await import('../lib/lead-assignment-governance.ts');
const sample={name:'Synthetic Walking Lead',phone:'9000000882',email:'contact-retry@example.test',area:'Bengaluru',service:'Dog Walking',message:'Local audit only',whatsappConsent:false,requestId:'6b249c1e-7a09-4d3a-93b6-761b2f551afd'};
function world(){
 const sqlite=new DatabaseSync(':memory:');let fault='';
 // The platform user directory always exists; routing joins the sales roster to it.
 sqlite.exec("CREATE TABLE IF NOT EXISTS app_users (id TEXT PRIMARY KEY,email TEXT UNIQUE,status TEXT,name TEXT,role_code TEXT)");
 const statement=(sql,args=[])=>({sql,args,bind:(...values)=>statement(sql,values),first:async()=>sqlite.prepare(sql).get(...args)??null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>execute(sql,args)});
 const execute=(sql,args)=>{if(fault&&sql.includes(fault))throw new Error('Injected database write failure');const r=sqlite.prepare(sql).run(...args);return{success:true,meta:{changes:Number(r.changes),rows_written:Number(r.changes)}};};
 const db={prepare:sql=>statement(sql),batch:async items=>{sqlite.exec('BEGIN');try{const results=items.map(s=>execute(s.sql,s.args));sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}},exec:async sql=>sqlite.exec(sql)};
 const count=table=>sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table)?sqlite.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get().n:0;
 const submit=(body=sample,ip='198.51.100.71')=>runWithWorkersDb(db,async()=>{const response=await route.POST(new Request('https://pawspace.test/api/public-contact',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':ip},body:JSON.stringify(body)}));return{status:response.status,body:await response.json()};});
 const warm=()=>submit({...sample,name:''},'198.51.100.72');
 return{sqlite,db,count,submit,warm,failAt:needle=>{fault=needle;}};
}
// One lead, one canonical assignment and one first-response clock however often the visitor retries.
const assertOne=w=>{for(const table of ['crm_contacts','crm_activities','lead_work_items','ai_lead_ownership','lead_assignments','lead_sla_clocks'])assert.equal(w.count(table),1,table);assert.equal(w.count('crm_tasks'),0,'crm_tasks');};
async function rosterMember(w,email,services,cities,team='sales'){
 w.sqlite.exec("CREATE TABLE IF NOT EXISTS app_users (id TEXT PRIMARY KEY,email TEXT UNIQUE,status TEXT,name TEXT,role_code TEXT)");
 w.sqlite.prepare("INSERT INTO app_users VALUES (?,?, 'active','QA Associate','associate')").run(email,email);
 await assignment.saveLeadAssignmentMember(w.db,{employeeEmail:email,teamCode:team,serviceCodes:services,cityIds:cities,active:true,actorId:'qa.setup@pawspace.test'});
}

test('same public submission retry preserves one routed lead, contact and activity',async()=>{const w=world();const first=await w.submit(),retry=await w.submit();assert.equal(first.status,201);assert.equal(retry.status,200);assert.equal(retry.body.leadId,first.body.leadId);assert.equal(retry.body.duplicatePrevented,true);assertOne(w);assert.equal(w.count('lead_owner_mapping_exceptions'),0);w.sqlite.close();});
for(const field of ['phone','service','whatsappConsent','gclid'])test(`reused submission key cannot change ${field}`,async()=>{const w=world();const first=await w.submit();const value=field==='phone'?'9000000883':field==='service'?'Boarding':field==='whatsappConsent'?true:'DIFFERENT-CLICK';const conflict=await w.submit({...sample,[field]:value});assert.equal(first.status,201);assert.equal(conflict.status,409);assertOne(w);w.sqlite.close();});
test('concurrent retries commit exactly one connected lead transaction',async()=>{const w=world();await w.warm();const results=await Promise.all(Array.from({length:4},()=>w.submit()));assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(results.filter(r=>r.status===200).length,3);assert.equal(new Set(results.map(r=>r.body.leadId)).size,1);assertOne(w);w.sqlite.close();});
test('failed lead transaction rolls back receipt contact task lead and ownership exception',async()=>{const w=world();await w.warm();w.failAt('INSERT INTO lead_work_items');assert.equal((await w.submit()).status,500);for(const table of ['crm_contacts','crm_activities','crm_tasks','lead_work_items','ai_lead_ownership','public_contact_submissions','lead_owner_mapping_exceptions'])assert.equal(w.count(table),0,table);w.failAt('');assert.equal((await w.submit()).status,201);assertOne(w);w.sqlite.close();});
const leadRow=w=>w.sqlite.prepare('SELECT id,owner,manager FROM lead_work_items').get();
const assignmentOf=(w,leadId)=>w.sqlite.prepare("SELECT employee_email,fallback_queue,assignment_reason,team_code FROM lead_assignments WHERE lead_id=? AND status='current'").get(leadId);
const clockOf=(w,leadId)=>w.sqlite.prepare("SELECT clock_type,status,policy_id FROM lead_sla_clocks WHERE lead_id=?").get(leadId);
// Round-2 staging: public /contact and web-chat leads were owned by "AI Orchestrator" with SLA
// "policy_unavailable", although the form promises "Our team will reach out within a couple of hours".
test('public intake routes the enquiry to the eligible roster rep and starts the first-response clock',async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'aa.training@pawspace.test',['training'],['Bengaluru']);await rosterMember(w,'zz.walking@pawspace.test',['dog_walking'],['Bengaluru']);const result=await w.submit();assert.equal(result.status,201,JSON.stringify(result.body));const lead=leadRow(w);assert.equal(lead.owner,'zz.walking@pawspace.test','the Dog Walking rep owns it - not the AI, not the Training rep');assert.equal(lead.manager,'Sales Manager');const assignment=assignmentOf(w,lead.id);assert.equal(assignment.employee_email,'zz.walking@pawspace.test');assert.equal(assignment.assignment_reason,'new_lead');assert.equal(assignment.team_code,'sales');const clock=clockOf(w,lead.id);assert.equal(clock.clock_type,'first_response');assert.equal(clock.status,'running');const contact=w.sqlite.prepare('SELECT owner,next_action FROM crm_contacts').get();assert.deepEqual({...contact},{owner:'zz.walking@pawspace.test',next_action:'First response call due'});assert.deepEqual(result.body.governance,{assignment:'canonical',sla:'canonical',owner:'zz.walking@pawspace.test',queue:null},'the answer names the owner and a running clock');assert.equal(w.count('crm_tasks'),0);assert.equal(w.count('lead_governance_exceptions'),0);w.sqlite.close();});
test('with nothing configured, the UAT default routing and SLA policies apply and a configured policy is never overwritten',async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'zz.walking@pawspace.test',['dog_walking'],['Bengaluru']);assert.equal((await w.submit()).status,201);const policies=w.sqlite.prepare("SELECT id,status,approval_reference FROM lead_assignment_policies").all();assert.deepEqual(policies.map(row=>({...row})),[{id:'LAP-UAT-DEFAULT-SALES',status:'active_uat',approval_reference:'UAT-DEFAULT-LEAD-ROUTING'}]);const sla=w.sqlite.prepare("SELECT id,status,approval_reference,first_response_minutes,business_hours_json FROM lead_sla_policies").all();assert.equal(sla.length,1);assert.equal(sla[0].id,'SLAP-UAT-DEFAULT-SALES');assert.equal(sla[0].status,'active_uat');assert.equal(sla[0].first_response_minutes,10);assert.match(sla[0].business_hours_json,/windowed/);assert.equal(clockOf(w,leadRow(w).id).policy_id,'SLAP-UAT-DEFAULT-SALES');
 // A second world where the ops owner already configured routing: the default is not seeded next to it.
 const v=world();await v.warm();await owners.ensureLeadOwnerTables(v.db);await rosterMember(v,'zz.walking@pawspace.test',['dog_walking'],['Bengaluru']);const governance=await import('../lib/lead-assignment-governance.ts');const configured=await governance.saveLeadAssignmentPolicy(v.db,{name:'Ops routing',teamCode:'sales',serviceCodes:['dog_walking'],cityIds:['blr'],maxActiveWorkload:5,continuityEnabled:true,requireShift:false,fallbackQueue:'ops-queue',effectiveFrom:1,reason:'Configured by ops',actorId:'ops@pawspace.test'});await governance.activateLeadAssignmentPolicy(v.db,{policyId:configured.id,approvalReference:'OPS-1',reason:'Approved by ops',actorId:'ops@pawspace.test'});assert.equal((await v.submit()).status,201);assert.deepEqual(v.sqlite.prepare('SELECT id FROM lead_assignment_policies').all().map(row=>row.id),[configured.id],'a configured policy stands alone');assert.equal(assignmentOf(v,leadRow(v).id).employee_email,'zz.walking@pawspace.test');w.sqlite.close();v.sqlite.close();});
test('an out-of-city rep is never chosen: the enquiry waits in the sales fallback queue with its clock running',async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'qa.chennai@pawspace.test',['dog_walking'],['Chennai']);const result=await w.submit();assert.equal(result.status,201);const lead=leadRow(w);assert.equal(lead.owner,'Unassigned');const assignment=assignmentOf(w,lead.id);assert.equal(assignment.employee_email,null);assert.equal(assignment.fallback_queue,'sales-enquiries');assert.equal(clockOf(w,lead.id).status,'running','the queue is on the clock too');assert.equal(result.body.governance.assignment,'fallback_queue');assert.match(w.sqlite.prepare('SELECT next_action FROM crm_contacts').get().next_action,/sales-enquiries/);assert.equal(w.count('lead_owner_mapping_exceptions'),0);assert.equal(w.count('crm_tasks'),0);w.sqlite.close();});
for(const [label,canonical] of [['General enquiry','general_inquiry'],['Doorstep Vet','vet'],['Pet Farewell Support','funeral']])test(`advertised ${label} reaches the rep whose scope names ${canonical}`,async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'qa.scope@pawspace.test',[canonical],['Bengaluru']);assert.equal((await w.submit({...sample,service:label})).status,201);assert.equal(leadRow(w).owner,'qa.scope@pawspace.test');assert.equal(clockOf(w,leadRow(w).id).status,'running');assert.equal(w.count('crm_tasks'),0);w.sqlite.close();});
test('an enquiry that names no service goes to any sales rep in the city, lowest workload first',async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'qa.boarding@pawspace.test',['boarding'],['Bengaluru']);assert.equal((await w.submit({...sample,service:'Talk to our team'})).status,201,'the web chat files a call request as "Talk to our team"');assert.equal(leadRow(w).owner,'qa.boarding@pawspace.test','a call request reaches a person even though no roster scope names it');w.sqlite.close();});
for(const malformed of ['{','{}','null','[17]','[""]'])test(`a malformed roster scope cannot break intake or routing for everyone else: ${malformed}`,async()=>{const w=world();await w.warm();await owners.ensureLeadOwnerTables(w.db);await rosterMember(w,'qa.scope@pawspace.test',['dog_walking'],['Bengaluru']);await rosterMember(w,'qb.healthy@pawspace.test',['dog_walking'],['Bengaluru']);w.sqlite.prepare("UPDATE lead_assignment_memberships SET service_codes_json=? WHERE employee_email='qa.scope@pawspace.test'").run(malformed);const accepted=await w.submit();assert.equal(accepted.status,201);const lead=leadRow(w);assert.equal(lead.owner,'qb.healthy@pawspace.test');assert.equal(assignmentOf(w,lead.id).employee_email,'qb.healthy@pawspace.test','canonical assignment, not a fallback pick');assert.equal(clockOf(w,lead.id).status,'running');assert.equal(w.count('crm_tasks'),0);w.sqlite.close();});
