import test from'node:test';
import assert from'node:assert/strict';
import{DatabaseSync}from'node:sqlite';
import{installWorkersHooks,runWithWorkersDb}from'./helpers/module-hooks.mjs';
installWorkersHooks('__PUBLIC_DIAL_DB__','__PUBLIC_DIAL_ENV__');
const route=await import('../app/api/public-contact/route.ts');
const assignment=await import('../lib/lead-assignment-governance.ts');
const queue=await import('../lib/outbound-human-queue.ts');
function world(){const sqlite=new DatabaseSync(':memory:');const statement=(sql,args=[])=>({sql,args,bind:(...v)=>statement(sql,v),first:async()=>sqlite.prepare(sql).get(...args)??null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>{const r=sqlite.prepare(sql).run(...args);return{success:true,meta:{changes:Number(r.changes),rows_written:Number(r.changes)}};}});const db={prepare:sql=>statement(sql),batch:async items=>{sqlite.exec('BEGIN');try{const out=[];for(const s of items)out.push(await s.run());sqlite.exec('COMMIT');return out;}catch(error){sqlite.exec('ROLLBACK');throw error;}},exec:async sql=>sqlite.exec(sql)};const submit=(body,ip='198.51.100.81')=>runWithWorkersDb(db,async()=>{const response=await route.POST(new Request('https://pawspace.test/api/public-contact',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':ip},body:JSON.stringify(body)}));return{status:response.status,body:await response.json()};});return{sqlite,db,submit};}
const base={name:'Power Dial QA',phone:'9000000890',email:'power-dial@example.test',area:'Bengaluru',service:'Dog Walking',message:'Please contact me about this service',whatsappConsent:false,requestId:'public-dial-qa-00000001'};
async function warm(w){await w.submit({...base,name:''},'198.51.100.82');}
async function member(w,email='walking.owner@pawspace.test'){w.sqlite.prepare("INSERT INTO app_users (id,email,name,role_code,status,created_at,updated_at) VALUES (?,?,?,'associate','active',?,?)").run(email,email,'Walking owner',Date.now(),Date.now());await assignment.saveLeadAssignmentMember(w.db,{employeeEmail:email,teamCode:'sales',serviceCodes:['dog_walking'],cityIds:['Bengaluru'],active:true,actorId:'qa.setup@pawspace.test'});return email;}

test('public service enquiry becomes one canonical priority-100 human callback owned by the assigned seller',async()=>{const w=world();await warm(w);const owner=await member(w),result=await w.submit(base);assert.equal(result.status,201,JSON.stringify(result.body));assert.equal(result.body.outbound.status,'queued');assert.equal(result.body.outbound.owner,owner);const lead=w.sqlite.prepare('SELECT id,customer_id,owner FROM lead_work_items').get(),customer=w.sqlite.prepare('SELECT id,primary_phone,source FROM canonical_customers WHERE id=?').get(lead.customer_id),pref=w.sqlite.prepare('SELECT marketing_consent,service_consent,whatsapp_consent,opt_out FROM customer_contact_preferences WHERE customer_id=?').get(lead.customer_id),q=w.sqlite.prepare("SELECT * FROM outbound_routing_queue WHERE lead_id=?").get(lead.id);assert.equal(customer.id,lead.customer_id);assert.equal(customer.source,'public_contact');assert.equal(pref.marketing_consent,0);assert.equal(pref.service_consent,1);assert.equal(pref.whatsapp_consent,0);assert.equal(pref.opt_out,0);assert.equal(q.lane,'human');assert.equal(q.priority_score,100);assert.equal(q.high_intent,1);assert.equal(q.lifecycle_code,'requested_callback');assert.equal(q.status,'queued');assert.equal(q.customer_id,lead.customer_id);assert.ok(Number(q.callback_at)<=Date.now());assert.equal(await queue.claimNextHumanQueue(w.db,{actorId:'someone.else@pawspace.test'}),null);const claimed=await queue.claimNextHumanQueue(w.db,{actorId:owner});assert.equal(claimed.id,q.id);assert.equal(claimed.assigned_to,owner);assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM communication_messages').get().n,0);w.sqlite.close();});

test('existing service-contact refusal is preserved and the new enquiry is queued as suppressed',async()=>{const w=world();await warm(w);await member(w);const now=Date.now();w.sqlite.prepare("INSERT INTO canonical_customers (id,city_id,name,primary_phone,secondary_phone,email,source,consent_json,created_at,updated_at) VALUES ('CUS-EXIST','blr','Existing','9000000891',NULL,NULL,'customer_app','{}',?,?)").run(now,now);w.sqlite.prepare("INSERT INTO customer_contact_preferences (customer_id,marketing_consent,service_consent,whatsapp_consent,sms_consent,email_consent,opt_out,source,updated_by,updated_at) VALUES ('CUS-EXIST',0,0,0,0,0,0,'customer','customer',?)").run(now);const result=await w.submit({...base,phone:'9000000891',requestId:'public-dial-qa-00000002'});assert.equal(result.status,201);const lead=w.sqlite.prepare('SELECT customer_id FROM lead_work_items').get();assert.equal(lead.customer_id,'CUS-EXIST');assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM canonical_customers').get().n,1);const q=w.sqlite.prepare('SELECT status,lane FROM outbound_routing_queue').get();assert.equal(q.status,'suppressed');assert.equal(q.lane,'human');assert.equal(await queue.claimNextHumanQueue(w.db,{actorId:'walking.owner@pawspace.test'}),null);w.sqlite.close();});

test('ambiguous canonical phone ownership records review and never creates a call queue',async()=>{const w=world();await warm(w);await member(w);const now=Date.now();for(const id of['CUS-A','CUS-B'])w.sqlite.prepare("INSERT INTO canonical_customers (id,city_id,name,primary_phone,secondary_phone,email,source,consent_json,created_at,updated_at) VALUES (?,'blr',?,'9000000892',NULL,NULL,'customer_app','{}',?,?)").run(id,id,now,now);const result=await w.submit({...base,phone:'9000000892',requestId:'public-dial-qa-00000003'});assert.equal(result.status,201);assert.equal(result.body.outbound.status,'identity_review');assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM canonical_customers').get().n,2);assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM public_contact_identity_reviews WHERE status=\'open\'').get().n,1);assert.equal(w.sqlite.prepare('SELECT COUNT(*) n FROM outbound_routing_queue').get().n,0);assert.equal(await queue.claimNextHumanQueue(w.db,{actorId:'walking.owner@pawspace.test'}),null);w.sqlite.close();});

test('retry reuses the same canonical lead and human queue without duplicate dial work',async()=>{const w=world();await warm(w);await member(w);const first=await w.submit({...base,requestId:'public-dial-qa-00000004'}),replay=await w.submit({...base,requestId:'public-dial-qa-00000004'});assert.equal(first.status,201);assert.equal(replay.status,200);assert.equal(replay.body.leadId,first.body.leadId);for(const table of['canonical_customers','lead_work_items','outbound_routing_queue','crm_tasks'])assert.equal(w.sqlite.prepare(`SELECT COUNT(*) n FROM ${table}`).get().n,1,table);w.sqlite.close();});
