import test from"node:test";
import assert from"node:assert/strict";
import http from"node:http";
import{DatabaseSync}from"node:sqlite";
import{createHmac}from"node:crypto";
import{installWorkersHooks}from"./helpers/module-hooks.mjs";
installWorkersHooks("__RPX_DB__","__RPX_ENV__");

function d1(sqlite){const st=(sql,args=[])=>({bind:(...b)=>st(sql,b),first:async()=>sqlite.prepare(sql).get(...args)??null,run:async()=>{const x=sqlite.prepare(sql).run(...args);return{success:true,meta:{changes:Number(x.changes)}}},all:async()=>({results:sqlite.prepare(sql).all(...args)})});return{prepare:s=>st(s),batch:async items=>{const out=[];for(const item of items)out.push(await item.run());return out;},exec:async sql=>{sqlite.exec(sql);return{count:0,duration:0}}};}
async function provider(){const calls=[];const server=http.createServer((req,res)=>{let raw="";req.on("data",x=>raw+=x);req.on("end",()=>{const body=raw?JSON.parse(raw):{};calls.push({method:req.method,url:req.url,headers:req.headers,body});if(req.method==="POST"&&req.url==="/v1/payouts"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({id:"pout_TEST123",entity:"payout",fund_account_id:body.fund_account_id,amount:body.amount,currency:"INR",status:"processing",reference_id:body.reference_id,utr:null}));return;}if(req.method==="GET"&&req.url==="/v1/payouts/pout_TEST123"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({id:"pout_TEST123",amount:50000,currency:"INR",status:"processing"}));return;}res.writeHead(404);res.end("{}");});});await new Promise(r=>server.listen(0,"127.0.0.1",r));return{calls,url:`http://127.0.0.1:${server.address().port}`,close:()=>new Promise(r=>server.close(r))};}
const baseEnv=url=>({PAWSPACE_PAYMENT_ENV:"sandbox",PAWSPACE_RAZORPAYX_ENV:"sandbox",PAWSPACE_RAZORPAYX_LIVE_APPROVED:"false",RAZORPAYX_KEY_ID_SANDBOX:"rzp_test_provider",RAZORPAYX_KEY_SECRET_SANDBOX:"secret",RAZORPAYX_ACCOUNT_NUMBER_SANDBOX:"7878780080316316",RAZORPAYX_WEBHOOK_SECRET_SANDBOX:"webhook-secret",PAWSPACE_RAZORPAYX_CONTRACT_TEST:"true",PAWSPACE_RAZORPAYX_API_BASE_URL:url});
async function world(){const sqlite=new DatabaseSync(":memory:"),db=d1(sqlite);globalThis.__RPX_DB__=db;const governance=await import("../lib/provider-commission-governance.ts"),settlement=await import("../lib/partner-settlement-governance.ts");await governance.ensureProviderCommissionTables(db);await settlement.ensurePartnerSettlementTables(db);return{sqlite,db,governance,settlement,runtime:await import("../lib/razorpayx-payout-runtime.ts"),client:await import("../lib/razorpayx-client.ts")};}
function seedCommission(w,{id="RPX-LOCAL-1",booking="BK-RPX-1",amount=500,fund="fa_TEST123"}={}){const t=Date.now();w.sqlite.prepare("INSERT INTO provider_order_payouts (id,booking_id,provider_id,amount,currency,rail,environment,status,due_at,razorpayx_contact_id,razorpayx_fund_account_id,idempotency_key,created_by,created_at,updated_at) VALUES (?,?,?,?,'INR','razorpayx','sandbox','queued_sandbox',?,'cont_TEST',?,'idem-rpx-1','checker2',?,?)").run(id,booking,"PRV-RPX",amount,t+10000,fund,t,t);w.sqlite.prepare("INSERT INTO provider_order_commissions (id,booking_id,work_order_id,provider_id,service_code,order_amount,commission_mode,commission_value,commission_amount,commission_source,status,completed_at,due_at,confirmed_by,confirmed_at,approval_level_1_by,approval_level_1_at,approval_level_2_by,approval_level_2_at,payout_id,created_at,updated_at) VALUES (?,?,?,?,?,2500,'percent',20,500,'provider_default','payout_queued_sandbox',?,?,?,?,?,?,?,?,?,?,?)").run("COMM-RPX",booking,"WO-RPX","PRV-RPX","pet_grooming",t,t+10000,"maker",t,"checker1",t,"checker2",t,id,t,t);}
function seedSettlement(w,{id="PAYOUT-RPX-2",statement="SET-RPX",amount=700,fund="fa_TEST456"}={}){const t=Date.now();w.sqlite.prepare("INSERT INTO partner_settlement_statements (id,provider_id,period_code,currency,earned_amount,adjustment_amount,payable_amount,status,source_json,policy_status,approved_by,approved_at,created_at,updated_at) VALUES (?,'PRV-RPX2','2026-09','INR',?,0,?,'approved','[]','approved','approver',?,?,?)").run(statement,amount,amount,t,t,t);return w.runtime.ensureRazorpayXPayoutRuntime(w.db).then(()=>w.sqlite.prepare("INSERT INTO partner_payout_instructions (id,statement_id,provider_id,amount,currency,environment,status,idempotency_key,provider_reference,last_error,created_by,created_at,updated_at,razorpayx_contact_id,razorpayx_fund_account_id,beneficiary_snapshot_json,beneficiary_snapshot_sha256,beneficiary_verified_at) VALUES (?,?,?,?,'INR','sandbox','approved_sandbox','idem-rpx-2',NULL,NULL,'checker2',?,?, 'cont_TEST2',?,'{}','hash',?)").run(id,statement,"PRV-RPX2",amount,t,t,fund,t));}
const sign=raw=>createHmac("sha256","webhook-secret").update(raw).digest("hex");
const webhook=(event,payout,created_at=1900000000)=>JSON.stringify({entity:"event",event,contains:["payout"],payload:{payout:{entity:payout}},created_at});

test("RazorpayX readiness is sandbox-only and rejects live/unlocked configurations",async()=>{const{client}=await world();assert.equal(client.razorpayXSandboxReadiness({...baseEnv("http://127.0.0.1:1"),PAWSPACE_PAYMENT_ENV:"live"}).ready,false);assert.equal(client.razorpayXSandboxReadiness({...baseEnv("http://127.0.0.1:1"),RAZORPAYX_KEY_ID_SANDBOX:"rzp_live_BAD"}).ready,false);assert.equal(client.razorpayXSandboxReadiness(baseEnv("http://127.0.0.1:1")).ready,true);});
test("provider client sends paise, TEST account, fund account and X-Payout-Idempotency",async()=>{const p=await provider();try{const{client}=await world(),r=await client.createRazorpayXSandboxPayout(baseEnv(p.url),{localPayoutId:"PX-1",bookingId:"BK-1",providerId:"PRV-1",fundAccountId:"fa_TEST123",amountPaise:50000,currency:"INR",idempotencyKey:"idem-1"});assert.equal(r.connected,true);assert.equal(p.calls.length,1);assert.equal(p.calls[0].headers["x-payout-idempotency"],"idem-1");assert.equal(p.calls[0].body.amount,50000);assert.equal(p.calls[0].body.queue_if_low_balance,true);assert.equal(p.calls[0].body.purpose,"payout");assert.equal(p.calls[0].body.account_number,"7878780080316316");}finally{await p.close();}});
test("commission dispatch calls provider once and persists provider identity",async()=>{const p=await provider();try{const w=await world();seedCommission(w);globalThis.__RPX_ENV__=baseEnv(p.url);const first=await w.runtime.dispatchRazorpayXSandboxPayout(w.db,globalThis.__RPX_ENV__,{source:"commission",payoutId:"RPX-LOCAL-1"});assert.equal(first.connected,true);assert.equal(first.providerPayoutId,"pout_TEST123");assert.equal(w.sqlite.prepare("SELECT status,provider_reference FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"provider_processing_sandbox");const again=await w.runtime.dispatchRazorpayXSandboxPayout(w.db,globalThis.__RPX_ENV__,{source:"commission",payoutId:"RPX-LOCAL-1"});assert.equal(again.duplicatePrevented,true);assert.equal(p.calls.length,1);}finally{await p.close();}});
test("provider failure stays retryable rather than claiming a payout",async()=>{const w=await world();seedCommission(w);const bad={...baseEnv("http://127.0.0.1:1"),PAWSPACE_RAZORPAYX_TIMEOUT_MS:"300"};const r=await w.runtime.dispatchRazorpayXSandboxPayout(w.db,bad,{source:"commission",payoutId:"RPX-LOCAL-1"});assert.equal(r.connected,false);assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"retry_pending_sandbox");assert.equal(w.sqlite.prepare("SELECT provider_payout_id FROM razorpayx_payout_provider_state WHERE local_payout_id='RPX-LOCAL-1'").get().provider_payout_id,null);});
test("signed processed webhook settles the exact commission payout",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});const raw=webhook("payout.processed",{id:"pout_TEST123",amount:50000,currency:"INR",status:"processed",reference_id:"RPX-LOCAL-1",utr:"UTR123"});const r=await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"evt-rpx-processed"});assert.equal(r.providerStatus,"processed");assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"payout_processed_sandbox");assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_commissions WHERE booking_id='BK-RPX-1'").get().status,"payout_processed_sandbox");}finally{await p.close();}});
test("invalid signature cannot move payout state",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});const raw=webhook("payout.processed",{id:"pout_TEST123",amount:50000,currency:"INR",status:"processed",reference_id:"RPX-LOCAL-1"});await assert.rejects(()=>w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:"00",eventId:"bad"}),e=>e instanceof Response&&e.status===401);assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"provider_processing_sandbox");}finally{await p.close();}});
test("webhook duplicate is idempotent and conflicting event-id replay is rejected",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});const raw=webhook("payout.processed",{id:"pout_TEST123",amount:50000,currency:"INR",status:"processed",reference_id:"RPX-LOCAL-1"});await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"evt-same"});const dup=await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"evt-same"});assert.equal(dup.duplicatePrevented,true);const changed=webhook("payout.reversed",{id:"pout_TEST123",amount:50000,currency:"INR",status:"reversed",reference_id:"RPX-LOCAL-1"});await assert.rejects(()=>w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:changed,signature:sign(changed),eventId:"evt-same"}),e=>e instanceof Response&&e.status===409);}finally{await p.close();}});
test("out-of-order queued event cannot regress a processed payout",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});for(const[event,id]of[["payout.processed","p1"],["payout.queued","q1"]]){const status=event.split(".")[1],raw=webhook(event,{id:"pout_TEST123",amount:50000,currency:"INR",status,reference_id:"RPX-LOCAL-1"});await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:id});}assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"payout_processed_sandbox");}finally{await p.close();}});
test("reversed may supersede processed and preserves finance review state",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});for(const[event,id]of[["payout.processed","p2"],["payout.reversed","r2"]]){const status=event.split(".")[1],raw=webhook(event,{id:"pout_TEST123",amount:50000,currency:"INR",status,reference_id:"RPX-LOCAL-1"});await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:id});}assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"payout_reversed_sandbox");}finally{await p.close();}});
test("signed unknown payout is recorded unmatched and cannot mint a local payout",async()=>{const w=await world(),env=baseEnv("http://127.0.0.1:1"),raw=webhook("payout.processed",{id:"pout_UNKNOWN",amount:100,currency:"INR",status:"processed",reference_id:"NOPE"});const r=await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"unknown"});assert.equal(r.matched,false);assert.equal(w.sqlite.prepare("SELECT COUNT(*) n FROM provider_order_payouts").get().n,0);});
test("amount mismatch is rejected after signature verification",async()=>{const p=await provider();try{const w=await world();seedCommission(w);const env=baseEnv(p.url);await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"commission",payoutId:"RPX-LOCAL-1"});const raw=webhook("payout.processed",{id:"pout_TEST123",amount:49999,currency:"INR",status:"processed",reference_id:"RPX-LOCAL-1"});await assert.rejects(()=>w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"mismatch"}),e=>e instanceof Response&&e.status===409);assert.equal(w.sqlite.prepare("SELECT status FROM provider_order_payouts WHERE id='RPX-LOCAL-1'").get().status,"provider_processing_sandbox");}finally{await p.close();}});
test("settlement payout webhook marks instruction paid and statement paid",async()=>{const p=await provider();try{const w=await world();await seedSettlement(w);const env=baseEnv(p.url);const d=await w.runtime.dispatchRazorpayXSandboxPayout(w.db,env,{source:"settlement",payoutId:"PAYOUT-RPX-2"});assert.equal(d.connected,true);const raw=webhook("payout.processed",{id:"pout_TEST123",amount:70000,currency:"INR",status:"processed",reference_id:"PAYOUT-RPX-2",utr:"UTR2"});await w.runtime.processRazorpayXWebhook(w.db,env,{rawBody:raw,signature:sign(raw),eventId:"settled"});assert.equal(w.sqlite.prepare("SELECT status FROM partner_payout_instructions WHERE id='PAYOUT-RPX-2'").get().status,"paid_sandbox");assert.equal(w.sqlite.prepare("SELECT status FROM partner_settlement_statements WHERE id='SET-RPX'").get().status,"paid");}finally{await p.close();}});

import fs from "node:fs";
const source = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("source contract: signed RazorpayX receiver is public only at the provider callback boundary",()=>{const route=source("app/api/razorpayx-webhook/route.ts"),gateway=source("lib/api-gateway.ts");assert.match(route,/x-razorpay-signature/);assert.match(route,/processRazorpayXWebhook/);assert.match(route,/readBoundedRequestText/);assert.match(gateway,/\/api\/razorpayx-webhook/);});
test("source contract: staging deploy forwards only sandbox RazorpayX credentials and locks live payout off",()=>{const stage=source("scripts/stage-config.mjs"),workflow=source(".github/workflows/deploy-staging.yml");assert.match(stage,/PAWSPACE_RAZORPAYX_ENV:\s*"sandbox"/);assert.match(stage,/PAWSPACE_RAZORPAYX_LIVE_APPROVED:\s*"false"/);for(const name of ["RAZORPAYX_KEY_ID_SANDBOX","RAZORPAYX_KEY_SECRET_SANDBOX","RAZORPAYX_ACCOUNT_NUMBER_SANDBOX","RAZORPAYX_FUND_ACCOUNT_MAP_SANDBOX","RAZORPAYX_WEBHOOK_SECRET_SANDBOX"])assert.match(workflow,new RegExp(name));assert.doesNotMatch(workflow,/RAZORPAYX_KEY_ID_LIVE|RAZORPAYX_KEY_SECRET_LIVE/);});
test("source contract: provider proof is manual-only and requires Test Mode confirmation",()=>{const workflow=source(".github/workflows/razorpayx-sandbox-provider.yml");assert.match(workflow,/workflow_dispatch:/);assert.doesNotMatch(workflow,/^\s*push:/m);assert.match(workflow,/rzp_test_/);assert.match(workflow,/PAWSPACE_RAZORPAYX_LIVE_APPROVED:\s*"false"/);assert.match(workflow,/razorpayx-test-payout/);});
test("source contract: finance exposes an explicit TEST-only dispatch action",()=>{const route=source("app/api/partner-finance/route.ts"),ui=source("app/team/finance/partners/page.tsx");assert.match(route,/dispatch_razorpayx_test_payout/);assert.match(route,/environment:\s*"sandbox"/);assert.match(route,/liveMoney:false/);assert.match(ui,/Send TEST payout/);assert.match(ui,/cannot use live credentials or move real money/);});

test("executed registry: RazorpayX requires the complete sandbox+webhook credential set and never self-verifies",async()=>{const w=await world(),registry=await import("../lib/integration-readiness.ts"),env={...baseEnv("http://127.0.0.1:1"),RAZORPAYX_FUND_ACCOUNT_MAP_SANDBOX:'{"PRV-RPX":"fa_TEST123"}'};let view=await registry.listIntegrationReadiness(w.db,env),item=view.items.find(x=>x.integrationCode==="INT-PAY-02");assert.equal(item.provider,"RazorpayX");assert.equal(item.environment,"sandbox");assert.equal(item.codeBoundaryStatus,"code_ready");assert.equal(item.credentialStatus,"configured");assert.equal(item.readinessState,"sandbox_setup_required");view=await registry.listIntegrationReadiness(w.db,{...env,RAZORPAYX_WEBHOOK_SECRET_SANDBOX:""});item=view.items.find(x=>x.integrationCode==="INT-PAY-02");assert.equal(item.credentialStatus,"missing");assert.equal(item.readinessState,"sandbox_setup_required");});
