import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Sitting Gate 4 media grants are short lived opaque and private",async()=>{const source=await read("lib/sitting-proof-governance.ts");assert.match(source,/sitting_media_upload_grants/);assert.match(source,/15\*60_000/);assert.match(source,/token_hash/);assert.match(source,/sandbox_contract/);assert.match(source,/rawPublicUrl:false/);assert.match(source,/Storage confirmation must use an opaque object ID, not a public URL/);assert.match(source,/upload grant expired/);assert.match(source,/upload token mismatch/);});

test("Sitting Gate 4 enforces proof MIME size checksum scan and exact ownership",async()=>{const source=await read("lib/sitting-proof-governance.ts");assert.match(source,/image\/jpeg/);assert.match(source,/image\/png/);assert.match(source,/image\/webp/);assert.match(source,/10_000_000/);assert.match(source,/SHA-256 checksum/);assert.match(source,/belongs to another booking/);assert.match(source,/belongs to another provider/);assert.match(source,/purpose does not match this evidence slot/);assert.match(source,/has not passed scan review/);assert.match(source,/not ready for private proof access/);assert.match(source,/outside active retention/);assert.match(source,/still synthetic/);});

test("Sitting Gate 4 medication requires Care Card and clean evidence",async()=>{const source=await read("lib/sitting-proof-governance.ts");assert.match(source,/sitting_medication_administrations/);assert.match(source,/A ready Care Card is required before medication evidence/);assert.match(source,/canonical Care Card has no medication instruction/);assert.match(source,/sitting_medication/);assert.match(source,/medication_evidenced/);assert.match(source,/careCardInstructionPresent:true/);});

test("Sitting Gate 4 incidents preserve booking and never invent money actions",async()=>{const source=await read("lib/sitting-proof-governance.ts");assert.match(source,/sitting_incidents/);assert.match(source,/attention/);assert.match(source,/urgent/);assert.match(source,/emergency/);assert.match(source,/ops_escalation/);assert.match(source,/notification_status TEXT NOT NULL DEFAULT 'queued'/);assert.match(source,/bookingPreserved:true/);assert.match(source,/automaticRefund:false/);assert.match(source,/automaticPayoutChange:false/);assert.match(source,/resolve_incident/);});

test("Sitting Gate 4 keeps communications queued while adapters are disconnected",async()=>{const source=await read("lib/sitting-proof-governance.ts");assert.match(source,/sitting_customer_notifications/);assert.match(source,/push/);assert.match(source,/whatsapp/);assert.match(source,/live messaging is not connected in UAT/);assert.match(source,/communications:\{mode:\"queued_only\",liveDelivery:false/);});

test("Sitting Gate 4 API separates provider customer and staff authority",async()=>{const api=await read("app/api/sitting-proof/route.ts"),gateway=await read("lib/api-gateway.ts");assert.match(api,/providerActions=new Set<SittingProofAction>/);assert.match(api,/staffActions=new Set<SittingProofAction>/);assert.match(api,/customerActions=new Set<SittingProofAction>/);assert.match(api,/requireProviderOwnership/);assert.match(api,/requireCustomerOwnership/);assert.match(api,/requirePermission\(actor,\"bookings\.manage\"\)/);assert.match(api,/securityAudit/);assert.match(api,/sandboxOnly:true/);assert.match(gateway,/url\.pathname===\"\/api\/sitting-proof\"/);assert.match(gateway,/acknowledge_incident/);assert.match(gateway,/record_media_scan/);});

test("Sitting Gate 4 closes legacy medication photo and incident lifecycle bypass",async()=>{const api=await read("app/api/sitting-lifecycle/route.ts");assert.match(api,/evidenceCareEvents=new Set\(\[\"medication\",\"photo_update\",\"incident\"\]\)/);assert.match(api,/Medication, photo proof and incidents must use the governed Sitting proof workflow/);});

test("Sitter workspace routes evidence to the dedicated proof workspace",async()=>{const workspace=await read("app/sitter/sitting-workspace.tsx"),proof=await read("app/sitter/proof/page.tsx");assert.match(workspace,/\/sitter\/proof\?bookingId=/);assert.match(workspace,/Proof · medication · incident/);assert.doesNotMatch(workspace,/careEventType:\"medication\"/);assert.doesNotMatch(workspace,/careEventType:\"photo_update\"/);assert.doesNotMatch(workspace,/careEventType:\"incident\"/);assert.match(proof,/prepare_media/);assert.match(proof,/record_medication/);assert.match(proof,/report_incident/);assert.match(proof,/SHA-256/);assert.match(proof,/staff-authorized storage finalization and scan review/);});

test("Sitting customer can see and acknowledge incidents without changing money",async()=>{const page=await read("app/sitting/manage/sitting-customer-incidents.tsx");assert.match(page,/loadSittingProof/);assert.match(page,/scope:\"customer\"/);assert.match(page,/action:\"acknowledge_incident\"/);assert.match(page,/does not approve a refund, charge or sitter payout change/);});
