import test from"node:test";import assert from"node:assert/strict";import{Fast2SmsProviderError,normalizeIndianMobile,parseSmsTestAllowlist,PAWSPACE_SMS_TEST_MESSAGE,sendFast2SmsMessage,sendFast2SmsTest}from"../lib/sms-test-provider.ts";

test("SMS test provider normalizes Indian mobile numbers and rejects invalid input",()=>{assert.equal(normalizeIndianMobile("+91 98765 43210"),"9876543210");assert.equal(normalizeIndianMobile("9876543210"),"9876543210");assert.equal(normalizeIndianMobile("5876543210"),null);});

test("SMS test allowlist keeps only valid Indian mobile numbers",()=>{const allowed=parseSmsTestAllowlist("9876543210,+91 91234 56789,123");assert.deepEqual([...allowed],["9876543210","9123456789"]);});

test("Fast2SMS test request remains fixed-message, authorized and returns provider request id",async()=>{let captured;const result=await sendFast2SmsTest({apiKey:"test-key",phone:"+91 98765 43210",fetcher:async(input,init)=>{captured={url:String(input),init};return new Response(JSON.stringify({return:true,request_id:"REQ-1"}),{status:200,headers:{"content-type":"application/json"}});}});const url=new URL(captured.url);assert.equal(url.origin,"https://www.fast2sms.com");assert.equal(url.pathname,"/dev/bulkV2");assert.equal(url.searchParams.get("route"),"q");assert.equal(url.searchParams.get("message"),PAWSPACE_SMS_TEST_MESSAGE);assert.equal(url.searchParams.get("numbers"),"9876543210");assert.equal(url.searchParams.get("sms_details"),"1");assert.equal(url.searchParams.get("udf1"),"pawspace-sms-test");assert.equal(captured.init.method,"GET");assert.equal(captured.init.headers.Authorization,"test-key");assert.equal(result.requestId,"REQ-1");});

test("Fast2SMS live-message transport sends the supplied OTP text without changing transport semantics",async()=>{let captured;await sendFast2SmsMessage({apiKey:"secret-key",phone:"9876543210",message:"Your PawSpace verification code is 654321. It expires in 5 minutes.",udf1:"pawspace-staging-customer-otp",fetcher:async(input,init)=>{captured={url:String(input),init};return new Response(JSON.stringify({return:true,request_id:"REQ-OTP"}),{status:200,headers:{"content-type":"application/json"}});}});const url=new URL(captured.url);assert.equal(url.searchParams.get("message"),"Your PawSpace verification code is 654321. It expires in 5 minutes.");assert.equal(url.searchParams.get("numbers"),"9876543210");assert.equal(url.searchParams.get("udf1"),"pawspace-staging-customer-otp");assert.equal(captured.init.headers.Authorization,"secret-key");});

test("Fast2SMS provider failure is fail-closed and exposes only sanitized status codes",async()=>{await assert.rejects(()=>sendFast2SmsTest({apiKey:"test-key",phone:"9876543210",fetcher:async()=>new Response(JSON.stringify({return:false,status_code:412,message:["sensitive provider text"]}),{status:401})}),error=>{assert.ok(error instanceof Fast2SmsProviderError);assert.equal(error.httpStatus,401);assert.equal(error.providerStatusCode,"412");assert.doesNotMatch(error.message,/sensitive provider text/);return true;});});

test("Fast2SMS transport failure is fail-closed without leaking transport details",async()=>{await assert.rejects(()=>sendFast2SmsTest({apiKey:"test-key",phone:"9876543210",fetcher:async()=>{throw new Error("socket contained secret");}}),error=>{assert.ok(error instanceof Fast2SmsProviderError);assert.equal(error.httpStatus,null);assert.equal(error.providerStatusCode,"transport");assert.doesNotMatch(error.message,/socket contained secret/);return true;});});
