import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {installWorkersHooks} from './helpers/module-hooks.mjs';
import {fixtureIsolationWorld} from './helpers/staging-fixture-isolation-world.mjs';
installWorkersHooks('__FIXTURE_ISOLATION_DB__','__FIXTURE_ISOLATION_ENV__');
const {handleStagingFixtureIsolation,fixtureRecipientExclusion}=await import('../lib/staging-fixture-isolation.ts');
const {issueUatToken}=await import('../lib/uat-staging-auth.ts');
const {STAGING_PROVIDER_FIXTURES}=await import('../lib/staging-fixture-provider-manifest.ts');
const SHA='a'.repeat(40),BASE='https://pawspace-staging.synthetic.workers.dev/__staging/fixture-isolation';
const world=(overrides={})=>fixtureIsolationWorld({SHA,overrides,assert,STAGING_PROVIDER_FIXTURES});
async function request(w,{anonymous=false,query=`expectedSha=${SHA}`,method='GET',base=BASE}={}){const headers=anonymous?{}:{cookie:`pawspace_uat=${await issueUatToken(w.env,'founder@synthetic.test',3600)}`};return new Request(`${base}?${query}`,{method,headers});}
async function run(w,options){const old=globalThis.fetch;globalThis.fetch=()=>assert.fail('attestation may not send network requests');try{return await handleStagingFixtureIsolation(await request(w,options),w.db,w.env)}finally{globalThis.fetch=old}}
test('complete fixed fixture snapshot passes with empty lists and SELECT-only reads, no network or data disclosure',async()=>{const w=world();try{const response=await run(w),body=await response.json();assert.equal(response.status,200);assert.equal(body.ok,true);assert.equal(body.assignmentLock,false);assert.equal(body.productionReadiness,false);assert.equal(body.requiresMatchingDeploymentIsolationCertificate,true);assert.ok(w.reads.length>0);const output=JSON.stringify(body);for(const value of ['9100000000','9000000901','founder@synthetic.test','CUS0000','uatcap_'])assert.ok(!output.includes(value));assert.ok(Object.values(body.checks).every(Boolean));}finally{w.sqlite.close()}});
for(const mode of ['production','',undefined])test(`deployment ${String(mode)} returns404 before DB`,async()=>{const w=world({PAWSPACE_DEPLOYMENT_ENV:mode});try{assert.equal((await run(w)).status,404);assert.equal(w.reads.length,0)}finally{w.sqlite.close()}});
test('arbitrary origin and method fail closed',async()=>{const w=world();try{assert.equal((await run(w,{base:'https://public.example/__staging/fixture-isolation'})).status,404);assert.equal((await run(w,{method:'POST'})).status,405);assert.equal(w.reads.length,0)}finally{w.sqlite.close()}});
test('unauthenticated and signed nonfounder refuse without fixture reads',async()=>{const w=world();try{assert.equal((await run(w,{anonymous:true})).status,401);w.sqlite.exec("UPDATE app_users SET role_code='superuser'; INSERT INTO role_definitions VALUES ('superuser','[\"*\"]')");assert.equal((await run(w)).status,403);assert.ok(w.reads.every(sql=>!sql.includes('canonical_')))}finally{w.sqlite.close()}});
test('disabled and exited Founder identities refused',async()=>{const w=world();try{w.sqlite.exec("UPDATE app_users SET status='disabled'");assert.equal((await run(w)).status,401);w.sqlite.exec("UPDATE app_users SET status='active'; CREATE TABLE employee_exit_cases(id TEXT,identity_email TEXT,user_id TEXT,status TEXT,access_ends_at INTEGER); INSERT INTO employee_exit_cases VALUES ('E','founder@synthetic.test','F','approved',0)");assert.equal((await run(w)).status,401)}finally{w.sqlite.close()}});
for(const patch of [{PAWSPACE_VERSION_METADATA:undefined},{PAWSPACE_VERSION_METADATA:{id:'bad',timestamp:'2026-09-30'}},{PAWSPACE_STAGING_BUILD_SHA:undefined}])test('missing or invalid version/revision denies',async()=>{const w=world(patch);try{assert.equal((await run(w)).status,409);assert.ok(w.reads.every(sql=>!sql.includes('canonical_')))}finally{w.sqlite.close()}});
test('revision mismatch and arbitrary recipient queries denied',async()=>{const w=world();try{assert.equal((await run(w,{query:`expectedSha=${'b'.repeat(40)}`})).status,409);assert.equal((await run(w,{query:`expectedSha=${SHA}&recipient=anything`})).status,400);assert.equal((await run(w,{query:''})).status,400)}finally{w.sqlite.close()}});
for(const [name,value] of [['PAWSPACE_PAYMENT_ENV','live'],['PAWSPACE_PAYMENT_LIVE_APPROVED','true'],['PAWSPACE_RAZORPAYX_ENV','live'],['PAWSPACE_RAZORPAYX_LIVE_APPROVED','true'],['PAWSPACE_COMMUNICATION_ENV','production'],['PAWSPACE_VOICE_ENV','live'],['PAWSPACE_STAGING_LIVE_CUSTOMER_OTP','true'],['PAWSPACE_STAGING_LIVE_CUSTOMER_OTP',undefined],['PAWSPACE_SCHEDULING_ENV','production']])test(`${name}=${String(value)} denies before fixture reads`,async()=>{const w=world({[name]:value});try{const r=await run(w);assert.equal(r.status,409);assert.ok(w.reads.every(sql=>!sql.includes('canonical_')))}finally{w.sqlite.close()}});
for(const sql of ["DELETE FROM canonical_customers","UPDATE canonical_customers SET primary_phone='9000000001'","UPDATE canonical_customers SET secondary_phone='9000000002'","UPDATE canonical_customers SET source='real'","DELETE FROM canonical_providers WHERE id='uatcap_walk_ft'","UPDATE canonical_providers SET phone='9000000001' WHERE id='uatcap_walk_ft'","UPDATE provider_capacity_profiles SET updated_by='operator' WHERE id='uatcap_walk_ft'","INSERT INTO provider_capacity_profiles (id,city_id,live,status,updated_by,services_json) VALUES ('UNKNOWN','blr',1,'active','founder_seed','[\"dog_walking\"]')"])test(`fixture or any active roster mismatch denies: ${sql}`,async()=>{const w=world();try{w.sqlite.exec(sql);assert.equal((await run(w)).status,409)}finally{w.sqlite.close()}});
for(const patch of [{PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'9100000000'},{META_WHATSAPP_UAT_ALLOWLIST:'910 000 0000'},{PAWSPACE_VOICE_UAT_ALLOWLIST:'+91 90000 00985'}])test('a selected recipient on any effective allowlist denies with no allowlist disclosure',async()=>{const w=world(patch);try{const r=await run(w);assert.equal(r.status,409);assert.ok(!JSON.stringify(await r.json()).includes(Object.values(patch)[0]))}finally{w.sqlite.close()}});
test('Meta raw-truthiness fallback matches dispatch, including whitespace-only own list',()=>{assert.equal(fixtureRecipientExclusion({PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'910 000 0000',META_WHATSAPP_UAT_ALLOWLIST:''},['9100000000']).metaExcluded,false);assert.equal(fixtureRecipientExclusion({PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'9100000000',META_WHATSAPP_UAT_ALLOWLIST:'   '},['9100000000']).metaExcluded,true);assert.equal(fixtureRecipientExclusion({PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'9100000000',META_WHATSAPP_UAT_ALLOWLIST:'9999999999'},['9100000000']).metaExcluded,true)});
test('generic exact/digits/email case and voice last10 normalization are fail-closed',()=>{assert.equal(fixtureRecipientExclusion({PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'(910) 000-0000'},['9100000000']).genericExcluded,false);assert.equal(fixtureRecipientExclusion({PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'TEST@EXAMPLE.INVALID'},[],['test@example.invalid']).genericExcluded,false);assert.equal(fixtureRecipientExclusion({PAWSPACE_VOICE_UAT_ALLOWLIST:'+91 90000 00985;9999999999'},['09000000985']).voiceExcluded,false);assert.ok(Object.values(fixtureRecipientExclusion({},['9100000000'])).every(Boolean))});
test('missing fixture schema returns sanitized unproven, no SQL error or identity leakage',async()=>{const w=world();try{w.sqlite.exec('DROP TABLE canonical_customers');const r=await run(w);assert.equal(r.status,503);assert.deepEqual(await r.json(),{ok:false,code:'read_only_evidence_unavailable'})}finally{w.sqlite.close()}});
test('fixed manifest remains aligned with checked-in synthetic seed and worker bypass is before generic gateway',()=>{const sql=readFileSync(new URL('../scripts/uat-staging-provider-capacity.sql',import.meta.url),'utf8');for(const [id,phone] of Object.entries(STAGING_PROVIDER_FIXTURES))assert.ok(sql.includes(`('${id}','blr'`)&&sql.includes(`'${phone}',NULL,'uat_staging_seed'`));const source=readFileSync(new URL('../worker/index.ts',import.meta.url),'utf8');assert.ok(source.indexOf('const fixtureIsolation=await handleStagingFixtureIsolation')<source.indexOf('if (url.pathname.startsWith("/api/"))'));});

test('unknown inactive and uat_ready roster members cannot be hidden by eligibility filters',async()=>{for(const [live,status] of [[0,'inactive'],[1,'uat_ready']]){const w=world();try{w.sqlite.prepare("INSERT INTO provider_capacity_profiles (id,city_id,live,status,updated_by,services_json) VALUES ('UNKNOWN','blr',?,?,'founder_seed','[]')").run(live,status);assert.equal((await run(w)).status,409)}finally{w.sqlite.close()}}});
test('bounded roster overflow is unproven rather than a truncated passing sample',async()=>{const w=world();try{for(let i=0;i<260;i++)w.sqlite.prepare("INSERT INTO provider_capacity_profiles (id,city_id,live,status,updated_by,services_json) VALUES (?,'blr',1,'active','founder_seed','[]')").run(`overflow-${i}`);const r=await run(w);assert.equal(r.status,409);assert.equal((await r.json()).checks.bengaluruCapacityRosterProven,false)}finally{w.sqlite.close()}});
test('tampered cookie and missing wildcard are refused',async()=>{const w=world();try{const valid=await request(w);valid.headers.set('cookie',valid.headers.get('cookie')+'tampered');assert.equal((await handleStagingFixtureIsolation(valid,w.db,w.env)).status,401);w.sqlite.exec("UPDATE role_definitions SET permissions_json='[]'");assert.equal((await run(w)).status,403)}finally{w.sqlite.close()}});

test('Bengaluru boarding host cannot hide a cross-city capacity profile from isolation proof',async()=>{const w=world();try{w.sqlite.exec("UPDATE provider_capacity_profiles SET city_id='hyd' WHERE id='uatcap_host_cm'; INSERT INTO boarding_host_profiles VALUES ('uatcap_host_cm','blr')");const r=await run(w);assert.equal(r.status,409);assert.equal((await r.json()).checks.bengaluruCapacityRosterProven,false)}finally{w.sqlite.close()}});

test('safe snapshot fingerprint is stable and changes for roster membership, unsafe snapshot reveals no fingerprint',async()=>{const w=world();try{const first=await (await run(w)).json(),second=await (await run(w)).json();assert.match(first.fixtureSnapshotId,/^[a-f0-9]{64}$/);assert.equal(first.fixtureSnapshotId,second.fixtureSnapshotId);w.sqlite.exec("DELETE FROM provider_capacity_profiles WHERE id='walk_asha'");const changed=await (await run(w)).json();assert.equal(changed.ok,true);assert.notEqual(changed.fixtureSnapshotId,first.fixtureSnapshotId);w.sqlite.exec("DELETE FROM canonical_customers");assert.equal((await (await run(w)).json()).fixtureSnapshotId,null)}finally{w.sqlite.close()}});
test('staging config emits platform version binding and only an exact expected revision',async()=>{
 const {mkdtempSync,mkdirSync,writeFileSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const {fileURLToPath}=await import('node:url');const {spawnSync}=await import('node:child_process');
 for(const expected of [SHA,'main','']){const dir=mkdtempSync(join(tmpdir(),'fixture-attestation-config-'));try{mkdirSync(join(dir,'dist/server'),{recursive:true});writeFileSync(join(dir,'dist/server/wrangler.json'),'{}');const result=spawnSync(process.execPath,[fileURLToPath(new URL('../scripts/stage-config.mjs',import.meta.url))],{cwd:dir,encoding:'utf8',env:{PATH:process.env.PATH,STAGING_D1_ID:'11111111-1111-4111-8111-111111111111',PAWSPACE_UAT_ACCESS_CODE:'x'.repeat(32),PAWSPACE_UAT_SIGNING_KEY:'y'.repeat(32),PAWSPACE_IDENTITY_ASSERTION_SECRET_UAT:'z'.repeat(32),EXPECTED_SHA:expected}});assert.equal(result.status,0,result.stderr);const config=JSON.parse(readFileSync(join(dir,'dist/server/wrangler.json'),'utf8'));assert.deepEqual(config.version_metadata,{binding:'PAWSPACE_VERSION_METADATA'});assert.equal(config.vars.PAWSPACE_STAGING_BUILD_SHA,expected===SHA?SHA:undefined);assert.equal(config.name,'pawspace-staging');assert.equal(config.vars.PAWSPACE_PAYMENT_ENV,'sandbox')}finally{rmSync(dir,{recursive:true,force:true})}}
});

const GROOM_QUERY=`expectedSha=${SHA}&scope=grooming_strict`;
test('strict Grooming scope proves only the fixed customer and full-time groomer with SELECT-only reads',async()=>{const w=world();try{w.sqlite.exec("DELETE FROM provider_capacity_profiles WHERE id!='uatcap_groom_ft'; DROP TABLE boarding_host_profiles");const r=await run(w,{query:GROOM_QUERY}),body=await r.json();assert.equal(r.status,200);assert.equal(body.scope,'grooming_strict');assert.equal(body.checks.specificGroomerFixtureProven,true);assert.equal(body.strictProviderSelectionRequired,true);for(const name of ['automaticAssignmentCovered','reassignmentRecoveryCovered','bookingMutationAuthorized','assignmentLock','alternateProviderTablesCovered'])assert.equal(body[name],false);assert.equal('bengaluruCapacityRosterProven' in body.checks,false);assert.equal('fixedProviderFixturesProven' in body.checks,false);assert.ok(w.reads.filter(sql=>sql.includes('provider_capacity_profiles')).every(sql=>sql.includes("WHERE p.id='uatcap_groom_ft'")&&!sql.includes('boarding_host_profiles')));assert.ok(!JSON.stringify(body).includes('9000000901'));assert.ok(!JSON.stringify(body).includes('CUS0000'));}finally{w.sqlite.close()}});
test('strict scope does not misrepresent an unknown outside provider as globally safe',async()=>{const w=world();try{w.sqlite.exec("INSERT INTO provider_capacity_profiles (id,city_id,live,status,updated_by,services_json) VALUES ('UNKNOWN','blr',1,'active','operator','[\"dog_walking\"]')");const r=await run(w,{query:GROOM_QUERY}),body=await r.json();assert.equal(r.status,200);assert.equal(body.automaticAssignmentCovered,false);assert.equal(body.reassignmentRecoveryCovered,false);assert.equal((await run(w)).status,409);}finally{w.sqlite.close()}});
for(const scope of ['','grooming','uatcap_groom_ft','grooming_strict&scope=bengaluru_roster'])test(`unsupported or duplicated fixed scope rejected: ${scope}`,async()=>{const w=world();try{const r=await run(w,{query:`expectedSha=${SHA}&scope=${scope}`});assert.equal(r.status,400);assert.ok(w.reads.every(sql=>!sql.includes('canonical_')))}finally{w.sqlite.close()}});
for(const sql of ["DELETE FROM provider_capacity_profiles WHERE id='uatcap_groom_ft'","DELETE FROM canonical_providers WHERE id='uatcap_groom_ft'","UPDATE canonical_providers SET email='someone@example.invalid' WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET provider_model='commission' WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET live=0 WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET status='uat_ready' WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET services_json='[\"dog_walking\"]' WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET services_json='invalid' WHERE id='uatcap_groom_ft'","UPDATE provider_capacity_profiles SET city_id='hyd' WHERE id='uatcap_groom_ft'"])test(`strict groomer identity or mode mismatch denied: ${sql}`,async()=>{const w=world();try{w.sqlite.exec(sql);const r=await run(w,{query:GROOM_QUERY});assert.equal(r.status,409);assert.equal((await r.json()).checks.specificGroomerFixtureProven,false)}finally{w.sqlite.close()}});
for(const patch of [{PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'9000000901'},{META_WHATSAPP_UAT_ALLOWLIST:'900 000 0901'},{PAWSPACE_VOICE_UAT_ALLOWLIST:'+91 90000 00901'},{PAWSPACE_COMMUNICATION_UAT_ALLOWLIST:'9100000000'},{META_WHATSAPP_UAT_ALLOWLIST:'910 000 0000'},{PAWSPACE_VOICE_UAT_ALLOWLIST:'+91 91000 00000'}])test('strict scope refuses either fixed recipient on each external channel',async()=>{const w=world(patch);try{const r=await run(w,{query:GROOM_QUERY});assert.equal(r.status,409);const body=await r.json();assert.equal(body.fixtureSnapshotId,null);assert.ok(!JSON.stringify(body).includes(Object.values(patch)[0]));}finally{w.sqlite.close()}});
test('strict scope retains Founder, exact revision and runtime locks',async()=>{const w=world();try{assert.equal((await run(w,{query:GROOM_QUERY,anonymous:true})).status,401);assert.equal((await run(w,{query:`expectedSha=${'b'.repeat(40)}&scope=grooming_strict`})).status,409);w.env.PAWSPACE_STAGING_LIVE_CUSTOMER_OTP='true';assert.equal((await run(w,{query:GROOM_QUERY})).status,409);}finally{w.sqlite.close()}});
test('strict-choice production helper narrows all policy modes and refuses a changed replay provider',async()=>{const {preferredModeForChoice,providerChoiceMatchesStored,providerChoiceProblem}=await import('../lib/scheduling-provider-choice.ts');const choice={providerSelection:'specific',preferredProviderId:'uatcap_groom_ft'};assert.equal(providerChoiceProblem(choice),null);for(const policy of ['strict','preference','disabled'])assert.equal(preferredModeForChoice(choice,policy),'strict');assert.equal(providerChoiceMatchesStored(choice,{...choice,preferredProviderId:'OTHER'}),false);assert.equal(providerChoiceMatchesStored(choice,{providerSelection:'auto'}),false);});

for(const phone of ['9100000000','+91 91000 00000','09100000000','00919100000000'])test(`normalized customer OTP alias ambiguity refuses without disclosing the other account: ${phone}`,async()=>{const w=world();try{w.sqlite.prepare("INSERT INTO canonical_customers VALUES ('OTHER','hyd',?,NULL,NULL,'not_a_fixture')").run(phone);for(const query of [GROOM_QUERY,`expectedSha=${SHA}`]){const r=await run(w,{query}),body=await r.json();assert.equal(r.status,409);assert.equal(body.checks.customerOtpTargetUnambiguous,false);assert.equal(body.fixtureSnapshotId,null);assert.ok(!JSON.stringify(body).includes('OTHER'));}}finally{w.sqlite.close()}});
test('strict groomer OTP exact lookup must resolve only to the documented fixture',async()=>{const w=world();try{w.sqlite.exec("INSERT INTO canonical_providers VALUES ('OTHER','hyd','9000000901',NULL,'not_a_fixture')");const r=await run(w,{query:GROOM_QUERY}),body=await r.json();assert.equal(r.status,409);assert.equal(body.checks.groomerOtpTargetUnambiguous,false);assert.equal(body.fixtureSnapshotId,null);}finally{w.sqlite.close()}});
