import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Pet Taxi Gate 2 owns driver acceptance vehicle assignment and idempotency",async()=>{const source=await read("lib/taxi-lifecycle.ts");assert.match(source,/taxi_trip_action_keys/);assert.match(source,/taxi_vehicle_profiles/);assert.match(source,/driver_accepted/);assert.match(source,/UAT-verified vehicle/);assert.match(source,/duplicatePrevented:true/);});

test("Pet Taxi Gate 2 requires pickup handover before trip start",async()=>{const source=await read("lib/taxi-lifecycle.ts");assert.match(source,/taxi_pickup_handover_events/);assert.match(source,/A governed Pet Taxi pickup handover method is required/);assert.match(source,/otpConnected:false/);assert.match(source,/Confirmed pickup handover is required before Pet Taxi trip start/);assert.match(source,/gpsConnected:false/);assert.match(source,/telemetryMode:"deterministic_sandbox"/);});

test("Pet Taxi Gate 2 separates non-evidence lifecycle events from proof governance",async()=>{const source=await read("lib/taxi-lifecycle.ts");for(const event of["pet_settled","water_break","customer_update"])assert.match(source,new RegExp(`\\"${event}\\"`));assert.match(source,/Route, location, photo and incident evidence must use the governed Taxi proof workflow/);assert.match(source,/taxi_trip_events/);});

test("Pet Taxi Gate 2 requires drop-off handover and creates payment due instead of fake capture",async()=>{const source=await read("lib/taxi-lifecycle.ts");assert.match(source,/taxi_dropoff_handover_events/);assert.match(source,/Drop-off arrival is required before handover confirmation/);assert.match(source,/Confirmed drop-off handover is required before Pet Taxi completion/);assert.match(source,/taxi_trip_payment_events/);assert.match(source,/canonical_taxi_completion/);assert.match(source,/status='due'/);assert.match(source,/captureRequired:true/);assert.match(source,/liveMoney:false/);assert.match(source,/paymentStatus:"due"/);assert.doesNotMatch(source,/paymentStatus:"captured"/);});

test("Pet Taxi Gate 2 recovery preserves booking and route before active trip",async()=>{const source=await read("lib/taxi-lifecycle.ts");assert.match(source,/taxi_recovery_cases/);assert.match(source,/reassignment_needed/);assert.match(source,/recovery_pending/);assert.match(source,/bookingPreserved:true/);assert.match(source,/routePreserved:true/);assert.match(source,/Active\/closed Pet Taxi trips require the safety incident workflow/);});

test("Pet Taxi lifecycle API enforces provider and staff authority",async()=>{const api=await read("app/api/taxi-lifecycle/route.ts");assert.match(api,/requireProviderOwnership/);assert.match(api,/requireCustomerOwnership/);assert.match(api,/requirePermission\(actor,\"bookings\.manage\"\)/);assert.match(api,/requirePermission\(actor,\"bookings\.view\"\)/);assert.match(api,/securityAudit/);assert.match(api,/taxi\.lifecycle/);});

test("Driver workspace uses canonical Taxi lifecycle and does not claim live GPS or payment",async()=>{const page=await read("app/driver/canonical-driver-page.tsx");assert.match(page,/loadTaxiLifecycle/);assert.match(page,/updateTaxiLifecycle/);for(const action of["accept","assign_vehicle","confirm_pickup","start_trip","trip_event","arrive_dropoff","confirm_dropoff","complete_trip","driver_unavailable"])assert.match(page,new RegExp(`\\"${action}\\"`));assert.match(page,/Production GPS not connected/);assert.match(page,/Complete trip · create payment due/);assert.match(page,/live payment remain disconnected or policy-pending/);});
