import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Pet Taxi Gate 5 builds one canonical Operations exception queue",async()=>{const source=await read("lib/taxi-ops-governance.ts");assert.match(source,/taxi_ops_action_keys/);assert.match(source,/taxi_ops_notes/);assert.match(source,/b\.service_code='pet_taxi'/);for(const flag of["driver_recovery","driver_acceptance_due","emergency_incident","urgent_incident","care_incident","cancellation_policy_review","refund_pending","media_blocked","route_missing","trip_overdue","trip_payment_due","settlement_not_ready"])assert.match(source,new RegExp(flag));assert.match(source,/needsAttention/);assert.match(source,/financeReview/);assert.match(source,/routeMissing/);});

test("Pet Taxi replacement candidates require exact-window capacity and active UAT vehicle",async()=>{const source=await read("lib/taxi-ops-governance.ts");assert.match(source,/provider_capacity_profiles/);assert.match(source,/taxi_vehicle_profiles/);assert.match(source,/inspection_status='uat_verified'/);assert.match(source,/pet_taxi/);assert.match(source,/provider_unavailability/);assert.match(source,/bufferedStart/);assert.match(source,/bufferedEnd/);assert.match(source,/Selected replacement driver is not eligible/);});

test("Pet Taxi recovery preserves same booking trip and route before trip start",async()=>{const source=await read("lib/taxi-ops-governance.ts");assert.match(source,/assign_replacement/);assert.match(source,/createAssignmentOffer/);assert.match(source,/routePreserved:true/);assert.match(source,/UPDATE canonical_bookings SET provider_id=\?,status='reassignment_offered'/);assert.match(source,/UPDATE taxi_trips SET provider_id=\?,vehicle_id=NULL,status='scheduled'/);assert.match(source,/UPDATE scheduling_reservations SET provider_id=\?,status='assigned'/);assert.match(source,/replacement_driver_offered/);});

test("Replacement driver acceptance verifies booking work order trip reservation and vehicle",async()=>{const source=await read("lib/taxi-recovery-governance.ts"),api=await read("app/api/taxi-recovery/route.ts"),page=await read("app/driver/recovery/page.tsx");assert.match(source,/reassignment_offered/);assert.match(source,/Replacement driver does not match the canonical booking, work order and trip/);assert.match(source,/No pending replacement driver offer is available/);assert.match(source,/canonical scheduling reservation/);assert.match(source,/active UAT-verified vehicle/);assert.match(source,/replacement_accepted/);assert.match(source,/routePreserved:true/);assert.match(api,/requireProviderOwnership/);assert.match(page,/Accept replacement Taxi trip/);});

test("Operations cannot close Taxi recovery before replacement acceptance",async()=>{const source=await read("lib/taxi-ops-governance.ts");assert.match(source,/Replacement driver must accept before Operations can close recovery/);assert.match(source,/status='replacement_accepted'/);assert.match(source,/recovery_closed/);assert.match(source,/routePreserved:true/);});

test("Pet Taxi Gate 5 API is staff permissioned and audited",async()=>{const api=await read("app/api/taxi-ops/route.ts");assert.match(api,/requirePermission\(actor,\"bookings\.manage\"\)/);assert.match(api,/assign_replacement/);assert.match(api,/close_recovery/);assert.match(api,/add_note/);assert.match(api,/securityAudit/);});

test("Pet Taxi Team Operations surface keeps specialist authority separate",async()=>{const page=await read("app/team/operations/taxi/page.tsx"),client=await read("lib/taxi-ops-client.ts");assert.match(page,/Driver recovery/);assert.match(page,/Offer replacement/);assert.match(page,/Close accepted recovery/);assert.match(page,/Incident resolution stays in Taxi proof governance/);assert.match(page,/Payments\/refunds\/driver settlement\/tax stay in Taxi Finance governance/);assert.match(client,/\/api\/taxi-ops/);});

test("Pet Taxi Gate 5 is engineering closed but explicitly not production ready",async()=>{const source=await read("lib/taxi-ops-governance.ts"),page=await read("app/team/operations/taxi/page.tsx");assert.match(source,/engineeringGate:\"gate_5_closed_uat_contract\"/);assert.match(source,/productionReady:false/);assert.match(source,/productionMaps:\"disconnected\"/);assert.match(source,/productionGps:\"disconnected\"/);assert.match(source,/payments:\"sandbox_only\"/);assert.match(source,/tax:\"configuration_required\"/);assert.match(source,/driverPayout:\"rule_pending\"/);assert.match(source,/vehicleCompliance:\"uat_only\"/);assert.match(page,/Production ready:/);});
