import test from 'node:test';
import assert from 'node:assert/strict';
import {freshWorld,seedBooking,TRAINER,CUSTOMER,sessionCookie,routeCall} from './helpers/training-lifecycle-harness.mjs';
const {materializeTrainingBooking}=await import('../lib/training-programme.ts');
const {issueMediaUploadGrant}=await import('../lib/media-upload-boundary.ts');
const media=await import('../app/api/training-session-media/route.ts');
const upload=await import('../app/api/training-session-media/upload/route.ts');
const content=await import('../app/api/training-session-media/content/route.ts');
async function fixture(){const w=freshWorld();seedBooking(w,{id:'VIDEO',group:'VIDEO-G',sessions:1,total:500,dueNow:500,packageCode:'trainer-meet-greet'});return {...w,...await materializeTrainingBooking(w.db,{bookingId:'VIDEO',actorId:'qa'})};}
async function grant(w,extra={}){return issueMediaUploadGrant(w.db,{bookingId:'VIDEO',scopeType:'training_session',scopeId:w.sessions[0].id,providerId:TRAINER,serviceCode:'dog_training',category:'training_video',mimeType:'video/mp4',sizeBytes:12,sha256:'a'.repeat(64),actorId:'qa',...extra});}
test('Training video accepts bounded MP4/WebM grants but preserves photo MIME floor',async()=>{const w=await fixture();try{assert.equal((await grant(w)).mimeType,'video/mp4');assert.equal((await grant(w,{mimeType:'video/webm',sha256:'b'.repeat(64)})).mimeType,'video/webm');await assert.rejects(grant(w,{category:'before_service'}));await assert.rejects(grant(w,{sizeBytes:10_000_001}));await assert.rejects(grant(w,{fileName:'video.js'}));await assert.rejects(grant(w,{serviceCode:'grooming'}));}finally{w.sqlite.close();}});
test('Video registration denies foreign provider and missing private bucket cannot count as stored',async()=>{const w=await fixture();try{const body={sessionId:w.sessions[0].id,purpose:'training_video',mimeType:'video/mp4',sizeBytes:12,sha256:'a'.repeat(64)};assert.equal((await routeCall(media.POST,'POST','/api/training-session-media',{body,cookie:await sessionCookie(w.db,'provider','foreign')})).status,403);const r=await routeCall(media.POST,'POST','/api/training-session-media',{body,cookie:await sessionCookie(w.db,'provider',TRAINER)});assert.equal(r.status,201);const req=new Request('https://pawspace.example/api/training-session-media/upload',{method:'PUT',headers:{cookie:await sessionCookie(w.db,'provider',TRAINER),'x-pawspace-media-id':r.body.data.id,'x-pawspace-upload-token':r.body.data.upload.token,'content-type':'video/mp4'},body:new Uint8Array(12)});assert.equal((await upload.PUT(req)).status,503);assert.equal(w.sqlite.prepare('SELECT access_status FROM service_media_assets WHERE id=?').get(r.body.data.id).access_status,'pending_upload');assert.equal((await routeCall(content.GET,'GET','/api/training-session-media/content?id='+r.body.data.id,{cookie:await sessionCookie(w.db,'customer',CUSTOMER)})).status,409);assert.equal((await routeCall(content.GET,'GET','/api/training-session-media/content?id='+r.body.data.id,{cookie:await sessionCookie(w.db,'customer','foreign-customer')})).status,403);}finally{w.sqlite.close();}});
test('Private in-memory test adapter verifies bytes, single use and authorized parent playback (not hosted storage proof)',async()=>{
 const objects=new Map();const bucket={async put(key,bytes,opt){objects.set(key,{bytes:new Uint8Array(bytes),type:opt.httpMetadata.contentType});},async head(key){const x=objects.get(key);return x?{size:x.bytes.length,httpMetadata:{contentType:x.type}}:null;},async get(key){const x=objects.get(key);return x?{size:x.bytes.length,httpMetadata:{contentType:x.type},arrayBuffer:async()=>x.bytes.buffer}:null;}};
 const w=freshWorld({PAWSPACE_MEDIA_BUCKET:bucket});try{seedBooking(w,{id:'VIDEO',group:'VIDEO-G',sessions:1,total:500,dueNow:500,packageCode:'trainer-meet-greet'});const p=await materializeTrainingBooking(w.db,{bookingId:'VIDEO',actorId:'qa'});const bytes=new Uint8Array([0,0,0,12,102,116,121,112,105,115,111,109]);const hash=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex');const cookie=await sessionCookie(w.db,'provider',TRAINER);
 const r=await routeCall(media.POST,'POST','/api/training-session-media',{cookie,body:{sessionId:p.sessions[0].id,purpose:'training_video',mimeType:'video/mp4',sizeBytes:12,sha256:hash}});assert.equal(r.status,201);
 const request=()=>new Request('https://pawspace.example/api/training-session-media/upload',{method:'PUT',headers:{cookie,'x-pawspace-media-id':r.body.data.id,'x-pawspace-upload-token':r.body.data.upload.token,'content-type':'video/mp4'},body:bytes});
 assert.equal((await upload.PUT(request())).status,200);assert.equal((await upload.PUT(request())).status,409);assert.equal(objects.size,1);
 // Separate normal review is intentionally exercised; UAT permitted-environment release is not a malware scan claim.
 const review=await routeCall(media.PATCH,'PATCH','/api/training-session-media',{preview:true,body:{id:r.body.data.id,action:'record_review',decision:'approved',reason:'Synthetic test video reviewed separately'}});assert.equal(review.status,200,JSON.stringify(review.body));
 const parent=await sessionCookie(w.db,'customer',CUSTOMER);const response=await content.GET(new Request('https://pawspace.example/api/training-session-media/content?id='+r.body.data.id,{headers:{cookie:parent}}));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.deepEqual(new Uint8Array(await response.arrayBuffer()),bytes);
 w.sqlite.prepare("UPDATE service_media_assets SET retention_status='revoked' WHERE id=?").run(r.body.data.id);assert.equal((await routeCall(content.GET,'GET','/api/training-session-media/content?id='+r.body.data.id,{cookie:parent})).status,409);
 }finally{w.sqlite.close();}
});
