import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { installAiHooks, freshAiDb, seedCustomer } from './helpers/ai-harness.mjs';
import { makeD1 } from './helpers/taxi-harness.mjs';
installAiHooks();
const { POST } = await import('../app/api/whatsapp/meta-webhook/route.ts');
const { ensureWhatsAppAiLeadTables } = await import('../lib/whatsapp-ai-lead-orchestration.ts');
const { queueWhatsAppUatOutbound } = await import('../lib/whatsapp-uat-adapter.ts');

test('signed STOP survives failure after inbound commit and blocks later outbound on retry', async () => {
  const secret = 'test-meta-opt-out-secret';
  const { sqlite } = freshAiDb({ META_WHATSAPP_APP_SECRET: secret });
  const db = makeD1(sqlite);
  globalThis.__AI_DB__ = db;
  seedCustomer(sqlite, 'CUS-STOP', 'Test Customer', '9876500001');
  await ensureWhatsAppAiLeadTables(db);
  sqlite.prepare("INSERT INTO customer_contact_preferences (customer_id,marketing_consent,service_consent,whatsapp_consent,sms_consent,email_consent,opt_out,source,updated_by,updated_at) VALUES ('CUS-STOP',1,1,1,0,0,0,'test','test',?)").run(Date.now());
  const payload = { object: 'whatsapp_business_account', entry: [{ changes: [{ value: { messages: [{ id: 'wamid.stop.recovery', from: '919876500001', timestamp: String(Math.floor(Date.now()/1000)), type: 'text', text: { body: 'STOP' } }] } }] }] };
  const raw = JSON.stringify(payload);
  const request = () => new Request('https://pawspace.test/api/whatsapp/meta-webhook', { method:'POST', headers: { 'content-type':'application/json', 'x-hub-signature-256': `sha256=${createHmac('sha256',secret).update(raw).digest('hex')}` }, body: raw });
  db.onSql("INSERT INTO customer_contact_preferences", () => { throw new Error('opt-out storage temporarily unavailable'); });
  const failed = await POST(request());
  assert.equal(failed.status,503, await failed.text());
  assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM communication_messages WHERE direction='inbound'").get().n,1);
  assert.equal(sqlite.prepare("SELECT opt_out FROM customer_contact_preferences WHERE customer_id='CUS-STOP'").get().opt_out,0);
  const threadId = sqlite.prepare("SELECT thread_id FROM communication_messages WHERE direction='inbound'").get().thread_id;
  sqlite.prepare("INSERT INTO whatsapp_no_response_sequences (id,thread_id,customer_id,provider,routing_mode,anchor_message_id,anchor_created_at,status,offer_type,offer_reference,created_at,updated_at) VALUES ('SEQ-STOP',?,'CUS-STOP','meta_whatsapp','chatbot_only','ANCHOR-STOP',?,'active','test','test',?,?)").run(threadId,Date.now(),Date.now(),Date.now());
  sqlite.prepare("INSERT INTO whatsapp_no_response_steps (id,sequence_id,step_index,delay_minutes,due_at,template_key,status,idempotency_key,created_at,updated_at) VALUES ('STEP-STOP','SEQ-STOP',1,10,?,'test','pending','step-stop',?,?)").run(Date.now(),Date.now(),Date.now());
  sqlite.prepare("UPDATE gateway_inbound_queue SET next_attempt_at=0").run();
  db.onSql("UPDATE whatsapp_uat_events SET detail_json", () => { throw new Error('completion marker unavailable'); });
  const interruptedCompletion = await POST(request());
  assert.equal(interruptedCompletion.status,503, await interruptedCompletion.text());
  assert.equal(sqlite.prepare("SELECT opt_out FROM customer_contact_preferences WHERE customer_id='CUS-STOP'").get().opt_out,0,'failed completion rolls back the companion consent write');
  assert.equal(sqlite.prepare("SELECT status FROM whatsapp_no_response_steps WHERE id='STEP-STOP'").get().status,'pending');
  sqlite.prepare("UPDATE gateway_inbound_queue SET next_attempt_at=0").run();
  const retry = await POST(request());
  assert.equal(retry.status,200, await retry.text());
  assert.equal(sqlite.prepare("SELECT opt_out FROM customer_contact_preferences WHERE customer_id='CUS-STOP'").get().opt_out,1,'retry must complete opt-out instead of skipping the already saved inbound message');
  assert.equal(sqlite.prepare("SELECT status FROM whatsapp_no_response_sequences WHERE id='SEQ-STOP'").get().status,'cancelled');
  assert.equal(sqlite.prepare("SELECT status FROM whatsapp_no_response_steps WHERE id='STEP-STOP'").get().status,'cancelled');
  const inbound = sqlite.prepare("SELECT thread_id FROM communication_messages WHERE direction='inbound'").get();
  const outbound = await queueWhatsAppUatOutbound(db,{provider:'meta_whatsapp',threadId:inbound.thread_id,customerId:'CUS-STOP',text:'Follow-up',idempotencyKey:'stop-recovery-followup',createdBy:'test'});
  assert.equal(outbound.queued,false);
  assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM communication_messages WHERE direction='outbound'").get().n,0);
  assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM communication_messages WHERE direction='inbound'").get().n,1);
  sqlite.prepare("UPDATE customer_contact_preferences SET opt_out=0,whatsapp_consent=1 WHERE customer_id='CUS-STOP'").run();
  await POST(request());
  // A repackaged provider envelope can reach message-level dedupe despite envelope-level dedupe.
  const { processMetaWhatsAppEvents, parseMetaWhatsAppWebhook } = await import('../lib/meta-whatsapp-webhook.ts');
  await processMetaWhatsAppEvents(db,parseMetaWhatsAppWebhook(payload),raw);
  assert.equal(sqlite.prepare("SELECT opt_out FROM customer_contact_preferences WHERE customer_id='CUS-STOP'").get().opt_out,0,'an already completed old STOP replay must not revoke a later consent');
  sqlite.close();
});
