import{authError,database}from"../../../lib/server-auth";
import{createTaxiQuote,listTaxiRouteClasses,type TaxiPaymentMode}from"../../../lib/taxi-governance";
import{createTaxiRideQuote}from"../../../lib/taxi-ride-governance";
import{computeTaxiRouteLeg}from"../../../lib/taxi-route-pricing";
import{TAXI_VEHICLES}from"../../../lib/taxi-business-rules";
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
function sameOriginWrite(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin Pet Taxi quote blocked",{status:403});}
async function failure(error:unknown){if(error instanceof Response&&error.status>=400&&error.status<600){const message=await error.text().catch(()=>"");return json({error:message||"Pet Taxi commercial request failed"},error.status);}return authError(error,"Pet Taxi commercial request failed");}
export async function GET(request:Request){try{const scheduledStart=new URL(request.url).searchParams.get("scheduledStart")||new Date().toISOString(),routes=await listTaxiRouteClasses(await database(),scheduledStart);return json({data:{routes,vehicles:Object.values(TAXI_VEHICLES),source:"canonical_taxi_governance",routeSource:"google_routes_uat_for_new_rides",productionMapsVerified:false,liveAvailability:false,liveMoney:false}})}catch(error){return failure(error)}}
type RideBody={originLabel?:string;destinationLabel?:string;returnDropLabel?:string;passengerCount?:number;petCount?:number;luggageCount?:number;scheduledStart?:string;tripType?:"one_way"|"round_trip";ridePurpose?:"regular"|"airport";waitingMinutes?:number};
export async function POST(request:Request){try{sameOriginWrite(request);const body=await request.json() as RideBody&{routeCode?:string;paymentMode?:TaxiPaymentMode;couponCode?:string};
  // Legacy route-class input remains executable for old callers while the customer UI uses address pricing.
  if(body.routeCode){if(!body.originLabel||!body.destinationLabel||!body.scheduledStart)return json({error:"Pet Taxi route, pickup, drop-off and pickup time are required"},400);const quote=await createTaxiQuote(await database(),{routeCode:body.routeCode,originLabel:body.originLabel,destinationLabel:body.destinationLabel,petCount:Number(body.petCount||0),scheduledStart:body.scheduledStart,paymentMode:body.paymentMode||"sandbox_deferred",couponCode:body.couponCode});return json({data:{...quote,liveMoney:false}},201)}
  const origin=String(body.originLabel||"").trim(),destination=String(body.destinationLabel||"").trim(),scheduledStart=String(body.scheduledStart||"").trim(),tripType=body.tripType||"one_way",ridePurpose=body.ridePurpose||"regular",returnDrop=String(body.returnDropLabel||"").trim();if(!origin||!destination||!scheduledStart)return json({error:"Pickup address, drop address, pickup date and time are required"},400);if(tripType==="round_trip"&&!returnDrop)return json({error:"Round trip requires a return drop address"},400);
  const {env}=await import("cloudflare:workers"),runtime=env as unknown as Record<string,unknown>,outbound=await computeTaxiRouteLeg(runtime,origin,destination),returnLeg=tripType==="round_trip"?await computeTaxiRouteLeg(runtime,destination,returnDrop):null,distanceKm=Math.round((outbound.distanceKm+(returnLeg?.distanceKm||0))*100)/100,estimatedDurationMinutes=outbound.durationMinutes+(returnLeg?.durationMinutes||0);const quote=await createTaxiRideQuote(await database(),{originLabel:origin,destinationLabel:destination,returnDropLabel:returnDrop||undefined,passengerCount:Number(body.passengerCount),petCount:Number(body.petCount),luggageCount:Number(body.luggageCount),scheduledStart,tripType,ridePurpose,waitingMinutes:Number(body.waitingMinutes||0),distanceKm,estimatedDurationMinutes,routeProvider:"google_routes_uat"});return json({data:quote},201)
 }catch(error){return failure(error)}}
