"use client";

import{useEffect,useState,useRef,useCallback}from"react";
import Link from"next/link";
import CaregiverConversation from "./caregiver-conversation";
import StayCareChoice from "./stay-care-choice";
import BookingServiceFeedback from "./booking-service-feedback";
import {useIntentIdempotency,intentOf} from "../../lib/use-intent-idempotency";
import{saveCustomerBoardingCare}from"../../lib/boarding-customer-care";
import type{BoardingCarePlan}from"../../lib/boarding-stay-lifecycle";
import{loadCustomerBoardingStay,updateBoardingStay,type BoardingStay}from"../../lib/boarding-stay-client";
import{requestBoardingFinanceChange}from"../../lib/boarding-finance-client";
import{loadBoardingProof,updateBoardingProof,type BoardingProofSnapshot}from"../../lib/boarding-proof-client";
import{formatIndiaDateTime}from"../../lib/india-time";
import styles from"./stay-flow.module.css";
import {indiaDateTimeInput,requireFutureIndiaInput} from "../../lib/customer-booking-safety";
import {plainErrorMessage} from "../../lib/safe-json-response";
import {boardingBookingHref,boardingExtensionClosedReason,boardingRequestStatusText,boardingStayHeadline,boardingStayMessage,boardingStayPaymentDue,inr,label} from "../../lib/boarding-customer-stay-view";
import {HOST_REQUESTS_NOTE,HOST_REQUESTS_NOT_INCLUDED,HOST_REQUESTS_TITLE,hostRequestsFromCarePlan} from "../../lib/boarding-host-requests";

function when(value:string|number){return formatIndiaDateTime(value,{fallback:String(value)});}
const localInput=indiaDateTimeInput;
function suggestedExtension(value:string){const ms=Date.parse(value);return Number.isFinite(ms)?indiaDateTimeInput(ms+86_400_000):"";}

/** The stay's state and, while it is unpaid, "Payment pending" with the way to pay (never inferred from the stay status). */
export function BoardingStaySummary({stay,caregiverName,routeScope="legacy"}:{stay:BoardingStay;caregiverName:string;routeScope?:"legacy"|"v2"}){
 const due=boardingStayPaymentDue(stay);
 return <article className={styles.careLive}><span>BOARDING STAY · {stay.booking_id}</span><h4>{boardingStayHeadline(stay)}</h4><p>{boardingStayMessage(stay)} Host: {stay.provider_name||caregiverName}. Stay window: {when(stay.check_in_at)} → {when(stay.check_out_at)}.</p>{due?<Link className={styles.primary} href={boardingBookingHref(stay.booking_id,routeScope,true)}>{due.amount?`Pay ${inr(due.amount)}`:"Complete payment"}</Link>:<Link href={boardingBookingHref(stay.booking_id,routeScope)}>Booking and payment details</Link>}</article>;
}

/** The Care Card's requests to the host, as requests: not part of the booking price. */
export function BoardingHostRequests({plan}:{plan:unknown}){
 const requests=hostRequestsFromCarePlan(plan);
 if(!requests.length)return null;
 return <article className={styles.next}><span>{HOST_REQUESTS_TITLE.toUpperCase()}</span><h4>{HOST_REQUESTS_NOT_INCLUDED}</h4><p>{requests.join(" · ")}</p><p>{HOST_REQUESTS_NOTE}</p></article>;
}

export default function BoardingCustomerStayPanel({bookingId,caregiverName,initialCarePlan,initialError,routeScope="legacy"}:{routeScope?:"legacy"|"v2";bookingId:string;caregiverName:string;initialCarePlan?:BoardingCarePlan;initialError?:string}){
 const[stay,setStay]=useState<BoardingStay|null>(null),[proof,setProof]=useState<BoardingProofSnapshot|null>(null),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(""),[error,setError]=useState(initialError||""),[message,setMessage]=useState(""),[emergencyContact,setEmergencyContact]=useState(""),[vet,setVet]=useState(""),[feeding,setFeeding]=useState(""),[medication,setMedication]=useState(""),[specialInstructions,setSpecialInstructions]=useState(""),[requestedEnd,setRequestedEnd]=useState(""),[cancelReason,setCancelReason]=useState(""),[changeReason,setChangeReason]=useState(""),[changeStart,setChangeStart]=useState(""),[changeEnd,setChangeEnd]=useState("");
 const careIntent=useRef({payload:"",key:""}),changeLock=useRef(false);
 const changeKeys=useIntentIdempotency("boarding-customer-change");
 const hydrate=useCallback((next:BoardingStay|null)=>{setStay(next);if(!next)return;const plan=next.carePlan?.plan??initialCarePlan??{};setEmergencyContact(String(plan.emergencyContact??""));setVet(String(plan.vet??""));setFeeding(String(plan.feeding??""));setMedication(String(plan.medication??""));setSpecialInstructions(String(plan.specialInstructions??""));setRequestedEnd(current=>current||suggestedExtension(next.check_out_at));setChangeStart(current=>current||localInput(next.check_in_at));setChangeEnd(current=>current||localInput(next.check_out_at));},[initialCarePlan]);
 const refresh=async()=>{const next=await loadCustomerBoardingStay(bookingId);hydrate(next);if(next)setProof(await loadBoardingProof(next.id,true));else setProof(null);return next;};
 useEffect(()=>{let active=true;void loadCustomerBoardingStay(bookingId).then(async next=>{if(!active)return;hydrate(next);setError(next?.carePlan?.status==="ready"?"":initialError||"");if(next){try{const snapshot=await loadBoardingProof(next.id,true);if(active)setProof(snapshot);}catch(problem){if(active)setError(plainErrorMessage(problem,"Unable to load Boarding proof status"));}}}).catch(problem=>{if(active)setError(plainErrorMessage(problem,"Unable to load Boarding stay"));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[bookingId,hydrate,initialError,attempt]);
 const saveCarePlan=async()=>{if(!stay)return;setBusy("care");setError("");setMessage("");const plan={emergencyContact,vet,feeding,medication,specialInstructions},payload=JSON.stringify({bookingId,plan});if(careIntent.current.payload!==payload)careIntent.current={payload,key:`boarding-care:${crypto.randomUUID()}`};try{await saveCustomerBoardingCare(bookingId,plan,careIntent.current.key);setMessage("Care instructions saved.");await refresh();}catch(problem){setError(plainErrorMessage(problem,"Unable to confirm care-plan save."));}finally{setBusy("");}};
 const requestExtension=async()=>{if(changeLock.current||!stay||!requestedEnd)return;changeLock.current=true;setBusy("extension");setError("");setMessage("");try{const iso=requireFutureIndiaInput(requestedEnd);await updateBoardingStay({stayId:stay.id,action:"request_extension",idempotencyKey:changeKeys.keyFor(intentOf([bookingId,stay.id,"extension"],{requestedEnd:iso})),requestedEnd:iso,reason:"Customer requested a longer Boarding stay"});await refresh();setMessage("Extension request recorded. Your paid checkout stays the same until the extra nights are priced and agreed.");}catch(problem){setError(plainErrorMessage(problem,"Unable to request extension"));}finally{changeLock.current=false;setBusy("");}};
 const requestCancellation=async()=>{if(changeLock.current||!stay||cancelReason.trim().length<3)return;changeLock.current=true;setBusy("cancel");setError("");setMessage("");try{const result=await requestBoardingFinanceChange({bookingId,action:"request_cancel",idempotencyKey:changeKeys.keyFor(intentOf([bookingId,stay.id,"cancel"],{reason:cancelReason.trim()})),reason:cancelReason.trim()});setMessage(`Cancellation request recorded · ${label(String(result.status||"policy_review_required"))}. No refund amount is calculated automatically.`);setCancelReason("");}catch(problem){setError(plainErrorMessage(problem,"Unable to request cancellation"));}finally{changeLock.current=false;setBusy("");}};
 const requestDateChange=async()=>{if(changeLock.current||!stay||!changeStart||!changeEnd||changeReason.trim().length<3)return;changeLock.current=true;setBusy("date-change");setError("");setMessage("");try{const result=await requestBoardingFinanceChange({bookingId,action:"request_date_change",idempotencyKey:changeKeys.keyFor(intentOf([bookingId,stay.id,"date-change"],{requestedStart:changeStart,requestedEnd:changeEnd,reason:changeReason.trim()})),reason:changeReason.trim(),requestedStart:requireFutureIndiaInput(changeStart),requestedEnd:requireFutureIndiaInput(changeEnd)});setMessage(`Date-change request recorded · ${boardingRequestStatusText(String(result.status||"commercial_quote_required"))}. The paid stay window is unchanged.`);}catch(problem){setError(plainErrorMessage(problem,"Unable to request date change"));}finally{changeLock.current=false;setBusy("");}};
 const acknowledgeIncident=async(incidentId:string)=>{if(!stay)return;setBusy(`incident:${incidentId}`);setError("");setMessage("");try{await updateBoardingProof({stayId:stay.id,action:"acknowledge_incident",incidentId,idempotencyKey:`boarding:${stay.id}:incident-ack:${incidentId}`});await refresh();setMessage("Incident acknowledgement recorded for your stay.");}catch(problem){setError(plainErrorMessage(problem,"Unable to acknowledge incident"));}finally{setBusy("");}};
 if(loading)return<article className={styles.next}><span>BOARDING STAY</span><h4>Loading stay status…</h4></article>;
 if(!stay)return<article className={styles.next}><span>BOARDING STAY</span><h4>Stay record unavailable</h4><p>{error||"No Boarding stay was found for this booking. Check the booking link and the account you signed in with."}</p><button type="button" onClick={()=>{setLoading(true);setError("");setAttempt(value=>value+1);}}>Retry loading the stay</button></article>;
 const changeAllowed=["awaiting_host_acceptance","confirmed"].includes(stay.status),closed=["completed","cancelled"].includes(stay.status),extensionClosed=boardingExtensionClosedReason(stay);
 return<>
  <BoardingStaySummary stay={stay} caregiverName={caregiverName} routeScope={routeScope}/>
  {error&&<p role="alert" className={styles.hint}>{error}</p>}{message&&<p className={styles.hint}>{message}</p>}
  {proof?.incidents.length?<article className={styles.next}><span>CARE INCIDENTS</span><h4>Incident record</h4><p>Incidents are recorded against this stay and shared with PawSpace Operations. Acknowledging confirms you saw the record; it does not approve a refund, charge or payout change.</p>{proof.incidents.map(incident=><div key={incident.id} className={styles.hint}><b>{label(incident.severity)} · {label(incident.status)}</b><br/>{incident.summary}<br/><span>Reported {when(incident.reported_at)}</span>{incident.resolution&&<><br/><span>Resolution: {incident.resolution}</span></>}{incident.customer_acknowledged_at?<><br/><span>Acknowledged {when(incident.customer_acknowledged_at)}</span></>:<><br/><button className={styles.primary} disabled={busy===`incident:${incident.id}`} onClick={()=>acknowledgeIncident(incident.id)}>{busy===`incident:${incident.id}`?"Recording…":"Acknowledge incident"}</button></>}</div>)}</article>:null}
  <BoardingHostRequests plan={stay.carePlan?.plan}/>
  <article className={styles.next}><span>OPTIONAL PET TAXI</span><h4>Add pickup or drop for this Boarding stay</h4><p>Pet Taxi is quoted separately from Boarding. Your stay booking only preselects the relationship; Taxi still requires its own route, vehicle, driver and 50% verified booking fee.</p><Link className={styles.primary} href={routeScope==="v2"?`/v2/taxi?sourceBookingId=${encodeURIComponent(bookingId)}`:`/mobile-app?service=pet_taxi&sourceBookingId=${encodeURIComponent(bookingId)}`}>Add Pet Taxi for this stay →</Link></article>
  <article className={styles.next}><span>CARE PLAN · {label(stay.care_plan_status)}</span><h4>Emergency and routine instructions</h4><p>Your host can check your pet in once this care plan is saved.</p><label className={styles.field}>Emergency contact<input value={emergencyContact} onChange={event=>setEmergencyContact(event.target.value)} placeholder="Name and reachable phone" /></label><label className={styles.field}>Vet details<input value={vet} onChange={event=>setVet(event.target.value)} placeholder="Clinic / vet and contact" /></label><StayCareChoice kind="feeding" title="Feeding routine" value={feeding} onChange={setFeeding} disabled={Boolean(busy)||closed}/><StayCareChoice kind="medication" title="Medication / allergies" value={medication} onChange={setMedication} disabled={Boolean(busy)||closed}/><StayCareChoice kind="specialInstructions" title="Special instructions" value={specialInstructions} onChange={setSpecialInstructions} disabled={Boolean(busy)||closed}/><button className={styles.primary} disabled={busy==="care"||!emergencyContact.trim()||!vet.trim()||closed} onClick={saveCarePlan}>{busy==="care"?"Saving…":"Save care plan"}</button></article>
  <article className={styles.next}><span>STAY EXTENSION</span><h4>No automatic charge or date change</h4>{extensionClosed&&<p className={styles.hint}>{extensionClosed}</p>}<p>An extension is a request: PawSpace checks your host&apos;s capacity and prices the extra nights first. Your paid checkout does not change until you agree the new price.</p><label className={styles.field}>Requested new checkout (IST)<input type="datetime-local" min={localInput(stay.check_out_at)} value={requestedEnd} onChange={event=>setRequestedEnd(event.target.value)} /></label><button className={styles.primary} disabled={busy==="extension"||!requestedEnd||Boolean(extensionClosed)} onClick={requestExtension}>{busy==="extension"?"Checking capacity…":"Request extension"}</button>{stay.extension&&<p className={styles.hint}>Latest request: {when(stay.extension.requested_end)} · {boardingRequestStatusText(stay.extension.status)}. Original checkout: {when(stay.check_out_at)}.</p>}</article>
  <article className={styles.next}><span>CHANGE STAY DATES</span><h4>Request first; we recheck the price and your host&apos;s capacity</h4><p>Your request does not change the paid stay. PawSpace confirms the new dates and any price difference with you before anything changes.</p><label className={styles.field}>Requested check-in (IST)<input type="datetime-local" value={changeStart} onChange={event=>setChangeStart(event.target.value)} /></label><label className={styles.field}>Requested checkout (IST)<input type="datetime-local" value={changeEnd} onChange={event=>setChangeEnd(event.target.value)} /></label><label className={styles.field}>Reason<textarea value={changeReason} onChange={event=>setChangeReason(event.target.value)} placeholder="Why do you need to change the stay dates?" /></label><button className={styles.primary} disabled={busy==="date-change"||!changeAllowed||!changeStart||!changeEnd||changeReason.trim().length<3} onClick={requestDateChange}>{busy==="date-change"?"Recording request…":"Request date change"}</button></article>
  <article className={styles.next}><span>CANCELLATION</span><h4>Refund policy review required</h4><p>A cancellation request is reviewed by PawSpace. No refund amount is calculated automatically; PawSpace confirms any refund with you.</p><label className={styles.field}>Reason<textarea value={cancelReason} onChange={event=>setCancelReason(event.target.value)} placeholder="Why do you need to cancel?" /></label><button className={styles.primary} disabled={busy==="cancel"||closed||cancelReason.trim().length<3} onClick={requestCancellation}>{busy==="cancel"?"Recording request…":"Request cancellation"}</button></article>
  <div className={styles.events}>{stay.events.length?stay.events.map(item=><article key={item.id}><i>✓</i><div><b>{label(item.event_type)}</b><span>{when(item.created_at)}</span></div></article>):<article><i>○</i><div><b>No care events yet</b><span>Host acceptance, check-in and care updates will appear here.</span></div></article>}</div>
  <CaregiverConversation key={bookingId} bookingId={bookingId}/><BookingServiceFeedback bookingId={bookingId} completed={stay.status==="completed"}/>
  <p className={styles.hint}>Stay photos are private to your booking and your host. Live WhatsApp and push updates, and real payments and refunds, are switched off in this test environment.</p>
 </>;
}
