"use client";
import{useEffect,useRef,useState}from"react";
import LiveTrackingPanel from"../components/live-tracking/live-tracking-panel";
import styles from"./customer-grooming-live-card.module.css";
type Summary={bookingId:string;status:string;packageName:string;scheduledStart:string;scheduledEnd:string;total:number;currency:string;provider:{id:string|null;name:string|null;model:string|null};pets:Array<{id:string;name:string;species:string;breed:string|null}>;payment:{status:string|null;mode:string|null;method:string|null;amount:number|null};tracking:{state:"not_started"|"not_sharing"|"live"|"stale"|"unavailable"|"ended";etaMinutes:number|null;distanceKm:number|null}};
const dt=(value:string)=>new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:currency||"INR"}).format(amount||0);
export default function CustomerGroomingLiveCard({bookingId}:{bookingId:string}){
 const[data,setData]=useState<Summary|null>(null),[error,setError]=useState(""),[mapTick,setMapTick]=useState(0),requestVersion=useRef(0);
 useEffect(()=>{if(!bookingId)return;let active=true,current:AbortController|null=null;const load=async()=>{const version=++requestVersion.current;current?.abort();const controller=new AbortController();current=controller;try{const response=await fetch(`/api/customer-grooming-summary?bookingId=${encodeURIComponent(bookingId)}`,{cache:"no-store",signal:controller.signal}),body=await response.json() as{data?:Summary;error?:string};if(!response.ok||!body.data)throw new Error(body.error||"Unable to load booking details");if(active&&version===requestVersion.current){setData(body.data);setMapTick(value=>value+1);setError("");}}catch(problem){if(controller.signal.aborted)return;if(active&&version===requestVersion.current)setError(problem instanceof Error?problem.message:"Unable to load booking details");}};void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;requestVersion.current+=1;current?.abort();clearInterval(timer);};},[bookingId]);
 if(error&&!data)return <p role="alert" className={styles.error}>{error}</p>;
 if(!data)return <p role="status" className={styles.loading}>Loading your confirmed booking…</p>;
 const tracking=data.tracking;
 const trackingCopy=tracking.state==="live"?`ETA about ${tracking.etaMinutes} min${tracking.distanceKm!=null?` · ${tracking.distanceKm.toFixed(1)} km away`:""}`:tracking.state==="stale"?"The latest route update is stale. We’ll refresh when the groomer shares a newer update.":tracking.state==="unavailable"?"The groomer is sharing progress, but a fresh ETA is not available yet.":tracking.state==="not_sharing"?"Waiting for the groomer’s first trusted route update.":tracking.state==="ended"?"Location sharing has ended for this booking.":"Location sharing starts when your groomer is on the way.";
 const providerLabel=data.provider.name||data.provider.id||null;
 return <article className={styles.card} aria-label="Live grooming booking details"><header><div><small>CONFIRMED BOOKING</small><h4>{data.packageName}</h4></div><strong>{data.status.replaceAll("_"," ")}</strong></header><dl><div><dt>Pet</dt><dd>{data.pets.map(p=>p.name).join(", ")||"Pet details unavailable"}</dd></div><div><dt>Groomer</dt><dd>{providerLabel||"Being reassigned — PawSpace Operations is confirming a replacement"}</dd></div><div><dt>Time</dt><dd>{dt(data.scheduledStart)} – {dt(data.scheduledEnd)} IST</dd></div><div><dt>Receipt</dt><dd>{money(data.total,data.currency)} · {data.payment.status||"payment recorded"}</dd></div></dl>
   <LiveTrackingPanel title={tracking.state==="live"?"Your groomer is on the way":"Booking tracking"} state={tracking.state} mapUrl={tracking.state==="live"?`/api/customer-grooming-summary?bookingId=${encodeURIComponent(bookingId)}&map=1&v=${mapTick}`:null} mapKey={mapTick} etaMinutes={tracking.etaMinutes} distanceKm={tracking.distanceKm} providerLabel={providerLabel} detail={tracking.state==="live"?`${trackingCopy}. The map refreshes automatically every few seconds. Provider position is privacy-rounded while your doorstep remains the destination.`:trackingCopy} live={tracking.state==="live"} onRecenter={()=>setMapTick(value=>value+1)} actions={[{label:"Chat support",href:"/chat",kind:"primary"},{label:"Booking help",href:"/contact",kind:"secondary"}]}/>
   {error&&<p role="status" className={styles.error}>Live tracking refresh issue: {error}</p>}
 </article>;
}
