"use client";
import{useState}from"react";

type Question={id:string;text:string;type?:string};
export type PendingFeedback={requestId:string;bookingId:string;serviceCode:string;packageName:string;scheduledStart:string;questions:Question[]};
type Result={average:number;feedbackReward:{code:string;kind:"coupon"|"addon";discount:number;addonCode:string|null;scope:string};publicReviewPrompt:{destination:string;googleReviewLink:string;appReviewLink:string}};

export default function ServiceFeedbackCard({item,customerId,onDone}:{item:PendingFeedback;customerId:string;onDone:(requestId:string,message:string)=>void}){
 const[answers,setAnswers]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null);
 const complete=item.questions.length===5&&item.questions.every(q=>answers[q.id]>=1&&answers[q.id]<=5);
 const submit=async()=>{setBusy(true);setError("");try{const response=await fetch("/api/service-review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerId,requestId:item.requestId,answers})});const body=await response.json() as{data?:Result;error?:string};if(!response.ok||!body.data)throw new Error(body.error||"Unable to submit feedback");setResult(body.data);const reward=body.data.feedbackReward.kind==="addon"?`free add-on ${body.data.feedbackReward.addonCode||"service"}`:`₹${body.data.feedbackReward.discount} master coupon`;onDone(item.requestId,`Thanks for your feedback · ${reward} added`);}catch(problem){setError(problem instanceof Error?problem.message:"Unable to submit feedback");}finally{setBusy(false)}};
 if(result){const destination=result.publicReviewPrompt.destination==="app"?"app":"google",href=destination==="app"?result.publicReviewPrompt.appReviewLink:result.publicReviewPrompt.googleReviewLink;return <article style={{padding:16,border:"1px solid var(--ps-border)",borderRadius:16,display:"grid",gap:10}}><span>FEEDBACK COMPLETE</span><h3 style={{margin:0}}>Thank you for helping PawSpace improve.</h3><p style={{margin:0}}>Your five-question average was {result.average.toFixed(1)}/5. {result.feedbackReward.kind==="addon"?<>Your free add-on <b>{result.feedbackReward.addonCode}</b> is reserved under reward <b>{result.feedbackReward.code}</b>.</>:<>Your ₹{result.feedbackReward.discount} master coupon is <b>{result.feedbackReward.code}</b>.</>}</p><a href={href} target="_blank" rel="noreferrer" style={{minHeight:44,display:"inline-flex",alignItems:"center",justifyContent:"center",border:"1px solid var(--ps-border)",borderRadius:12,textDecoration:"none"}}>Optionally review PawSpace on {destination==="app"?"the app store":"Google"} ↗</a><small>Public reviews are optional and never change your PawSpace reward.</small></article>}
 return <article style={{padding:16,border:"1px solid var(--ps-border)",borderRadius:16,display:"grid",gap:12}} aria-label={`Feedback for booking ${item.bookingId}`}><span>COMPLETED · 5-QUESTION FEEDBACK</span><h3 style={{margin:0}}>{item.packageName||item.serviceCode.replaceAll("_"," ")}</h3><small>Booking {item.bookingId} · Complete all five ratings to receive your PawSpace feedback reward.</small>{item.questions.map((question,index)=><section key={question.id} style={{display:"grid",gap:6}}><b style={{fontSize:12}}>{index+1}. {question.text}</b><div style={{display:"flex",gap:5}}>{[1,2,3,4,5].map(star=><button key={star} type="button" aria-label={`${question.text}: ${star} out of 5`} aria-pressed={answers[question.id]===star} disabled={busy} onClick={()=>setAnswers(previous=>({...previous,[question.id]:star}))} style={{minWidth:42,minHeight:42,borderRadius:10,border:"1px solid var(--ps-border)",background:answers[question.id]===star?"var(--ps-primary,#075744)":"transparent",color:answers[question.id]===star?"white":"inherit"}}>{star}★</button>)}</div></section>)}<button type="button" disabled={!complete||busy} onClick={()=>void submit()} style={{minHeight:46,border:0,borderRadius:12,fontWeight:800}}>{busy?"Saving feedback…":"Submit feedback & receive reward"}</button>{error&&<p role="alert" style={{color:"#b3261e",margin:0}}>{error}</p>}</article>;
}
