"use client";
import Link from "next/link";
import Image from "next/image";
import {useEffect,useMemo,useRef,useState} from "react";
import CustomerLogin from "../mobile-app/customer-login";
import {SERVICE_ART} from "../mobile-app/service-art";
import {createCanonicalFoodOrder,createFoodQuote,loadFoodCatalogue,type FoodCatalogueItem,type FoodOrderResult,type FoodQuote} from "../../lib/food-client";
import {loadV2CustomerAccount,loadV2CustomerSession} from "../../lib/v2/customer-experience-client";
import type {CustomerPet} from "../../lib/customer-account-client";
import type {CustomerAccountRecord} from "../../lib/customer-account";
import {createFoodSubscription} from "../../lib/food-subscription-client";
import styles from "./food-experience.module.css";
const box={background:"var(--paw-surface)",border:"1px solid var(--paw-line)",borderRadius:"var(--paw-card-radius)",padding:20} as const;
const renewalOptions=[7,14,30,60] as const;
type PurchaseMode="single"|"subscription";
type SubscriptionResult={subscriptionId:string;nextRenewalAt:number};
const selectionKey="pawspace:v2:food-selection:v1";
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export default function V2FoodExperience(){
 const href=(path:string)=>path==="/"?"/v2":`/v2${path}`;
 const [account,setAccount]=useState<CustomerAccountRecord|null>(null),[accountError,setAccountError]=useState(""),[accountLoading,setAccountLoading]=useState(true),[guest,setGuest]=useState(false),[login,setLogin]=useState(false),[attempt,setAttempt]=useState(0);
 const customer=account?{id:account.customerId,name:account.name,primaryPhone:account.primaryPhone,secondaryPhone:account.secondaryPhone??undefined,email:account.email??undefined}:null;
 const [selectionReady,setSelectionReady]=useState(false);
 const [items,setItems]=useState<FoodCatalogueItem[]>([]),[catalogueLoading,setCatalogueLoading]=useState(true),[catalogueError,setCatalogueError]=useState(""),[catalogueAttempt,setCatalogueAttempt]=useState(0);
 const [sku,setSku]=useState(""),[quantity,setQuantity]=useState(1),[selectedPetId,setSelectedPetId]=useState(""),[quote,setQuote]=useState<FoodQuote|null>(null),[quoteLoading,setQuoteLoading]=useState(false),[quoteError,setQuoteError]=useState(""),[quoteAttempt,setQuoteAttempt]=useState(0);
 const [order,setOrder]=useState<FoodOrderResult|null>(null),[orderLoading,setOrderLoading]=useState(false),[orderError,setOrderError]=useState(""),[purchaseMode,setPurchaseMode]=useState<PurchaseMode>("single"),[renewalIntervalDays,setRenewalIntervalDays]=useState<number>(30),[subscription,setSubscription]=useState<SubscriptionResult|null>(null),[subscriptionError,setSubscriptionError]=useState("");
 const orderInFlightRef=useRef(false);
 const [review,setReview]=useState(false),[exitReview,setExitReview]=useState(false);
 const reviewDialog=useRef<HTMLDialogElement>(null),reviewOpener=useRef<HTMLButtonElement>(null);
 const selectedPet=account?.pets.find(pet=>pet.id===selectedPetId);
 useEffect(()=>{const dialog=reviewDialog.current;if(review&&dialog&&!dialog.open)dialog.showModal();if(!review&&dialog?.open){dialog.close();reviewOpener.current?.focus();}},[review]);
 function openReview(){setExitReview(false);setReview(true);}
 function closeReview(){setReview(false);setExitReview(false);}
 const active=useMemo(()=>items.find(item=>item.sku===sku),[items,sku]);
 const pets=useMemo(()=>(account?.pets||[]) as CustomerPet[],[account]);
 const compatiblePets=useMemo(()=>active?pets.filter(pet=>pet.species===active.pet_type):[],[active,pets]);
 const limit=active?Math.max(0,Math.min(active.max_qty_per_order,active.uat_available_units)):0;
 const quoteCurrent=Boolean(quote&&customer&&active&&!accountLoading&&!accountError&&!catalogueLoading&&!catalogueError&&quantity>0&&quantity<=limit&&quote.version===active.version&&quote.sku===sku&&quote.quantity===quantity&&quote.petIds.includes(selectedPetId));
 useEffect(()=>{let cancelled=false;loadFoodCatalogue().then(catalogue=>{if(cancelled)return;setItems(catalogue.items);let saved:Record<string,unknown>|null=null;try{const raw=JSON.parse(window.sessionStorage.getItem(selectionKey)||"null");if(raw&&typeof raw==="object"&&!Array.isArray(raw))saved=raw;}catch{/* Browsing works when storage is unavailable. */}const item=catalogue.items.find(i=>i.sku===saved?.sku)||catalogue.items[0];setSku(item?.sku||"");const savedQuantity=Number(saved?.quantity);setQuantity(Number.isInteger(savedQuantity)&&savedQuantity>0?Math.max(1,Math.min(savedQuantity,item?.max_qty_per_order||1,item?.uat_available_units||1)):1);setPurchaseMode(saved?.purchaseMode==="subscription"?"subscription":"single");const interval=Number(saved?.renewalIntervalDays);setRenewalIntervalDays(renewalOptions.some(days=>days===interval)?interval:30);setSelectionReady(true);}).catch(problem=>{if(!cancelled)setCatalogueError(problem instanceof Error?problem.message:"Unable to load food catalogue");}).finally(()=>{if(!cancelled)setCatalogueLoading(false);});return()=>{cancelled=true;};},[catalogueAttempt]);
 useEffect(()=>{if(!selectionReady||!active)return;try{if(order)window.sessionStorage.removeItem(selectionKey);else window.sessionStorage.setItem(selectionKey,JSON.stringify({sku,quantity,purchaseMode,renewalIntervalDays}));}catch{/* Keep the current visit usable without browser storage. */}},[selectionReady,active,sku,quantity,purchaseMode,renewalIntervalDays,order]);
 useEffect(()=>{let cancelled=false;loadV2CustomerSession().then(session=>session?loadV2CustomerAccount():null).then(record=>{if(!cancelled){setAccount(record);setGuest(!record);setAccountError("");}}).catch(problem=>{if(!cancelled){setAccount(null);setGuest(false);setAccountError(problem instanceof Error?problem.message:"Unable to load your account");}}).finally(()=>{if(!cancelled)setAccountLoading(false);});return()=>{cancelled=true;};},[attempt]);
 useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(cancelled)return;setQuote(null);setQuoteError("");setOrderError("");if(!account||!active||!selectedPetId||!compatiblePets.some(p=>p.id===selectedPetId)||quantity>limit){setQuoteLoading(false);return;}setQuoteLoading(true);void createFoodQuote({sku,quantity,paymentMode:"sandbox_deferred",customerId:account.customerId,petIds:[selectedPetId]}).then(next=>{if(!cancelled)setQuote(next);}).catch(problem=>{if(!cancelled)setQuoteError(problem instanceof Error?problem.message:"Unable to refresh food quote");}).finally(()=>{if(!cancelled)setQuoteLoading(false);});});return()=>{cancelled=true;};},[account,active,compatiblePets,sku,quantity,selectedPetId,limit,quoteAttempt]);
 useEffect(()=>{if(!quote||order)return;const timer=setTimeout(()=>setQuote(null),Math.max(0,quote.expiresAt-Date.now()));return()=>clearTimeout(timer);},[quote,order]);
 function choose(item:FoodCatalogueItem){setQuote(null);setSku(item.sku);setQuantity(1);setSelectedPetId("");setLogin(false);}
 async function orderNow(){if(!quote||!quoteCurrent||quoteLoading||orderInFlightRef.current)return;if(quote.expiresAt<=Date.now()){setQuote(null);setQuoteError("Food quote expired. Refresh before reserving.");return;};if(!customer){setOrderError("Sign in as a customer to order Fresh Food");return;}orderInFlightRef.current=true;setOrderLoading(true);setOrderError("");setSubscriptionError("");setSubscription(null);try{const result=await createCanonicalFoodOrder({idempotencyKey:`food:${quote.quoteId}:${customer.id}`,quoteId:quote.quoteId,customer});setOrder(result);setReview(false);if(purchaseMode==="subscription"){try{const next=await createFoodSubscription({sourceOrderId:result.orderId,renewalIntervalDays,communicationChannel:"whatsapp"});setSubscription({subscriptionId:String(next.subscriptionId||""),nextRenewalAt:Number(next.nextRenewalAt||0)})}catch(error){setSubscriptionError(error instanceof Error?error.message:"Canonical order was reserved, but subscription setup needs attention")}}window.scrollTo(0,0)}catch(error){setOrderError(error instanceof Error?error.message:"Unable to create canonical Food order")}finally{orderInFlightRef.current=false;setOrderLoading(false)}}
 function reset(){setOrder(null);setSubscription(null);setSubscriptionError("")}
 if(order)return <main style={{maxWidth:900,margin:"0 auto",padding:28,fontFamily:"var(--paw-font, system-ui)",display:"grid",gap:16}}><Link href={href("/")}>PawSpace</Link><section style={box}><p>CANONICAL FOOD · INTERNAL UAT</p><h1>UAT inventory reserved</h1><h2>{order.orderId}</h2><p>{quote?.name} · {quote?.quantity} × ₹{quote?.unitPrice.toLocaleString("en-IN")}</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}><article style={box}><small>Order status</small><strong style={{display:"block"}}>{order.status}</strong><span>{order.deliveryStatus}</span></article><article style={box}><small>UAT value</small><strong style={{display:"block"}}>₹{Number(order.totalAmount??0).toLocaleString("en-IN")}</strong><span>₹0 due now · live money disabled</span></article><article style={box}><small>Inventory</small><strong style={{display:"block"}}>{order.inventoryMode}</strong><span>Production inventory verified: {String(order.productionInventoryVerified)}</span></article></div>{purchaseMode==="subscription"&&<section style={{...box,marginTop:14}}><h3>Repeat subscription</h3>{subscription?<><p><strong>{subscription.subscriptionId}</strong></p><p>Renewal interval: every {renewalIntervalDays} days. At each due renewal PawSpace queues a payment link; it does not silently auto-charge. After canonical payment confirmation, the paid message and invoice are queued automatically.</p><p>Next renewal: {new Date(subscription.nextRenewalAt).toLocaleString("en-IN")}</p><Link href={href(`/food/subscriptions?subscriptionId=${encodeURIComponent(subscription.subscriptionId)}`)}>Manage subscription</Link></>:<><p>The order is safe. Subscription setup needs completion before any renewal link can be generated.</p>{subscriptionError&&<p role="alert">{subscriptionError}</p>}<Link href={href(`/food/subscriptions?sourceOrderId=${encodeURIComponent(order.orderId)}`)}>Finish subscription setup</Link></>}</section>}<p>This is a canonical internal-UAT order reservation, not a production sale. Delivery fee policy, production inventory/SKU master, fulfilment logistics and live payment remain disconnected or configuration-pending.</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Link href={href(`/food/manage?orderId=${encodeURIComponent(order.orderId)}`)}>Manage order</Link><button onClick={reset}>Back to UAT catalogue</button></div></section></main>;

 return <main className={styles.page}><div className={styles.shell}>
 <header className={styles.hero}><div><p className={styles.eyebrow}>FOOD · PAWSPACE FAMILY</p><h1>Good food.<br/>Happy little routines.</h1><p>Choose food for your companion, make it yours, and review every detail before reserving.</p><span className={styles.badge}>UAT catalogue · no live charges</span></div><div className={styles.art}><Image src={SERVICE_ART.food.image} alt={SERVICE_ART.food.alt} width={600} height={440} priority/><span>Illustrative PawSpace artwork</span><Image className={styles.familyPhoto} src="/assets/breeds/german-shepherd-hero.jpg" alt="PawSpace team member with a German Shepherd; illustrative family image" width={220} height={160}/></div></header>
 <aside className={styles.notice}>These are server-owned test products and UAT stock. Production inventory, delivery fees and live payment are not configured. Nothing is reserved while browsing. Your food choices stay saved in this browser session until an order is reserved.</aside>
 <section aria-labelledby="food-items"><p className={styles.eyebrow}>01 · CHOOSE YOUR FOOD</p><h2 id="food-items">For their next bowl</h2>
 {catalogueLoading&&<p role="status">Loading food and UAT stock…</p>}{catalogueError&&<p role="alert">{catalogueError} <button onClick={()=>{setCatalogueLoading(true);setCatalogueError("");setCatalogueAttempt(n=>n+1);}}>Retry catalogue</button></p>}
 {!catalogueLoading&&!catalogueError&&!items.length&&<p>No food items are available. Please check again later.</p>}
 <div className={styles.cards}>{items.map(item=><button className={styles.card} aria-pressed={sku===item.sku} key={item.sku} disabled={orderLoading} onClick={()=>choose(item)}><span className={styles.cardTop}>{item.pet_type==="cat"?"FOR CATS":"FOR DOGS"}<span>{sku===item.sku?"Selected ✓":"Choose →"}</span></span><h3>{item.name}</h3><p>{item.pack_size} per pack</p><strong>{money(item.unit_price)}</strong><p>{item.uat_available_units>0?`${item.uat_available_units} UAT packs available`:"Out of UAT stock"}</p><small>Recipe inclusions are not published in this catalogue.</small></button>)}</div></section>
 {active&&<div className={styles.configuration}><section className={styles.panel}><p className={styles.eyebrow}>02 · MAKE IT YOURS</p><h2>Size & quantity</h2><p className={styles.size}>{active.pack_size} <small>Catalogue pack size</small></p><p>Only this size is published for the selected item. Meal size and multipack plans are not available.</p><label>Number of packs<select aria-label="Number of packs" value={quantity} disabled={!limit||orderLoading} onChange={e=>{setQuote(null);setQuantity(Number(e.target.value));}}>{Array.from({length:limit},(_,i)=><option key={i+1} value={i+1}>{i+1} {i?"packs":"pack"}</option>)}</select></label>{!limit&&<p role="status">This item is out of UAT stock.</p>}
 <h3>Order type</h3><div className={styles.choices}><button disabled={orderLoading} aria-pressed={purchaseMode==="single"} onClick={()=>setPurchaseMode("single")}>One-time order</button><button disabled={orderLoading} aria-pressed={purchaseMode==="subscription"} onClick={()=>setPurchaseMode("subscription")}>Repeat subscription</button></div>
 {purchaseMode==="subscription"&&<><label>Renewal interval<select aria-label="Renewal interval" disabled={orderLoading} value={renewalIntervalDays} onChange={e=>setRenewalIntervalDays(Number(e.target.value))}>{renewalOptions.map(days=><option key={days} value={days}>Every {days} days</option>)}</select></label><p>Uses the existing UAT renewal plan. A payment link is queued when renewal is due; there is no silent auto-charge, discount or guaranteed delivery schedule.</p></>}
 </section><section className={styles.panel}><p className={styles.eyebrow}>03 · YOUR COMPANION</p><h2>Who is this for?</h2>{accountLoading?<p role="status">Loading your pet family…</p>:guest?<p>Keep browsing as a guest. Verify your mobile at Continue to load your saved pets and check eligibility.</p>:accountError?<p role="alert">{accountError} <button onClick={()=>{setAccountLoading(true);setAttempt(n=>n+1);}}>Retry account</button></p>:compatiblePets.length?<label>Pet<select aria-label="Pet" disabled={orderLoading} value={selectedPetId} onChange={e=>{setQuote(null);setSelectedPetId(e.target.value);}}><option value="">Choose your pet</option>{compatiblePets.map(pet=><option key={pet.id} value={pet.id}>{pet.name} · {pet.species}</option>)}</select></label>:<p>Add a {active.pet_type} profile before quoting this food. <Link href="/v2/account">Manage pet family →</Link></p>}
 <div className={styles.guide}><h3>Feeding guide</h3><p>A product-specific feeding guide has not been published. Check the product label and your vet’s guidance before choosing portions.</p></div><h3>Delivery & payment</h3><p>Bengaluru East UAT preview. Delivery fee is ₹0 in UAT; the production policy is pending. Coupons are disabled. No live money is collected.</p></section></div>}
 {login&&guest&&<section className={styles.panel} aria-label="Verify mobile before food reservation"><h2>Bring your pet family in</h2><p>Your food, quantity and order type stay selected. Verification loads your saved pets; it does not reserve food.</p><CustomerLogin embedded onLoggedIn={()=>{setLogin(false);setAccountLoading(true);setAttempt(n=>n+1);}}/><button onClick={()=>setLogin(false)}>Keep browsing</button></section>}
 <section className={styles.footer} aria-label="Food price review" aria-busy={quoteLoading}><div><small>{quoteCurrent?"SERVER QUOTE":"CATALOGUE PREVIEW"}</small><strong>{quoteCurrent&&quote?money(quote.totalAmount):active?money(active.unit_price*quantity):"—"}</strong><span>{active?`${quantity} × ${active.pack_size} · ${money(active.unit_price)} per pack`:"Choose a food item"}</span><span>{quoteCurrent&&quote?`Items ${money(quote.unitPrice*quote.quantity)} + UAT delivery ${money(quote.deliveryFee)} · due now ${money(quote.amountDueNow)}`:"Final total requires your eligible pet and a fresh server quote."}</span>{purchaseMode==="subscription"&&<span>Payment-link renewal every {renewalIntervalDays} days</span>}<span role="status">{quoteLoading?"Refreshing server quote…":quoteCurrent?"Ready for UAT reservation":guest?"Verify mobile to continue":selectedPetId?"Refresh your quote to continue":"Select an eligible pet to continue"}</span></div><div className={styles.footerActions}>{guest?<button data-v2-action="primary" disabled={!active||!limit||catalogueLoading||Boolean(catalogueError)||accountLoading} onClick={()=>setLogin(true)}>Continue · verify mobile →</button>:<><button disabled={!account||!selectedPetId||!limit||quoteLoading||orderLoading} onClick={()=>setQuoteAttempt(n=>n+1)}>Refresh quote</button><button ref={reviewOpener} data-v2-action="primary" disabled={!quoteCurrent||quoteLoading||Boolean(quoteError)||orderLoading||!customer||!limit} onClick={openReview}>{orderLoading?"Reserving UAT stock…":"Review food selection →"}</button></>}</div></section>

 <dialog ref={reviewDialog} className={styles.reviewDialog} aria-labelledby="food-review-title" onCancel={event=>{event.preventDefault();if(!orderLoading)setExitReview(true);}}>
 <div className={styles.reviewHeader}><h2 id="food-review-title">Review your food selection</h2><button disabled={orderLoading} onClick={()=>setExitReview(true)} aria-label="Close food review">×</button></div>
 {exitReview?<section aria-label="Leave food review"><h3>Leave this review?</h3><p>Your food choices stay saved for this browser session. Nothing is reserved until you confirm.</p><div className={styles.choices}><button onClick={()=>setExitReview(false)}>Keep reviewing</button><button onClick={closeReview}>Leave review · keep choices</button></div></section>:<section>
 <p className={styles.badge}>UAT reservation · no live payment</p><h3>{active?.name}</h3><p>{quantity} × {active?.pack_size} · {selectedPet?.name||"Choose an eligible pet"}</p><p>{purchaseMode==="subscription"?`Repeat subscription · payment-link renewal every ${renewalIntervalDays} days`:"One-time order"}</p>
 <section className={styles.profileSummary} aria-label="Known customer profile"><strong>{account?.name}</strong><p>{[account?.primaryPhone,account?.email].filter(Boolean).join(" · ")}</p><small>Using your saved PawSpace profile. No new contact details or photos are required.</small><details><summary>Saved addresses · profile reference</summary><p>Food delivery is not configured. This UAT reservation does not select or reserve delivery to an address.</p>{account?.addresses?.length?<div className={styles.addresses}>{account.addresses.map(address=><article key={address.id}><strong>{address.label}{address.isDefault?" · Profile default":""}</strong><p>{[address.line1,address.line2,address.area,address.city,address.postalCode].filter(Boolean).join(", ")}</p></article>)}</div>:<p>No saved addresses yet.</p>}<Link href="/v2/account">Manage saved profile</Link></details></section>
 <dl className={styles.reviewTotals}><div><dt>Items</dt><dd>{quoteCurrent&&quote?money(quote.unitPrice*quote.quantity):"Fresh quote required"}</dd></div><div><dt>UAT delivery</dt><dd>{quoteCurrent&&quote?money(quote.deliveryFee):"—"}</dd></div><div><dt>UAT total</dt><dd>{quoteCurrent&&quote?money(quote.totalAmount):"—"}</dd></div><div><dt>Due now</dt><dd>{quoteCurrent&&quote?money(quote.amountDueNow):"—"}</dd></div></dl>
 <p>Production stock, delivery and live payments remain unconfigured. Confirming reserves UAT stock{purchaseMode==="subscription"?" and creates the existing UAT renewal plan":""}.</p>
 {!quoteCurrent&&<p role="status">The quote is no longer current. Leave review and refresh before reserving.</p>}{orderError&&<p role="alert">{orderError}</p>}
 <div className={`${styles.choices} ${styles.reviewActions}`}><button disabled={orderLoading} onClick={()=>setExitReview(true)}>Back to browsing</button><button className={styles.confirm} disabled={!quoteCurrent||quoteLoading||Boolean(quoteError)||orderLoading||!customer||!limit} onClick={()=>void orderNow()}>{orderLoading?"Reserving UAT stock…":purchaseMode==="subscription"?"Confirm UAT order + subscription":"Confirm UAT food reservation"}</button></div>
 </section>}
 </dialog>
 {quoteError&&<p role="alert" className={styles.notice}>{quoteError} Refresh the quote to retry.</p>}{orderError&&<p role="alert" className={styles.notice}>{orderError}</p>}
 </div></main>;
}
