import{authError,authorize,database,securityAudit}from"../../../lib/server-auth";
import{addSettlementAdjustment,approveSandboxPayoutInstruction,approveSettlement,approveSettlementPolicy,createSandboxPayoutInstruction,ensurePartnerSettlementTables,refreshPartnerSettlementStatements}from"../../../lib/partner-settlement-governance";
import{approveOrderCommission,approveOrderCommissionOverride,confirmOrderCommission,getProviderCommissionDashboard,requestOrderCommissionOverride,saveProviderCompensationProfile,saveProviderPayoutAccount,type CommissionMode,type EngagementModel}from"../../../lib/provider-commission-governance";
import{activateProviderCommercialTerms,commercialTermsOverview,draftProviderCommercialTerms}from"../../../lib/provider-commission-setup";
import{rejectOrderCommercialOverride,setOrderCommercialOverride}from"../../../lib/provider-commercial-terms";
import{pawspaceCommissionProblem,providerShareFromCommission}from"../../../lib/commission-range";
import{arbitrateEscrow,escrowCustodySnapshot,freezeEscrowForDispute,releaseUndisputedEscrowToProvider,requireEscrowProviderReleaseForPayout,reserveEscrowForProviderPayout,type ArbitrationDecision}from"../../../lib/escrow-custody-engine";
import{preauthorizeVerifiedPayoutBeneficiary}from"../../../lib/payout-beneficiary-verification";
import{getProviderPayoutQueueDashboard,releaseProviderPayouts,runProviderPayoutQueueSweep}from"../../../lib/provider-payout-queue";
import{setProviderPayoutHoldDays}from"../../../lib/provider-payout-hold";
type Body={action?:string;termIds?:string[];engagement?:string;services?:Array<{serviceCode:string;pawspaceCommissionPercent?:number|string|null}>;effectiveFrom?:string;approvalReference?:string;pawspaceCommissionPercent?:number;requestId?:string;note?:string;bookingIds?:string[];holdDays?:number;statementId?:string;instructionId?:string;type?:"incentive"|"deduction"|"reversal"|"manual_correction";amount?:number;reason?:string;idempotencyKey?:string;providerId?:string;engagementModel?:EngagementModel;commissionMode?:CommissionMode;commissionValue?:number;razorpayxContactId?:string;razorpayxFundAccountId?:string;bookingId?:string;disputeReference?:string;decision?:ArbitrationDecision;providerAmount?:number;customerAmount?:number;evidence?:Record<string,unknown>};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});function sameOrigin(r:Request){const o=r.headers.get("origin");if(o&&o!==new URL(r.url).origin)throw new Response("Cross-origin partner finance write blocked",{status:403});}
export async function GET(request:Request){try{await authorize(request,"finance.view");const db=await database();await ensurePartnerSettlementTables(db);const period=new URL(request.url).searchParams.get("period")||new Date().toISOString().slice(0,7);await refreshPartnerSettlementStatements(db,period);const [statements,payouts,commission,escrow,payoutQueue,commercialTerms]=await Promise.all([db.prepare("SELECT * FROM partner_settlement_statements WHERE period_code=? ORDER BY provider_id").bind(period).all(),db.prepare("SELECT * FROM partner_payout_instructions ORDER BY updated_at DESC LIMIT 100").all(),getProviderCommissionDashboard(db),escrowCustodySnapshot(db),getProviderPayoutQueueDashboard(db),commercialTermsOverview(db)]);return json({data:{period,statements:statements.results,payouts:payouts.results,commission,escrow,payoutQueue,commercialTerms,source:"canonical_partner_settlement",livePayouts:false,paymentEnvironment:"sandbox"}});}catch(error){return authError(error,"Unable to load partner finance");}}
export async function POST(request:Request){try{sameOrigin(request);const actor=await authorize(request,"finance.manage"),body=await request.json() as Body,db=await database();await ensurePartnerSettlementTables(db);
 // Commission is set in provider_commercial_terms (owner decision 8): the maker saves a proposal for each service, a
 // second person activates it with an approval reference. The older profile keeps only the engagement and bank account.
 if(body.action==="save_provider_commercial_terms"){if(!body.providerId||!body.engagement||!body.reason)return json({error:"Provider, engagement and reason are required"},400);const data=await draftProviderCommercialTerms(db,{providerId:body.providerId,engagement:body.engagement,services:Array.isArray(body.services)?body.services:[],effectiveFrom:body.effectiveFrom,reason:body.reason,actorId:actor.email});await securityAudit(db,actor,"partner.commercial_terms.propose","provider",data.providerId,"completed",{engagement:data.engagement,services:data.drafts.map(d=>({serviceCode:d.serviceCode,termId:d.termId,pawspaceCommissionPercent:d.pawspaceCommissionPercent})),effectiveFrom:data.effectiveFrom,liveMoney:false});return json({data},201);}
 if(body.action==="activate_provider_commercial_terms"){if(!body.providerId||!body.approvalReference)return json({error:"Provider and approval reference are required"},400);const data=await activateProviderCommercialTerms(db,{providerId:body.providerId,approvalReference:body.approvalReference,actorId:actor.email,termIds:Array.isArray(body.termIds)?body.termIds:null});await securityAudit(db,actor,"partner.commercial_terms.activate","provider",data.providerId,"completed",{engagement:data.engagement,termIds:data.activated.map(t=>t.termId),approvalReference:body.approvalReference,liveMoney:false});return json({data});}
 if(body.action==="save_provider_bank_account"){if(!body.providerId||!body.reason)return json({error:"Provider and reason are required"},400);const data=await saveProviderPayoutAccount(db,{providerId:body.providerId,razorpayxContactId:body.razorpayxContactId,razorpayxFundAccountId:body.razorpayxFundAccountId,reason:body.reason,actor:actor.email});await securityAudit(db,actor,"partner.payout_account.save","provider",body.providerId,"completed",{environment:"sandbox",liveMoney:false});return json({data});}
 // Any booking not yet completed: ask for a different PawSpace commission (10-40%) with a reason; a second person approves it.
 if(body.action==="request_order_override"){if(!body.bookingId||body.pawspaceCommissionPercent==null||!body.reason)return json({error:"Booking, PawSpace's commission % and a reason are required"},400);const percent=Number(body.pawspaceCommissionPercent),problem=pawspaceCommissionProblem(percent,`booking ${body.bookingId}`);if(problem)return json({error:problem},400);const data=await setOrderCommercialOverride(db,{bookingId:body.bookingId,providerSharePct:providerShareFromCommission(percent),reason:body.reason,actorId:actor.email});await securityAudit(db,actor,"partner.commission.override.request","booking",body.bookingId,"completed",{requestId:data.requestId,pawspaceCommissionPercent:percent,awaitingSecondApprover:true});return json({data},201);}
 if(body.action==="approve_order_override"){if(!body.bookingId&&!body.requestId)return json({error:"Booking or override request is required"},400);const data=await approveOrderCommissionOverride(db,{bookingId:String(body.bookingId||""),requestId:body.requestId,actor:actor.email,note:body.note});await securityAudit(db,actor,"partner.commission.override.approve","booking",data.bookingId,"completed",{requestId:data.requestId,requestedBy:data.requestedBy,pawspaceCommissionPercent:data.pawspaceCommissionPercent});return json({data});}
 if(body.action==="reject_order_override"){if(!body.bookingId&&!body.requestId)return json({error:"Booking or override request is required"},400);const data=await rejectOrderCommercialOverride(db,{bookingId:body.bookingId,requestId:body.requestId,actorId:actor.email,note:body.note});await securityAudit(db,actor,"partner.commission.override.reject","booking",data.bookingId,"completed",{requestId:data.requestId});return json({data});}
 if(body.action==="save_provider_profile"){if(!body.providerId||!body.engagementModel||!body.reason)return json({error:"Provider, engagement model and reason are required"},400);const data=await saveProviderCompensationProfile(db,{providerId:body.providerId,engagementModel:body.engagementModel,commissionMode:body.commissionMode,commissionValue:body.commissionValue,razorpayxContactId:body.razorpayxContactId,razorpayxFundAccountId:body.razorpayxFundAccountId,reason:body.reason,actor:actor.email});await securityAudit(db,actor,"partner.compensation.profile","provider",body.providerId,"completed",{engagementModel:body.engagementModel,commissionMode:body.commissionMode,commissionValue:body.commissionValue,liveMoney:false});return json({data});}
 if(body.action==="override_order_commission"){if(!body.bookingId||body.pawspaceCommissionPercent==null||!Number.isFinite(Number(body.pawspaceCommissionPercent))||!body.reason)return json({error:"Booking, PawSpace's commission % and a reason are required"},400);const data=await requestOrderCommissionOverride(db,{bookingId:body.bookingId,pawspaceCommissionPercent:Number(body.pawspaceCommissionPercent),reason:body.reason,actor:actor.email});await securityAudit(db,actor,"partner.commission.override","booking",body.bookingId,"completed",{requestId:data.requestId,pawspaceCommissionPercent:data.pawspaceCommissionPercent,awaitingSecondApprover:true});return json({data},201);}
 if(body.action==="confirm_order_commission"){if(!body.bookingId)return json({error:"Booking ID is required"},400);const data=await confirmOrderCommission(db,{bookingId:body.bookingId,actor:actor.email});await securityAudit(db,actor,"partner.commission.confirm","booking",body.bookingId,"completed",{dueAt:data.dueAt,escrowRequiredBeforeApproval:true});return json({data});}
 if(body.action==="approve_order_commission_level_1"){if(!body.bookingId)return json({error:"Booking ID is required"},400);const order=await db.prepare("SELECT provider_id,commission_amount FROM provider_order_commissions WHERE booking_id=? AND status='awaiting_approval_1'").bind(body.bookingId).first<Record<string,unknown>>();if(!order)return json({error:"Commission is not awaiting level 1 approval"},409);const escrow=await reserveEscrowForProviderPayout(db,{bookingId:body.bookingId,providerId:String(order.provider_id),amount:Number(order.commission_amount),currency:"INR",actorId:actor.email,reason:"Reserve captured customer funds before provider commission approval"});const data=await approveOrderCommission(db,{bookingId:body.bookingId,level:1,actor:actor.email});await securityAudit(db,actor,"partner.commission.approve.level1","booking",body.bookingId,"completed",{escrowAccountId:escrow.accountId,escrowState:escrow.state,environment:"sandbox",liveMoney:false});return json({data:{...data,escrow}});}
 if(body.action==="escrow_freeze_dispute"){if(!body.bookingId||!body.disputeReference||!body.reason)return json({error:"Booking, dispute reference and reason are required"},400);const data=await freezeEscrowForDispute(db,{bookingId:body.bookingId,disputeReference:body.disputeReference,reason:body.reason,evidence:body.evidence,actorId:actor.email});await securityAudit(db,actor,"partner.escrow.freeze","booking",body.bookingId,"completed",{disputeReference:body.disputeReference,state:data.state,liveMoney:false});return json({data});}
 if(body.action==="escrow_release_undisputed"){if(!body.bookingId||!body.reason)return json({error:"Booking and release reason are required"},400);const data=await releaseUndisputedEscrowToProvider(db,{bookingId:body.bookingId,reason:body.reason,actorId:actor.email});await securityAudit(db,actor,"partner.escrow.release","booking",body.bookingId,"completed",{state:data.state,providerAmount:data.providerAmount,liveMoney:false});return json({data});}
 if(body.action==="escrow_arbitrate"){if(!body.bookingId||!body.decision||!body.reason)return json({error:"Booking, arbitration decision and reason are required"},400);const data=await arbitrateEscrow(db,{bookingId:body.bookingId,decision:body.decision,providerAmount:body.providerAmount,customerAmount:body.customerAmount,reason:body.reason,evidence:body.evidence,actorId:actor.email});await securityAudit(db,actor,"partner.escrow.arbitrate","booking",body.bookingId,"completed",{decision:body.decision,providerAmount:data.providerAmount,customerAmount:data.customerAmount,liveMoney:false});return json({data});}
 if(body.action==="approve_order_commission_level_2"){if(!body.bookingId)return json({error:"Booking ID is required"},400);const order=await db.prepare("SELECT provider_id,commission_amount FROM provider_order_commissions WHERE booking_id=? AND status='awaiting_approval_2'").bind(body.bookingId).first<Record<string,unknown>>();if(!order)return json({error:"Commission is not awaiting level 2 approval"},409);const escrow=await requireEscrowProviderReleaseForPayout(db,{bookingId:body.bookingId,maximumAmount:Number(order.commission_amount)});const beneficiary=await preauthorizeVerifiedPayoutBeneficiary(db,{providerId:String(order.provider_id),scopeType:"booking",scopeId:body.bookingId});const data=await approveOrderCommission(db,{bookingId:body.bookingId,level:2,actor:actor.email,idempotencyKey:body.idempotencyKey});await securityAudit(db,actor,"partner.commission.approve.level2","booking",body.bookingId,"completed",{payoutId:data.payoutId,escrowAccountId:escrow.accountId,escrowState:escrow.state,beneficiarySnapshotSha256:beneficiary.snapshotSha256,rail:"razorpayx",environment:"sandbox",liveMoney:false});return json({data:{...data,escrow,beneficiarySnapshotSha256:beneficiary.snapshotSha256}});}
 if(body.action==="adjust"){if(!body.statementId||!body.type||!Number.isFinite(body.amount)||!body.reason)return json({error:"Complete adjustment details are required"},400);const data=await addSettlementAdjustment(db,{statementId:body.statementId,type:body.type,amount:Number(body.amount),reason:body.reason,actor:actor.email});await securityAudit(db,actor,"partner.settlement.adjust","partner_settlement",body.statementId,"completed",{adjustmentId:data.id,type:body.type,amount:body.amount});return json({data},201);}
 if(body.action==="approve_policy"){if(!body.statementId||!body.reason)return json({error:"Statement ID and reason are required"},400);const data=await approveSettlementPolicy(db,{statementId:body.statementId,reason:body.reason,actor:actor.email});await securityAudit(db,actor,"partner.settlement.policy_approve","partner_settlement",body.statementId,"completed",{reason:body.reason});return json({data},data.duplicatePrevented?200:201);}
 if(body.action==="approve"){if(!body.statementId)return json({error:"Statement ID is required"},400);const data=await approveSettlement(db,{statementId:body.statementId,actor:actor.email});await securityAudit(db,actor,"partner.settlement.approve","partner_settlement",body.statementId,"completed",{});return json({data});}
 if(body.action==="sandbox_payout"){if(!body.statementId||!body.idempotencyKey)return json({error:"Statement and idempotency key are required"},400);const data=await createSandboxPayoutInstruction(db,{statementId:body.statementId,idempotencyKey:body.idempotencyKey,actor:actor.email});await securityAudit(db,actor,"partner.payout.prepare","partner_settlement",body.statementId,"completed",{environment:"sandbox",liveMoney:false});return json({data},data.duplicatePrevented?200:201);}
 if(body.action==="approve_sandbox_payout_level_1"){if(!body.instructionId)return json({error:"Payout instruction ID is required"},400);const data=await approveSandboxPayoutInstruction(db,{instructionId:body.instructionId,level:1,actor:actor.email});await securityAudit(db,actor,"partner.payout.approve.level1","payout_instruction",body.instructionId,"completed",{environment:"sandbox",liveMoney:false});return json({data});}
 if(body.action==="approve_sandbox_payout_level_2"){if(!body.instructionId)return json({error:"Payout instruction ID is required"},400);const instruction=await db.prepare("SELECT provider_id FROM partner_payout_instructions WHERE id=? AND status='awaiting_approval_2'").bind(body.instructionId).first<Record<string,unknown>>();if(!instruction)return json({error:"Payout is not awaiting level 2 approval"},409);const beneficiary=await preauthorizeVerifiedPayoutBeneficiary(db,{providerId:String(instruction.provider_id),scopeType:"instruction",scopeId:body.instructionId});const data=await approveSandboxPayoutInstruction(db,{instructionId:body.instructionId,level:2,actor:actor.email});await securityAudit(db,actor,"partner.payout.approve.level2","payout_instruction",body.instructionId,"completed",{beneficiarySnapshotSha256:beneficiary.snapshotSha256,environment:"sandbox",liveMoney:false});return json({data:{...data,beneficiarySnapshotSha256:beneficiary.snapshotSha256}});}
 // ONE Finance click: a queued provider payout (7 days after completion, queued by the scheduled job) is
 // released here, one booking or a selected batch, reason optional. Sandbox only; live money stays behind
 // the live-payout approvals.
 if(body.action==="release_provider_payout"){const bookingIds=Array.isArray(body.bookingIds)?body.bookingIds.map(String):body.bookingId?[body.bookingId]:[];if(!bookingIds.length)return json({error:"Choose at least one payout to release"},400);let data:Awaited<ReturnType<typeof releaseProviderPayouts>>;try{data=await releaseProviderPayouts(db,{bookingIds,actor:actor.email,reason:body.reason});}catch(error){await securityAudit(db,actor,"partner.payout.release","provider_payout_queue",null,"rejected",{bookingIds:bookingIds.slice(0,100),error:error instanceof Response?await error.clone().text():error instanceof Error?error.message:String(error),reason:body.reason||null,environment:"sandbox",liveMoney:false});throw error;}for(const item of data.released)await securityAudit(db,actor,"partner.payout.release","booking",String(item.bookingId),"completed",{payoutId:item.payoutId,amount:item.amount,duplicatePrevented:item.duplicatePrevented,followUp:item.followUp??null,reason:body.reason||null,environment:"sandbox",liveMoney:false});for(const item of data.refused)await securityAudit(db,actor,"partner.payout.release","booking",item.bookingId,"rejected",{error:item.error,reason:body.reason||null,environment:"sandbox",liveMoney:false});if(!data.released.length)return json({error:data.refused.map(item=>`${item.bookingId}: ${item.error}`).join("; "),data},409);return json({data});}
 if(body.action==="run_payout_queue"){const data=await runProviderPayoutQueueSweep(db,{actorId:actor.email,force:true,limit:10});await securityAudit(db,actor,"partner.payout.queue_run","provider_payout_queue",null,"completed",{queued:data.queued,cancelled:data.cancelled,recoveries:data.recoveries,errors:data.errors.length});return json({data});}
 if(body.action==="set_payout_hold_days"){if(!Number.isFinite(Number(body.holdDays))||!body.reason)return json({error:"Number of days and a reason are required"},400);const data=await setProviderPayoutHoldDays(db,{days:Number(body.holdDays),reason:body.reason,actor:actor.email});await securityAudit(db,actor,"finance.payout_hold.set","finance_setting","provider_payout_hold","completed",{holdDays:data.holdDays,effectiveFrom:data.effectiveFrom,reason:data.reason});return json({data},201);}
 return json({error:"Unsupported partner finance action"},400);}catch(error){if(error instanceof Response)return json({error:await error.text()},error.status);return authError(error,"Unable to update partner finance");}}
