"use client";

import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import baseStyles from"./trainer.module.css";
import extraStyles from"./trainer-extra.module.css";
import{currentProviderIdentity,loadTrainerSessions,loadTrainingEvidence,prepareTrainingEvidence,trainingSessionAction,type TrainerSession}from"../../lib/training-session-client";
const styles={...baseStyles,...extraStyles};
type Tab="today"|"clients"|"earnings";
type EvidenceAsset={id:string;ref:string;proofReady:boolean;scan_status:string;access_status:string};
type EditorState={attendanceMode:"parent"|"trainer_led";parentConfirmed:boolean;safeArea:boolean;homework:string;scores:Record<string,number>;evidenceRefs:string[]};
type Earning={session_id:string;booking_id:string;package_code:string;gross_earning:number|null;status:string;hold_reason:string|null;completed_at:number};
type Payout={period_code:string;earned_amount:number;earned_sessions:number;pending_sessions:number;held_sessions:number;status:string;execution_mode:string};
type EarningsData={providerId:string;earnings:Earning[];payouts:Payout[];livePayout:false;executionMode:string};
const statusLabel=(status:string)=>({scheduled:"Scheduled",accepted:"Accepted",on_the_way:"On the way",arrived:"Arrived",in_session:"In session",reschedule_requested:"Reschedule requested",completed:"Completed",no_show:"No-show",cancelled:"Cancelled"}[status]||status.replaceAll("_"," "));
const formatTime=(value:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0);
const editorFrom=(session:TrainerSession):EditorState=>{const progress=session.progress||{};return{attendanceMode:String(session.attendance?.mode||"parent") as "parent"|"trainer_led",parentConfirmed:session.attendance?.parentOrCaretakerConfirmed!==false,safeArea:session.attendance?.safeAreaConfirmed!==false,homework:String(session.homework?.text||""),scores:{focus:Number(progress.focus||7),recall:Number(progress.recall||7),impulse:Number(progress.impulse||7),parent:Number(progress.parent||7)},evidenceRefs:session.evidenceRefs||[]};};
async function providerEarnings(providerId:string){const response=await fetch(`/api/training-provider-earnings?providerId=${encodeURIComponent(providerId)}`,{cache:"no-store"}),body=await response.json() as {data?:EarningsData;error?:string};if(!response.ok||!body.data)throw new Error(body.error||"Unable to load Training earnings");return body.data;}

export default function TrainerPage(){
 const[tab,setTab]=useState<Tab>("today"),[providerId,setProviderId]=useState(""),[sessions,setSessions]=useState<TrainerSession[]>([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState(""),[evidence,setEvidence]=useState<EvidenceAsset[]>([]),[earnings,setEarnings]=useState<EarningsData|null>(null),[attendanceMode,setAttendanceMode]=useState<"parent"|"trainer_led">("parent"),[parentConfirmed,setParentConfirmed]=useState(true),[safeArea,setSafeArea]=useState(true),[homework,setHomework]=useState(""),[scores,setScores]=useState<Record<string,number>>({focus:7,recall:7,impulse:7,parent:7}),[evidenceRefs,setEvidenceRefs]=useState<string[]>([]);
 const selected=useMemo(()=>sessions.find(item=>item.id===selectedId)||null,[sessions,selectedId]);
 const programmes=useMemo(()=>{const map=new Map<string,TrainerSession>();for(const session of sessions)if(!map.has(session.programme_id))map.set(session.programme_id,session);return[...map.values()];},[sessions]);
 const earnedAmount=useMemo(()=>earnings?.earnings.filter(item=>item.status==="earned").reduce((sum,item)=>sum+Number(item.gross_earning||0),0)||0,[earnings]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600);};
 const applyEditor=(editor:EditorState)=>{setAttendanceMode(editor.attendanceMode);setParentConfirmed(editor.parentConfirmed);setSafeArea(editor.safeArea);setHomework(editor.homework);setScores(editor.scores);setEvidenceRefs(editor.evidenceRefs);};
 async function selectSession(session:TrainerSession){setSelectedId(session.id);applyEditor(editorFrom(session));try{const result=await loadTrainingEvidence(session.id);setEvidence(result.assets);}catch{setEvidence([]);}}
 async function refresh(id=providerId,preferredSessionId=selectedId){if(!id)return;const rows=await loadTrainerSessions(id);setSessions(rows);const next=rows.find(row=>row.id===preferredSessionId)||rows[0]||null;if(next){setSelectedId(next.id);applyEditor(editorFrom(next));try{const result=await loadTrainingEvidence(next.id);setEvidence(result.assets);}catch{setEvidence([]);}}else{setSelectedId("");setEvidence([]);}if(tab==="earnings")try{setEarnings(await providerEarnings(id));}catch{setEarnings(null);}}
 async function openTab(next:Tab){setTab(next);if(next==="earnings"&&providerId){setBusy(true);try{setEarnings(await providerEarnings(providerId));setError("");}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load Training earnings");}finally{setBusy(false);}}}
 useEffect(()=>{void(async()=>{try{const identity=await currentProviderIdentity();if(identity.subjectType!=="provider")throw new Error("A provider identity session is required for the trainer workspace");const rows=await loadTrainerSessions(identity.subjectId);setProviderId(identity.subjectId);setSessions(rows);const first=rows[0]||null;if(first){const editor=editorFrom(first);setSelectedId(first.id);setAttendanceMode(editor.attendanceMode);setParentConfirmed(editor.parentConfirmed);setSafeArea(editor.safeArea);setHomework(editor.homework);setScores(editor.scores);setEvidenceRefs(editor.evidenceRefs);try{const result=await loadTrainingEvidence(first.id);setEvidence(result.assets);}catch{setEvidence([]);}}}catch(problem){setError(problem instanceof Error?problem.message:"Unable to authenticate trainer");}finally{setLoading(false);}})();},[]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!selected)return;setBusy(true);setError("");try{await trainingSessionAction({sessionId:selected.id,action,...extra} as Parameters<typeof trainingSessionAction>[0]);await refresh(providerId,selected.id);notify(`Session ${action.replaceAll("_"," ")} recorded`);}catch(problem){setError(problem instanceof Error?problem.message:"Training session update failed");}finally{setBusy(false);}}
 const report={attendance:{mode:attendanceMode,parentOrCaretakerConfirmed:attendanceMode==="parent"?parentConfirmed:false,safeAreaConfirmed:safeArea},homework,progress:scores,evidenceRefs};
 async function addEvidence(file:File|null){if(!selected||!file)return;setBusy(true);setError("");try{const prepared=await prepareTrainingEvidence({sessionId:selected.id,file});setEvidenceRefs(current=>current.includes(prepared.ref)?current:[...current,prepared.ref]);const result=await loadTrainingEvidence(selected.id);setEvidence(result.assets);notify(prepared.storage.uploadReady?"Evidence upload prepared":"Evidence registered; secure storage connection is still pending");}catch(problem){setError(problem instanceof Error?problem.message:"Unable to prepare Training evidence");}finally{setBusy(false);}}
 if(loading)return <main className={styles.shell}><section className={styles.main}><h1>Loading trainer workspace…</h1></section></main>;
 if(!providerId)return <main className={styles.gate}><section className={styles.gateCard}><h1>Trainer sign-in required</h1><p>{error||"Verify the trainer identity with the PawSpace provider OTP session before opening assigned sessions."}</p><Link href="/partner">Return to Partner</Link></section></main>;
 const nowLabel=new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 return <main className={styles.shell}>
  <aside><div className={styles.brand}><span>paw●space</span><small>TRAINER PARTNER</small></div><div className={styles.trainer}><span>TR</span><div><strong>{providerId}</strong><small>Authenticated provider session</small></div></div><nav><button className={tab==="today"?styles.active:""} onClick={()=>void openTab("today")}>▦ Sessions</button><button className={tab==="clients"?styles.active:""} onClick={()=>void openTab("clients")}>🐾 Programmes</button><button className={tab==="earnings"?styles.active:""} onClick={()=>void openTab("earnings")}>₹ Earnings</button></nav><div className={styles.links}><Link href="/partner">Partner home</Link><Link href="/training">Customer training</Link></div></aside>
  <section className={styles.main}><header><div><p>{nowLabel}</p><h1>{tab==="today"?"Your canonical training sessions":tab==="clients"?"Dogs & programmes":"Training earnings readiness"}</h1></div><span><i></i>{sessions.length} assigned session{sessions.length===1?"":"s"}</span></header>
   {error&&<section className={styles.success}><p>{error}</p></section>}
   {tab==="today"&&<section className={styles.layout}><div className={styles.schedule}><div className={styles.heading}><div><span>CANONICAL SESSION LEDGER</span><h2>{sessions.length?sessions.length:"No"} assigned sessions</h2></div><button disabled={busy} onClick={()=>void refresh()}>Refresh</button></div>{sessions.length===0&&<article className={styles.meetRequest}><b>No Training sessions are currently assigned to this authenticated trainer.</b><small>Assignments appear here only after a customer programme is materialized and this provider owns the session.</small></article>}{sessions.map(session=><button key={session.id} className={selected?.id===session.id?styles.selected:""} onClick={()=>void selectSession(session)}><span>{formatTime(session.scheduled_start)}<small>{statusLabel(session.status)}</small></span><div><strong>{session.plan_name}</strong><small>{session.customer_name} · Session {session.sequence_no} of {session.total_sessions}</small></div><b>{session.completed_sessions}/{session.total_sessions} complete</b></button>)}</div>
    {selected&&<article className={styles.session}><div className={styles.sessionHead}><div><span>{selected.id} · Booking {selected.booking_id}</span><h2>{selected.plan_name}</h2><p>{selected.customer_name} · Session {selected.sequence_no} of {selected.total_sessions}</p></div><b>{statusLabel(selected.status)}</b></div><div className={styles.actions}><button disabled={busy||selected.status!=="scheduled"} onClick={()=>void act("accept")}>Accept</button><button disabled={busy||selected.status!=="accepted"} onClick={()=>void act("on_the_way")}>On the way</button><button disabled={busy||selected.status!=="on_the_way"} onClick={()=>void act("arrive")}>Arrived</button></div>
     {["scheduled","accepted","on_the_way","arrived"].includes(selected.status)&&<section className={styles.precheck}><span>RECOVERY</span><p>Reschedule requests and no-show records open an auditable recovery case; they do not silently consume a paid session.</p><button disabled={busy} onClick={()=>{const reason=window.prompt("Why must this session be rescheduled?")||"";if(reason)void act("request_reschedule",{reason});}}>Request reschedule</button><button disabled={busy} onClick={()=>{const reason=window.prompt("Record the no-show reason")||"";if(reason)void act("no_show",{reason});}}>Record no-show</button></section>}
     {selected.status==="arrived"&&<section className={styles.precheck}><span>SESSION PRE-CHECK</span><label><input type="radio" checked={attendanceMode==="parent"} onChange={()=>setAttendanceMode("parent")}/> Parent/caretaker present</label><label><input type="radio" checked={attendanceMode==="trainer_led"} onChange={()=>setAttendanceMode("trainer_led")}/> Trainer-led permitted programme</label>{attendanceMode==="parent"&&<label><input type="checkbox" checked={parentConfirmed} onChange={event=>setParentConfirmed(event.target.checked)}/> Parent/caretaker attendance confirmed</label>}<label><input type="checkbox" checked={safeArea} onChange={event=>setSafeArea(event.target.checked)}/> Training area is safe</label><button disabled={busy||!safeArea||(attendanceMode==="parent"&&!parentConfirmed)} onClick={()=>void act("start")}>Start session</button></section>}
     {selected.status==="in_session"&&<><section className={styles.goals}><span>SESSION PLAN · SERVER-OWNED</span><p>Goals snapshot: {selected.requirements.length?selected.requirements.join(" · "):"No programme requirements were recorded"}</p><p>Completion requires attendance, homework, 1–10 progress scores and clean secure media linked to this exact session.</p></section><section className={styles.scoreGrid}>{Object.entries(scores).map(([key,value])=><label key={key}><span>{key==="parent"?"Parent practice":key[0].toUpperCase()+key.slice(1)} <b>{value}/10</b></span><input type="range" min="1" max="10" value={value} onChange={event=>setScores(current=>({...current,[key]:Number(event.target.value)}))}/></label>)}</section><section className={styles.media}><div><span>SECURE SESSION EVIDENCE</span><h3>{evidence.filter(item=>item.proofReady).length} proof-ready · {evidence.length} registered</h3><p>Prepared files remain incomplete until object storage and malware scan callbacks mark them clean and ready.</p></div><label><span>＋ Add evidence</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>void addEvidence(event.target.files?.[0]||null)}/></label></section><label className={styles.homework}><span>Homework for pet parent</span><textarea value={homework} onChange={event=>setHomework(event.target.value)}/></label><div className={styles.actions}><button disabled={busy} onClick={()=>void act("save_report",{report})}>Save report</button><button className={styles.complete} disabled={busy||homework.trim().length<10||evidenceRefs.length===0} onClick={()=>void act("complete",{report})}>Complete & consume one session</button></div></>}
     {selected.status==="completed"&&<section className={styles.success}><i>✓</i><h2>Session completed canonically</h2><p>Exactly one session consumption is recorded. Attendance, scores, homework and secure evidence remain attached to this session.</p></section>}
     {selected.status==="reschedule_requested"&&<section className={styles.success}><h2>Reschedule awaiting staff action</h2><p>The trainer cannot rewrite the canonical calendar. Team Operations must approve a new future slot after conflict checks.</p></section>}
     {selected.status==="no_show"&&<section className={styles.success}><h2>No-show recovery case open</h2><p>Session consumption is intentionally pending policy; it is not automatically charged as completed.</p></section>}
    </article>}
   </section>}
   {tab==="clients"&&<section className={styles.clientGrid}>{programmes.length===0?<article><h2>No assigned programmes</h2><p>Programme cards are derived from canonical Training sessions only.</p></article>:programmes.map(programme=><article key={programme.programme_id}><span>{programme.plan_name.slice(0,2).toUpperCase()}</span><h2>{programme.plan_name}</h2><p>{programme.customer_name}</p><div><strong>{programme.programme_status.replaceAll("_"," ")}</strong><small>{programme.completed_sessions} completed · {programme.no_show_sessions} no-show · {programme.cancelled_sessions} cancelled · {programme.total_sessions} total</small></div><button onClick={()=>{setTab("today");const next=sessions.find(item=>item.programme_id===programme.programme_id&&!["completed","cancelled","no_show"].includes(item.status))||sessions.find(item=>item.programme_id===programme.programme_id);if(next)void selectSession(next);}}>Open programme sessions</button></article>)}</section>}
   {tab==="earnings"&&<section className={styles.earnings}><div className={styles.hero}><span>CANONICAL TRAINING PAYOUT LEDGER</span><strong>{earnings?money(earnedAmount):busy?"Loading…":"No earnings ledger yet"}</strong><p>{earnings?`Execution: ${earnings.executionMode.replaceAll("_"," ")}. Live payout is not connected.`:"Only completed canonical sessions can enter this ledger. A Finance-published rate is required before money is shown as earned."}</p></div><div className={styles.stats}><article><span>Completed session earnings</span><strong>{earnings?.earnings.filter(item=>item.status==="earned").length??0}</strong><small>Rate configured + customer payment captured</small></article><article><span>Pending rate / holds</span><strong>{earnings?.earnings.filter(item=>item.status!=="earned").length??0}</strong><small>No invented amount while blocked</small></article><article><span>Payout statement</span><strong>{earnings?.payouts[0]?.status.replaceAll("_"," ")||"Not created"}</strong><small>{earnings?.payouts[0]?`${earnings.payouts[0].period_code} · ${money(earnings.payouts[0].earned_amount)}`:"Appears after completed-session earnings exist"}</small></article></div>{earnings?.earnings.length?<section className={styles.clientGrid}>{earnings.earnings.map(item=><article key={item.session_id}><span>₹</span><h2>{item.gross_earning===null?"Rate pending":money(item.gross_earning)}</h2><p>{item.session_id} · {item.package_code}</p><div><strong>{item.status.replaceAll("_"," ")}</strong><small>{item.hold_reason||"Eligible completed session"}</small></div></article>)}</section>:null}</section>}
  </section>{toast&&<div className={styles.toast}>✓ {toast}</div>}
 </main>;
}
