import{authError,authorize,securityAudit}from"../../../lib/server-auth";
import{ensureGroomingPolicyTables,seedDefaultGroomingPolicy}from"../../../lib/grooming-policy-governance";

type Row=Record<string,unknown>;
const json=(value:unknown,status=200)=>Response.json(value,{status});
async function database(){const{env}=await import("cloudflare:workers");return env.DB;}
const editable=["enforcement_mode","cancellation_cutoff_minutes","refund_percent_before_cutoff","refund_percent_after_cutoff","reschedule_cutoff_minutes","reschedule_allowed_after_cutoff","max_reschedules","reschedule_fee_type","reschedule_fee_value","no_show_refund_percent","multi_pet_max","multi_pet_pricing_mode","change_lock_statuses_json","active","effective_from","effective_to"];

// The policy field rules, in ONE place. They used to live only inside the PATCH loop, so a policy could
// be CREATED with values PATCH would have refused - and enforcement_mode is the one that costs money:
// rowToPolicy coerces anything that is not exactly "enforce" to "observe", and evaluateBookingChange's
// observe branch forces refundPercent to 100 and waives every configured cutoff. A create carrying
// "Enforce" therefore produced a policy that refunded late cancellations in full while reading as
// strict in the operator UI. Same rules, same messages, now applied on both paths. [PTJA-P0-03]
const NON_NEGATIVE=["cancellation_cutoff_minutes","refund_percent_before_cutoff","refund_percent_after_cutoff","reschedule_cutoff_minutes","max_reschedules","reschedule_fee_value","no_show_refund_percent","multi_pet_max"];
const PERCENTAGES=["refund_percent_before_cutoff","refund_percent_after_cutoff","no_show_refund_percent"];
function policyFieldProblem(key:string,value:unknown){
 if(NON_NEGATIVE.includes(key)&&Number(value)<0)return `${key} cannot be negative`;
 if(PERCENTAGES.includes(key)&&Number(value)>100)return `${key} cannot exceed 100`;
 if(key==="enforcement_mode"&&!['observe','enforce'].includes(String(value)))return "Enforcement mode must be observe or enforce";
 if(key==="reschedule_fee_type"&&!['none','flat','percent'].includes(String(value)))return "Reschedule fee type must be none, flat or percent";
 if(key==="multi_pet_pricing_mode"&&!['catalogue','per_pet','custom'].includes(String(value)))return "Multi-pet pricing mode must be catalogue, per_pet or custom";
 return null;
}

export async function GET(request:Request){try{await authorize(request,"pricing.view");const db=await database();await seedDefaultGroomingPolicy(db);const url=new URL(request.url),cityId=(url.searchParams.get("cityId")||"blr").trim();const rows=await db.prepare("SELECT * FROM grooming_commercial_policies WHERE city_id=? ORDER BY policy_code,version DESC").bind(cityId).all<Row>();const audit=await db.prepare("SELECT * FROM grooming_commercial_policy_audit WHERE city_id=? ORDER BY created_at DESC LIMIT 50").bind(cityId).all<Row>();return json({data:{cityId,policies:rows.results,audit:audit.results}});}catch(error){return authError(error,"Unable to load Grooming commercial policy");}}

export async function PATCH(request:Request){try{const actor=await authorize(request,"pricing.manage");const db=await database();await seedDefaultGroomingPolicy(db);const body=await request.json() as {id?:string;changes?:Record<string,unknown>;reason?:string};if(!body.id||!body.reason||body.reason.trim().length<5)return json({error:"Policy ID and a clear change reason are required"},400);const before=await db.prepare("SELECT * FROM grooming_commercial_policies WHERE id=?").bind(body.id).first<Row>();if(!before)return json({error:"Grooming commercial policy not found"},404);const entries=Object.entries(body.changes||{}).filter(([key])=>editable.includes(key));if(!entries.length)return json({error:"No supported policy changes supplied"},400);for(const [key,value] of entries){const problem=policyFieldProblem(key,value);if(problem)return json({error:problem},400);}const now=Date.now(),set=entries.map(([key])=>`${key}=?`).join(",");await db.prepare(`UPDATE grooming_commercial_policies SET ${set},version=version+1,updated_by=?,updated_at=? WHERE id=?`).bind(...entries.map(([,value])=>value),actor.email,now,body.id).run();const after=await db.prepare("SELECT * FROM grooming_commercial_policies WHERE id=?").bind(body.id).first<Row>();await db.prepare("INSERT INTO grooming_commercial_policy_audit (id,policy_id,policy_code,city_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),body.id,String(before.policy_code),String(before.city_id),"updated",JSON.stringify(before),JSON.stringify(after),actor.email,body.reason.trim(),now).run();await securityAudit(db,actor,"grooming.commercial_policy.update","commercial_policy",body.id,"completed",{reason:body.reason,changes:entries.map(([key])=>key)});return json({data:after});}catch(error){return authError(error,"Unable to update Grooming commercial policy");}}

export async function POST(request:Request){try{const actor=await authorize(request,"pricing.manage");const db=await database();await ensureGroomingPolicyTables(db);const body=await request.json() as Record<string,unknown>;if(!body.cityId||!body.policyCode)return json({error:"City and policy code are required"},400);
 // The values below are exactly what the INSERT binds, judged by the same rules PATCH applies.
 const proposed:Record<string,unknown>={enforcement_mode:String(body.enforcementMode||"observe"),cancellation_cutoff_minutes:Number(body.cancellationCutoffMinutes||0),refund_percent_before_cutoff:Number(body.refundPercentBeforeCutoff??100),refund_percent_after_cutoff:Number(body.refundPercentAfterCutoff??100),reschedule_cutoff_minutes:Number(body.rescheduleCutoffMinutes||0),max_reschedules:Number(body.maxReschedules||0),reschedule_fee_type:String(body.rescheduleFeeType||"none"),reschedule_fee_value:Number(body.rescheduleFeeValue||0),no_show_refund_percent:Number(body.noShowRefundPercent||0),multi_pet_max:Number(body.multiPetMax||4),multi_pet_pricing_mode:String(body.multiPetPricingMode||"catalogue")};
 for(const [key,value] of Object.entries(proposed)){const problem=policyFieldProblem(key,value);if(problem)return json({error:problem},400);}
 const id=`gpolicy_${crypto.randomUUID().slice(0,12)}`,now=Date.now();await db.prepare("INSERT INTO grooming_commercial_policies (id,policy_code,city_id,zone_id,enforcement_mode,cancellation_cutoff_minutes,refund_percent_before_cutoff,refund_percent_after_cutoff,reschedule_cutoff_minutes,reschedule_allowed_after_cutoff,max_reschedules,reschedule_fee_type,reschedule_fee_value,no_show_refund_percent,multi_pet_max,multi_pet_pricing_mode,change_lock_statuses_json,active,version,effective_from,effective_to,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,1,?,?,?,?)").bind(id,String(body.policyCode),String(body.cityId),body.zoneId?String(body.zoneId):null,String(body.enforcementMode||"observe"),Number(body.cancellationCutoffMinutes||0),Number(body.refundPercentBeforeCutoff??100),Number(body.refundPercentAfterCutoff??100),Number(body.rescheduleCutoffMinutes||0),body.rescheduleAllowedAfterCutoff===false?0:1,Number(body.maxReschedules||0),String(body.rescheduleFeeType||"none"),Number(body.rescheduleFeeValue||0),Number(body.noShowRefundPercent||0),Number(body.multiPetMax||4),String(body.multiPetPricingMode||"catalogue"),JSON.stringify(body.changeLockStatuses||["completed","cancelled"]),String(body.effectiveFrom||new Date().toISOString().slice(0,10)),body.effectiveTo?String(body.effectiveTo):null,actor.email,now).run();const created=await db.prepare("SELECT * FROM grooming_commercial_policies WHERE id=?").bind(id).first<Row>();await db.prepare("INSERT INTO grooming_commercial_policy_audit (id,policy_id,policy_code,city_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,?,NULL,?,?,?,?)").bind(crypto.randomUUID(),id,String(body.policyCode),String(body.cityId),"created",JSON.stringify(created),actor.email,String(body.reason||"New Grooming commercial policy"),now).run();await securityAudit(db,actor,"grooming.commercial_policy.create","commercial_policy",id,"completed",{cityId:body.cityId,zoneId:body.zoneId??null});return json({data:created},201);}catch(error){return authError(error,"Unable to create Grooming commercial policy");}}
