import{refuseUnlessGatewayPermits}from"../../../lib/api-gateway";
import{authError,database,requireCustomerOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{ensureGroomingMapTables,mapsNavigationUrl}from"../../../lib/grooming-maps";

type Input={bookingId:string;customerId:string;address:string;latitude?:number;longitude?:number};
const json=(value:unknown,status=200)=>Response.json(value,{status});

export async function POST(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{
  const input=await request.json() as Input;const bookingId=String(input.bookingId||"").trim(),customerId=String(input.customerId||"").trim(),address=String(input.address||"").trim();if(!bookingId||!customerId||address.length<8)return json({error:"Booking, customer and complete doorstep address are required"},400);
  const db=await database();await ensureGroomingMapTables(db);const actor=await resolveActor(request);await requireCustomerOwnership(db,actor,customerId);const booking=await db.prepare("SELECT id,customer_id,provider_id,service_code FROM canonical_bookings WHERE id=?").bind(bookingId).first<Record<string,unknown>>();if(!booking)return json({error:"Canonical booking not found"},404);if(String(booking.customer_id)!==customerId)return json({error:"Customer does not own this booking"},403);if(String(booking.service_code)!=="grooming")return json({error:"This endpoint is currently limited to Grooming UAT"},409);
  const lat=Number(input.latitude),lng=Number(input.longitude),hasCoords=Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lng)&&lng>=-180&&lng<=180;const now=Date.now();await db.prepare("INSERT INTO booking_service_locations (booking_id,customer_id,provider_id,address_text,latitude,longitude,source,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'customer_booking','active',?,?) ON CONFLICT(booking_id) DO UPDATE SET customer_id=excluded.customer_id,provider_id=excluded.provider_id,address_text=excluded.address_text,latitude=excluded.latitude,longitude=excluded.longitude,status='active',updated_at=excluded.updated_at").bind(bookingId,customerId,String(booking.provider_id),address,hasCoords?lat:null,hasCoords?lng:null,now,now).run();await securityAudit(db,actor,"grooming.service_location.save","booking",bookingId,"completed",{hasCoordinates:hasCoords,addressLength:address.length});return json({data:{bookingId,addressSaved:true,coordinatesSaved:hasCoords,navigationUrl:mapsNavigationUrl(address)}} ,201);
}catch(error){return authError(error,"Unable to save Grooming service location");}}
