import{authError,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";

type Db=Awaited<ReturnType<typeof database>>;
type Row=Record<string,unknown>;
type MediaPurpose="before_service"|"after_service"|"service_issue"|"training_homework"|"stay_update";
type RegisterInput={bookingId:string;purpose:MediaPurpose;mimeType:string;sizeBytes:number;sha256:string;storageKey?:string};

const json=(value:unknown,status=200)=>Response.json(value,{status});
async function database(){const{env}=await import("cloudflare:workers");return env.DB;}
async function ensureTables(db:Db){await db.batch([
  db.prepare("CREATE TABLE IF NOT EXISTS provider_work_orders (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,schedule_group_id TEXT NOT NULL,provider_id TEXT NOT NULL,provider_name TEXT NOT NULL,provider_model TEXT NOT NULL,service_code TEXT NOT NULL,scheduled_start TEXT NOT NULL,scheduled_end TEXT NOT NULL,occurrence_count INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'assigned',assignment_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
  db.prepare("CREATE TABLE IF NOT EXISTS service_media_assets (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,purpose TEXT NOT NULL,storage_key TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,scan_status TEXT NOT NULL DEFAULT 'clean',access_status TEXT NOT NULL DEFAULT 'ready',retention_status TEXT NOT NULL DEFAULT 'active',synthetic INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
]);}
const allowedPurpose=new Set<MediaPurpose>(["before_service","after_service","service_issue","training_homework","stay_update"]);
const allowedMime=new Set(["image/jpeg","image/png","image/webp"]);

export async function GET(request:Request){try{const db=await database();await ensureTables(db);const actor=await resolveActor(request);requirePermission(actor,"bookings.view");const url=new URL(request.url),bookingId=(url.searchParams.get("bookingId")||"").trim();if(!bookingId)return json({error:"Booking ID is required"},400);const work=await db.prepare("SELECT provider_id FROM provider_work_orders WHERE booking_id=?").bind(bookingId).first<Row>();if(!work)return json({error:"Provider work order not found"},404);await requireProviderOwnership(db,actor,String(work.provider_id));const assets=await db.prepare("SELECT id,booking_id,provider_id,purpose,mime_type,size_bytes,sha256,scan_status,access_status,retention_status,synthetic,created_at FROM service_media_assets WHERE booking_id=? ORDER BY created_at").bind(bookingId).all<Row>();return json({bookingId,assets:assets.results.map(row=>({...row,ref:`media://asset/${String(row.id)}`}))});}catch(error){return authError(error,"Unable to load service media");}}

export async function POST(request:Request){try{const input=await request.json() as RegisterInput;if(!input.bookingId||!input.purpose||!input.mimeType||!Number.isFinite(input.sizeBytes)||!input.sha256)return json({error:"Booking, purpose, MIME type, size and checksum are required"},400);if(!allowedPurpose.has(input.purpose))return json({error:"Unsupported media purpose"},400);if(!allowedMime.has(input.mimeType))return json({error:"Only JPEG, PNG and WebP proof images are accepted in this UAT registry"},400);if(input.sizeBytes<1||input.sizeBytes>10_000_000)return json({error:"Proof image must be between 1 byte and 10 MB"},400);if(!/^[a-f0-9]{64}$/i.test(input.sha256))return json({error:"A valid SHA-256 checksum is required"},400);
  const db=await database();await ensureTables(db);const actor=await resolveActor(request);requirePermission(actor,"bookings.view");const work=await db.prepare("SELECT provider_id,service_code FROM provider_work_orders WHERE booking_id=?").bind(input.bookingId).first<Row>();if(!work)return json({error:"Provider work order not found"},404);await requireProviderOwnership(db,actor,String(work.provider_id));const id=`MEDIA-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now(),storageKey=input.storageKey?.trim()||`uat/${String(work.service_code)}/${input.bookingId}/${id}`;
  await db.prepare("INSERT INTO service_media_assets (id,booking_id,provider_id,purpose,storage_key,mime_type,size_bytes,sha256,scan_status,access_status,retention_status,synthetic,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'clean','ready','active',1,?,?,?)").bind(id,input.bookingId,work.provider_id,input.purpose,storageKey,input.mimeType,input.sizeBytes,input.sha256,actor.email,now,now).run();await securityAudit(db,actor,"service_media.register","booking",input.bookingId,"completed",{mediaId:id,purpose:input.purpose,providerId:work.provider_id,synthetic:true});return json({data:{id,ref:`media://asset/${id}`,bookingId:input.bookingId,providerId:String(work.provider_id),purpose:input.purpose,scanStatus:"clean",accessStatus:"ready",synthetic:true}},201);
}catch(error){return authError(error,"Unable to register service media");}}
