"use client";
import Link from"next/link";
import{useEffect,useState}from"react";
import{loadWalkingLifecycle,updateWalkingLifecycle,type WalkingLifecycleBooking}from"../../lib/walking-lifecycle-client";

export default function WalkerWorkspace({bookingId}:{bookingId:string}){
 const[booking,setBooking]=useState<WalkingLifecycleBooking|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function refresh(){if(!bookingId)return;try{setError("");const rows=await loadWalkingLifecycle({bookingId});setBooking(rows[0]||null)}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load Walking booking")}}
 useEffect(()=>{if(!bookingId)return;let active=true;void loadWalkingLifecycle({bookingId}).then(rows=>{if(active)setBooking(rows[0]||null)}).catch(problem=>{if(active)setError(problem instanceof Error?problem.message:"Unable to load Walking booking")});return()=>{active=false}},[bookingId]);
 async function act(action:"accept"|"decline"|"start_walk"|"walk_event"|"walker_unavailable"|"complete_walk",extra:Record<string,unknown>={}){if(!bookingId||busy)return;setBusy(true);setError("");try{await updateWalkingLifecycle({bookingId,action,idempotencyKey:`walker:${bookingId}:${action}:${crypto.randomUUID()}`,...extra});await refresh()}catch(problem){setError(problem instanceof Error?problem.message:"Unable to update Walking booking")}finally{setBusy(false)}}
 if(!bookingId)return <main style={{padding:24,fontFamily:"system-ui"}}><h1>PawSpace Walker workspace</h1><p>Open this workspace from a canonical Walking booking.</p><Link href="/walking">Open Walking customer flow</Link></main>;
 if(!booking)return <main style={{padding:24,fontFamily:"system-ui"}}><h1>PawSpace Walker workspace</h1><p>{error||"Loading canonical booking…"}</p></main>;
 const status=String(booking.status||"");return <main style={{maxWidth:900,margin:"0 auto",padding:24,fontFamily:"system-ui",display:"grid",gap:16}}><header><Link href="/">PawSpace</Link><h1>Walker workspace</h1><p>Canonical booking <strong>{booking.id}</strong></p></header><section style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><p>Status: <strong>{status}</strong></p><p>Window: {String(booking.scheduled_start)} → {String(booking.scheduled_end)}</p><p>Handover: {booking.handover?"UAT verified":"waiting for customer"}</p>{error&&<p role="alert">{error}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={busy||!["confirmed","reassignment_offered"].includes(status)} onClick={()=>void act("accept")}>Accept walk</button><button disabled={busy||["completed","cancelled","in_progress"].includes(status)} onClick={()=>void act("decline",{reason:"Walker declined during UAT lifecycle"})}>Decline</button><button disabled={busy||status!=="assigned"||!booking.handover} onClick={()=>void act("start_walk")}>Start walk</button><button disabled={busy||status!=="in_progress"} onClick={()=>void act("walk_event",{eventType:"pee",detail:{source:"walker_workspace"}})}>Log pee</button><button disabled={busy||status!=="in_progress"} onClick={()=>void act("walk_event",{eventType:"water",detail:{source:"walker_workspace"}})}>Log water</button><button disabled={busy||status!=="in_progress"} onClick={()=>void act("walk_event",{eventType:"route_checkpoint",detail:{gpsMode:"uat_not_live",note:"Route checkpoint recorded without live GPS adapter"}})}>Route checkpoint</button><button disabled={busy||status!=="in_progress"} onClick={()=>void act("complete_walk")}>Complete walk</button><button disabled={busy||["completed","cancelled"].includes(status)} onClick={()=>void act("walker_unavailable",{reason:"Walker unavailable during UAT lifecycle"})}>Mark unavailable</button></div></section><section style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Canonical walk timeline</h2>{(booking.events||[]).length?(booking.events||[]).map((item,index)=><p key={String(item.id||index)}><strong>{String(item.event_type||"event")}</strong> · {new Date(Number(item.created_at||0)).toLocaleString("en-IN")}</p>):<p>No walk events yet.</p>}<p><small>Live GPS, live OTP delivery and production messaging remain disconnected in UAT.</small></p></section></main>;
}
