import{authError,database,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{findIdentityBinding}from"../../../lib/identity-binding";
import{hasPermission}from"../../../lib/platform-security";
import{computeGoogleRoute}from"../../../lib/grooming-maps";
import{createAccountabilityCandidate,createApprovedFinancialAdjustment,ensureUniversalLocationTables,evaluatePredictedLateness,LocationConfigurationRequired,locationGovernanceSnapshot,openRecoveryCase,recordEtaSnapshot,recordLocationEvidence,reviewAccountability,startLocationSession}from"../../../lib/universal-location-recovery";
import{selectCapacitySafeReplacement}from"../../../lib/universal-replacement-recovery";
import{journeyIsLive,resolveLiveJourneyDestination,serviceJourneyStatus}from"../../../lib/live-journey-destination";
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{"cache-control":"no-store"}});
function sameOrigin(r:Request){const o=r.headers.get("origin");if(o&&o!==new URL(r.url).origin)throw new Response("Cross-origin write blocked",{status:403})}
type Row=Record<string,unknown>;
async function ownProviderId(db:D1Database,actor:Awaited<ReturnType<typeof resolveActor>>){const binding=await findIdentityBinding(db,{identitySource:actor.identitySource,principalType:actor.principalType,principalKey:actor.principalKey,subjectType:"provider"});if(binding)return String(binding.subject_id);const legacy=await db.prepare("SELECT provider_id,status FROM provider_identity_links WHERE email=?").bind(actor.email).first<Row>();return legacy&&String(legacy.status)==="active"?String(legacy.provider_id):null;}
async function stagingDistanceFallback(){const{env}=await import("cloudflare:workers");const runtime=env as unknown as Record<string,unknown>,appEnv=String(runtime.APP_ENV??"").trim().toLowerCase(),schedulingEnv=String(runtime.PAWSPACE_SCHEDULING_ENV??"").trim().toLowerCase();return appEnv==="staging"||schedulingEnv==="uat"?2.5:null;}
/** Where an accepted fix from this provider would be routed right now; null once the journey is over or has nowhere to go. */
async function liveJourney(db:D1Database,bookingId:string,providerId:string){
 const booking=await db.prepare("SELECT service_code,status FROM canonical_bookings WHERE id=? AND provider_id=?").bind(bookingId,providerId).first<Row>();
 if(!booking)return null;
 const serviceCode=String(booking.service_code||""),canonical=String(booking.status||"");
 // A location session is never closed with its booking, so the booking itself must still be live: otherwise a
 // completed, cancelled or reassigned journey keeps turning every accepted fix into a customer-facing ETA.
 if(!journeyIsLive(serviceCode,canonical))return null;
 const status=await serviceJourneyStatus(db,serviceCode,bookingId)||canonical;
 const destination=await resolveLiveJourneyDestination(db,{bookingId,serviceCode,status});
 return destination?{status,destination}:null;
}
async function refreshEtaForAcceptedFix(db:D1Database,input:{eventId:string;trustState:string;sessionId:string;providerId:string;lat:number;lng:number}){
 if(input.trustState!=="accepted")return null;
 const session=await db.prepare("SELECT booking_id FROM provider_location_sessions WHERE id=? AND provider_id=? AND status='active'").bind(input.sessionId,input.providerId).first<Row>();
 if(!session)return null;
 const bookingId=String(session.booking_id),journey=await liveJourney(db,bookingId,input.providerId);
 if(!journey)return null;
 const{destination}=journey;
 const route=await computeGoogleRoute({lat:input.lat,lng:input.lng},{lat:destination.latitude,lng:destination.longitude});
 // The Routes call is the slow step. If a transition landed meanwhile (trip started, walk completed, booking cancelled),
 // an ETA for the phase it just left must not be stored as the latest one; the next accepted fix routes afresh.
 if(JSON.stringify(await liveJourney(db,bookingId,input.providerId))!==JSON.stringify(journey))return null;
 const distanceMeters=Number(route.distanceMeters),durationSeconds=Number(route.durationSeconds);
 return recordEtaSnapshot(db,{bookingId,providerId:input.providerId,originEventId:input.eventId,destination:{latitude:destination.latitude,longitude:destination.longitude,phase:destination.phase},distanceMeters:Number.isFinite(distanceMeters)?distanceMeters:undefined,durationSeconds:Number.isFinite(durationSeconds)?durationSeconds:undefined,providerStatus:route.status,providerReference:route.provider??"google_routes_sandbox",polyline:route.polyline??null});
}
export const LOCATION_ACTION_PERMISSION:Record<string,"bookings.view"|"bookings.manage"|"finance.manage">={start_session:"bookings.view",record_location:"bookings.view",calculate_eta:"bookings.view",create_financial_adjustment:"finance.manage"};
export async function GET(request:Request){try{const actor=await resolveActor(request),db=await database();await ensureUniversalLocationTables(db);if(actor.developmentPreview||hasPermission(actor.permissions,"bookings.manage")){return json({data:await locationGovernanceSnapshot(db),productionReady:false,rawGpsCustomerExposure:false,gpsConnected:true,simulatedDistanceKm:await stagingDistanceFallback(),telemetryMode:"deterministic_sandbox"});}const providerId=await ownProviderId(db,actor);if(!providerId)throw new Response("Provider ownership denied",{status:403});await requireProviderOwnership(db,actor,providerId);const booking=await db.prepare("SELECT id,provider_id,status,scheduled_start,scheduled_end,service_code FROM canonical_bookings WHERE provider_id=? AND status IN ('confirmed','assigned','on_the_way','arrived','in_service') ORDER BY updated_at DESC LIMIT 1").bind(providerId).first<Row>();if(!booking)throw new Response("No active assigned booking for provider",{status:404});const bookingId=String(booking.id),[session,lastLocation,eta]=await Promise.all([db.prepare("SELECT id,status,starts_at,ends_at,policy_version_id FROM provider_location_sessions WHERE booking_id=? AND provider_id=? AND status='active' ORDER BY starts_at DESC LIMIT 1").bind(bookingId,providerId).first<Row>(),db.prepare("SELECT id,trust_state,accuracy_meters,server_received_at,client_captured_at FROM universal_provider_location_events WHERE booking_id=? AND provider_id=? ORDER BY server_received_at DESC LIMIT 1").bind(bookingId,providerId).first<Row>(),db.prepare("SELECT id,distance_meters,duration_seconds,predicted_arrival_at,provider_status,calculated_at,stale_after FROM route_eta_snapshots WHERE booking_id=? AND provider_id=? ORDER BY calculated_at DESC LIMIT 1").bind(bookingId,providerId).first<Row>()]);const measured=Number(eta?.distance_meters),simulatedDistanceKm=Number.isFinite(measured)&&measured>=0?Math.round(measured)/1000:await stagingDistanceFallback();return json({data:{providerId,bookingId,bookingStatus:String(booking.status),serviceCode:String(booking.service_code),scheduledStart:String(booking.scheduled_start),scheduledEnd:String(booking.scheduled_end),session:session??null,lastLocation:lastLocation??null,eta:eta??null},productionReady:false,rawGpsCustomerExposure:false,gpsConnected:true,simulatedDistanceKm,telemetryMode:eta?"sandbox_adapter":"deterministic_sandbox"});}catch(e){return authError(e,"Unable to load location recovery governance")}}
export async function POST(request:Request){try{sameOrigin(request);const actor=await resolveActor(request),db=await database(),b=await request.json() as Record<string,unknown>,action=String(b.action||"");requirePermission(actor,LOCATION_ACTION_PERMISSION[action]??"bookings.manage");await ensureUniversalLocationTables(db);let data:unknown;
 if(action==="save_policy"){const required=["etaFreshnessSeconds","allowedAccuracyMeters","customerAlertMinutes","opsEscalationMinutes","reassignmentMinutes","rawGpsRetentionDays"];if(required.some(k=>!Number.isFinite(Number(b[k]))||Number(b[k])<=0))throw new Response("Approved policy thresholds and retention must be configured",{status:400});const id=String(b.id||`PUNC-${crypto.randomUUID().slice(0,10).toUpperCase()}`),t=Date.now(),state=String(b.approvalState||"draft");if(!["draft","approved","retired"].includes(state))throw new Response("Invalid policy approval state",{status:400});await db.prepare("INSERT INTO booking_punctuality_policies (id,service_code,city_id,provider_model,tracking_enabled,eta_freshness_seconds,allowed_accuracy_meters,grace_minutes,customer_alert_minutes,ops_escalation_minutes,reassignment_minutes,evidence_requirements_json,excluded_reasons_json,raw_gps_retention_days,approval_state,effective_from,effective_to,approved_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET tracking_enabled=excluded.tracking_enabled,eta_freshness_seconds=excluded.eta_freshness_seconds,allowed_accuracy_meters=excluded.allowed_accuracy_meters,grace_minutes=excluded.grace_minutes,customer_alert_minutes=excluded.customer_alert_minutes,ops_escalation_minutes=excluded.ops_escalation_minutes,reassignment_minutes=excluded.reassignment_minutes,evidence_requirements_json=excluded.evidence_requirements_json,excluded_reasons_json=excluded.excluded_reasons_json,raw_gps_retention_days=excluded.raw_gps_retention_days,approval_state=excluded.approval_state,effective_from=excluded.effective_from,effective_to=excluded.effective_to,approved_by=excluded.approved_by,updated_at=excluded.updated_at").bind(id,String(b.serviceCode),b.cityId??null,b.providerModel??null,b.trackingEnabled===false?0:1,Number(b.etaFreshnessSeconds),Number(b.allowedAccuracyMeters),Number(b.graceMinutes||0),Number(b.customerAlertMinutes),Number(b.opsEscalationMinutes),Number(b.reassignmentMinutes),JSON.stringify(b.evidenceRequirements||["punctuality_event","recovery_case"]),JSON.stringify(b.excludedReasons||[]),Number(b.rawGpsRetentionDays),state,String(b.effectiveFrom||new Date().toISOString().slice(0,10)),b.effectiveTo??null,state==="approved"?actor.email:null,t).run();data={id,approvalState:state,gpsConnected:String(b.serviceCode||"")==="pet_taxi"?true:undefined,telemetryMode:String(b.serviceCode||"")==="pet_taxi"?"deterministic_sandbox":undefined};}
 else if(action==="set_controls"){if(String(b.mapEnvironment||"sandbox")!=="sandbox")throw new Response("Production map mode is not enabled in this UAT workstream",{status:409});await db.prepare("UPDATE location_control_settings SET gps_ingestion_enabled=?,map_adapter_enabled=?,map_environment='sandbox',updated_by=?,updated_at=? WHERE id='global'").bind(b.gpsIngestionEnabled===false?0:1,b.mapAdapterEnabled===true?1:0,actor.email,Date.now()).run();data={gpsIngestionEnabled:b.gpsIngestionEnabled!==false,mapAdapterEnabled:b.mapAdapterEnabled===true,mapEnvironment:"sandbox",gpsConnected:true,telemetryMode:"deterministic_sandbox"};}
 else if(action==="start_session"){await requireProviderOwnership(db,actor,String(b.providerId));data={...(await startLocationSession(db,{bookingId:String(b.bookingId),providerId:String(b.providerId),actor:actor.email})),gpsConnected:true,telemetryMode:"deterministic_sandbox"};}
 else if(action==="record_location"){await requireProviderOwnership(db,actor,String(b.providerId));const lat=Number(b.latitude),lng=Number(b.longitude),location=await recordLocationEvidence(db,{sessionId:String(b.sessionId),providerId:String(b.providerId),lat,lng,accuracyMeters:Number(b.accuracyMeters),clientCapturedAt:b.clientCapturedAt?Number(b.clientCapturedAt):undefined,actor}),eta=await refreshEtaForAcceptedFix(db,{eventId:String(location.id),trustState:String(location.trustState),sessionId:String(b.sessionId),providerId:String(b.providerId),lat,lng});data={...location,eta:eta??undefined,gpsConnected:true,telemetryMode:eta?"sandbox_adapter":"deterministic_sandbox"};}
 else if(action==="calculate_eta"){await requireProviderOwnership(db,actor,String(b.providerId));const origin=await db.prepare("SELECT latitude,longitude,trust_state FROM universal_provider_location_events WHERE id=? AND booking_id=? AND provider_id=?").bind(String(b.originEventId),String(b.bookingId),String(b.providerId)).first<Record<string,unknown>>();if(!origin)throw new Response("Origin evidence not found",{status:404});if(String(origin.trust_state)!=="accepted")throw new Response("Untrusted GPS cannot drive ETA",{status:409});const destination=String(b.destinationAddress||"").trim();if(destination.length<8)throw new Response("A complete service destination is required",{status:400});let distanceMeters:number,durationSeconds:number,providerStatus:"configured"|"configuration_required"|"route_unavailable",providerReference:string,polyline:string|null=null;const simulatedDistanceKm=Number(b.simulatedDistanceKm);if(Number.isFinite(simulatedDistanceKm)&&simulatedDistanceKm>=0){distanceMeters=Math.round(simulatedDistanceKm*1000);durationSeconds=Math.max(60,Math.round(simulatedDistanceKm/30*3600));providerStatus="configured";providerReference="pawspace-deterministic-sandbox";}else{const route=await computeGoogleRoute({lat:Number(origin.latitude),lng:Number(origin.longitude)},destination);distanceMeters=Number(route.distanceMeters);durationSeconds=Number(route.durationSeconds);providerStatus=route.status;providerReference=route.provider??"google_routes_sandbox";polyline=route.polyline??null;}data={...(await recordEtaSnapshot(db,{bookingId:String(b.bookingId),providerId:String(b.providerId),originEventId:String(b.originEventId),destination:{address:destination},distanceMeters,durationSeconds,providerStatus,providerReference,polyline})),gpsConnected:true,telemetryMode:providerReference==="pawspace-deterministic-sandbox"?"deterministic_sandbox":"sandbox_adapter"};}
 else if(action==="evaluate_lateness"){data=await evaluatePredictedLateness(db,{bookingId:String(b.bookingId),providerId:String(b.providerId),etaSnapshotId:String(b.etaSnapshotId)});}
 else if(action==="open_recovery"){data=await openRecoveryCase(db,{bookingId:String(b.bookingId),providerId:String(b.providerId),reasonCode:String(b.reasonCode||"predicted_late"),owner:actor.email,detail:b.detail});}
 else if(action==="select_replacement"){const candidate=await selectCapacitySafeReplacement(db,{bookingId:String(b.bookingId),excludeProviderId:String(b.providerId)});data=candidate?{...candidate,status:candidate.requiresAcceptance?"replacement_offer_required":"replacement_eligible"}:{status:"ops_escalation",reason:"no_capacity_safe_candidate"};}
 else if(action==="create_accountability"){data=await createAccountabilityCandidate(db,{bookingId:String(b.bookingId),providerId:String(b.providerId),recoveryCaseId:String(b.recoveryCaseId),candidateType:String(b.candidateType||"quality_review") as "coaching"|"quality_review"|"penalty_candidate"|"no_action",evidenceEventIds:Array.isArray(b.evidenceEventIds)?b.evidenceEventIds.map(String):[]});}
 else if(action==="review_accountability"){data=await reviewAccountability(db,{caseId:String(b.caseId),decision:String(b.decision) as "approved"|"rejected"|"exempted"|"disputed",reviewer:actor.email,reason:String(b.reason||""),consequenceReference:b.consequenceReference?String(b.consequenceReference):undefined});}
 else if(action==="create_financial_adjustment"){data=await createApprovedFinancialAdjustment(db,{accountabilityCaseId:String(b.accountabilityCaseId),amount:Number(b.amount),adjustmentType:String(b.adjustmentType||"deduction") as "deduction"|"reversal"|"manual_correction",settlementPeriod:String(b.settlementPeriod||""),financeApprover:actor.email,auditReference:String(b.auditReference||"")});}
 else throw new Response("Unsupported action",{status:400});await securityAudit(db,actor,`location.recovery.${action}`,"location_recovery",String((data as Record<string,unknown>)?.id||b.bookingId||"control"),"completed",{productionReady:false,liveDeduction:false,liveMapProduction:false,gpsConnected:true,telemetryMode:"deterministic_sandbox"});return json({data,productionReady:false,liveDeductionEnabled:false,liveMapProduction:false,gpsConnected:true,telemetryMode:"deterministic_sandbox"});
 }catch(e){if(e instanceof LocationConfigurationRequired)return json({error:"configuration_required",configurationKey:e.key,productionReady:false},409);return authError(e,"Location recovery action failed")}}
