import{authError,database,requireCustomerOwnership,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission}from"../../../lib/platform-security";
import{getSittingBooking,listSittingBookings,mutateSittingBooking,type SittingAction,type SittingCarePlan}from"../../../lib/sitting-lifecycle";

type Body={bookingId?:string;action?:SittingAction;idempotencyKey?:string;reason?:string;carePlan?:SittingCarePlan;careEventType?:string;detail?:Record<string,unknown>};
const json=(value:unknown,status=200)=>Response.json(value,{status});
const providerActions=new Set<SittingAction>(["accept","decline","check_in","care_event","sitter_unavailable","check_out"]);
const customerActions=new Set<SittingAction>(["submit_care_plan"]);

export async function GET(request:Request){try{const url=new URL(request.url),providerId=String(url.searchParams.get("providerId")||"").trim(),customerId=String(url.searchParams.get("customerId")||"").trim(),bookingId=String(url.searchParams.get("bookingId")||"").trim();if(!providerId&&!customerId&&!bookingId)return json({error:"Sitting lifecycle reads require provider, customer or booking scope"},400);const db=await database(),actor=await resolveActor(request);requirePermission(actor,"bookings.view");if(providerId)await requireProviderOwnership(db,actor,providerId);if(customerId)await requireCustomerOwnership(db,actor,customerId);if(bookingId&&!hasPermission(actor.permissions,"bookings.manage")){const booking=await getSittingBooking(db,bookingId);if(!booking)return json({data:[]});try{await requireProviderOwnership(db,actor,String(booking.provider_id));}catch{await requireCustomerOwnership(db,actor,String(booking.customer_id));}}const rows=await listSittingBookings(db,{providerId:providerId||undefined,customerId:customerId||undefined,bookingId:bookingId||undefined});return json({data:rows});}catch(error){return authError(error,"Unable to load Sitting lifecycle");}}

export async function POST(request:Request){try{const body=await request.json() as Body,bookingId=String(body.bookingId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!bookingId||!action||!idempotencyKey)return json({error:"Booking, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request),booking=await getSittingBooking(db,bookingId);if(!booking)return json({error:"Sitting booking not found"},404);const providerId=String(booking.provider_id),customerId=String(booking.customer_id),staff=hasPermission(actor.permissions,"bookings.manage");if(action==="no_show"){requirePermission(actor,"bookings.manage");}else if(providerActions.has(action)){requirePermission(actor,"bookings.view");if(!staff)await requireProviderOwnership(db,actor,providerId);}else if(customerActions.has(action)){if(!staff){requirePermission(actor,"scheduling.book");await requireCustomerOwnership(db,actor,customerId);}}else return json({error:"Unsupported Sitting lifecycle action"},400);const result=await mutateSittingBooking(db,{bookingId,action,actorId:actor.email,idempotencyKey,reason:body.reason,carePlan:body.carePlan,careEventType:body.careEventType,detail:body.detail});await securityAudit(db,actor,`sitting.lifecycle.${action}`,"canonical_booking",bookingId,"completed",{providerId,customerId,staffOverride:staff,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented)});return json({data:result},String((result as Record<string,unknown>).status)==="ops_escalation"?202:200);}catch(error){return authError(error,"Unable to update Sitting lifecycle");}}