"use client";
import Link from"next/link";
import{useCallback,useEffect,useState}from"react";
import StaffModule from "../../../components/staff-workspace/StaffModule";
type Statement=Record<string,unknown>&{id:string;provider_id:string;earned_amount:number;adjustment_amount:number;payable_amount:number;status:string;policy_status:string};
type CommissionOrder=Record<string,unknown>&{booking_id:string;provider_id:string;service_code:string;order_amount:number;commission_mode:string;commission_value:number;commission_amount:number;commission_source:string;status:string;completed_at:number;due_at:number};
type Profile=Record<string,unknown>&{provider_id:string;engagement_model:string;default_commission_mode?:string;default_commission_value?:number};type Payout=Record<string,unknown>;
type QueueRow=Record<string,unknown>&{booking_id:string;provider_id:string;service_code:string;due_at:number;payable_amount:number;refund_adjustment:number;tds_amount:number;recovery_deduction:number;amount:number;status:string;statusLabel:string;blockedLabel:string|null;blocked_detail?:string|null;releasable:boolean};
type UpcomingRow=Record<string,unknown>&{booking_id:string;provider_id?:string|null;service_code?:string|null;due_at?:number|null;amount_preview:number;reason:string;reasonLabel:string;detail?:string|null};
type Recovery=Record<string,unknown>&{id:string;provider_id:string;booking_id:string;amount:number;recovered_amount:number};
type PayoutQueue={holdDays:number;queue:QueueRow[];upcoming:UpcomingRow[];recoveries:Recovery[];reconciliation:{ok:boolean;checked:number;mismatches:unknown[]};totals:{awaitingRelease:number;awaitingAmount:number;releasable:number;openRecoveryAmount:number}};
type Payload={statements:Statement[];payouts:Payout[];commission:{profiles:Profile[];orders:CommissionOrder[];payouts:Payout[];policy:Record<string,unknown>};payoutQueue?:PayoutQueue};
const EMPTY_QUEUE:PayoutQueue={holdDays:7,queue:[],upcoming:[],recoveries:[],reconciliation:{ok:true,checked:0,mismatches:[]},totals:{awaitingRelease:0,awaitingAmount:0,releasable:0,openRecoveryAmount:0}};
const rupees=(value:unknown)=>`₹${Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;const day=(value:unknown)=>value?new Date(Number(value)).toLocaleDateString("en-IN"):"Not known";
const breakdown=(r:QueueRow)=>[`Payable ${rupees(r.payable_amount)}`,Number(r.refund_adjustment)>0?`refund −${rupees(r.refund_adjustment)}`:"",Number(r.tds_amount)>0?`TDS −${rupees(r.tds_amount)}`:"",Number(r.recovery_deduction)>0?`earlier overpayment −${rupees(r.recovery_deduction)}`:""].filter(Boolean).join(" · ");
const card={background:"var(--staff-surface)",border:"1px solid var(--staff-line)",borderRadius:14};
export default function PartnerFinancePage(){const[data,setData]=useState<Payload>({statements:[],payouts:[],commission:{profiles:[],orders:[],payouts:[],policy:{}}}),[error,setError]=useState(""),[busy,setBusy]=useState(""),[providerId,setProviderId]=useState(""),[model,setModel]=useState<"full_time"|"commission">("commission"),[mode,setMode]=useState<"fixed"|"percent">("percent"),[value,setValue]=useState(""),[reason,setReason]=useState("Provider commercial terms configured"),[contact,setContact]=useState(""),[fund,setFund]=useState(""),[selected,setSelected]=useState<string[]>([]),[releaseReason,setReleaseReason]=useState(""),[notice,setNotice]=useState(""),[holdDraft,setHoldDraft]=useState(""),[holdReason,setHoldReason]=useState("");const payoutQueue=data.payoutQueue??EMPTY_QUEUE;const load=useCallback(async()=>{const r=await fetch("/api/partner-finance",{cache:"no-store"}),b=await r.json() as {data?:Payload;error?:string};if(!r.ok)throw new Error(b.error||"Partner Finance unavailable");if(b.data)setData(b.data);},[]);useEffect(()=>{let active=true;void fetch("/api/partner-finance",{cache:"no-store"}).then(async r=>{const b=await r.json() as {data?:Payload;error?:string};if(!r.ok)throw new Error(b.error||"Partner Finance unavailable");return b;}).then(b=>{if(active&&b.data)setData(b.data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Partner Finance unavailable")});return()=>{active=false}},[]);async function post(body:Record<string,unknown>){setBusy(String(body.bookingId||body.providerId||body.statementId||body.action));setError("");try{const r=await fetch("/api/partner-finance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||"Partner Finance action failed");await load()}catch(e){setError(e instanceof Error?e.message:"Partner Finance action failed")}finally{setBusy("")}}
async function release(bookingIds:string[]){if(!bookingIds.length)return;setBusy(bookingIds.join(","));setError("");setNotice("");try{const r=await fetch("/api/partner-finance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"release_provider_payout",bookingIds,reason:releaseReason.trim()||undefined})}),b=await r.json() as {error?:string;data?:{released:Array<{bookingId:string;amount:number;followUp?:string|null}>;refused:Array<{bookingId:string;error:string}>}};if(!r.ok)throw new Error(b.error||"Payout release failed");const done=b.data?.released.length??0,refused=b.data?.refused??[],followUps=(b.data?.released??[]).filter(x=>x.followUp);setNotice(`${done} payout${done===1?"":"s"} released to the sandbox payout queue.${followUps.length?` ${followUps.map(x=>`${x.bookingId}: ${x.followUp}`).join(" · ")}`:""}`);if(refused.length)setError(refused.map(x=>`${x.bookingId}: ${x.error}`).join(" · "));setSelected([]);await load()}catch(e){setError(e instanceof Error?e.message:"Payout release failed")}finally{setBusy("")}}
async function runQueue(){setNotice("");await post({action:"run_payout_queue"})}
async function saveHold(){await post({action:"set_payout_hold_days",holdDays:Number(holdDraft),reason:holdReason});setHoldDraft("");setHoldReason("")}
const toggle=(bookingId:string)=>setSelected(current=>current.includes(bookingId)?current.filter(id=>id!==bookingId):[...current,bookingId]);
async function saveProfile(){await post({action:"save_provider_profile",providerId,engagementModel:model,commissionMode:model==="commission"?mode:undefined,commissionValue:model==="commission"?Number(value):undefined,razorpayxContactId:contact||undefined,razorpayxFundAccountId:fund||undefined,reason})}
async function sendTestPayout(payoutId:string){setBusy(payoutId);setError("");try{const r=await fetch("/api/razorpayx-test-dispatch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({payoutId})}),b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||"RazorpayX TEST payout failed");await load()}catch(e){setError(e instanceof Error?e.message:"RazorpayX TEST payout failed")}finally{setBusy("")}}
async function override(o:CommissionOrder){const m=window.prompt("Commission mode: fixed or percent",o.commission_mode||"percent");if(m!=="fixed"&&m!=="percent")return;const v=Number(window.prompt("Commission value",String(o.commission_value||0)));if(!Number.isFinite(v))return;const why=window.prompt("Reason for order-level commission override","Order commercial exception approved");if(!why)return;await post({action:"override_order_commission",bookingId:o.booking_id,commissionMode:m,commissionValue:v,reason:why})}
return <StaffModule><main style={{minHeight:"100vh",background:"var(--staff-bg)",padding:28,fontFamily:"inherit",color:"var(--staff-text)"}}><div style={{maxWidth:1450,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,marginBottom:18}}><div><small style={{fontWeight:800,color:"var(--staff-primary)"}}>PAWSPACE FINANCE · PROVIDER PAYOUTS</small><h1 style={{margin:"7px 0"}}>Provider compensation & RazorpayX payout control</h1><p style={{margin:0,color:"var(--staff-muted)"}}>Full-time providers are never paid commission. Commission providers are paid {payoutQueue.holdDays} days after the service is completed: each payout is queued automatically and released with one Finance click.</p></div><Link href="/team/finance" style={{padding:10,background:"var(--staff-primary)",color:"var(--staff-on-primary)",borderRadius:10,textDecoration:"none"}}>Finance home</Link></header>{error&&<div style={{padding:12,background:"var(--staff-danger-bg)",borderRadius:10,marginBottom:12}}>{error}</div>}{notice&&<div role="status" style={{padding:12,background:"var(--staff-surface)",border:"1px solid var(--staff-line)",borderRadius:10,marginBottom:12}}>{notice}</div>}
<section style={{...card,overflow:"hidden",marginBottom:14}}><div style={{padding:15,borderBottom:"1px solid var(--staff-line)",display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><div><b>Provider payouts</b><small style={{display:"block",color:"var(--staff-muted)"}}>Paid {payoutQueue.holdDays} days after the service is completed, from the provider payable in the books. Refunds, TDS and earlier overpayments are taken off before release.</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button disabled={Boolean(busy)} onClick={()=>void runQueue()}>Check for due payouts now</button><button disabled={Boolean(busy)||selected.length===0} onClick={()=>void release(selected)}>Release selected ({selected.length})</button></div></div>
<div style={{padding:15,display:"grid",gridTemplateColumns:"repeat(4,minmax(150px,1fr))",gap:10,borderBottom:"1px solid var(--staff-line)"}} data-staff-grid="stats"><span>Ready to release<br/><b>{payoutQueue.totals.releasable}</b></span><span>Waiting in queue<br/><b>{payoutQueue.totals.awaitingRelease} · {rupees(payoutQueue.totals.awaitingAmount)}</b></span><span>Owed back by providers<br/><b>{rupees(payoutQueue.totals.openRecoveryAmount)}</b></span><span>Books check<br/><b>{payoutQueue.reconciliation.ok?"Provider payable matches the journal":`${payoutQueue.reconciliation.mismatches.length} booking(s) do not match the journal`}</b></span></div>
<div style={{padding:"10px 15px",borderBottom:"1px solid var(--staff-line)"}}><input style={{width:"100%"}} placeholder="Reason for release (optional)" value={releaseReason} onChange={e=>setReleaseReason(e.target.value)}/></div>
{payoutQueue.queue.length===0?<p style={{padding:18,color:"var(--staff-muted)"}}>No provider payouts are in the queue yet. A payout appears here {payoutQueue.holdDays} days after the service is completed.</p>:payoutQueue.queue.map(r=><article key={r.booking_id} style={{padding:15,borderBottom:"1px solid var(--staff-line)",display:"grid",gridTemplateColumns:"auto 2fr repeat(3,1fr) 1.4fr",gap:10,alignItems:"center"}} data-staff-grid="record"><input type="checkbox" aria-label={`Select payout for ${r.booking_id}`} disabled={!r.releasable||Boolean(busy)} checked={selected.includes(r.booking_id)} onChange={()=>toggle(r.booking_id)}/><div><strong>{r.provider_id}</strong><small style={{display:"block"}}>{r.booking_id} · {String(r.service_code||"").replaceAll("_"," ")}</small></div><span>Due<br/><b>{day(r.due_at)}</b></span><span>Amount<br/><b>{rupees(r.amount)}</b><small style={{display:"block"}}>{breakdown(r)}</small></span><span>Status<br/><b>{r.statusLabel}</b>{r.blocked_detail&&<small style={{display:"block"}}>{r.blocked_detail}</small>}</span><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{r.releasable&&<button disabled={Boolean(busy)} onClick={()=>void release([r.booking_id])}>Release payout</button>}</div></article>)}
{payoutQueue.upcoming.length>0&&<div style={{padding:15,borderTop:"1px solid var(--staff-line)"}}><b>Not queued yet</b>{payoutQueue.upcoming.map(u=><div key={u.booking_id} style={{padding:"8px 0",borderBottom:"1px solid var(--staff-line)",display:"flex",gap:10,flexWrap:"wrap"}}><span>{u.provider_id||"No provider"} · {u.booking_id}</span><span>Due {day(u.due_at)}</span><span>{rupees(u.amount_preview)}</span><b>{u.reasonLabel}</b>{u.detail&&<small>{u.detail}</small>}</div>)}</div>}
{payoutQueue.recoveries.length>0&&<div style={{padding:15,borderTop:"1px solid var(--staff-line)"}}><b>Refunds after payout, to take off the next payout</b>{payoutQueue.recoveries.map(x=><div key={x.id} style={{padding:"8px 0",borderBottom:"1px solid var(--staff-line)"}}>{x.provider_id} · {x.booking_id} · {rupees(Number(x.amount)-Number(x.recovered_amount||0))} still to recover</div>)}</div>}
<div style={{padding:15,borderTop:"1px solid var(--staff-line)",display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><span>Payout days after completion (every service): <b>{payoutQueue.holdDays}</b></span><input style={{width:90}} type="number" min={1} max={60} placeholder="Days" value={holdDraft} onChange={e=>setHoldDraft(e.target.value)}/><input style={{flex:"1 1 220px"}} placeholder="Reason for the change" value={holdReason} onChange={e=>setHoldReason(e.target.value)}/><button disabled={Boolean(busy)||!holdDraft||holdReason.trim().length<8} onClick={()=>void saveHold()}>Change payout days</button></div></section>
<section style={{...card,padding:16,marginBottom:14}}><h2 style={{marginTop:0}}>Provider commercial profile</h2><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(160px,1fr))",gap:10}} data-staff-grid="stats"><input placeholder="Provider ID" value={providerId} onChange={e=>setProviderId(e.target.value)}/><select value={model} onChange={e=>setModel(e.target.value as "full_time"|"commission")}><option value="full_time">Direct contract · full time</option><option value="commission">Commission based</option></select><select value={mode} disabled={model!=="commission"} onChange={e=>setMode(e.target.value as "fixed"|"percent")}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select><input disabled={model!=="commission"} type="number" placeholder={mode==="percent"?"Commission %":"Fixed ₹"} value={value} onChange={e=>setValue(e.target.value)}/><input placeholder="RazorpayX contact ID (UAT)" value={contact} onChange={e=>setContact(e.target.value)}/><input placeholder="RazorpayX fund account ID (UAT)" value={fund} onChange={e=>setFund(e.target.value)}/><input style={{gridColumn:"span 2"}} placeholder="Configuration reason" value={reason} onChange={e=>setReason(e.target.value)}/></div><button style={{marginTop:10}} disabled={!providerId||Boolean(busy)} onClick={()=>void saveProfile()}>Save provider terms</button><p style={{fontSize:14,color:"var(--staff-muted)"}}>RazorpayX is orchestrated in sandbox/UAT only here. Live-money payout remains separately gated. No RazorpayX/production payout is executed from this workspace.</p></section>
<section style={{...card,overflow:"hidden",marginBottom:14}}><div style={{padding:15,borderBottom:"1px solid var(--staff-line)"}}><b>Older approval steps</b><small style={{display:"block",color:"var(--staff-muted)"}}>Only bookings that started on the older confirm-and-approve steps, or have no provider payable in the books, stay here.</small></div>{data.commission.orders.length===0?<p style={{padding:18,color:"var(--staff-muted)"}}>No bookings are waiting in the older approval steps.</p>:data.commission.orders.map(o=><article key={o.booking_id} style={{padding:15,borderBottom:"1px solid var(--staff-line)",display:"grid",gridTemplateColumns:"2fr repeat(5,1fr) 2fr",gap:10,alignItems:"center"}} data-staff-grid="record"><div><strong>{o.provider_id}</strong><small style={{display:"block"}}>{o.booking_id} · {o.service_code}</small></div><span>Order<br/><b>₹{Number(o.order_amount).toLocaleString("en-IN")}</b></span><span>Commission<br/><b>₹{Number(o.commission_amount).toLocaleString("en-IN")}</b><small style={{display:"block"}}>{o.commission_mode} {o.commission_value}</small></span><span>Source<br/><b>{String(o.commission_source).replaceAll("_"," ")}</b></span><span>Due<br/><b>{new Date(Number(o.due_at)).toLocaleDateString("en-IN")}</b></span><span>Status<br/><b>{String(o.status).replaceAll("_"," ")}</b></span><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{["configuration_required","pending_confirmation"].includes(o.status)&&<button disabled={Boolean(busy)} onClick={()=>void override(o)}>Override</button>}{o.status==="pending_confirmation"&&<button disabled={Boolean(busy)} onClick={()=>void post({action:"confirm_order_commission",bookingId:o.booking_id})}>Confirm</button>}{o.status==="awaiting_approval_1"&&<button disabled={Boolean(busy)} onClick={()=>void post({action:"approve_order_commission_level_1",bookingId:o.booking_id})}>Approval 1</button>}{o.status==="awaiting_approval_2"&&<button disabled={Boolean(busy)} onClick={()=>void post({action:"approve_order_commission_level_2",bookingId:o.booking_id,idempotencyKey:`razorpayx-${o.booking_id}`})}>Approval 2</button>}</div></article>)}</section>
<section style={{...card,padding:15,marginBottom:14}}><b>RazorpayX Test Mode payout queue</b><p style={{fontSize:14,color:"var(--staff-muted)"}}>Only approved sandbox payouts can be sent. This action calls RazorpayX Test Mode and cannot use live credentials or move real money.</p><div style={{marginTop:8}}>{data.commission.payouts.length===0?"None":data.commission.payouts.map(p=><div key={String(p.id)} style={{padding:"8px 0",borderBottom:"1px solid var(--staff-line)",display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><span>{String(p.id)} · {String(p.provider_id)} · ₹{Number(p.amount||0).toLocaleString("en-IN")} · {String(p.status)} · due {new Date(Number(p.due_at)).toLocaleDateString("en-IN")}</span>{["queued_sandbox","retry_pending_sandbox"].includes(String(p.status))&&<button disabled={Boolean(busy)} onClick={()=>void sendTestPayout(String(p.id))}>Send TEST payout</button>}{Boolean(p.provider_reference)&&<small>Provider ref {String(p.provider_reference)}</small>}</div>)}</div></section>
<section style={{...card,overflow:"hidden"}}><div style={{padding:15,borderBottom:"1px solid var(--staff-line)"}}><b>Legacy settlement statements</b></div>{data.statements.length===0?<p style={{padding:18,color:"var(--staff-muted)"}}>No legacy settlement rows.</p>:data.statements.map(s=><article key={s.id} style={{padding:12,borderBottom:"1px solid var(--staff-line)"}}>{s.provider_id} · ₹{Number(s.payable_amount).toLocaleString("en-IN")} · {s.status} · {s.policy_status}</article>)}</section></div></main></StaffModule>}
