import {governedJsonError} from "../../../lib/governed-http-error";
import {listTrainingProviderNotifications} from '../../../lib/training-workflow-notifications';
import {trainingListReadback} from "../../../lib/training-list-readback";
import{authError,authFailure,database,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission,maskName}from"../../../lib/platform-security";
import{withLifecycleMutationLock}from"../../../lib/lifecycle-mutation-lock";
import{getTrainingSession,isTerminalTrainingProgramme,listTrainerSessions,mutateTrainingSession,type TrainingSessionAction,type TrainingReport}from"../../../lib/training-session-lifecycle";
import{projectTrainerSession}from"../../../lib/training-provider-projection";
import{tryQualifyLinkedReferral}from"../../../lib/referral-booking-governance";
type Body={sessionId?:string;providerId?:string;action?:TrainingSessionAction;idempotencyKey?:string;reason?:string;report?:TrainingReport;newStart?:string;newEnd?:string;newProviderId?:string;latitude?:number;longitude?:number;ownerHandoverMinutes?:number;ownerHandoverCompleted?:boolean;accuracyMeters?:number;simulatedArrival?:{approvalId:string;reason:string}};
const json=(value:unknown,status=200)=>Response.json(value,{status});
const staffActions=new Set<TrainingSessionAction>(["reschedule","replace_provider","cancel_session"]);
async function trainingSessionError(error:unknown){if(error instanceof Response&&error.status===409){let message="";try{message=await error.clone().text();}catch{}if(message==="Trainer roster availability is not configured; cannot verify the trainer works this window"||/^Trainer has no roster availability covering \d{4}-\d{2}-\d{2} in this zone for the requested window$/.test(message))return authFailure("Trainer roster unavailable",409);if(/^Provider schedule conflicts with reservation .+ including travel buffer$/.test(message))return authFailure("Trainer schedule conflicts with travel buffer",409);}return authError(error,"Unable to update Training session");}

export async function GET(request:Request){try{const providerId=String(new URL(request.url).searchParams.get("providerId")||"").trim();if(!providerId)return json({error:"Trainer provider ID is required"},400);const db=await database();const actor=await resolveActor(request);requirePermission(actor,"bookings.view");await requireProviderOwnership(db,actor,providerId);const sessions=await listTrainerSessions(db,providerId);const readback=await trainingListReadback(db,sessions,providerId,{homework:true});return json({data:await Promise.all(sessions.map(async(item:Record<string,unknown>)=>({...projectTrainerSession({...item,customer_name:maskName(String(item.customer_name||"Customer"))}),assignmentOffer:readback.assignments.get(String(item.id)),homeworkReceipt:readback.homeworkReceipts.get(String(item.id))}))),notifications:await listTrainingProviderNotifications(db,providerId)});}catch(error){return authError(error,"Unable to load Training sessions");}}

export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Cross-origin Training action blocked'},403);const body=await request.json() as Body,sessionId=String(body.sessionId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!sessionId||!action||!idempotencyKey)return json({error:"Session, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request);const session=await getTrainingSession(db,sessionId);if(!session)return json({error:"Training session not found"},404);const bookingId=String(session.booking_id),staff=hasPermission(actor.permissions,"bookings.manage");if(staffActions.has(action)){requirePermission(actor,"bookings.manage");}else{requirePermission(actor,"bookings.view");if(!staff)await requireProviderOwnership(db,actor,String(session.provider_id));}
 const result=await withLifecycleMutationLock(db,{bookingId,actorId:actor.email,action},async()=>{const mutated=await mutateTrainingSession(db,{sessionId,action,actorId:actor.email,idempotencyKey,reason:body.reason,report:body.report,newStart:body.newStart,newEnd:body.newEnd,newProviderId:body.newProviderId,latitude:body.latitude,longitude:body.longitude,ownerHandoverMinutes:body.ownerHandoverMinutes,ownerHandoverCompleted:body.ownerHandoverCompleted,accuracyMeters:body.accuracyMeters,simulatedArrival:body.simulatedArrival,trustedRequest:request,staffOverride:staff});if(action==="complete"&&isTerminalTrainingProgramme(((mutated as Record<string,unknown>).programme as Record<string,unknown>|undefined)?.status)){const completion=await db.prepare("UPDATE canonical_bookings SET status='completed',updated_at=? WHERE id=? AND status!='cancelled'").bind(Date.now(),bookingId).run();if(Number((completion as {meta?:{changes?:number}})?.meta?.changes||0)!==1)throw governedJsonError({error:"This Training booking changed while the session was being completed, so nothing was written. Reload the booking and complete it again."},409);}return mutated;});let referral:unknown={applicable:false,status:"not_applicable"};if(action==="complete"&&isTerminalTrainingProgramme(((result as Record<string,unknown>).programme as Record<string,unknown>|undefined)?.status)){try{referral=await tryQualifyLinkedReferral(db,{bookingId,actorId:actor.email});}catch(error){referral={applicable:true,status:"review_required",reason:error instanceof Error?error.message:"Referral qualification requires review"};}}
 await securityAudit(db,actor,`training.session.${action}`,"training_session",sessionId,"completed",{bookingId,programmeId:session.programme_id,providerId:session.provider_id,staffOverride:staff,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented),referral});return json({data:result,referral});}catch(error){return trainingSessionError(error);}}
