import{authError,authFailure,database,requirePermission,requireProviderOwnership,resolveActor,securityAudit}from"../../../lib/server-auth";
import{hasPermission,maskName}from"../../../lib/platform-security";
import{getTrainingSession,isTerminalTrainingProgramme,listTrainerSessions,mutateTrainingSession,type TrainingSessionAction,type TrainingReport}from"../../../lib/training-session-lifecycle";
import{tryQualifyLinkedReferral}from"../../../lib/referral-booking-governance";
import{resolveServiceCompletionFinance}from"../../../lib/service-completion-finance";
type Body={sessionId?:string;providerId?:string;action?:TrainingSessionAction;idempotencyKey?:string;reason?:string;report?:TrainingReport;newStart?:string;newEnd?:string;newProviderId?:string;latitude?:number;longitude?:number;ownerHandoverMinutes?:number};
const json=(value:unknown,status=200)=>Response.json(value,{status});
const staffActions=new Set<TrainingSessionAction>(["reschedule","replace_provider","cancel_session"]);
async function trainingSessionError(error:unknown){if(error instanceof Response&&error.status===409){let message="";try{message=await error.clone().text();}catch{}if(message==="Trainer roster availability is not configured; cannot verify the trainer works this window"||/^Trainer has no roster availability covering \d{4}-\d{2}-\d{2} in this zone for the requested window$/.test(message))return authFailure("Trainer roster unavailable",409);if(/^Provider schedule conflicts with reservation .+ including travel buffer$/.test(message))return authFailure("Trainer schedule conflicts with travel buffer",409);}return authError(error,"Unable to update Training session");}

export async function GET(request:Request){try{const providerId=String(new URL(request.url).searchParams.get("providerId")||"").trim();if(!providerId)return json({error:"Trainer provider ID is required"},400);const db=await database();const actor=await resolveActor(request);requirePermission(actor,"bookings.view");await requireProviderOwnership(db,actor,providerId);const sessions=await listTrainerSessions(db,providerId);return json({data:sessions.map((item:Record<string,unknown>)=>({...item,customer_name:maskName(String(item.customer_name||"Customer"))}))});}catch(error){return authError(error,"Unable to load Training sessions");}}

export async function POST(request:Request){try{const body=await request.json() as Body,sessionId=String(body.sessionId||"").trim(),action=body.action,idempotencyKey=String(body.idempotencyKey||"").trim();if(!sessionId||!action||!idempotencyKey)return json({error:"Session, action and idempotency key are required"},400);const db=await database(),actor=await resolveActor(request);const session=await getTrainingSession(db,sessionId);if(!session)return json({error:"Training session not found"},404);const staff=hasPermission(actor.permissions,"bookings.manage");if(staffActions.has(action)){requirePermission(actor,"bookings.manage");}else{requirePermission(actor,"bookings.view");if(!staff)await requireProviderOwnership(db,actor,String(session.provider_id));}
 const result=await mutateTrainingSession(db,{sessionId,action,actorId:actor.email,idempotencyKey,reason:body.reason,report:body.report,newStart:body.newStart,newEnd:body.newEnd,newProviderId:body.newProviderId,latitude:body.latitude,longitude:body.longitude,ownerHandoverMinutes:body.ownerHandoverMinutes,staffOverride:staff});let referral:unknown={applicable:false,status:"not_applicable"};let finance:unknown=null;if(action==="complete"&&isTerminalTrainingProgramme(((result as Record<string,unknown>).programme as Record<string,unknown>|undefined)?.status)){const completedAt=Date.now();finance=await resolveServiceCompletionFinance(db,{bookingId:String(session.booking_id),actorId:actor.email,completedAt});const transition=await db.prepare("UPDATE canonical_bookings SET status='completed',updated_at=? WHERE id=? AND status!='cancelled' AND status!='completed'").bind(completedAt,session.booking_id).run();if(Number(transition?.meta?.changes||0)===0){const current=await db.prepare("SELECT status FROM canonical_bookings WHERE id=?").bind(session.booking_id).first<{status:string}>();if(String(current?.status||"")!=="completed")throw new Response("Training booking changed concurrently before completion could commit",{status:409});}try{referral=await tryQualifyLinkedReferral(db,{bookingId:String(session.booking_id),actorId:actor.email});}catch(error){referral={applicable:true,status:"review_required",reason:error instanceof Error?error.message:"Referral qualification requires review"};}}
 await securityAudit(db,actor,`training.session.${action}`,"training_session",sessionId,"completed",{bookingId:session.booking_id,programmeId:session.programme_id,providerId:session.provider_id,staffOverride:staff,duplicatePrevented:Boolean((result as Record<string,unknown>).duplicatePrevented),referral,finance});return json({data:result,referral,finance});}catch(error){return trainingSessionError(error);}}
