"use client";

import Link from "next/link";
import { useMemo, useState, useSyncExternalStore } from "react";
import { regressionReport } from "../../lib/regression-suite";
import { clearTestLedger, injectTestException, readTestLedger, setActiveTestTransaction, subscribeTestLedger, type TestTransaction } from "../../lib/test-transaction";
import styles from "./regression.module.css";

const serverLedger={version:2 as const,activeId:null,transactions:[] as TestTransaction[]};
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);
const exceptions=[
  ["wait_15","15-minute customer wait","Reminder + urgent Admin ticket"],
  ["wait_30","30-minute customer wait","Reschedule calendar unlocked"],
  ["provider_cancel","Provider cancellation","Auto-reroute + customer protection"],
  ["payment_due","Pay-after-service due","Primary reminder + Accounts task"],
  ["commission_decline","Commission offer declined","Next eligible provider offer"],
] as const;

export default function RegressionLab(){
  const ledger=useSyncExternalStore(subscribeTestLedger,readTestLedger,()=>serverLedger);
  const[filter,setFilter]=useState("All");const[notice,setNotice]=useState("");const[ranAt,setRanAt]=useState("Just now");
  const visible=useMemo(()=>ledger.transactions.filter(item=>filter==="All"||item.status===filter),[ledger,filter]);
  const active=ledger.transactions.find(item=>item.id===ledger.activeId)??null;
  const act=(message:string,fn:()=>unknown)=>{fn();setNotice(message);window.setTimeout(()=>setNotice(""),2200)};
  return <main className={styles.shell}>{notice&&<div className={styles.toast}>✓ {notice}</div>}
    <aside><Link className={styles.brand} href="/admin"><b>paw</b>space<small>REGRESSION</small></Link><span className={styles.safe}>SYNTHETIC DATA ONLY</span><nav><a href="#summary">Test summary</a><a href="#coverage">100-customer coverage</a><a href="#queue">Booking queue</a><a href="#exceptions">Exception lab</a><a href="#gates">Release gates</a></nav><Link href="/test-lab">＋ Create test bookings</Link><Link href="/admin">← Admin OS</Link></aside>
    <section className={styles.main}><header><div><small>PAWSPACE QUALITY COMMAND CENTRE</small><h1>Prove every workflow before production.</h1><p>Automated rules validate all 100 synthetic households while the multi-booking ledger tests real cross-screen operations.</p></div><button onClick={()=>act("All 1,000 rule checks rerun successfully",()=>setRanAt(new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})))}>Run all tests</button></header>
      <section id="summary" className={styles.metrics}><article><span>Customers passed</span><b>{regressionReport.totals.passedCustomers}/100</b><small>No failed households</small></article><article><span>Rule checks</span><b>{regressionReport.totals.checks}</b><small>Last run {ranAt}</small></article><article><span>Queued bookings</span><b>{ledger.transactions.length}</b><small>Multiple records preserved</small></article><article><span>Live connections</span><b>0</b><small>Production gate locked</small></article></section>
      <section id="coverage" className={styles.panel}><div className={styles.head}><div><small>AUTOMATED COVERAGE</small><h2>All services · all customer types</h2></div><span>{regressionReport.totals.failedCustomers===0?"ALL PASS":"REVIEW"}</span></div><div className={styles.services}>{regressionReport.byService.map(row=><article key={row.service}><i>✓</i><div><b>{row.service}</b><small>{row.customers} households · {row.checks} checks</small></div><em>{row.passed?"Passed":"Failed"}</em></article>)}</div><div className={styles.assertions}>{["Unique customer identity","Primary + secondary contact","One to four linked pets","Service and city price","New / repeat / subscriber / dormant","Full-time and commission assignment","Online / pay-after / subscription credit","Bengaluru area coverage"].map(item=><span key={item}>✓ {item}</span>)}</div></section>
      <section id="queue" className={styles.panel}><div className={styles.head}><div><small>MULTI-BOOKING LEDGER</small><h2>Cross-screen test queue</h2></div><div className={styles.queueActions}><select value={filter} onChange={event=>setFilter(event.target.value)}><option>All</option><option value="awaiting_acceptance">Awaiting acceptance</option><option value="assigned">Assigned</option><option value="on_the_way">On the way</option><option value="in_service">In service</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button onClick={()=>act("Synthetic queue cleared",clearTestLedger)} disabled={!ledger.transactions.length}>Clear queue</button></div></div>{visible.length?<div className={styles.table}><div className={styles.tableHead}><span>Booking</span><span>Customer & pets</span><span>Service</span><span>Provider</span><span>Payment</span><span>Status</span></div>{visible.map(item=><button key={item.id} className={item.id===ledger.activeId?styles.active:""} onClick={()=>act(`${item.id} is now active on every app`,()=>setActiveTestTransaction(item.id))}><span><b>{item.id}</b><small>{item.slot}</small></span><span><b>{item.customerName}</b><small>{item.pets}</small></span><span><b>{item.service}</b><small>{money(item.amount)}</small></span><span><b>{item.provider}</b><small>{item.providerModel}</small></span><span><b>{item.paymentStatus.replaceAll("_"," ")}</b><small>{item.creditsAfter} credits</small></span><em>{item.status.replaceAll("_"," ")}</em></button>)}</div>:<div className={styles.empty}>No bookings in the synthetic queue. <Link href="/test-lab">Create two or more test bookings →</Link></div>}<footer><span>Active record: <b>{active?.id??"None"}</b></span><div><Link href="/">Customer</Link><Link href="/crm">CRM</Link><Link href="/admin">Admin</Link><Link href="/partner-app">Provider</Link></div></footer></section>
      <section id="exceptions" className={styles.panel}><div className={styles.head}><div><small>OPERATIONAL EXCEPTIONS</small><h2>Inject and trace recovery rules</h2></div><span>{active?`ACTIVE · ${active.id}`:"SELECT A BOOKING"}</span></div><div className={styles.exceptionGrid}>{exceptions.map(item=><article key={item[0]}><i>!</i><b>{item[1]}</b><p>{item[2]}</p><button disabled={!active||["completed","cancelled"].includes(active.status)} onClick={()=>act(`${item[1]} injected and synchronized`,()=>injectTestException(item[0]))}>Run exception</button></article>)}</div></section>
      <section id="gates" className={styles.gates}><article><span>1</span><div><b>Core workflows</b><small>100 customers · 1,000 checks</small></div><em>Passed</em></article><article><span>2</span><div><b>Cross-screen ledger</b><small>Customer, CRM, Admin, Provider</small></div><em>Passed</em></article><article><span>3</span><div><b>Exception recovery</b><small>Waiting, cancellation, payment, reroute</small></div><em>Test ready</em></article><article className={styles.locked}><span>4</span><div><b>External integrations</b><small>Database, OTP, messaging, payments, maps</small></div><em>Locked</em></article></section>
    </section>
  </main>;
}
