"use client";

import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import{loadBoardingOps,updateBoardingOps,type BoardingOpsSnapshot,type BoardingOpsStay}from"../../../../lib/boarding-ops-client";

const label=(value:unknown)=>String(value||"not recorded").replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const when=(value:unknown)=>{const date=new Date(String(value||""));return Number.isFinite(date.getTime())?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(date):"Not scheduled";};
const money=(value:unknown)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value||0));

export default function BoardingOperationsPage(){
 const[snapshot,setSnapshot]=useState<BoardingOpsSnapshot|null>(null),[selectedId,setSelectedId]=useState(""),[filter,setFilter]=useState<"attention"|"all"|"clear">("attention"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[reason,setReason]=useState("Verified replacement selected by Operations"),[note,setNote]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const data=await loadBoardingOps();setSnapshot(data);setSelectedId(current=>current&&data.stays.some(item=>item.id===current)?current:data.stays.find(item=>item.exceptionFlags.length)?.id??data.stays[0]?.id??"");}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load Boarding Operations");}finally{setLoading(false);}};
 useEffect(()=>{let active=true;void loadBoardingOps().then(data=>{if(!active)return;setSnapshot(data);setSelectedId(data.stays.find(item=>item.exceptionFlags.length)?.id??data.stays[0]?.id??"");}).catch(problem=>{if(active)setError(problem instanceof Error?problem.message:"Unable to load Boarding Operations");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const visible=useMemo(()=>{const stays=snapshot?.stays??[];return stays.filter(item=>filter==="all"||(filter==="clear"?item.exceptionFlags.length===0:item.exceptionFlags.length>0));},[snapshot,filter]);
 const selected=(snapshot?.stays.find(item=>item.id===selectedId)??visible[0]) as BoardingOpsStay|undefined;
 const run=async(action:"assign_replacement"|"close_recovery"|"add_note",providerId?:string)=>{if(!selected)return;setBusy(action+(providerId||""));setError("");setMessage("");try{const result=await updateBoardingOps({stayId:selected.id,action,idempotencyKey:`boarding:${selected.id}:ops:${action}:${providerId||crypto.randomUUID()}`,providerId,reason,note});setMessage(`${label(action)} · ${label(result.status)}`);if(action==="add_note")setNote("");await load();}catch(problem){setError(problem instanceof Error?problem.message:"Boarding Operations action failed");}finally{setBusy("");}};
 return <main style={{maxWidth:1480,margin:"0 auto",padding:24,fontFamily:"system-ui",display:"grid",gap:18}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><Link href="/team/operations/bookings">← Booking Command Center</Link><p style={{fontSize:12,fontWeight:800,letterSpacing:1}}>TEAM OS · BOARDING · UAT CONTROL</p><h1 style={{margin:"4px 0"}}>Boarding Operations exception queue</h1><p>One canonical queue for host recovery, care incidents, finance review, proof/media blocks and stay timing exceptions.</p></div><button onClick={()=>void load()}>↻ Refresh</button></header>
  {snapshot&&<section style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(120px,1fr))",gap:10}}>{[["Total",snapshot.metrics.total],["Needs attention",snapshot.metrics.needsAttention],["Clear",snapshot.metrics.clear],["Recovery",snapshot.metrics.recovery],["Open incidents",snapshot.metrics.openIncidents],["Finance review",snapshot.metrics.financeReview],["Media blocked",snapshot.metrics.mediaBlocked]].map(([name,value])=><article key={String(name)} style={{border:"1px solid #ddd",borderRadius:14,padding:14}}><small>{name}</small><strong style={{display:"block",fontSize:24}}>{value}</strong></article>)}</section>}
  <section style={{display:"flex",gap:8}}>{(["attention","all","clear"] as const).map(item=><button key={item} onClick={()=>setFilter(item)} disabled={filter===item}>{label(item)}</button>)}</section>
  {loading&&<p>Loading canonical Boarding exception state…</p>}{error&&<p role="alert">{error}</p>}{message&&<p>{message}</p>}
  {!loading&&snapshot&&<section style={{display:"grid",gridTemplateColumns:"minmax(360px,.8fr) minmax(560px,1.2fr)",gap:18,alignItems:"start"}}>
   <section style={{border:"1px solid #ddd",borderRadius:16,overflow:"hidden"}}>{visible.length?visible.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} style={{display:"grid",width:"100%",textAlign:"left",padding:14,border:0,borderBottom:"1px solid #eee",background:selected?.id===item.id?"#f2f2f2":"white",gap:4}}><strong>{item.booking_id} · {item.customer_name||item.customer_id}</strong><span>{label(item.status)} · {item.provider_name||item.host_provider_id}</span><small>{when(item.check_in_at)} → {when(item.check_out_at)}</small><span>{item.exceptionFlags.length?item.exceptionFlags.map(label).join(" · "):"Clear"}</span></button>):<p style={{padding:18}}>No stays in this view.</p>}</section>
   <section style={{display:"grid",gap:14}}>{selected?<>
    <article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><small>{label(selected.priority)} PRIORITY</small><h2>{selected.booking_id}</h2><p>{selected.customer_name||selected.customer_id} · {selected.package_name} · {selected.provider_name||selected.host_provider_id}</p><p>{when(selected.check_in_at)} → {when(selected.check_out_at)}</p><p>Stay {label(selected.status)} · Booking {label(selected.booking_status)} · Payment {label(selected.payment_status)}</p><p><b>Exceptions:</b> {selected.exceptionFlags.length?selected.exceptionFlags.map(label).join(" · "):"None"}</p></article>
    {selected.exceptionFlags.includes("host_recovery")&&<article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Host recovery</h2><p>The same booking ID and paid stay window are preserved. Only verified exact-stay candidates can be offered.</p><label style={{display:"grid",gap:4}}>Operations reason<textarea value={reason} onChange={event=>setReason(event.target.value)} /></label><div style={{display:"grid",gap:8,marginTop:12}}>{selected.replacementCandidates.length?selected.replacementCandidates.map(candidate=><div key={candidate.providerId} style={{border:"1px solid #eee",borderRadius:12,padding:12,display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{candidate.name}</strong><div>{candidate.area} · {candidate.rating.toFixed(1)} ★ · quality {candidate.qualityScore}</div><small>Available {candidate.availableGuestPets}/{candidate.maxGuestPets} pets · {candidate.oneFamilyOnly?"one family":"shared capacity"}</small></div><button disabled={busy.startsWith("assign_replacement")} onClick={()=>void run("assign_replacement",candidate.providerId)}>Offer replacement</button></div>):<p>No eligible replacement host is available for this exact stay.</p>}</div>{selected.status==="confirmed"&&selected.recovery?.replacement_provider_id&&<button style={{marginTop:12}} disabled={busy==="close_recovery"} onClick={()=>void run("close_recovery")}>Close accepted recovery</button>}</article>}
    <article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Care incidents</h2>{selected.incidents.length?selected.incidents.map((incident,index)=><div key={String(incident.id||index)} style={{borderTop:index?"1px solid #eee":"none",paddingTop:index?10:0,marginTop:index?10:0}}><b>{label(incident.severity)} · {label(incident.status)}</b><p>{String(incident.summary||"")}</p><small>Ops {label(incident.ops_status)} · customer acknowledgement {incident.customer_acknowledged_at?"recorded":"pending"}</small></div>):<p>No incidents.</p>}<p><small>Incident resolution remains in the canonical Boarding proof workflow; this queue does not duplicate that authority.</small></p></article>
    <article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Finance & settlement</h2><p>Booking value: {money((selected as unknown as Record<string,unknown>).total_amount)} · Cancellation: {label(selected.cancellation?.status)} · Date change: {label(selected.dateChange?.status)}</p><p>Refunds: {selected.refunds.length?selected.refunds.map(item=>`${money(item.amount)} ${label(item.status)}`).join(" · "):"None"}</p><p>Settlement: {selected.settlement?`${label(selected.settlement.approval_status)} · payout ${label(selected.settlement.payout_status)} · tax ${label(selected.settlement.tax_status)}`:"Not prepared"}</p><small>Refund decisions, settlement amounts and tax remain in canonical Finance governance; this queue never invents them.</small></article>
    <article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Proof/media</h2>{selected.media.length?selected.media.map((item,index)=><p key={String(item.id||index)}><code>{String(item.id)}</code> · {label(item.purpose)} · scan {label(item.scan_status)} · access {label(item.access_status)}</p>):<p>No Boarding proof media.</p>}<small>Object storage and malware-scanner adapters remain disconnected.</small></article>
    <article style={{border:"1px solid #ddd",borderRadius:16,padding:18}}><h2>Operations note</h2><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Record an auditable operational note" style={{width:"100%",minHeight:80}}/><button disabled={busy==="add_note"||note.trim().length<5} onClick={()=>void run("add_note")}>Add note</button>{selected.notes.map((item,index)=><p key={String(item.id||index)}><small>{when(item.created_at)} · {String(item.actor_id)}</small><br/>{String(item.note)}</p>)}</article>
   </>:<p>Select a Boarding stay.</p>}</section>
  </section>}
  {snapshot&&<footer style={{borderTop:"1px solid #ddd",paddingTop:16}}><b>Gate 5: {label(snapshot.readiness.engineeringGate)}</b><p>Production ready: {String(snapshot.readiness.productionReady)}. Storage {snapshot.readiness.externalDependencies.objectStorage}; scanner {snapshot.readiness.externalDependencies.malwareScanner}; WhatsApp/push {snapshot.readiness.externalDependencies.whatsappPush}; payments {snapshot.readiness.externalDependencies.payments}; tax {snapshot.readiness.externalDependencies.tax}; host payout {snapshot.readiness.externalDependencies.hostPayout}.</p></footer>}
 </main>;
}
