import {acceptTrainingBroadcast,listTrainingBroadcastOffers,respondTrainingBroadcast,retryTrainingBroadcast} from '../../../lib/training-broadcast-integration';
import {authError,database,requirePermission,requireProviderOwnership,resolveActor} from '../../../lib/server-auth';
import {respondTrainingOffer,runTrainingOfferExpirySweep,trainingAssignmentOffer} from '../../../lib/training-assignment-dispatch';
export async function GET(request:Request){try{const actor=await resolveActor(request);requirePermission(actor,'bookings.view');const url=new URL(request.url),bookingId=url.searchParams.get('bookingId')||'',providerId=url.searchParams.get('providerId')||'';if(!providerId)return Response.json({error:'Training booking and provider are required'},{status:400});const db=await database();await requireProviderOwnership(db,actor,providerId);return Response.json({data:bookingId?await trainingAssignmentOffer(db,bookingId,providerId):await listTrainingBroadcastOffers(db,providerId)},{headers:{'cache-control':'no-store'}});}catch(error){return authError(error,'Unable to read Training assignment');}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Cross-origin Training response blocked'},{status:403});const body=await request.json() as Record<string,unknown>,actor=await resolveActor(request),db=await database();if(body.action==='expire_due'){requirePermission(actor,'bookings.manage');return Response.json({data:await runTrainingOfferExpirySweep(db)});}if(body.action==='retry_broadcast'){requirePermission(actor,'bookings.manage');const bookingId=String(body.bookingId||''),idempotencyKey=String(body.idempotencyKey||'');if(!bookingId||!idempotencyKey||idempotencyKey.length>160)return Response.json({error:'Booking and stable response key required'},{status:400});return Response.json({data:await retryTrainingBroadcast(db,{bookingId,idempotencyKey,reason:String(body.reason||''),actorId:actor.email})});}if(body.action==='accept'||body.bookingId){
 const bookingId=String(body.bookingId||''),sessionId=String(body.sessionId||''),providerId=String(body.providerId||''),idempotencyKey=String(body.idempotencyKey||'');
 if(!bookingId||!sessionId||!providerId||!idempotencyKey||idempotencyKey.length>160||!['accept','decline','timeout'].includes(String(body.action)))return Response.json({error:'Booking, session, provider, action and stable response key required'},{status:400});
 if(body.action==='timeout')requirePermission(actor,'bookings.manage');else{requirePermission(actor,'bookings.view');await requireProviderOwnership(db,actor,providerId);}
 const identity={bookingId,sessionId,providerId,idempotencyKey,actorId:actor.email};
 return Response.json({data:body.action==='accept'?await acceptTrainingBroadcast(db,identity):await respondTrainingBroadcast(db,{...identity,action:body.action as 'decline'|'timeout',reason:String(body.reason||'')})});
 }if(!['decline','timeout'].includes(String(body.action)))return Response.json({error:'Training decline or timeout action required'},{status:400});const sessionId=String(body.sessionId||''),providerId=String(body.providerId||''),idempotencyKey=String(body.idempotencyKey||''),expectedAttemptNo=Number(body.expectedAttemptNo);if(!sessionId||!providerId||!idempotencyKey||idempotencyKey.length>160||!Number.isInteger(expectedAttemptNo)||expectedAttemptNo<1)return Response.json({error:'Session, provider, expected attempt and stable response key required'},{status:400});if(body.action==='decline'){requirePermission(actor,'bookings.view');await requireProviderOwnership(db,actor,providerId);const session=await db.prepare("SELECT s.provider_id FROM training_sessions s WHERE s.id=? AND (s.provider_id=? OR EXISTS(SELECT 1 FROM training_assignment_attempts a WHERE a.booking_id=s.booking_id AND a.provider_id=?))").bind(sessionId,providerId,providerId).first<{provider_id:string}>();if(!session)return Response.json({error:'Training session ownership denied'},{status:403});}else requirePermission(actor,'bookings.manage');return Response.json({data:await respondTrainingOffer(db,{sessionId,providerId,idempotencyKey,expectedAttemptNo,action:body.action as 'decline'|'timeout',reason:String(body.reason||''),actorId:actor.email})});}catch(error){return authError(error,'Unable to recover Training assignment');}}
