import { aiProviderConnection, requestAiDraft } from "../ai-provider-adapter";
import { revenueMissionSummary } from "../revenue-mission-control";

export type AtlasMetric<T>={value:T|null;source:string;asOf:number;reason?:string};
export type AtlasBusinessSnapshot={
 asOf:number;
 mission:AtlasMetric<{id:string;target:number;booked:number;collected:number;refunded:number;net:number;achieved:number;percent:number;period:{start:number;end:number};basis:string;pipeline_weighted:null;pipeline_unweighted:null;forecast:null}>;
 bookings:AtlasMetric<Array<{service_code:string;created:number;accepted:number;completed:number;cancelled:number}>>;
 ops:{open_cases:AtlasMetric<number>;sla_breaches:AtlasMetric<number>;sitting_pending_accepts:AtlasMetric<number>;boarding_pending_accepts:AtlasMetric<number>;cash_collection_holds:AtlasMetric<number>};
 finance:{invoice_completed_gap:AtlasMetric<{completed_jobs:number;issued_invoices:number;gap:number}>;trainer_earnings:AtlasMetric<{pending_rate:number;held_payment:number;earned:number;published_uat_rates:number}>};
 integrations:{payments:AtlasMetric<boolean>;maps:AtlasMetric<boolean>;whatsapp:AtlasMetric<boolean>;ai:AtlasMetric<boolean>};
 limitations:string[];insufficient_data:boolean;production_ready:false;
};
type Row=Record<string,unknown>;type Db=D1Database;
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const metric=<T>(value:T|null,source:string,asOf:number,reason?:string):AtlasMetric<T>=>reason?{value,source,asOf,reason}:{value,source,asOf};
async function tableExists(db:Db,name:string){try{return Boolean(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first<Row>())}catch{return false}}
async function safeOne(db:Db,table:string,sql:string,binds:unknown[]=[]){if(!(await tableExists(db,table)))return{row:null as Row|null,reason:`missing_table:${table}`};try{return{row:await db.prepare(sql).bind(...binds).first<Row>(),reason:null}}catch{return{row:null,reason:`query_failed:${table}`}}}
async function safeAll(db:Db,table:string,sql:string){if(!(await tableExists(db,table)))return{rows:null as Row[]|null,reason:`missing_table:${table}`};try{return{rows:(await db.prepare(sql).all<Row>()).results,reason:null}}catch{return{rows:null,reason:`query_failed:${table}`}}}
async function runtimeEnv(){try{const {env}=await import("cloudflare:workers");return env as unknown as Record<string,unknown>}catch{return(globalThis as typeof globalThis&{__PAWSPACE_TEST_ENV__?:Record<string,unknown>}).__PAWSPACE_TEST_ENV__||{}}}

export async function buildAtlasBusinessSnapshot(db:Db,options:{asOf?:number;missionId?:string}={}):Promise<AtlasBusinessSnapshot>{
 const asOf=options.asOf??Date.now(),limitations:string[]=[];
 let mission:AtlasBusinessSnapshot["mission"];
 if(!(await tableExists(db,"revenue_missions"))){mission=metric<NonNullable<AtlasBusinessSnapshot["mission"]["value"]>>(null,"revenue_missions + revenue_mission_events",asOf,"missing_table:revenue_missions");limitations.push("Revenue mission tables are unavailable; mission achievement is unknown.");}
 else{const row=options.missionId?await db.prepare("SELECT id FROM revenue_missions WHERE id=?").bind(options.missionId).first<Row>():await db.prepare("SELECT id FROM revenue_missions WHERE status='active_uat' ORDER BY updated_at DESC LIMIT 1").first<Row>();if(!row){mission=metric<NonNullable<AtlasBusinessSnapshot["mission"]["value"]>>(null,"revenue_missions + revenue_mission_events",asOf,"mission_not_found");limitations.push("No active UAT revenue mission was found.");}else{const s=await revenueMissionSummary(db,text(row.id));mission=metric({id:s.mission.id,target:s.metrics.target,booked:s.metrics.booked,collected:s.metrics.collected,refunded:s.metrics.refunded,net:s.metrics.netCollected,achieved:s.metrics.achieved,percent:s.metrics.percent,period:{start:s.mission.periodStart,end:s.mission.periodEnd},basis:s.mission.revenueBasis,pipeline_weighted:null,pipeline_unweighted:null,forecast:null},"revenue_mission_events (canonical bookings + payment reconciliation)",asOf);}}
 const grouped=await safeAll(db,"canonical_bookings","SELECT service_code,status,COUNT(*) n FROM canonical_bookings GROUP BY service_code,status");let bookings:AtlasBusinessSnapshot["bookings"];
 if(!grouped.rows){bookings=metric<NonNullable<AtlasBusinessSnapshot["bookings"]["value"]>>(null,"canonical_bookings",asOf,grouped.reason!);limitations.push("Canonical booking status mix is unavailable.");}
 else{const by=new Map<string,{service_code:string;created:number;accepted:number;completed:number;cancelled:number}>();for(const r of grouped.rows){const code=text(r.service_code)||"unknown",status=text(r.status),n=num(r.n),x=by.get(code)??{service_code:code,created:0,accepted:0,completed:0,cancelled:0};x.created+=n;if(["assigned","accepted","confirmed","in_progress","in_service","on_the_way","arrived"].includes(status))x.accepted+=n;if(status==="completed")x.completed+=n;if(status==="cancelled")x.cancelled+=n;by.set(code,x)}bookings=metric([...by.values()].sort((a,b)=>a.service_code.localeCompare(b.service_code)),"canonical_bookings",asOf);}
 const cases=await safeOne(db,"unified_cases","SELECT COUNT(*) n FROM unified_cases WHERE status NOT IN ('resolved','closed')"),sla=await safeOne(db,"unified_cases","SELECT COUNT(*) n FROM unified_cases WHERE status NOT IN ('resolved','closed') AND ((first_responded_at IS NULL AND first_response_due_at<?) OR resolution_due_at<?)",[asOf,asOf]),sittingAccepts=await safeOne(db,"canonical_bookings","SELECT COUNT(*) n FROM canonical_bookings WHERE service_code='pet_sitting' AND status='awaiting_provider_acceptance'"),boardingAccepts=await safeOne(db,"boarding_stays","SELECT COUNT(*) n FROM boarding_stays WHERE status IN ('awaiting_host_acceptance','recovery_pending')");
 const completed=await safeOne(db,"canonical_bookings","SELECT COUNT(*) n FROM canonical_bookings WHERE status='completed'"),invoices=await safeOne(db,"booking_invoices","SELECT COUNT(*) n FROM booking_invoices WHERE issued_at IS NOT NULL");
 let invoiceGap:AtlasBusinessSnapshot["finance"]["invoice_completed_gap"];if(completed.row&&invoices.row)invoiceGap=metric({completed_jobs:num(completed.row.n),issued_invoices:num(invoices.row.n),gap:Math.max(0,num(completed.row.n)-num(invoices.row.n))},"canonical_bookings + booking_invoices",asOf);else{invoiceGap=metric<NonNullable<AtlasBusinessSnapshot["finance"]["invoice_completed_gap"]["value"]>>(null,"canonical_bookings + booking_invoices",asOf,completed.reason||invoices.reason||"insufficient_invoice_data");limitations.push("Invoice-to-completed-job reconciliation is incomplete.");}

 const earnings=await safeOne(db,"training_session_earnings","SELECT SUM(CASE WHEN status='pending_rate_configuration' THEN 1 ELSE 0 END) pending_rate,SUM(CASE WHEN status='held_payment' THEN 1 ELSE 0 END) held_payment,SUM(CASE WHEN status='earned' THEN 1 ELSE 0 END) earned FROM training_session_earnings"),rates=await safeOne(db,"training_compensation_rules","SELECT COUNT(*) n FROM training_compensation_rules WHERE status='published'");
 const trainer=earnings.row&&rates.row?metric({pending_rate:num(earnings.row.pending_rate),held_payment:num(earnings.row.held_payment),earned:num(earnings.row.earned),published_uat_rates:num(rates.row.n)},"training_session_earnings + training_compensation_rules",asOf):metric<NonNullable<AtlasBusinessSnapshot["finance"]["trainer_earnings"]["value"]>>(null,"training_session_earnings + training_compensation_rules",asOf,earnings.reason||rates.reason||"insufficient_trainer_finance_data");
 const env=await runtimeEnv(),ai=await aiProviderConnection(),flag=(value:boolean,source:string,reason?:string)=>metric(value,source,asOf,reason);
 const integrations={payments:flag(text(env.PAWSPACE_PAYMENT_ENV).toLowerCase()==="sandbox","runtime configuration (secret-free)",text(env.PAWSPACE_PAYMENT_ENV)?undefined:"payment_environment_unset"),maps:flag(Boolean(text(env.GOOGLE_MAPS_SERVER_API_KEY_UAT)),"runtime configuration (secret-free)",text(env.GOOGLE_MAPS_SERVER_API_KEY_UAT)?undefined:"maps_key_unset"),whatsapp:flag(Boolean(text(env.META_WHATSAPP_UAT_ACCESS_TOKEN)&&text(env.META_WHATSAPP_PHONE_NUMBER_ID)),"runtime configuration (secret-free)",text(env.META_WHATSAPP_UAT_ACCESS_TOKEN)?undefined:"whatsapp_uat_not_connected"),ai:flag(ai.configured,"ai-provider-adapter",ai.configured?undefined:"ai_provider_key_unset")};
 for(const [name,m] of Object.entries(integrations))if(!m.value)limitations.push(`${name} integration is not ready for this UAT snapshot${m.reason?`: ${m.reason}`:""}.`);
 const ops={open_cases:cases.row?metric(num(cases.row.n),"unified_cases",asOf):metric<number>(null,"unified_cases",asOf,cases.reason!),sla_breaches:sla.row?metric(num(sla.row.n),"unified_cases",asOf):metric<number>(null,"unified_cases",asOf,sla.reason!),sitting_pending_accepts:sittingAccepts.row?metric(num(sittingAccepts.row.n),"canonical_bookings:pet_sitting.awaiting_provider_acceptance",asOf):metric<number>(null,"canonical_bookings:pet_sitting.awaiting_provider_acceptance",asOf,sittingAccepts.reason!),boarding_pending_accepts:boardingAccepts.row?metric(num(boardingAccepts.row.n),"boarding_stays:awaiting_host_acceptance|recovery_pending",asOf):metric<number>(null,"boarding_stays:awaiting_host_acceptance|recovery_pending",asOf,boardingAccepts.reason!),cash_collection_holds:metric<number>(null,"canonical cash collection hold source",asOf,"canonical_cash_collection_hold_source_not_available")};limitations.push("Cash-collection holds remain unknown because no dedicated canonical cash-hold ledger/status exists; Atlas does not infer cash from generic payment confirmation.");
 return{asOf,mission,bookings,ops,finance:{invoice_completed_gap:invoiceGap,trainer_earnings:trainer},integrations,limitations:[...new Set(limitations)],insufficient_data:[mission,bookings,ops.open_cases,invoiceGap].some(x=>x.value===null),production_ready:false};
}
function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const row=value as Record<string,unknown>;return Object.fromEntries(Object.keys(row).sort().map(k=>[k,stable(row[k])]))}return value}
export async function atlasSnapshotHash(snapshot:AtlasBusinessSnapshot){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(stable(snapshot))));return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("")}
export async function ensureAtlasProposalJournal(db:Db){await db.prepare("CREATE TABLE IF NOT EXISTS atlas_proposals (id TEXT PRIMARY KEY,proposal_type TEXT NOT NULL,summary TEXT NOT NULL,snapshot_hash TEXT NOT NULL,basis_id TEXT NOT NULL,risk_class TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'approval_required',action_json TEXT,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,reviewed_by TEXT,reviewed_at INTEGER)").run()}
export async function recordAtlasProposal(db:Db,input:{proposalType:string;summary:string;snapshot:AtlasBusinessSnapshot;basisId:string;riskClass:"low"|"medium"|"high";action?:Record<string,unknown>|null;createdBy:string}){await ensureAtlasProposalJournal(db);const id=`ATLASPROP-${crypto.randomUUID().slice(0,12).toUpperCase()}`,snapshotHash=await atlasSnapshotHash(input.snapshot);await db.prepare("INSERT INTO atlas_proposals (id,proposal_type,summary,snapshot_hash,basis_id,risk_class,status,action_json,created_by,created_at) VALUES (?,?,?,?,?,?,'approval_required',?,?,?)").bind(id,input.proposalType,input.summary,snapshotHash,input.basisId,input.riskClass,input.action?JSON.stringify(input.action):null,input.createdBy,Date.now()).run();return{id,snapshotHash,status:"approval_required" as const,executed:false as const}}
export async function listAtlasProposals(db:Db,limit=20){await ensureAtlasProposalJournal(db);return(await db.prepare(`SELECT id,proposal_type,summary,snapshot_hash,basis_id,risk_class,status,action_json,created_by,created_at,reviewed_by,reviewed_at FROM atlas_proposals ORDER BY created_at DESC LIMIT ${Math.max(1,Math.min(100,Math.floor(limit)))}`).all<Row>()).results}

export function atlasNarrativeIsTightEnough(snapshot:AtlasBusinessSnapshot,narrative:string){const percent=snapshot.mission.value?.percent??null;if(percent!==null&&percent<100&&/(100\s*%|100 percent|target (?:is )?(?:fully )?(?:achieved|met)|achieved the full target)/i.test(narrative))return{ok:false as const,reason:"narrative_overstates_achievement"};if(/activate all campaigns|campaigns? (?:have been|are) activated|i activated/i.test(narrative))return{ok:false as const,reason:"narrative_claims_unauthorized_execution"};return{ok:true as const}}
export function atlasNumbersOnlyBrief(snapshot:AtlasBusinessSnapshot){const m=snapshot.mission.value;if(!m)return"Narrative unavailable; numbers only. Mission data is insufficient.";return`Narrative unavailable; numbers only. Target INR ${m.target.toLocaleString("en-IN")}; booked INR ${m.booked.toLocaleString("en-IN")}; collected INR ${m.collected.toLocaleString("en-IN")}; refunded INR ${m.refunded.toLocaleString("en-IN")}; net INR ${m.net.toLocaleString("en-IN")}; achieved ${m.percent.toFixed(2)}% on ${m.basis}.`}

export async function answerAtlasBusinessQuestion(db:Db,input:{question:string;missionId?:string;asOf?:number}){
 const snapshot=await buildAtlasBusinessSnapshot(db,{missionId:input.missionId,asOf:input.asOf}),numbersOnly=atlasNumbersOnlyBrief(snapshot);
 const draft=await requestAiDraft({systemPrompt:"You are Atlas, PawSpace founder intelligence. Answer only from the supplied canonical business snapshot. Never increase achieved revenue, turn pipeline into achieved revenue, claim an action executed, or waive approval/consent/DND. If data is missing, say so.",userPrompt:JSON.stringify({question:input.question,snapshot}),maxTokens:220,channel:"founder",intent:"atlas_business_snapshot_qa"});
 if(!draft.connected)return{snapshot,content:numbersOnly,narrativeAvailable:false,narrativeReason:draft.failure};
 const tight=atlasNarrativeIsTightEnough(snapshot,draft.text);return tight.ok?{snapshot,content:draft.text,narrativeAvailable:true,narrativeReason:null}:{snapshot,content:numbersOnly,narrativeAvailable:false,narrativeReason:tight.reason};
}
