type Db=D1Database;type Row=Record<string,unknown>;
const text=(v:unknown)=>String(v??"").trim(),DAY=86_400_000;
const DURABLE_REFERENCE=/^(?:audit:[A-Za-z0-9_./#-]{3,}|(?:d1|ledger):[A-Za-z_][A-Za-z0-9_]*:[A-Za-z0-9_./:#-]{3,})$/;
export type AtlasDecisionCommitmentStatus="open"|"completed"|"cancelled";
export type AtlasCommitmentCompletionEvidence={note:string;refs:string[];recordedBy:string;recordedAt:number;humanAttested:true;atlasVerified:false};
export type AtlasCommitmentEvidenceResolution={commitmentId:string;refs:string[];resolvedCount:number;allResolved:true;resolvedAt:number;resolver:"local_d1_row";outcomeVerified:false;authorityMutationAllowed:false;executionMutationAllowed:false;note:string};
export type AtlasCommitmentEvidenceIntegrity={commitmentId:string;state:"intact"|"degraded";checkedAt:number;missingRefs:string[];changedRefs:string[];remediationStatus:"open"|"acknowledged"|"resolved";remediationNote:string|null;requiresFounderAttention:boolean;automaticReopenAllowed:false;outcomeVerified:false;authorityMutationAllowed:false;executionMutationAllowed:false;note:string};
export type AtlasDecisionCommitment={id:string;proposalId:string|null;title:string;ownerRole:string;dueAt:number;expectedOutcome:string;status:AtlasDecisionCommitmentStatus;overdue:boolean;createdBy:string;createdAt:number;updatedBy:string;updatedAt:number;closedAt:number|null;completionEvidence:AtlasCommitmentCompletionEvidence|null;evidenceResolution:AtlasCommitmentEvidenceResolution|null;evidenceIntegrity:AtlasCommitmentEvidenceIntegrity|null;trackingOnly:true;externalMutation:false;authorityMutationAllowed:false;executionMutationAllowed:false};

export async function ensureAtlasDecisionCommitments(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS atlas_decision_commitments (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,proposal_id TEXT,title TEXT NOT NULL,owner_role TEXT NOT NULL,due_at INTEGER NOT NULL,expected_outcome TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','completed','cancelled')),created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL,closed_at INTEGER)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_atlas_decision_commitments_due ON atlas_decision_commitments(status,due_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS atlas_decision_commitment_evidence (commitment_id TEXT PRIMARY KEY,note TEXT NOT NULL,evidence_refs_json TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_atlas_commitment_evidence_time ON atlas_decision_commitment_evidence(recorded_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS atlas_decision_commitment_evidence_resolution (commitment_id TEXT PRIMARY KEY,evidence_refs_json TEXT NOT NULL,resolved_count INTEGER NOT NULL,resolved_at INTEGER NOT NULL,resolver TEXT NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_atlas_commitment_evidence_resolution_time ON atlas_decision_commitment_evidence_resolution(resolved_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS atlas_decision_commitment_evidence_fingerprints (commitment_id TEXT NOT NULL,evidence_ref TEXT NOT NULL,row_hash TEXT NOT NULL,recorded_at INTEGER NOT NULL,PRIMARY KEY(commitment_id,evidence_ref))"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_atlas_commitment_evidence_fingerprint_time ON atlas_decision_commitment_evidence_fingerprints(recorded_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS atlas_decision_commitment_integrity_remediation (commitment_id TEXT PRIMARY KEY,status TEXT NOT NULL CHECK(status IN ('acknowledged','resolved')),note TEXT NOT NULL,actor_id TEXT NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_atlas_commitment_integrity_remediation_time ON atlas_decision_commitment_integrity_remediation(updated_at)")
]);}

function evidence(row?:Row|null):AtlasCommitmentCompletionEvidence|null{if(!row)return null;let refs:string[]=[];try{const x=JSON.parse(text(row.evidence_refs_json)||"[]");if(Array.isArray(x))refs=x.map(text).filter(Boolean)}catch{}return{note:text(row.note),refs,recordedBy:text(row.recorded_by),recordedAt:Number(row.recorded_at),humanAttested:true,atlasVerified:false};}
function resolution(row?:Row|null):AtlasCommitmentEvidenceResolution|null{if(!row)return null;let refs:string[]=[];try{const x=JSON.parse(text(row.evidence_refs_json)||"[]");if(Array.isArray(x))refs=x.map(text).filter(Boolean)}catch{}return{commitmentId:text(row.commitment_id),refs,resolvedCount:Number(row.resolved_count)||0,allResolved:true,resolvedAt:Number(row.resolved_at)||0,resolver:"local_d1_row",outcomeVerified:false,authorityMutationAllowed:false,executionMutationAllowed:false,note:"Atlas verified that each evidence pointer resolves to an existing local PawSpace row. This proves evidence existence only; it does not prove the expected business outcome occurred."};}
function shape(row:Row,now:number,proof?:Row|null,resolved?:Row|null,integrity:AtlasCommitmentEvidenceIntegrity|null=null):AtlasDecisionCommitment{return{id:text(row.id),proposalId:text(row.proposal_id)||null,title:text(row.title),ownerRole:text(row.owner_role),dueAt:Number(row.due_at),expectedOutcome:text(row.expected_outcome),status:text(row.status) as AtlasDecisionCommitmentStatus,overdue:text(row.status)==="open"&&Number(row.due_at)<now,createdBy:text(row.created_by),createdAt:Number(row.created_at),updatedBy:text(row.updated_by),updatedAt:Number(row.updated_at),closedAt:row.closed_at==null?null:Number(row.closed_at),completionEvidence:evidence(proof),evidenceResolution:resolution(resolved),evidenceIntegrity:integrity,trackingOnly:true,externalMutation:false,authorityMutationAllowed:false,executionMutationAllowed:false};}

async function validateEvidenceRefs(db:Db,refsInput:string[]){const refs=[...new Set(refsInput.map(text).filter(Boolean))],resolved:string[]=[];if(!refs.length)throw new Response("Atlas commitment evidence resolution requires evidence references",{status:400});for(const reference of refs){if(!DURABLE_REFERENCE.test(reference))throw new Response("Atlas commitment evidence must use a locally resolvable reference (audit:<id> or d1/ledger:<table>:<id>)",{status:400});const[scheme,first,...rest]=reference.split(":"),table=scheme==="audit"?"security_audit_events":first,id=scheme==="audit"?first:rest.join(":");if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(table)||!id)throw new Response("Atlas commitment evidence reference must identify a local table and row",{status:400});const exists=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(table).first<Row>();if(!exists)throw new Response(`Atlas commitment evidence could not be resolved: table ${table} does not exist`,{status:400});const target=await db.prepare(`SELECT id FROM "${table}" WHERE id=? LIMIT 1`).bind(id).first<Row>();if(!target)throw new Response(`Atlas commitment evidence could not be resolved: ${reference}`,{status:400});resolved.push(reference)}return resolved;}
function evidenceTarget(reference:string){if(!DURABLE_REFERENCE.test(reference))return null;const[scheme,first,...rest]=reference.split(":"),table=scheme==="audit"?"security_audit_events":first,id=scheme==="audit"?first:rest.join(":");return /^[A-Za-z_][A-Za-z0-9_]*$/.test(table)&&id?{table,id}:null;}
async function evidenceRow(db:Db,reference:string){const target=evidenceTarget(reference);if(!target)return null;const exists=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(target.table).first<Row>();if(!exists)return null;return db.prepare(`SELECT * FROM "${target.table}" WHERE id=? LIMIT 1`).bind(target.id).first<Row>();}
const NON_SEMANTIC_FINGERPRINT_FIELDS=new Set(["updated_at","updatedAt","synced_at","syncedAt","last_seen_at","lastSeenAt","ingested_at","ingestedAt"]);
function stableRow(row:Row){return JSON.stringify(Object.fromEntries(Object.entries(row).filter(([key])=>!NON_SEMANTIC_FINGERPRINT_FIELDS.has(key)).sort(([a],[b])=>a.localeCompare(b))));}
async function rowHash(row:Row){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(stableRow(row)));return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("");}
async function evidenceFingerprint(db:Db,reference:string){const row=await evidenceRow(db,reference);return row?rowHash(row):null;}
export async function buildAtlasCommitmentEvidenceIntegrity(db:Db,commitments:AtlasDecisionCommitment[],now=Date.now()):Promise<AtlasCommitmentEvidenceIntegrity[]>{const completed=commitments.filter(x=>x.status==="completed"&&x.evidenceResolution);return Promise.all(completed.map(async x=>{const refs=x.evidenceResolution?.refs??[],stored=(await db.prepare("SELECT evidence_ref,row_hash FROM atlas_decision_commitment_evidence_fingerprints WHERE commitment_id=?").bind(x.id).all<Row>()).results,remediation=await db.prepare("SELECT status,note FROM atlas_decision_commitment_integrity_remediation WHERE commitment_id=?").bind(x.id).first<Row>(),hashByRef=new Map(stored.map(row=>[text(row.evidence_ref),text(row.row_hash)])),checks=await Promise.all(refs.map(async ref=>{const hash=await evidenceFingerprint(db,ref);return{ref,hash,expected:hashByRef.get(ref)||null}})),missingRefs=checks.filter(x=>!x.hash).map(x=>x.ref),changedRefs=checks.filter(x=>x.hash&&x.expected&&x.hash!==x.expected).map(x=>x.ref),unfingerprintedRefs=checks.filter(x=>x.hash&&!x.expected).map(x=>x.ref),degraded=missingRefs.length>0||changedRefs.length>0||unfingerprintedRefs.length>0,storedStatus=text(remediation?.status),remediationStatus=degraded?(storedStatus==="acknowledged"?"acknowledged" as const:"open" as const):(storedStatus==="resolved"?"resolved" as const:"open" as const);return{commitmentId:x.id,state:degraded?"degraded" as const:"intact" as const,checkedAt:now,missingRefs,changedRefs:[...changedRefs,...unfingerprintedRefs],remediationStatus,remediationNote:text(remediation?.note)||null,requiresFounderAttention:degraded,automaticReopenAllowed:false as const,outcomeVerified:false as const,authorityMutationAllowed:false as const,executionMutationAllowed:false as const,note:degraded?"Recorded commitment evidence is missing, changed, or lacks its completion-time fingerprint. Founder review is required; acknowledgement records review but does not clear the alert.":"All recorded commitment evidence rows still resolve and match their completion-time fingerprints. This confirms proof continuity only, not the business outcome itself."};}));}

export async function updateAtlasCommitmentIntegrityRemediation(db:Db,input:{commitmentId:string;status:"acknowledged"|"resolved";note:string;actorId:string;asOf?:number}){await ensureAtlasDecisionCommitments(db);const commitmentId=text(input.commitmentId),note=text(input.note),actorId=text(input.actorId)||"system:unknown",asOf=input.asOf??Date.now();if(!commitmentId||!note)throw new Response("Commitment integrity remediation requires commitment ID and review note",{status:400});const commitments=await listAtlasDecisionCommitments(db,{asOf,limit:100}),commitment=commitments.find(x=>x.id===commitmentId);if(!commitment||commitment.status!=="completed")throw new Response("Commitment integrity remediation requires a completed commitment",{status:409});const integrity=(await buildAtlasCommitmentEvidenceIntegrity(db,[commitment],asOf))[0];if(!integrity)throw new Response("Commitment integrity state is unavailable",{status:409});if(input.status==="acknowledged"&&integrity.state!=="degraded")throw new Response("Only degraded commitment evidence can be acknowledged",{status:409});if(input.status==="resolved"&&integrity.state!=="intact")throw new Response("Commitment evidence must be intact before remediation can be resolved",{status:409});await db.prepare("INSERT INTO atlas_decision_commitment_integrity_remediation (commitment_id,status,note,actor_id,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(commitment_id) DO UPDATE SET status=excluded.status,note=excluded.note,actor_id=excluded.actor_id,updated_at=excluded.updated_at").bind(commitmentId,input.status,note,actorId,asOf).run();return{commitmentId,status:input.status,note,actorId,updatedAt:asOf,trackingOnly:true as const,automaticEvidenceMutation:false as const,automaticReopenAllowed:false as const,outcomeVerified:false as const,authorityMutationAllowed:false as const,executionMutationAllowed:false as const};}

export async function createAtlasDecisionCommitment(db:Db,input:{idempotencyKey:string;proposalId?:string;title:string;ownerRole:string;dueAt:number;expectedOutcome:string;actorId:string;asOf?:number}){await ensureAtlasDecisionCommitments(db);const asOf=input.asOf??Date.now(),key=text(input.idempotencyKey),title=text(input.title),ownerRole=text(input.ownerRole),expectedOutcome=text(input.expectedOutcome),proposalId=text(input.proposalId)||null;if(!key||!title||!ownerRole||!expectedOutcome)throw new Response("Atlas decision commitment requires idempotency key, title, owner and expected outcome",{status:400});if(!Number.isFinite(input.dueAt)||input.dueAt<=asOf||input.dueAt>asOf+366*DAY)throw new Response("Atlas decision commitment due date must be in the future and within 366 days",{status:400});const existing=await db.prepare("SELECT * FROM atlas_decision_commitments WHERE idempotency_key=?").bind(key).first<Row>();if(existing)return{...shape(existing,asOf),duplicatePrevented:true};const id=`ATLASCOM-${crypto.randomUUID().slice(0,12).toUpperCase()}`;await db.prepare("INSERT INTO atlas_decision_commitments (id,idempotency_key,proposal_id,title,owner_role,due_at,expected_outcome,status,created_by,created_at,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,'open',?,?,?,?)").bind(id,key,proposalId,title,ownerRole,input.dueAt,expectedOutcome,text(input.actorId)||"system:unknown",asOf,text(input.actorId)||"system:unknown",asOf).run();const row=await db.prepare("SELECT * FROM atlas_decision_commitments WHERE id=?").bind(id).first<Row>();return{...shape(row!,asOf),duplicatePrevented:false};}

export async function updateAtlasDecisionCommitment(db:Db,input:{id:string;status:"completed"|"cancelled";actorId:string;completionNote?:string;evidenceRefs?:string[];asOf?:number}){await ensureAtlasDecisionCommitments(db);const asOf=input.asOf??Date.now(),id=text(input.id),actor=text(input.actorId)||"system:unknown";if(!id)throw new Response("Atlas decision commitment ID is required",{status:400});const current=await db.prepare("SELECT * FROM atlas_decision_commitments WHERE id=? AND status='open'").bind(id).first<Row>();if(!current)throw new Response("Atlas decision commitment cannot transition",{status:409});let proof:Row|null=null,resolved:Row|null=null;if(input.status==="completed"){const note=text(input.completionNote),refs=[...new Set((input.evidenceRefs||[]).map(text).filter(Boolean))];if(!note||refs.length===0)throw new Response("Completed Atlas commitment requires a human result note and at least one evidence reference",{status:400});const resolvedRefs=await validateEvidenceRefs(db,refs),fingerprints=await Promise.all(resolvedRefs.map(async ref=>({ref,hash:await evidenceFingerprint(db,ref)})));if(fingerprints.some(x=>!x.hash))throw new Response("Atlas commitment evidence changed before completion could be recorded",{status:409});const results=await db.batch([db.prepare("UPDATE atlas_decision_commitments SET status='completed',updated_by=?,updated_at=?,closed_at=? WHERE id=? AND status='open'").bind(actor,asOf,asOf,id),db.prepare("INSERT INTO atlas_decision_commitment_evidence (commitment_id,note,evidence_refs_json,recorded_by,recorded_at) VALUES (?,?,?,?,?)").bind(id,note,JSON.stringify(resolvedRefs),actor,asOf),db.prepare("INSERT INTO atlas_decision_commitment_evidence_resolution (commitment_id,evidence_refs_json,resolved_count,resolved_at,resolver) VALUES (?,?,?,?,?)").bind(id,JSON.stringify(resolvedRefs),resolvedRefs.length,asOf,"local_d1_row"),...fingerprints.map(x=>db.prepare("INSERT INTO atlas_decision_commitment_evidence_fingerprints (commitment_id,evidence_ref,row_hash,recorded_at) VALUES (?,?,?,?)").bind(id,x.ref,x.hash!,asOf))]);if(Number(results[0]?.meta?.changes||0)!==1)throw new Response("Atlas decision commitment cannot transition",{status:409});proof={note,evidence_refs_json:JSON.stringify(resolvedRefs),recorded_by:actor,recorded_at:asOf};resolved={commitment_id:id,evidence_refs_json:JSON.stringify(resolvedRefs),resolved_count:resolvedRefs.length,resolved_at:asOf,resolver:"local_d1_row"};}else{const result=await db.prepare("UPDATE atlas_decision_commitments SET status='cancelled',updated_by=?,updated_at=?,closed_at=? WHERE id=? AND status='open'").bind(actor,asOf,asOf,id).run();if(Number(result.meta?.changes||0)!==1)throw new Response("Atlas decision commitment cannot transition",{status:409});}const row=await db.prepare("SELECT * FROM atlas_decision_commitments WHERE id=?").bind(id).first<Row>();return shape(row!,asOf,proof,resolved);}

export async function listAtlasDecisionCommitments(db:Db,input:{asOf?:number;limit?:number}={}){await ensureAtlasDecisionCommitments(db);const asOf=input.asOf??Date.now(),limit=Math.max(1,Math.min(100,Math.floor(input.limit??30))),rows=(await db.prepare(`SELECT * FROM atlas_decision_commitments ORDER BY CASE WHEN status='open' AND due_at<${asOf} THEN 0 WHEN status='open' THEN 1 ELSE 2 END,due_at ASC,updated_at DESC LIMIT ${limit}`).all<Row>()).results;if(!rows.length)return[];const proofs=(await db.prepare("SELECT * FROM atlas_decision_commitment_evidence ORDER BY recorded_at DESC").all<Row>()).results,resolutions=(await db.prepare("SELECT * FROM atlas_decision_commitment_evidence_resolution ORDER BY resolved_at DESC").all<Row>()).results,proofById=new Map(proofs.map(x=>[text(x.commitment_id),x])),resolutionById=new Map(resolutions.map(x=>[text(x.commitment_id),x]));return rows.map(row=>{const id=text(row.id);return shape(row,asOf,proofById.get(id),resolutionById.get(id))});}
