import { requestAiDraft } from "../ai-provider-adapter";
import { ensureAtlasTables } from "./atlas-data";

type Metric="revenue"|"cost"|"payment"|"net"|"margin"|"row_count";
type Dimension="period_month"|"entry_date"|"service_code"|"source_kind"|"category"|"ledger_name"|"party_name"|"voucher_type";
type Filter={field:Dimension;op:"eq"|"gte"|"lte";value:string};
type QueryPlan={metrics:Metric[];dimensions:Dimension[];filters:Filter[];limit:number};
type Row=Record<string,unknown>;
const dimensions=new Set<Dimension>(["period_month","entry_date","service_code","source_kind","category","ledger_name","party_name","voucher_type"]);
const metrics=new Set<Metric>(["revenue","cost","payment","net","margin","row_count"]);
const metricSql:Record<Metric,string>={revenue:"ROUND(SUM(revenue_amount),2) AS revenue",cost:"ROUND(SUM(cost_amount),2) AS cost",payment:"ROUND(SUM(payment_amount),2) AS payment",net:"ROUND(SUM(net_amount),2) AS net",margin:"ROUND(SUM(revenue_amount)-SUM(cost_amount),2) AS margin",row_count:"COUNT(*) AS row_count"};
const text=(v:unknown)=>String(v??"").trim();

function extractJson(raw:string){const match=raw.match(/\{[\s\S]*\}/);if(!match)throw new Error("Atlas query planner returned no JSON object");return JSON.parse(match[0]) as Record<string,unknown>;}
function validatePlan(raw:Record<string,unknown>):QueryPlan{const requestedMetrics=Array.isArray(raw.metrics)?raw.metrics.map(text).filter(v=>metrics.has(v as Metric)) as Metric[]:[];const requestedDimensions=Array.isArray(raw.dimensions)?raw.dimensions.map(text).filter(v=>dimensions.has(v as Dimension)) as Dimension[]:[];const requestedFilters=Array.isArray(raw.filters)?raw.filters:[];const filters:Filter[]=requestedFilters.flatMap(value=>{if(!value||typeof value!=="object"||Array.isArray(value))return[];const f=value as Row,field=text(f.field) as Dimension,op=text(f.op) as Filter["op"],val=text(f.value);return dimensions.has(field)&&["eq","gte","lte"].includes(op)&&val?[{field,op,value:val}]:[];});if(!requestedMetrics.length)throw new Error("Atlas query requires at least one approved metric");return{metrics:[...new Set(requestedMetrics)].slice(0,6),dimensions:[...new Set(requestedDimensions)].slice(0,3),filters:filters.slice(0,8),limit:Math.max(1,Math.min(200,Math.floor(Number(raw.limit)||50)))};}
export function compileFinancialQuery(plan:QueryPlan){const select=[...plan.dimensions,...plan.metrics.map(m=>metricSql[m])],where:string[]=[],bindings:string[]=[];for(const f of plan.filters){const operator=f.op==="eq"?"=":f.op==="gte"?">=":"<=";where.push(`${f.field} ${operator} ?`);bindings.push(f.value);}let sql=`SELECT ${select.join(", ")} FROM analytics_historical_financials`;if(where.length)sql+=` WHERE ${where.join(" AND ")}`;if(plan.dimensions.length)sql+=` GROUP BY ${plan.dimensions.join(", ")} ORDER BY ${plan.dimensions[0]} DESC`;sql+=` LIMIT ${plan.limit}`;return{sql,bindings};}

export async function planFinancialQuery(question:string){const q=text(question);if(!q||q.length>1000)throw new Response("Founder analytics question must be 1-1000 characters",{status:400});const result=await requestAiDraft({systemPrompt:`Translate the founder's financial question into JSON only. Allowed table is analytics_historical_financials. Allowed metrics: revenue,cost,payment,net,margin,row_count. Allowed dimensions/filter fields: period_month,entry_date,service_code,source_kind,category,ledger_name,party_name,voucher_type. Filters use op eq|gte|lte. Never output SQL. Never request another table. Shape: {"metrics":[],"dimensions":[],"filters":[{"field":"","op":"eq","value":""}],"limit":50}.`,userPrompt:q,maxTokens:350,channel:"founder",intent:"atlas_financial_query_plan"});if(!result.connected)throw new Response("Atlas AI query planner is unavailable",{status:503});return validatePlan(extractJson(result.text));}

export async function answerFinancialQuestion(db:D1Database,question:string){await ensureAtlasTables(db);const plan=await planFinancialQuery(question),compiled=compileFinancialQuery(plan);if(!/^SELECT\s/i.test(compiled.sql)||/\b(?:INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|ATTACH|PRAGMA|REPLACE|VACUUM)\b/i.test(compiled.sql))throw new Error("Atlas read-only SQL invariant rejected the query");const rows=await db.prepare(compiled.sql).bind(...compiled.bindings).all<Row>();return{question,plan,sql:compiled.sql,bindings:compiled.bindings,rows:rows.results,readOnly:true,source:"analytics_historical_financials"};}
