import{authError,authorize,database,securityAudit}from"../../../lib/server-auth";
import{hasPermission,maskName,maskPhone}from"../../../lib/platform-security";
import{assignConversation,getConversation,listConversationThreads,recordInboundMessage,setConversationStatus}from"../../../lib/conversation-governance";
import{actorCanAccessConversation}from"../../../lib/conversation-access";

type Body={action?:string;threadId?:string;customerId?:string;channel?:"whatsapp"|"sms"|"email"|"push"|"chat"|"voice";payload?:Record<string,unknown>;provider?:string;providerReference?:string;eventId?:string;assignedTo?:string;reason?:string;slaMinutes?:number;status?:"open"|"pending_customer"|"resolved"|"closed"};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin conversation write blocked",{status:403});}
/*
 * Customer contact data is masked for an actor without customers.view_full_phone, the convention
 * app/api/subscription-customers/route.ts already applies (PTJA W2-B3-C07). Measured: the same
 * associate identity - which holds communications.manage but NOT customers.view_full_phone - was served
 * the thread list carrying "+919845012345" verbatim, and the thread view's message payload carried
 * customerPhone as well.
 *
 * The payload's `internalNote` is deliberately left alone. Who may read a staff-authored internal note
 * is a product decision, not a masking rule, and it is carried in the audit ledger rather than decided
 * here.
 */
export async function GET(request:Request){try{const convActor=await authorize(request,"communications.manage");const revealPhone=hasPermission(convActor.permissions,"customers.view_full_phone");const maskThread=(row:Record<string,unknown>)=>revealPhone?row:{...row,customer_name:row.customer_name?maskName(String(row.customer_name)):row.customer_name,primary_phone:row.primary_phone?maskPhone(String(row.primary_phone)):row.primary_phone};const maskPayload=(value:unknown):unknown=>{if(revealPhone||!value||typeof value!=="object")return value;const record={...value as Record<string,unknown>};if(record.customerPhone)record.customerPhone=maskPhone(String(record.customerPhone));return record;};const db=await database(),url=new URL(request.url),threadId=url.searchParams.get("threadId");if(threadId){if(!(await actorCanAccessConversation(db,convActor,threadId)))return json({error:"Conversation access denied"},403);const data=await getConversation(db,threadId,"staff");if(data){const shaped=data as Record<string,unknown>;const thread=shaped.thread?maskThread(shaped.thread as Record<string,unknown>):shaped.thread;const messages=Array.isArray(shaped.messages)?(shaped.messages as Record<string,unknown>[]).map(message=>({...message,payload:maskPayload(message.payload)})):shaped.messages;return json({data:{...shaped,thread,messages}});}return json({error:"Conversation not found"},404);}const data=await listConversationThreads(db,{actor:convActor,customerId:url.searchParams.get("customerId")||undefined,status:url.searchParams.get("status")||undefined,limit:Number(url.searchParams.get("limit")||100)});return json({data:{threads:(data as Record<string,unknown>[]).map(maskThread),source:"canonical_conversation_threads",liveDelivery:false}});}catch(error){return authError(error,"Unable to load conversations");}}
export async function POST(request:Request){try{sameOrigin(request);const actor=await authorize(request,"communications.manage"),body=await request.json() as Body,db=await database();if(body.threadId&&!(await actorCanAccessConversation(db,actor,body.threadId))){await securityAudit(db,actor,`conversation.${String(body.action||"unknown")}`,"conversation",body.threadId,"denied",{reason:"row_scope"});return json({error:"Conversation access denied"},403);}if(body.action==="record_inbound"){if(!body.threadId||!body.customerId||!body.channel||!body.provider||!body.providerReference||!body.eventId)return json({error:"Complete inbound message identity is required"},400);const data=await recordInboundMessage(db,{threadId:body.threadId,customerId:body.customerId,channel:body.channel,payload:body.payload||{},provider:body.provider,providerReference:body.providerReference,eventId:body.eventId,createdBy:actor.email});await securityAudit(db,actor,"conversation.inbound","conversation",body.threadId,"completed",{messageId:data.id,provider:body.provider});return json({data},data.duplicatePrevented?200:201);}
 if(body.action==="assign"){if(!body.threadId||!body.assignedTo)return json({error:"Thread and assignee are required"},400);const data=await assignConversation(db,{threadId:body.threadId,assignedTo:body.assignedTo,assignedBy:actor.email,reason:body.reason,slaMinutes:body.slaMinutes});await securityAudit(db,actor,"conversation.assign","conversation",body.threadId,"completed",{assignedTo:body.assignedTo});return json({data});}
 if(body.action==="status"){if(!body.threadId||!body.status)return json({error:"Thread and status are required"},400);const data=await setConversationStatus(db,{threadId:body.threadId,status:body.status,actorEmail:actor.email,reason:body.reason});await securityAudit(db,actor,"conversation.status","conversation",body.threadId,"completed",{status:body.status});return json({data});}
 return json({error:"Unsupported conversation action"},400);
}catch(error){if(error instanceof Response)return json({error:await error.text()},error.status);return authError(error,"Unable to update conversation");}}
