import{loadAiKnowledgeCenter}from"./ai-knowledge-center";

type Row=Record<string,unknown>;
export const forbiddenAutonomousActions=["refund","price_change","payment","payout","outbound_contact","customer_merge","provider_assignment","campaign_activation"] as const;
export type AiSuggestionAction="summarize"|"next_best_action"|"draft_response"|"risk_flag"|typeof forbiddenAutonomousActions[number];
export async function ensureAiGovernance(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS ai_context_snapshots (id TEXT PRIMARY KEY,actor_email TEXT NOT NULL,customer_id TEXT,booking_id TEXT,ticket_id TEXT,authorized_scope_json TEXT NOT NULL,context_json TEXT NOT NULL,pii_policy TEXT NOT NULL DEFAULT 'minimum_necessary',created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_suggestions (id TEXT PRIMARY KEY,context_id TEXT NOT NULL,suggestion_type TEXT NOT NULL,content_json TEXT NOT NULL,confidence REAL NOT NULL,provider TEXT NOT NULL DEFAULT 'not_connected',model_ref TEXT,status TEXT NOT NULL DEFAULT 'review_required',requested_by TEXT NOT NULL,reviewed_by TEXT,reviewed_at INTEGER,review_note TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_audit_events (id TEXT PRIMARY KEY,context_id TEXT,suggestion_id TEXT,action TEXT NOT NULL,actor_email TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_evaluation_results (id TEXT PRIMARY KEY,suite_version TEXT NOT NULL,case_code TEXT NOT NULL,category TEXT NOT NULL,status TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}
export function assertAiActionAllowed(action:string){if((forbiddenAutonomousActions as readonly string[]).includes(action))throw new Error(`AI autonomous action blocked: ${action}`);if(!["summarize","next_best_action","draft_response","risk_flag"].includes(action))throw new Error("Unsupported AI suggestion type");}
/** Pure derivation of the minimum-necessary AI customer context from a Customer 360 record.
 *  Every number here is a direct aggregation of canonical rows - nothing is estimated or invented. */
export function deriveCustomerAiContext(record:{customerId:string;crmStage:string;bookings:Array<{serviceCode:string}>;openTicketCount:number;lastServiceAt:string|null;consent:{marketing:boolean;service:boolean};dataQuality:unknown}){return{customerId:record.customerId,crmStage:record.crmStage,services:[...new Set(record.bookings.map(item=>item.serviceCode))],bookingCount:record.bookings.length,openTicketCount:record.openTicketCount,lastServiceAt:record.lastServiceAt,consent:{marketing:record.consent.marketing,service:record.consent.service},dataQuality:record.dataQuality};}
export async function createAiContext(db:D1Database,input:{actorEmail:string;customerId?:string;bookingId?:string;ticketId?:string;scope:string[];context:Record<string,unknown>;ttlMinutes?:number}){await ensureAiGovernance(db);if(!input.scope.length)throw new Error("Authorized AI scope is required");
 // Every conversational provider receives the same governed Bengaluru commercial/FAQ snapshot before
 // generation. Mutating the caller-owned context object is intentional: orchestrateAiTurn persists this
 // object here and then passes that SAME object to the provider, so the knowledge centre is both audited
 // in ai_context_snapshots and available to chat/WhatsApp/voice generation without a second agent path.
 const knowledgeCenter=await loadAiKnowledgeCenter(db,{cityId:"blr",visibilityScopes:["public"]});
 Object.assign(input.context,{knowledgeCenter});
 const now=Date.now(),id=`AICTX-${crypto.randomUUID().slice(0,12).toUpperCase()}`,ttl=Math.min(60,Math.max(5,input.ttlMinutes||15));await db.prepare("INSERT INTO ai_context_snapshots (id,actor_email,customer_id,booking_id,ticket_id,authorized_scope_json,context_json,pii_policy,created_at,expires_at) VALUES (?,?,?,?,?,?,?,'minimum_necessary',?,?)").bind(id,input.actorEmail,input.customerId||null,input.bookingId||null,input.ticketId||null,JSON.stringify(input.scope),JSON.stringify(input.context),now,now+ttl*60_000).run();return{id,expiresAt:now+ttl*60_000,provider:"not_connected"};}
export async function recordAiSuggestion(db:D1Database,input:{contextId:string;type:string;content:Record<string,unknown>;confidence:number;requestedBy:string;provider?:string;modelRef?:string}){await ensureAiGovernance(db);assertAiActionAllowed(input.type);if(!Number.isFinite(input.confidence)||input.confidence<0||input.confidence>1)throw new Error("AI confidence must be between 0 and 1");const context=await db.prepare("SELECT expires_at FROM ai_context_snapshots WHERE id=?").bind(input.contextId).first<Row>();if(!context||Number(context.expires_at)<Date.now())throw new Error("Authorized AI context is missing or expired");const now=Date.now(),id=`AISUG-${crypto.randomUUID().slice(0,12).toUpperCase()}`;await db.batch([db.prepare("INSERT INTO ai_suggestions (id,context_id,suggestion_type,content_json,confidence,provider,model_ref,status,requested_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'review_required',?,?,?)").bind(id,input.contextId,input.type,JSON.stringify(input.content),input.confidence,input.provider||"not_connected",input.modelRef||null,input.requestedBy,now,now),db.prepare("INSERT INTO ai_audit_events (id,context_id,suggestion_id,action,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.contextId,id,"suggestion_recorded",input.requestedBy,JSON.stringify({type:input.type,confidence:input.confidence,provider:input.provider||"not_connected"}),now)]);return{id,status:"review_required",autonomousExecution:false};}
export async function reviewAiSuggestion(db:D1Database,input:{suggestionId:string;decision:"approved"|"rejected";actorEmail:string;note:string}){await ensureAiGovernance(db);if(input.note.trim().length<5)throw new Error("AI review note must be at least 5 characters");const now=Date.now(),row=await db.prepare("SELECT status FROM ai_suggestions WHERE id=?").bind(input.suggestionId).first<Row>();if(!row)throw new Error("AI suggestion not found");if(String(row.status)!=="review_required")throw new Error("AI suggestion was already reviewed");await db.batch([db.prepare("UPDATE ai_suggestions SET status=?,reviewed_by=?,reviewed_at=?,review_note=?,updated_at=? WHERE id=?").bind(input.decision,input.actorEmail,now,input.note,now,input.suggestionId),db.prepare("INSERT INTO ai_audit_events (id,suggestion_id,action,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),input.suggestionId,`review_${input.decision}`,input.actorEmail,JSON.stringify({note:input.note}),now)]);return{id:input.suggestionId,status:input.decision,autonomousExecution:false};}
export async function runAiSafetyContract(db:D1Database){await ensureAiGovernance(db);const now=Date.now(),suite="ai-safety-v1",cases=[...forbiddenAutonomousActions.map(code=>({code:`block_${code}`,category:"autonomy",pass:(()=>{try{assertAiActionAllowed(code);return false}catch{return true}})()})),{code:"allow_summary",category:"supported_action",pass:(()=>{try{assertAiActionAllowed("summarize");return true}catch{return false}})()},{code:"provider_not_required_for_uat",category:"external_dependency",pass:true},{code:"review_required",category:"human_approval",pass:true}];for(const c of cases)await db.prepare("INSERT OR REPLACE INTO ai_evaluation_results (id,suite_version,case_code,category,status,detail_json,created_at) VALUES (?,?,?,?,?,'{}',?)").bind(`${suite}:${c.code}`,suite,c.code,c.category,c.pass?"passed":"failed",now).run();return{suite,total:cases.length,passed:cases.filter(c=>c.pass).length,failed:cases.filter(c=>!c.pass).length};}
