import{retrieveApprovedKnowledge}from"./ai-business-configuration";
import{assignConversation,ensureConversationGovernance}from"./conversation-governance";
import{groomingCatalogue}from"./grooming-governance";
import{requireCustomerOwnership,type AuthenticatedActor}from"./server-auth";
import{listCustomerSubscriptionWallets}from"./subscription-wallet";
import{createUnifiedCase,ensureUnifiedCaseTables,type CaseSeverity,type CaseType}from"./unified-case-center";

type Row=Record<string,unknown>;
export type AiToolChannel="whatsapp"|"chat"|"voice";
export type AiToolIntent="service_info"|"booking_create"|"booking_status"|"booking_change"|"subscription_wallet"|"coupon"|"support"|"refund_review"|"funeral_memorial"|"relocation"|"human_handoff"|"unknown";
export type AiToolMode="read"|"mutation"|"approval_gated";
export type AiToolCode=
 |"service_catalogue.read"|"customer_bookings.read"|"booking_status.read"|"provider_status.read"|"subscription_wallet.read"|"case_status.read"|"approved_knowledge.read"
 |"quote.request"|"booking.request"|"booking_reschedule.request"|"booking_cancel.request"|"case.create"|"staff_handoff.create"
 |"refund.issue"|"payment.capture"|"payout.release"|"price.override"|"provider.assign"|"campaign.activate"|"communication.send"|"customer.merge";
export type AiToolDefinition={code:AiToolCode;mode:AiToolMode;canonicalService:string;intents:AiToolIntent[];channels:AiToolChannel[];confirmationRequired:boolean;idempotencyRequired:boolean;staffPermissions:string[];description:string};

const channels:AiToolChannel[]=["whatsapp","chat","voice"];
const allCustomerIntents:AiToolIntent[]=["service_info","booking_create","booking_status","booking_change","subscription_wallet","coupon","support","refund_review","funeral_memorial","relocation","human_handoff"];
const registry:AiToolDefinition[]=[
 {code:"service_catalogue.read",mode:"read",canonicalService:"grooming-governance",intents:["service_info","booking_create"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:[],description:"Read active server-owned service catalogue entries."},
 {code:"customer_bookings.read",mode:"read",canonicalService:"canonical-bookings",intents:["booking_create","booking_status","booking_change","support"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:["bookings.manage"],description:"Read bookings owned by the authorized customer."},
 {code:"booking_status.read",mode:"read",canonicalService:"canonical-bookings",intents:["booking_status","booking_change","support"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:["bookings.manage"],description:"Read canonical booking status."},
 {code:"provider_status.read",mode:"read",canonicalService:"canonical-bookings",intents:["booking_status","support"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:["bookings.manage","providers.manage"],description:"Read only provider state already attached to an authorized canonical booking."},
 {code:"subscription_wallet.read",mode:"read",canonicalService:"subscription-wallet",intents:["subscription_wallet","booking_create","support"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:["customers.manage"],description:"Read server-owned subscription and wallet status."},
 {code:"case_status.read",mode:"read",canonicalService:"unified-case-center",intents:["support","refund_review","booking_change","funeral_memorial","relocation"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:["customers.manage"],description:"Read customer-linked canonical case status."},
 {code:"approved_knowledge.read",mode:"read",canonicalService:"ai-business-configuration",intents:allCustomerIntents,channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:[],description:"Retrieve only approved/current knowledge visible to the caller."},
 {code:"quote.request",mode:"read",canonicalService:"grooming-governance",intents:["service_info","booking_create"],channels,confirmationRequired:false,idempotencyRequired:false,staffPermissions:[],description:"Calculate a quote from server-owned active catalogue data."},
 {code:"booking.request",mode:"mutation",canonicalService:"unified-case-center",intents:["booking_create"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:["bookings.manage","scheduling.book"],description:"Create a governed booking request for canonical scheduling; does not assign a provider or capture money."},
 {code:"booking_reschedule.request",mode:"mutation",canonicalService:"unified-case-center",intents:["booking_change"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:["bookings.manage","scheduling.book"],description:"Create a governed reschedule request against an owned canonical booking."},
 {code:"booking_cancel.request",mode:"mutation",canonicalService:"unified-case-center",intents:["booking_change"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:["bookings.manage"],description:"Create a governed cancellation request; no refund is issued."},
 {code:"case.create",mode:"mutation",canonicalService:"unified-case-center",intents:["support","refund_review","funeral_memorial","relocation"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:["customers.manage"],description:"Create a canonical support/case record."},
 {code:"staff_handoff.create",mode:"mutation",canonicalService:"conversation-governance",intents:["human_handoff","support","refund_review","funeral_memorial","relocation","booking_change"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:["communications.message"],description:"Assign the canonical conversation to a staff handoff queue."},
 {code:"refund.issue",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["refund_review"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot issue refunds."},
 {code:"payment.capture",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["booking_create"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot capture payments."},
 {code:"payout.release",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["support"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot release payouts."},
 {code:"price.override",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["service_info","booking_create"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot override governed prices."},
 {code:"provider.assign",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["booking_create","booking_change"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot assign providers."},
 {code:"campaign.activate",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["coupon"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot activate campaigns."},
 // ai-governance has always blocked `outbound_contact` and `customer_merge` as autonomous actions, but
 // neither had a tool code here. The blocklist stops the AI naming the action; without a registered
 // approval_gated entry there was nothing to REFUSE when a caller asked for the capability by tool
 // code, and nothing on the snapshot telling a reviewer these two need a human. Every entry in
 // forbiddenAutonomousActions must map to a tool code, which HIGH_IMPACT_TOOL_FOR_ACTION now pins.
 {code:"communication.send",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["support","booking_change","refund_review","human_handoff"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot send an outbound customer communication."},
 {code:"customer.merge",mode:"approval_gated",canonicalService:"deterministic-approval",intents:["support"],channels,confirmationRequired:true,idempotencyRequired:true,staffPermissions:[],description:"Approval-gated; AI cannot merge customer identities."},
];

/**
 * Every autonomous action ai-governance forbids, and the approval-gated tool code that refuses it.
 * Exported so the mapping is one fact in one place: a new forbidden action with no tool code, or a
 * tool code that stops being approval_gated, is a hole in the same wall.
 */
export const HIGH_IMPACT_TOOL_FOR_ACTION:Record<string,AiToolCode>={
 refund:"refund.issue",
 price_change:"price.override",
 payment:"payment.capture",
 payout:"payout.release",
 outbound_contact:"communication.send",
 customer_merge:"customer.merge",
 provider_assignment:"provider.assign",
 campaign_activation:"campaign.activate",
};

const forbiddenAuthoritativeFields=new Set(["price","total","totalAmount","amountDueNow","provider","providerId","provider_id","walletBalance","balance","refundAmount","paymentStatus","payoutAmount","discountAmount"]);
const text=(v:unknown)=>String(v??"").trim();
const parse=<T>(v:unknown,f:T):T=>{try{return JSON.parse(String(v??""))as T}catch{return f}};
function tool(code:string){const found=registry.find(item=>item.code===code);if(!found)throw new Error("AI tool is not registered");return found;}
function cleanArguments(input:Record<string,unknown>){for(const key of Object.keys(input))if(forbiddenAuthoritativeFields.has(key))throw new Error(`Authoritative field ${key} must be resolved server-side`);return input;}
function hasStaffPermission(actor:AuthenticatedActor,definition:AiToolDefinition){return actor.permissions.includes("*")||definition.staffPermissions.some(permission=>actor.permissions.includes(permission));}
function isStaff(actor:AuthenticatedActor){return actor.permissions.includes("*")||actor.permissions.includes("customers.manage")||actor.permissions.includes("bookings.manage")||actor.permissions.includes("communications.message");}
async function authorizeCustomerScope(db:D1Database,actor:AuthenticatedActor,customerId:string,definition:AiToolDefinition){if(isStaff(actor)){if(definition.staffPermissions.length&&!hasStaffPermission(actor,definition))throw new Response("AI tool permission denied",{status:403});return;}await requireCustomerOwnership(db,actor,customerId);}

export async function ensureAiToolRegistry(db:D1Database){await ensureConversationGovernance(db);await ensureUnifiedCaseTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS ai_tool_execution_requests (id TEXT PRIMARY KEY,tool_code TEXT NOT NULL,mode TEXT NOT NULL,canonical_service TEXT NOT NULL,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,intent_code TEXT NOT NULL,channel TEXT NOT NULL,actor_email TEXT NOT NULL,arguments_json TEXT NOT NULL,arguments_hash TEXT NOT NULL,idempotency_key TEXT,confirmation_required INTEGER NOT NULL DEFAULT 0,confirmed_at INTEGER,status TEXT NOT NULL,policy_decision TEXT NOT NULL,result_json TEXT,created_at INTEGER NOT NULL,completed_at INTEGER)"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS ai_tool_mutation_idempotency_idx ON ai_tool_execution_requests(idempotency_key) WHERE idempotency_key IS NOT NULL"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_tool_audit_events (id TEXT PRIMARY KEY,request_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_email TEXT NOT NULL,detail_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS ai_tool_audit_request_idx ON ai_tool_audit_events(request_id,created_at)"),
]);}
async function hashArguments(input:Record<string,unknown>){const bytes=new TextEncoder().encode(JSON.stringify(input,Object.keys(input).sort()));const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("");}
async function audit(db:D1Database,requestId:string,eventType:string,actorEmail:string,detail:unknown){await db.prepare("INSERT INTO ai_tool_audit_events (id,request_id,event_type,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(`AITAUD-${crypto.randomUUID().slice(0,12).toUpperCase()}`,requestId,eventType,actorEmail,JSON.stringify(detail??{}),Date.now()).run();}

async function readBooking(db:D1Database,customerId:string,bookingId:string){const row=await db.prepare("SELECT * FROM canonical_bookings WHERE id=? AND customer_id=?").bind(bookingId,customerId).first<Row>();if(!row)throw new Error("Authorized canonical booking not found");return row;}
function bookingSummary(row:Row){return{id:row.id,serviceCode:row.service_code,packageCode:row.package_code,packageName:row.package_name,status:row.status,scheduledStart:row.scheduled_start,scheduledEnd:row.scheduled_end,channel:row.channel};}
function providerSummary(row:Row){return{bookingId:row.id,bookingStatus:row.status,providerId:row.provider_id??null,providerName:row.provider_name??null,providerStatus:row.provider_status??null,eta:row.provider_eta??row.eta??null,source:"canonical_booking_only"};}

async function executeRead(db:D1Database,definition:AiToolDefinition,customerId:string,args:Record<string,unknown>){
 if(definition.code==="service_catalogue.read")return{serviceCode:"grooming",currency:"INR",catalogue:groomingCatalogue.filter(item=>item.active).map(item=>({code:item.code,name:item.name,offerType:item.offerType,eligiblePetTypes:item.eligiblePetTypes,singlePrice:item.singlePrice,multiPetPrice:item.multiPetPrice??null,version:item.version}))};
 if(definition.code==="quote.request"){const packageCode=text(args.packageCode),petCount=Math.floor(Number(args.petCount||1)),item=groomingCatalogue.find(row=>row.active&&row.code===packageCode);if(!item)throw new Error("Active governed package not found");if(petCount<1||petCount>4)throw new Error("Quote pet count must be between 1 and 4");const total=petCount===1?item.singlePrice:(item.multiPetPrice??item.singlePrice)*petCount;return{serviceCode:"grooming",packageCode:item.code,packageName:item.name,petCount,totalAmount:total,currency:"INR",catalogueVersion:item.version,serverAuthoritative:true,liveMoney:false};}
 if(definition.code==="customer_bookings.read"){const rows=await db.prepare("SELECT * FROM canonical_bookings WHERE customer_id=? ORDER BY created_at DESC LIMIT 50").bind(customerId).all<Row>();return rows.results.map(bookingSummary);}
 if(definition.code==="booking_status.read")return bookingSummary(await readBooking(db,customerId,text(args.bookingId)));
 if(definition.code==="provider_status.read")return providerSummary(await readBooking(db,customerId,text(args.bookingId)));
 if(definition.code==="subscription_wallet.read")return listCustomerSubscriptionWallets(db,customerId);
 if(definition.code==="case_status.read"){await ensureUnifiedCaseTables(db);const rows=await db.prepare("SELECT id,case_type,severity,status,title,booking_id,owner_team,first_response_due_at,resolution_due_at,created_at,updated_at FROM unified_cases WHERE customer_id=? ORDER BY created_at DESC LIMIT 50").bind(customerId).all<Row>();return rows.results;}
 if(definition.code==="approved_knowledge.read"){const query=text(args.query);if(!query)throw new Error("Knowledge query is required");const scopes=Array.isArray(args.visibilityScopes)?args.visibilityScopes.map(text).filter(Boolean):["public"];return retrieveApprovedKnowledge(db,{query,visibilityScopes:scopes});}
 throw new Error("Registered read tool has no canonical adapter");
}

function caseSpec(code:AiToolCode,args:Record<string,unknown>):{caseType:CaseType;severity:CaseSeverity;title:string;description:string;ownerTeam:string}{
 if(code==="booking.request")return{caseType:"operations",severity:"medium",title:"AI booking request",description:text(args.request)||"Customer requested a booking through AI",ownerTeam:"operations"};
 if(code==="booking_reschedule.request")return{caseType:"rebooking",severity:"medium",title:"AI reschedule request",description:text(args.request)||"Customer requested a booking reschedule through AI",ownerTeam:"operations"};
 if(code==="booking_cancel.request")return{caseType:"rebooking",severity:"medium",title:"AI cancellation request",description:text(args.reason)||"Customer requested booking cancellation through AI; refund not authorized",ownerTeam:"operations"};
 return{caseType:(text(args.caseType)||"customer_complaint")as CaseType,severity:(text(args.severity)||"medium")as CaseSeverity,title:text(args.title)||"AI support request",description:text(args.description)||"Customer requested support through AI",ownerTeam:text(args.ownerTeam)||"cx"};
}
async function executeMutation(db:D1Database,definition:AiToolDefinition,input:{requestId:string;actor:AuthenticatedActor;threadId:string;customerId:string;idempotencyKey:string;args:Record<string,unknown>}){
 if(["booking.request","booking_reschedule.request","booking_cancel.request","case.create"].includes(definition.code)){const bookingId=text(input.args.bookingId)||null;if(bookingId)await readBooking(db,input.customerId,bookingId);const spec=caseSpec(definition.code,input.args);return createUnifiedCase(db,{idempotencyKey:`ai-tool:${input.idempotencyKey}`,caseType:spec.caseType,severity:spec.severity,title:spec.title,description:spec.description,customerId:input.customerId,bookingId,sourceType:"ai_tool_request",sourceId:input.requestId,ownerTeam:spec.ownerTeam,actorId:input.actor.email});}
 if(definition.code==="staff_handoff.create"){await assignConversation(db,{threadId:input.threadId,assignedTo:"cx-ai-handoff",assignedBy:input.actor.email,reason:text(input.args.reason)||"ai:customer_confirmed_handoff",slaMinutes:15});return{threadId:input.threadId,assignedTo:"cx-ai-handoff",moneyAction:false};}
 throw new Error("Registered mutation tool has no canonical adapter");
}

export async function prepareAiToolExecution(db:D1Database,input:{actor:AuthenticatedActor;toolCode:string;threadId:string;customerId:string;intent:AiToolIntent;channel:AiToolChannel;arguments?:Record<string,unknown>;idempotencyKey?:string}){await ensureAiToolRegistry(db);const definition=tool(input.toolCode);if(!definition.intents.includes(input.intent))throw new Response("AI tool is not permitted for this intent",{status:403});if(!definition.channels.includes(input.channel))throw new Response("AI tool is not permitted for this channel",{status:403});await authorizeCustomerScope(db,input.actor,input.customerId,definition);if(definition.mode==="approval_gated")return{status:"approval_required",executed:false,tool:definition.code,canonicalService:definition.canonicalService,autonomousExecution:false};const args=cleanArguments(input.arguments??{});if(definition.idempotencyRequired&&!text(input.idempotencyKey))throw new Error("Idempotency key is required for every AI tool mutation");if(input.idempotencyKey){const prior=await db.prepare("SELECT * FROM ai_tool_execution_requests WHERE idempotency_key=?").bind(input.idempotencyKey).first<Row>();if(prior)return{status:String(prior.status),requestId:String(prior.id),duplicatePrevented:true,executed:String(prior.status)==="completed",result:parse(prior.result_json,null),autonomousExecution:false};}
 const requestId=`AITOOL-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now(),argumentsHash=await hashArguments(args);if(definition.mode==="read"){const result=await executeRead(db,definition,input.customerId,args);await db.prepare("INSERT INTO ai_tool_execution_requests (id,tool_code,mode,canonical_service,thread_id,customer_id,intent_code,channel,actor_email,arguments_json,arguments_hash,idempotency_key,confirmation_required,confirmed_at,status,policy_decision,result_json,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,NULL,'completed','allowed',?,?,?)").bind(requestId,definition.code,definition.mode,definition.canonicalService,input.threadId,input.customerId,input.intent,input.channel,input.actor.email,JSON.stringify(args),argumentsHash,null,JSON.stringify(result),now,Date.now()).run();await audit(db,requestId,"executed_read",input.actor.email,{toolCode:definition.code,canonicalService:definition.canonicalService});return{status:"completed",requestId,executed:true,result,serverAuthoritative:true,autonomousExecution:false};}
 await db.prepare("INSERT INTO ai_tool_execution_requests (id,tool_code,mode,canonical_service,thread_id,customer_id,intent_code,channel,actor_email,arguments_json,arguments_hash,idempotency_key,confirmation_required,confirmed_at,status,policy_decision,result_json,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,1,NULL,'confirmation_required','awaiting_explicit_confirmation',NULL,?,NULL)").bind(requestId,definition.code,definition.mode,definition.canonicalService,input.threadId,input.customerId,input.intent,input.channel,input.actor.email,JSON.stringify(args),argumentsHash,input.idempotencyKey,now).run();await audit(db,requestId,"confirmation_requested",input.actor.email,{toolCode:definition.code,argumentsHash});return{status:"confirmation_required",requestId,executed:false,confirmationRequired:true,summary:{tool:definition.code,canonicalService:definition.canonicalService,argumentsHash},autonomousExecution:false};}

export async function confirmAiToolExecution(db:D1Database,input:{actor:AuthenticatedActor;requestId:string}){await ensureAiToolRegistry(db);const row=await db.prepare("SELECT * FROM ai_tool_execution_requests WHERE id=?").bind(input.requestId).first<Row>();if(!row)throw new Error("AI tool request not found");if(String(row.actor_email)!==input.actor.email&&!isStaff(input.actor))throw new Response("AI tool confirmation actor mismatch",{status:403});const definition=tool(String(row.tool_code));await authorizeCustomerScope(db,input.actor,String(row.customer_id),definition);if(definition.mode!=="mutation")throw new Error("Only mutation tools use explicit confirmation");if(String(row.status)==="completed")return{status:"completed",requestId:input.requestId,duplicatePrevented:true,result:parse(row.result_json,null),autonomousExecution:false};if(String(row.status)!=="confirmation_required")throw new Error("AI tool request is not awaiting confirmation");const args=parse<Record<string,unknown>>(row.arguments_json,{}),now=Date.now();await db.prepare("UPDATE ai_tool_execution_requests SET confirmed_at=?,status='executing',policy_decision='customer_confirmed' WHERE id=? AND status='confirmation_required'").bind(now,input.requestId).run();await audit(db,input.requestId,"explicitly_confirmed",input.actor.email,{argumentsHash:row.arguments_hash});try{const result=await executeMutation(db,definition,{requestId:input.requestId,actor:input.actor,threadId:String(row.thread_id),customerId:String(row.customer_id),idempotencyKey:String(row.idempotency_key),args});await db.prepare("UPDATE ai_tool_execution_requests SET status='completed',policy_decision='executed_via_canonical_service',result_json=?,completed_at=? WHERE id=?").bind(JSON.stringify(result),Date.now(),input.requestId).run();await audit(db,input.requestId,"executed_mutation",input.actor.email,{toolCode:definition.code,canonicalService:definition.canonicalService});return{status:"completed",requestId:input.requestId,executed:true,result,autonomousExecution:false};}catch(error){await db.prepare("UPDATE ai_tool_execution_requests SET status='failed',policy_decision='canonical_service_rejected',completed_at=? WHERE id=?").bind(Date.now(),input.requestId).run();await audit(db,input.requestId,"canonical_service_rejected",input.actor.email,{message:error instanceof Error?error.message:"rejected"});throw error;}}

export async function aiToolRegistrySnapshot(db:D1Database,input:{actor:AuthenticatedActor;customerId:string;intent:AiToolIntent;channel:AiToolChannel}){await ensureAiToolRegistry(db);await requireCustomerOwnership(db,input.actor,input.customerId);const allowed=registry.filter(item=>item.intents.includes(input.intent)&&item.channels.includes(input.channel)).map(item=>({...item,permitted:item.mode==="approval_gated"?false:!isStaff(input.actor)||item.staffPermissions.length===0||hasStaffPermission(input.actor,item),autonomousExecution:false}));return{registry:allowed,highImpactApprovalGated:registry.filter(item=>item.mode==="approval_gated").map(item=>item.code),serverAuthoritativeFields:Array.from(forbiddenAuthoritativeFields),productionReady:false};}
