import{ensureCommunicationTables}from"./communication-engine";
import{orchestrateAiTurn}from"./ai-conversation-orchestrator";
import{requestAiHumanHandoff}from"./ai-human-handoff";
import{canonicalVoiceLocale}from"./voice-locale";
import{requireCustomerOwnership,requirePermission,type AuthenticatedActor}from"./server-auth";

type Row=Record<string,unknown>;
const text=(value:unknown)=>String(value??"").trim();

export type VoiceTransportProvider="exotel"|"sandbox_simulator";
export type VoiceSttProvider={provider:string;status:"connected"|"not_connected"|"degraded";transcribe(input:{audioRef:string;language?:string|null}):Promise<{text:string;confidence:number;latencyMs:number;empty?:boolean}>};
export type VoiceTtsProvider={provider:string;status:"connected"|"not_connected"|"degraded";synthesize(input:{text:string;language?:string|null}):Promise<{audioRef:string;latencyMs:number}>};
export const disconnectedStt:VoiceSttProvider={provider:"not_connected",status:"not_connected",async transcribe(){throw new Error("STT provider not connected")}};
export const disconnectedTts:VoiceTtsProvider={provider:"not_connected",status:"not_connected",async synthesize(){throw new Error("TTS provider not connected")}};

export async function ensureAiVoiceUatTables(db:D1Database){await ensureCommunicationTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS ai_voice_calls (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,transport_provider TEXT NOT NULL,direction TEXT NOT NULL,status TEXT NOT NULL,consent_status TEXT NOT NULL,language TEXT,started_at INTEGER NOT NULL,ended_at INTEGER,outcome TEXT,disposition TEXT,live_agent_transfer INTEGER NOT NULL DEFAULT 0,reconnect_count INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_voice_segments (id TEXT PRIMARY KEY,call_id TEXT NOT NULL,message_id TEXT NOT NULL,segment_index INTEGER NOT NULL,speaker TEXT NOT NULL,transcript_text TEXT NOT NULL,stt_provider TEXT,stt_confidence REAL,interrupted INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,UNIQUE(call_id,segment_index))"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_voice_events (id TEXT PRIMARY KEY,call_id TEXT NOT NULL,event_type TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}

async function openThread(db:D1Database,customerId:string){const existing=await db.prepare("SELECT id FROM communication_threads WHERE customer_id=? AND status='open' ORDER BY updated_at DESC LIMIT 1").bind(customerId).first<Row>();if(existing)return text(existing.id);const id=`THREAD-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now();await db.batch([db.prepare("INSERT INTO communication_threads (id,customer_id,booking_id,lead_id,ticket_id,status,assigned_to,sla_due_at,created_at,updated_at) VALUES (?,?,NULL,NULL,NULL,'open','ai-orchestrator',NULL,?,?)").bind(id,customerId,now,now),db.prepare("INSERT OR IGNORE INTO communication_participants (id,thread_id,participant_type,participant_id,display_ref,role,created_at) VALUES (?,?,?,?,?,'customer',?)").bind(crypto.randomUUID(),id,"customer",customerId,customerId,now)]);return id;}

export async function startAiVoiceUatCall(db:D1Database,input:{actor:AuthenticatedActor;customerId:string;direction:"inbound"|"outbound";transportProvider:VoiceTransportProvider;consent:boolean;language?:string|null}){await ensureAiVoiceUatTables(db);await requireCustomerOwnership(db,input.actor,input.customerId);if(!input.consent)throw new Response("Voice consent is required",{status:403});const threadId=await openThread(db,input.customerId),id=`AIVCALL-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now(),locale=canonicalVoiceLocale(input.language);await db.prepare("INSERT INTO ai_voice_calls (id,thread_id,customer_id,transport_provider,direction,status,consent_status,language,started_at,created_by) VALUES (?,?,?,?,?,'active','verified',?,?,?)").bind(id,threadId,input.customerId,input.transportProvider,input.direction,locale,now,input.actor.email).run();return{callId:id,threadId,customerId:input.customerId,status:"active",transportProvider:input.transportProvider,locale,streamingTransport:"uat_interface_only",productionTelephony:false};}

export async function recordAiVoiceTranscriptSegment(db:D1Database,input:{actor:AuthenticatedActor;callId:string;segmentIndex:number;speaker:"customer"|"assistant";text:string;sttProvider?:string|null;sttConfidence?:number|null;interrupted?:boolean}){await ensureAiVoiceUatTables(db);const call=await db.prepare("SELECT * FROM ai_voice_calls WHERE id=? AND status='active'").bind(input.callId).first<Row>();if(!call)throw new Error("Active voice call not found");await requireCustomerOwnership(db,input.actor,text(call.customer_id));const locale=canonicalVoiceLocale(call.language);
 const priorSegment=await db.prepare("SELECT message_id,speaker FROM ai_voice_segments WHERE call_id=? AND segment_index=?").bind(input.callId,input.segmentIndex).first<Row>();
 if(priorSegment){
  if(text(priorSegment.speaker)!==input.speaker)throw new Error("Voice segment index already recorded for the other speaker");
  const priorMessageId=text(priorSegment.message_id);
  if(input.speaker==="customer"){const ai=await orchestrateAiTurn(db,{actor:input.actor,threadId:text(call.thread_id),customerId:text(call.customer_id),inputMessageId:priorMessageId,idempotencyKey:`voice-ai:${input.callId}:${input.segmentIndex}`,channel:"voice"});return{messageId:priorMessageId,threadId:text(call.thread_id),ai,locale,bargeInRecorded:Boolean(input.interrupted),duplicatePrevented:true,productionTelephony:false};}
  return{messageId:priorMessageId,threadId:text(call.thread_id),locale,bargeInRecorded:Boolean(input.interrupted),duplicatePrevented:true,productionTelephony:false};
 }
 const messageId=`MSG-VOICE-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now(),direction=input.speaker==="customer"?"inbound":"outbound";await db.batch([db.prepare("INSERT INTO communication_messages (id,thread_id,customer_id,booking_id,lead_id,ticket_id,direction,channel,purpose,template_key,payload_json,status,provider,provider_reference,idempotency_key,policy_json,created_by,created_at,updated_at) VALUES (?,?,?,NULL,NULL,NULL,?,'voice','transactional','voice_transcript_segment',?,'received',?,NULL,?,?,?, ?,?)").bind(messageId,text(call.thread_id),text(call.customer_id),direction,JSON.stringify({text:input.text,segmentIndex:input.segmentIndex,interrupted:Boolean(input.interrupted),locale}),input.sttProvider||"voice_uat",`voice:${input.callId}:${input.segmentIndex}:${input.speaker}`,JSON.stringify({consentVerified:true,productionTelephony:false,locale}),input.actor.email,now,now),db.prepare("INSERT INTO ai_voice_segments (id,call_id,message_id,segment_index,speaker,transcript_text,stt_provider,stt_confidence,interrupted,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.callId,messageId,input.segmentIndex,input.speaker,input.text,input.sttProvider||null,input.sttConfidence??null,input.interrupted?1:0,now),db.prepare("INSERT INTO ai_voice_events (id,call_id,event_type,detail_json,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),input.callId,input.interrupted?"barge_in":"transcript_segment",JSON.stringify({segmentIndex:input.segmentIndex,speaker:input.speaker,locale}),now)]);
 if(input.speaker==="customer"){const ai=await orchestrateAiTurn(db,{actor:input.actor,threadId:text(call.thread_id),customerId:text(call.customer_id),inputMessageId:messageId,idempotencyKey:`voice-ai:${input.callId}:${input.segmentIndex}`,channel:"voice"});return{messageId,threadId:text(call.thread_id),ai,locale,bargeInRecorded:Boolean(input.interrupted),productionTelephony:false};}
 return{messageId,threadId:text(call.thread_id),locale,bargeInRecorded:Boolean(input.interrupted),productionTelephony:false};}

export async function transferAiVoiceToAgent(db:D1Database,input:{actor:AuthenticatedActor;callId:string;reason:string;confidence?:number|null}){await ensureAiVoiceUatTables(db);const call=await db.prepare("SELECT * FROM ai_voice_calls WHERE id=? AND status='active'").bind(input.callId).first<Row>();if(!call)throw new Error("Active voice call not found");await requireCustomerOwnership(db,input.actor,text(call.customer_id));await requestAiHumanHandoff(db,{actorEmail:input.actor.email,threadId:text(call.thread_id),customerId:text(call.customer_id),reason:"customer_requested_human",confidence:input.confidence??null});const now=Date.now();await db.batch([db.prepare("UPDATE ai_voice_calls SET live_agent_transfer=1,status='transferred',outcome='human_handoff',disposition=?,ended_at=? WHERE id=?").bind(text(input.reason)||"voice_live_agent_transfer",now,input.callId),db.prepare("INSERT INTO ai_voice_events (id,call_id,event_type,detail_json,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),input.callId,"live_agent_transfer",JSON.stringify({reason:input.reason,sameCanonicalThread:true}),now)]);return{callId:input.callId,threadId:text(call.thread_id),sameCanonicalThread:true,status:"transferred"};}

export async function recordAiVoiceTransportFailure(db:D1Database,input:{actor:AuthenticatedActor;callId:string;reason:string;reconnected:boolean}){await ensureAiVoiceUatTables(db);const call=await db.prepare("SELECT id,customer_id,reconnect_count FROM ai_voice_calls WHERE id=?").bind(input.callId).first<Row>();if(!call)throw new Error("Voice call not found");requirePermission(input.actor,"communications.call");await requireCustomerOwnership(db,input.actor,text(call.customer_id));const now=Date.now();await db.prepare("INSERT INTO ai_voice_events (id,call_id,event_type,detail_json,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),input.callId,input.reconnected?"transport_reconnected":"transport_failure",JSON.stringify({reason:input.reason}),now).run();if(input.reconnected)await db.prepare("UPDATE ai_voice_calls SET reconnect_count=reconnect_count+1 WHERE id=?").bind(input.callId).run();else await db.prepare("UPDATE ai_voice_calls SET status='failed',outcome='provider_failure',disposition=?,ended_at=? WHERE id=?").bind(input.reason,now,input.callId).run();return{callId:input.callId,reconnected:input.reconnected,staffFallbackRequired:!input.reconnected,productionTelephony:false};}

export async function completeAiVoiceCall(db:D1Database,input:{actor:AuthenticatedActor;callId:string;outcome:string;disposition:string}){await ensureAiVoiceUatTables(db);const owner=await db.prepare("SELECT customer_id FROM ai_voice_calls WHERE id=?").bind(input.callId).first<Row>();if(!owner)throw new Error("Voice call not found");requirePermission(input.actor,"communications.call");await requireCustomerOwnership(db,input.actor,text(owner.customer_id));const now=Date.now();
 const claim=await db.prepare("UPDATE ai_voice_calls SET status='completed',outcome=?,disposition=?,ended_at=? WHERE id=? AND status='active'").bind(input.outcome,input.disposition,now,input.callId).run();
 if(!Number(claim.meta.changes)){const current=await db.prepare("SELECT status,outcome,disposition FROM ai_voice_calls WHERE id=?").bind(input.callId).first<Row>();if(!current)throw new Error("Voice call not found");return{callId:input.callId,status:text(current.status),outcome:text(current.outcome)||null,disposition:text(current.disposition)||null,completed:false,reason:`Call is ${text(current.status)}, not active`};}
 return{callId:input.callId,status:"completed",outcome:input.outcome,disposition:input.disposition,completed:true};}
