type AuthenticatedActor={email:string;name:string;roleCode:string;permissions:string[];developmentPreview:boolean;identitySource:string;principalType:string;principalKey:string};
type Row=Record<string,unknown>;
type AiBinding={run(model:string,input:unknown):Promise<unknown>};
type VectorIndex={upsert(vectors:Array<{id:string;values:number[];metadata:Record<string,unknown>}>):Promise<unknown>;query(values:number[],options:{topK:number;filter:Record<string,unknown>;returnMetadata?:boolean}):Promise<{matches?:Array<{id:string;score?:number;metadata?:Record<string,unknown>}>}>};
export type AtlasMemoryEnv={AI?:AiBinding;ATLAS_VECTORIZE?:VectorIndex;ATLAS_SECURE_CONTEXT_KEY?:string};
export type AtlasSecurePurpose="human_operation"|"deterministic_dispatch";
export async function ensureAtlasMemoryTables(db:D1Database){
 const statements=[
  "CREATE TABLE IF NOT EXISTS atlas_vector_memories (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,pet_id TEXT,memory_type TEXT NOT NULL DEFAULT 'behavioral',sensitivity TEXT NOT NULL DEFAULT 'non_sensitive' CHECK(sensitivity='non_sensitive'),content_hash TEXT NOT NULL,content_text TEXT NOT NULL,vector_id TEXT NOT NULL UNIQUE,embedding_model TEXT NOT NULL DEFAULT '@cf/baai/bge-m3' CHECK(embedding_model='@cf/baai/bge-m3'),embedding_dimensions INTEGER NOT NULL DEFAULT 1024 CHECK(embedding_dimensions=1024),status TEXT NOT NULL DEFAULT 'active',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_atlas_vector_memories_scope ON atlas_vector_memories(customer_id,pet_id,status,updated_at DESC)",
  "CREATE TABLE IF NOT EXISTS atlas_secure_context_facts (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,pet_id TEXT,fact_type TEXT NOT NULL,sensitivity TEXT NOT NULL CHECK(sensitivity IN ('pii','credential','restricted')),ciphertext_b64 TEXT NOT NULL,iv_b64 TEXT NOT NULL,content_hash TEXT NOT NULL,aad_agent_id TEXT NOT NULL DEFAULT 'legacy',aad_purpose TEXT NOT NULL DEFAULT 'legacy',aad_version INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_atlas_secure_context_scope ON atlas_secure_context_facts(customer_id,pet_id,aad_agent_id,aad_purpose,status,updated_at DESC)",
  "CREATE TABLE IF NOT EXISTS atlas_memory_consents (customer_id TEXT PRIMARY KEY,status TEXT NOT NULL CHECK(status IN ('granted','revoked')),granted_by TEXT,granted_at INTEGER,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS atlas_memory_audit (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,pet_id TEXT,action TEXT NOT NULL,storage_class TEXT NOT NULL CHECK(storage_class IN ('vector','secure_context')),content_hash TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL)",
 ];
 for(const sql of statements)await db.prepare(sql).run();
 for(const ddl of["ALTER TABLE atlas_secure_context_facts ADD COLUMN aad_agent_id TEXT NOT NULL DEFAULT 'legacy'","ALTER TABLE atlas_secure_context_facts ADD COLUMN aad_purpose TEXT NOT NULL DEFAULT 'legacy'","ALTER TABLE atlas_secure_context_facts ADD COLUMN aad_version INTEGER NOT NULL DEFAULT 0"]){try{await db.prepare(ddl).run()}catch(error){if(!/duplicate column|already exists/i.test(error instanceof Error?error.message:String(error)))throw error}}
}
const MODEL="@cf/baai/bge-m3",DIMENSIONS=1024,text=(v:unknown)=>String(v??"").trim();
const b64=(bytes:Uint8Array)=>{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)},fromB64=(value:string)=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
async function hash(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(d)].map(v=>v.toString(16).padStart(2,"0")).join("")}
export function classifyAtlasMemory(content:string){const v=text(content),credential=/(?:gate|door|access|lockbox|alarm|entry)\s*(?:code|pin|number)|password|passcode|api[_ -]?key|secret|bearer\s+token|otp\b/i.test(v),pii=/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b|(?:\+?91[\s-]?)?[6-9]\d{9}\b|\b\d{12}\b|\b(?:aadhaar|pan|passport|bank account|ifsc)\b/i.test(v);return credential?{storage:"secure_context" as const,sensitivity:"credential" as const,factType:"access_credential"}:pii?{storage:"secure_context" as const,sensitivity:"pii" as const,factType:"direct_identifier"}:{storage:"vector" as const,sensitivity:"non_sensitive" as const,factType:"behavioral"};}
async function key(env:AtlasMemoryEnv){const raw=text(env.ATLAS_SECURE_CONTEXT_KEY);if(!raw)throw new Error("ATLAS_SECURE_CONTEXT_KEY is required for secure context");const bytes=fromB64(raw);if(bytes.length!==32)throw new Error("ATLAS_SECURE_CONTEXT_KEY must decode to 32 bytes");return crypto.subtle.importKey("raw",bytes,"AES-GCM",false,["encrypt","decrypt"]);}
function aad(input:{customerId:string;petId?:string|null;agentId:string;purpose:AtlasSecurePurpose}){return new TextEncoder().encode(JSON.stringify({v:1,customer_id:text(input.customerId),pet_id:text(input.petId),agent_id:text(input.agentId),purpose:input.purpose}))}
async function encrypt(env:AtlasMemoryEnv,value:string,boundary:{customerId:string;petId?:string|null;agentId:string;purpose:AtlasSecurePurpose}){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:aad(boundary)},await key(env),new TextEncoder().encode(value));return{ciphertextB64:b64(new Uint8Array(cipher)),ivB64:b64(iv)}}async function decrypt(env:AtlasMemoryEnv,row:Row){if(Number(row.aad_version)!==1)throw new Response("Secure context requires AAD-bound data",{status:409});const purpose=text(row.aad_purpose) as AtlasSecurePurpose;if(!["human_operation","deterministic_dispatch"].includes(purpose))throw new Response("Secure context purpose is invalid",{status:409});const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64(text(row.iv_b64)),additionalData:aad({customerId:text(row.customer_id),petId:text(row.pet_id)||null,agentId:text(row.aad_agent_id),purpose})},await key(env),fromB64(text(row.ciphertext_b64)));return new TextDecoder().decode(plain)}
async function embed(env:AtlasMemoryEnv,value:string){if(!env.AI)throw new Error("Cloudflare AI binding is required");const raw=await env.AI.run(MODEL,{text:[value]}) as Row,data=(raw.data??raw) as unknown,vector=Array.isArray(data)&&Array.isArray(data[0])?data[0]:Array.isArray((data as Row)?.data)?((data as Row).data as unknown[])[0]:null;if(!Array.isArray(vector)||vector.length!==DIMENSIONS)throw new Error("bge-m3 embedding must be exactly 1024 dimensions");return vector.map(Number);}
function requireAuthenticatedActor(actor:AuthenticatedActor){if(!actor||!text(actor.email)||!text(actor.principalKey))throw new Response("Authentication required",{status:401});return actor}
async function consentGranted(db:D1Database,customerId:string){const row=await db.prepare("SELECT status FROM atlas_memory_consents WHERE customer_id=?").bind(customerId).first<Row>();return text(row?.status)==="granted";}
async function authorizeMemory(db:D1Database,actor:AuthenticatedActor,customerId:string){requireAuthenticatedActor(actor);const elevated=actor.developmentPreview||actor.permissions.includes("*")||actor.permissions.includes("customers.manage")||actor.permissions.includes("bookings.manage");if(!elevated){const {requireCustomerOwnership}=await import("./server-auth");await requireCustomerOwnership(db,actor as never,customerId);}return consentGranted(db,customerId);}
export async function setAtlasMemoryConsent(db:D1Database,input:{customerId:string;granted:boolean;actorId:string}){await ensureAtlasMemoryTables(db);const now=Date.now(),status=input.granted?"granted":"revoked";await db.prepare("INSERT INTO atlas_memory_consents(customer_id,status,granted_by,granted_at,updated_by,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(customer_id) DO UPDATE SET status=excluded.status,granted_by=CASE WHEN excluded.status='granted' THEN excluded.granted_by ELSE atlas_memory_consents.granted_by END,granted_at=CASE WHEN excluded.status='granted' THEN excluded.granted_at ELSE atlas_memory_consents.granted_at END,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(input.customerId,status,input.granted?input.actorId:null,input.granted?now:null,input.actorId,now).run();return{customerId:input.customerId,status};}
export async function storeAtlasMemory(db:D1Database,env:AtlasMemoryEnv,input:{customerId:string;petId?:string|null;content:string;actorId:string;agentId?:string;securePurpose?:AtlasSecurePurpose}){
 await ensureAtlasMemoryTables(db);const content=text(input.content);if(!content)throw new Error("Memory content is required");const classification=classifyAtlasMemory(content),contentHash=await hash(content),now=Date.now(),id=`ATM-${crypto.randomUUID().slice(0,12).toUpperCase()}`;
 if(classification.storage==="secure_context"){const agentId=text(input.agentId)||text(input.actorId),purpose=input.securePurpose||"deterministic_dispatch",enc=await encrypt(env,content,{customerId:input.customerId,petId:input.petId,agentId,purpose});await db.prepare("INSERT INTO atlas_secure_context_facts(id,customer_id,pet_id,fact_type,sensitivity,ciphertext_b64,iv_b64,content_hash,aad_agent_id,aad_purpose,aad_version,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,1,'active',?,?,?)").bind(id,input.customerId,input.petId||null,classification.factType,classification.sensitivity,enc.ciphertextB64,enc.ivB64,contentHash,agentId,purpose,input.actorId,now,now).run();await db.prepare("INSERT INTO atlas_memory_audit(id,customer_id,pet_id,action,storage_class,content_hash,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(`AMA-${crypto.randomUUID()}`,input.customerId,input.petId||null,"store","secure_context",contentHash,input.actorId,now).run();return{id,storage:"secure_context" as const,sensitivity:classification.sensitivity,vectorized:false,aadBound:true,agentId,purpose};}
 if(!env.ATLAS_VECTORIZE)throw new Error("ATLAS_VECTORIZE binding is required");const values=await embed(env,content),vectorId=`ATV-${crypto.randomUUID()}`;await env.ATLAS_VECTORIZE.upsert([{id:vectorId,values,metadata:{customer_id:input.customerId,pet_id:input.petId||"",sensitivity:"non_sensitive",memory_id:id}}]);await db.prepare("INSERT INTO atlas_vector_memories(id,customer_id,pet_id,memory_type,sensitivity,content_hash,content_text,vector_id,embedding_model,embedding_dimensions,status,created_by,created_at,updated_at) VALUES (?,?,?,'behavioral','non_sensitive',?,?,?,?,1024,'active',?,?,?)").bind(id,input.customerId,input.petId||null,contentHash,content,vectorId,MODEL,input.actorId,now,now).run();await db.prepare("INSERT INTO atlas_memory_audit(id,customer_id,pet_id,action,storage_class,content_hash,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(`AMA-${crypto.randomUUID()}`,input.customerId,input.petId||null,"store","vector",contentHash,input.actorId,now).run();return{id,storage:"vector" as const,sensitivity:"non_sensitive" as const,vectorized:true};
}
export async function retrieveAtlasMemoryForLlm(db:D1Database,env:AtlasMemoryEnv,input:{actor:AuthenticatedActor;customerId:string;petId?:string|null;query:string;topK?:number}){await ensureAtlasMemoryTables(db);if(!await authorizeMemory(db,input.actor,input.customerId))return{matches:[],secureContextExcluded:true,consentDenied:true};if(classifyAtlasMemory(input.query).storage==="secure_context")return{matches:[],secureContextExcluded:true,consentDenied:false};if(!env.ATLAS_VECTORIZE)throw new Error("ATLAS_VECTORIZE binding is required");const values=await embed(env,input.query),filter:Record<string,unknown>={customer_id:input.customerId,pet_id:input.petId||"",sensitivity:"non_sensitive"},result=await env.ATLAS_VECTORIZE.query(values,{topK:Math.max(1,Math.min(20,input.topK||6)),filter,returnMetadata:true}),ids=(result.matches||[]).map(m=>text(m.metadata?.memory_id)).filter(Boolean);if(!ids.length)return{matches:[],secureContextExcluded:true,consentDenied:false};const rows=await db.prepare(`SELECT id,customer_id,pet_id,memory_type,sensitivity,content_text,vector_id,updated_at FROM atlas_vector_memories WHERE customer_id=? AND sensitivity='non_sensitive' AND status='active' AND id IN (${ids.map(()=>'?').join(",")})`).bind(input.customerId,...ids).all<Row>();return{matches:rows.results,secureContextExcluded:true,consentDenied:false};}
export async function readAtlasSecureContext(db:D1Database,env:AtlasMemoryEnv,input:{actor:AuthenticatedActor;customerId:string;petId?:string|null;agentId:string;purpose:AtlasSecurePurpose}){await ensureAtlasMemoryTables(db);if(!await authorizeMemory(db,input.actor,input.customerId))throw new Response("Atlas memory consent is required",{status:403});const agentId=text(input.agentId);if(!agentId)throw new Response("Atlas secure-context agent identity is required",{status:403});const rows=await db.prepare("SELECT * FROM atlas_secure_context_facts WHERE customer_id=? AND (pet_id IS NULL OR pet_id=?) AND aad_agent_id=? AND aad_purpose=? AND aad_version=1 AND status='active' ORDER BY updated_at DESC LIMIT 50").bind(input.customerId,input.petId||null,agentId,input.purpose).all<Row>(),out=[] as Array<{id:string;factType:string;sensitivity:string;value:string}>;for(const row of rows.results)out.push({id:text(row.id),factType:text(row.fact_type),sensitivity:text(row.sensitivity),value:await decrypt(env,row)});await db.prepare("INSERT INTO atlas_memory_audit(id,customer_id,pet_id,action,storage_class,content_hash,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(`AMA-${crypto.randomUUID()}`,input.customerId,input.petId||null,`read:${input.purpose}`,"secure_context","not_exposed",input.actor.email,Date.now()).run();return{facts:out,forLlm:false,aadBound:true,agentId:input.agentId,purpose:input.purpose};}
export const ATLAS_VECTOR_MEMORY_MODEL=MODEL;
export const ATLAS_VECTOR_DIMENSIONS=DIMENSIONS;
export const ATLAS_VECTOR_METRIC="cosine" as const;
