import {loadOwnedBoardingStay} from "./boarding-customer-care";
export type BoardingStayEvent={id:string;event_type:string;actor_id:string;detail:Record<string,unknown>;created_at:number};
export type BoardingStay={id:string;booking_id:string;customer_id:string;host_provider_id:string;city_id:string;zone_id:string;package_code:string;package_name?:string;provider_name?:string;check_in_at:string;check_out_at:string;billed_units:number;pet_count:number;status:string;updated_at:number;care_plan_status:string;check_in_status:string;check_out_status:string;extension_status:string;booking_status?:string;total_amount?:number;amount_due_now?:number;carePlan?:{status:string;plan:Record<string,unknown>;updatedAt:number}|null;extension?:{id:string;requested_end:string;status:string;reason:string;created_at:number}|null;events:BoardingStayEvent[]};
export type BoardingStayAction="accept"|"decline"|"submit_care_plan"|"check_in"|"care_event"|"request_extension"|"host_unavailable"|"no_show"|"check_out";
type BoardingStayScope={providerId?:string|null;cityId?:string|null;zoneId?:string|null;customerId?:string|null;bookingId?:string|null};
async function body<T>(response:Response){const payload=await response.json() as {data?:T;error?:string;scope?:BoardingStayScope};if(!response.ok)throw new Error(payload.error||"Boarding stay request failed");return payload;}

function normalizeEvent(value:unknown):BoardingStayEvent{const row=(value&&typeof value==="object"&&!Array.isArray(value)?value:{}) as Record<string,unknown>;return{id:String(row.id||""),event_type:String(row.event_type??row.eventType??""),actor_id:String(row.actor_id??row.actorId??"provider_or_system"),detail:(row.detail&&typeof row.detail==="object"&&!Array.isArray(row.detail)?row.detail:{}) as Record<string,unknown>,created_at:Number(row.created_at??row.createdAt??0)};}
function normalizeExtension(value:unknown):BoardingStay["extension"]{if(!value||typeof value!=="object"||Array.isArray(value))return null;const row=value as Record<string,unknown>;return{id:String(row.id||""),requested_end:String(row.requested_end??row.requestedEnd??""),status:String(row.status||""),reason:String(row.reason||""),created_at:Number(row.created_at??row.createdAt??0)};}
function normalizeProviderStay(row:Record<string,unknown>):BoardingStay{return{
 id:String(row.id||""),booking_id:String(row.booking_id??row.bookingId??""),customer_id:String(row.customer_id??row.customerId??""),host_provider_id:String(row.host_provider_id??row.hostProviderId??""),city_id:String(row.city_id??row.cityId??""),zone_id:String(row.zone_id??row.zoneId??""),package_code:String(row.package_code??row.packageCode??""),package_name:String(row.package_name??row.packageName??""),provider_name:String(row.provider_name??row.providerName??""),check_in_at:String(row.check_in_at??row.checkInAt??""),check_out_at:String(row.check_out_at??row.checkOutAt??""),billed_units:Number(row.billed_units??row.billedUnits??0),pet_count:Number(row.pet_count??row.petCount??0),status:String(row.status||""),updated_at:Number(row.updated_at??row.updatedAt??0),care_plan_status:String(row.care_plan_status??row.carePlanStatus??""),check_in_status:String(row.check_in_status??row.checkInStatus??"pending"),check_out_status:String(row.check_out_status??row.checkOutStatus??"pending"),extension_status:String(row.extension_status??row.extensionStatus??"none"),booking_status:row.booking_status!=null?String(row.booking_status):row.bookingStatus!=null?String(row.bookingStatus):undefined,total_amount:row.total_amount!=null?Number(row.total_amount):row.totalAmount!=null?Number(row.totalAmount):undefined,amount_due_now:row.amount_due_now!=null?Number(row.amount_due_now):row.amountDueNow!=null?Number(row.amountDueNow):undefined,carePlan:(row.carePlan as BoardingStay["carePlan"])??null,extension:normalizeExtension(row.extension),events:Array.isArray(row.events)?row.events.map(normalizeEvent):[]};}
export async function loadOwnBoardingStays(){const response=await fetch("/api/boarding-stays",{cache:"no-store"}),payload=await body<Record<string,unknown>[]>(response);return{stays:(payload.data??[]).map(normalizeProviderStay),providerId:payload.scope?.providerId??null,cityId:payload.scope?.cityId??null,zoneId:payload.scope?.zoneId??null};}
export async function loadCustomerBoardingStay(bookingId:string){return loadOwnedBoardingStay(bookingId);}

export async function updateBoardingStay(input:{stayId:string;action:BoardingStayAction;idempotencyKey:string;reason?:string;careEventType?:string;detail?:Record<string,unknown>;requestedEnd?:string;carePlan?:Record<string,string>}){const payload=await body<Record<string,unknown>>(await fetch("/api/boarding-stays",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)}));return payload.data??{};}
