import{ensureBoardingGovernanceTables}from"./boarding-governance";

type Row=Record<string,unknown>;
export type BoardingStayAction="accept"|"decline"|"submit_care_plan"|"check_in"|"care_event"|"request_extension"|"host_unavailable"|"no_show"|"check_out";
export type BoardingCarePlan={feeding?:string;medication?:string;emergencyContact?:string;vet?:string;specialInstructions?:string};
export type BoardingStayMutation={stayId:string;action:BoardingStayAction;actorId:string;idempotencyKey:string;reason?:string;carePlan?:BoardingCarePlan;careEventType?:string;detail?:Record<string,unknown>;requestedEnd?:string};

export async function ensureBoardingStayLifecycleTables(db:D1Database){await ensureBoardingGovernanceTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS boarding_stay_action_keys (idempotency_key TEXT PRIMARY KEY,stay_id TEXT NOT NULL,action TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS boarding_capacity_locks (stay_id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,capacity_units INTEGER NOT NULL,family_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_boarding_capacity_overlap ON boarding_capacity_locks(provider_id,status,starts_at,ends_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS boarding_care_plan_snapshots (stay_id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,plan_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ready',updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS boarding_extension_requests (id TEXT PRIMARY KEY,stay_id TEXT NOT NULL,booking_id TEXT NOT NULL,requested_end TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'commercial_quote_required',reason TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS boarding_recovery_cases (id TEXT PRIMARY KEY,stay_id TEXT NOT NULL,booking_id TEXT NOT NULL,failed_provider_id TEXT NOT NULL,reason_code TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ops_escalation',replacement_provider_id TEXT,detail_json TEXT NOT NULL DEFAULT '{}',opened_at INTEGER NOT NULL,resolved_at INTEGER,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS booking_customer_notifications (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,customer_id TEXT,channel TEXT NOT NULL,template_code TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',event_id TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 ]);}

function parse<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??"")) as T;}catch{return fallback;}}
async function stayRow(db:D1Database,stayId:string){await ensureBoardingStayLifecycleTables(db);return db.prepare("SELECT s.*,b.schedule_group_id,b.status booking_status,b.provider_id booking_provider_id FROM boarding_stays s JOIN canonical_bookings b ON b.id=s.booking_id WHERE s.id=? AND b.service_code='boarding'").bind(stayId).first<Row>();}
export async function getBoardingStay(db:D1Database,stayId:string){return stayRow(db,stayId);}

export async function listBoardingStays(db:D1Database,input:{providerId?:string;customerId?:string;bookingId?:string}){await ensureBoardingStayLifecycleTables(db);const where=["b.service_code='boarding'"],binds:unknown[]=[];if(input.providerId){where.push("s.host_provider_id=?");binds.push(input.providerId);}if(input.customerId){where.push("s.customer_id=?");binds.push(input.customerId);}if(input.bookingId){where.push("s.booking_id=?");binds.push(input.bookingId);}const rows=await db.prepare(`SELECT s.*,b.schedule_group_id,b.status booking_status,b.total_amount,pay.amount_due_now,b.package_name,pr.name provider_name FROM boarding_stays s JOIN canonical_bookings b ON b.id=s.booking_id LEFT JOIN booking_payments pay ON pay.booking_id=b.id LEFT JOIN provider_capacity_profiles pr ON pr.id=s.host_provider_id WHERE ${where.join(" AND ")} ORDER BY s.check_in_at DESC`).bind(...binds).all<Row>();const out=[];for(const row of rows.results){const care=await db.prepare("SELECT status,plan_json,updated_at FROM boarding_care_plan_snapshots WHERE stay_id=?").bind(row.id).first<Row>();const extension=await db.prepare("SELECT id,requested_end,status,reason,created_at FROM boarding_extension_requests WHERE stay_id=? ORDER BY created_at DESC LIMIT 1").bind(row.id).first<Row>();const events=await db.prepare("SELECT id,event_type,actor_id,detail_json,created_at FROM boarding_stay_events WHERE stay_id=? ORDER BY created_at DESC LIMIT 30").bind(row.id).all<Row>();out.push({...row,carePlan:care?{status:String(care.status),plan:parse(care.plan_json,{}),updatedAt:Number(care.updated_at)}:null,extension:extension??null,events:events.results.map(item=>({...item,detail:parse(item.detail_json,{})}))});}return out;}

async function event(db:D1Database,stay:Row,eventType:string,actorId:string,detail:unknown={}){const id=crypto.randomUUID();await db.prepare("INSERT INTO boarding_stay_events (id,stay_id,booking_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,stay.id,stay.booking_id,eventType,actorId,JSON.stringify(detail),Date.now()).run();return id;}
async function notify(db:D1Database,stay:Row,eventId:string,message:string){for(const channel of ["push","whatsapp"])await db.prepare("INSERT INTO booking_customer_notifications (id,booking_id,customer_id,channel,template_code,message,status,event_id,created_at) VALUES (?,?,?,?,?,?, 'queued',?,?)").bind(crypto.randomUUID(),stay.booking_id,stay.customer_id,channel,"boarding_stay_update",message,eventId,Date.now()).run();}

async function assertCapacity(db:D1Database,stay:Row,providerId=String(stay.host_provider_id),endsAt=String(stay.check_out_at)){const profile=await db.prepare("SELECT h.max_guest_pets,h.one_family_only,h.active,h.home_verified,h.kyc_status,h.background_check_status,p.live,p.status provider_status,p.services_json,p.zones_json FROM boarding_host_profiles h JOIN provider_capacity_profiles p ON p.id=h.provider_id WHERE h.provider_id=?").bind(providerId).first<Row>();if(!profile||Number(profile.active)!==1||!Boolean(profile.live)||String(profile.provider_status)!=="active")throw new Response("Boarding host is not active",{status:409});if(Number(profile.home_verified)!==1||String(profile.kyc_status)!=="verified"||String(profile.background_check_status)!=="verified")throw new Response("Boarding host verification is incomplete",{status:409});if(!parse<string[]>(profile.services_json,[]).includes("boarding")||!parse<string[]>(profile.zones_json,[]).includes(String(stay.zone_id)))throw new Response("Boarding host is not eligible for this zone",{status:409});const blocked=await db.prepare("SELECT id FROM provider_unavailability WHERE provider_id=? AND status='active' AND starts_at<? AND ends_at>? LIMIT 1").bind(providerId,endsAt,stay.check_in_at).first<Row>();if(blocked)throw new Response("Boarding host is unavailable during this stay window",{status:409});const locks=await db.prepare("SELECT stay_id,capacity_units,family_key FROM boarding_capacity_locks WHERE provider_id=? AND status='active' AND stay_id!=? AND starts_at<? AND ends_at>?").bind(providerId,stay.id,endsAt,stay.check_in_at).all<Row>();if(Number(profile.one_family_only)===1&&locks.results.length)throw new Response("This host accepts only one family at a time",{status:409});const used=locks.results.reduce((sum,row)=>sum+Number(row.capacity_units||0),0),max=Math.max(1,Number(profile.max_guest_pets||1));if(used+Number(stay.pet_count)>max)throw new Response("Boarding host capacity is no longer available",{status:409});return{maxGuestPets:max,usedGuestPets:used,availableGuestPets:max-used,oneFamilyOnly:Boolean(profile.one_family_only)};}

async function lockCapacity(db:D1Database,stay:Row,endsAt=String(stay.check_out_at)){const capacity=await assertCapacity(db,stay,String(stay.host_provider_id),endsAt),now=Date.now();await db.prepare("INSERT INTO boarding_capacity_locks (stay_id,booking_id,provider_id,starts_at,ends_at,capacity_units,family_key,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'active',?,?) ON CONFLICT(stay_id) DO UPDATE SET provider_id=excluded.provider_id,starts_at=excluded.starts_at,ends_at=excluded.ends_at,capacity_units=excluded.capacity_units,family_key=excluded.family_key,status='active',updated_at=excluded.updated_at").bind(stay.id,stay.booking_id,stay.host_provider_id,stay.check_in_at,endsAt,stay.pet_count,stay.customer_id,now,now).run();return capacity;}
async function releaseCapacity(db:D1Database,stayId:string){await db.prepare("UPDATE boarding_capacity_locks SET status='released',updated_at=? WHERE stay_id=? AND status='active'").bind(Date.now(),stayId).run();}

async function priorResult(db:D1Database,key:string){const row=await db.prepare("SELECT result_json FROM boarding_stay_action_keys WHERE idempotency_key=?").bind(key).first<Row>();return row?parse<Record<string,unknown>>(row.result_json,{}):null;}
async function remember(db:D1Database,input:BoardingStayMutation,result:unknown){await db.prepare("INSERT INTO boarding_stay_action_keys (idempotency_key,stay_id,action,result_json,created_at) VALUES (?,?,?,?,?)").bind(input.idempotencyKey,input.stayId,input.action,JSON.stringify(result),Date.now()).run();return result;}

export async function mutateBoardingStay(db:D1Database,input:BoardingStayMutation){if(!input.stayId||!input.action||!input.actorId||!input.idempotencyKey)throw new Response("Stay, action, actor and idempotency key are required",{status:400});await ensureBoardingStayLifecycleTables(db);const prior=await priorResult(db,input.idempotencyKey);if(prior)return{...prior,duplicatePrevented:true};const stay=await stayRow(db,input.stayId);if(!stay)throw new Response("Boarding stay not found",{status:404});const now=Date.now(),status=String(stay.status),bookingId=String(stay.booking_id),groupId=String(stay.schedule_group_id||"");
 if(input.action==="accept"){
  if(status!=="awaiting_host_acceptance"&&status!=="recovery_pending")throw new Response("Boarding stay is not awaiting host acceptance",{status:409});if(String(stay.host_provider_id)!==String(stay.booking_provider_id))throw new Response("Stay host no longer matches the canonical booking",{status:409});const offer=groupId?await db.prepare("SELECT * FROM provider_assignment_offers WHERE group_id=?").bind(groupId).first<Row>():null;if(offer){if(String(offer.provider_id)!==String(stay.host_provider_id)||String(offer.status)!=="pending")throw new Response("No pending host offer is available",{status:409});if(Number(offer.expires_at)<now)throw new Response("Host acceptance offer expired; Operations recovery is required",{status:409});}
  const capacity=await lockCapacity(db,stay);const statements=[db.prepare("UPDATE boarding_stays SET status='confirmed',updated_at=? WHERE id=?").bind(now,stay.id),db.prepare("UPDATE canonical_bookings SET status=CASE WHEN status IN ('confirmed','created') THEN 'assigned' ELSE status END,updated_at=? WHERE id=?").bind(now,bookingId)];if(offer)statements.push(db.prepare("UPDATE provider_assignment_offers SET status='accepted',responded_at=?,response_reason='Accepted in Host workspace',updated_at=? WHERE group_id=?").bind(now,now,groupId));await db.batch(statements);const eventId=await event(db,stay,"host_accepted",input.actorId,{providerId:stay.host_provider_id,capacity});await notify(db,stay,eventId,"Your PawSpace boarding host has accepted the stay. Your booking ID and stay window are unchanged.");return remember(db,input,{stayId:stay.id,bookingId,status:"confirmed",capacity});
 }
 if(input.action==="decline"||input.action==="host_unavailable"||input.action==="no_show"){
  const reason=String(input.reason||"").trim();if(reason.length<3)throw new Response("A recovery reason is required",{status:400});await releaseCapacity(db,String(stay.id));if(groupId)await db.prepare("UPDATE provider_assignment_offers SET status=?,responded_at=?,response_reason=?,updated_at=? WHERE group_id=? AND provider_id=? AND status='pending'").bind(input.action==="decline"?"declined":"cancelled",now,reason,now,groupId,stay.host_provider_id).run();const recoveryId=crypto.randomUUID();await db.batch([db.prepare("UPDATE boarding_stays SET status='recovery_pending',updated_at=? WHERE id=?").bind(now,stay.id),db.prepare("UPDATE canonical_bookings SET status='reassignment_needed',updated_at=? WHERE id=?").bind(now,bookingId),db.prepare("UPDATE scheduling_assignment_decisions SET status='reassignment_needed',actor_id=?,reason=?,updated_at=? WHERE group_id=?").bind(input.actorId,reason,now,groupId),db.prepare("INSERT INTO boarding_recovery_cases (id,stay_id,booking_id,failed_provider_id,reason_code,status,replacement_provider_id,detail_json,opened_at,resolved_at,updated_at) VALUES (?,?,?,?,?,'ops_escalation',NULL,?,?,NULL,?)").bind(recoveryId,stay.id,bookingId,stay.host_provider_id,input.action,JSON.stringify({reason,bookingPreserved:true}),now,now)]);const eventId=await event(db,stay,`host_${input.action}`,input.actorId,{reason,recoveryId});await notify(db,stay,eventId,"Your boarding host needs to be recovered. PawSpace Operations is protecting the same booking while a replacement is arranged.");return remember(db,input,{stayId:stay.id,bookingId,status:"ops_escalation",recoveryId});
 }
 if(input.action==="submit_care_plan"){
  if(["completed","cancelled"].includes(status))throw new Response("Care plan cannot change after the stay is closed",{status:409});const plan=input.carePlan??{};if(!String(plan.emergencyContact||"").trim()||!String(plan.vet||"").trim())throw new Response("Boarding care plan requires emergency contact and vet details",{status:409});await db.batch([db.prepare("INSERT INTO boarding_care_plan_snapshots (stay_id,booking_id,plan_json,status,updated_by,updated_at) VALUES (?,?,?,'ready',?,?) ON CONFLICT(stay_id) DO UPDATE SET plan_json=excluded.plan_json,status='ready',updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(stay.id,bookingId,JSON.stringify(plan),input.actorId,now),db.prepare("UPDATE boarding_stays SET care_plan_status='ready',updated_at=? WHERE id=?").bind(now,stay.id)]);await event(db,stay,"care_plan_ready",input.actorId,{fields:Object.keys(plan)});return remember(db,input,{stayId:stay.id,bookingId,status:"care_plan_ready"});
 }
 if(input.action==="check_in"){
  if(status!=="confirmed")throw new Response("Host acceptance is required before check-in",{status:409});if(String(stay.care_plan_status)!=="ready")throw new Response("A ready care plan is required before check-in",{status:409});if(String(stay.check_in_status)==="complete")throw new Response("Boarding stay is already checked in",{status:409});if(new Date(String(stay.check_out_at)).getTime()<=now)throw new Response("Cannot check in after the stay window has ended",{status:409});const capacity=await lockCapacity(db,stay);await db.batch([db.prepare("UPDATE boarding_stays SET status='in_progress',check_in_status='complete',updated_at=? WHERE id=?").bind(now,stay.id),db.prepare("UPDATE canonical_bookings SET status='in_progress',updated_at=? WHERE id=?").bind(now,bookingId)]);const eventId=await event(db,stay,"checked_in",input.actorId,{capacity});await notify(db,stay,eventId,"Your pet has been checked in with the PawSpace host. Care updates will be recorded against this stay.");return remember(db,input,{stayId:stay.id,bookingId,status:"in_progress",capacity});
 }
 if(input.action==="care_event"){
  if(status!=="in_progress")throw new Response("Care events can be logged only during an active stay",{status:409});const eventType=String(input.careEventType||"").trim();if(!["meal","walk","medication","photo_update","general_update","incident"].includes(eventType))throw new Response("Unsupported Boarding care event",{status:400});const eventId=await event(db,stay,`care_${eventType}`,input.actorId,input.detail??{});return remember(db,input,{stayId:stay.id,bookingId,status:"logged",eventId,eventType});
 }
 if(input.action==="request_extension"){
  if(!["confirmed","in_progress"].includes(status))throw new Response("Only an accepted or active stay can request an extension",{status:409});const requestedEnd=String(input.requestedEnd||"").trim(),endMs=new Date(requestedEnd).getTime(),currentEnd=new Date(String(stay.check_out_at)).getTime();if(!Number.isFinite(endMs)||endMs<=currentEnd)throw new Response("Extension end must be later than the current checkout",{status:400});const reason=String(input.reason||"Customer requested extension").trim();await assertCapacity(db,stay,String(stay.host_provider_id),requestedEnd);const id=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO boarding_extension_requests (id,stay_id,booking_id,requested_end,status,reason,actor_id,created_at,updated_at) VALUES (?,?,?,?,'commercial_quote_required',?,?,?,?)").bind(id,stay.id,bookingId,requestedEnd,reason,input.actorId,now,now),db.prepare("UPDATE boarding_stays SET extension_status='commercial_quote_required',updated_at=? WHERE id=?").bind(now,stay.id)]);await event(db,stay,"extension_requested",input.actorId,{extensionId:id,requestedEnd,commercialPolicy:"quote_required",stayWindowUnchanged:true});return remember(db,input,{stayId:stay.id,bookingId,status:"commercial_quote_required",extensionId:id,requestedEnd,stayWindowUnchanged:true});
 }
 if(input.action==="check_out"){
  if(status!=="in_progress"||String(stay.check_in_status)!=="complete")throw new Response("Only a checked-in active stay can be checked out",{status:409});await releaseCapacity(db,String(stay.id));await db.batch([db.prepare("UPDATE boarding_stays SET status='completed',check_out_status='complete',updated_at=? WHERE id=?").bind(now,stay.id),db.prepare("UPDATE canonical_bookings SET status='completed',updated_at=? WHERE id=?").bind(now,bookingId),db.prepare("UPDATE scheduling_reservations SET status='completed' WHERE group_id=? AND service_code='boarding' AND status!='cancelled'").bind(groupId)]);const eventId=await event(db,stay,"checked_out",input.actorId,{payout:"rule_pending",tax:"configuration_required"});await notify(db,stay,eventId,"Your PawSpace boarding stay is checked out and completed. Any payout, tax or settlement remains governed separately.");return remember(db,input,{stayId:stay.id,bookingId,status:"completed",payout:"rule_pending",tax:"configuration_required"});
 }
 throw new Response("Unsupported Boarding stay action",{status:400});
}
