export type BoardingProofMedia={id:string;purpose:string;mime_type:string;size_bytes:number;scan_status:string;access_status:string;retention_status:string;synthetic:number;created_at:number;updated_at:number;ref:string;proofReady:boolean};
export type BoardingMedication={id:string;medication_name:string;dose:string;administered_at:string;media_id:string;mediaRef:string;note:string;recorded_by:string;created_at:number};
export type BoardingIncident={id:string;severity:string;summary:string;action_taken:string;media_id?:string|null;mediaRef?:string|null;status:string;ops_status:string;notification_status:string;customer_acknowledged_at?:number|null;resolution?:string|null;resolved_at?:number|null;reported_at:number};
export type BoardingProofSnapshot={stay:{id:string;bookingId:string;providerId:string;customerId:string;status:string;carePlanStatus:string;checkInAt:string;checkOutAt:string};media:BoardingProofMedia[];medication:BoardingMedication[];incidents:BoardingIncident[];storage:{mode:string;adapterConnected:boolean;rawPublicUrls:boolean};communications:{mode:string;liveDelivery:boolean}};
export type BoardingProofAction="prepare_media"|"sandbox_finalize_media"|"record_media_scan"|"revoke_media"|"record_daily_update"|"record_medication"|"report_incident"|"acknowledge_incident"|"resolve_incident";

type Payload<T>={data?:T;error?:string};
async function read<T>(response:Response){const payload=await response.json() as Payload<T>;if(!response.ok)throw new Error(payload.error||"Boarding proof request failed");return payload.data as T;}
export async function loadBoardingProof(stayId:string,customer=false){return read<BoardingProofSnapshot>(await fetch(`/api/boarding-proof?${customer?"scope=customer&":""}stayId=${encodeURIComponent(stayId)}`,{cache:"no-store"}));}
export async function updateBoardingProof(input:{stayId:string;action:BoardingProofAction;idempotencyKey:string;purpose?:"boarding_checkin"|"stay_update"|"boarding_medication"|"boarding_incident"|"boarding_checkout";mimeType?:string;sizeBytes?:number;sha256?:string;uploadToken?:string;storageObjectId?:string;mediaRef?:string;scanResult?:"clean"|"rejected";reason?:string;note?:string;medicationName?:string;dose?:string;administeredAt?:string;incidentId?:string;severity?:"attention"|"urgent"|"emergency";summary?:string;actionTaken?:string;resolution?:string}){return read<Record<string,unknown>>(await fetch("/api/boarding-proof",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)}));}
