type Db=D1Database;type Row=Record<string,unknown>;
const DAY=86_400_000;const text=(v:unknown)=>String(v??'').trim();
export async function ensureCommunicationGovernance(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS communication_consent (customer_id TEXT PRIMARY KEY,global_opt_out INTEGER NOT NULL DEFAULT 0,whatsapp_allowed INTEGER,email_allowed INTEGER,voice_allowed INTEGER,sms_allowed INTEGER,source TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_frequency_reservations (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,channel TEXT NOT NULL,message_id TEXT NOT NULL,window_started_at INTEGER NOT NULL,reserved_at INTEGER NOT NULL,UNIQUE(channel,message_id))"),
 db.prepare("CREATE INDEX IF NOT EXISTS communication_frequency_identity_idx ON communication_frequency_reservations(customer_id,channel,reserved_at)"),
]);}
export async function recordGlobalOptOut(db:Db,input:{customerId:string;source:string;actorId:string;asOf?:number}){await ensureCommunicationGovernance(db);const now=input.asOf??Date.now();await db.prepare("INSERT INTO communication_consent(customer_id,global_opt_out,whatsapp_allowed,email_allowed,voice_allowed,sms_allowed,source,updated_by,updated_at) VALUES (?,1,0,0,0,0,?,?,?) ON CONFLICT(customer_id) DO UPDATE SET global_opt_out=1,whatsapp_allowed=0,email_allowed=0,voice_allowed=0,sms_allowed=0,source=excluded.source,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(input.customerId,text(input.source)||'opt_out',input.actorId,now).run();return{customerId:input.customerId,optedOut:true};}
export async function centralConsentAllows(db:Db,customerId:string,channel:string){await ensureCommunicationGovernance(db);const row=await db.prepare("SELECT * FROM communication_consent WHERE customer_id=?").bind(customerId).first<Row>();if(!row)return true;if(Number(row.global_opt_out||0)===1)return false;const key=channel==='whatsapp'?'whatsapp_allowed':channel==='email'?'email_allowed':channel==='voice'?'voice_allowed':channel==='sms'?'sms_allowed':null;if(!key)return true;return row[key]==null?true:Number(row[key])===1;}
export async function reserveCommunicationFrequency(db:Db,input:{customerId:string;channel:string;messageId:string;asOf?:number}){await ensureCommunicationGovernance(db);const now=input.asOf??Date.now();const prior=await db.prepare("SELECT id FROM communication_frequency_reservations WHERE channel=? AND message_id=?").bind(input.channel,input.messageId).first<Row>();if(prior)return{allowed:true,cap:input.channel==='voice'?1:input.channel==='whatsapp'?2:null,releaseAt:null,duplicatePrevented:true};const spec=input.channel==='voice'?{cap:1,window:14*DAY}:input.channel==='whatsapp'?{cap:2,window:7*DAY}:null;if(!spec)return{allowed:true,cap:null,releaseAt:null};const since=now-spec.window;const claim=await db.prepare("INSERT INTO communication_frequency_reservations(id,customer_id,channel,message_id,window_started_at,reserved_at) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM communication_frequency_reservations WHERE customer_id=? AND channel=? AND reserved_at>=?) < ?").bind(`CFR-${crypto.randomUUID()}`,input.customerId,input.channel,input.messageId,since,now,input.customerId,input.channel,since,spec.cap).run();if(Number(claim.meta?.changes||0)>0)return{allowed:true,cap:spec.cap,releaseAt:null};const oldest=await db.prepare("SELECT MIN(reserved_at) t FROM communication_frequency_reservations WHERE customer_id=? AND channel=? AND reserved_at>=?").bind(input.customerId,input.channel,since).first<Row>();return{allowed:false,cap:spec.cap,releaseAt:Number(oldest?.t||now)+spec.window};}
