import { seedCommunicationAdapters } from "./communication-adapters";
import { dispatchExternalCommunication } from "./communication-provider-boundary";
import { failOutboxAttempt } from "./communication-engine";

type Db=D1Database;
type Env=Record<string,unknown>;
type Row=Record<string,unknown>;

const text=(value:unknown)=>String(value??"").trim();

async function recipientFor(db:Db,customerId:string,channel:string){const row=await db.prepare("SELECT primary_phone,secondary_phone,email FROM canonical_customers WHERE id=?").bind(customerId).first<Row>().catch(()=>null);if(!row)return null;if(channel==="email")return text(row.email)||null;if(channel==="sms")return text(row.primary_phone)||text(row.secondary_phone)||null;return null;}
async function configuredAdapter(db:Db,channel:string){const row=await db.prepare("SELECT adapter_name FROM communication_adapter_configs WHERE channel=? AND environment='sandbox' AND status='sandbox_ready' AND credentials_status='configured' ORDER BY priority ASC,adapter_name ASC LIMIT 1").bind(channel).first<Row>();return text(row?.adapter_name)||null;}
async function recoverStaleClaims(db:Db,asOf:number){const staleBefore=asOf-5*60_000;const result=await db.prepare("UPDATE communication_outbox SET status='retry_pending',next_attempt_at=?,last_error='stale_dispatch_claim_recovered',locked_at=NULL,updated_at=? WHERE status='dispatching' AND locked_at IS NOT NULL AND locked_at<=?").bind(asOf,asOf,staleBefore).run();await db.prepare("UPDATE communication_messages SET status='retry_pending',updated_at=? WHERE id IN (SELECT message_id FROM communication_outbox WHERE status='retry_pending' AND last_error='stale_dispatch_claim_recovered' AND updated_at=?) AND status NOT IN ('delivered','read','dead_letter','suppressed')").bind(asOf,asOf).run();return Number(result.meta?.changes||0);}

export async function runCommunicationOutboxDispatcher(db:Db,env:Env,input:{asOf?:number;limit?:number}={}){await seedCommunicationAdapters(db);const asOf=input.asOf??Date.now(),limit=Math.max(1,Math.min(250,Math.floor(input.limit??100))),recovered=await recoverStaleClaims(db,asOf);const rows=await db.prepare("SELECT o.message_id,o.status,o.next_attempt_at,m.customer_id,m.channel,m.purpose FROM communication_outbox o JOIN communication_messages m ON m.id=o.message_id WHERE m.channel<>'whatsapp' AND o.status IN ('queued','retry_pending','scheduled') AND o.next_attempt_at<=? ORDER BY o.next_attempt_at ASC,o.updated_at ASC LIMIT ?").bind(asOf,limit).all<Row>();const report={processed:0,accepted:0,retried:0,deadLettered:0,scheduled:0,skipped:0,claimLost:0,recoveredStaleClaims:recovered,errors:[] as string[]};for(const row of rows.results){const messageId=text(row.message_id),channel=text(row.channel);try{let result:Record<string,unknown>;if(["sms","email"].includes(channel)){const adapterName=await configuredAdapter(db,channel);if(!adapterName){report.skipped++;continue;}const recipient=await recipientFor(db,text(row.customer_id),channel);if(!recipient){report.skipped++;report.errors.push(`${messageId}:canonical_recipient_missing`);continue;}result=await dispatchExternalCommunication(db,env,{messageId,adapterName,recipient}) as Record<string,unknown>;}else{report.skipped++;continue;}report.processed++;const status=text(result.status);if(status==="provider_accepted")report.accepted++;else if(status==="retry_pending")report.retried++;else if(status==="dead_letter")report.deadLettered++;else if(status==="scheduled")report.scheduled++;else if(status==="dispatch_claim_lost"||status==="already_dispatched")report.claimLost++;else report.skipped++;}catch(error){report.errors.push(`${messageId}:${error instanceof Error?error.message:String(error)}`);const outbox=await db.prepare("SELECT status FROM communication_outbox WHERE message_id=?").bind(messageId).first<Row>().catch(()=>null);if(text(outbox?.status)==="dispatching")await failOutboxAttempt(db,messageId,"dispatcher_unhandled_failure").catch(()=>null);}}
 return{...report,externalDelivery:report.accepted>0};}
