type Row=Record<string,unknown>;
export type CommunicationChannel="whatsapp"|"sms"|"email"|"push"|"chat"|"voice";
export type CommunicationPurpose="auth"|"transactional"|"service_recovery"|"marketing";
export type CommunicationInput={customerId:string;cityId:string;channel:CommunicationChannel;purpose:CommunicationPurpose;idempotencyKey:string;templateKey:string;payload:Record<string,unknown>;createdBy:string;bookingId?:string;leadId?:string;ticketId?:string;assignedTo?:string;scheduledAt?:number};

export async function ensureCommunicationTables(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS communication_policies (id TEXT PRIMARY KEY,city_id TEXT NOT NULL,zone_id TEXT,enforcement_mode TEXT NOT NULL DEFAULT 'observe',quiet_start_hour INTEGER NOT NULL DEFAULT 21,quiet_end_hour INTEGER NOT NULL DEFAULT 8,promotional_cap_7d INTEGER NOT NULL DEFAULT 3,max_attempts INTEGER NOT NULL DEFAULT 5,retry_base_minutes INTEGER NOT NULL DEFAULT 5,active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,effective_from TEXT NOT NULL,effective_to TEXT,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_communication_policy_lookup ON communication_policies(city_id,zone_id,active,effective_from,effective_to)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_threads (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,booking_id TEXT,lead_id TEXT,ticket_id TEXT,status TEXT NOT NULL DEFAULT 'open',assigned_to TEXT,sla_due_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_communication_threads_customer ON communication_threads(customer_id,updated_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_participants (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,participant_type TEXT NOT NULL,participant_id TEXT NOT NULL,display_ref TEXT,role TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(thread_id,participant_type,participant_id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_messages (id TEXT PRIMARY KEY,thread_id TEXT NOT NULL,customer_id TEXT NOT NULL,booking_id TEXT,lead_id TEXT,ticket_id TEXT,direction TEXT NOT NULL,channel TEXT NOT NULL,purpose TEXT NOT NULL,template_key TEXT NOT NULL,payload_json TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,provider_reference TEXT,idempotency_key TEXT NOT NULL UNIQUE,policy_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_communication_messages_thread ON communication_messages(thread_id,created_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_outbox (message_id TEXT PRIMARY KEY,status TEXT NOT NULL,next_attempt_at INTEGER NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,max_attempts INTEGER NOT NULL,last_error TEXT,locked_at INTEGER,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_delivery_events (id TEXT PRIMARY KEY,message_id TEXT NOT NULL,provider TEXT NOT NULL,event_id TEXT NOT NULL,event_type TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,UNIQUE(provider,event_id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_dead_letters (id TEXT PRIMARY KEY,message_id TEXT NOT NULL,reason TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,resolved_at INTEGER,resolved_by TEXT)"),
 db.prepare("CREATE TABLE IF NOT EXISTS communication_preferences (customer_id TEXT PRIMARY KEY,service_updates INTEGER,marketing INTEGER,preferred_channel TEXT,timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',source TEXT NOT NULL,updated_at INTEGER NOT NULL)"),
]);}

export async function seedCommunicationPolicy(db:D1Database){await ensureCommunicationTables(db);const now=Date.now();await db.prepare("INSERT OR IGNORE INTO communication_policies (id,city_id,zone_id,enforcement_mode,quiet_start_hour,quiet_end_hour,promotional_cap_7d,max_attempts,retry_base_minutes,active,version,effective_from,effective_to,updated_by,updated_at) VALUES ('comm_blr_default','blr',NULL,'observe',21,8,3,5,5,1,1,'2026-08-01',NULL,'founder_seed',?)").bind(now).run();}

function parse<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??"")) as T}catch{return fallback}}
function inQuietHours(hour:number,start:number,end:number){return start>end?hour>=start||hour<end:hour>=start&&hour<end;}
function nextQuietEnd(now:number,endHour:number){const date=new Date(now);const offsetMinutes=330;const local=new Date(now+offsetMinutes*60_000);const target=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate(),endHour,0,0));if(local.getUTCHours()>=endHour)target.setUTCDate(target.getUTCDate()+1);return target.getTime()-offsetMinutes*60_000;}

async function policy(db:D1Database,cityId:string){await seedCommunicationPolicy(db);const date=new Date().toISOString().slice(0,10);const row=await db.prepare("SELECT * FROM communication_policies WHERE city_id=? AND active=1 AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY version DESC LIMIT 1").bind(cityId,date,date).first<Row>();if(!row)throw new Error("No active communication policy for city");return row;}

async function consent(db:D1Database,customerId:string){const pref=await db.prepare("SELECT * FROM communication_preferences WHERE customer_id=?").bind(customerId).first<Row>();if(pref)return{serviceUpdates:pref.service_updates==null?null:Boolean(pref.service_updates),marketing:pref.marketing==null?null:Boolean(pref.marketing),source:String(pref.source||"preference")};const customer=await db.prepare("SELECT consent_json FROM canonical_customers WHERE id=?").bind(customerId).first<Row>();const c=customer?parse<Record<string,unknown>>(customer.consent_json,{}):{};return{serviceUpdates:typeof c.serviceUpdates==="boolean"?Boolean(c.serviceUpdates):null,marketing:typeof c.marketing==="boolean"?Boolean(c.marketing):null,source:customer?"canonical_customer":"unknown"};}

async function thread(db:D1Database,input:CommunicationInput){const existing=await db.prepare("SELECT * FROM communication_threads WHERE customer_id=? AND COALESCE(booking_id,'')=? AND COALESCE(lead_id,'')=? AND COALESCE(ticket_id,'')=? AND status='open' ORDER BY updated_at DESC LIMIT 1").bind(input.customerId,input.bookingId??"",input.leadId??"",input.ticketId??"").first<Row>();if(existing)return String(existing.id);const now=Date.now(),id=`THREAD-${crypto.randomUUID().slice(0,12).toUpperCase()}`;await db.prepare("INSERT INTO communication_threads (id,customer_id,booking_id,lead_id,ticket_id,status,assigned_to,sla_due_at,created_at,updated_at) VALUES (?,?,?,?,?,'open',?,?,?,?)").bind(id,input.customerId,input.bookingId??null,input.leadId??null,input.ticketId??null,input.assignedTo??null,input.purpose==="service_recovery"?now+15*60_000:null,now,now).run();await db.prepare("INSERT OR IGNORE INTO communication_participants (id,thread_id,participant_type,participant_id,display_ref,role,created_at) VALUES (?,?,?,?,?,'customer',?)").bind(crypto.randomUUID(),id,"customer",input.customerId,input.customerId,now).run();return id;}

export async function enqueueCommunication(db:D1Database,input:CommunicationInput){await ensureCommunicationTables(db);if(!input.customerId||!input.idempotencyKey||!input.templateKey)throw new Error("Customer, idempotency key and template are required");const prior=await db.prepare("SELECT * FROM communication_messages WHERE idempotency_key=?").bind(input.idempotencyKey).first<Row>();if(prior)return{duplicatePrevented:true,message:prior};
 const p=await policy(db,input.cityId),c=await consent(db,input.customerId),now=Date.now();const reasons:string[]=[];let hardSuppressed=false;
 if(input.purpose==="marketing"&&c.marketing!==true){hardSuppressed=true;reasons.push(c.marketing===false?"marketing_opt_out":"marketing_consent_unknown");}
 if(["transactional","service_recovery"].includes(input.purpose)&&c.serviceUpdates===false){hardSuppressed=true;reasons.push("service_updates_opt_out");}
 if(["transactional","service_recovery"].includes(input.purpose)&&!input.bookingId){hardSuppressed=true;reasons.push("booking_link_required");}
 const localHour=new Date(now+330*60_000).getUTCHours(),quiet=inQuietHours(localHour,Number(p.quiet_start_hour),Number(p.quiet_end_hour));if(input.purpose==="marketing"&&quiet)reasons.push("quiet_hours");
 const recent=input.purpose==="marketing"?await db.prepare("SELECT COUNT(*) count FROM communication_messages WHERE customer_id=? AND purpose='marketing' AND status NOT IN ('suppressed','dead_letter') AND created_at>=?").bind(input.customerId,now-7*86_400_000).first<{count:number}>():null;const capExceeded=Number(recent?.count||0)>=Number(p.promotional_cap_7d);if(capExceeded)reasons.push("frequency_cap_7d");
 const enforce=String(p.enforcement_mode)==="enforce";const delayMarketing=!hardSuppressed&&input.purpose==="marketing"&&enforce&&(quiet||capExceeded);const nextAttempt=input.scheduledAt??(delayMarketing?nextQuietEnd(now,Number(p.quiet_end_hour)):now);const status=hardSuppressed?"suppressed":delayMarketing?"scheduled":"queued";const threadId=await thread(db,input),messageId=`MSG-${crypto.randomUUID().slice(0,14).toUpperCase()}`;const policyDecision={policyId:p.id,policyVersion:p.version,enforcementMode:p.enforcement_mode,consentSource:c.source,serviceUpdates:c.serviceUpdates,marketing:c.marketing,quietHours:quiet,frequencyCapExceeded:capExceeded,reasons,wouldSuppress:hardSuppressed,wouldDelay:quiet||capExceeded};
 await db.batch([
  db.prepare("INSERT INTO communication_messages (id,thread_id,customer_id,booking_id,lead_id,ticket_id,direction,channel,purpose,template_key,payload_json,status,provider,provider_reference,idempotency_key,policy_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,'outbound',?,?,?,?,?,NULL,NULL,?,?,?, ?,?)").bind(messageId,threadId,input.customerId,input.bookingId??null,input.leadId??null,input.ticketId??null,input.channel,input.purpose,input.templateKey,JSON.stringify(input.payload),status,input.idempotencyKey,JSON.stringify(policyDecision),input.createdBy,now,now),
  db.prepare("UPDATE communication_threads SET assigned_to=COALESCE(?,assigned_to),updated_at=? WHERE id=?").bind(input.assignedTo??null,now,threadId),
 ]);
 if(!hardSuppressed)await db.prepare("INSERT INTO communication_outbox (message_id,status,next_attempt_at,attempt_count,max_attempts,last_error,locked_at,updated_at) VALUES (?,?,?,0,?,NULL,NULL,?)").bind(messageId,status,nextAttempt,Number(p.max_attempts),now).run();return{duplicatePrevented:false,messageId,threadId,status,nextAttempt,policy:policyDecision};}

export async function recordDeliveryEvent(db:D1Database,input:{messageId:string;provider:string;eventId:string;eventType:"accepted"|"sent"|"delivered"|"read"|"failed";detail?:Record<string,unknown>}){await ensureCommunicationTables(db);const prior=await db.prepare("SELECT id FROM communication_delivery_events WHERE provider=? AND event_id=?").bind(input.provider,input.eventId).first<Row>();if(prior)return{duplicatePrevented:true};const message=await db.prepare("SELECT * FROM communication_messages WHERE id=?").bind(input.messageId).first<Row>();if(!message)throw new Error("Communication message not found");const now=Date.now();await db.prepare("INSERT INTO communication_delivery_events (id,message_id,provider,event_id,event_type,detail_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.messageId,input.provider,input.eventId,input.eventType,JSON.stringify(input.detail??{}),now).run();const map:Record<string,string>={accepted:"provider_accepted",sent:"sent",delivered:"delivered",read:"read",failed:"retry_pending"};await db.prepare("UPDATE communication_messages SET status=?,provider=?,updated_at=? WHERE id=?").bind(map[input.eventType],input.provider,now,input.messageId).run();if(input.eventType==="failed")await failOutboxAttempt(db,input.messageId,String(input.detail?.reason||"provider_failed"));else if(["accepted","sent","delivered","read"].includes(input.eventType))await db.prepare("UPDATE communication_outbox SET status=?,updated_at=? WHERE message_id=?").bind(input.eventType==="accepted"?"sent":input.eventType,now,input.messageId).run();return{duplicatePrevented:false,status:map[input.eventType]};}

export async function failOutboxAttempt(db:D1Database,messageId:string,reason:string){await ensureCommunicationTables(db);const row=await db.prepare("SELECT o.*,m.customer_id,m.city_id FROM communication_outbox o JOIN communication_messages m ON m.id=o.message_id WHERE o.message_id=?").bind(messageId).first<Row>().catch(()=>null);const current=row??await db.prepare("SELECT * FROM communication_outbox WHERE message_id=?").bind(messageId).first<Row>();if(!current)throw new Error("Outbox entry not found");const attempts=Number(current.attempt_count||0)+1,max=Number(current.max_attempts||5),now=Date.now();if(attempts>=max){await db.batch([db.prepare("UPDATE communication_outbox SET status='dead_letter',attempt_count=?,last_error=?,updated_at=? WHERE message_id=?").bind(attempts,reason,now,messageId),db.prepare("UPDATE communication_messages SET status='dead_letter',updated_at=? WHERE id=?").bind(now,messageId),db.prepare("INSERT OR IGNORE INTO communication_dead_letters (id,message_id,reason,detail_json,created_at) VALUES (?,?,?,?,?)").bind(`DLQ-${messageId}`,messageId,reason,JSON.stringify({attempts,max}),now)]);return{status:"dead_letter",attempts};}const backoffMinutes=Math.min(240,5*Math.pow(2,attempts-1));await db.batch([db.prepare("UPDATE communication_outbox SET status='retry_pending',attempt_count=?,next_attempt_at=?,last_error=?,locked_at=NULL,updated_at=? WHERE message_id=?").bind(attempts,now+backoffMinutes*60_000,reason,now,messageId),db.prepare("UPDATE communication_messages SET status='retry_pending',updated_at=? WHERE id=?").bind(now,messageId)]);return{status:"retry_pending",attempts,nextAttemptAt:now+backoffMinutes*60_000};}

export async function setCommunicationPreference(db:D1Database,input:{customerId:string;serviceUpdates?:boolean|null;marketing?:boolean|null;preferredChannel?:CommunicationChannel|null;source:string}){await ensureCommunicationTables(db);const now=Date.now();await db.prepare("INSERT INTO communication_preferences (customer_id,service_updates,marketing,preferred_channel,timezone,source,updated_at) VALUES (?,?,?,?, 'Asia/Kolkata',?,?) ON CONFLICT(customer_id) DO UPDATE SET service_updates=excluded.service_updates,marketing=excluded.marketing,preferred_channel=excluded.preferred_channel,source=excluded.source,updated_at=excluded.updated_at").bind(input.customerId,input.serviceUpdates==null?null:input.serviceUpdates?1:0,input.marketing==null?null:input.marketing?1:0,input.preferredChannel??null,input.source,now).run();return{customerId:input.customerId,updatedAt:now};}
