import{ensureFoodFulfilmentTables}from"./food-fulfilment-governance";
type Row=Record<string,unknown>;
export type FoodFinanceAction="request_cancel"|"approve_cancel"|"record_order_payment"|"record_refund"|"prepare_supplier_settlement"|"reconcile";
export type FoodFinanceInput={orderId:string;action:FoodFinanceAction;actorId:string;idempotencyKey:string;reason?:string;paymentReference?:string;approvedRefundAmount?:number;refundReference?:string};
const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value??"")) as T}catch{return fallback}};
export async function ensureFoodFinanceTables(db:D1Database){await ensureFoodFulfilmentTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS food_finance_action_keys (idempotency_key TEXT PRIMARY KEY,order_id TEXT NOT NULL,action TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS food_cancellation_requests (id TEXT PRIMARY KEY,order_id TEXT NOT NULL,requested_by TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'policy_review_required',approved_refund_amount REAL,decision_by TEXT,decision_reason TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS food_refund_ledger (id TEXT PRIMARY KEY,order_id TEXT NOT NULL,cancellation_request_id TEXT,amount REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',status TEXT NOT NULL DEFAULT 'sandbox_pending',reference TEXT,policy_source TEXT NOT NULL,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS idx_food_refund_reference ON food_refund_ledger(reference) WHERE reference IS NOT NULL"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS idx_food_payment_reference ON food_order_payment_events(reference) WHERE reference IS NOT NULL"),
 db.prepare("CREATE TABLE IF NOT EXISTS food_supplier_settlement_ledger (order_id TEXT PRIMARY KEY,gross_paid_value REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',supplier_cost REAL,supplier_settlement_amount REAL,cogs_status TEXT NOT NULL DEFAULT 'configuration_required',supplier_settlement_policy TEXT NOT NULL DEFAULT 'rule_pending',tax_status TEXT NOT NULL DEFAULT 'configuration_required',approval_status TEXT NOT NULL DEFAULT 'not_ready',settlement_status TEXT NOT NULL DEFAULT 'not_instructed',eligible_at INTEGER,approved_by TEXT,reference TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS food_finance_reconciliation (id TEXT PRIMARY KEY,order_id TEXT NOT NULL,order_total REAL NOT NULL,delivery_due_total REAL NOT NULL,paid_total REAL NOT NULL,refund_total REAL NOT NULL,net_paid_total REAL NOT NULL,unpaid_total REAL NOT NULL,supplier_settlement_amount REAL,cogs_state TEXT NOT NULL,supplier_settlement_state TEXT NOT NULL,tax_state TEXT NOT NULL,status TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',checked_by TEXT NOT NULL,created_at INTEGER NOT NULL)"),
])}
async function context(db:D1Database,orderId:string){await ensureFoodFinanceTables(db);const row=await db.prepare("SELECT o.*,f.status fulfilment_status,r.status reservation_status,p.status payment_intent_status FROM food_orders o LEFT JOIN food_order_fulfilment f ON f.order_id=o.id LEFT JOIN food_inventory_reservations r ON r.order_id=o.id LEFT JOIN food_order_payments p ON p.order_id=o.id WHERE o.id=?").bind(orderId).first<Row>();if(!row)throw new Response("Canonical Food order not found",{status:404});return row}
async function prior(db:D1Database,key:string){const row=await db.prepare("SELECT result_json FROM food_finance_action_keys WHERE idempotency_key=?").bind(key).first<Row>();return row?parse<Record<string,unknown>>(row.result_json,{}):null}
async function remember(db:D1Database,input:FoodFinanceInput,result:Record<string,unknown>){await db.prepare("INSERT INTO food_finance_action_keys (idempotency_key,order_id,action,result_json,created_at) VALUES (?,?,?,?,?)").bind(input.idempotencyKey,input.orderId,input.action,JSON.stringify(result),Date.now()).run();return result}
function why(input:FoodFinanceInput){const value=String(input.reason||"").trim();if(value.length<3)throw new Response("A Food finance reason is required",{status:400});return value}
async function totals(db:D1Database,orderId:string){const payment=await db.prepare("SELECT amount,status FROM food_order_payment_events WHERE order_id=?").bind(orderId).first<Row>(),refund=await db.prepare("SELECT COALESCE(SUM(amount),0) total FROM food_refund_ledger WHERE order_id=? AND status='sandbox_recorded'").bind(orderId).first<Row>(),due=payment?Number(payment.amount||0):0,paid=payment&&String(payment.status)==="sandbox_paid"?Number(payment.amount||0):0,unpaid=payment&&String(payment.status)==="due"?Number(payment.amount||0):0;return{due,paid,unpaid,refund:Number(refund?.total||0)}}
async function releaseReservedInventory(db:D1Database,order:Row,now:number){const reservation=await db.prepare("SELECT sku,zone_id,quantity,status FROM food_inventory_reservations WHERE order_id=?").bind(order.id).first<Row>();if(reservation&&String(reservation.status)==="reserved")await db.batch([db.prepare("UPDATE food_inventory_uat SET reserved_units=MAX(0,reserved_units-?),updated_at=? WHERE sku=? AND zone_id=?").bind(Number(reservation.quantity),now,reservation.sku,reservation.zone_id),db.prepare("UPDATE food_inventory_reservations SET status='released',updated_at=? WHERE order_id=? AND status='reserved'").bind(now,order.id)])}
export async function mutateFoodFinance(db:D1Database,input:FoodFinanceInput){if(!input.orderId||!input.action||!input.actorId||!input.idempotencyKey)throw new Response("Order, action, actor and idempotency key are required",{status:400});await ensureFoodFinanceTables(db);const old=await prior(db,input.idempotencyKey);if(old)return{...old,duplicatePrevented:true};const order=await context(db,input.orderId),now=Date.now(),orderStatus=String(order.status),fulfilment=String(order.fulfilment_status||"");
 if(input.action==="request_cancel"){if(["cancelled","delivered"].includes(orderStatus))throw new Response("Closed Food orders cannot accept cancellation requests",{status:409});if(["packed","dispatched"].includes(fulfilment))throw new Response("Packed/dispatched Food order must use Operations fulfilment review before cancellation",{status:409});const id=crypto.randomUUID();await db.prepare("INSERT INTO food_cancellation_requests (id,order_id,requested_by,reason,status,created_at,updated_at) VALUES (?,?,?,?, 'policy_review_required',?,?)").bind(id,input.orderId,input.actorId,why(input),now,now).run();return remember(db,input,{requestId:id,orderId:input.orderId,status:"policy_review_required",refundPolicy:"configuration_required",orderPreserved:true})}
 if(input.action==="approve_cancel"){if(["packed","dispatched"].includes(fulfilment))throw new Response("Packed/dispatched Food order must be operationally resolved before Finance cancellation",{status:409});const request=await db.prepare("SELECT * FROM food_cancellation_requests WHERE order_id=? AND status='policy_review_required' ORDER BY created_at DESC LIMIT 1").bind(input.orderId).first<Row>();if(!request)throw new Response("No Food cancellation request is awaiting policy review",{status:409});const current=await totals(db,input.orderId),amount=Number(input.approvedRefundAmount);if(!Number.isFinite(amount)||amount<0||amount>current.paid)throw new Response("Approved Food refund must be explicit and cannot exceed sandbox-paid order value",{status:409});const reason=why(input),refundId=amount>0?crypto.randomUUID():null;await releaseReservedInventory(db,order,now);const statements=[db.prepare("UPDATE food_cancellation_requests SET status='approved',approved_refund_amount=?,decision_by=?,decision_reason=?,updated_at=? WHERE id=?").bind(amount,input.actorId,reason,now,request.id),db.prepare("UPDATE food_orders SET status='cancelled',delivery_status='cancelled',updated_at=? WHERE id=?").bind(now,input.orderId),db.prepare("UPDATE food_order_fulfilment SET status='cancelled',updated_by=?,updated_at=? WHERE order_id=? AND status NOT IN ('delivered','cancelled')").bind(input.actorId,now,input.orderId)];if(refundId)statements.push(db.prepare("INSERT INTO food_refund_ledger (id,order_id,cancellation_request_id,amount,currency,status,reference,policy_source,created_by,created_at,updated_at) VALUES (?,?,?,?,'INR','sandbox_pending',NULL,'explicit_finance_approval',?,?,?)").bind(refundId,input.orderId,request.id,amount,input.actorId,now,now));await db.batch(statements);return remember(db,input,{orderId:input.orderId,status:"cancelled",approvedRefundAmount:amount,refundId,refundStatus:refundId?"sandbox_pending":"not_required",inventoryReservationReleased:true})}
 if(input.action==="record_order_payment"){const reference=String(input.paymentReference||"").trim();if(!reference)throw new Response("Sandbox Food payment reference is required",{status:400});const payment=await db.prepare("SELECT * FROM food_order_payment_events WHERE order_id=?").bind(input.orderId).first<Row>();if(!payment)throw new Response("Delivered Food payment-due event not found",{status:404});if(String(payment.status)==="sandbox_paid")return remember(db,input,{orderId:input.orderId,status:"sandbox_paid",reference:payment.reference,amount:Number(payment.amount),duplicatePayment:true});if(String(payment.status)!=="due")throw new Response("Food payment event is not payable",{status:409});const used=await db.prepare("SELECT id FROM food_order_payment_events WHERE reference=?").bind(reference).first<Row>();if(used)throw new Response("Food sandbox payment reference was already used",{status:409});await db.batch([db.prepare("UPDATE food_order_payment_events SET status='sandbox_paid',reference=?,updated_at=? WHERE id=? AND status='due'").bind(reference,now,payment.id),db.prepare("UPDATE food_order_payments SET status='paid',detail_json=?,updated_at=? WHERE order_id=?").bind(JSON.stringify({source:"food_delivery_ledger",sandboxReference:reference,liveMoney:false,productionPaymentPolicy:"pending"}),now,input.orderId)]);return remember(db,input,{orderId:input.orderId,status:"sandbox_paid",reference,amount:Number(payment.amount),liveMoney:false})}
 if(input.action==="record_refund"){const reference=String(input.refundReference||"").trim();if(!reference)throw new Response("Sandbox Food refund reference is required",{status:400});const refund=await db.prepare("SELECT * FROM food_refund_ledger WHERE order_id=? AND status='sandbox_pending' ORDER BY created_at DESC LIMIT 1").bind(input.orderId).first<Row>();if(!refund)throw new Response("No Food sandbox refund is pending",{status:409});const used=await db.prepare("SELECT id FROM food_refund_ledger WHERE reference=?").bind(reference).first<Row>();if(used&&String(used.id)!==String(refund.id))throw new Response("Food refund reference was already used",{status:409});await db.prepare("UPDATE food_refund_ledger SET status='sandbox_recorded',reference=?,updated_at=? WHERE id=?").bind(reference,now,refund.id).run();return remember(db,input,{orderId:input.orderId,refundId:refund.id,status:"sandbox_recorded",amount:Number(refund.amount),reference})}
 if(input.action==="prepare_supplier_settlement"){if(orderStatus!=="delivered"||fulfilment!=="delivered")throw new Response("Supplier settlement can be prepared only after canonical UAT Food delivery",{status:409});const current=await totals(db,input.orderId);if(current.unpaid>0||current.paid<=0)throw new Response("Delivered Food order must be sandbox-paid before supplier settlement readiness",{status:409});await db.prepare("INSERT INTO food_supplier_settlement_ledger (order_id,gross_paid_value,currency,cogs_status,supplier_settlement_policy,tax_status,approval_status,settlement_status,eligible_at,created_at,updated_at) VALUES (?,?,'INR','configuration_required','rule_pending','configuration_required','not_ready','not_instructed',?,?,?) ON CONFLICT(order_id) DO UPDATE SET gross_paid_value=excluded.gross_paid_value,eligible_at=excluded.eligible_at,updated_at=excluded.updated_at").bind(input.orderId,current.paid,now,now,now).run();return remember(db,input,{orderId:input.orderId,status:"not_ready",grossPaidValue:current.paid,cogs:"configuration_required",supplierSettlementPolicy:"rule_pending",tax:"configuration_required",settlement:"not_instructed"})}
 if(input.action==="reconcile"){const current=await totals(db,input.orderId),settlement=await db.prepare("SELECT * FROM food_supplier_settlement_ledger WHERE order_id=?").bind(input.orderId).first<Row>(),net=Math.max(0,current.paid-current.refund),cogsState=settlement?String(settlement.cogs_status):"configuration_required",supplierState=settlement?String(settlement.approval_status):orderStatus==="delivered"?"attention_required":"not_due",taxState=settlement?String(settlement.tax_status):"configuration_required",attention=current.unpaid>0||supplierState==="attention_required"||cogsState==="configuration_required"||taxState==="configuration_required",id=crypto.randomUUID();await db.prepare("INSERT INTO food_finance_reconciliation (id,order_id,order_total,delivery_due_total,paid_total,refund_total,net_paid_total,unpaid_total,supplier_settlement_amount,cogs_state,supplier_settlement_state,tax_state,status,detail_json,checked_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.orderId,order.total_amount,current.due,current.paid,current.refund,net,current.unpaid,settlement?.supplier_settlement_amount??null,cogsState,supplierState,taxState,attention?"attention_required":"balanced",JSON.stringify({sandboxOnly:true,paymentIntentStatus:order.payment_intent_status}),input.actorId,now).run();return remember(db,input,{orderId:input.orderId,reconciliationId:id,status:attention?"attention_required":"balanced",deliveryDueTotal:current.due,paidTotal:current.paid,refundTotal:current.refund,unpaidTotal:current.unpaid,netPaidTotal:net,cogsState,supplierSettlementState:supplierState,taxState})}
 throw new Response("Unsupported Food finance action",{status:400})}
