export type FoodCatalogueItem={sku:string;name:string;pet_type:"dog"|"cat";pack_size:string;unit_price:number;currency:string;max_qty_per_order:number;version:number;uat_available_units:number;inventory_mode:"uat_seed";production_inventory_verified:false};
export type FoodQuote={quoteId:string;sku:string;name:string;version:number;petType:"dog"|"cat";packSize:string;quantity:number;unitPrice:number;deliveryFee:0;totalAmount:number;amountDueNow:0;currency:"INR";zoneId:string;paymentMode:"sandbox_deferred";expiresAt:number;inventoryMode:"uat_seed";productionInventoryVerified:false;liveMoney:false};
export type FoodOrderResult={orderId:string;status:string;lineId:string;reservationId:string;paymentId:string;totalAmount:number;amountDueNow:0;inventoryMode:"uat_seed";productionInventoryVerified:false;deliveryStatus:string;liveMoney:false;duplicatePrevented:boolean};
export async function loadFoodCatalogue(zoneId="blr-east"){const response=await fetch(`/api/food-commercial?zoneId=${encodeURIComponent(zoneId)}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load Food catalogue");return body.data as {items:FoodCatalogueItem[];source:string;inventoryMode:string;productionInventoryVerified:false;deliveryFeePolicy:string;liveMoney:false}}
export async function createFoodQuote(input:{sku:string;quantity:number;zoneId?:string;paymentMode?:"sandbox_deferred"}){const response=await fetch("/api/food-commercial",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,zoneId:input.zoneId||"blr-east",paymentMode:input.paymentMode||"sandbox_deferred"})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to create Food quote");return body.data as FoodQuote}
export async function createCanonicalFoodOrder(input:{idempotencyKey:string;quoteId:string;customer:{id:string;name:string;primaryPhone:string;secondaryPhone?:string;email?:string};cityId?:string;zoneId?:string}){const response=await fetch("/api/food-orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,cityId:input.cityId||"blr",zoneId:input.zoneId||"blr-east"})});const body=await response.json() as {data?:FoodOrderResult;error?:string};if(!response.ok||!body.data)throw new Error(body.error||"Unable to create canonical Food order");return body.data}

// --- Additive cart helpers for the customer Food flow (compose the existing contract above; no pricing is computed client-side) ---
export type FoodCartLine={sku:string;quantity:number};
export type FoodCartQuotes={quotes:FoodQuote[];serverTotal:number};
/** One server quote per cart line (the Food quote contract is per-SKU). serverTotal is the sum of server-computed quote totals only. */
export async function quoteFoodCart(lines:FoodCartLine[],zoneId="blr-east"):Promise<FoodCartQuotes>{if(!lines.length)throw new Error("Food cart is empty");const quotes:FoodQuote[]=[];for(const line of lines)quotes.push(await createFoodQuote({sku:line.sku,quantity:line.quantity,zoneId}));return{quotes,serverTotal:quotes.reduce((sum,quote)=>sum+quote.totalAmount,0)}}
/** One canonical order per server quote, idempotent per quote (safe to retry after a network failure). */
export async function placeQuotedFoodOrders(input:{quotes:FoodQuote[];customer:{id:string;name:string;primaryPhone:string;secondaryPhone?:string;email?:string};cityId?:string;zoneId?:string}):Promise<FoodOrderResult[]>{if(!input.quotes.length)throw new Error("A server Food quote is required before ordering");const orders:FoodOrderResult[]=[];for(const quote of input.quotes)orders.push(await createCanonicalFoodOrder({idempotencyKey:`food-flow:${input.customer.id}:${quote.quoteId}`,quoteId:quote.quoteId,customer:input.customer,cityId:input.cityId,zoneId:input.zoneId}));return orders}
