import{ensureLeadLifecycleColumn,normalizeLeadServiceCode}from"./lead-lifecycle-governance";
import{recordMarketingConversionFact}from"./marketing-conversion-feedback";
import{attributeConvertedLeadBookingToOwner}from"./sales-incentive-engine";

type Db=D1Database;type Row=Record<string,unknown>;const leadWorkItemsEnsured=new WeakSet<Db>();
export async function ensureLeadWorkItemsTable(db:Db){if(leadWorkItemsEnsured.has(db))return;await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS lead_work_items (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, source TEXT NOT NULL, service TEXT NOT NULL, owner TEXT NOT NULL, manager TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', stage TEXT NOT NULL DEFAULT 'day_1', work_day INTEGER NOT NULL DEFAULT 1, assigned_at INTEGER NOT NULL, first_action_due_at INTEGER NOT NULL, manager_alert_at INTEGER NOT NULL, first_action_at INTEGER, call_attempts INTEGER NOT NULL DEFAULT 0, whatsapp_attempts INTEGER NOT NULL DEFAULT 0, last_outcome TEXT, next_action_at INTEGER, recycle_at INTEGER, recycle_cycle INTEGER NOT NULL DEFAULT 0, opt_out INTEGER NOT NULL DEFAULT 0, converted_booking_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_lead_work_items_customer ON lead_work_items(customer_id,status,assigned_at)")]);const columns=await db.prepare("PRAGMA table_info(lead_work_items)").all<Row>().catch(()=>({results:[]as Row[]}));if(columns.results.length&&!columns.results.some(column=>String(column.name)==="initiated_booking_id")){await db.prepare("ALTER TABLE lead_work_items ADD COLUMN initiated_booking_id TEXT").run().catch(async error=>{const after=await db.prepare("PRAGMA table_info(lead_work_items)").all<Row>();if(!after.results.some(column=>String(column.name)==="initiated_booking_id"))throw error;});}await ensureLeadLifecycleColumn(db);await db.prepare("CREATE TABLE IF NOT EXISTS booking_attribution (booking_id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,service_code TEXT NOT NULL,attribution_type TEXT NOT NULL,lead_id TEXT,source TEXT NOT NULL DEFAULT 'system',detail_json TEXT NOT NULL DEFAULT '{}',recorded_at INTEGER NOT NULL)").run();await db.prepare("CREATE INDEX IF NOT EXISTS idx_booking_attribution_type ON booking_attribution(attribution_type,recorded_at)").run().catch(()=>{});leadWorkItemsEnsured.add(db);}
export type BookingAttributionType="lead"|"direct_booking";
async function recordAttribution(db:Db,input:{bookingId:string;customerId:string;serviceCode:string;type:BookingAttributionType;leadId?:string|null;detail?:unknown;strict?:boolean}){const insert=db.prepare("INSERT OR IGNORE INTO booking_attribution (booking_id,customer_id,service_code,attribution_type,lead_id,source,detail_json,recorded_at) VALUES (?,?,?,?,?,?,?,?)"+(input.strict?" RETURNING customer_id,service_code,attribution_type,lead_id,detail_json":"")).bind(input.bookingId,input.customerId,input.serviceCode,input.type,input.leadId??null,input.type==="lead"?"lead_work_item":"system_direct_booking",JSON.stringify(input.detail??{}),Date.now());if(!input.strict){await insert.run();return;}const inserted=await insert.first<Row>();const recorded=inserted??await db.prepare("SELECT customer_id,service_code,attribution_type,lead_id,detail_json FROM booking_attribution WHERE booking_id=?").bind(input.bookingId).first<Row>();const wanted=input.detail as {threadId?:string|null}|undefined;const stored=JSON.parse(String(recorded?.detail_json||"{}"));if(!recorded||String(recorded.customer_id)!==input.customerId||normalizeLeadServiceCode(recorded.service_code)!==normalizeLeadServiceCode(input.serviceCode)||String(recorded.attribution_type)!==input.type||String(recorded.lead_id||"")!==String(input.leadId||"")||wanted?.threadId&&stored.threadId&&wanted.threadId!==stored.threadId)throw new Response("Booking attribution changed concurrently",{status:409});}
async function commercials(db:Db,bookingId:string){const booking=await db.prepare("SELECT total_amount,currency FROM canonical_bookings WHERE id=?").bind(bookingId).first<Row>().catch(()=>null);return{valueMinor:Math.max(0,Math.round(Number(booking?.total_amount||0)*100)),currency:String(booking?.currency||"INR")};}
async function latestPayment(db:Db,bookingId:string,capturedOnly=false){const status=capturedOnly?" AND status='captured'":"";try{return await db.prepare(`SELECT id,status,amount,currency FROM booking_payments WHERE booking_id=?${status} ORDER BY updated_at DESC LIMIT 1`).bind(bookingId).first<Row>();}catch{try{return await db.prepare(`SELECT id,status,amount,currency FROM booking_payments WHERE booking_id=?${status} LIMIT 1`).bind(bookingId).first<Row>();}catch{return db.prepare(`SELECT id,status,amount FROM booking_payments WHERE booking_id=?${status} LIMIT 1`).bind(bookingId).first<Row>().catch(()=>null);}}}
async function creditSalesOwner(db:Db,leadId:string,bookingId:string){return attributeConvertedLeadBookingToOwner(db,{leadId,bookingId,actorId:"system:payment-capture"}).catch(()=>({attributed:false,duplicatePrevented:false,conflict:false,reason:"sales_attribution_error"}));}
export async function bookingAttributionSummary(db:Db,input:{from?:number;to?:number}={}){await ensureLeadWorkItemsTable(db);const rows=await db.prepare("SELECT attribution_type,COUNT(*) n FROM booking_attribution WHERE recorded_at>=? AND recorded_at<=? GROUP BY attribution_type").bind(input.from??0,input.to??Number.MAX_SAFE_INTEGER).all<Row>();const summary:Record<string,number>={lead:0,direct_booking:0};for(const row of rows.results)summary[String(row.attribution_type)]=Number(row.n||0);return summary;}


/** Validate explicit conversation origin before booking effects. Never infer another lead. */
export async function validateBookingOrigin(db:Db,input:{customerId:string;serviceCode:string;leadId?:string|null;threadId?:string|null;bookingId?:string}){
 await ensureLeadWorkItemsTable(db);
 const service=normalizeLeadServiceCode(input.serviceCode);let leadId=input.leadId?.trim()||null;
 const threadId=input.threadId?.trim()||null;
 if(threadId){
  const thread=await db.prepare("SELECT customer_id,lead_id,booking_id FROM communication_threads WHERE id=?").bind(threadId).first<Row>();
  if(!thread||String(thread.customer_id)!==input.customerId)throw new Response("Booking conversation ownership denied",{status:403});
  if(thread.booking_id&&String(thread.booking_id)!==input.bookingId)throw new Response("Conversation is already bound to another booking",{status:409});
  if(leadId&&String(thread.lead_id||"")!==leadId)throw new Response("Booking lead conflicts with conversation",{status:409});
  leadId=String(thread.lead_id||"").trim()||null;
 }
 if(leadId){
  const lead=await db.prepare("SELECT customer_id,service,initiated_booking_id,converted_booking_id,lifecycle_state FROM lead_work_items WHERE id=?").bind(leadId).first<Row>();
  if(!lead||String(lead.customer_id)!==input.customerId)throw new Response("Booking lead ownership denied",{status:403});
  if(normalizeLeadServiceCode(lead.service)!==service)throw new Response("Booking lead service mismatch",{status:409});
  if([lead.initiated_booking_id,lead.converted_booking_id].some(id=>id&&String(id)!==input.bookingId)||String(lead.lifecycle_state)==="dropped")throw new Response("Lead is unavailable for this booking",{status:409});
 }
 return{leadId,threadId};
}

export async function attributeBookingToOpenLead(db:Db,input:{customerId:string;bookingId:string;leadId?:string|null;threadId?:string|null}):Promise<{leadId:string|null;converted:boolean;attribution:BookingAttributionType}>{
 await ensureLeadWorkItemsTable(db);
 const booked=await db.prepare("SELECT b.customer_id,b.service_code,a.booking_id attribution_booking_id,a.customer_id attribution_customer_id,a.service_code attribution_service_code,a.lead_id,a.attribution_type,a.detail_json FROM canonical_bookings b LEFT JOIN booking_attribution a ON a.booking_id=b.id WHERE b.id=?").bind(input.bookingId).first<Row>();
 if(!booked||String(booked.customer_id)!==input.customerId)throw new Response("Booking ownership denied",{status:403});
 const bookedService=normalizeLeadServiceCode(booked.service_code);
 const origin=await validateBookingOrigin(db,{...input,serviceCode:bookedService});
 const prior=booked.attribution_booking_id?{customer_id:booked.attribution_customer_id,service_code:booked.attribution_service_code,lead_id:booked.lead_id,attribution_type:booked.attribution_type,detail_json:booked.detail_json}:null;
 if(prior&&(String(prior.customer_id)!==input.customerId||normalizeLeadServiceCode(prior.service_code)!==bookedService||origin.leadId&&String(prior.lead_id||"")!==origin.leadId))throw new Response("Booking attribution conflicts with origin",{status:409});
 if(prior&&origin.threadId){const detail=JSON.parse(String(prior.detail_json||"{}"));if(detail.threadId&&detail.threadId!==origin.threadId)throw new Response("Booking attribution belongs to another conversation",{status:409});}
 const selectedId=prior?String(prior.lead_id||"")||null:origin.leadId;
 const explicit=Boolean(prior||origin.threadId||origin.leadId);
 const candidates=explicit?{results:[] as Row[]}:await db.prepare("SELECT id,service FROM lead_work_items WHERE customer_id=? AND converted_booking_id IS NULL AND initiated_booking_id IS NULL AND status NOT IN ('closed','converted') AND lifecycle_state NOT IN ('converted','dropped') ORDER BY assigned_at DESC LIMIT 100").bind(input.customerId).all<Row>();
 const openLead=selectedId?await db.prepare("SELECT id,service FROM lead_work_items WHERE id=? AND customer_id=?").bind(selectedId,input.customerId).first<Row>():candidates.results.find(row=>normalizeLeadServiceCode(row.service)===bookedService)||null;
 if(selectedId&&!openLead)throw new Response("Attributed lead no longer exists",{status:409});
 async function bindThread(){if(origin.threadId){
  await db.prepare("UPDATE communication_threads SET booking_id=?,updated_at=? WHERE id=? AND customer_id=? AND (booking_id IS NULL OR booking_id=?) AND COALESCE(lead_id,'')=?").bind(input.bookingId,Date.now(),origin.threadId,input.customerId,input.bookingId,origin.leadId||"").run();
  const bound=await db.prepare("SELECT booking_id FROM communication_threads WHERE id=? AND customer_id=?").bind(origin.threadId,input.customerId).first<Row>();
  if(String(bound?.booking_id||"")!==input.bookingId)throw new Response("Conversation changed during booking attribution",{status:409});
 }}
 if(!openLead){await recordAttribution(db,{strict:true,bookingId:input.bookingId,customerId:input.customerId,serviceCode:bookedService,type:"direct_booking",detail:{reason:"no_originating_lead",threadId:origin.threadId}});await bindThread();return{leadId:null,converted:false,attribution:"direct_booking"};}
 const leadId=String(openLead.id),now=Date.now();const payment=await latestPayment(db,input.bookingId);const captured=String(payment?.status||"")==="captured";await recordAttribution(db,{strict:true,bookingId:input.bookingId,customerId:input.customerId,serviceCode:bookedService,type:"lead",leadId,detail:{matchedOn:origin.leadId?"verified_conversation_origin":"customer_and_normalized_service",threadId:origin.threadId}});await bindThread();const commercial=await commercials(db,input.bookingId);await recordMarketingConversionFact(db,{eventType:"booking_created",businessReference:input.bookingId,leadId,customerId:input.customerId,bookingId:input.bookingId,valueMinor:commercial.valueMinor,currency:commercial.currency,occurredAt:now}).catch(()=>{});if(captured){await db.prepare("UPDATE lead_work_items SET converted_booking_id=?,status='converted',lifecycle_state='converted',updated_at=? WHERE id=? AND converted_booking_id IS NULL AND lifecycle_state!='dropped'").bind(input.bookingId,now,leadId).run();await recordMarketingConversionFact(db,{eventType:"payment_captured",businessReference:String(payment?.id||input.bookingId),leadId,customerId:input.customerId,bookingId:input.bookingId,paymentId:String(payment?.id||""),valueMinor:Math.max(0,Math.round(Number(payment?.amount||0)*100)),currency:String(payment?.currency||commercial.currency),occurredAt:now}).catch(()=>{});await creditSalesOwner(db,leadId,input.bookingId);return{leadId,converted:true,attribution:"lead"};}await db.prepare("UPDATE lead_work_items SET last_outcome='booking_initiated',initiated_booking_id=?,lifecycle_state=CASE WHEN lifecycle_state IN ('new','contacted') THEN 'qualified' ELSE lifecycle_state END,next_action_at=?,updated_at=? WHERE id=? AND converted_booking_id IS NULL AND lifecycle_state NOT IN ('converted','dropped')").bind(input.bookingId,now,now,leadId).run();await recordMarketingConversionFact(db,{eventType:"lead_qualified",businessReference:leadId,leadId,customerId:input.customerId,occurredAt:now}).catch(()=>{});return{leadId,converted:false,attribution:"lead"};}

export async function convertLeadOnPaymentCaptured(db:Db,input:{customerId:string;bookingId:string}):Promise<{leadId:string}|null>{await ensureLeadWorkItemsTable(db);const openLead=await db.prepare("SELECT id FROM lead_work_items WHERE customer_id=? AND initiated_booking_id=? AND converted_booking_id IS NULL AND status NOT IN ('closed','converted') AND lifecycle_state NOT IN ('converted','dropped') ORDER BY assigned_at DESC LIMIT 1").bind(input.customerId,input.bookingId).first<Row>().catch(()=>null);if(!openLead){const booked=await db.prepare("SELECT service_code FROM canonical_bookings WHERE id=?").bind(input.bookingId).first<Row>().catch(()=>null);await recordAttribution(db,{bookingId:input.bookingId,customerId:input.customerId,serviceCode:normalizeLeadServiceCode(booked?.service_code),type:"direct_booking",detail:{reason:"no_lead_linked_at_booking_creation"}});return null;}const leadId=String(openLead.id),now=Date.now(),changed=await db.prepare("UPDATE lead_work_items SET converted_booking_id=?,status='converted',lifecycle_state='converted',updated_at=? WHERE id=? AND converted_booking_id IS NULL AND lifecycle_state NOT IN ('converted','dropped')").bind(input.bookingId,now,leadId).run();if(Number(changed.meta?.changes||0)!==1)return null;const payment=await latestPayment(db,input.bookingId,true),commercial=await commercials(db,input.bookingId);await recordMarketingConversionFact(db,{eventType:"payment_captured",businessReference:String(payment?.id||input.bookingId),leadId,customerId:input.customerId,bookingId:input.bookingId,paymentId:String(payment?.id||""),valueMinor:payment?Math.max(0,Math.round(Number(payment.amount||0)*100)):commercial.valueMinor,currency:String(payment?.currency||commercial.currency),occurredAt:now}).catch(()=>{});await creditSalesOwner(db,leadId,input.bookingId);return{leadId};}