import{ensureMarketingAdConnectorTables,syncGoogleAdsMetrics,syncMetaAdsMetrics,type MarketingAdPlatform}from"./marketing-ad-connectors";

type Db=D1Database;type Row=Record<string,unknown>;type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
const METRIC_COLUMNS="dimension_key,platform,account_id,report_date,dimension_type,campaign_id,campaign_name,ad_set_id,ad_set_name,ad_id,ad_name,keyword,search_term,match_type,device,age_range,gender,impressions,clicks,spend_minor,conversions,conversion_value_minor,currency,ctr_percent,cpc_minor,cpa_minor,current_bid_minor,pulled_at,updated_at";
const text=(value:unknown)=>String(value??"").trim();const number=(value:unknown)=>{const parsed=Number(value??0);return Number.isFinite(parsed)?parsed:0;};
function stageSql(sql:string){return sql.replace(/\bmarketing_ad_metric_facts\b/g,"marketing_ad_metric_stage").replace(/\bmarketing_ad_sync_runs\b/g,"marketing_ad_sync_runs_stage");}
function stageDb(db:Db):Db{return{prepare:(sql:string)=>db.prepare(stageSql(sql)),batch:(statements:D1PreparedStatement[])=>db.batch(statements)}as Db;}
async function ensureMarketingAdStageTables(db:Db){await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS marketing_ad_metric_stage (dimension_key TEXT PRIMARY KEY,platform TEXT NOT NULL,account_id TEXT NOT NULL,report_date TEXT NOT NULL,dimension_type TEXT NOT NULL,campaign_id TEXT,campaign_name TEXT,ad_set_id TEXT,ad_set_name TEXT,ad_id TEXT,ad_name TEXT,keyword TEXT,search_term TEXT,match_type TEXT,device TEXT,age_range TEXT,gender TEXT,impressions INTEGER NOT NULL DEFAULT 0,clicks INTEGER NOT NULL DEFAULT 0,spend_minor INTEGER NOT NULL DEFAULT 0,conversions REAL NOT NULL DEFAULT 0,conversion_value_minor INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'INR',ctr_percent REAL NOT NULL DEFAULT 0,cpc_minor INTEGER NOT NULL DEFAULT 0,cpa_minor INTEGER NOT NULL DEFAULT 0,current_bid_minor INTEGER,pulled_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS marketing_ad_sync_runs_stage (id TEXT PRIMARY KEY,platform TEXT NOT NULL,from_date TEXT NOT NULL,to_date TEXT NOT NULL,status TEXT NOT NULL,rows_written INTEGER NOT NULL DEFAULT 0,external_read INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 1,last_error TEXT,started_at INTEGER NOT NULL,finished_at INTEGER,updated_at INTEGER NOT NULL,UNIQUE(platform,from_date,to_date))")]);}
async function prepareStage(db:Db,platform:MarketingAdPlatform,from:string,to:string){await ensureMarketingAdStageTables(db);const staged=stageDb(db);await db.batch([db.prepare("DELETE FROM marketing_ad_metric_stage WHERE platform=? AND report_date>=? AND report_date<=?").bind(platform,from,to),db.prepare("DELETE FROM marketing_ad_sync_runs_stage WHERE platform=? AND from_date=? AND to_date=?").bind(platform,from,to)]);return staged;}
async function promote(db:Db,platform:MarketingAdPlatform,from:string,to:string,rowsWritten:number){await ensureMarketingAdConnectorTables(db);const now=Date.now(),runId=`MADSYNC-${crypto.randomUUID().slice(0,12).toUpperCase()}`;await db.batch([db.prepare("DELETE FROM marketing_ad_metric_facts WHERE platform=? AND report_date>=? AND report_date<=?").bind(platform,from,to),db.prepare(`INSERT INTO marketing_ad_metric_facts (${METRIC_COLUMNS}) SELECT ${METRIC_COLUMNS} FROM marketing_ad_metric_stage WHERE platform=? AND report_date>=? AND report_date<=?`).bind(platform,from,to),db.prepare("INSERT INTO marketing_ad_sync_runs (id,platform,from_date,to_date,status,rows_written,external_read,attempts,last_error,started_at,finished_at,updated_at) VALUES (?,?,?,?,'completed',?,1,1,NULL,?,?,?) ON CONFLICT(platform,from_date,to_date) DO UPDATE SET status='completed',rows_written=excluded.rows_written,external_read=1,attempts=marketing_ad_sync_runs.attempts+1,last_error=NULL,started_at=excluded.started_at,finished_at=excluded.finished_at,updated_at=excluded.updated_at").bind(runId,platform,from,to,rowsWritten,now,now,now)]);}

function actionValue(items:unknown,type:string){if(!Array.isArray(items))return 0;const found=items.find(item=>item&&typeof item==="object"&&text((item as Row).action_type)===type)as Row|undefined;return number(found?.value);}
async function enrichMetaPrimaryConversions(db:Db,runtime:Record<string,unknown>,input:{from:string;to:string;fetchImpl?:Fetcher}){
 const accountId=text(runtime.META_ADS_ACCOUNT_ID).replace(/\D/g,""),token=text(runtime.META_ADS_ACCESS_TOKEN),version=text(runtime.META_ADS_API_VERSION),priority=(text(runtime.META_ADS_PRIMARY_CONVERSION_ACTIONS)||"offsite_conversion.fb_pixel_purchase,purchase,offsite_conversion.fb_pixel_lead,lead").split(",").map(item=>item.trim()).filter(Boolean);if(!accountId||!token||!/^v\d+(?:\.\d+)?$/.test(version))return{enriched:0,configured:false};
 const url=new URL(`https://graph.facebook.com/${version}/act_${accountId}/insights`);url.searchParams.set("fields","ad_id,date_start,age,gender,actions,action_values");url.searchParams.set("level","ad");url.searchParams.set("time_increment","1");url.searchParams.set("time_range",JSON.stringify({since:input.from,until:input.to}));url.searchParams.set("breakdowns","age,gender");url.searchParams.set("limit","500");const fetchImpl=input.fetchImpl||fetch;let next:string|null=url.toString(),enriched=0;
 for(let page=0;page<100&&next;page++){const parsed=new URL(next);if(parsed.protocol!=="https:"||parsed.hostname!=="graph.facebook.com")throw new Error("Meta conversion enrichment pagination failed provider-host validation");const response=await fetchImpl(parsed,{headers:{authorization:`Bearer ${token}`}}),raw=await response.text();let body:Row={};try{body=raw?JSON.parse(raw):{};}catch{throw new Error("Meta conversion enrichment returned invalid JSON");}if(!response.ok){const nested=body.error&&typeof body.error==="object"?body.error as Row:{};throw new Error(`Meta conversion enrichment failed (${response.status}): ${text(nested.message||body.message||response.statusText).slice(0,300)}`);}for(const row of Array.isArray(body.data)?body.data as Row[]:[]){const selected=priority.find(type=>actionValue(row.actions,type)>0||actionValue(row.action_values,type)>0);const conversions=selected?actionValue(row.actions,selected):0,valueMinor=selected?Math.max(0,Math.round(actionValue(row.action_values,selected)*100)):0,adId=text(row.ad_id),date=text(row.date_start),age=text(row.age),gender=text(row.gender);if(!adId||!date)continue;const staged=await db.prepare("SELECT spend_minor FROM marketing_ad_metric_stage WHERE platform='meta_ads' AND report_date=? AND ad_id=? AND COALESCE(age_range,'')=? AND COALESCE(gender,'')=? LIMIT 1").bind(date,adId,age,gender).first<Row>();if(!staged)continue;const spend=Math.max(0,Number(staged.spend_minor||0)),cpa=conversions>0?Math.round(spend/conversions):0;const changed=await db.prepare("UPDATE marketing_ad_metric_stage SET conversions=?,conversion_value_minor=?,cpa_minor=?,updated_at=? WHERE platform='meta_ads' AND report_date=? AND ad_id=? AND COALESCE(age_range,'')=? AND COALESCE(gender,'')=?").bind(conversions,valueMinor,cpa,Date.now(),date,adId,age,gender).run();enriched+=Number(changed.meta?.changes||0);}const paging=body.paging&&typeof body.paging==="object"?body.paging as Row:{};next=text(paging.next)||null;}
 return{enriched,configured:true};
}

export async function syncGoogleAdsMetricsAtomic(db:Db,runtime:Record<string,unknown>,input:{from:string;to:string;fetchImpl?:Fetcher}){const staged=await prepareStage(db,"google_ads",input.from,input.to),result=await syncGoogleAdsMetrics(staged,runtime,input);if(result.status!=="completed")return result;await promote(db,"google_ads",input.from,input.to,result.rowsWritten);return{...result,atomicPromotion:true,duplicatePrevented:false};}
export async function syncMetaAdsMetricsAtomic(db:Db,runtime:Record<string,unknown>,input:{from:string;to:string;fetchImpl?:Fetcher}){const staged=await prepareStage(db,"meta_ads",input.from,input.to),result=await syncMetaAdsMetrics(staged,runtime,input);if(result.status!=="completed")return result;const enrichment=await enrichMetaPrimaryConversions(db,runtime,input);await promote(db,"meta_ads",input.from,input.to,result.rowsWritten);return{...result,atomicPromotion:true,duplicatePrevented:false,primaryConversionEnrichment:enrichment};}
export async function syncMarketingAdMetricsAtomic(db:Db,runtime:Record<string,unknown>,input:{from:string;to:string;fetchImpl?:Fetcher}){const settled=await Promise.allSettled([syncGoogleAdsMetricsAtomic(db,runtime,input),syncMetaAdsMetricsAtomic(db,runtime,input)]);return settled.map((result,index)=>result.status==="fulfilled"?result.value:{platform:index===0?"google_ads":"meta_ads",status:"failed",error:result.reason instanceof Error?result.reason.message:String(result.reason),rowsWritten:0,externalRead:false,atomicPromotion:false});}
