import{buildCustomer360}from"./customer-360";
type Row=Record<string,unknown>;
export async function ensureMarketingGovernance(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS governed_marketing_campaigns (id TEXT PRIMARY KEY,name TEXT NOT NULL,objective TEXT NOT NULL,service_code TEXT,city_id TEXT,audience_rule_json TEXT NOT NULL DEFAULT '{}',budget_amount REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',holdout_percent INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft',approval_status TEXT NOT NULL DEFAULT 'approval_required',approved_by TEXT,approved_at INTEGER,start_at INTEGER,end_at INTEGER,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS marketing_audience_snapshots (id TEXT PRIMARY KEY,campaign_id TEXT NOT NULL,snapshot_at INTEGER NOT NULL,total_candidates INTEGER NOT NULL,eligible_count INTEGER NOT NULL,holdout_count INTEGER NOT NULL,suppressed_count INTEGER NOT NULL,policy_json TEXT NOT NULL,created_by TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS marketing_audience_members (snapshot_id TEXT NOT NULL,campaign_id TEXT NOT NULL,customer_id TEXT NOT NULL,cohort TEXT NOT NULL,suppression_reason TEXT,PRIMARY KEY(snapshot_id,customer_id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS marketing_attribution_facts (id TEXT PRIMARY KEY,campaign_id TEXT NOT NULL,customer_id TEXT,lead_id TEXT,booking_id TEXT,collection_id TEXT,source TEXT NOT NULL,medium TEXT,spend_amount REAL,booked_revenue REAL,collected_revenue REAL,contribution_margin REAL,attribution_model TEXT NOT NULL DEFAULT 'unconfigured',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS marketing_governance_events (id TEXT PRIMARY KEY,campaign_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_email TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}
function bucket(customerId:string){let value=0;for(const c of customerId)value=(value*31+c.charCodeAt(0))%10000;return value%100;}
export async function snapshotCampaignAudience(db:D1Database,input:{campaignId:string;actor:string}){await ensureMarketingGovernance(db);const campaign=await db.prepare("SELECT * FROM governed_marketing_campaigns WHERE id=?").bind(input.campaignId).first<Row>();if(!campaign)throw new Error("Campaign not found");if(!["draft","approved","paused"].includes(String(campaign.status)))throw new Error("Campaign audience cannot be snapshotted in the current state");const customers=await buildCustomer360(db),holdout=Math.max(0,Math.min(100,Number(campaign.holdout_percent))),snapshotId=`AUD-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now();let eligible=0,suppressed=0,held=0;const statements=[];for(const customer of customers){const reasons:string[]=[];if(!customer.consent.marketing)reasons.push("marketing_consent_missing");if(customer.openTicketCount>0)reasons.push("open_customer_experience_case");if(customer.dataQuality.issues.includes("possible_duplicate"))reasons.push("duplicate_review_required");if(customer.dataQuality.score<60)reasons.push("data_quality_low");const cohort=reasons.length?"suppressed":bucket(customer.customerId)<holdout?"holdout":"eligible";if(cohort==="suppressed")suppressed++;else if(cohort==="holdout")held++;else eligible++;statements.push(db.prepare("INSERT INTO marketing_audience_members (snapshot_id,campaign_id,customer_id,cohort,suppression_reason) VALUES (?,?,?,?,?)").bind(snapshotId,input.campaignId,customer.customerId,cohort,reasons.length?reasons.join(","):null));}for(let i=0;i<statements.length;i+=25)await db.batch(statements.slice(i,i+25));await db.batch([db.prepare("INSERT INTO marketing_audience_snapshots (id,campaign_id,snapshot_at,total_candidates,eligible_count,holdout_count,suppressed_count,policy_json,created_by) VALUES (?,?,?,?,?,?,?,?,?)").bind(snapshotId,input.campaignId,now,customers.length,eligible,held,suppressed,JSON.stringify({marketingConsentRequired:true,openCxSuppressed:true,duplicateSuppressed:true,dataQualityMinimum:60,holdoutPercent:holdout}),input.actor),db.prepare("INSERT INTO marketing_governance_events (id,campaign_id,event_type,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),input.campaignId,"audience_snapshotted",input.actor,JSON.stringify({snapshotId,eligible,holdout:held,suppressed}),now)]);return{snapshotId,total:customers.length,eligible,holdout:held,suppressed};}
export async function activateCampaign(db:D1Database,input:{campaignId:string;actor:string}){await ensureMarketingGovernance(db);const row=await db.prepare("SELECT * FROM governed_marketing_campaigns WHERE id=?").bind(input.campaignId).first<Row>();if(!row)throw new Error("Campaign not found");if(String(row.approval_status)!=="approved")throw new Error("Campaign requires explicit approval before activation");const snapshot=await db.prepare("SELECT id FROM marketing_audience_snapshots WHERE campaign_id=? ORDER BY snapshot_at DESC LIMIT 1").bind(input.campaignId).first<Row>();if(!snapshot)throw new Error("Campaign requires a governed audience snapshot before activation");const now=Date.now();await db.batch([db.prepare("UPDATE governed_marketing_campaigns SET status='active',updated_at=? WHERE id=?").bind(now,input.campaignId),db.prepare("INSERT INTO marketing_governance_events (id,campaign_id,event_type,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),input.campaignId,"activated",input.actor,JSON.stringify({snapshotId:snapshot.id}),now)]);return{campaignId:input.campaignId,status:"active",liveMediaSpend:false};}
