import { ensureOutboundOrchestratorTables } from "./outbound-schema";
import { POWER_DIALLER_AUTO_ADVANCE_MS,POWER_DIALLER_MAX_NO_ANSWER_ATTEMPTS,POWER_DIALLER_NO_ANSWER_RETRY_MS,POWER_DIALLER_NOT_INTERESTED_COOLDOWN_MS } from "./power-dialler-policy";
type Db=D1Database;type Row=Record<string,unknown>;const text=(v:unknown)=>String(v??"").trim(),uid=(p:string)=>`${p}-${crypto.randomUUID().slice(0,12).toUpperCase()}`;
export type PowerDiallerDisposition="interested"|"booked"|"callback"|"no_answer"|"not_interested"|"wrong_number"|"dnd";
function actorOwnsLead(row:Row,actorId:string){const leadId=text(row.lead_id),owner=text(row.lead_owner);return!leadId||owner==="Unassigned"||owner.toLowerCase()===actorId.toLowerCase();}
export async function claimNextHumanQueue(db:Db,i:{actorId:string;asOf?:number}){
 await ensureOutboundOrchestratorTables(db);const now=i.asOf??Date.now();
 const current=await db.prepare("SELECT q.*,l.owner lead_owner FROM outbound_routing_queue q LEFT JOIN lead_work_items l ON l.id=q.lead_id WHERE q.lane='human' AND q.assigned_to=? AND q.status IN ('claimed','dialing') LIMIT 1").bind(i.actorId).first<Row>();
 if(current){if(text(current.status)==="dialing"||actorOwnsLead(current,i.actorId))return current;await db.prepare("UPDATE outbound_routing_queue SET status='queued',assigned_to=NULL,updated_at=? WHERE id=? AND assigned_to=? AND status='claimed'").bind(now,current.id,i.actorId).run();}
 // A lead-owned call follows the same canonical owner that CRM, task and SLA views show. Unassigned
 // leads and non-lead service queues remain claimable; a different employee's lead is not stolen.
 const q=await db.prepare("SELECT q.id FROM outbound_routing_queue q LEFT JOIN lead_work_items l ON l.id=q.lead_id WHERE q.lane='human' AND q.status='queued' AND (q.callback_at IS NULL OR q.callback_at<=?) AND (q.cooldown_until IS NULL OR q.cooldown_until<=?) AND (q.lead_id IS NULL OR l.owner='Unassigned' OR lower(l.owner)=lower(?)) ORDER BY CASE WHEN q.lead_id IS NOT NULL AND lower(l.owner)=lower(?) THEN 0 WHEN q.lead_id IS NULL THEN 1 ELSE 2 END,q.high_intent DESC,q.priority_score DESC,COALESCE(q.callback_at,q.created_at) LIMIT 1").bind(now,now,i.actorId,i.actorId).first<Row>();
 if(!q)return null;const r=await db.prepare("UPDATE outbound_routing_queue SET status='claimed',assigned_to=?,updated_at=? WHERE id=? AND status='queued'").bind(i.actorId,now,q.id).run();return Number(r.meta?.changes||0)?db.prepare("SELECT * FROM outbound_routing_queue WHERE id=?").bind(q.id).first<Row>():null;
}
export async function releaseHumanQueueClaim(db:Db,i:{queueId:string;actorId:string;asOf?:number}){const now=i.asOf??Date.now();const r=await db.prepare("UPDATE outbound_routing_queue SET status='queued',assigned_to=NULL,updated_at=? WHERE id=? AND assigned_to=? AND status='claimed'").bind(now,i.queueId,i.actorId).run();return{released:Number(r.meta?.changes||0)===1};}
export async function recordPowerDiallerDisposition(db:Db,i:{queueId:string;actorId:string;disposition:PowerDiallerDisposition;callbackAt?:number|null;asOf?:number}){await ensureOutboundOrchestratorTables(db);const now=i.asOf??Date.now(),q=await db.prepare("SELECT * FROM outbound_routing_queue WHERE id=?").bind(i.queueId).first<Row>();if(!q)throw new Error("Queue item not found");if(text(q.assigned_to)!==i.actorId)throw new Error("Queue item belongs to another employee");const attempts=Number(q.attempt_count||0)+1;let status="completed",callbackAt:null|number=null,cooldown:null|number=null;if(i.disposition==="callback"){callbackAt=Number(i.callbackAt||0);if(callbackAt<=now)throw new Error("Future callback time required");status="queued";cooldown=callbackAt}else if(i.disposition==="no_answer"&&attempts<POWER_DIALLER_MAX_NO_ANSWER_ATTEMPTS){status="queued";cooldown=now+POWER_DIALLER_NO_ANSWER_RETRY_MS}else if(i.disposition==="not_interested")await db.prepare("INSERT INTO outbound_contact_controls VALUES (?,?,?,?,?,?,?,?,?)").bind(uid("OCC"),q.customer_id,"cooling_period","marketing","Customer not interested",now+POWER_DIALLER_NOT_INTERESTED_COOLDOWN_MS,"power_dialler",i.actorId,now).run();else if(["wrong_number","dnd"].includes(i.disposition)){status="suppressed";await db.prepare("INSERT INTO outbound_contact_controls VALUES (?,?,?,?,?,NULL,?,?,?)").bind(uid("OCC"),q.customer_id,i.disposition,"all",i.disposition==="dnd"?"Customer requested DND":"Wrong number","power_dialler",i.actorId,now).run()}
 await db.prepare("UPDATE outbound_routing_queue SET status=?,attempt_count=?,callback_at=?,cooldown_until=?,assigned_to=CASE WHEN ?='queued' THEN NULL ELSE assigned_to END,updated_at=? WHERE id=?").bind(status,attempts,callbackAt,cooldown,status,now,i.queueId).run();await db.prepare("INSERT INTO outbound_dialler_events VALUES (?,?,?,?,?,?,?)").bind(uid("ODE"),i.queueId,i.actorId,"disposition",i.disposition,JSON.stringify({autoAdvanceAfterMs:POWER_DIALLER_AUTO_ADVANCE_MS}),now).run();return{queueId:i.queueId,status,attempts,callbackAt,cooldownUntil:cooldown,autoAdvanceAfterMs:POWER_DIALLER_AUTO_ADVANCE_MS};}
