export { decideOutboundRoute,OUTBOUND_POLICY_VERSION } from "./outbound-routing-policy";
export { ensureOutboundOrchestratorTables } from "./outbound-schema";
export { runOutboundOrchestrationSweep } from "./outbound-sweep";
export { detectAiOutboundEscalation,enqueueHumanEscalation } from "./outbound-escalation";
export { claimNextHumanQueue,releaseHumanQueueClaim,recordPowerDiallerDisposition,type PowerDiallerDisposition } from "./outbound-human-queue";
import { ensureOutboundOrchestratorTables } from "./outbound-schema";
type Db=D1Database;type Row=Record<string,unknown>;const text=(v:unknown)=>String(v??"").trim();
async function all(db:Db,sql:string,b:unknown[]=[]){try{let q=db.prepare(sql);if(b.length)q=q.bind(...b);return(await q.all<Row>()).results||[]}catch{return[]}}
function objectJson(value:unknown):Record<string,unknown>{try{const parsed=JSON.parse(text(value)||"{}");return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{}}}
export async function getPowerDiallerHud(db:Db,id:string){await ensureOutboundOrchestratorTables(db);const q=await db.prepare("SELECT * FROM outbound_routing_queue WHERE id=?").bind(id).first<Row>();if(!q)return null;const cid=text(q.customer_id),[customer,pets,history,score,handoff,messages]=await Promise.all([db.prepare("SELECT id,name,primary_phone,email,city_id FROM canonical_customers WHERE id=?").bind(cid).first<Row>(),all(db,"SELECT id,name,species,breed FROM canonical_pets WHERE customer_id=? LIMIT 10",[cid]),all(db,"SELECT id,service_code,package_name,status,scheduled_start,scheduled_end,total_amount,currency FROM canonical_bookings WHERE customer_id=? ORDER BY scheduled_start DESC LIMIT 12",[cid]),q.lead_id?db.prepare("SELECT * FROM lead_scores WHERE lead_id=?").bind(q.lead_id).first<Row>().catch(()=>null):null,db.prepare("SELECT summary_json FROM ai_handoffs WHERE customer_id=? ORDER BY created_at DESC LIMIT 1").bind(cid).first<Row>().catch(()=>null),all(db,"SELECT direction,channel,payload_json,created_at FROM communication_messages WHERE customer_id=? ORDER BY created_at DESC LIMIT 8",[cid])]);const ctx=objectJson(q.context_json),aiSummary=handoff?objectJson(handoff.summary_json):ctx.aiSummary?{transcript:[{direction:"customer",text:text(ctx.aiSummary)}]}:null,recentConversation=messages.reverse().map(r=>{const p=objectJson(r.payload_json);return{direction:text(r.direction),channel:text(r.channel),text:text(p.text||p.message||p.body||p.content),createdAt:Number(r.created_at||0)}}).filter(x=>x.text);return{queue:{id:text(q.id),status:text(q.status),lifecycleCode:text(q.lifecycle_code),priorityScore:Number(q.priority_score),highIntent:Number(q.high_intent)===1,targetOffer:text(q.target_offer)||null,nextBestService:text(q.next_best_service)||null,expectedRevenue:q.expected_revenue==null?null:Number(q.expected_revenue),ltv:Number(q.ltv||0),callbackAt:q.callback_at==null?null:Number(q.callback_at),attemptCount:Number(q.attempt_count||0),reasons:Array.isArray(ctx.decisionReasons)?ctx.decisionReasons:[]},customer,pets,serviceHistory:history,leadScore:score?{total:Number(score.total_score||0),grade:text(score.grade),engagement:Number(score.engagement_score||0),profile:Number(score.profile_score||0),recency:Number(score.recency_score||0),value:Number(score.value_score||0)}:{total:Number(ctx.leadScore||0),grade:null},aiSummary,recentConversation};}
export async function outboundQueueStats(db:Db){await ensureOutboundOrchestratorTables(db);const rows=await all(db,"SELECT lane,status,COUNT(*) count FROM outbound_routing_queue GROUP BY lane,status");return{byLaneStatus:rows,humanWaiting:rows.filter(r=>text(r.lane)==="human"&&text(r.status)==="queued").reduce((n,r)=>n+Number(r.count||0),0),aiWaiting:rows.filter(r=>text(r.lane)==="ai"&&text(r.status)==="queued").reduce((n,r)=>n+Number(r.count||0),0)};}