type Db=D1Database;
type Row=Record<string,unknown>;
const encoder=new TextEncoder();
const text=(value:unknown)=>String(value??"").trim();
const hex=(buffer:ArrayBuffer)=>Array.from(new Uint8Array(buffer)).map(value=>value.toString(16).padStart(2,"0")).join("");
async function sha256(value:string){return hex(await crypto.subtle.digest("SHA-256",encoder.encode(value)));}
async function tableExists(db:Db,name:string){return Boolean(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first<Row>());}
async function columns(db:Db,name:string){if(!await tableExists(db,name))return new Set<string>();const result=await db.prepare(`PRAGMA table_info(${name})`).all<Row>();return new Set(result.results.map(row=>text(row.name)));}
async function addColumn(db:Db,table:string,column:string,definition:string){const cols=await columns(db,table);if(cols.has(column))return;try{await db.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run();}catch(error){if(!/duplicate column/i.test(error instanceof Error?error.message:String(error)))throw error;}}

export type VerifiedPayoutBeneficiary={providerId:string;applicationId:string;verificationId:string;verificationStatus:"verified";verifiedAt:number|null;expiresAt:number|null;razorpayxContactId:string;razorpayxFundAccountId:string;profileStatus:"active";snapshotJson:string;snapshotSha256:string;verifiedForPayoutAt:number;};

export async function assertActiveVerifiedPayoutBeneficiary(db:Db,providerIdInput:string,asOf=Date.now()):Promise<VerifiedPayoutBeneficiary>{
 const providerId=text(providerIdInput);if(!providerId)throw new Error("Payout provider ID is required");
 if(!await tableExists(db,"provider_compensation_profiles"))throw new Error("Payout beneficiary profile is not configured");
 if(!await tableExists(db,"provider_onboarding_applications")||!await tableExists(db,"provider_verifications"))throw new Error("Provider bank KYC verification store is not configured");
 const profile=await db.prepare("SELECT provider_id,status,razorpayx_contact_id,razorpayx_fund_account_id FROM provider_compensation_profiles WHERE provider_id=? LIMIT 1").bind(providerId).first<Row>();
 if(!profile||text(profile.status)!=="active")throw new Error("Payout beneficiary profile must be active");
 const contactId=text(profile.razorpayx_contact_id),fundAccountId=text(profile.razorpayx_fund_account_id);if(!contactId||!fundAccountId)throw new Error("Payout beneficiary requires RazorpayX contact and fund account bindings");
 const application=await db.prepare("SELECT id FROM provider_onboarding_applications WHERE provider_id=? ORDER BY updated_at DESC LIMIT 1").bind(providerId).first<Row>();if(!application)throw new Error("Payout beneficiary has no governed onboarding application");
 const verification=await db.prepare("SELECT id,status,verified_at,expires_at FROM provider_verifications WHERE application_id=? AND verification_type='bank_kyc' ORDER BY COALESCE(verified_at,updated_at,created_at) DESC LIMIT 1").bind(text(application.id)).first<Row>();
 if(!verification||text(verification.status)!=="verified")throw new Error("Payout beneficiary bank_kyc is not verified");
 const expiresAt=verification.expires_at==null?null:Number(verification.expires_at);if(expiresAt!==null&&Number.isFinite(expiresAt)&&expiresAt<=asOf)throw new Error("Payout beneficiary bank_kyc has expired");
 const snapshot={version:1,providerId,applicationId:text(application.id),verificationId:text(verification.id),verificationType:"bank_kyc",verificationStatus:"verified",verifiedAt:verification.verified_at==null?null:Number(verification.verified_at),expiresAt,profileStatus:"active",razorpayxContactId:contactId,razorpayxFundAccountId:fundAccountId,verifiedForPayoutAt:asOf};
 const snapshotJson=JSON.stringify(snapshot),snapshotSha256=await sha256(snapshotJson);
 return{providerId,applicationId:snapshot.applicationId,verificationId:snapshot.verificationId,verificationStatus:"verified",verifiedAt:snapshot.verifiedAt,expiresAt,razorpayxContactId:contactId,razorpayxFundAccountId:fundAccountId,profileStatus:"active",snapshotJson,snapshotSha256,verifiedForPayoutAt:asOf};
}

export async function ensurePayoutBeneficiarySnapshotSchema(db:Db){
 if(await tableExists(db,"provider_verifications")){await addColumn(db,"provider_verifications","expires_at","INTEGER");await addColumn(db,"provider_verifications","verified_at","INTEGER");await db.prepare("UPDATE provider_verifications SET verified_at=updated_at WHERE status='verified' AND verified_at IS NULL").run().catch(()=>{});}
 if(await tableExists(db,"provider_order_payouts")){await addColumn(db,"provider_order_payouts","beneficiary_snapshot_json","TEXT");await addColumn(db,"provider_order_payouts","beneficiary_snapshot_sha256","TEXT");await addColumn(db,"provider_order_payouts","beneficiary_verified_at","INTEGER");}
 if(await tableExists(db,"partner_payout_instructions")){await addColumn(db,"partner_payout_instructions","beneficiary_snapshot_json","TEXT");await addColumn(db,"partner_payout_instructions","beneficiary_snapshot_sha256","TEXT");await addColumn(db,"partner_payout_instructions","beneficiary_verified_at","INTEGER");await addColumn(db,"partner_payout_instructions","razorpayx_contact_id","TEXT");await addColumn(db,"partner_payout_instructions","razorpayx_fund_account_id","TEXT");}
 await db.prepare("CREATE TABLE IF NOT EXISTS payout_beneficiary_preauthorizations (scope_type TEXT NOT NULL,scope_id TEXT NOT NULL,provider_id TEXT NOT NULL,snapshot_json TEXT NOT NULL,snapshot_sha256 TEXT NOT NULL,razorpayx_contact_id TEXT NOT NULL,razorpayx_fund_account_id TEXT NOT NULL,verified_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(scope_type,scope_id))").run();
 if(await tableExists(db,"provider_order_payouts"))await db.exec(`CREATE TRIGGER IF NOT EXISTS trg_provider_order_payout_snapshot_after_insert AFTER INSERT ON provider_order_payouts BEGIN UPDATE provider_order_payouts SET beneficiary_snapshot_json=(SELECT snapshot_json FROM payout_beneficiary_preauthorizations WHERE scope_type='booking' AND scope_id=NEW.booking_id AND provider_id=NEW.provider_id AND expires_at>=NEW.created_at),beneficiary_snapshot_sha256=(SELECT snapshot_sha256 FROM payout_beneficiary_preauthorizations WHERE scope_type='booking' AND scope_id=NEW.booking_id AND provider_id=NEW.provider_id AND expires_at>=NEW.created_at),beneficiary_verified_at=(SELECT verified_at FROM payout_beneficiary_preauthorizations WHERE scope_type='booking' AND scope_id=NEW.booking_id AND provider_id=NEW.provider_id AND expires_at>=NEW.created_at) WHERE id=NEW.id; SELECT CASE WHEN (SELECT beneficiary_snapshot_sha256 FROM provider_order_payouts WHERE id=NEW.id) IS NULL THEN RAISE(ABORT,'verified payout beneficiary snapshot required') END; END;`);
 if(await tableExists(db,"partner_payout_instructions"))await db.exec(`CREATE TRIGGER IF NOT EXISTS trg_partner_payout_requires_beneficiary BEFORE UPDATE OF status ON partner_payout_instructions WHEN NEW.status='approved_sandbox' BEGIN SELECT CASE WHEN NEW.beneficiary_snapshot_sha256 IS NULL OR NEW.razorpayx_contact_id IS NULL OR NEW.razorpayx_fund_account_id IS NULL THEN RAISE(ABORT,'verified payout beneficiary snapshot required') END; END;`);
}

export async function preauthorizeVerifiedPayoutBeneficiary(db:Db,input:{providerId:string;scopeType:"booking"|"settlement"|"instruction";scopeId:string;asOf?:number}){
 await ensurePayoutBeneficiarySnapshotSchema(db);const asOf=input.asOf??Date.now(),scopeId=text(input.scopeId);if(!scopeId)throw new Error("Payout beneficiary scope ID is required");const verified=await assertActiveVerifiedPayoutBeneficiary(db,input.providerId,asOf),expires=asOf+15*60_000;
 await db.prepare("INSERT INTO payout_beneficiary_preauthorizations (scope_type,scope_id,provider_id,snapshot_json,snapshot_sha256,razorpayx_contact_id,razorpayx_fund_account_id,verified_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(scope_type,scope_id) DO UPDATE SET provider_id=excluded.provider_id,snapshot_json=excluded.snapshot_json,snapshot_sha256=excluded.snapshot_sha256,razorpayx_contact_id=excluded.razorpayx_contact_id,razorpayx_fund_account_id=excluded.razorpayx_fund_account_id,verified_at=excluded.verified_at,expires_at=excluded.expires_at").bind(input.scopeType,scopeId,verified.providerId,verified.snapshotJson,verified.snapshotSha256,verified.razorpayxContactId,verified.razorpayxFundAccountId,asOf,expires).run();
 if(input.scopeType==="instruction"&&await tableExists(db,"partner_payout_instructions")){const changed=await db.prepare("UPDATE partner_payout_instructions SET beneficiary_snapshot_json=?,beneficiary_snapshot_sha256=?,beneficiary_verified_at=?,razorpayx_contact_id=?,razorpayx_fund_account_id=?,updated_at=? WHERE id=? AND provider_id=?").bind(verified.snapshotJson,verified.snapshotSha256,asOf,verified.razorpayxContactId,verified.razorpayxFundAccountId,asOf,scopeId,verified.providerId).run();if(Number(changed.meta?.changes||0)!==1)throw new Error("Payout instruction/provider beneficiary binding mismatch");}
 return verified;
}
