type Db=D1Database;
type Row=Record<string,unknown>;
const text=(v:unknown)=>String(v??"").trim();
const uid=(p:string)=>`${p}-${crypto.randomUUID().slice(0,12).toUpperCase()}`;
export async function ensurePeopleTables(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS employees (id TEXT PRIMARY KEY,user_email TEXT UNIQUE,employee_code TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,work_email TEXT NOT NULL UNIQUE,phone TEXT,employment_status TEXT NOT NULL DEFAULT 'active',joined_at INTEGER,ended_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS employee_employment_versions (id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,version INTEGER NOT NULL,effective_from INTEGER NOT NULL,effective_until INTEGER,employment_type TEXT,probation_status TEXT,title TEXT,team_code TEXT,manager_employee_id TEXT,cost_centre_code TEXT,location_code TEXT,reason TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(employee_id,version))"),
 db.prepare("CREATE TABLE IF NOT EXISTS people_audit_events (id TEXT PRIMARY KEY,employee_id TEXT,action TEXT NOT NULL,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS employee_employment_effective_idx ON employee_employment_versions(employee_id,effective_from,effective_until)"),
]);}
export function maskEmployeePhone(v:unknown){const d=text(v).replace(/\D/g,"");return d.length>=4?`+91 ••••••${d.slice(-4)}`:"Not available";}
export async function upsertEmployee(db:Db,input:{id?:string;userEmail?:string|null;employeeCode:string;displayName:string;workEmail:string;phone?:string|null;joinedAt?:number|null;actorId:string}){await ensurePeopleTables(db);if(!input.employeeCode.trim()||!input.displayName.trim()||!input.workEmail.trim())throw new Error("Employee code, name and work email are required");const now=Date.now(),id=input.id?.trim()||uid("EMP"),prior=await db.prepare("SELECT id FROM employees WHERE id=? OR employee_code=? OR work_email=?").bind(id,input.employeeCode.trim(),input.workEmail.trim().toLowerCase()).first<Row>();if(prior)await db.prepare("UPDATE employees SET user_email=?,employee_code=?,display_name=?,work_email=?,phone=?,joined_at=COALESCE(joined_at,?),updated_at=? WHERE id=?").bind(input.userEmail?.trim().toLowerCase()||null,input.employeeCode.trim(),input.displayName.trim(),input.workEmail.trim().toLowerCase(),input.phone?.trim()||null,input.joinedAt??null,now,prior.id).run();else await db.prepare("INSERT INTO employees (id,user_email,employee_code,display_name,work_email,phone,joined_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,input.userEmail?.trim().toLowerCase()||null,input.employeeCode.trim(),input.displayName.trim(),input.workEmail.trim().toLowerCase(),input.phone?.trim()||null,input.joinedAt??null,now,now).run();const employeeId=text(prior?.id||id);await db.prepare("INSERT INTO people_audit_events (id,employee_id,action,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(uid("PAE"),employeeId,prior?"employee.updated":"employee.created",input.actorId,JSON.stringify({employeeCode:input.employeeCode,workEmail:input.workEmail}),now).run();return db.prepare("SELECT * FROM employees WHERE id=?").bind(employeeId).first<Row>();}
export async function addEmploymentVersion(db:Db,input:{employeeId:string;effectiveFrom:number;employmentType?:string|null;probationStatus?:string|null;title?:string|null;teamCode?:string|null;managerEmployeeId?:string|null;costCentreCode?:string|null;locationCode?:string|null;reason:string;actorId:string}){await ensurePeopleTables(db);if(!Number.isFinite(input.effectiveFrom)||input.effectiveFrom<=0)throw new Error("Effective-from is required");if(input.reason.trim().length<8)throw new Error("A clear employment change reason is required");const emp=await db.prepare("SELECT id FROM employees WHERE id=?").bind(input.employeeId).first<Row>();if(!emp)throw new Error("Employee not found");const prior=await db.prepare("SELECT * FROM employee_employment_versions WHERE employee_id=? ORDER BY version DESC LIMIT 1").bind(input.employeeId).first<Row>();const version=Number(prior?.version||0)+1,now=Date.now();if(prior&&Number(prior.effective_from)>=input.effectiveFrom)throw new Error("Employment changes must be effective-dated after the current version");if(prior)await db.prepare("UPDATE employee_employment_versions SET effective_until=? WHERE id=? AND effective_until IS NULL").bind(input.effectiveFrom-1,prior.id).run();await db.prepare("INSERT INTO employee_employment_versions (id,employee_id,version,effective_from,employment_type,probation_status,title,team_code,manager_employee_id,cost_centre_code,location_code,reason,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(uid("EEV"),input.employeeId,version,input.effectiveFrom,input.employmentType??null,input.probationStatus??null,input.title??null,input.teamCode??null,input.managerEmployeeId??null,input.costCentreCode??null,input.locationCode??null,input.reason.trim(),input.actorId,now).run();await db.prepare("INSERT INTO people_audit_events (id,employee_id,action,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(uid("PAE"),input.employeeId,"employment.version_created",input.actorId,JSON.stringify({version,effectiveFrom:input.effectiveFrom}),now).run();return db.prepare("SELECT * FROM employee_employment_versions WHERE employee_id=? AND version=?").bind(input.employeeId,version).first<Row>();}
export async function peopleDirectory(db:Db,input:{includeSensitive:boolean}){await ensurePeopleTables(db);const rows=await db.prepare("SELECT e.*,v.version,v.effective_from,v.effective_until,v.employment_type,v.probation_status,v.title,v.team_code,v.manager_employee_id,v.cost_centre_code,v.location_code FROM employees e LEFT JOIN employee_employment_versions v ON v.employee_id=e.id AND v.effective_until IS NULL ORDER BY e.display_name").all<Row>();return rows.results.map(r=>({...r,phone:input.includeSensitive?text(r.phone)||null:maskEmployeePhone(r.phone),sensitiveMasked:!input.includeSensitive}));}
