export const CANONICAL_PROVIDER_STATES=["requested","provider_matched","accepted","in_transit","arrived","in_progress","completed"] as const;
export type CanonicalProviderState=typeof CANONICAL_PROVIDER_STATES[number];
export type CanonicalProviderTerminalState="cancelled"|"rejected"|"expired";
export type CanonicalProviderLifecycleState=CanonicalProviderState|CanonicalProviderTerminalState;
export type ProviderServiceCode="grooming"|"pet_sitting"|"dog_walking"|"boarding"|"dog_training";

type Db=D1Database;
type Row=Record<string,unknown>;
type Prepared=ReturnType<Db["prepare"]>;
const NEXT:Record<CanonicalProviderLifecycleState,CanonicalProviderLifecycleState[]>={
 requested:["provider_matched","cancelled","expired"],
 provider_matched:["accepted","rejected","cancelled","expired"],
 accepted:["in_transit","rejected","cancelled","expired"],
 in_transit:["arrived","rejected","cancelled","expired"],
 arrived:["in_progress","rejected","cancelled","expired"],
 in_progress:["completed","rejected","cancelled"],
 completed:[],cancelled:[],rejected:["requested"],expired:["requested"],
};
const ensured=new WeakSet<object>();
export function lifecycleConflict(message="Unable to update provider lifecycle. Invalid or stale state."){return new Response(JSON.stringify({error:message}),{status:409,headers:{"content-type":"application/json"}});}
export function assertCanonicalProviderTransition(from:CanonicalProviderLifecycleState,to:CanonicalProviderLifecycleState){if(!NEXT[from]?.includes(to))throw lifecycleConflict(`Provider lifecycle cannot transition from ${from} to ${to}`);return true;}
export function assertCanonicalProviderPath(from:CanonicalProviderLifecycleState,path:CanonicalProviderLifecycleState[]){let current=from;for(const next of path){assertCanonicalProviderTransition(current,next);current=next;}return current;}
export function canonicalAssignmentPath(){return{from:"requested" as const,path:["provider_matched" as const]};}
export function canonicalRecoveryPath(from:CanonicalProviderLifecycleState,terminal:CanonicalProviderTerminalState,requeue=false){assertCanonicalProviderTransition(from,terminal);if(!requeue)return[terminal];if(!["rejected","expired"].includes(terminal))throw lifecycleConflict(`Provider lifecycle cannot requeue from ${terminal}`);return[terminal,"requested"] as CanonicalProviderLifecycleState[];}
export function canonicalStateFromServiceStatus(service:ProviderServiceCode,status:unknown):CanonicalProviderLifecycleState{const s=String(status??"");const maps:Record<ProviderServiceCode,Record<string,CanonicalProviderLifecycleState>>={grooming:{confirmed:"provider_matched",awaiting_acceptance:"provider_matched",assigned:"accepted",on_the_way:"in_transit",arrived:"arrived",in_service:"in_progress",completed:"completed",cancelled:"cancelled"},pet_sitting:{confirmed:"provider_matched",awaiting_provider_acceptance:"provider_matched",assigned:"accepted",in_progress:"in_progress",completed:"completed",cancelled:"cancelled",reassignment_needed:"requested"},dog_walking:{confirmed:"provider_matched",assigned:"accepted",in_progress:"in_progress",completed:"completed",cancelled:"cancelled",reassignment_needed:"requested"},boarding:{awaiting_host_acceptance:"provider_matched",recovery_pending:"provider_matched",confirmed:"accepted",in_progress:"in_progress",completed:"completed",cancelled:"cancelled"},dog_training:{scheduled:"provider_matched",accepted:"accepted",on_the_way:"in_transit",arrived:"arrived",in_session:"in_progress",completed:"completed",cancelled:"cancelled",no_show:"expired",reschedule_requested:"rejected"}};const value=maps[service][s];if(!value)throw lifecycleConflict(`No canonical provider state mapping exists for ${service}:${s}`);return value;}
export function canonicalPathForServiceAction(service:ProviderServiceCode,action:string,context:{allComplete?:boolean}={}):{from:CanonicalProviderLifecycleState;path:CanonicalProviderLifecycleState[]}|null{const key=`${service}:${action}`;const map:Record<string,{from:CanonicalProviderLifecycleState;path:CanonicalProviderLifecycleState[]}>= {"grooming:accept":{from:"provider_matched",path:["accepted"]},"grooming:on_the_way":{from:"accepted",path:["in_transit"]},"grooming:arrived":{from:"in_transit",path:["arrived"]},"grooming:start_service":{from:"arrived",path:["in_progress"]},"grooming:complete":{from:"in_progress",path:["completed"]},"pet_sitting:accept":{from:"provider_matched",path:["accepted"]},"pet_sitting:check_in":{from:"accepted",path:["in_transit","arrived","in_progress"]},"pet_sitting:check_out":{from:"in_progress",path:["completed"]},"dog_walking:accept":{from:"provider_matched",path:["accepted"]},"dog_walking:start_walk":{from:"accepted",path:["in_transit","arrived","in_progress"]},"boarding:accept":{from:"provider_matched",path:["accepted"]},"boarding:check_in":{from:"accepted",path:["in_transit","arrived","in_progress"]},"boarding:check_out":{from:"in_progress",path:["completed"]},"dog_training:accept":{from:"provider_matched",path:["accepted"]},"dog_training:on_the_way":{from:"accepted",path:["in_transit"]},"dog_training:arrive":{from:"in_transit",path:["arrived"]},"dog_training:start":{from:"arrived",path:["in_progress"]},"dog_training:complete":{from:"in_progress",path:["completed"]}};if(key==="dog_walking:complete_walk")return context.allComplete?{from:"in_progress",path:["completed"]}:null;return map[key]??null;}
export async function ensureProviderLifecycleTables(db:Db){if(ensured.has(db as object))return;await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS provider_lifecycle_records (lifecycle_key TEXT PRIMARY KEY,booking_id TEXT NOT NULL,service_code TEXT NOT NULL,scope_id TEXT NOT NULL,provider_id TEXT,status TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,lease_token TEXT,lease_expires_at INTEGER,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL)"),db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_lifecycle_scope ON provider_lifecycle_records(service_code,scope_id)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_provider_lifecycle_booking ON provider_lifecycle_records(booking_id,status)"),db.prepare("CREATE TABLE IF NOT EXISTS provider_lifecycle_events (id TEXT PRIMARY KEY,lifecycle_key TEXT NOT NULL,booking_id TEXT NOT NULL,service_code TEXT NOT NULL,scope_id TEXT NOT NULL,provider_id TEXT,from_status TEXT NOT NULL,to_status TEXT NOT NULL,actor_id TEXT NOT NULL,reason TEXT,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS provider_lifecycle_assertions (id TEXT PRIMARY KEY,ok INTEGER NOT NULL CHECK(ok=1),created_at INTEGER NOT NULL)")]);ensured.add(db as object);}
export type LifecycleLease={lifecycleKey:string;bookingId:string;serviceCode:ProviderServiceCode;scopeId:string;providerId:string|null;nextProviderId:string|null|undefined;from:CanonicalProviderLifecycleState;to:CanonicalProviderLifecycleState;path:CanonicalProviderLifecycleState[];token:string;actorId:string;reason?:string;detail?:unknown};
export type LifecycleContext={lease:LifecycleLease;guardSql:string;guardBinds:unknown[]};
function lifecycleKey(serviceCode:ProviderServiceCode,scopeId:string){return `${serviceCode}:${scopeId}`;}
export async function ensureProviderLifecycleRecord(db:Db,input:{bookingId:string;serviceCode:ProviderServiceCode;scopeId?:string;providerId?:string|null;status:CanonicalProviderLifecycleState;actorId:string}){await ensureProviderLifecycleTables(db);const scopeId=input.scopeId??input.bookingId,key=lifecycleKey(input.serviceCode,scopeId),now=Date.now();await db.prepare("INSERT OR IGNORE INTO provider_lifecycle_records (lifecycle_key,booking_id,service_code,scope_id,provider_id,status,version,lease_token,lease_expires_at,updated_by,updated_at) VALUES (?,?,?,?,?,?,1,NULL,NULL,?,?)").bind(key,input.bookingId,input.serviceCode,scopeId,input.providerId??null,input.status,input.actorId,now).run();const row=await db.prepare("SELECT lifecycle_key,booking_id,service_code,scope_id,provider_id,status,version,lease_token,lease_expires_at FROM provider_lifecycle_records WHERE lifecycle_key=?").bind(key).first<Row>();if(!row)throw lifecycleConflict("Provider lifecycle record could not be created");return row;}
export async function acquireProviderLifecycleLease(db:Db,input:{bookingId:string;serviceCode:ProviderServiceCode;scopeId?:string;providerId?:string|null;nextProviderId?:string|null;from:CanonicalProviderLifecycleState;path:CanonicalProviderLifecycleState[];actorId:string;reason?:string;detail?:unknown;legacySeedStatus?:CanonicalProviderLifecycleState;leaseMs?:number}):Promise<LifecycleLease>{assertCanonicalProviderPath(input.from,input.path);const to=input.path.at(-1)??input.from,scopeId=input.scopeId??input.bookingId,key=lifecycleKey(input.serviceCode,scopeId),now=Date.now(),token=crypto.randomUUID(),leaseMs=Math.max(5000,input.leaseMs??30_000);const row=await ensureProviderLifecycleRecord(db,{bookingId:input.bookingId,serviceCode:input.serviceCode,scopeId,providerId:input.providerId,status:input.legacySeedStatus??input.from,actorId:input.actorId});if(input.providerId!==undefined&&row.provider_id!==null&&String(row.provider_id)!==String(input.providerId))throw lifecycleConflict("Provider lifecycle ownership changed; refresh before updating");const claim=await db.prepare("UPDATE provider_lifecycle_records SET lease_token=?,lease_expires_at=?,updated_by=?,updated_at=? WHERE lifecycle_key=? AND status=? AND (lease_token IS NULL OR lease_expires_at<?)").bind(token,now+leaseMs,input.actorId,now,key,input.from,now).run();if(Number(claim?.meta?.changes||0)!==1)throw lifecycleConflict();return{lifecycleKey:key,bookingId:input.bookingId,serviceCode:input.serviceCode,scopeId,providerId:row.provider_id==null?null:String(row.provider_id),nextProviderId:input.nextProviderId,from:input.from,to,path:input.path,token,actorId:input.actorId,reason:input.reason,detail:input.detail};}
export function providerLifecycleGuard(lease:LifecycleLease){return{guardSql:"EXISTS (SELECT 1 FROM provider_lifecycle_records pl_guard WHERE pl_guard.lifecycle_key=? AND pl_guard.status=? AND pl_guard.lease_token=?)",guardBinds:[lease.lifecycleKey,lease.from,lease.token]};}
export function providerLifecycleAssertionStatement(db:Db,ctx:LifecycleContext,predicateSql:string,predicateBinds:unknown[]=[]){return db.prepare(`INSERT INTO provider_lifecycle_assertions (id,ok,created_at) SELECT ?,CASE WHEN (${ctx.guardSql}) AND (${predicateSql}) THEN 1 ELSE 0 END,?`).bind(ctx.lease.token,...ctx.guardBinds,...predicateBinds,Date.now());}
export async function releaseProviderLifecycleLease(db:Db,lease:LifecycleLease){await db.prepare("UPDATE provider_lifecycle_records SET lease_token=NULL,lease_expires_at=NULL,updated_at=? WHERE lifecycle_key=? AND lease_token=?").bind(Date.now(),lease.lifecycleKey,lease.token).run();}
export async function finalizeProviderLifecycleLease(db:Db,lease:LifecycleLease,input:{buildStatements:(ctx:LifecycleContext)=>Prepared[];buildAssertion?:(ctx:LifecycleContext)=>Prepared}){const now=Date.now(),ctx:LifecycleContext={lease,...providerLifecycleGuard(lease)};const statements=input.buildStatements(ctx);if(input.buildAssertion)statements.push(input.buildAssertion(ctx));const providerUpdate=lease.nextProviderId!==undefined?1:0;statements.push(db.prepare("UPDATE provider_lifecycle_records SET status=?,provider_id=CASE WHEN ?=1 THEN ? ELSE provider_id END,version=version+1,lease_token=NULL,lease_expires_at=NULL,updated_by=?,updated_at=? WHERE lifecycle_key=? AND status=? AND lease_token=?").bind(lease.to,providerUpdate,lease.nextProviderId??null,lease.actorId,now,lease.lifecycleKey,lease.from,lease.token));statements.push(db.prepare("DELETE FROM provider_lifecycle_assertions WHERE id=?").bind(lease.token));const eventProvider=lease.nextProviderId!==undefined?lease.nextProviderId:lease.providerId;statements.push(db.prepare("INSERT INTO provider_lifecycle_events (id,lifecycle_key,booking_id,service_code,scope_id,provider_id,from_status,to_status,actor_id,reason,detail_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM provider_lifecycle_records WHERE lifecycle_key=? AND status=? AND lease_token IS NULL)").bind(crypto.randomUUID(),lease.lifecycleKey,lease.bookingId,lease.serviceCode,lease.scopeId,eventProvider,lease.from,lease.to,lease.actorId,lease.reason??null,JSON.stringify({path:lease.path,detail:lease.detail??null}),now,lease.lifecycleKey,lease.to));const results=await db.batch(statements);const lifecycleResult=results[results.length-3];if(Number(lifecycleResult?.meta?.changes||0)!==1)throw lifecycleConflict();return{from:lease.from,to:lease.to,path:lease.path,token:lease.token,providerId:eventProvider};}
export async function runAtomicProviderLifecycleTransition(db:Db,input:Parameters<typeof acquireProviderLifecycleLease>[1]&{buildStatements:(ctx:LifecycleContext)=>Prepared[];buildAssertion?:(ctx:LifecycleContext)=>Prepared}){const lease=await acquireProviderLifecycleLease(db,input);try{return await finalizeProviderLifecycleLease(db,lease,{buildStatements:input.buildStatements,buildAssertion:input.buildAssertion});}catch(error){await releaseProviderLifecycleLease(db,lease).catch(()=>{});throw error;}}
