type Row=Record<string,unknown>;
export type CommissionMode="fixed"|"percent";
export type EngagementModel="full_time"|"commission";
const FIVE_DAYS=5*24*60*60*1000;
const rows=<T=Row>(r:{results?:unknown[]})=>(r.results||[]) as T[];

function commissionAmount(orderAmount:number,mode:CommissionMode,value:number){if(!Number.isFinite(value)||value<0)throw new Error("Commission value must be zero or greater");if(mode==="percent"){if(value>100)throw new Error("Commission percent cannot exceed 100");return Math.round(orderAmount*value)/100;}return Math.min(orderAmount,Math.round(value*100)/100);}
async function event(db:D1Database,bookingId:string,eventType:string,actor:string,detail:unknown){await db.prepare("INSERT INTO provider_commission_events (id,booking_id,event_type,actor_email,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),bookingId,eventType,actor,JSON.stringify(detail),Date.now()).run();}

export async function ensureProviderCommissionTables(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS provider_compensation_profiles (provider_id TEXT PRIMARY KEY,engagement_model TEXT NOT NULL DEFAULT 'full_time',default_commission_mode TEXT,default_commission_value REAL,razorpayx_contact_id TEXT,razorpayx_fund_account_id TEXT,status TEXT NOT NULL DEFAULT 'active',reason TEXT,updated_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS provider_order_commissions (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,work_order_id TEXT NOT NULL,provider_id TEXT NOT NULL,service_code TEXT NOT NULL,order_amount REAL NOT NULL,commission_mode TEXT,commission_value REAL,commission_amount REAL NOT NULL DEFAULT 0,commission_source TEXT NOT NULL DEFAULT 'provider_default',override_reason TEXT,status TEXT NOT NULL DEFAULT 'configuration_required',completed_at INTEGER NOT NULL,due_at INTEGER NOT NULL,confirmed_by TEXT,confirmed_at INTEGER,approval_level_1_by TEXT,approval_level_1_at INTEGER,approval_level_2_by TEXT,approval_level_2_at INTEGER,payout_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS provider_order_payouts (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,provider_id TEXT NOT NULL,amount REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',rail TEXT NOT NULL DEFAULT 'razorpayx',environment TEXT NOT NULL DEFAULT 'sandbox',status TEXT NOT NULL DEFAULT 'queued_sandbox',due_at INTEGER NOT NULL,razorpayx_contact_id TEXT,razorpayx_fund_account_id TEXT,provider_reference TEXT,idempotency_key TEXT NOT NULL UNIQUE,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS provider_commission_events (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_email TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}

export async function saveProviderCompensationProfile(db:D1Database,input:{providerId:string;engagementModel:EngagementModel;commissionMode?:CommissionMode;commissionValue?:number;razorpayxContactId?:string;razorpayxFundAccountId?:string;reason:string;actor:string}){await ensureProviderCommissionTables(db);const providerId=input.providerId.trim();if(!providerId)throw new Error("Provider ID is required");if(input.reason.trim().length<8)throw new Error("Configuration reason must be at least 8 characters");if(input.engagementModel==="commission"&&!input.commissionMode)throw new Error("Commission providers require a default commission mode");const value=input.engagementModel==="commission"?Number(input.commissionValue):0;if(input.engagementModel==="commission")commissionAmount(100000,input.commissionMode!,value);const now=Date.now();await db.prepare("INSERT INTO provider_compensation_profiles (provider_id,engagement_model,default_commission_mode,default_commission_value,razorpayx_contact_id,razorpayx_fund_account_id,status,reason,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,'active',?,?,?,?) ON CONFLICT(provider_id) DO UPDATE SET engagement_model=excluded.engagement_model,default_commission_mode=excluded.default_commission_mode,default_commission_value=excluded.default_commission_value,razorpayx_contact_id=excluded.razorpayx_contact_id,razorpayx_fund_account_id=excluded.razorpayx_fund_account_id,status='active',reason=excluded.reason,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(providerId,input.engagementModel,input.engagementModel==="commission"?input.commissionMode:null,input.engagementModel==="commission"?value:null,input.razorpayxContactId?.trim()||null,input.razorpayxFundAccountId?.trim()||null,input.reason.trim(),input.actor,now,now).run();return{providerId,engagementModel:input.engagementModel,commissionMode:input.engagementModel==="commission"?input.commissionMode:null,commissionValue:input.engagementModel==="commission"?value:null,livePayout:false};}

export async function syncCompletedCommissionOrders(db:D1Database){await ensureProviderCommissionTables(db);let candidates:Row[]=[];try{candidates=rows(await db.prepare("SELECT b.id booking_id,b.service_code,b.total_amount,b.updated_at,w.id work_order_id,w.provider_id,w.provider_model,COALESCE((SELECT MAX(e.occurred_at) FROM booking_lifecycle_events e WHERE e.booking_id=b.id AND e.event_type IN ('service_completed','booking_completed','completed')),b.updated_at) completed_at FROM canonical_bookings b JOIN provider_work_orders w ON w.booking_id=b.id WHERE b.status='completed' AND w.provider_model='commission'").all<Row>());}catch{return 0;}const now=Date.now();let inserted=0;for(const item of candidates){const bookingId=String(item.booking_id),existing=await db.prepare("SELECT id FROM provider_order_commissions WHERE booking_id=?").bind(bookingId).first<Row>();if(existing)continue;const profile=await db.prepare("SELECT * FROM provider_compensation_profiles WHERE provider_id=? AND status='active'").bind(String(item.provider_id)).first<Row>();const orderAmount=Number(item.total_amount||0),mode=profile?.engagement_model==="commission"?String(profile.default_commission_mode||"") as CommissionMode:undefined,value=Number(profile?.default_commission_value??0),configured=Boolean(mode&&(mode==="fixed"||mode==="percent"));const amount=configured?commissionAmount(orderAmount,mode!,value):0,completedAt=Number(item.completed_at||now),status=configured?"pending_confirmation":"configuration_required";await db.prepare("INSERT INTO provider_order_commissions (id,booking_id,work_order_id,provider_id,service_code,order_amount,commission_mode,commission_value,commission_amount,commission_source,status,completed_at,due_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?, 'provider_default',?,?,?,?,?,?)").bind(`COMM-${crypto.randomUUID().slice(0,12).toUpperCase()}`,bookingId,String(item.work_order_id),String(item.provider_id),String(item.service_code),orderAmount,configured?mode:null,configured?value:null,amount,status,completedAt,completedAt+FIVE_DAYS,now,now).run();inserted++;}return inserted;}

export async function overrideOrderCommission(db:D1Database,input:{bookingId:string;mode:CommissionMode;value:number;reason:string;actor:string}){await ensureProviderCommissionTables(db);await syncCompletedCommissionOrders(db);if(input.reason.trim().length<8)throw new Error("Order-level override reason must be at least 8 characters");const row=await db.prepare("SELECT * FROM provider_order_commissions WHERE booking_id=?").bind(input.bookingId).first<Row>();if(!row)throw new Error("Completed commission-based order not found");if(!["configuration_required","pending_confirmation"].includes(String(row.status)))throw new Error("Commission can only be overridden before confirmation");const amount=commissionAmount(Number(row.order_amount),input.mode,input.value),now=Date.now();await db.prepare("UPDATE provider_order_commissions SET commission_mode=?,commission_value=?,commission_amount=?,commission_source='order_override',override_reason=?,status='pending_confirmation',updated_at=? WHERE booking_id=?").bind(input.mode,input.value,amount,input.reason.trim(),now,input.bookingId).run();await event(db,input.bookingId,"order_commission_overridden",input.actor,{mode:input.mode,value:input.value,amount,reason:input.reason});return{bookingId:input.bookingId,commissionMode:input.mode,commissionValue:input.value,commissionAmount:amount,source:"order_override",status:"pending_confirmation"};}

export async function confirmOrderCommission(db:D1Database,input:{bookingId:string;actor:string}){await ensureProviderCommissionTables(db);await syncCompletedCommissionOrders(db);const row=await db.prepare("SELECT * FROM provider_order_commissions WHERE booking_id=?").bind(input.bookingId).first<Row>();if(!row)throw new Error("Completed commission-based order not found");if(String(row.status)!=="pending_confirmation")throw new Error("Configured pending commission is required");const now=Date.now();await db.prepare("UPDATE provider_order_commissions SET status='awaiting_approval_1',confirmed_by=?,confirmed_at=?,updated_at=? WHERE booking_id=?").bind(input.actor,now,now,input.bookingId).run();await event(db,input.bookingId,"commission_confirmed",input.actor,{commissionAmount:Number(row.commission_amount),dueAt:Number(row.due_at)});return{bookingId:input.bookingId,status:"awaiting_approval_1",commissionAmount:Number(row.commission_amount),dueAt:Number(row.due_at)};}

export async function approveOrderCommission(db:D1Database,input:{bookingId:string;level:1|2;actor:string;idempotencyKey?:string}){await ensureProviderCommissionTables(db);const row=await db.prepare("SELECT * FROM provider_order_commissions WHERE booking_id=?").bind(input.bookingId).first<Row>();if(!row)throw new Error("Commission order not found");const now=Date.now();if(input.level===1){if(String(row.status)!=="awaiting_approval_1")throw new Error("Commission is not awaiting level 1 approval");await db.prepare("UPDATE provider_order_commissions SET status='awaiting_approval_2',approval_level_1_by=?,approval_level_1_at=?,updated_at=? WHERE booking_id=?").bind(input.actor,now,now,input.bookingId).run();await event(db,input.bookingId,"commission_approval_level_1",input.actor,{amount:Number(row.commission_amount)});return{bookingId:input.bookingId,status:"awaiting_approval_2",approvalLevel:1};}
 if(String(row.status)!=="awaiting_approval_2")throw new Error("Commission is not awaiting level 2 approval");if(String(row.approval_level_1_by||"").toLowerCase()===input.actor.toLowerCase())throw new Error("Level 2 approval must be completed by a different approver");const profile=await db.prepare("SELECT * FROM provider_compensation_profiles WHERE provider_id=?").bind(String(row.provider_id)).first<Row>();const idempotencyKey=(input.idempotencyKey||`razorpayx-${input.bookingId}`).trim(),prior=await db.prepare("SELECT * FROM provider_order_payouts WHERE idempotency_key=?").bind(idempotencyKey).first<Row>();let payoutId=prior?String(prior.id):`RPX-${crypto.randomUUID().slice(0,12).toUpperCase()}`;if(!prior){await db.prepare("INSERT INTO provider_order_payouts (id,booking_id,provider_id,amount,currency,rail,environment,status,due_at,razorpayx_contact_id,razorpayx_fund_account_id,idempotency_key,created_by,created_at,updated_at) VALUES (?,?,?,?,?,'razorpayx','sandbox','queued_sandbox',?,?,?,?,?,?,?)").bind(payoutId,input.bookingId,String(row.provider_id),Number(row.commission_amount),"INR",Number(row.due_at),profile?.razorpayx_contact_id||null,profile?.razorpayx_fund_account_id||null,idempotencyKey,input.actor,now,now).run();}
 await db.prepare("UPDATE provider_order_commissions SET status='payout_queued_sandbox',approval_level_2_by=?,approval_level_2_at=?,payout_id=?,updated_at=? WHERE booking_id=?").bind(input.actor,now,payoutId,now,input.bookingId).run();await event(db,input.bookingId,"commission_approval_level_2",input.actor,{payoutId,rail:"razorpayx",environment:"sandbox",liveMoney:false,dueAt:Number(row.due_at),overdue:now>Number(row.due_at)});return{bookingId:input.bookingId,status:"payout_queued_sandbox",approvalLevel:2,payoutId,rail:"razorpayx",environment:"sandbox",liveMoney:false,dueAt:Number(row.due_at),overdue:now>Number(row.due_at)};}

export async function getProviderCommissionDashboard(db:D1Database){await ensureProviderCommissionTables(db);await syncCompletedCommissionOrders(db);const [profiles,orders,payouts]=await Promise.all([db.prepare("SELECT * FROM provider_compensation_profiles ORDER BY updated_at DESC").all(),db.prepare("SELECT * FROM provider_order_commissions ORDER BY completed_at DESC LIMIT 250").all(),db.prepare("SELECT * FROM provider_order_payouts ORDER BY created_at DESC LIMIT 250").all()]);return{profiles:profiles.results,orders:orders.results,payouts:payouts.results,policy:{providerModels:["full_time","commission"],commissionModes:["fixed","percent"],orderOverride:true,payoutSlaDays:5,approvalLevels:2,secondApproverMustDiffer:true,payoutRail:"razorpayx",environment:"sandbox",livePayout:false}};}
