import type{ReferralClaimInput,ReferralProgramme}from"./referral-governance";

type SaveProgramme=Omit<ReferralProgramme,"createdAt"|"updatedAt"|"testOnly"|"qualificationRule">;
async function payload(response:Response){const body=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(String(body.error||"Referral request failed"));return body.data;}
export async function loadReferralDirectory(){return payload(await fetch("/api/referral-governance",{cache:"no-store"}));}
export async function saveGovernedReferralProgramme(programme:SaveProgramme){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save_programme",programme})})) as Promise<ReferralProgramme>;}
export async function ensureGovernedReferralCode(customerId:string,programmeId="uat-referral-programme"){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"ensure_code",customerId,programmeId})})) as Promise<{code:string;codeId:string;duplicatePrevented:boolean}>;}
export async function claimGovernedReferral(input:ReferralClaimInput){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"claim",input})})) as Promise<{matched:boolean;claimId?:string;friendDiscount?:number;status?:string;fraudState?:string;reviewReason?:string;duplicatePrevented?:boolean;bookingPricingAuthoritative?:boolean;testOnly?:boolean;liveMoney?:boolean}>;}
export async function qualifyGovernedReferral(input:{claimId:string;bookingId:string;idempotencyKey:string}){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"qualify",...input})}));}
export async function reviewGovernedReferral(input:{claimId:string;decision:"clear"|"hold"|"reject";reason:string}){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"review",...input})}));}
export async function reserveGovernedReferralReward(input:{rewardId:string;bookingId:string;customerId:string;idempotencyKey:string}){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reserve_reward",...input})}));}
export async function reverseGovernedReferralReward(input:{rewardId:string;reason:string}){return payload(await fetch("/api/referral-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reverse_reward",...input})}));}
