export type RevenueMissionBasis="booked"|"collected"|"net_collected";
export type RevenueMissionStatus="draft"|"active_uat"|"closed";
export type RevenueMissionScope={type:"company"|"city"|"service";value?:string};

type Db=D1Database;
type Row=Record<string,unknown>;
const basisSet=new Set<RevenueMissionBasis>(["booked","collected","net_collected"]);
const statusSet=new Set<RevenueMissionStatus>(["draft","active_uat","closed"]);
const scopeSet=new Set(["company","city","service"]);
const text=(value:unknown)=>String(value??"").trim();
const amount=(value:unknown)=>Math.round(Number(value||0)*100)/100;
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID().slice(0,12).toUpperCase()}`;

export async function ensureRevenueMissionTables(db:Db){await db.batch([
  db.prepare("CREATE TABLE IF NOT EXISTS revenue_missions (id TEXT PRIMARY KEY,name TEXT NOT NULL,target_amount REAL NOT NULL,currency TEXT NOT NULL,period_start INTEGER NOT NULL,period_end INTEGER NOT NULL,scope_json TEXT NOT NULL,revenue_basis TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',approval_reference TEXT,config_version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL,closed_at INTEGER)"),
  db.prepare("CREATE TABLE IF NOT EXISTS revenue_mission_versions (id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,config_version INTEGER NOT NULL,snapshot_json TEXT NOT NULL,reason TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL)"),
  db.prepare("CREATE TABLE IF NOT EXISTS revenue_mission_events (id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,source_event_key TEXT NOT NULL,event_type TEXT NOT NULL,customer_id TEXT NOT NULL,booking_id TEXT NOT NULL,payment_id TEXT,refund_id TEXT,service_code TEXT NOT NULL,city_id TEXT NOT NULL,gross_amount REAL NOT NULL DEFAULT 0,refund_amount REAL NOT NULL DEFAULT 0,eligible_amount REAL NOT NULL DEFAULT 0,currency TEXT NOT NULL,source_at INTEGER NOT NULL,source_version TEXT NOT NULL,attribution_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,UNIQUE(mission_id,source_event_key))"),
  db.prepare("CREATE INDEX IF NOT EXISTS revenue_mission_events_mission_time_idx ON revenue_mission_events(mission_id,source_at)"),
  db.prepare("CREATE INDEX IF NOT EXISTS revenue_mission_events_booking_idx ON revenue_mission_events(booking_id,event_type)"),
]);}

function parseScope(value:unknown):RevenueMissionScope{let parsed:Record<string,unknown>={};if(typeof value==="string"){try{parsed=JSON.parse(value) as Record<string,unknown>}catch{}}else if(value&&typeof value==="object")parsed=value as Record<string,unknown>;const type=text(parsed.type) as RevenueMissionScope["type"],scopeValue=text(parsed.value);if(!scopeSet.has(type))throw new Error("Mission scope must be company, city or service");if(type!=="company"&&!scopeValue)throw new Error("Mission city/service scope requires an explicit value");return type==="company"?{type:"company"}:{type,value:scopeValue};}
function missionSnapshot(row:Row){return{id:text(row.id),name:text(row.name),targetAmount:amount(row.target_amount),currency:text(row.currency),periodStart:Number(row.period_start),periodEnd:Number(row.period_end),scope:parseScope(row.scope_json),revenueBasis:text(row.revenue_basis) as RevenueMissionBasis,status:text(row.status) as RevenueMissionStatus,approvalReference:row.approval_reference?text(row.approval_reference):null,configVersion:Number(row.config_version||1),createdBy:text(row.created_by),createdAt:Number(row.created_at),updatedBy:text(row.updated_by),updatedAt:Number(row.updated_at),closedAt:row.closed_at==null?null:Number(row.closed_at)};}
function validateMission(input:{name:string;targetAmount:number;currency:string;periodStart:number;periodEnd:number;scope:RevenueMissionScope;revenueBasis:RevenueMissionBasis}){if(input.name.trim().length<3)throw new Error("Mission name is required");if(!Number.isFinite(input.targetAmount)||input.targetAmount<=0)throw new Error("Mission target amount must be positive");if(!/^[A-Z]{3}$/.test(input.currency))throw new Error("Mission currency must be an explicit ISO-style 3-letter code");if(!Number.isFinite(input.periodStart)||!Number.isFinite(input.periodEnd)||input.periodStart<=0||input.periodEnd<=input.periodStart)throw new Error("Mission period start and end are required and must be valid");if(!basisSet.has(input.revenueBasis))throw new Error("Mission revenue basis must be booked, collected or net_collected");parseScope(input.scope);}
async function version(db:Db,row:Row,reason:string,actorId:string){await db.prepare("INSERT INTO revenue_mission_versions (id,mission_id,config_version,snapshot_json,reason,actor_id,created_at) VALUES (?,?,?,?,?,?,?)").bind(uid("RMV"),row.id,row.config_version,JSON.stringify(missionSnapshot(row)),reason,actorId,Date.now()).run();}

export async function saveRevenueMission(db:Db,input:{id?:string;name:string;targetAmount:number;currency:string;periodStart:number;periodEnd:number;scope:RevenueMissionScope;revenueBasis:RevenueMissionBasis;reason:string;actorId:string}){await ensureRevenueMissionTables(db);const normalized={name:input.name.trim(),targetAmount:amount(input.targetAmount),currency:input.currency.trim().toUpperCase(),periodStart:Number(input.periodStart),periodEnd:Number(input.periodEnd),scope:parseScope(input.scope),revenueBasis:input.revenueBasis};validateMission(normalized);if(input.reason.trim().length<8)throw new Error("A clear mission configuration reason is required");const now=Date.now(),missionId=input.id?.trim()||uid("MISSION");const prior=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(missionId).first<Row>();if(prior&&text(prior.status)!=="draft")throw new Error("Active or closed mission configuration is immutable; create a new versioned mission instead");const nextVersion=prior?Number(prior.config_version||1)+1:1;if(prior){await db.prepare("UPDATE revenue_missions SET name=?,target_amount=?,currency=?,period_start=?,period_end=?,scope_json=?,revenue_basis=?,config_version=?,updated_by=?,updated_at=? WHERE id=?").bind(normalized.name,normalized.targetAmount,normalized.currency,normalized.periodStart,normalized.periodEnd,JSON.stringify(normalized.scope),normalized.revenueBasis,nextVersion,input.actorId,now,missionId).run();}else{await db.prepare("INSERT INTO revenue_missions (id,name,target_amount,currency,period_start,period_end,scope_json,revenue_basis,status,approval_reference,config_version,created_by,created_at,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,'draft',NULL,1,?,?,?,?)").bind(missionId,normalized.name,normalized.targetAmount,normalized.currency,normalized.periodStart,normalized.periodEnd,JSON.stringify(normalized.scope),normalized.revenueBasis,input.actorId,now,input.actorId,now).run();}const row=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(missionId).first<Row>();if(!row)throw new Error("Mission configuration could not be saved");await version(db,row,input.reason,input.actorId);return missionSnapshot(row);}

export async function activateRevenueMission(db:Db,input:{missionId:string;approvalReference:string;actorId:string;reason:string}){await ensureRevenueMissionTables(db);const row=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(input.missionId).first<Row>();if(!row)throw new Error("Revenue mission not found");if(text(row.status)!=="draft")throw new Error("Only a draft mission can be activated");if(input.approvalReference.trim().length<4)throw new Error("Mission activation requires an approval reference");if(input.reason.trim().length<8)throw new Error("A clear activation reason is required");const snapshot=missionSnapshot(row);validateMission({name:snapshot.name,targetAmount:snapshot.targetAmount,currency:snapshot.currency,periodStart:snapshot.periodStart,periodEnd:snapshot.periodEnd,scope:snapshot.scope,revenueBasis:snapshot.revenueBasis});const now=Date.now();await db.prepare("UPDATE revenue_missions SET status='active_uat',approval_reference=?,updated_by=?,updated_at=? WHERE id=?").bind(input.approvalReference.trim(),input.actorId,now,input.missionId).run();const after=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(input.missionId).first<Row>();await version(db,after!,input.reason,input.actorId);return missionSnapshot(after!);}

export async function closeRevenueMission(db:Db,input:{missionId:string;actorId:string;reason:string}){await ensureRevenueMissionTables(db);if(input.reason.trim().length<8)throw new Error("A clear mission close reason is required");const row=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(input.missionId).first<Row>();if(!row)throw new Error("Revenue mission not found");if(text(row.status)!=="active_uat")throw new Error("Only an active UAT mission can be closed");const now=Date.now();await db.prepare("UPDATE revenue_missions SET status='closed',closed_at=?,updated_by=?,updated_at=? WHERE id=?").bind(now,input.actorId,now,input.missionId).run();const after=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(input.missionId).first<Row>();await version(db,after!,input.reason,input.actorId);return missionSnapshot(after!);}

function scopeMatches(scope:RevenueMissionScope,source:{cityId:string;serviceCode:string}){if(scope.type==="company")return true;if(scope.type==="city")return scope.value===source.cityId;return scope.value===source.serviceCode;}
async function activeMissions(db:Db,source:{currency:string;sourceAt:number;cityId:string;serviceCode:string}){const result=await db.prepare("SELECT * FROM revenue_missions WHERE status='active_uat' AND currency=? AND period_start<=? AND period_end>=? ORDER BY created_at").bind(source.currency,source.sourceAt,source.sourceAt).all<Row>();return result.results.filter(row=>scopeMatches(parseScope(row.scope_json),source));}
async function insertEvent(db:Db,input:{missionId:string;sourceEventKey:string;eventType:"booked"|"collected"|"refunded"|"reversed"|"cancelled";customerId:string;bookingId:string;paymentId?:string|null;refundId?:string|null;serviceCode:string;cityId:string;grossAmount:number;refundAmount:number;eligibleAmount:number;currency:string;sourceAt:number;sourceVersion:string;attribution?:Record<string,unknown>}){const now=Date.now();const result=await db.prepare("INSERT OR IGNORE INTO revenue_mission_events (id,mission_id,source_event_key,event_type,customer_id,booking_id,payment_id,refund_id,service_code,city_id,gross_amount,refund_amount,eligible_amount,currency,source_at,source_version,attribution_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(uid("RME"),input.missionId,input.sourceEventKey,input.eventType,input.customerId,input.bookingId,input.paymentId??null,input.refundId??null,input.serviceCode,input.cityId,amount(input.grossAmount),amount(input.refundAmount),amount(input.eligibleAmount),input.currency,input.sourceAt,input.sourceVersion,JSON.stringify(input.attribution||{}),now).run();return Number(result.meta?.changes||0)>0;}

export async function recordMissionBookingEvent(db:Db,input:{bookingId:string;customerId:string;serviceCode:string;cityId:string;totalAmount:number;currency:string;sourceAt:number;status:string;actorId:string}){await ensureRevenueMissionTables(db);const missions=await activeMissions(db,{currency:input.currency,sourceAt:input.sourceAt,cityId:input.cityId,serviceCode:input.serviceCode});let created=0;for(const mission of missions){if(await insertEvent(db,{missionId:text(mission.id),sourceEventKey:`booking:${input.bookingId}:booked`,eventType:"booked",customerId:input.customerId,bookingId:input.bookingId,serviceCode:input.serviceCode,cityId:input.cityId,grossAmount:input.totalAmount,refundAmount:0,eligibleAmount:input.totalAmount,currency:input.currency,sourceAt:input.sourceAt,sourceVersion:"canonical_booking:v1",attribution:{bookingStatus:input.status,actorId:input.actorId}}))created++;}return{created,missions:missions.length};}

export async function recordMissionCollectionDelta(db:Db,input:{bookingId:string;paymentId:string;customerId:string;serviceCode:string;cityId:string;canonicalCapturedAmount:number;currency:string;sourceAt:number;sourceReference:string;actorId:string}){await ensureRevenueMissionTables(db);const missions=await activeMissions(db,{currency:input.currency,sourceAt:input.sourceAt,cityId:input.cityId,serviceCode:input.serviceCode});let created=0;for(const mission of missions){const prior=await db.prepare("SELECT COALESCE(SUM(eligible_amount),0) total FROM revenue_mission_events WHERE mission_id=? AND payment_id=? AND event_type='collected'").bind(mission.id,input.paymentId).first<Row>();const delta=amount(Math.max(0,amount(input.canonicalCapturedAmount)-amount(prior?.total)));if(delta<=0)continue;if(await insertEvent(db,{missionId:text(mission.id),sourceEventKey:`collection:${input.paymentId}:${input.sourceReference}`,eventType:"collected",customerId:input.customerId,bookingId:input.bookingId,paymentId:input.paymentId,serviceCode:input.serviceCode,cityId:input.cityId,grossAmount:delta,refundAmount:0,eligibleAmount:delta,currency:input.currency,sourceAt:input.sourceAt,sourceVersion:"payment_reconciliation:v1",attribution:{sourceReference:input.sourceReference,actorId:input.actorId}}))created++;}return{created,missions:missions.length};}

export async function recordMissionRefundDelta(db:Db,input:{bookingId:string;paymentId:string;refundId?:string|null;customerId:string;serviceCode:string;cityId:string;canonicalRefundedAmount:number;currency:string;sourceAt:number;sourceReference:string;actorId:string}){await ensureRevenueMissionTables(db);const missions=await activeMissions(db,{currency:input.currency,sourceAt:input.sourceAt,cityId:input.cityId,serviceCode:input.serviceCode});let created=0;for(const mission of missions){const prior=await db.prepare("SELECT COALESCE(SUM(refund_amount),0) total FROM revenue_mission_events WHERE mission_id=? AND payment_id=? AND event_type='refunded'").bind(mission.id,input.paymentId).first<Row>();const delta=amount(Math.max(0,amount(input.canonicalRefundedAmount)-amount(prior?.total)));if(delta<=0)continue;if(await insertEvent(db,{missionId:text(mission.id),sourceEventKey:`refund:${input.paymentId}:${input.sourceReference}`,eventType:"refunded",customerId:input.customerId,bookingId:input.bookingId,paymentId:input.paymentId,refundId:input.refundId,serviceCode:input.serviceCode,cityId:input.cityId,grossAmount:0,refundAmount:delta,eligibleAmount:-delta,currency:input.currency,sourceAt:input.sourceAt,sourceVersion:"payment_reconciliation:v1",attribution:{sourceReference:input.sourceReference,actorId:input.actorId}}))created++;}return{created,missions:missions.length};}

export async function recordMissionCancellationEvent(db:Db,input:{bookingId:string;customerId:string;serviceCode:string;cityId:string;currency:string;sourceAt:number;sourceReference:string;actorId:string}){await ensureRevenueMissionTables(db);const missions=await activeMissions(db,{currency:input.currency,sourceAt:input.sourceAt,cityId:input.cityId,serviceCode:input.serviceCode});let created=0;for(const mission of missions){if(await insertEvent(db,{missionId:text(mission.id),sourceEventKey:`cancellation:${input.bookingId}:${input.sourceReference}`,eventType:"cancelled",customerId:input.customerId,bookingId:input.bookingId,serviceCode:input.serviceCode,cityId:input.cityId,grossAmount:0,refundAmount:0,eligibleAmount:0,currency:input.currency,sourceAt:input.sourceAt,sourceVersion:"canonical_booking:v1",attribution:{sourceReference:input.sourceReference,actorId:input.actorId}}))created++;}return{created,missions:missions.length};}

export async function backfillRevenueMissionFromCanonicalSources(db:Db,missionId:string,actorId:string){await ensureRevenueMissionTables(db);const mission=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(missionId).first<Row>();if(!mission)throw new Error("Revenue mission not found");if(!statusSet.has(text(mission.status) as RevenueMissionStatus)||text(mission.status)==="draft")throw new Error("Only active or closed mission canonical history can be rebuilt");const snapshot=missionSnapshot(mission);const scope=snapshot.scope;const bookings=await db.prepare("SELECT id,customer_id,service_code,city_id,total_amount,currency,status,created_at FROM canonical_bookings WHERE currency=? AND status NOT IN ('cancelled','draft') AND created_at>=? AND created_at<=? ORDER BY created_at,id").bind(snapshot.currency,snapshot.periodStart,snapshot.periodEnd).all<Row>();let bookingEvents=0,collectionEvents=0,refundEvents=0;for(const booking of bookings.results){const source={cityId:text(booking.city_id),serviceCode:text(booking.service_code)};if(!scopeMatches(scope,source))continue;if(await insertEvent(db,{missionId,sourceEventKey:`booking:${text(booking.id)}:booked`,eventType:"booked",customerId:text(booking.customer_id),bookingId:text(booking.id),serviceCode:source.serviceCode,cityId:source.cityId,grossAmount:amount(booking.total_amount),refundAmount:0,eligibleAmount:amount(booking.total_amount),currency:text(booking.currency),sourceAt:Number(booking.created_at),sourceVersion:"canonical_booking:v1",attribution:{rebuild:true,actorId}}))bookingEvents++;const payment=await db.prepare("SELECT p.id,p.customer_id,p.currency,r.captured_amount,r.refunded_amount,r.last_event_id,r.updated_at FROM booking_payments p LEFT JOIN payment_reconciliation_records r ON r.payment_id=p.id WHERE p.booking_id=?").bind(booking.id).first<Row>();if(!payment)continue;const captured=amount(payment.captured_amount),refunded=amount(payment.refunded_amount),paymentId=text(payment.id),eventAt=Number(payment.updated_at||booking.created_at),ref=text(payment.last_event_id)||`rebuild:${paymentId}`;if(captured>0){const result=await recordMissionCollectionDelta(db,{bookingId:text(booking.id),paymentId,customerId:text(booking.customer_id),serviceCode:source.serviceCode,cityId:source.cityId,canonicalCapturedAmount:captured,currency:text(payment.currency||booking.currency),sourceAt:eventAt,sourceReference:`rebuild:${ref}:captured`,actorId});collectionEvents+=result.created;}if(refunded>0){const result=await recordMissionRefundDelta(db,{bookingId:text(booking.id),paymentId,customerId:text(booking.customer_id),serviceCode:source.serviceCode,cityId:source.cityId,canonicalRefundedAmount:refunded,currency:text(payment.currency||booking.currency),sourceAt:eventAt,sourceReference:`rebuild:${ref}:refunded`,actorId});refundEvents+=result.created;}
  // Split-payment stays: the governed sandbox balance capture lives in stay_payment_schedules
  // (lib/stay-split-payments.ts), not in payment_reconciliation_records - without this read-side
  // join the collected truth silently missed every 50/50 balance settlement. Tracked as its own
  // synthetic payment lane so the gateway-capture delta math is untouched, and delta-idempotent on
  // rebuild like every other collection source.
  const stayTable=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='stay_payment_schedules'").first<Row>();
  if(stayTable){const stayBalance=await db.prepare("SELECT paid_now_amount,balance_amount,payment_ref,paid_at FROM stay_payment_schedules WHERE booking_id=? AND status='paid'").bind(booking.id).first<Row>();
   // Credit only the settled balance NOT already inside the gateway reconciliation record. When the
   // balance is captured through the gateway, lib/grooming-payment-reconciliation.ts settles the
   // schedule to 'paid' AND accumulates the balance into captured_amount, so crediting balance_amount
   // again here would double-count it (captured lane + this lane). A sandbox-settled balance leaves
   // captured_amount at the first instalment, so the residual is the whole balance and behaviour is
   // unchanged.
   if(stayBalance){const stayCredit=Math.min(amount(stayBalance.balance_amount),Math.max(0,amount(stayBalance.paid_now_amount)+amount(stayBalance.balance_amount)-captured));
    if(stayCredit>0){const result=await recordMissionCollectionDelta(db,{bookingId:text(booking.id),paymentId:`${paymentId}:stay-balance`,customerId:text(booking.customer_id),serviceCode:source.serviceCode,cityId:source.cityId,canonicalCapturedAmount:stayCredit,currency:text(payment.currency||booking.currency),sourceAt:Number(stayBalance.paid_at||eventAt),sourceReference:`stay-balance:${text(stayBalance.payment_ref)||text(booking.id)}`,actorId});collectionEvents+=result.created;}}}}
 return{missionId,bookingEvents,collectionEvents,refundEvents,syntheticSourcesUsed:false};}

export async function revenueMissionSummary(db:Db,missionId:string){await ensureRevenueMissionTables(db);const mission=await db.prepare("SELECT * FROM revenue_missions WHERE id=?").bind(missionId).first<Row>();if(!mission)throw new Error("Revenue mission not found");
 // A booking with a canonical cancellation event in this mission no longer counts toward 'booked':
 // otherwise a cancelled ₹1,500 booking kept crediting the target forever, and mission booked
 // disagreed with the P&L revenue view (canonical_bookings excluding cancelled/draft).
 const totals=await db.prepare("SELECT COALESCE(SUM(CASE WHEN event_type='booked' AND booking_id NOT IN (SELECT booking_id FROM revenue_mission_events WHERE mission_id=? AND event_type='cancelled') THEN eligible_amount ELSE 0 END),0) booked,COALESCE(SUM(CASE WHEN event_type='collected' THEN eligible_amount ELSE 0 END),0) collected,COALESCE(SUM(CASE WHEN event_type='refunded' THEN refund_amount ELSE 0 END),0) refunded,COUNT(*) event_count FROM revenue_mission_events WHERE mission_id=?").bind(missionId,missionId).first<Row>();const snapshot=missionSnapshot(mission),booked=amount(totals?.booked),collected=amount(totals?.collected),refunded=amount(totals?.refunded),netCollected=amount(collected-refunded),achieved=snapshot.revenueBasis==="booked"?booked:snapshot.revenueBasis==="collected"?collected:netCollected,target=snapshot.targetAmount,gap=amount(Math.max(0,target-achieved)),percent=target>0?Math.round((achieved/target)*10000)/100:0;return{mission:snapshot,metrics:{booked,collected,refunded,netCollected,achieved,target,gap,percent,eventCount:Number(totals?.event_count||0),pipeline:null,forecast:null},truth:{achievedSource:"canonical bookings + payment reconciliation only",syntheticOpportunityCredit:false,provisionalLeaderboardCredit:false,productionReady:false}};}

export async function listRevenueMissions(db:Db){await ensureRevenueMissionTables(db);const rows=await db.prepare("SELECT * FROM revenue_missions ORDER BY created_at DESC").all<Row>();const items=[];for(const row of rows.results)items.push(await revenueMissionSummary(db,text(row.id)));return{items,productionReady:false as const};}

export async function revenueMissionAudit(db:Db,missionId?:string){await ensureRevenueMissionTables(db);if(missionId){const [versions,events]=await Promise.all([db.prepare("SELECT * FROM revenue_mission_versions WHERE mission_id=? ORDER BY config_version DESC").bind(missionId).all<Row>(),db.prepare("SELECT * FROM revenue_mission_events WHERE mission_id=? ORDER BY source_at DESC,created_at DESC LIMIT 300").bind(missionId).all<Row>()]);return{versions:versions.results,events:events.results};}const versions=await db.prepare("SELECT * FROM revenue_mission_versions ORDER BY created_at DESC LIMIT 100").all<Row>();return{versions:versions.results,events:[]};}
