import{computeOrderPayout,type PayoutBreakdown}from"./provider-commercial-terms";
import{postJournal,periodOf,ACCT}from"./finance-accounts";
import{resolveBookingPlaceOfSupply,TCS_RATE_S52}from"./tcs-governance";

type Row=Record<string,unknown>;
const round2=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
const MARKETPLACE_MODELS=new Set(["commission_standard","commission_groomer"]);
const OPERATOR_STATE_CODE="29";
export type CompletionFinanceFact={bookingId:string;serviceCode:string;providerId:string;orderValue:number;providerGrossPayout:number;tcsWithheld:number;providerPayoutAccrued:number;platformFee:number;platformRevenueNetOfGst:number;taxAmount:number;gstLiability:number;tcsLiability:number;supplyType:"intra"|"inter";placeOfSupplyStateCode:string;cgstTcs:number;sgstTcs:number;igstTcs:number;payoutStatus:"accrued";taxStatus:"resolved";ledgerStatus:"balanced";journalGroup:string;commercial:PayoutBreakdown};

export async function resolveServiceCompletionFinance(db:D1Database,input:{bookingId:string;actorId:string;completedAt?:number}):Promise<CompletionFinanceFact>{
 const booking=await db.prepare("SELECT id,customer_id,city_id,service_code,provider_id,total_amount FROM canonical_bookings WHERE id=?").bind(input.bookingId).first<Row>();if(!booking)throw new Response("Canonical booking not found for completion finance",{status:404});
 const commercial=await computeOrderPayout(db,{bookingId:input.bookingId,actorId:input.actorId,persist:true}),pos=await resolveBookingPlaceOfSupply(db,input.bookingId),supplyType:"intra"|"inter"=pos.stateCode===OPERATOR_STATE_CODE?"intra":"inter",tcsBase=MARKETPLACE_MODELS.has(commercial.engagementModel)?Math.max(0,round2(commercial.orderValue-commercial.providerGstDeducted)):0,tcsTotal=round2(tcsBase*TCS_RATE_S52.total),cgstTcs=supplyType==="intra"?round2(tcsBase*TCS_RATE_S52.cgst):0,sgstTcs=supplyType==="intra"?round2(tcsBase*TCS_RATE_S52.sgst):0,igstTcs=supplyType==="inter"?round2(tcsBase*TCS_RATE_S52.igst):0,providerPayoutAccrued=round2(Math.max(0,commercial.providerNetPayout-tcsTotal)),gstLiability=round2(commercial.providerGstDeducted+commercial.platformGst+commercial.pawspaceGstOnOrder),platformRevenueNetOfGst=round2(commercial.platformFee-commercial.platformGst),completedAt=input.completedAt??Date.now(),entryDate=new Date(completedAt).toISOString().slice(0,10),periodCode=periodOf(entryDate);
 const creditTotal=round2(providerPayoutAccrued+tcsTotal+gstLiability+platformRevenueNetOfGst);if(Math.abs(creditTotal-commercial.orderValue)>0.01)throw new Response(`Completion finance is not balanced for booking ${input.bookingId}: credits ${creditTotal} != order ${commercial.orderValue}`,{status:409});
 const journal=await postJournal(db,{groupKey:`SERVICE-COMPLETION-${input.bookingId}`,entryDate,periodCode,sourceType:"service_completion",sourceId:input.bookingId,narration:`Resolved service completion accrual for ${String(booking.service_code)}`,metadata:{bookingId:input.bookingId,customerId:String(booking.customer_id),cityId:String(booking.city_id),serviceCode:String(booking.service_code),taxAmount:round2(gstLiability+tcsTotal),transactionAt:completedAt,verificationStatus:"resolved"},lines:[{accountCode:ACCT.CUSTOMER_COLLECTIONS,debit:commercial.orderValue,vertical:String(booking.service_code)},{accountCode:"2110-Provider Payable",credit:providerPayoutAccrued,vertical:String(booking.service_code)},{accountCode:"2140-TCS Payable",credit:tcsTotal,vertical:String(booking.service_code)},{accountCode:"2130-GST Payable",credit:gstLiability,vertical:String(booking.service_code)},{accountCode:ACCT.REVENUE,credit:platformRevenueNetOfGst,vertical:String(booking.service_code)}]});
 return{bookingId:input.bookingId,serviceCode:String(booking.service_code),providerId:String(booking.provider_id),orderValue:commercial.orderValue,providerGrossPayout:commercial.providerNetPayout,tcsWithheld:tcsTotal,providerPayoutAccrued,platformFee:commercial.platformFee,platformRevenueNetOfGst,taxAmount:round2(gstLiability+tcsTotal),gstLiability,tcsLiability:tcsTotal,supplyType,placeOfSupplyStateCode:pos.stateCode,cgstTcs,sgstTcs,igstTcs,payoutStatus:"accrued",taxStatus:"resolved",ledgerStatus:"balanced",journalGroup:journal.journalGroup,commercial};
}
