import{creditBreakdownAppliedToBooking}from"./booking-credit-application";
import{collectedForBooking}from"./collected-funds";

type Db=D1Database;type Row=Record<string,unknown>;
const round2=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;const num=(v:unknown)=>Number(v??0);const text=(v:unknown)=>String(v??"").trim();const TOLERANCE=0.01;
const REFUND_TABLES=["boarding_refund_ledger","sitting_refund_ledger","walking_refund_ledger","taxi_refund_ledger","grooming_refund_ledger","training_refund_ledger"] as const;
async function tableExists(db:Db,name:string){return Boolean(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first<Row>());}
async function cols(db:Db,name:string){return(await db.prepare(`PRAGMA table_info(${name})`).all<Row>()).results.map(r=>text(r.name));}
export async function refundedForBooking(db:Db,bookingId:string){let total=0;for(const table of REFUND_TABLES){if(!(await tableExists(db,table)))continue;const c=await cols(db,table);if(!c.includes("booking_id")||!c.includes("amount"))continue;let sql=`SELECT COALESCE(SUM(amount),0) amount FROM ${table} WHERE booking_id=?`;if(c.includes("status"))sql+=" AND lower(status) NOT IN ('rejected','failed','void','cancelled')";const row=await db.prepare(sql).bind(bookingId).first<Row>();total+=Math.max(0,num(row?.amount));}if(await tableExists(db,"finance_adjustment_documents")&&await tableExists(db,"finance_invoices")){const row=await db.prepare("SELECT COALESCE(SUM(a.amount+a.tax_amount),0) amount FROM finance_adjustment_documents a JOIN finance_invoices i ON i.id=a.invoice_id WHERE i.source_type='booking' AND i.source_id=? AND a.kind='credit_note' AND a.status='issued'").bind(bookingId).first<Row>().catch(()=>null);total+=Math.max(0,num(row?.amount));}return round2(total);}
export async function ensureSettlementParityTables(db:Db){await db.prepare("CREATE TABLE IF NOT EXISTS booking_settlement_reconciliations (booking_id TEXT PRIMARY KEY,customer_gross_collection REAL NOT NULL,pawspace_entitlement REAL NOT NULL,statutory_liabilities REAL NOT NULL,provider_settlement REAL NOT NULL,refunds_adjustments REAL NOT NULL,variance REAL NOT NULL,status TEXT NOT NULL,detail_json TEXT NOT NULL,actor_id TEXT NOT NULL,reconciled_at INTEGER NOT NULL)").run();}
export type SettlementParityInput={bookingId:string;actorId:string;pawspaceEntitlement:number;statutoryLiabilities:number;providerSettlement:number;refundsAdjustments?:number;customerGrossCollection?:number;detail?:Record<string,unknown>};
export async function assertBookingSettlementParity(db:Db,input:SettlementParityInput){await ensureSettlementParityTables(db);const cash=input.customerGrossCollection==null?await collectedForBooking(db,input.bookingId):round2(input.customerGrossCollection),credits=await creditBreakdownAppliedToBooking(db,input.bookingId),customerGross=round2(cash+credits.totalApplied),refunds=input.refundsAdjustments==null?await refundedForBooking(db,input.bookingId):round2(input.refundsAdjustments),pawspace=round2(input.pawspaceEntitlement),statutory=round2(input.statutoryLiabilities),provider=round2(input.providerSettlement),rhs=round2(pawspace+statutory+provider+refunds),variance=round2(customerGross-rhs),status=Math.abs(variance)<=TOLERANCE?"reconciled":"blocked",detail={...(input.detail??{}),cashCollection:cash,walletCreditApplied:credits.walletApplied,pawPointsCreditApplied:credits.pawPointsApplied,totalCreditApplied:credits.totalApplied,totalFunding:customerGross};await db.prepare("INSERT INTO booking_settlement_reconciliations (booking_id,customer_gross_collection,pawspace_entitlement,statutory_liabilities,provider_settlement,refunds_adjustments,variance,status,detail_json,actor_id,reconciled_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(booking_id) DO UPDATE SET customer_gross_collection=excluded.customer_gross_collection,pawspace_entitlement=excluded.pawspace_entitlement,statutory_liabilities=excluded.statutory_liabilities,provider_settlement=excluded.provider_settlement,refunds_adjustments=excluded.refunds_adjustments,variance=excluded.variance,status=excluded.status,detail_json=excluded.detail_json,actor_id=excluded.actor_id,reconciled_at=excluded.reconciled_at").bind(input.bookingId,customerGross,pawspace,statutory,provider,refunds,variance,status,JSON.stringify(detail),input.actorId,Date.now()).run();if(status!=="reconciled")throw new Response(`Settlement parity failed for booking ${input.bookingId}: cash ${cash} + credits ${credits.totalApplied} != entitlement ${pawspace} + statutory ${statutory} + provider ${provider} + refunds ${refunds}; variance ${variance}`,{status:409});return{bookingId:input.bookingId,customerGrossCollection:customerGross,customerCashCollection:cash,customerCreditApplied:credits.totalApplied,walletCreditApplied:credits.walletApplied,pawPointsCreditApplied:credits.pawPointsApplied,pawspaceEntitlement:pawspace,statutoryLiabilities:statutory,providerSettlement:provider,refundsAdjustments:refunds,variance,status,tolerance:TOLERANCE};}
