import{ensureSittingLifecycleTables,getSittingBooking}from"./sitting-lifecycle";
import{ensureServiceMediaTable}from"./service-media-security";

type Row=Record<string,unknown>;
export type SittingMediaPurpose="sitting_checkin"|"sitting_update"|"sitting_medication"|"sitting_incident"|"sitting_checkout";
export type SittingProofAction="prepare_media"|"sandbox_finalize_media"|"record_media_scan"|"revoke_media"|"record_update"|"record_medication"|"report_incident"|"acknowledge_incident"|"resolve_incident";
export type SittingProofInput={bookingId:string;action:SittingProofAction;actorId:string;idempotencyKey:string;purpose?:SittingMediaPurpose;mimeType?:string;sizeBytes?:number;sha256?:string;uploadToken?:string;storageObjectId?:string;mediaRef?:string;scanResult?:"clean"|"rejected";reason?:string;note?:string;medicationName?:string;dose?:string;administeredAt?:string;incidentId?:string;severity?:"attention"|"urgent"|"emergency";summary?:string;actionTaken?:string;resolution?:string};
const allowedMime=new Set(["image/jpeg","image/png","image/webp"]);
const allowedPurpose=new Set<SittingMediaPurpose>(["sitting_checkin","sitting_update","sitting_medication","sitting_incident","sitting_checkout"]);
const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value??"")) as T}catch{return fallback}};
const mediaIdFromRef=(ref:string)=>{const prefix="media://asset/";if(!ref.startsWith(prefix))throw new Response("Sitting proof must use a PawSpace media reference",{status:400});const id=ref.slice(prefix.length).trim();if(!id||id.includes("/")||id.includes("?")||id.includes("#"))throw new Response("Invalid PawSpace media asset reference",{status:400});return id;};
async function digest(value:string){const data=new TextEncoder().encode(value),hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(byte=>byte.toString(16).padStart(2,"0")).join("");}

export async function ensureSittingProofTables(db:D1Database){await ensureSittingLifecycleTables(db);await ensureServiceMediaTable(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS sitting_proof_action_keys (idempotency_key TEXT PRIMARY KEY,booking_id TEXT NOT NULL,action TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS sitting_media_upload_grants (id TEXT PRIMARY KEY,media_id TEXT NOT NULL UNIQUE,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,token_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'issued',expires_at INTEGER NOT NULL,consumed_at INTEGER,created_by TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS sitting_medication_administrations (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,medication_name TEXT NOT NULL,dose TEXT NOT NULL,administered_at TEXT NOT NULL,media_id TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',recorded_by TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_sitting_medication_booking ON sitting_medication_administrations(booking_id,administered_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS sitting_incidents (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,severity TEXT NOT NULL,summary TEXT NOT NULL,action_taken TEXT NOT NULL DEFAULT '',media_id TEXT,status TEXT NOT NULL DEFAULT 'open',ops_status TEXT NOT NULL DEFAULT 'queued',notification_status TEXT NOT NULL DEFAULT 'queued',customer_acknowledged_at INTEGER,resolution TEXT,resolved_by TEXT,resolved_at INTEGER,reported_by TEXT NOT NULL,reported_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_sitting_incident_booking ON sitting_incidents(booking_id,status,severity,reported_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS sitting_incident_events (id TEXT PRIMARY KEY,incident_id TEXT NOT NULL,booking_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS service_media_events (id TEXT PRIMARY KEY,media_id TEXT NOT NULL,booking_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}
async function booking(db:D1Database,bookingId:string){await ensureSittingProofTables(db);const row=await getSittingBooking(db,bookingId);if(!row)throw new Response("Sitting booking not found",{status:404});return row;}
async function prior(db:D1Database,key:string){const row=await db.prepare("SELECT result_json FROM sitting_proof_action_keys WHERE idempotency_key=?").bind(key).first<Row>();return row?parse<Record<string,unknown>>(row.result_json,{}):null;}
async function remember(db:D1Database,input:SittingProofInput,result:unknown){await db.prepare("INSERT INTO sitting_proof_action_keys (idempotency_key,booking_id,action,result_json,created_at) VALUES (?,?,?,?,?)").bind(input.idempotencyKey,input.bookingId,input.action,JSON.stringify(result),Date.now()).run();return result;}
async function careEvent(db:D1Database,b:Row,eventType:string,actorId:string,detail:unknown){await db.prepare("INSERT INTO sitting_care_events (id,booking_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),b.id,eventType,actorId,JSON.stringify(detail),Date.now()).run();}
async function mediaEvent(db:D1Database,mediaId:string,bookingId:string,eventType:string,actorId:string,detail:unknown){await db.prepare("INSERT INTO service_media_events (id,media_id,booking_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),mediaId,bookingId,eventType,actorId,JSON.stringify(detail),Date.now()).run();}
async function incidentEvent(db:D1Database,incidentId:string,bookingId:string,eventType:string,actorId:string,detail:unknown){await db.prepare("INSERT INTO sitting_incident_events (id,incident_id,booking_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),incidentId,bookingId,eventType,actorId,JSON.stringify(detail),Date.now()).run();}
async function queueCustomerNotice(db:D1Database,b:Row,eventId:string,templateCode:string,message:string){for(const channel of ["push","whatsapp"])await db.prepare("INSERT INTO sitting_customer_notifications (id,booking_id,customer_id,channel,template_code,message,status,event_id,created_at) VALUES (?,?,?,?,?,?,'queued',?,?)").bind(crypto.randomUUID(),b.id,b.customer_id,channel,templateCode,message,eventId,Date.now()).run();}
async function proofAsset(db:D1Database,b:Row,ref:string,purpose:SittingMediaPurpose){const id=mediaIdFromRef(ref),row=await db.prepare("SELECT id,booking_id,provider_id,purpose,mime_type,size_bytes,sha256,scan_status,access_status,retention_status,synthetic,created_at,updated_at FROM service_media_assets WHERE id=?").bind(id).first<Row>();if(!row)throw new Response("Sitting media asset does not exist",{status:409});if(String(row.booking_id)!==String(b.id))throw new Response("Sitting media asset belongs to another booking",{status:403});if(String(row.provider_id)!==String(b.provider_id))throw new Response("Sitting media asset belongs to another provider",{status:403});if(String(row.purpose)!==purpose)throw new Response("Sitting media asset purpose does not match this evidence slot",{status:409});if(String(row.scan_status)!=="clean")throw new Response("Sitting media asset has not passed scan review",{status:409});if(String(row.access_status)!=="ready")throw new Response("Sitting media asset is not ready for private proof access",{status:409});if(String(row.retention_status)!=="active")throw new Response("Sitting media asset is outside active retention",{status:409});if(Number(row.synthetic||0)!==0)throw new Response("Sitting media asset is still synthetic",{status:409});return row;}

export async function prepareSittingMedia(db:D1Database,input:SittingProofInput){const b=await booking(db,input.bookingId),purpose=input.purpose;if(!purpose||!allowedPurpose.has(purpose))throw new Response("Unsupported Sitting media purpose",{status:400});if(!allowedMime.has(String(input.mimeType)))throw new Response("Only JPEG, PNG and WebP Sitting proof images are accepted",{status:400});const size=Number(input.sizeBytes);if(!Number.isFinite(size)||size<1||size>10_000_000)throw new Response("Sitting proof image must be between 1 byte and 10 MB",{status:400});if(!/^[a-f0-9]{64}$/i.test(String(input.sha256||"")))throw new Response("A valid SHA-256 checksum is required",{status:400});const status=String(b.status);if(["sitting_checkin","sitting_update","sitting_medication","sitting_incident"].includes(purpose)&&!["assigned","in_progress"].includes(status))throw new Response("Sitting booking is not open for this proof purpose",{status:409});if(purpose==="sitting_checkout"&&status!=="in_progress")throw new Response("Checkout proof requires an in-progress Sitting booking",{status:409});const mediaId=`SMEDIA-${crypto.randomUUID().slice(0,12).toUpperCase()}`,grantId=`SGRANT-${crypto.randomUUID().slice(0,12).toUpperCase()}`,secret=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-",""),token=`${grantId}.${secret}`,tokenHash=await digest(token),now=Date.now(),expiresAt=now+15*60_000,storageKey=`sitting/pending/${String(b.id)}/${mediaId}`;await db.batch([db.prepare("INSERT INTO service_media_assets (id,booking_id,provider_id,purpose,storage_key,mime_type,size_bytes,sha256,scan_status,access_status,retention_status,synthetic,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'pending','pending_upload','active',0,?,?,?)").bind(mediaId,b.id,b.provider_id,purpose,storageKey,input.mimeType,size,input.sha256,input.actorId,now,now),db.prepare("INSERT INTO sitting_media_upload_grants (id,media_id,booking_id,provider_id,token_hash,status,expires_at,consumed_at,created_by,created_at) VALUES (?,?,?,?,?,'issued',?,NULL,?,?)").bind(grantId,mediaId,b.id,b.provider_id,tokenHash,expiresAt,input.actorId,now)]);await mediaEvent(db,mediaId,String(b.id),"sitting_upload_grant_issued",input.actorId,{purpose,mimeType:input.mimeType,sizeBytes:size,expiresAt,adapterConnected:false});return{bookingId:b.id,mediaId,mediaRef:`media://asset/${mediaId}`,purpose,scanStatus:"pending",accessStatus:"pending_upload",proofReady:false,upload:{mode:"sandbox_contract",token,expiresAt,adapterConnected:false,rawPublicUrl:false}};}

export async function mutateSittingProof(db:D1Database,input:SittingProofInput){if(!input.bookingId||!input.action||!input.actorId||!input.idempotencyKey)throw new Response("Booking, action, actor and idempotency key are required",{status:400});await ensureSittingProofTables(db);const old=await prior(db,input.idempotencyKey);if(old)return{...old,duplicatePrevented:true};if(input.action==="prepare_media")return remember(db,input,await prepareSittingMedia(db,input));const b=await booking(db,input.bookingId),now=Date.now(),status=String(b.status);
 if(input.action==="sandbox_finalize_media"){
  const token=String(input.uploadToken||"").trim(),objectId=String(input.storageObjectId||"").trim();if(!token||!objectId)throw new Response("Sandbox upload token and opaque storage object ID are required",{status:400});if(objectId.includes("://")||!/^[A-Za-z0-9._\/-]{8,256}$/.test(objectId))throw new Response("Storage confirmation must use an opaque object ID, not a public URL",{status:400});const grantId=token.split(".")[0]||"",grant=await db.prepare("SELECT * FROM sitting_media_upload_grants WHERE id=? AND booking_id=?").bind(grantId,input.bookingId).first<Row>();if(!grant||String(grant.status)!=="issued")throw new Response("Sitting media upload grant is invalid or already consumed",{status:409});if(Number(grant.expires_at)<now)throw new Response("Sitting media upload grant expired",{status:409});if(String(grant.token_hash)!==await digest(token))throw new Response("Sitting media upload token mismatch",{status:403});const media=await db.prepare("SELECT * FROM service_media_assets WHERE id=?").bind(grant.media_id).first<Row>();if(!media||String(media.booking_id)!==String(b.id)||String(media.provider_id)!==String(b.provider_id))throw new Response("Sitting media upload ownership mismatch",{status:403});if(String(media.access_status)!=="pending_upload")throw new Response("Sitting media is not awaiting upload finalization",{status:409});await db.batch([db.prepare("UPDATE sitting_media_upload_grants SET status='consumed',consumed_at=? WHERE id=? AND status='issued'").bind(now,grantId),db.prepare("UPDATE service_media_assets SET storage_key=?,access_status='quarantined',scan_status='pending',updated_at=? WHERE id=?").bind(`sitting/object/${objectId}`,now,grant.media_id)]);await mediaEvent(db,String(grant.media_id),String(b.id),"sitting_upload_finalized",input.actorId,{storageObjectId:objectId,publicUrlStored:false});return remember(db,input,{bookingId:b.id,mediaId:grant.media_id,status:"quarantined",scanStatus:"pending",proofReady:false});
 }
 if(input.action==="record_media_scan"){
  const id=mediaIdFromRef(String(input.mediaRef||"")),result=String(input.scanResult||"");if(!["clean","rejected"].includes(result))throw new Response("Sitting media scan result must be clean or rejected",{status:400});const media=await db.prepare("SELECT * FROM service_media_assets WHERE id=?").bind(id).first<Row>();if(!media||String(media.booking_id)!==String(b.id)||String(media.provider_id)!==String(b.provider_id))throw new Response("Sitting media scan ownership mismatch",{status:403});if(String(media.created_by)===input.actorId)throw new Response("Sitting proof cannot be scan-approved by the actor who submitted it",{status:403});if(String(media.access_status)!=="quarantined"||String(media.scan_status)!=="pending")throw new Response("Sitting media is not awaiting scan review",{status:409});const clean=result==="clean";await db.prepare("UPDATE service_media_assets SET scan_status=?,access_status=?,updated_at=? WHERE id=?").bind(clean?"clean":"rejected",clean?"ready":"quarantined",now,id).run();await mediaEvent(db,id,String(b.id),clean?"sitting_scan_passed":"sitting_scan_rejected",input.actorId,{reason:input.reason||null});return remember(db,input,{bookingId:b.id,mediaId:id,scanStatus:clean?"clean":"rejected",accessStatus:clean?"ready":"quarantined",proofReady:clean});
 }
 if(input.action==="revoke_media"){
  const id=mediaIdFromRef(String(input.mediaRef||"")),media=await db.prepare("SELECT * FROM service_media_assets WHERE id=?").bind(id).first<Row>();if(!media||String(media.booking_id)!==String(b.id)||String(media.provider_id)!==String(b.provider_id))throw new Response("Sitting media revoke ownership mismatch",{status:403});await db.prepare("UPDATE service_media_assets SET access_status='revoked',retention_status='revoked',updated_at=? WHERE id=?").bind(now,id).run();await mediaEvent(db,id,String(b.id),"sitting_media_revoked",input.actorId,{reason:input.reason||"Revoked by authorized operator"});return remember(db,input,{bookingId:b.id,mediaId:id,accessStatus:"revoked",retentionStatus:"revoked",proofReady:false});
 }
 if(input.action==="record_update"){
  if(status!=="in_progress")throw new Response("Sitting proof updates can be recorded only during an active booking",{status:409});const note=String(input.note||"").trim();if(note.length<3)throw new Response("A Sitting update note is required",{status:400});const media=await proofAsset(db,b,String(input.mediaRef||""),"sitting_update");await careEvent(db,b,"proof_update",input.actorId,{mediaRef:`media://asset/${media.id}`,note});return remember(db,input,{bookingId:b.id,status:"recorded",mediaRef:`media://asset/${media.id}`});
 }
 if(input.action==="record_medication"){
  if(status!=="in_progress")throw new Response("Medication evidence can be recorded only during an active Sitting booking",{status:409});const care=await db.prepare("SELECT status,plan_json FROM sitting_care_plan_snapshots WHERE booking_id=?").bind(b.id).first<Row>();if(String(care?.status)!=="ready")throw new Response("A ready Care Card is required before medication evidence",{status:409});const plan=parse<Record<string,unknown>>(care?.plan_json,{}),instruction=String(plan.medication||"").trim();if(!instruction||instruction.toLowerCase()==="none")throw new Response("The canonical Care Card has no medication instruction",{status:409});const medicationName=String(input.medicationName||"").trim(),dose=String(input.dose||"").trim(),administeredAt=String(input.administeredAt||"").trim();if(!medicationName||!dose||!administeredAt||!Number.isFinite(new Date(administeredAt).getTime()))throw new Response("Medication name, dose and administered time are required",{status:400});const media=await proofAsset(db,b,String(input.mediaRef||""),"sitting_medication"),id=crypto.randomUUID();await db.prepare("INSERT INTO sitting_medication_administrations (id,booking_id,provider_id,medication_name,dose,administered_at,media_id,note,recorded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,b.id,b.provider_id,medicationName,dose,administeredAt,media.id,String(input.note||""),input.actorId,now).run();await careEvent(db,b,"medication_evidenced",input.actorId,{administrationId:id,mediaRef:`media://asset/${media.id}`,medicationName,dose,careCardInstructionPresent:true});return remember(db,input,{bookingId:b.id,status:"medication_evidenced",administrationId:id,mediaRef:`media://asset/${media.id}`,careCardInstructionPresent:true});
 }
 if(input.action==="report_incident"){
  if(status!=="in_progress")throw new Response("Sitting incidents can be reported only during an active booking",{status:409});const severity=String(input.severity||"") as "attention"|"urgent"|"emergency",summary=String(input.summary||"").trim(),actionTaken=String(input.actionTaken||"").trim();if(!["attention","urgent","emergency"].includes(severity)||summary.length<5)throw new Response("Incident severity and summary are required",{status:400});let mediaId:string|null=null;if(String(input.mediaRef||"").trim())mediaId=String((await proofAsset(db,b,String(input.mediaRef),"sitting_incident")).id);const id=crypto.randomUUID();await db.prepare("INSERT INTO sitting_incidents (id,booking_id,provider_id,severity,summary,action_taken,media_id,status,ops_status,notification_status,reported_by,reported_at,updated_at) VALUES (?,?,?,?,?,?,?,'open','queued','queued',?,?,?)").bind(id,b.id,b.provider_id,severity,summary,actionTaken,mediaId,input.actorId,now,now).run();await incidentEvent(db,id,String(b.id),"reported",input.actorId,{severity,summary,actionTaken,mediaRef:mediaId?`media://asset/${mediaId}`:null,bookingPreserved:true,automaticRefund:false,automaticPayoutChange:false});await careEvent(db,b,"incident_reported",input.actorId,{incidentId:id,severity,ops_escalation:true});await queueCustomerNotice(db,b,id,"sitting_incident",`A PawSpace Sitting incident was reported (${severity}). Operations review is queued; the booking and money state are unchanged.`);return remember(db,input,{bookingId:b.id,incidentId:id,status:"ops_escalation",severity,bookingPreserved:true,automaticRefund:false,automaticPayoutChange:false,communications:{mode:"queued_only",liveDelivery:false}});
 }
 if(input.action==="acknowledge_incident"){
  const incidentId=String(input.incidentId||"").trim(),incident=await db.prepare("SELECT * FROM sitting_incidents WHERE id=? AND booking_id=?").bind(incidentId,b.id).first<Row>();if(!incident)throw new Response("Sitting incident not found",{status:404});if(String(incident.reported_by)===input.actorId)throw new Response("A Sitting incident cannot be acknowledged by the actor who reported it",{status:403});if(incident.customer_acknowledged_at)return remember(db,input,{bookingId:b.id,incidentId,status:String(incident.status),duplicateAcknowledgement:true,automaticRefund:false,automaticPayoutChange:false});await db.prepare("UPDATE sitting_incidents SET customer_acknowledged_at=?,updated_at=? WHERE id=?").bind(now,now,incidentId).run();await incidentEvent(db,incidentId,String(b.id),"customer_acknowledged",input.actorId,{automaticRefund:false,automaticPayoutChange:false});return remember(db,input,{bookingId:b.id,incidentId,status:String(incident.status),customerAcknowledged:true,automaticRefund:false,automaticPayoutChange:false});
 }
 if(input.action==="resolve_incident"){
  const incidentId=String(input.incidentId||"").trim(),resolution=String(input.resolution||"").trim();if(resolution.length<5)throw new Response("Incident resolution is required",{status:400});const incident=await db.prepare("SELECT * FROM sitting_incidents WHERE id=? AND booking_id=?").bind(incidentId,b.id).first<Row>();if(!incident)throw new Response("Sitting incident not found",{status:404});if(String(incident.reported_by)===input.actorId)throw new Response("A Sitting incident cannot be resolved by the actor who reported it",{status:403});if(String(incident.status)==="resolved")return remember(db,input,{bookingId:b.id,incidentId,status:"resolved",duplicateResolution:true});await db.prepare("UPDATE sitting_incidents SET status='resolved',ops_status='resolved',resolution=?,resolved_by=?,resolved_at=?,updated_at=? WHERE id=?").bind(resolution,input.actorId,now,now,incidentId).run();await incidentEvent(db,incidentId,String(b.id),"resolved",input.actorId,{resolution,automaticRefund:false,automaticPayoutChange:false});return remember(db,input,{bookingId:b.id,incidentId,status:"resolved",automaticRefund:false,automaticPayoutChange:false});
 }
 throw new Response("Unsupported Sitting proof action",{status:400});
}

export async function getSittingProofSnapshot(db:D1Database,bookingId:string){const b=await booking(db,bookingId);const[media,medications,incidents]=await Promise.all([db.prepare("SELECT id,purpose,mime_type,size_bytes,sha256,scan_status,access_status,retention_status,synthetic,created_at,updated_at FROM service_media_assets WHERE booking_id=? AND provider_id=? AND purpose LIKE 'sitting_%' ORDER BY created_at DESC").bind(b.id,b.provider_id).all<Row>(),db.prepare("SELECT * FROM sitting_medication_administrations WHERE booking_id=? ORDER BY administered_at DESC").bind(b.id).all<Row>(),db.prepare("SELECT * FROM sitting_incidents WHERE booking_id=? ORDER BY reported_at DESC").bind(b.id).all<Row>()]);return{bookingId:b.id,providerId:b.provider_id,customerId:b.customer_id,status:b.status,media:media.results.map(row=>({...row,mediaRef:`media://asset/${row.id}`})),medications:medications.results,incidents:incidents.results,communications:{mode:"queued_only",liveDelivery:false,detail:"Push and WhatsApp remain queued because live messaging is not connected in UAT."},sandboxOnly:true};}
