import{registerServicePolicyDomain,resolveServicePolicy,seedServicePolicyScope}from"./service-policy-governance";
type Db=D1Database;
export type SpecialServiceFinancePolicy={taxEnabled:boolean;taxRatePercent:number;taxMode:"inclusive";settlementDelayDays:number};
const defaults:SpecialServiceFinancePolicy&Record<string,unknown>={taxEnabled:false,taxRatePercent:0,taxMode:"inclusive",settlementDelayDays:0};
export const RELOCATION_FINANCE_POLICY_DOMAIN="relocation_commercial_finance";
export const FUNERAL_FINANCE_POLICY_DOMAIN="funeral_commercial_finance";
function domain(domain:string,label:string){return registerServicePolicyDomain<SpecialServiceFinancePolicy&Record<string,unknown>>({domain,label,managePermission:"settings.manage",defaults,problem(config){if(typeof config.taxEnabled!=="boolean")return`${label}: taxEnabled must be true or false`;const rate=Number(config.taxRatePercent);if(!Number.isFinite(rate)||rate<0||rate>100)return`${label}: tax rate must be between 0 and 100 percent`;if(config.taxEnabled&&rate<=0)return`${label}: enabled tax requires a positive rate`;if(config.taxMode!=="inclusive")return`${label}: customer prices are gross and tax mode must be inclusive`;const delay=Number(config.settlementDelayDays);if(!Number.isInteger(delay)||delay<0||delay>90)return`${label}: settlement delay must be a whole number from 0 to 90 days`;return null;}})}
export const relocationFinancePolicyDomain=domain(RELOCATION_FINANCE_POLICY_DOMAIN,"Relocation tax and vendor settlement");
export const funeralFinancePolicyDomain=domain(FUNERAL_FINANCE_POLICY_DOMAIN,"Funeral tax and vendor settlement");
export async function seedSpecialServiceFinancePolicies(db:Db){await seedServicePolicyScope(db,RELOCATION_FINANCE_POLICY_DOMAIN,"relocation","*",defaults,"Strict default: tax disabled until Finance/CA publishes a rate; vendor settlement uses quoted vendor cost");await seedServicePolicyScope(db,FUNERAL_FINANCE_POLICY_DOMAIN,"funeral_memorial","*",defaults,"Strict default: tax disabled until Finance/CA publishes a rate; vendor settlement requires explicit configured commercial terms");}
export async function resolveRelocationFinancePolicy(db:Db,cityId="blr"){await seedSpecialServiceFinancePolicies(db);return resolveServicePolicy<SpecialServiceFinancePolicy&Record<string,unknown>>(db,RELOCATION_FINANCE_POLICY_DOMAIN,{serviceCode:"relocation",cityId});}
export async function resolveFuneralFinancePolicy(db:Db,cityId="blr"){await seedSpecialServiceFinancePolicies(db);return resolveServicePolicy<SpecialServiceFinancePolicy&Record<string,unknown>>(db,FUNERAL_FINANCE_POLICY_DOMAIN,{serviceCode:"funeral_memorial",cityId});}
export function taxFromGrossMargin(grossMargin:number,policy:SpecialServiceFinancePolicy){const gross=Math.max(0,Number(grossMargin||0));if(!policy.taxEnabled)return{taxStatus:"disabled_by_policy" as const,taxAmount:0,revenueNet:gross};const rate=Number(policy.taxRatePercent);const tax=Number((gross*rate/(100+rate)).toFixed(2));return{taxStatus:"resolved" as const,taxAmount:tax,revenueNet:Number((gross-tax).toFixed(2))};}
