import{ensureLeadSlaTables,runLeadSlaGovernance}from"./lead-sla-governance";
import{ensureUnifiedCaseTables,runUnifiedCaseEscalations,syncNativeCases}from"./unified-case-center";
import{enqueueCommunication}from"./communication-engine";

type Db=D1Database;
type Row=Record<string,unknown>;
export type StaffAlertStatus="open"|"acknowledged"|"resolved";
const text=(value:unknown)=>String(value??"").trim();
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID().slice(0,12).toUpperCase()}`;

export async function ensureStaffAlertTables(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS staff_alerts (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,alert_type TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',source_type TEXT NOT NULL,source_id TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,team_code TEXT,recipient_role TEXT,recipient_email TEXT,customer_id TEXT,booking_id TEXT,lead_id TEXT,case_id TEXT,due_at INTEGER NOT NULL,acknowledged_at INTEGER,acknowledged_by TEXT,resolved_at INTEGER,resolved_by TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS staff_alerts_queue_idx ON staff_alerts(status,severity,due_at,team_code,recipient_role,recipient_email)"),
 db.prepare("CREATE TABLE IF NOT EXISTS staff_alert_events (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,alert_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}

async function emit(db:Db,input:{key:string;alertType:string;severity:"medium"|"high"|"critical";sourceType:string;sourceId:string;title:string;body:string;teamCode?:string|null;recipientRole?:string|null;recipientEmail?:string|null;customerId?:string|null;bookingId?:string|null;leadId?:string|null;caseId?:string|null;dueAt:number;actorId:string}){await ensureStaffAlertTables(db);const prior=await db.prepare("SELECT id,status FROM staff_alerts WHERE idempotency_key=?").bind(input.key).first<Row>();if(prior)return{duplicatePrevented:true,alertId:text(prior.id),status:text(prior.status)};const now=Date.now(),id=uid("ALERT");await db.batch([
 db.prepare("INSERT INTO staff_alerts (id,idempotency_key,alert_type,severity,status,source_type,source_id,title,body,team_code,recipient_role,recipient_email,customer_id,booking_id,lead_id,case_id,due_at,created_at,updated_at) VALUES (?,?,?,?,'open',?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.key,input.alertType,input.severity,input.sourceType,input.sourceId,input.title,input.body,input.teamCode??null,input.recipientRole??null,input.recipientEmail??null,input.customerId??null,input.bookingId??null,input.leadId??null,input.caseId??null,input.dueAt,now,now),
 db.prepare("INSERT INTO staff_alert_events (id,idempotency_key,alert_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,'{}',?)").bind(uid("ALE"),`${input.key}:created`,id,"created",input.actorId,now),
]);return{duplicatePrevented:false,alertId:id,status:"open"};}

async function tableExists(db:Db,name:string){const row=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first<Row>();return Boolean(row);}

async function leadAlerts(db:Db,asOf:number,actorId:string){if(!(await tableExists(db,"lead_sla_clocks"))||!(await tableExists(db,"lead_assignments")))return{created:0,skipped:true};const rows=await db.prepare("SELECT c.id clock_id,c.lead_id,c.clock_type,c.status,c.due_at,c.manager_escalation_due_at,c.reassignment_due_at,a.employee_email,a.team_code,l.customer_id FROM lead_sla_clocks c JOIN lead_assignments a ON a.id=c.assignment_id LEFT JOIN lead_work_items l ON l.id=c.lead_id WHERE c.status IN ('running','breached') AND (c.due_at<=? OR c.manager_escalation_due_at<=? OR c.reassignment_due_at<=?) ORDER BY c.due_at").bind(asOf,asOf,asOf).all<Row>();let created=0;for(const row of rows.results){const clockId=text(row.clock_id),leadId=text(row.lead_id),clockType=text(row.clock_type),owner=text(row.employee_email),team=text(row.team_code)||"sales",customerId=text(row.customer_id)||null;
  if(Number(row.due_at)<=asOf){const r=await emit(db,{key:`lead:${clockId}:sla_due`,alertType:"lead_sla_breach",severity:"medium",sourceType:"lead_sla_clock",sourceId:clockId,title:`Lead SLA overdue · ${leadId}`,body:`${clockType.replaceAll("_"," ")} is overdue for ${leadId}. Owner action is required.`,teamCode:team,recipientRole:"owner",recipientEmail:owner,customerId,leadId,dueAt:Number(row.due_at),actorId});if(!r.duplicatePrevented)created++;}
  if(Number(row.manager_escalation_due_at)<=asOf){const r=await emit(db,{key:`lead:${clockId}:manager`,alertType:"lead_manager_escalation",severity:"high",sourceType:"lead_sla_clock",sourceId:clockId,title:`Manager escalation · ${leadId}`,body:`${clockType.replaceAll("_"," ")} exceeded the configured manager-escalation threshold. Review the owner, next action and customer risk.`,teamCode:team,recipientRole:"manager",customerId,leadId,dueAt:Number(row.manager_escalation_due_at),actorId});if(!r.duplicatePrevented)created++;}
  if(Number(row.reassignment_due_at)<=asOf){const r=await emit(db,{key:`lead:${clockId}:reassignment`,alertType:"lead_reassignment_due",severity:"critical",sourceType:"lead_sla_clock",sourceId:clockId,title:`Lead reassignment due · ${leadId}`,body:`${leadId} exceeded the configured reassignment threshold. This lead is automatically reassigned to the next eligible agent; this alert is for manager visibility, not action.`,teamCode:team,recipientRole:"manager",customerId,leadId,dueAt:Number(row.reassignment_due_at),actorId});if(!r.duplicatePrevented)created++;}}
 return{created,scanned:rows.results.length,skipped:false};}

async function caseAlerts(db:Db,asOf:number,actorId:string){if(!(await tableExists(db,"unified_cases")))return{created:0,skipped:true};const rows=await db.prepare("SELECT id,case_type,severity,status,title,owner_team,owner_email,customer_id,booking_id,lead_id,first_response_due_at,manager_escalation_due_at,resolution_due_at,first_responded_at FROM unified_cases WHERE status NOT IN ('resolved','closed') AND (first_response_due_at<=? OR manager_escalation_due_at<=? OR resolution_due_at<=?) ORDER BY created_at").bind(asOf,asOf,asOf).all<Row>();let created=0;for(const row of rows.results){const caseId=text(row.id),team=text(row.owner_team)||"operations",owner=text(row.owner_email)||null,base={sourceType:"unified_case",sourceId:caseId,teamCode:team,customerId:text(row.customer_id)||null,bookingId:text(row.booking_id)||null,leadId:text(row.lead_id)||null,caseId,actorId};
  if(!row.first_responded_at&&row.first_response_due_at!=null&&Number(row.first_response_due_at)<=asOf){const r=await emit(db,{...base,key:`case:${caseId}:first_response`,alertType:"case_first_response_overdue",severity:"high",title:`Case response overdue · ${caseId}`,body:`${text(row.title)} has crossed its configured first-response SLA.`,recipientRole:owner?"owner":"manager",recipientEmail:owner,dueAt:Number(row.first_response_due_at)});if(!r.duplicatePrevented)created++;}
  if(row.manager_escalation_due_at!=null&&Number(row.manager_escalation_due_at)<=asOf){const r=await emit(db,{...base,key:`case:${caseId}:manager`,alertType:"case_manager_escalation",severity:text(row.severity)==="critical"?"critical":"high",title:`Manager case escalation · ${caseId}`,body:`${text(row.title)} crossed its configured manager-escalation threshold.`,recipientRole:"manager",dueAt:Number(row.manager_escalation_due_at)});if(!r.duplicatePrevented)created++;}
  if(row.resolution_due_at!=null&&Number(row.resolution_due_at)<=asOf){const r=await emit(db,{...base,key:`case:${caseId}:resolution`,alertType:"case_resolution_overdue",severity:"critical",title:`Case resolution overdue · ${caseId}`,body:`${text(row.title)} crossed its configured resolution SLA.`,recipientRole:"manager",dueAt:Number(row.resolution_due_at)});if(!r.duplicatePrevented)created++;}}
 return{created,scanned:rows.results.length,skipped:false};}

async function caseCustomerNotifications(db:Db,asOf:number,actorId:string){const empty={attempted:0,enqueued:0,suppressed:0,duplicatePrevented:0,skipped:0,errors:[] as string[],transport:"canonical_chat_outbox",externalDelivery:false};try{if(!(await tableExists(db,"unified_cases"))||!(await tableExists(db,"canonical_customers")))return{...empty,unavailable:true};const rows=await db.prepare("SELECT c.id,c.title,c.status,c.customer_id,c.booking_id,c.owner_email,c.first_response_due_at,c.resolution_due_at,c.first_responded_at,cc.city_id FROM unified_cases c JOIN canonical_customers cc ON cc.id=c.customer_id WHERE c.status NOT IN ('resolved','closed') AND c.customer_id IS NOT NULL AND c.booking_id IS NOT NULL AND ((c.first_responded_at IS NULL AND c.first_response_due_at IS NOT NULL AND c.first_response_due_at<=?) OR (c.resolution_due_at IS NOT NULL AND c.resolution_due_at<=?)) ORDER BY c.created_at").bind(asOf,asOf).all<Row>();let attempted=0,enqueued=0,suppressed=0,duplicatePrevented=0,skipped=0;const errors:string[]=[];for(const row of rows.results){const caseId=text(row.id),customerId=text(row.customer_id),bookingId=text(row.booking_id),cityId=text(row.city_id),owner=text(row.owner_email)||undefined;if(!caseId||!customerId||!bookingId||!cityId){skipped++;continue;}const events:Array<{kind:"first_response"|"resolution";templateKey:string;dueAt:number;notice:string}>=[];if(!row.first_responded_at&&row.first_response_due_at!=null&&Number(row.first_response_due_at)<=asOf)events.push({kind:"first_response",templateKey:"case_first_response_overdue",dueAt:Number(row.first_response_due_at),notice:"Your PawSpace support case has crossed its first-response target and is being escalated for staff attention."});if(row.resolution_due_at!=null&&Number(row.resolution_due_at)<=asOf)events.push({kind:"resolution",templateKey:"case_resolution_overdue",dueAt:Number(row.resolution_due_at),notice:"Your PawSpace support case has crossed its resolution target and remains escalated for staff attention."});for(const item of events){attempted++;try{const result=await enqueueCommunication(db,{customerId,cityId,channel:"chat",purpose:"service_recovery",idempotencyKey:`case:${caseId}:customer:${item.kind}`,templateKey:item.templateKey,payload:{caseId,title:text(row.title),status:text(row.status),escalationType:item.kind,dueAt:item.dueAt,notice:item.notice},createdBy:actorId,bookingId,assignedTo:owner});if(result.duplicatePrevented)duplicatePrevented++;else if(result.status==="suppressed")suppressed++;else enqueued++;}catch(error){errors.push(`case:${caseId}:${item.kind}:${error instanceof Error?error.message:String(error)}`);}}}return{attempted,enqueued,suppressed,duplicatePrevented,skipped,errors,transport:"canonical_chat_outbox",externalDelivery:false,unavailable:false};}catch(error){return{...empty,errors:[error instanceof Error?error.message:String(error)],unavailable:true};}}

export async function runStaffAlertSweep(db:Db,input:{actorId:string;asOf?:number}){const asOf=input.asOf??Date.now();await ensureStaffAlertTables(db);const warnings:string[]=[];try{await ensureLeadSlaTables(db);await runLeadSlaGovernance(db,{actorId:input.actorId,asOf});}catch(error){warnings.push(`lead_sla:${error instanceof Error?error.message:String(error)}`);}try{await ensureUnifiedCaseTables(db);await syncNativeCases(db,input.actorId);await runUnifiedCaseEscalations(db,{actorId:input.actorId,asOf});}catch(error){warnings.push(`case_sync:${error instanceof Error?error.message:String(error)}`);}const leads=await leadAlerts(db,asOf,input.actorId),cases=await caseAlerts(db,asOf,input.actorId),customerNotifications=await caseCustomerNotifications(db,asOf,input.actorId);if(customerNotifications.errors.length)warnings.push(...customerNotifications.errors.map(error=>`customer_notification:${error}`));return{asOf,created:leads.created+cases.created,leads,cases,customerNotifications,warnings,automaticMode:"governed_runner_available",runnerBoundary:"/api/staff-alert-runner",backgroundSchedulerConfigured:false,customerNotificationTransport:"canonical_chat_outbox",externalDelivery:false,productionReady:false};}

export async function staffAlertDirectory(db:Db){await ensureStaffAlertTables(db);const now=Date.now(),alerts=await db.prepare("SELECT * FROM staff_alerts ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,due_at ASC LIMIT 250").all<Row>(),summary=await db.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='open' THEN 1 ELSE 0 END) open,SUM(CASE WHEN status='acknowledged' THEN 1 ELSE 0 END) acknowledged,SUM(CASE WHEN status='open' AND severity='critical' THEN 1 ELSE 0 END) critical,SUM(CASE WHEN status='open' AND due_at<=? THEN 1 ELSE 0 END) overdue FROM staff_alerts").bind(now).first<Row>();return{summary,alerts:alerts.results,truth:{thresholds:"source_policy_derived",hardcodedTwentyMinuteRule:false,automaticMode:"governed_runner_available",runnerBoundary:"/api/staff-alert-runner",backgroundSchedulerConfigured:false,customerNotificationTransport:"canonical_chat_outbox",externalDelivery:false,productionReady:false}};}

export async function updateStaffAlert(db:Db,input:{alertId:string;action:"acknowledge"|"resolve";actorId:string}){await ensureStaffAlertTables(db);const row=await db.prepare("SELECT * FROM staff_alerts WHERE id=?").bind(input.alertId).first<Row>();if(!row)throw new Error("Staff alert not found");const now=Date.now(),eventKey=`alert:${input.alertId}:${input.action}`;if(input.action==="acknowledge"){if(text(row.status)==="resolved")throw new Error("Resolved alert cannot be acknowledged");await db.prepare("UPDATE staff_alerts SET status='acknowledged',acknowledged_at=COALESCE(acknowledged_at,?),acknowledged_by=COALESCE(acknowledged_by,?),updated_at=? WHERE id=?").bind(now,input.actorId,now,input.alertId).run();}else await db.prepare("UPDATE staff_alerts SET status='resolved',resolved_at=?,resolved_by=?,updated_at=? WHERE id=?").bind(now,input.actorId,now,input.alertId).run();await db.prepare("INSERT OR IGNORE INTO staff_alert_events (id,idempotency_key,alert_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?,?,'{}',?)").bind(uid("ALE"),eventKey,input.alertId,input.action,input.actorId,now).run();return{alertId:input.alertId,status:input.action==="resolve"?"resolved":"acknowledged"};}
