import{addCalendarMonthsClamped}from"./subscription-calendar";
type Db=D1Database;type Row=Record<string,unknown>;const t=(v:unknown)=>String(v??"").trim(),n=(v:unknown)=>Number(v??0),uid=(p:string)=>`${p}-${crypto.randomUUID().slice(0,16).toUpperCase()}`;const parse=<T>(v:unknown,f:T):T=>{try{return JSON.parse(String(v??"")) as T}catch{return f}};

export async function ensureSubscriptionEntitlementRenewalTables(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS subscription_entitlement_grants (cycle_id TEXT PRIMARY KEY,contract_id TEXT NOT NULL,entitlement_subscription_id TEXT NOT NULL,credits_granted INTEGER NOT NULL,amount_paise INTEGER NOT NULL,total_before INTEGER NOT NULL,period_end INTEGER,refund_reserved_credits INTEGER NOT NULL DEFAULT 0,refunded_credits INTEGER NOT NULL DEFAULT 0,refunded_paise INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'applied',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_subscription_entitlement_grants_subscription ON subscription_entitlement_grants(entitlement_subscription_id,created_at,cycle_id)"),
 db.prepare("CREATE TABLE IF NOT EXISTS subscription_refund_entitlement_allocations (id TEXT PRIMARY KEY,allocation_key TEXT NOT NULL UNIQUE,cycle_id TEXT NOT NULL,refund_case_id TEXT UNIQUE,gateway_refund_id TEXT UNIQUE,amount_paise INTEGER NOT NULL,credits INTEGER NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'reserved',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS subscription_wallet_events (id TEXT PRIMARY KEY,subscription_id TEXT NOT NULL,booking_id TEXT,event_type TEXT NOT NULL,credits INTEGER NOT NULL DEFAULT 0,balance_after INTEGER NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
]);}

export async function assertSubscriptionEntitlementBinding(db:Db,input:{planCode:string;customerId:string;sourceBookingId:string;entitlementSubscriptionId?:string}){await ensureSubscriptionEntitlementRenewalTables(db);const plan=await db.prepare("SELECT service_code,status FROM subscription_billing_plans WHERE plan_code=?").bind(input.planCode).first<Row>();if(!plan||t(plan.status)!=="active")return;const service=t(plan.service_code);if(service!=="grooming")throw new Error(`subscription_entitlement_adapter_not_configured:${service||"unknown"}`);const entitlementId=t(input.entitlementSubscriptionId);if(!entitlementId)throw new Error("subscription_entitlement_binding_required");const entitlement=await db.prepare("SELECT id,status FROM customer_grooming_subscriptions WHERE id=? AND customer_id=? AND source_booking_id=?").bind(entitlementId,input.customerId,input.sourceBookingId).first<Row>();if(!entitlement)throw new Error("subscription_entitlement_binding_mismatch");if(["payment_failed","cancelled"].includes(t(entitlement.status)))throw new Error("subscription_entitlement_not_renewable");}

function renewalExpiry(current:number,periodEnd:number,cfg:{validityValue?:unknown;validityUnit?:unknown}){if(periodEnd>0)return Math.max(current,periodEnd);const value=Math.max(1,Math.floor(n(cfg.validityValue)||1)),base=Math.max(current,Date.now());return t(cfg.validityUnit)==="days"?base+value*86_400_000:addCalendarMonthsClamped(base,value);}
export async function grantSubscriptionRenewalEntitlement(db:Db,input:{eventId:string}){await ensureSubscriptionEntitlementRenewalTables(db);const row=await db.prepare("SELECT cy.id cycle_id,cy.contract_id,cy.amount_paise,cy.period_end,c.customer_id,c.source_booking_id,c.entitlement_subscription_id,p.service_code FROM subscription_billing_cycles cy JOIN subscription_billing_contracts c ON c.id=cy.contract_id JOIN subscription_billing_plans p ON p.plan_code=c.plan_code WHERE cy.provider_event_id=?").bind(input.eventId).first<Row>();if(!row)return{handled:false};if(t(row.service_code)!=="grooming")throw new Error(`subscription_entitlement_adapter_not_configured:${t(row.service_code)||"unknown"}`);const entitlementId=t(row.entitlement_subscription_id);if(!entitlementId)throw new Error("subscription_entitlement_binding_required");const cycleId=t(row.cycle_id),prior=await db.prepare("SELECT * FROM subscription_entitlement_grants WHERE cycle_id=?").bind(cycleId).first<Row>();if(prior){if(t(prior.status)!=="applied")throw new Error("subscription_entitlement_grant_incomplete");return{handled:true,duplicate:true,cycleId,credits:n(prior.credits_granted)}}const entitlement=await db.prepare("SELECT s.*,x.config_json FROM customer_grooming_subscriptions s JOIN grooming_subscription_purchase_snapshots x ON x.subscription_id=s.id WHERE s.id=? AND s.customer_id=? AND s.source_booking_id=?").bind(entitlementId,t(row.customer_id),t(row.source_booking_id)).first<Row>();if(!entitlement)throw new Error("subscription_entitlement_binding_mismatch");if(["payment_failed","cancelled"].includes(t(entitlement.status)))throw new Error("subscription_entitlement_not_renewable");const cfg=parse<{sessions?:unknown;validityValue?:unknown;validityUnit?:unknown}>(entitlement.config_json,{}),credits=Math.floor(n(cfg.sessions));if(!Number.isSafeInteger(credits)||credits<=0)throw new Error("subscription_renewal_credit_configuration_invalid");const ts=Date.now(),expiresAt=renewalExpiry(n(entitlement.expires_at),n(row.period_end),cfg),eventKey=`subscription-renewal:${cycleId}`,detail=JSON.stringify({cycleId,providerEventId:input.eventId,amountPaise:n(row.amount_paise),expiresAt});const results=await db.batch([
 db.prepare("INSERT INTO subscription_entitlement_grants (cycle_id,contract_id,entitlement_subscription_id,credits_granted,amount_paise,total_before,period_end,status,created_at,updated_at) SELECT ?,?,?,?,?,total_sessions,?,'claiming',?,? FROM customer_grooming_subscriptions WHERE id=? AND status NOT IN ('payment_failed','cancelled') AND NOT EXISTS (SELECT 1 FROM subscription_entitlement_grants WHERE cycle_id=?)").bind(cycleId,t(row.contract_id),entitlementId,credits,n(row.amount_paise),n(row.period_end)||null,ts,ts,entitlementId,cycleId),
 db.prepare("UPDATE customer_grooming_subscriptions SET total_sessions=total_sessions+?,expires_at=MAX(expires_at,?),status=CASE WHEN status IN ('expired','exhausted') THEN 'active' ELSE status END,updated_at=? WHERE id=? AND EXISTS (SELECT 1 FROM subscription_entitlement_grants WHERE cycle_id=? AND status='claiming')").bind(credits,expiresAt,ts,entitlementId,cycleId),
 db.prepare("INSERT INTO subscription_wallet_events (id,subscription_id,booking_id,event_type,credits,balance_after,idempotency_key,actor_id,detail_json,created_at) SELECT ?,id,NULL,'renewal_granted',?,MAX(0,total_sessions-sessions_reserved-sessions_consumed),?,'system:subscription-billing',?,? FROM customer_grooming_subscriptions WHERE id=? AND EXISTS (SELECT 1 FROM subscription_entitlement_grants WHERE cycle_id=? AND status='claiming')").bind(uid("SWE"),credits,eventKey,detail,ts,entitlementId,cycleId),
 db.prepare("UPDATE subscription_entitlement_grants SET status='applied',updated_at=? WHERE cycle_id=? AND status='claiming'").bind(ts,cycleId),
]);if(results.some(r=>Number(r.meta?.changes||0)!==1))throw new Error("subscription_entitlement_grant_incomplete");return{handled:true,duplicate:false,cycleId,credits,expiresAt};}

export async function repairSubscriptionRenewalEntitlements(db:Db,input:{limit?:number}={}){await ensureSubscriptionEntitlementRenewalTables(db);const limit=Math.min(100,Math.max(1,Math.floor(input.limit??25))),rows=await db.prepare("SELECT cy.provider_event_id FROM subscription_billing_cycles cy JOIN subscription_billing_contracts c ON c.id=cy.contract_id JOIN subscription_billing_plans p ON p.plan_code=c.plan_code LEFT JOIN subscription_entitlement_grants g ON g.cycle_id=cy.id WHERE p.service_code='grooming' AND c.entitlement_subscription_id IS NOT NULL AND (g.cycle_id IS NULL OR g.status!='applied') ORDER BY cy.created_at LIMIT ?").bind(limit).all<Row>();let granted=0,duplicates=0,errors=0;const failures:string[]=[];for(const item of rows.results){try{const r=await grantSubscriptionRenewalEntitlement(db,{eventId:t(item.provider_event_id)});if(r.duplicate)duplicates++;else if(r.handled)granted++;}catch(error){errors++;failures.push(error instanceof Error?error.message:String(error));}}return{processed:rows.results.length,granted,duplicates,errors,failures};}

async function refundContext(db:Db,cycleId:string){await ensureSubscriptionEntitlementRenewalTables(db);const target=await db.prepare("SELECT g.*,cy.amount_paise cycle_amount_paise,s.total_sessions,s.sessions_reserved,s.sessions_consumed,s.status entitlement_status FROM subscription_entitlement_grants g JOIN subscription_billing_cycles cy ON cy.id=g.cycle_id JOIN customer_grooming_subscriptions s ON s.id=g.entitlement_subscription_id WHERE g.cycle_id=? AND g.status='applied'").bind(cycleId).first<Row>();if(!target)throw new Error("subscription_entitlement_grant_missing");const grants=await db.prepare("SELECT * FROM subscription_entitlement_grants WHERE entitlement_subscription_id=? AND status='applied' ORDER BY created_at,cycle_id").bind(t(target.entitlement_subscription_id)).all<Row>(),idx=grants.results.findIndex(g=>t(g.cycle_id)===cycleId);if(idx<0)throw new Error("subscription_entitlement_grant_missing");const net=(g:Row)=>n(g.credits_granted)-n(g.refunded_credits)-n(g.refund_reserved_credits),netAll=grants.results.reduce((s,g)=>s+net(g),0),netBefore=grants.results.slice(0,idx).reduce((s,g)=>s+net(g),0),base=n(target.total_sessions)-netAll;if(base<0)throw new Error("subscription_entitlement_ledger_drift");const committed=n(target.sessions_reserved)+n(target.sessions_consumed),targetNet=Math.max(0,net(target)),used=Math.min(targetNet,Math.max(0,committed-(base+netBefore))),unused=Math.max(0,targetNet-used),reserved=await db.prepare("SELECT COALESCE(SUM(amount_paise),0) amount FROM subscription_refund_entitlement_allocations WHERE cycle_id=? AND status='reserved'").bind(cycleId).first<Row>();return{target,unused,used,lockedCredits:n(target.refunded_credits)+n(target.refund_reserved_credits),lockedPaise:n(target.refunded_paise)+n(reserved?.amount),cycleAmount:n(target.cycle_amount_paise),totalCredits:n(target.credits_granted),entitlementId:t(target.entitlement_subscription_id)};}
function refundCredits(c:{cycleAmount:number;totalCredits:number;lockedCredits:number;lockedPaise:number;unused:number},amount:number){const max=Math.max(0,Math.floor(c.cycleAmount*(c.lockedCredits+c.unused)/c.totalCredits)-c.lockedPaise);for(let credits=1;credits<=c.unused;credits++){if(Math.floor(c.cycleAmount*(c.lockedCredits+credits)/c.totalCredits)-c.lockedPaise===amount)return{credits,max};}return{credits:0,max};}
export async function validateSubscriptionRefundAgainstUnusedEntitlement(db:Db,input:{cycleId:string;amountPaise:number}){const c=await refundContext(db,input.cycleId),m=refundCredits(c,input.amountPaise);if(!m.credits){if(c.unused<=0)throw new Error("subscription_refund_has_no_unused_entitlement");if(input.amountPaise>m.max)throw new Error("subscription_refund_exceeds_unused_entitlement");throw new Error(`subscription_refund_amount_must_match_unused_entitlement_units:max_${m.max}`);}return{cycleId:input.cycleId,credits:m.credits,maxAdditionalPaise:m.max,unusedCredits:c.unused,usedCredits:c.used};}

async function reserveAllocation(db:Db,input:{cycleId:string;amountPaise:number;allocationKey:string;refundCaseId?:string;gatewayRefundId?:string;kind:"maker_checker"|"provider_proration"}){const existing=await db.prepare("SELECT * FROM subscription_refund_entitlement_allocations WHERE allocation_key=?").bind(input.allocationKey).first<Row>();if(existing)return existing;const c=await refundContext(db,input.cycleId),m=refundCredits(c,input.amountPaise);if(!m.credits){if(c.unused<=0)throw new Error("subscription_refund_has_no_unused_entitlement");if(input.amountPaise>m.max)throw new Error("subscription_refund_exceeds_unused_entitlement");throw new Error(`subscription_refund_amount_must_match_unused_entitlement_units:max_${m.max}`);}const id=uid("SREA"),ts=Date.now(),newTotal=n(c.target.total_sessions)-m.credits;if(newTotal<n(c.target.sessions_reserved)+n(c.target.sessions_consumed))throw new Error("subscription_refund_exceeds_uncommitted_entitlement");const newStatus=t(c.target.entitlement_status)==="paused"?"paused":newTotal<=n(c.target.sessions_reserved)+n(c.target.sessions_consumed)?"exhausted":t(c.target.entitlement_status),results=await db.batch([
 db.prepare("INSERT INTO subscription_refund_entitlement_allocations (id,allocation_key,cycle_id,refund_case_id,gateway_refund_id,amount_paise,credits,kind,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'reserved',?,?)").bind(id,input.allocationKey,input.cycleId,input.refundCaseId||null,input.gatewayRefundId||null,input.amountPaise,m.credits,input.kind,ts,ts),
 db.prepare("UPDATE subscription_entitlement_grants SET refund_reserved_credits=refund_reserved_credits+?,updated_at=? WHERE cycle_id=?").bind(m.credits,ts,input.cycleId),
 db.prepare("UPDATE customer_grooming_subscriptions SET total_sessions=?,status=?,updated_at=? WHERE id=? AND total_sessions=? AND sessions_reserved=? AND sessions_consumed=?").bind(newTotal,newStatus,ts,c.entitlementId,n(c.target.total_sessions),n(c.target.sessions_reserved),n(c.target.sessions_consumed)),
]);if(results.some(r=>Number(r.meta?.changes||0)!==1))throw new Error("subscription_refund_entitlement_changed_during_reservation");return db.prepare("SELECT * FROM subscription_refund_entitlement_allocations WHERE id=?").bind(id).first<Row>();}

export async function approveSubscriptionRefundAgainstUnusedEntitlement(db:Db,input:{refundCaseId:string;actor:string}){await ensureSubscriptionEntitlementRenewalTables(db);const refund=await db.prepare("SELECT * FROM subscription_refund_cases WHERE id=?").bind(input.refundCaseId).first<Row>();if(!refund)throw new Error("subscription_refund_not_found");if(t(refund.requested_by)===input.actor)throw new Error("refund_self_approval_forbidden");if(t(refund.status)!=="requested"){if(t(refund.status)==="approved")return refund;throw new Error("subscription_refund_not_requested");}await reserveAllocation(db,{cycleId:t(refund.cycle_id),amountPaise:n(refund.amount_paise),allocationKey:`refund-case:${input.refundCaseId}`,refundCaseId:input.refundCaseId,kind:"maker_checker"});const claim=await db.prepare("INSERT OR IGNORE INTO subscription_refund_transition_claims (id,refund_case_id,from_status,to_status,actor_id,created_at) VALUES (?,?, 'requested','approved',?,?)").bind(uid("SRFTC"),input.refundCaseId,input.actor,Date.now()).run();if(Number(claim.meta?.changes||0)!==1)throw new Error("refund_transition_already_claimed");await db.prepare("UPDATE subscription_refund_cases SET status='approved',approved_by=?,approved_at=?,updated_at=? WHERE id=? AND status='requested'").bind(input.actor,Date.now(),Date.now(),input.refundCaseId).run();return db.prepare("SELECT * FROM subscription_refund_cases WHERE id=?").bind(input.refundCaseId).first<Row>();}

function refundEntity(payload:Row){const p=payload.payload as Record<string,{entity?:Row}>|undefined;return p?.refund?.entity||{};}
export async function prepareSubscriptionRefundEntitlementForWebhook(db:Db,payload:Row){await ensureSubscriptionEntitlementRenewalTables(db);if(t(payload.event)!=="refund.processed")return{handled:false as const};const refund=refundEntity(payload),refundId=t(refund.id),paymentId=t(refund.payment_id),amount=n(refund.amount);if(!refundId||!paymentId||!Number.isSafeInteger(amount)||amount<=0)return{handled:false as const};const refundCase=await db.prepare("SELECT id,cycle_id,amount_paise FROM subscription_refund_cases WHERE gateway_refund_id=?").bind(refundId).first<Row>().catch(()=>null);if(refundCase){if(n(refundCase.amount_paise)!==amount)throw new Error("subscription_refund_amount_mismatch");const allocation=await db.prepare("SELECT * FROM subscription_refund_entitlement_allocations WHERE refund_case_id=?").bind(t(refundCase.id)).first<Row>();if(!allocation)throw new Error("approved_subscription_refund_entitlement_allocation_missing");return{handled:true as const,allocationKey:t(allocation.allocation_key)};}const cycle=await db.prepare("SELECT id FROM subscription_billing_cycles WHERE provider_payment_id=?").bind(paymentId).first<Row>().catch(()=>null);if(!cycle)return{handled:false as const};const allocation=await reserveAllocation(db,{cycleId:t(cycle.id),amountPaise:amount,allocationKey:`provider-refund:${refundId}`,gatewayRefundId:refundId,kind:"provider_proration"});return{handled:true as const,allocationKey:t(allocation?.allocation_key)};}
export async function finalizeSubscriptionRefundEntitlement(db:Db,allocationKey:string){const a=await db.prepare("SELECT * FROM subscription_refund_entitlement_allocations WHERE allocation_key=?").bind(allocationKey).first<Row>();if(!a)throw new Error("subscription_refund_entitlement_allocation_missing");if(t(a.status)==="processed")return{processed:true,duplicate:true};const ts=Date.now(),results=await db.batch([db.prepare("UPDATE subscription_entitlement_grants SET refund_reserved_credits=refund_reserved_credits-?,refunded_credits=refunded_credits+?,refunded_paise=refunded_paise+?,updated_at=? WHERE cycle_id=? AND refund_reserved_credits>=?").bind(n(a.credits),n(a.credits),n(a.amount_paise),ts,t(a.cycle_id),n(a.credits)),db.prepare("UPDATE subscription_refund_entitlement_allocations SET status='processed',updated_at=? WHERE id=? AND status='reserved'").bind(ts,t(a.id))]);if(results.some(r=>Number(r.meta?.changes||0)!==1))throw new Error("subscription_refund_entitlement_finalize_failed");return{processed:true,duplicate:false,credits:n(a.credits),amountPaise:n(a.amount_paise)};}
