import{calculateTaxiAdjustment,type TaxiVehicleClass}from"./taxi-business-rules";
import{ensureTaxiRideTables}from"./taxi-ride-governance";
import{ensureTaxiProofTables}from"./taxi-proof-governance";
type Row=Record<string,unknown>;
export type TaxiAdjustmentType="parking"|"cleaning"|"extra_waiting"|"extra_distance";
export type TaxiAdjustmentInput={bookingId:string;type:TaxiAdjustmentType;actorId:string;idempotencyKey:string;reason:string;amount?:number;minutes?:number;distanceKm?:number;mediaRef?:string;incidentId?:string};
const mediaId=(ref:string)=>{const prefix="media://asset/";if(!ref.startsWith(prefix))throw new Response("Taxi charge proof must use a PawSpace media reference",{status:400});return ref.slice(prefix.length).trim()};
export async function ensureTaxiAdjustmentTables(db:D1Database){await ensureTaxiRideTables(db);await ensureTaxiProofTables(db);await db.prepare("CREATE TABLE IF NOT EXISTS taxi_adjustment_action_keys (idempotency_key TEXT PRIMARY KEY,booking_id TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)").run();}
export async function applyTaxiTripAdjustment(db:D1Database,input:TaxiAdjustmentInput){await ensureTaxiAdjustmentTables(db);if(!input.bookingId||!input.idempotencyKey||!input.actorId||String(input.reason||"").trim().length<3)throw new Response("Taxi adjustment requires booking, actor, idempotency key and reason",{status:400});const prior=await db.prepare("SELECT result_json FROM taxi_adjustment_action_keys WHERE idempotency_key=?").bind(input.idempotencyKey).first<Row>();if(prior)return{...JSON.parse(String(prior.result_json||"{}")),duplicatePrevented:true};const [booking,trip,ride,schedule]=await Promise.all([db.prepare("SELECT id,status,total_amount,provider_id FROM canonical_bookings WHERE id=? AND service_code='pet_taxi'").bind(input.bookingId).first<Row>(),db.prepare("SELECT id,status FROM taxi_trips WHERE booking_id=?").bind(input.bookingId).first<Row>(),db.prepare("SELECT * FROM taxi_ride_booking_details WHERE booking_id=?").bind(input.bookingId).first<Row>(),db.prepare("SELECT * FROM taxi_payment_schedules WHERE booking_id=?").bind(input.bookingId).first<Row>()]);if(!booking||!trip||!ride||!schedule)throw new Response("Taxi v2 ride is not available for adjustments",{status:404});if(!["in_progress","arrived_dropoff","dropoff_confirmed"].includes(String(trip.status)))throw new Response("Taxi adjustments are allowed only during the active ride before completion",{status:409});if(String(schedule.status)==="paid")throw new Response("A fully settled Taxi ride cannot accept a new charge",{status:409});const vehicleClass=String(ride.vehicle_class) as TaxiVehicleClass,calc=calculateTaxiAdjustment({vehicleClass,type:input.type,amount:input.amount,minutes:input.minutes,distanceKm:input.distanceKm});let proofId:string|null=null,incidentId:string|null=null;
 if(input.type==="cleaning") {incidentId=String(input.incidentId||"").trim();proofId=mediaId(String(input.mediaRef||""));const incident=await db.prepare("SELECT id,media_id,summary,status FROM taxi_incidents WHERE id=? AND booking_id=? AND trip_id=?").bind(incidentId,input.bookingId,trip.id).first<Row>();if(!incident)throw new Response("Cleaning charge requires the linked Taxi incident",{status:409});if(String(incident.media_id)!==proofId)throw new Response("Cleaning charge proof must be the incident photo shared with the customer",{status:409});if(!/pee|poop|vomit|vomiting|soil|clean/i.test(String(incident.summary||"")))throw new Response("Cleaning charge incident must describe a cleaning event",{status:409});const proof=await db.prepare("SELECT scan_status,access_status,retention_status,synthetic FROM service_media_assets WHERE id=? AND booking_id=? AND provider_id=? AND purpose='taxi_incident'").bind(proofId,input.bookingId,booking.provider_id).first<Row>();if(!proof||String(proof.scan_status)!=="clean"||String(proof.access_status)!=="ready"||String(proof.retention_status)!=="active"||Number(proof.synthetic||0)!==0)throw new Response("Cleaning charge requires clean active incident proof",{status:409});}
 if(input.type==="parking"){if(!String(input.mediaRef||"").trim())throw new Response("Parking charge requires receipt/photo proof",{status:409});proofId=mediaId(String(input.mediaRef));const proof=await db.prepare("SELECT scan_status,access_status,retention_status,synthetic FROM service_media_assets WHERE id=? AND booking_id=? AND provider_id=?").bind(proofId,input.bookingId,booking.provider_id).first<Row>();if(!proof||String(proof.scan_status)!=="clean"||String(proof.access_status)!=="ready"||String(proof.retention_status)!=="active"||Number(proof.synthetic||0)!==0)throw new Response("Parking proof must be clean active Taxi media",{status:409});}
 const amount=Number(calc.amount),newTotal=Math.round((Number(ride.final_total)+amount)*100)/100,newBalance=Math.round((newTotal-Number(schedule.booking_fee_amount))*100)/100,id=`TADJ-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now(),quantity=input.type==="extra_waiting"?Number(input.minutes):input.type==="extra_distance"?Number(input.distanceKm):null,result={bookingId:input.bookingId,adjustmentId:id,type:input.type,amount,quantity,finalTotal:newTotal,finalBalance:newBalance,proofRef:proofId?`media://asset/${proofId}`:null,incidentId,liveMoney:false};
 await db.batch([db.prepare("INSERT INTO taxi_trip_adjustments (id,booking_id,trip_id,adjustment_type,quantity,amount,media_id,incident_id,status,reason,created_by,created_at) VALUES (?,?,?,?,?,?,?,?, 'applied',?,?,?)").bind(id,input.bookingId,trip.id,input.type,quantity,amount,proofId,incidentId,String(input.reason).trim(),input.actorId,now),db.prepare("UPDATE taxi_ride_booking_details SET final_total=?,updated_at=? WHERE booking_id=?").bind(newTotal,now,input.bookingId),db.prepare("UPDATE canonical_bookings SET total_amount=?,updated_at=? WHERE id=? AND status='in_progress'").bind(newTotal,now,input.bookingId),db.prepare("UPDATE booking_payments SET amount=?,detail_json=json_set(COALESCE(detail_json,'{}'),'$.finalBalance',?,'$.hasTripAdjustments',1),updated_at=? WHERE booking_id=?").bind(newTotal,newBalance,now,input.bookingId),db.prepare("UPDATE taxi_payment_schedules SET total_amount=?,balance_amount=?,updated_at=? WHERE booking_id=? AND status!='paid'").bind(newTotal,newBalance,now,input.bookingId),db.prepare("INSERT INTO taxi_trip_events (id,booking_id,trip_id,provider_id,event_type,actor_id,detail_json,created_at) VALUES (?,?,?,?, 'trip_charge_adjusted',?,?,?)").bind(crypto.randomUUID(),input.bookingId,trip.id,booking.provider_id,input.actorId,JSON.stringify(result),now),db.prepare("INSERT INTO taxi_adjustment_action_keys (idempotency_key,booking_id,result_json,created_at) VALUES (?,?,?,?)").bind(input.idempotencyKey,input.bookingId,JSON.stringify(result),now)]);return result;}
export async function listTaxiTripAdjustments(db:D1Database,bookingId:string){await ensureTaxiAdjustmentTables(db);return(await db.prepare("SELECT * FROM taxi_trip_adjustments WHERE booking_id=? AND status='applied' ORDER BY created_at").bind(bookingId).all<Row>()).results;}
