import{ensureD1Once}from"./d1-ensure-once.js";
import{taxiVehicleEconomics,type TaxiVehicleClass}from"./taxi-business-rules";
import{resolveTaxiMarketplacePolicy}from"./taxi-marketplace-policy";
import{chunkedIn}from"./d1-chunked-in";
type Row=Record<string,unknown>;
export const TAXI_FULL_TIME_DRIVERS=["taxi_rahul","taxi_meera"] as const;
const missingColumn=(error:unknown)=>/duplicate column name/i.test(error instanceof Error?error.message:String(error));
async function addColumn(db:D1Database,sql:string){try{await db.prepare(sql).run()}catch(error){if(!missingColumn(error))throw error}}
/*
 * Once per isolate (ready-set only: lib/d1-ensure-once.js, so a cancelled request can never leave a later one
 * waiting on its setup). Every Pet Taxi ride booking ran this before holding a car - a CREATE batch, twelve
 * sequential ALTERs and nine sequential seed writes, 22 D1 round trips (~5.5 s at staging's ~250 ms per call).
 * The end state is the same: one table_info read per table decides which columns an older table still lacks and
 * exactly those ALTERs run as before (every ALTER is attempted if that read fails), and the three code-seeded cars
 * and their full-time drivers are written INSERT OR IGNORE in one batch.
 */
export async function ensureTaxiFleetTables(db:D1Database){await ensureD1Once(db,"taxi_fleet_tables",()=>ensureTaxiFleetTablesUncached(db));}
const tableColumns=(db:D1Database,table:string)=>db.prepare(`PRAGMA table_info(${table})`).all<Row>().then(rows=>new Set(rows.results.map(row=>String(row.name)))).catch(()=>null);
async function ensureTaxiFleetTablesUncached(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS taxi_fleet_vehicles (id TEXT PRIMARY KEY,vehicle_class TEXT NOT NULL,label TEXT NOT NULL,registration_suffix TEXT NOT NULL UNIQUE,ownership_model TEXT NOT NULL,pawspace_share_percent REAL NOT NULL,owner_commission_percent REAL NOT NULL,gst_rate REAL NOT NULL,gst_base TEXT NOT NULL,inspection_status TEXT NOT NULL DEFAULT 'uat_verified',active INTEGER NOT NULL DEFAULT 1,features_json TEXT NOT NULL DEFAULT '[]',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS taxi_driver_vehicle_eligibility (provider_id TEXT NOT NULL,vehicle_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',created_at INTEGER NOT NULL,PRIMARY KEY(provider_id,vehicle_id))"),
 db.prepare("CREATE TABLE IF NOT EXISTS taxi_fleet_reservations (id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,provider_id TEXT NOT NULL,quote_id TEXT NOT NULL,booking_id TEXT,scheduled_start TEXT NOT NULL,scheduled_end TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'held',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_taxi_fleet_window ON taxi_fleet_reservations(vehicle_id,status,scheduled_start,scheduled_end)"),
 ]);
 const columns={taxi_fleet_vehicles:tableColumns(db,"taxi_fleet_vehicles"),taxi_fleet_reservations:tableColumns(db,"taxi_fleet_reservations")};
 for(const sql of[
  "ALTER TABLE taxi_fleet_vehicles ADD COLUMN city_id TEXT NOT NULL DEFAULT 'blr'",
  "ALTER TABLE taxi_fleet_vehicles ADD COLUMN owner_provider_id TEXT",
  "ALTER TABLE taxi_fleet_vehicles ADD COLUMN commercial_mode TEXT NOT NULL DEFAULT 'fixed'",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN city_id TEXT",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN ownership_model TEXT",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN owner_provider_id TEXT",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN pawspace_share_percent REAL",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN owner_commission_percent REAL",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN gst_rate REAL",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN gst_base TEXT",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN commercial_policy_id TEXT",
  "ALTER TABLE taxi_fleet_reservations ADD COLUMN commercial_policy_version TEXT"
 ]){const [,table,column]=/^ALTER TABLE (\w+) ADD COLUMN (\w+)/.exec(sql)!;const present=await columns[table as keyof typeof columns];if(!present?.has(column))await addColumn(db,sql);}
 const now=Date.now(),seed=[{id:"TXF-CITROEN-9179",vehicleClass:"citroen_ec3" as const,label:"Citroen eC3 · 9179",suffix:"9179"},{id:"TXF-CITROEN-9188",vehicleClass:"citroen_ec3" as const,label:"Citroen eC3 · 9188",suffix:"9188"},{id:"TXF-XUV-OWNER",vehicleClass:"xuv" as const,label:"PawSpace XUV",suffix:"XUV"}];
 await db.batch(seed.flatMap(v=>{const economics=taxiVehicleEconomics(v.suffix,v.vehicleClass);return[db.prepare("INSERT OR IGNORE INTO taxi_fleet_vehicles (id,vehicle_class,label,registration_suffix,ownership_model,pawspace_share_percent,owner_commission_percent,gst_rate,gst_base,inspection_status,active,features_json,created_at,updated_at,city_id,commercial_mode) VALUES (?,?,?,?,?,?,?,?,?,'uat_verified',1,?,?,?,?, 'fixed')").bind(v.id,v.vehicleClass,v.label,v.suffix,economics.ownership,economics.pawspaceSharePercent,economics.ownerCommissionPercent,economics.gstRate,economics.gstBase,JSON.stringify(["AC","pet_restraint","gps","masked_calling"]),now,now,"blr"),...TAXI_FULL_TIME_DRIVERS.map(driver=>db.prepare("INSERT OR IGNORE INTO taxi_driver_vehicle_eligibility (provider_id,vehicle_id,status,created_at) VALUES (?,?,'active',?)").bind(driver,v.id,now))];}));}
export async function availableTaxiFleet(db:D1Database,input:{vehicleClass:TaxiVehicleClass;providerId:string;cityId:string;scheduledStart:string;scheduledEnd:string}){await ensureTaxiFleetTables(db);const rows=await db.prepare(`SELECT v.* FROM taxi_fleet_vehicles v JOIN taxi_driver_vehicle_eligibility e ON e.vehicle_id=v.id AND e.provider_id=? AND e.status='active' WHERE v.vehicle_class=? AND v.city_id=? AND v.active=1 AND v.inspection_status='uat_verified' AND (v.commercial_mode!='marketplace_policy' OR v.owner_provider_id=?) AND NOT EXISTS(SELECT 1 FROM taxi_fleet_reservations r WHERE r.vehicle_id=v.id AND r.status IN ('held','confirmed','in_progress') AND r.scheduled_start<? AND r.scheduled_end>?) ORDER BY CASE WHEN v.registration_suffix='9179' THEN 0 ELSE 1 END,v.id`).bind(input.providerId,input.vehicleClass,input.cityId,input.providerId,input.scheduledEnd,input.scheduledStart).all<Row>();return rows.results;}
/**
 * The drivers (of `providerIds`, or of the whole city when omitted) who can take a free, verified fleet car
 * (of `vehicleClass`, when given) in this window - the same test holdTaxiFleetVehicle applies when the booking
 * is written, asked BEFORE a driver is assigned. The scheduler used to rank every pet_taxi profile, so it could
 * assign a driver with no car (uatcap_taxi_ft, taxi_imran) and the booking then refused with "No Citroen eC3 is
 * free for this 3-hour Taxi window" although another driver's car was free. One read, which needs nothing but
 * the city and window, so the scheduler runs it beside its own provider reads; the fleet schema is created only
 * if it is missing (a fresh database).
 */
export async function taxiDriversWithFreeCar(db:D1Database,input:{providerIds?:readonly string[];cityId:string;scheduledStart:string;scheduledEnd:string;vehicleClass?:string|null}):Promise<Set<string>>{
 const ids=input.providerIds?[...new Set(input.providerIds)]:null,vehicleClass=input.vehicleClass==="citroen_ec3"||input.vehicleClass==="xuv"?input.vehicleClass:null;if(ids&&!ids.length)return new Set();
 const query=(scope:string)=>`SELECT DISTINCT e.provider_id FROM taxi_driver_vehicle_eligibility e JOIN taxi_fleet_vehicles v ON v.id=e.vehicle_id WHERE e.status='active'${scope} AND v.city_id=? AND v.active=1 AND v.inspection_status='uat_verified'${vehicleClass?" AND v.vehicle_class=?":""} AND (v.commercial_mode!='marketplace_policy' OR v.owner_provider_id=e.provider_id) AND NOT EXISTS(SELECT 1 FROM taxi_fleet_reservations r WHERE r.vehicle_id=v.id AND r.status IN ('held','confirmed','in_progress') AND r.scheduled_start<? AND r.scheduled_end>?)`;
 const tail=[input.cityId,...(vehicleClass?[vehicleClass]:[]),input.scheduledEnd,input.scheduledStart];
 const read=async()=>ids?chunkedIn(ids,async(chunk,placeholders)=>(await db.prepare(query(` AND e.provider_id IN (${placeholders})`)).bind(...chunk,...tail).all<Row>()).results):(await db.prepare(query("")).bind(...tail).all<Row>()).results;
 let rows:Row[];
 try{rows=await read();}catch(error){if(!/no such (table|column)/i.test(error instanceof Error?error.message:String(error)))throw error;await ensureTaxiFleetTables(db);rows=await read();}
 return new Set(rows.map(row=>String(row.provider_id)));
}
export async function holdTaxiFleetVehicle(db:D1Database,input:{quoteId:string;vehicleClass:TaxiVehicleClass;providerId:string;cityId:string;scheduledStart:string;scheduledEnd:string}){const candidates=await availableTaxiFleet(db,input);if(!candidates.length)throw new Response(`No ${input.vehicleClass==="xuv"?"XUV":"Citroen eC3"} is free for this 3-hour Taxi window in ${input.cityId}`,{status:409});for(const v of candidates){let pawspace=Number(v.pawspace_share_percent),owner=Number(v.owner_commission_percent),gst=Number(v.gst_rate),gstBase=String(v.gst_base),policyId:string|null=null,policyVersion:string|null=null;if(String(v.commercial_mode)==="marketplace_policy"){const policy=await resolveTaxiMarketplacePolicy(db,input.cityId);if(!policy.config.providerOwnedEnabled)continue;pawspace=Number(policy.config.pawspaceSharePercent);owner=Number(policy.config.providerSharePercent);gst=Number(policy.config.gstRate);gstBase=String(policy.config.gstBase);policyId=policy.id;policyVersion=policy.policyVersion;}if(Math.abs(pawspace+owner-100)>0.0001)throw new Response("Taxi fleet ownership shares do not balance to 100%",{status:409});const id=`TFR-${crypto.randomUUID().slice(0,12).toUpperCase()}`,now=Date.now();try{const held=await db.prepare("INSERT INTO taxi_fleet_reservations (id,vehicle_id,provider_id,quote_id,booking_id,scheduled_start,scheduled_end,status,created_at,updated_at,city_id,ownership_model,owner_provider_id,pawspace_share_percent,owner_commission_percent,gst_rate,gst_base,commercial_policy_id,commercial_policy_version) SELECT ?,?,?,?,?,?,?,'held',?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM taxi_fleet_reservations WHERE vehicle_id=? AND status IN ('held','confirmed','in_progress') AND scheduled_start<? AND scheduled_end>?) RETURNING id").bind(id,v.id,input.providerId,input.quoteId,null,input.scheduledStart,input.scheduledEnd,now,now,input.cityId,v.ownership_model,v.owner_provider_id||null,pawspace,owner,gst,gstBase,policyId,policyVersion,v.id,input.scheduledEnd,input.scheduledStart).first<Row>();/* The same in-statement NOT EXISTS guard decides; RETURNING says whether this car was held (it was read back with a second SELECT). */if(held)return{reservationId:id,vehicleId:String(v.id),vehicleLabel:String(v.label),registrationSuffix:String(v.registration_suffix),vehicleClass:String(v.vehicle_class) as TaxiVehicleClass,ownershipModel:String(v.ownership_model),ownerProviderId:v.owner_provider_id?String(v.owner_provider_id):null,pawspaceSharePercent:pawspace,ownerCommissionPercent:owner,providerSharePercent:owner,gstRate:gst,gstBase,commercialPolicyId:policyId,commercialPolicyVersion:policyVersion};}catch{/* try next physical car */}}
 throw new Response("Taxi fleet availability changed; refresh the ride",{status:409});}
/** The statement that turns a held car into the booking's car, for a caller that runs it inside its own batch. */
export function confirmTaxiFleetHoldStatement(db:D1Database,input:{reservationId:string;bookingId:string},now=Date.now()){return db.prepare("UPDATE taxi_fleet_reservations SET booking_id=?,status='confirmed',updated_at=? WHERE id=? AND status='held'").bind(input.bookingId,now,input.reservationId);}
/** Refuses unless the confirmation changed exactly the held row. */
export function assertTaxiFleetHoldConfirmed(result:{meta?:{changes?:number}}|undefined){if(Number(result?.meta?.changes||0)!==1)throw new Response("Taxi fleet hold expired or changed",{status:409});}
export async function confirmTaxiFleetHold(db:D1Database,input:{reservationId:string;bookingId:string}){assertTaxiFleetHoldConfirmed(await confirmTaxiFleetHoldStatement(db,input).run());}
export async function taxiFleetForBooking(db:D1Database,bookingId:string){await ensureTaxiFleetTables(db);return db.prepare("SELECT r.*,v.vehicle_class,v.label vehicle_label,v.registration_suffix,COALESCE(r.ownership_model,v.ownership_model) ownership_model,COALESCE(r.owner_provider_id,v.owner_provider_id) owner_provider_id,COALESCE(r.pawspace_share_percent,v.pawspace_share_percent) pawspace_share_percent,COALESCE(r.owner_commission_percent,v.owner_commission_percent) owner_commission_percent,COALESCE(r.gst_rate,v.gst_rate) gst_rate,COALESCE(r.gst_base,v.gst_base) gst_base,v.commercial_mode FROM taxi_fleet_reservations r JOIN taxi_fleet_vehicles v ON v.id=r.vehicle_id WHERE r.booking_id=? ORDER BY r.created_at DESC LIMIT 1").bind(bookingId).first<Row>();}
export async function registerProviderTaxiVehicle(db:D1Database,input:{providerId:string;cityId:string;vehicleClass:TaxiVehicleClass;label:string;registrationNumber:string;actorId:string}){await ensureTaxiFleetTables(db);const provider=await db.prepare("SELECT id,city_id,provider_model,services_json,live,status FROM provider_capacity_profiles WHERE id=?").bind(input.providerId).first<Row>();if(!provider||String(provider.status)!=="active"||Number(provider.live)!==1)throw new Response("Taxi provider must be active and live before a vehicle can be onboarded",{status:409});if(String(provider.city_id)!==input.cityId)throw new Response("Taxi vehicle city must match the provider city",{status:409});let services:string[]=[];try{services=JSON.parse(String(provider.services_json||"[]"))}catch{}if(!services.includes("pet_taxi"))throw new Response("Provider is not enabled for Pet Taxi",{status:409});if(String(provider.provider_model)!=="commission")throw new Response("Marketplace Taxi vehicles require a commission provider",{status:409});const registration=input.registrationNumber.toUpperCase().replace(/[^A-Z0-9]/g,"");if(registration.length<4)throw new Response("A valid vehicle registration is required",{status:400});const id=`TXF-${input.cityId.toUpperCase()}-${registration}`,now=Date.now();await db.prepare("INSERT INTO taxi_fleet_vehicles (id,vehicle_class,label,registration_suffix,ownership_model,pawspace_share_percent,owner_commission_percent,gst_rate,gst_base,inspection_status,active,features_json,created_at,updated_at,city_id,owner_provider_id,commercial_mode) VALUES (?,?,?,?, 'provider_owned',30,70,18,'pawspace_share','verification_required',0,?,?,?, ?,?,'marketplace_policy') ON CONFLICT(id) DO UPDATE SET label=excluded.label,vehicle_class=excluded.vehicle_class,city_id=excluded.city_id,owner_provider_id=excluded.owner_provider_id,updated_at=excluded.updated_at").bind(id,input.vehicleClass,input.label.trim(),registration,JSON.stringify(["AC","pet_restraint","gps","masked_calling"]),now,now,input.cityId,input.providerId).run();await db.prepare("INSERT OR REPLACE INTO taxi_driver_vehicle_eligibility (provider_id,vehicle_id,status,created_at) VALUES (?,?,'active',?)").bind(input.providerId,id,now).run();return{id,providerId:input.providerId,cityId:input.cityId,vehicleClass:input.vehicleClass,label:input.label.trim(),registrationNumber:registration,ownershipModel:"provider_owned" as const,commercialMode:"marketplace_policy" as const,inspectionStatus:"verification_required" as const,active:false,defaultProviderSharePercent:70,defaultPawspaceSharePercent:30};}
export async function setTaxiVehicleAvailability(db:D1Database,input:{vehicleId:string;inspectionStatus:"verification_required"|"uat_verified"|"rejected";active:boolean;actorId:string}){await ensureTaxiFleetTables(db);const changed=await db.prepare("UPDATE taxi_fleet_vehicles SET inspection_status=?,active=?,updated_at=? WHERE id=?").bind(input.inspectionStatus,input.active&&input.inspectionStatus==="uat_verified"?1:0,Date.now(),input.vehicleId).run();if(Number(changed.meta?.changes||0)!==1)throw new Response("Taxi vehicle not found",{status:404});return db.prepare("SELECT * FROM taxi_fleet_vehicles WHERE id=?").bind(input.vehicleId).first<Row>();}
export async function listTaxiFleet(db:D1Database,cityId?:string){await ensureTaxiFleetTables(db);const rows=cityId?await db.prepare("SELECT * FROM taxi_fleet_vehicles WHERE city_id=? ORDER BY active DESC,label").bind(cityId).all<Row>():await db.prepare("SELECT * FROM taxi_fleet_vehicles ORDER BY city_id,active DESC,label").all<Row>();return rows.results;}
