import{ensureTrainingProgrammeTables}from"./training-programme";
import{getGovernedProvider,seedProviderCapacityDefaults}from"./provider-capacity-governance";
import{listAuthoritativeAvailability}from"./scheduling-roster-authority";
import{haversineDistanceKm}from"../backend/src/scheduling";
import{trainingQuotePaymentState,ensureTrainingCommercialTables}from"./training-commercial-governance";

type Row=Record<string,unknown>;
export const TRAINING_REQUIRED_PROOF=["before_service","after_service"] as const;
export const TRAINING_ARRIVAL_GEOFENCE_METERS=250;
export type TrainingSessionAction="accept"|"on_the_way"|"arrive"|"start"|"save_report"|"owner_handover"|"complete"|"request_reschedule"|"no_show"|"reschedule"|"replace_provider"|"cancel_session";
export type TrainingReport={attendance?:Record<string,unknown>;homework?:string;progress?:Record<string,unknown>;evidenceRefs?:string[]};
export type TrainingSessionMutation={sessionId:string;action:TrainingSessionAction;actorId:string;idempotencyKey:string;reason?:string;report?:TrainingReport;newStart?:string;newEnd?:string;newProviderId?:string;staffOverride?:boolean;latitude?:number;longitude?:number;ownerHandoverMinutes?:number};

export async function ensureTrainingSessionLifecycleTables(db:D1Database){
 /* #388 added governedPayment() and assertFinalBalancePaid() here, both of which SELECT from
  * training_booking_quote_links - a table owned by training-commercial-governance and never
  * created by this module. Any caller that reached session lifecycle without first going
  * through the commercial path therefore threw "no such table". Ensuring it here makes this
  * module self-sufficient for the tables it reads; CREATE TABLE IF NOT EXISTS is idempotent. */
 await ensureTrainingCommercialTables(db);await ensureTrainingProgrammeTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS training_session_events (id TEXT PRIMARY KEY,session_id TEXT NOT NULL,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_training_session_events_session ON training_session_events(session_id,created_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_session_consumptions (session_id TEXT PRIMARY KEY,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,actor_id TEXT NOT NULL,consumed_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_session_recovery_cases (id TEXT PRIMARY KEY,session_id TEXT NOT NULL,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,recovery_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',reason TEXT NOT NULL,requested_by TEXT NOT NULL,replacement_provider_id TEXT,new_start TEXT,new_end TEXT,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_training_session_recovery_open ON training_session_recovery_cases(session_id,status,updated_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_session_media_links (media_id TEXT PRIMARY KEY,session_id TEXT NOT NULL,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_training_session_media_session ON training_session_media_links(session_id,created_at)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_owner_handover (session_id TEXT PRIMARY KEY,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,duration_minutes INTEGER NOT NULL,completed_by TEXT NOT NULL,completed_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_completion_certificates (programme_id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,certificate_number TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'generated',payload_json TEXT NOT NULL,generated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS training_customer_notifications (id TEXT PRIMARY KEY,programme_id TEXT NOT NULL,booking_id TEXT NOT NULL,customer_id TEXT NOT NULL,channel TEXT NOT NULL,template_code TEXT NOT NULL,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',created_at INTEGER NOT NULL)"),
]);}

function parse<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??"")) as T}catch{return fallback}}
async function sessionRow(db:D1Database,sessionId:string){await ensureTrainingSessionLifecycleTables(db);return db.prepare("SELECT s.*,p.customer_id,p.provider_id programme_provider_id,p.zone_id,p.plan_code,p.plan_name,p.pet_ids_json,p.requirements_json,p.total_sessions,p.completed_sessions,p.no_show_sessions,p.cancelled_sessions,p.status programme_status,c.name customer_name FROM training_sessions s JOIN training_programmes p ON p.id=s.programme_id LEFT JOIN canonical_customers c ON c.id=p.customer_id WHERE s.id=?").bind(sessionId).first<Row>();}
export async function getTrainingSession(db:D1Database,sessionId:string){return sessionRow(db,sessionId);}
async function event(db:D1Database,row:Row,input:TrainingSessionMutation,detail:unknown={}){await db.prepare("INSERT INTO training_session_events (id,session_id,programme_id,booking_id,event_type,actor_id,idempotency_key,detail_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),row.id,row.programme_id,row.booking_id,input.action,input.actorId,input.idempotencyKey,JSON.stringify(detail),Date.now()).run();}
async function duplicate(db:D1Database,idempotencyKey:string,sessionId:string,action:string){const row=await db.prepare("SELECT session_id,event_type,detail_json,created_at FROM training_session_events WHERE idempotency_key=?").bind(idempotencyKey).first<Row>();if(!row)return null;if(String(row.session_id)!==String(sessionId)||String(row.event_type)!==String(action))throw new Response("An idempotency key identifies one action on one record; this key was already used for a different one",{status:409});return row;}
async function recalcProgramme(db:D1Database,programmeId:string){const counts=await db.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status='no_show' THEN 1 ELSE 0 END) no_show,SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) cancelled,SUM(CASE WHEN status IN ('accepted','on_the_way','arrived','in_session','reschedule_requested') THEN 1 ELSE 0 END) active FROM training_sessions WHERE programme_id=?").bind(programmeId).first<Row>();const total=Number(counts?.total||0),completed=Number(counts?.completed||0),noShow=Number(counts?.no_show||0),cancelled=Number(counts?.cancelled||0),active=Number(counts?.active||0),terminal=completed+cancelled+noShow===total;const status=terminal?"CLOSED":active>0||completed>0||noShow>0?"in_progress":"scheduled";await db.prepare("UPDATE training_programmes SET completed_sessions=?,no_show_sessions=?,cancelled_sessions=?,status=?,updated_at=? WHERE id=?").bind(completed,noShow,cancelled,status,Date.now(),programmeId).run();return{total,completed,noShow,cancelled,status,terminal};}

export async function listTrainerSessions(db:D1Database,providerId:string){await ensureTrainingSessionLifecycleTables(db);const rows=await db.prepare("SELECT s.*,p.customer_id,p.plan_code,p.plan_name,p.pet_ids_json,p.requirements_json,p.total_sessions,p.completed_sessions,p.no_show_sessions,p.cancelled_sessions,p.status programme_status,c.name customer_name FROM training_sessions s JOIN training_programmes p ON p.id=s.programme_id LEFT JOIN canonical_customers c ON c.id=p.customer_id WHERE s.provider_id=? ORDER BY s.scheduled_start,s.sequence_no LIMIT 200").bind(providerId).all<Row>();const results=[];for(const row of rows.results){const events=await db.prepare("SELECT event_type,actor_id,detail_json,created_at FROM training_session_events WHERE session_id=? ORDER BY created_at DESC LIMIT 20").bind(row.id).all<Row>();results.push({...row,petIds:parse<string[]>(row.pet_ids_json,[]),requirements:parse<string[]>(row.requirements_json,[]),attendance:parse(row.attendance_json,{}),homework:parse(row.homework_json,{}),progress:parse(row.progress_json,{}),evidenceRefs:parse<string[]>(row.evidence_json,[]),events:events.results});}return results;}

async function secureEvidenceReady(db:D1Database,row:Row,refs:string[]){if(!refs.length)return{ready:false,reason:"At least one secure Training evidence asset is required"};let before=false,after=false;for(const ref of refs){const match=/^media:\/\/asset\/(.+)$/.exec(ref);if(!match)return{ready:false,reason:"Training evidence must use a canonical media://asset reference"};const asset=await db.prepare("SELECT a.id,a.booking_id,a.provider_id,a.purpose,a.scan_status,a.access_status,a.retention_status,a.synthetic,l.session_id,l.provider_id link_provider_id FROM service_media_assets a JOIN training_session_media_links l ON l.media_id=a.id WHERE a.id=?").bind(match[1]).first<Row>();if(!asset||String(asset.session_id)!==String(row.id)||String(asset.booking_id)!==String(row.booking_id)||String(asset.provider_id)!==String(row.provider_id)||String(asset.link_provider_id)!==String(row.provider_id)||String(asset.scan_status)!=="clean"||String(asset.access_status)!=="ready"||String(asset.retention_status)!=="active"||Number(asset.synthetic||0)!==0)return{ready:false,reason:`Evidence ${ref} is not clean, ready, active, non-synthetic proof linked to this exact Training session/trainer`};const purpose=String(asset.purpose);if(purpose==="before_service")before=true;if(purpose==="after_service")after=true;}if(!before||!after)return{ready:false,reason:"Canonical Before Picture + After Picture are required for Training completion"};return{ready:true};}
function reportProblem(report:TrainingReport|undefined){const attendance=report?.attendance??{},mode=String(attendance.mode||"");if(!["parent","trainer_led"].includes(mode))return"Attendance mode must be parent or trainer_led";if(attendance.safeAreaConfirmed!==true)return"Safe training area confirmation is required";if(mode==="parent"&&attendance.parentOrCaretakerConfirmed!==true)return"Parent/caretaker attendance confirmation is required";if(String(report?.homework||"").trim().length<10)return"Meaningful homework is required before completion";const progress=report?.progress??{},scores=Object.values(progress).filter(value=>typeof value==="number") as number[];if(!scores.length||scores.some(score=>score<1||score>10))return"At least one 1-10 progress score is required";return null;}
async function assertArrivalGeofence(db:D1Database,row:Row,input:TrainingSessionMutation){if(!Number.isFinite(input.latitude)||!Number.isFinite(input.longitude))throw new Response("ARRIVED requires provider latitude and longitude",{status:409});const exists=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='booking_service_addresses'").first<Row>();if(!exists)throw new Response("Booking doorstep coordinates are not configured",{status:409});const target=await db.prepare("SELECT latitude,longitude FROM booking_service_addresses WHERE booking_id=?").bind(row.booking_id).first<Row>();if(target?.latitude==null||target?.longitude==null)throw new Response("Booking doorstep coordinates are not configured",{status:409});const distanceKm=haversineDistanceKm({latitude:Number(input.latitude),longitude:Number(input.longitude)},{latitude:Number(target.latitude),longitude:Number(target.longitude)});if(distanceKm*1000>TRAINING_ARRIVAL_GEOFENCE_METERS)throw new Response(`Trainer is ${(distanceKm*1000).toFixed(0)}m from the customer doorstep; ARRIVED requires <=${TRAINING_ARRIVAL_GEOFENCE_METERS}m`,{status:409});return{distanceMeters:Math.round(distanceKm*1000),thresholdMeters:TRAINING_ARRIVAL_GEOFENCE_METERS};}
function windowCovers(window:string,startMinutes:number,endMinutes:number){const match=/^(\d{2}):(\d{2})-(\d{2}):(\d{2})$/.exec(window);if(!match)return false;const from=Number(match[1])*60+Number(match[2]),to=Number(match[3])*60+Number(match[4]);return startMinutes>=from&&endMinutes<=to;}
async function rosterCovers(db:D1Database,providerId:string,zoneId:string,start:string,end:string){const table=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='scheduling_availability'").first<Row>();if(!table)return{covered:false,reason:"Trainer roster availability is not configured; cannot verify the trainer works this window"};const localStart=new Date(new Date(start).getTime()+330*60_000),localEnd=new Date(new Date(end).getTime()+330*60_000),date=localStart.toISOString().slice(0,10),startMinutes=localStart.getUTCHours()*60+localStart.getUTCMinutes(),endMinutes=localEnd.getUTCHours()*60+localEnd.getUTCMinutes();const rows=await listAuthoritativeAvailability(db,providerId,date);const covered=rows.some(item=>String(item.zone_id)===String(zoneId)&&parse<string[]>(item.windows_json,[]).some(window=>windowCovers(window,startMinutes,endMinutes)));return covered?{covered:true}:{covered:false,reason:`Trainer has no roster availability covering ${date} in this zone for the requested window`};}
async function providerConflict(db:D1Database,providerId:string,zoneId:string,start:string,end:string,reservationId:string){await seedProviderCapacityDefaults(db);const profile=await db.prepare("SELECT travel_buffer_minutes FROM provider_capacity_profiles WHERE id=? AND status='active' AND live=1").bind(providerId).first<Row>();if(!profile)return{conflict:true,reason:"Replacement/reschedule provider is not active"};const roster=await rosterCovers(db,providerId,zoneId,start,end);if(!roster.covered)return{conflict:true,reason:roster.reason};const buffer=Math.max(0,Number(profile.travel_buffer_minutes||0))*60_000,startMs=new Date(start).getTime(),endMs=new Date(end).getTime();const rows=await db.prepare("SELECT id,scheduled_start,scheduled_end FROM scheduling_reservations WHERE provider_id=? AND id!=? AND status!='cancelled'").bind(providerId,reservationId).all<Row>();const conflict=rows.results.find(item=>new Date(String(item.scheduled_start)).getTime()<endMs+buffer&&new Date(String(item.scheduled_end)).getTime()>startMs-buffer);return conflict?{conflict:true,reason:`Provider schedule conflicts with reservation ${String(conflict.id)} including travel buffer`}:{conflict:false};}
async function recovery(db:D1Database,row:Row,type:string,reason:string,actorId:string,extra:Record<string,unknown>={}){const now=Date.now(),existing=await db.prepare("SELECT id FROM training_session_recovery_cases WHERE session_id=? AND recovery_type=? AND status='open' ORDER BY created_at DESC LIMIT 1").bind(row.id,type).first<Row>();if(existing){await db.prepare("UPDATE training_session_recovery_cases SET reason=?,requested_by=?,detail_json=?,updated_at=? WHERE id=?").bind(reason,actorId,JSON.stringify(extra),now,existing.id).run();return String(existing.id);}const id=`TSR-${crypto.randomUUID().slice(0,12).toUpperCase()}`;await db.prepare("INSERT INTO training_session_recovery_cases (id,session_id,programme_id,booking_id,recovery_type,status,reason,requested_by,replacement_provider_id,new_start,new_end,detail_json,created_at,updated_at) VALUES (?,?,?,?,?,'open',?,?,NULL,NULL,NULL,?,?,?)").bind(id,row.id,row.programme_id,row.booking_id,type,reason,actorId,JSON.stringify(extra),now,now).run();return id;}
async function assertFinalBalancePaid(db:D1Database,row:Row){if(Number(row.sequence_no)!==Number(row.total_sessions))return;const link=await db.prepare("SELECT quote_id FROM training_booking_quote_links WHERE booking_id=?").bind(row.booking_id).first<Row>();if(!link)throw new Response("Final Training session requires a linked commercial quote",{status:409});const state=await trainingQuotePaymentState(db,String(link.quote_id));if(state.status!=="FULLY_PAID")throw new Response(`Final Training session is blocked until the remaining balance is paid; current state ${state.status}`,{status:409});}
async function unlockNextSession(db:D1Database,row:Row,now:number){const next=await db.prepare("SELECT id,schedule_reservation_id,sequence_no FROM training_sessions WHERE programme_id=? AND sequence_no>? AND status='locked' ORDER BY sequence_no LIMIT 1").bind(row.programme_id,row.sequence_no).first<Row>();if(!next)return null;await db.batch([db.prepare("UPDATE training_sessions SET status='scheduled',updated_at=? WHERE id=? AND status='locked'").bind(now,next.id),db.prepare("UPDATE scheduling_reservations SET status='assigned' WHERE id=? AND status!='cancelled'").bind(next.schedule_reservation_id)]);return{sessionId:String(next.id),sequenceNo:Number(next.sequence_no),status:"scheduled" as const};}
async function closeProgrammeArtifacts(db:D1Database,row:Row,programme:{status:string;terminal:boolean}){if(!programme.terminal)return null;const now=Date.now(),certificateNumber=`PS-TRN-${String(row.programme_id).replace(/[^A-Za-z0-9]/g,"").slice(-10).toUpperCase()}`;await db.batch([db.prepare("INSERT OR IGNORE INTO training_completion_certificates (programme_id,booking_id,certificate_number,status,payload_json,generated_at) VALUES (?,?,?,'generated',?,?)").bind(row.programme_id,row.booking_id,certificateNumber,JSON.stringify({programmeId:row.programme_id,bookingId:row.booking_id,customerId:row.customer_id,planCode:row.plan_code,planName:row.plan_name,terminalState:"CLOSED"}),now),...(["push","whatsapp"] as const).map(channel=>db.prepare("INSERT INTO training_customer_notifications (id,programme_id,booking_id,customer_id,channel,template_code,payload_json,status,created_at) VALUES (?,?,?,?,?,'training_review_and_certificate',?,'queued',?)").bind(crypto.randomUUID(),row.programme_id,row.booking_id,row.customer_id,channel,JSON.stringify({reviewRequested:true,certificateNumber,programmeStatus:"CLOSED"}),now))]);return{certificateNumber,reviewDispatched:true};}

export async function mutateTrainingSession(db:D1Database,input:TrainingSessionMutation){await ensureTrainingSessionLifecycleTables(db);if(!input.sessionId||!input.idempotencyKey||!input.action)throw new Response("Session, action and idempotency key are required",{status:400});const prior=await duplicate(db,input.idempotencyKey,input.sessionId,input.action);if(prior)return{duplicatePrevented:true,sessionId:String(prior.session_id),eventType:String(prior.event_type),detail:parse(prior.detail_json,{})};const row=await sessionRow(db,input.sessionId);if(!row)throw new Response("Training session not found",{status:404});const current=String(row.status),now=Date.now();const requireState=(allowed:string[])=>{if(!allowed.includes(current))throw new Response(`Training session cannot ${input.action} from ${current}`,{status:409});};
 if(input.action==="accept"){requireState(["scheduled"]);await db.prepare("UPDATE training_sessions SET status='accepted',updated_at=? WHERE id=?").bind(now,row.id).run();await event(db,row,input,{from:current,to:"accepted"});return{duplicatePrevented:false,status:"accepted"};}
 if(input.action==="on_the_way"){requireState(["accepted"]);await db.prepare("UPDATE training_sessions SET status='on_the_way',updated_at=? WHERE id=?").bind(now,row.id).run();await event(db,row,input,{from:current,to:"on_the_way"});return{duplicatePrevented:false,status:"on_the_way"};}
 if(input.action==="arrive"){requireState(["on_the_way"]);const geofence=await assertArrivalGeofence(db,row,input);await db.prepare("UPDATE training_sessions SET status='arrived',updated_at=? WHERE id=?").bind(now,row.id).run();await event(db,row,input,{from:current,to:"arrived",geofence});return{duplicatePrevented:false,status:"arrived",geofence};}
 if(input.action==="start"){requireState(["arrived"]);await db.prepare("UPDATE training_sessions SET status='in_session',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").bind(now,now,row.id).run();await recalcProgramme(db,String(row.programme_id));await event(db,row,input,{from:current,to:"in_session"});return{duplicatePrevented:false,status:"in_session"};}
 if(input.action==="save_report"){requireState(["arrived","in_session"]);const report=input.report??{};await db.prepare("UPDATE training_sessions SET attendance_json=?,homework_json=?,progress_json=?,evidence_json=?,updated_at=? WHERE id=?").bind(JSON.stringify(report.attendance??parse(row.attendance_json,{})),JSON.stringify({text:String(report.homework??parse<Record<string,unknown>>(row.homework_json,{}).text??"")}),JSON.stringify(report.progress??parse(row.progress_json,{})),JSON.stringify(report.evidenceRefs??parse(row.evidence_json,[])),now,row.id).run();await event(db,row,input,{saved:true});return{duplicatePrevented:false,status:current,reportSaved:true};}
 if(input.action==="owner_handover"){requireState(["in_session"]);const minutes=Math.floor(Number(input.ownerHandoverMinutes));if(!Number.isFinite(minutes)||minutes<15)throw new Response("Owner Handover must record at least 15 minutes before session close",{status:409});await db.prepare("INSERT INTO training_owner_handover (session_id,programme_id,booking_id,duration_minutes,completed_by,completed_at) VALUES (?,?,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET duration_minutes=excluded.duration_minutes,completed_by=excluded.completed_by,completed_at=excluded.completed_at").bind(row.id,row.programme_id,row.booking_id,minutes,input.actorId,now).run();await event(db,row,input,{phase:"owner_handover",durationMinutes:minutes,minimumMinutes:15,completed:true});return{duplicatePrevented:false,status:"in_session",ownerHandover:{durationMinutes:minutes,completed:true}};}
 if(input.action==="complete"){requireState(["in_session"]);await assertFinalBalancePaid(db,row);const handover=await db.prepare("SELECT duration_minutes,completed_at FROM training_owner_handover WHERE session_id=?").bind(row.id).first<Row>();if(!handover||Number(handover.duration_minutes)<15)throw new Response("Complete the mandatory 15-minute Owner Handover phase before closing the session",{status:409});const report=input.report??{attendance:parse(row.attendance_json,{}),homework:String(parse<Record<string,unknown>>(row.homework_json,{}).text||""),progress:parse(row.progress_json,{}),evidenceRefs:parse(row.evidence_json,[])};const problem=reportProblem(report);if(problem)throw new Response(problem,{status:409});const refs=report.evidenceRefs??[];const evidence=await secureEvidenceReady(db,row,refs);if(!evidence.ready)throw new Response(evidence.reason||"Secure Training evidence is not ready",{status:409});await db.batch([db.prepare("UPDATE training_sessions SET status='completed',attendance_json=?,homework_json=?,progress_json=?,evidence_json=?,completed_at=?,updated_at=? WHERE id=?").bind(JSON.stringify(report.attendance),JSON.stringify({text:String(report.homework)}),JSON.stringify(report.progress),JSON.stringify(refs),now,now,row.id),db.prepare("INSERT OR IGNORE INTO training_session_consumptions (session_id,programme_id,booking_id,actor_id,consumed_at) VALUES (?,?,?,?,?)").bind(row.id,row.programme_id,row.booking_id,input.actorId,now),db.prepare("UPDATE scheduling_reservations SET status='completed' WHERE id=?").bind(row.schedule_reservation_id)]);const nextSession=await unlockNextSession(db,row,now),programme=await recalcProgramme(db,String(row.programme_id)),closure=await closeProgrammeArtifacts(db,row,programme);await event(db,row,input,{from:current,to:"completed",consumedExactlyOnce:true,evidenceRefs:refs,ownerHandoverMinutes:Number(handover.duration_minutes),nextSession,programme,closure});return{duplicatePrevented:false,status:"completed",consumedExactlyOnce:true,nextSession,programme,closure};}
 if(input.action==="request_reschedule"){requireState(["scheduled","accepted","on_the_way","arrived"]);const reason=String(input.reason||"").trim();if(reason.length<8)throw new Response("Reschedule request requires a clear reason",{status:400});const caseId=await recovery(db,row,"reschedule",reason,input.actorId);await db.prepare("UPDATE training_sessions SET status='reschedule_requested',updated_at=? WHERE id=?").bind(now,row.id).run();await event(db,row,input,{from:current,to:"reschedule_requested",caseId,reason});return{duplicatePrevented:false,status:"reschedule_requested",caseId};}
 if(input.action==="no_show"){requireState(["scheduled","accepted","on_the_way","arrived"]);const reason=String(input.reason||"").trim();if(reason.length<8)throw new Response("No-show requires a clear reason",{status:400});if(!input.staffOverride&&now<new Date(String(row.scheduled_start)).getTime()+15*60_000)throw new Response("Provider no-show can only be recorded after the session start grace period",{status:409});const caseId=await recovery(db,row,"no_show",reason,input.actorId,{consumption:"pending_policy"});await db.prepare("UPDATE training_sessions SET status='no_show',updated_at=? WHERE id=?").bind(now,row.id).run();await db.prepare("UPDATE scheduling_reservations SET status='no_show' WHERE id=?").bind(row.schedule_reservation_id).run();const nextSession=await unlockNextSession(db,row,now),programme=await recalcProgramme(db,String(row.programme_id));await event(db,row,input,{from:current,to:"no_show",caseId,consumption:"not_automatic",nextSession,programme});return{duplicatePrevented:false,status:"no_show",caseId,consumption:"pending_policy",nextSession,programme};}
 if(input.action==="reschedule"){if(!input.staffOverride)throw new Response("Rescheduling a canonical Training session requires staff booking permission",{status:403});requireState(["reschedule_requested","scheduled","accepted"]);const start=String(input.newStart||""),end=String(input.newEnd||""),startMs=new Date(start).getTime(),endMs=new Date(end).getTime();if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||endMs<=startMs||startMs<=now)throw new Response("A valid future Training session window is required",{status:400});const conflict=await providerConflict(db,String(row.provider_id),String(row.zone_id||""),start,end,String(row.schedule_reservation_id));if(conflict.conflict)throw new Response(conflict.reason||"Trainer is unavailable",{status:409});await db.batch([db.prepare("UPDATE training_sessions SET scheduled_start=?,scheduled_end=?,status='scheduled',started_at=NULL,completed_at=NULL,updated_at=? WHERE id=?").bind(start,end,now,row.id),db.prepare("UPDATE scheduling_reservations SET scheduled_start=?,scheduled_end=?,status='assigned' WHERE id=?").bind(start,end,row.schedule_reservation_id),db.prepare("UPDATE training_session_recovery_cases SET status='resolved',new_start=?,new_end=?,updated_at=? WHERE session_id=? AND recovery_type='reschedule' AND status='open'").bind(start,end,now,row.id)]);await recalcProgramme(db,String(row.programme_id));await event(db,row,input,{from:current,to:"scheduled",newStart:start,newEnd:end});return{duplicatePrevented:false,status:"scheduled",scheduledStart:start,scheduledEnd:end};}
 if(input.action==="replace_provider"){if(!input.staffOverride)throw new Response("Trainer replacement requires staff booking permission",{status:403});requireState(["scheduled","accepted","reschedule_requested"]);const newProviderId=String(input.newProviderId||"").trim(),reason=String(input.reason||"").trim();if(!newProviderId||reason.length<8)throw new Response("Replacement trainer and clear reason are required",{status:400});const provider=await getGovernedProvider(db,newProviderId);if(!provider||!provider.live||!provider.services.includes("dog_training")||!provider.zones.includes(String(row.zone_id||"")))throw new Response("Replacement trainer is not eligible for this Training session",{status:409});const conflict=await providerConflict(db,newProviderId,String(row.zone_id||""),String(row.scheduled_start),String(row.scheduled_end),String(row.schedule_reservation_id));if(conflict.conflict)throw new Response(conflict.reason||"Replacement trainer is unavailable",{status:409});const caseId=await recovery(db,row,"replacement",reason,input.actorId,{fromProviderId:row.provider_id,toProviderId:newProviderId});await db.batch([db.prepare("UPDATE training_sessions SET provider_id=?,status='scheduled',updated_at=? WHERE id=?").bind(newProviderId,now,row.id),db.prepare("UPDATE scheduling_reservations SET provider_id=?,status='assigned' WHERE id=?").bind(newProviderId,row.schedule_reservation_id),db.prepare("UPDATE training_session_recovery_cases SET status='resolved',replacement_provider_id=?,updated_at=? WHERE id=?").bind(newProviderId,now,caseId)]);await event(db,row,input,{fromProviderId:row.provider_id,toProviderId:newProviderId,reason,caseId});return{duplicatePrevented:false,status:"scheduled",providerId:newProviderId,caseId};}
 if(input.action==="cancel_session"){if(!input.staffOverride)throw new Response("Training session cancellation requires staff booking permission",{status:403});requireState(["scheduled","accepted","reschedule_requested","locked"]);const reason=String(input.reason||"").trim();if(reason.length<8)throw new Response("Session cancellation requires a clear reason",{status:400});const caseId=await recovery(db,row,"cancel",reason,input.actorId,{consumption:"not_consumed"});await db.batch([db.prepare("UPDATE training_sessions SET status='cancelled',updated_at=? WHERE id=?").bind(now,row.id),db.prepare("UPDATE scheduling_reservations SET status='cancelled' WHERE id=?").bind(row.schedule_reservation_id)]);const nextSession=await unlockNextSession(db,row,now),programme=await recalcProgramme(db,String(row.programme_id));await event(db,row,input,{from:current,to:"cancelled",reason,caseId,consumption:"not_consumed",nextSession,programme});return{duplicatePrevented:false,status:"cancelled",caseId,nextSession,programme};}
 throw new Response("Unsupported Training session action",{status:400});}
