import {customerDataAccessResolver} from './purpose-based-access';
import {resolveBookingDoorstep} from './booking-doorstep';
import {availableTrainingArrivalSimulation} from './training-arrival-test-approval';
import {projectTrainingHomework} from './training-homework-receipt';
type Row=Record<string,unknown>;
export function trainingHandoverReminder(session:Row,completedAt:number|null,now=Date.now()){const started=Number(session.started_at),duration=Date.parse(String(session.scheduled_end))-Date.parse(String(session.scheduled_start)),remindAfter=Math.max(0,(Number.isFinite(duration)?duration:3600000)-600000),remindAt=started>0?started+remindAfter:null;return{completed:Boolean(completedAt),completedAt,remindAt,reminderDue:session.status==='in_session'&&!completedAt&&remindAt!==null&&now>=remindAt,sessionStartedAt:started>0?started:null};}
export async function trainingSessionContext(db:D1Database,input:{request:Request;session:Row;actor:{email:string;roleCode:string;permissions?:readonly string[]}}){
 const s=input.session,booking=await db.prepare("SELECT customer_id,provider_id,status,city_id,scheduled_start FROM canonical_bookings WHERE id=? AND service_code='dog_training'").bind(s.booking_id).first<Row>();
 if(!booking||['cancelled','completed','refunded','failed','expired'].includes(String(booking.status)))return{sessionId:String(s.id),navigation:{available:false,destination:null,mapsUrl:null,reason:'booking_inactive'},handover:trainingHandoverReminder(s,null),arrival:{thresholdMeters:500,simulation:{eligible:false,approvalId:null,label:null},evidence:{mode:'unavailable',simulated:false,physicalVisitVerified:null}},homeworkReceipt:await projectTrainingHomework(db,s,String(booking?.customer_id||''))};
 const access=await customerDataAccessResolver(db,{serviceCode:'dog_training',cityId:String(booking.city_id)}),view=access.view({actor:input.actor,subject:{customerId:String(booking.customer_id),name:String(s.customer_name||"Customer"),address:{line1:null}},purpose:'service_delivery',assignment:{type:'booking',id:String(s.booking_id),assignedTo:input.actor.email,status:String(booking.status),scheduledStart:Date.parse(String(s.scheduled_start))}});
 const stateAllows=['accepted','on_the_way','arrived','in_session'].includes(String(s.status)),target=stateAllows&&view.address.precision==='full'?await resolveBookingDoorstep(db,String(s.booking_id)):null;
 const arrivalEvent=await db.prepare("SELECT detail_json FROM training_session_events WHERE session_id=? AND event_type='arrive' ORDER BY created_at DESC,rowid DESC LIMIT 1").bind(s.id).first<Row>();let arrivalDetail:Row={};try{arrivalDetail=JSON.parse(String(arrivalEvent?.detail_json||'{}'))}catch{}const geofence=arrivalDetail.geofence as Row|undefined,simulated=geofence?.simulation===true;
 const arrivalEvidence={mode:String(geofence?.evidenceMode||'unavailable'),simulated,physicalVisitVerified:simulated?false:null};
 const h=await db.prepare('SELECT completed_at FROM training_owner_handover WHERE session_id=?').bind(s.id).first<Row>();
 return{sessionId:String(s.id),navigation:{available:Boolean(target),destination:target,mapsUrl:target?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${target.latitude},${target.longitude}`)}`:null,reason:target?null:!stateAllows?'acceptance_required':view.address.precision!=='full'?'address_window_closed':'doorstep_missing'},handover:trainingHandoverReminder(s,h?Number(h.completed_at):null),arrival:{thresholdMeters:500,evidence:arrivalEvidence,simulation:await availableTrainingArrivalSimulation(db,{request:input.request,sessionId:String(s.id),providerId:String(s.provider_id)})},homeworkReceipt:await projectTrainingHomework(db,s,String(booking.customer_id))};
}
