import{ensureWalkingLifecycleTables,getWalkingBooking}from"./walking-lifecycle";

type Row=Record<string,unknown>;
export type WalkingProofAction="request_upload"|"sandbox_finalize_media"|"record_media_scan"|"revoke_media"|"record_incident"|"resolve_incident"|"acknowledge_incident";
export type WalkingProofInput={bookingId:string;action:WalkingProofAction;actorId:string;idempotencyKey:string;providerId?:string;purpose?:"walk_photo"|"handover_photo"|"route_proof"|"incident_evidence";mediaId?:string;mimeType?:string;sizeBytes?:number;sha256?:string;scanResult?:"clean"|"blocked";incidentSeverity?:"attention"|"urgent"|"emergency";incidentType?:string;description?:string;resolution?:string};
const allowedMime=new Set(["image/jpeg","image/png","image/webp"]),maxBytes=8*1024*1024;

export async function ensureWalkingProofTables(db:D1Database){await ensureWalkingLifecycleTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS walking_proof_action_keys (idempotency_key TEXT PRIMARY KEY,booking_id TEXT NOT NULL,action TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS walking_media_records (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,purpose TEXT NOT NULL,mime_type TEXT,size_bytes INTEGER,sha256 TEXT,object_key TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'upload_granted',scan_status TEXT NOT NULL DEFAULT 'pending',upload_token_hash TEXT NOT NULL,upload_expires_at INTEGER NOT NULL,retention_until INTEGER NOT NULL,revoked_at INTEGER,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE INDEX IF NOT EXISTS idx_walking_media_booking ON walking_media_records(booking_id,provider_id,purpose,state)"),
 db.prepare("CREATE TABLE IF NOT EXISTS walking_incidents (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,provider_id TEXT NOT NULL,severity TEXT NOT NULL,incident_type TEXT NOT NULL,description TEXT NOT NULL,evidence_media_id TEXT,status TEXT NOT NULL DEFAULT 'open',customer_acknowledged_at INTEGER,resolution TEXT,resolved_by TEXT,resolved_at INTEGER,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS walking_ops_notifications (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,incident_id TEXT,kind TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 ]);}
function parse(value:unknown){try{return JSON.parse(String(value??"{}"))as Record<string,unknown>}catch{return{}}}
async function prior(db:D1Database,key:string){const row=await db.prepare("SELECT result_json FROM walking_proof_action_keys WHERE idempotency_key=?").bind(key).first<Row>();return row?parse(row.result_json):null;}
async function remember(db:D1Database,input:WalkingProofInput,result:unknown){await db.prepare("INSERT INTO walking_proof_action_keys (idempotency_key,booking_id,action,result_json,created_at) VALUES (?,?,?,?,?)").bind(input.idempotencyKey,input.bookingId,input.action,JSON.stringify(result),Date.now()).run();return result;}
async function context(db:D1Database,input:WalkingProofInput){await ensureWalkingProofTables(db);const booking=await getWalkingBooking(db,input.bookingId);if(!booking)throw new Response("Walking booking not found",{status:404});const providerId=String(booking.provider_id);if(input.providerId&&input.providerId!==providerId)throw new Response("Walking proof provider does not own this booking",{status:403});return{booking,providerId};}
export async function listWalkingProof(db:D1Database,bookingId:string){await ensureWalkingProofTables(db);const media=await db.prepare("SELECT id,booking_id,provider_id,purpose,mime_type,size_bytes,sha256,state,scan_status,upload_expires_at,retention_until,created_at,updated_at FROM walking_media_records WHERE booking_id=? ORDER BY created_at DESC").bind(bookingId).all<Row>(),incidents=await db.prepare("SELECT * FROM walking_incidents WHERE booking_id=? ORDER BY created_at DESC").bind(bookingId).all<Row>();return{media:media.results,incidents:incidents.results,storageMode:"metadata_only_uat",scannerMode:"manual_uat_callback",liveGps:false};}

export async function mutateWalkingProof(db:D1Database,input:WalkingProofInput){if(!input.bookingId||!input.action||!input.actorId||!input.idempotencyKey)throw new Response("Walking booking, action, actor and idempotency key are required",{status:400});const old=await prior(db,input.idempotencyKey);if(old)return{...old,duplicatePrevented:true};const{booking,providerId}=await context(db,input),now=Date.now();
 if(input.action==="request_upload"){const purpose=String(input.purpose||"");if(!["walk_photo","handover_photo","route_proof","incident_evidence"].includes(purpose))throw new Response("Unsupported Walking proof purpose",{status:400});if(!["assigned","in_progress","completed"].includes(String(booking.status)))throw new Response("Walking proof is available only for an active or completed booking",{status:409});const id=`WM-${crypto.randomUUID()}`,token=crypto.randomUUID()+crypto.randomUUID(),hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)),tokenHash=Array.from(new Uint8Array(hash)).map(value=>value.toString(16).padStart(2,"0")).join(""),expires=now+10*60_000,retention=now+30*24*60*60_000,objectKey=`private/walking/${input.bookingId}/${providerId}/${id}`;await db.prepare("INSERT INTO walking_media_records (id,booking_id,provider_id,purpose,object_key,state,scan_status,upload_token_hash,upload_expires_at,retention_until,created_by,created_at,updated_at) VALUES (?,?,?,?,?,'upload_granted','pending',?,?,?,?,?,?)").bind(id,input.bookingId,providerId,purpose,objectKey,tokenHash,expires,retention,input.actorId,now,now).run();return remember(db,input,{mediaId:id,uploadGrant:token,expiresAt:expires,objectKeyOpaque:true,private:true,storageConnected:false});}
 if(input.action==="sandbox_finalize_media"){const media=await db.prepare("SELECT * FROM walking_media_records WHERE id=? AND booking_id=? AND provider_id=?").bind(input.mediaId,input.bookingId,providerId).first<Row>();if(!media)throw new Response("Walking media grant not found for this booking/provider",{status:404});if(Number(media.upload_expires_at)<now)throw new Response("Walking media upload grant expired",{status:409});const mime=String(input.mimeType||""),size=Number(input.sizeBytes),sha=String(input.sha256||"").toLowerCase();if(!allowedMime.has(mime))throw new Response("Walking proof MIME type is not allowed",{status:409});if(!Number.isFinite(size)||size<1||size>maxBytes)throw new Response("Walking proof file size is outside the 8 MB limit",{status:409});if(!/^[a-f0-9]{64}$/.test(sha))throw new Response("Walking proof requires a SHA-256 checksum",{status:409});await db.prepare("UPDATE walking_media_records SET mime_type=?,size_bytes=?,sha256=?,state='quarantined',scan_status='pending',updated_at=? WHERE id=?").bind(mime,size,sha,now,input.mediaId).run();return remember(db,input,{mediaId:input.mediaId,state:"quarantined",scanStatus:"pending",private:true});}
 if(input.action==="record_media_scan"){const media=await db.prepare("SELECT * FROM walking_media_records WHERE id=? AND booking_id=?").bind(input.mediaId,input.bookingId).first<Row>();if(!media||String(media.state)!=="quarantined")throw new Response("Walking media must be quarantined before scan result",{status:409});const clean=input.scanResult==="clean",state=clean?"ready":"blocked";await db.prepare("UPDATE walking_media_records SET state=?,scan_status=?,updated_at=? WHERE id=?").bind(state,clean?"clean":"blocked",now,input.mediaId).run();return remember(db,input,{mediaId:input.mediaId,state,scanStatus:clean?"clean":"blocked",scannerConnected:false});}
 if(input.action==="revoke_media"){await db.prepare("UPDATE walking_media_records SET state='revoked',revoked_at=?,updated_at=? WHERE id=? AND booking_id=?").bind(now,now,input.mediaId,input.bookingId).run();return remember(db,input,{mediaId:input.mediaId,state:"revoked"});}
 if(input.action==="record_incident"){const severity=String(input.incidentSeverity||""),type=String(input.incidentType||"").trim(),description=String(input.description||"").trim();if(!["attention","urgent","emergency"].includes(severity)||type.length<3||description.length<8)throw new Response("Walking incident requires severity, type and description",{status:400});let evidenceId:String|undefined;if(input.mediaId){const media=await db.prepare("SELECT id,purpose,state,scan_status FROM walking_media_records WHERE id=? AND booking_id=? AND provider_id=?").bind(input.mediaId,input.bookingId,providerId).first<Row>();if(!media||String(media.purpose)!=="incident_evidence"||String(media.state)!=="ready"||String(media.scan_status)!=="clean")throw new Response("Walking incident evidence must be clean ready exact-purpose proof",{status:409});evidenceId=String(media.id);}const id=`WI-${crypto.randomUUID()}`;await db.batch([db.prepare("INSERT INTO walking_incidents (id,booking_id,provider_id,severity,incident_type,description,evidence_media_id,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'open',?,?,?)").bind(id,input.bookingId,providerId,severity,type,description,evidenceId??null,input.actorId,now,now),db.prepare("INSERT INTO walking_ops_notifications (id,booking_id,incident_id,kind,severity,status,detail_json,created_at,updated_at) VALUES (?,?,?,'incident',?,'open',?,?,?)").bind(crypto.randomUUID(),input.bookingId,id,severity,JSON.stringify({incidentType:type,noAutomaticRefund:true,noAutomaticPayoutChange:true}),now,now)]);return remember(db,input,{incidentId:id,status:"open",severity,noAutomaticRefund:true,noAutomaticPayoutChange:true});}
 if(input.action==="acknowledge_incident"){const incident=await db.prepare("SELECT * FROM walking_incidents WHERE id=? AND booking_id=?").bind(input.mediaId,input.bookingId).first<Row>();if(!incident)throw new Response("Walking incident not found",{status:404});await db.prepare("UPDATE walking_incidents SET customer_acknowledged_at=?,updated_at=? WHERE id=?").bind(now,now,incident.id).run();return remember(db,input,{incidentId:incident.id,status:String(incident.status),customerAcknowledged:true,moneyChanged:false});}
 if(input.action==="resolve_incident"){const resolution=String(input.resolution||"").trim();if(resolution.length<5)throw new Response("Walking incident resolution detail is required",{status:400});const incident=await db.prepare("SELECT * FROM walking_incidents WHERE id=? AND booking_id=?").bind(input.mediaId,input.bookingId).first<Row>();if(!incident)throw new Response("Walking incident not found",{status:404});await db.batch([db.prepare("UPDATE walking_incidents SET status='resolved',resolution=?,resolved_by=?,resolved_at=?,updated_at=? WHERE id=?").bind(resolution,input.actorId,now,now,incident.id),db.prepare("UPDATE walking_ops_notifications SET status='resolved',updated_at=? WHERE incident_id=? AND kind='incident'").bind(now,incident.id)]);return remember(db,input,{incidentId:incident.id,status:"resolved",moneyChanged:false});}
 throw new Response("Unsupported Walking proof action",{status:400});}
