import{createAssignmentOffer,loadGovernedProviders}from"./provider-capacity-governance";
import{ensureWalkingFinanceTables}from"./walking-finance-governance";
import{ensureWalkingProofTables}from"./walking-proof-governance";

type Row=Record<string,unknown>;
export type WalkingOpsAction="assign_replacement"|"close_recovery"|"add_note";
export type WalkingOpsInput={bookingId:string;action:WalkingOpsAction;actorId:string;idempotencyKey:string;providerId?:string;note?:string};

export async function ensureWalkingOpsTables(db:D1Database){await ensureWalkingFinanceTables(db);await ensureWalkingProofTables(db);await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS walking_ops_action_keys (idempotency_key TEXT PRIMARY KEY,booking_id TEXT NOT NULL,action TEXT NOT NULL,result_json TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS walking_ops_notes (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,note TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL)"),
 ]);}
function parse<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??""))as T}catch{return fallback}}
async function prior(db:D1Database,key:string){const row=await db.prepare("SELECT result_json FROM walking_ops_action_keys WHERE idempotency_key=?").bind(key).first<Row>();return row?parse<Record<string,unknown>>(row.result_json,{}):null;}
async function remember(db:D1Database,input:WalkingOpsInput,result:unknown){await db.prepare("INSERT INTO walking_ops_action_keys (idempotency_key,booking_id,action,result_json,created_at) VALUES (?,?,?,?,?)").bind(input.idempotencyKey,input.bookingId,input.action,JSON.stringify(result),Date.now()).run();return result;}
async function booking(db:D1Database,id:string){await ensureWalkingOpsTables(db);const row=await db.prepare("SELECT b.*,w.status work_order_status,p.status payment_status FROM canonical_bookings b LEFT JOIN provider_work_orders w ON w.booking_id=b.id LEFT JOIN booking_payments p ON p.booking_id=b.id WHERE b.id=? AND b.service_code='dog_walking'").bind(id).first<Row>();if(!row)throw new Response("Canonical Walking booking not found",{status:404});return row;}
function overlaps(aStart:number,aEnd:number,bStart:number,bEnd:number){return aStart<bEnd&&bStart<aEnd;}

export async function walkingRecoveryCandidates(db:D1Database,bookingId:string){const b=await booking(db,bookingId),failed=String(b.provider_id),start=String(b.scheduled_start),end=String(b.scheduled_end),providers=await loadGovernedProviders(db,String(b.city_id),String(b.zone_id),"dog_walking",new Date(start)),out=[];for(const provider of providers){if(provider.id===failed)continue;const blocked=await db.prepare("SELECT id FROM provider_unavailability WHERE provider_id=? AND status='active' AND starts_at<? AND ends_at>? LIMIT 1").bind(provider.id,end,start).first<Row>();if(blocked)continue;const existing=await db.prepare("SELECT scheduled_start,scheduled_end FROM scheduling_reservations WHERE provider_id=? AND status NOT IN ('cancelled','completed')").bind(provider.id).all<Row>(),buffer=(provider.travelBufferMinutes??20)*60_000,a=new Date(start).getTime(),z=new Date(end).getTime();if(existing.results.some(row=>overlaps(a-buffer,z+buffer,new Date(String(row.scheduled_start)).getTime(),new Date(String(row.scheduled_end)).getTime())))continue;out.push(provider);}return out.sort((a,b)=>(b.qualityScore??0)-(a.qualityScore??0));}

export async function listWalkingOpsQueue(db:D1Database){await ensureWalkingOpsTables(db);const bookings=await db.prepare("SELECT b.*,w.status work_order_status,p.status payment_status FROM canonical_bookings b LEFT JOIN provider_work_orders w ON w.booking_id=b.id LEFT JOIN booking_payments p ON p.booking_id=b.id WHERE b.service_code='dog_walking' ORDER BY b.updated_at DESC").all<Row>(),items=[];for(const b of bookings.results){const exceptions=[] as Array<{code:string;severity:string;detail?:unknown}>;const recovery=await db.prepare("SELECT * FROM walking_recovery_cases WHERE booking_id=? AND status!='resolved' ORDER BY opened_at DESC LIMIT 1").bind(b.id).first<Row>();if(recovery)exceptions.push({code:"walker_recovery",severity:"urgent",detail:{recoveryId:recovery.id,status:recovery.status,failedProviderId:recovery.failed_provider_id,replacementProviderId:recovery.replacement_provider_id}});const incident=await db.prepare("SELECT * FROM walking_incidents WHERE booking_id=? AND status='open' ORDER BY created_at DESC LIMIT 1").bind(b.id).first<Row>();if(incident)exceptions.push({code:"incident",severity:String(incident.severity),detail:{incidentId:incident.id,type:incident.incident_type}});const cancel=await db.prepare("SELECT id FROM walking_cancellation_requests WHERE booking_id=? AND status='policy_review_required' LIMIT 1").bind(b.id).first<Row>();if(cancel)exceptions.push({code:"cancellation_policy_review",severity:"attention"});const change=await db.prepare("SELECT id FROM walking_reschedule_requests WHERE booking_id=? AND status='commercial_quote_required' LIMIT 1").bind(b.id).first<Row>();if(change)exceptions.push({code:"reschedule_quote_required",severity:"attention"});const refund=await db.prepare("SELECT id FROM walking_refund_ledger WHERE booking_id=? AND status='sandbox_pending' LIMIT 1").bind(b.id).first<Row>();if(refund)exceptions.push({code:"refund_pending",severity:"attention"});const blockedMedia=await db.prepare("SELECT COUNT(*) count FROM walking_media_records WHERE booking_id=? AND state='blocked'").bind(b.id).first<Row>();if(Number(blockedMedia?.count||0)>0)exceptions.push({code:"blocked_media",severity:"attention",detail:{count:Number(blockedMedia?.count)}});if(String(b.status)==="completed"){const settlement=await db.prepare("SELECT approval_status,tax_status FROM walking_settlement_ledger WHERE booking_id=?").bind(b.id).first<Row>();if(!settlement||String(settlement.approval_status)!=="ready")exceptions.push({code:"settlement_not_ready",severity:"attention",detail:{tax:String(settlement?.tax_status||"configuration_required")}});}if(exceptions.length)items.push({bookingId:String(b.id),customerId:String(b.customer_id),providerId:String(b.provider_id),scheduleGroupId:String(b.schedule_group_id),scheduledStart:String(b.scheduled_start),scheduledEnd:String(b.scheduled_end),bookingStatus:String(b.status),paymentStatus:String(b.payment_status||""),exceptions});}return items;}

export async function mutateWalkingOps(db:D1Database,input:WalkingOpsInput){if(!input.bookingId||!input.action||!input.actorId||!input.idempotencyKey)throw new Response("Walking booking, action, actor and idempotency key are required",{status:400});const old=await prior(db,input.idempotencyKey);if(old)return{...old,duplicatePrevented:true};const b=await booking(db,input.bookingId),now=Date.now(),groupId=String(b.schedule_group_id);
 if(input.action==="add_note"){const note=String(input.note||"").trim();if(note.length<4)throw new Response("Walking Operations note is too short",{status:400});const id=crypto.randomUUID();await db.prepare("INSERT INTO walking_ops_notes (id,booking_id,note,actor_id,created_at) VALUES (?,?,?,?,?)").bind(id,input.bookingId,note,input.actorId,now).run();return remember(db,input,{bookingId:input.bookingId,noteId:id,status:"recorded"});}
 if(input.action==="assign_replacement"){const recovery=await db.prepare("SELECT * FROM walking_recovery_cases WHERE booking_id=? AND status='ops_escalation' ORDER BY opened_at DESC LIMIT 1").bind(input.bookingId).first<Row>();if(!recovery)throw new Response("No Walking recovery case is awaiting replacement",{status:409});const providerId=String(input.providerId||""),candidates=await walkingRecoveryCandidates(db,input.bookingId);if(!providerId||!candidates.some(provider=>provider.id===providerId))throw new Response("Replacement walker must be exact-window eligible",{status:409});const provider=candidates.find(item=>item.id===providerId)!,reservationId=`${groupId}_${provider.id}_recovery_${now}`;await db.batch([db.prepare("UPDATE scheduling_reservations SET status='cancelled' WHERE group_id=? AND status!='completed'").bind(groupId),db.prepare("INSERT INTO scheduling_reservations (id,group_id,provider_id,service_code,city_id,zone_id,customer_id,pet_ids_json,scheduled_start,scheduled_end,capacity_units,occurrence_number,care_mode,status,explanation_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,NULL,'assigned',?,?)").bind(reservationId,groupId,provider.id,"dog_walking",b.city_id,b.zone_id,b.customer_id,b.pet_ids_json,b.scheduled_start,b.scheduled_end,parse<unknown[]>(b.pet_ids_json,[]).length,JSON.stringify(["Walking Gate 5 replacement","Exact paid window preserved"]),now),db.prepare("UPDATE scheduling_assignment_decisions SET selected_provider_id=?,status='assigned',actor_id=?,reason='Walking Ops replacement offered',updated_at=? WHERE group_id=?").bind(provider.id,input.actorId,now,groupId),db.prepare("UPDATE canonical_bookings SET provider_id=?,status='reassignment_offered',updated_at=? WHERE id=?").bind(provider.id,now,input.bookingId),db.prepare("UPDATE provider_work_orders SET provider_id=?,provider_name=?,provider_model=?,status='reassignment_offered',updated_at=? WHERE booking_id=?").bind(provider.id,provider.name,provider.model,now,input.bookingId),db.prepare("UPDATE walking_recovery_cases SET replacement_provider_id=?,status='replacement_offered',updated_at=? WHERE id=?").bind(provider.id,now,recovery.id)]);const offer=await createAssignmentOffer(db,{groupId,bookingId:input.bookingId,providerId:provider.id,attemptNo:2});return remember(db,input,{bookingId:input.bookingId,recoveryId:recovery.id,status:"replacement_offered",providerId:provider.id,offer,bookingPreserved:true,paidWindowPreserved:true});}
 if(input.action==="close_recovery"){const recovery=await db.prepare("SELECT * FROM walking_recovery_cases WHERE booking_id=? AND status='replacement_offered' ORDER BY opened_at DESC LIMIT 1").bind(input.bookingId).first<Row>();if(!recovery)throw new Response("No Walking replacement offer is ready for closure",{status:409});const current=await booking(db,input.bookingId),offer=await db.prepare("SELECT * FROM provider_assignment_offers WHERE group_id=?").bind(groupId).first<Row>();if(String(current.status)!=="assigned"||!offer||String(offer.status)!=="accepted"||String(offer.provider_id)!==String(recovery.replacement_provider_id))throw new Response("Replacement walker must accept before Operations closes recovery",{status:409});await db.batch([db.prepare("UPDATE walking_recovery_cases SET status='resolved',resolved_at=?,updated_at=? WHERE id=?").bind(now,now,recovery.id),db.prepare("UPDATE provider_work_orders SET status='assigned',updated_at=? WHERE booking_id=?").bind(now,input.bookingId),db.prepare("UPDATE scheduling_assignment_decisions SET status='assigned',selected_provider_id=?,actor_id=?,reason='Walking recovery accepted and normalized',updated_at=? WHERE group_id=?").bind(current.provider_id,input.actorId,now,groupId),db.prepare("UPDATE scheduling_reservations SET status='assigned' WHERE group_id=? AND provider_id=? AND status!='cancelled'").bind(groupId,current.provider_id)]);return remember(db,input,{bookingId:input.bookingId,recoveryId:recovery.id,status:"resolved",providerId:String(current.provider_id),bookingPreserved:true,paidWindowPreserved:true});}
 throw new Response("Unsupported Walking Operations action",{status:400});}
