import{database}from"../../../lib/server-auth";
import{resolvePlatformSession}from"../../../lib/platform-session";
import{addOwnedProviderDocument,addOwnedProviderProfileMedia,acceptOwnedProviderSla,createOwnedProviderApplication,providerOnboardingSelfServiceSnapshot,saveOwnedProviderProfile,scoreOwnedProviderQuiz,submitOwnedProviderApplication,updateOwnedActivatedProfile}from"../../../lib/provider-onboarding-self-service";
import{generateProviderProfileBioDraft}from"../../../lib/provider-profile-ai-bio";

type Body={action?:string;applicationId?:string;payload?:Record<string,unknown>;documentType?:string;fileRef?:string;expiresAt?:number|null;quizVersionId?:string;answers?:Record<string,string>;agreementId?:string;mediaType?:"provider_photo"|"home_photo"|"facility_photo"|"business_photo"|"reference";changes?:Record<string,unknown>;reason?:string;verticalKey?:string;cityCode?:string;displayName?:string;businessName?:string};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin provider onboarding write blocked",{status:403});}
async function providerActor(request:Request){const db=await database(),actor=await resolvePlatformSession(db,request);if(!actor)throw new Response("Provider identity session required",{status:401});if(actor.subjectType!=="provider"||actor.roleCode!=="service_provider")throw new Response("Provider identity required",{status:403});return{db,actor};}
async function audit(db:D1Database,actor:{auditId:string;roleCode:string},action:string,resourceId:string|null,outcome:string,detail:unknown={}){await db.prepare("INSERT INTO security_audit_events (id,actor_email,actor_role,action,resource_type,resource_id,outcome,detail_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),actor.auditId,actor.roleCode,action,"provider_onboarding_self_service",resourceId,outcome,JSON.stringify(detail),Date.now()).run();}
function failure(error:unknown){if(error instanceof Response)return json({error:"Provider onboarding request rejected"},error.status);return json({error:error instanceof Error?error.message:"Unable to update provider onboarding"},500);}

export async function GET(request:Request){try{const{db,actor}=await providerActor(request);const data=await providerOnboardingSelfServiceSnapshot(db,actor.subjectId);await audit(db,actor,"provider.onboarding.self_service.read",null,"allowed",{productionReady:false});return json({data});}catch(error){return failure(error);}}

export async function POST(request:Request){let db:D1Database|undefined,actor:Awaited<ReturnType<typeof resolvePlatformSession>>=null,action="unknown",resourceId:string|null=null;try{sameOrigin(request);const resolved=await providerActor(request);db=resolved.db;actor=resolved.actor;const body=await request.json() as Body;action=String(body.action||"");let data:unknown,status=200;
 if(action==="create_application"){if(!body.payload)return json({error:"Application payload is required"},400);data=await createOwnedProviderApplication(db,{providerId:actor.subjectId,actorId:actor.auditId,payload:body.payload});resourceId=(data as{ id:string}).id;status=201;}
 else if(action==="add_document"){if(!body.applicationId||!body.documentType||!body.fileRef)return json({error:"Application, document type and secure file reference are required"},400);resourceId=body.applicationId;data=await addOwnedProviderDocument(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId,documentType:body.documentType,fileRef:body.fileRef,expiresAt:body.expiresAt});status=201;}
 else if(action==="submit_application"){if(!body.applicationId)return json({error:"Application ID is required"},400);resourceId=body.applicationId;data=await submitOwnedProviderApplication(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId});}
 else if(action==="score_quiz"){if(!body.applicationId||!body.quizVersionId||!body.answers)return json({error:"Application, frozen quiz version and answers are required"},400);resourceId=body.applicationId;data=await scoreOwnedProviderQuiz(db,{providerId:actor.subjectId,applicationId:body.applicationId,quizVersionId:body.quizVersionId,answers:body.answers});status=201;}
 else if(action==="accept_sla_uat"){if(!body.applicationId||!body.agreementId)return json({error:"Application and agreement IDs are required"},400);resourceId=body.applicationId;data=await acceptOwnedProviderSla(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId,agreementId:body.agreementId});}
 else if(action==="save_profile"){if(!body.applicationId||!body.payload)return json({error:"Application ID and profile payload are required"},400);resourceId=body.applicationId;data=await saveOwnedProviderProfile(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId,payload:body.payload});}
 else if(action==="generate_profile_bio_ai"){if(!body.verticalKey)return json({error:"Vertical key is required"},400);const draft=await generateProviderProfileBioDraft({verticalKey:body.verticalKey,cityCode:body.cityCode,displayName:body.displayName,businessName:body.businessName});if(!draft.connected)return json({error:draft.reason,connected:false},503);data={bio:draft.bio,modelRef:draft.modelRef,providerRef:draft.providerRef,draftOnly:true};}
 else if(action==="add_profile_media"){if(!body.applicationId||!body.mediaType||!body.fileRef)return json({error:"Application, media type and secure file reference are required"},400);resourceId=body.applicationId;data=await addOwnedProviderProfileMedia(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId,mediaType:body.mediaType,fileRef:body.fileRef});status=201;}
 else if(action==="update_activated_profile"){if(!body.applicationId||!body.changes||!body.reason)return json({error:"Application, changes and reason are required"},400);resourceId=body.applicationId;data=await updateOwnedActivatedProfile(db,{providerId:actor.subjectId,actorId:actor.auditId,applicationId:body.applicationId,changes:body.changes,reason:body.reason});}
 else return json({error:"Unsupported provider self-service action"},400);
 await audit(db,actor,`provider.onboarding.self_service.${action}`,resourceId,"completed",{productionReady:false,marketplaceLive:false,orderEligible:false});return json({data},status);
 }catch(error){if(db&&actor)await audit(db,actor,`provider.onboarding.self_service.${action}`,resourceId,"denied",{status:error instanceof Response?error.status:500}).catch(()=>{});return failure(error);}}
