"use client";
import Link from"next/link";
import{useEffect,useState}from"react";
import{loadWalkingOpsQueue,loadWalkingRecoveryCandidates,updateWalkingOps}from"../../../../lib/walking-ops-client";

type QueueItem=Record<string,unknown>&{bookingId:string;providerId:string;bookingStatus:string;exceptions:Array<{code:string;severity:string;detail?:unknown}>};
export default function WalkingOperationsWorkspace(){const[items,setItems]=useState<QueueItem[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[candidates,setCandidates]=useState<Record<string,Array<{id:string;name:string}>>>({});
 async function refresh(){try{setError("");setItems(await loadWalkingOpsQueue() as QueueItem[])}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load Walking Operations")}}
 useEffect(()=>{let active=true;void loadWalkingOpsQueue().then(rows=>{if(active)setItems(rows as QueueItem[])}).catch(problem=>{if(active)setError(problem instanceof Error?problem.message:"Unable to load Walking Operations")});return()=>{active=false}},[]);
 async function showCandidates(bookingId:string){setBusy(bookingId);try{const rows=await loadWalkingRecoveryCandidates(bookingId);setCandidates(current=>({...current,[bookingId]:rows}))}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load recovery candidates")}finally{setBusy("")}}
 async function act(bookingId:string,action:"assign_replacement"|"close_recovery"|"add_note",providerId?:string){setBusy(bookingId);setError("");try{await updateWalkingOps({bookingId,action,providerId,idempotencyKey:`walk-ops:${bookingId}:${action}:${crypto.randomUUID()}`,note:action==="add_note"?"Operations reviewed the canonical Walking exception queue.":undefined});await refresh()}catch(problem){setError(problem instanceof Error?problem.message:"Walking Operations action failed")}finally{setBusy("")}}
 return <main style={{maxWidth:1100,margin:"0 auto",padding:24,fontFamily:"system-ui",display:"grid",gap:18}}><header><Link href="/team/operations">← Team Operations</Link><h1>Walking exception control</h1><p>One queue projects canonical booking, recovery, incident, finance, proof and settlement exceptions. Finance and proof decisions stay in their specialist modules.</p></header>{error&&<p role="alert">{error}</p>}{items.length===0?<p>No active Walking exceptions.</p>:items.map(item=><section key={item.bookingId} style={{border:"1px solid #ddd",borderRadius:16,padding:18,display:"grid",gap:10}}><div><strong>{item.bookingId}</strong> · {item.bookingStatus} · walker {item.providerId}</div><ul>{item.exceptions.map((exception,index)=><li key={`${exception.code}-${index}`}><strong>{exception.code}</strong> · {exception.severity}</li>)}</ul>{item.exceptions.some(exception=>exception.code==="walker_recovery")&&<><button disabled={busy===item.bookingId} onClick={()=>void showCandidates(item.bookingId)}>Load exact-window replacement walkers</button>{(candidates[item.bookingId]||[]).map(provider=><button key={provider.id} disabled={busy===item.bookingId} onClick={()=>void act(item.bookingId,"assign_replacement",provider.id)}>Offer same booking to {provider.name}</button>)}<button disabled={busy===item.bookingId} onClick={()=>void act(item.bookingId,"close_recovery")}>Close accepted recovery</button></>}<button disabled={busy===item.bookingId} onClick={()=>void act(item.bookingId,"add_note")}>Add audited Ops note</button></section>)}</main>;
}
