import {writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {issueUatToken,resolveUatStaffActor} from './issue-uat-token.mjs';
export const PIN={sha:'9c06b8d7b09c51bd0ff05adf0d4a92ce4b6d60af',version:'9072e565-06d0-4a93-abc4-02e3b34e61b0',d1:'1b879a28-c8a9-40b0-830d-1ce439061a00',origin:'https://pawspace-staging.karthik-fce.workers.dev'};
const assert=(ok,code)=>{if(!ok)throw Error(code)};
export function readResult(p){assert(p?.success===true&&Array.isArray(p.result)&&p.result.length===1,'d1_read_failed');const x=p.result[0];assert(x.success===true&&Array.isArray(x.results)&&x.meta?.rows_written===0&&x.meta?.changed_db===false,'d1_read_metadata_unproven');return x.results;}
export async function run(env=process.env,fetcher=fetch){
 const receipt={kind:'finance_current_single_existing_booking_eligibility_read',pin:PIN,modelRequests:0,mutations:0,operations:[],cancellationMutationPerformed:false};
 const save=()=>writeFileSync(env.EVIDENCE_PATH||'finance-current-eligibility-receipt.json',JSON.stringify(receipt,null,2)+'\n');
 const account=env.CLOUDFLARE_ACCOUNT_ID,token=env.CLOUDFLARE_API_TOKEN;
 async function request(url,init,label){receipt.operations.push({label,state:'read_pending'});save();const op=receipt.operations.at(-1);let response;try{response=await fetcher(url,{...init,redirect:'manual',signal:AbortSignal.timeout(20000)});}catch{op.state='read_failed';throw Error('transport_failed_'+label)}op.httpStatus=response.status;assert(response.ok,'http_refused_'+label);op.state='read_received';save();return response;}
 const cf=async(path,body)=>{const r=await request(`https://api.cloudflare.com/client/v4/accounts/${account}/${path}`,{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})},body?'d1_select':'native_read');const p=await r.json();assert(p?.success===true,'native_read_failed');return p;};
 const query=async(sql,params=[])=>{assert(/^SELECT\s/i.test(sql)&&!sql.includes(';'),'select_only');return readResult(await cf(`d1/database/${PIN.d1}/query`,{sql,params}));};
 const db={prepare(sql){let params=[];return{bind(...v){params=v;return this},async first(){return(await query(sql,params))[0]??null}}}};
 const active=async()=>{const p=(await cf('workers/scripts/pawspace-staging/deployments')).result;assert(p?.deployments?.[0]?.versions?.length===1&&p.deployments[0].versions[0].percentage===100&&p.deployments[0].versions[0].version_id===PIN.version,'active_version_unproven');};
 try{
 assert(env.CONFIRM==='read-only-existing-finance-eligibility'&&env.GITHUB_RUN_ATTEMPT==='1'&&/^ops\/atlas-session-/.test(env.GITHUB_REF_NAME||'')&&env.EXPECTED_SHA===env.GITHUB_SHA,'execution_scope_refused');
 assert(/^[a-f0-9]{32}$/.test(account||'')&&token&&env.PAWSPACE_UAT_SIGNING_KEY?.length>=32,'existing_credentials_missing');
 await active();const version=(await cf(`workers/scripts/pawspace-staging/versions/${PIN.version}`)).result,bindings=version?.resources?.bindings;
 assert(Array.isArray(bindings)&&bindings.filter(b=>b.type==='d1').length===1&&bindings.some(b=>b.type==='d1'&&b.name==='DB'&&(b.id??b.database_id)===PIN.d1),'dedicated_d1_unproven');
 const vars=Object.fromEntries(bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,String(b.text??b.value??'')]));
 assert(vars.PAWSPACE_STAGING_BUILD_SHA===PIN.sha&&vars.PAWSPACE_UAT_LOGIN==='on'&&vars.PAWSPACE_COMMUNICATION_ENV==='uat'&&vars.PAWSPACE_PAYMENT_ENV==='sandbox'&&vars.PAWSPACE_PAYMENT_LIVE_APPROVED==='false'&&vars.PAWSPACE_RAZORPAYX_ENV==='sandbox'&&vars.PAWSPACE_RAZORPAYX_LIVE_APPROVED==='false','runtime_flags_unproven');
 const cookie='pawspace_uat='+encodeURIComponent(await issueUatToken({PAWSPACE_UAT_SIGNING_KEY:env.PAWSPACE_UAT_SIGNING_KEY},'founder@pawspace.in',120));
 const actor=await resolveUatStaffActor(db,new Request(PIN.origin+'/api/grooming-payment-sandbox',{headers:{cookie}}),{...vars,PAWSPACE_UAT_SIGNING_KEY:env.PAWSPACE_UAT_SIGNING_KEY});
 assert(actor?.roleCode==='founder'&&actor.permissions.includes('*'),'normal_founder_authority_unproven');receipt.actor={normalUatFounder:true,verifiedActivePrincipal:true,credentialsEmitted:false};save();
 const bookingId='PS-UAT-MUTI4M2P-B62C',paymentId='PAY-B260FC6F',orderId='order_TjkWPuozbTwhCn';
 const rows=await query("SELECT b.id,b.service_code,b.status bookingStatus,b.provider_id,b.total_amount,b.currency,b.scheduled_start,b.scheduled_end,p.id paymentId,p.mode,p.amount,p.amount_due_now,p.status paymentStatus,w.id workOrderId,w.status workOrderStatus,g.provider gatewayProvider,g.environment gatewayEnvironment,g.gateway_order_id,g.gateway_payment_id,g.gateway_payment_link_id,g.status gatewayLinkStatus FROM canonical_bookings b JOIN booking_payments p ON p.booking_id=b.id JOIN provider_work_orders w ON w.booking_id=b.id LEFT JOIN payment_gateway_links g ON g.booking_id=b.id WHERE b.id=? AND b.customer_id='CUS0000'",[bookingId]);
 assert(rows.length===1,'single_existing_booking_unproven');const row=rows[0];
 assert(row.paymentId===paymentId&&row.workOrderId==='WO-D3B42F36'&&row.provider_id==='uatcap_groom_ft'&&row.service_code==='grooming'&&row.total_amount===1349&&row.amount===1349&&row.currency==='INR'&&row.gateway_order_id===orderId&&row.gatewayEnvironment==='sandbox'&&row.gatewayProvider==='razorpay','existing_booking_order_binding_or_cap_refused');
 receipt.booking=row;receipt.observedAt=new Date().toISOString();receipt.scheduleEligibleNow=Date.now()>=Date.parse(row.scheduled_start)&&Date.now()<=Date.parse(row.scheduled_end);save();
 const tables=await query("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('grooming_service_proof','payment_gateway_events','payment_reconciliation_records','post_service_payment_requests','service_cash_collections')");const names=new Set(tables.map(r=>r.name));
 if(names.has('grooming_service_proof'))receipt.proof=await query("SELECT before_photo_ref IS NOT NULL AND length(trim(before_photo_ref))>0 beforeProofPresent,after_photo_ref IS NOT NULL AND length(trim(after_photo_ref))>0 afterProofPresent FROM grooming_service_proof WHERE booking_id=?",[bookingId]);else receipt.proof=[];
 if(names.has('payment_reconciliation_records'))receipt.reconciliation=await query("SELECT gateway,environment,expected_amount,captured_amount,refunded_amount,currency,gateway_status,reconciliation_status FROM payment_reconciliation_records WHERE booking_id=? AND payment_id=?",[bookingId,paymentId]);
 if(names.has('payment_gateway_events'))receipt.captureEventCount=(await query("SELECT COUNT(*) count FROM payment_gateway_events WHERE booking_id=? AND payment_id=? AND event_type IN ('payment.captured','order.paid')",[bookingId,paymentId]))[0].count;
 if(names.has('post_service_payment_requests'))receipt.existingPaymentRequestCount=(await query("SELECT COUNT(*) count FROM post_service_payment_requests WHERE booking_id=?",[bookingId]))[0].count;
 if(names.has('service_cash_collections'))receipt.cashCollectionCount=(await query("SELECT COUNT(*) count FROM service_cash_collections WHERE booking_id=?",[bookingId]))[0].count;
 receipt.postServiceRequestEligible=['in_service','completed'].includes(row.bookingStatus)&&(row.bookingStatus==='completed'||receipt.proof.some(p=>p.beforeProofPresent===1&&p.afterProofPresent===1))&&row.mode==='pay_after_service'&&!['captured','refunded','partially_refunded'].includes(row.paymentStatus);
 const fixed=await(await request(PIN.origin+'/__staging/fixture-isolation?scope=grooming_strict&expectedSha='+PIN.sha,{method:'GET',headers:{cookie}},'normal_founder_fixture_get')).json();const keys=['paymentSandbox','payoutsSandbox','communicationsUat','voiceNotLive','customerLiveOtpDisabled','productionOtpDisabled','schedulerUat','customerFixtureProven','customerOtpTargetUnambiguous','specificGroomerFixtureProven','groomerOtpTargetUnambiguous','genericExcluded','metaExcluded','voiceExcluded'];
 assert(fixed.ok===true&&fixed.scope==='grooming_strict'&&fixed.version?.id===PIN.version&&fixed.version?.buildSha===PIN.sha&&keys.every(k=>fixed.checks?.[k]===true),'current_runtime_isolation_unproven');receipt.isolation={exactVersion:true,checks:14,allPass:true};
 await active();receipt.ok=true;receipt.providerOrderFreshlyQueried=false;receipt.captureAttempted=false;receipt.newInstrumentCreated=false;receipt.nextAction=receipt.postServiceRequestEligible?'Reviewed single-instrument canonical TEST checkout plan still required':'Existing future booking cannot enter normal post-service collection. Obtain reviewed today-eligible recovery with governed quote at most1349 and supported retirement/supersession of existing unpaid order before any new payable instrument; or wait for original window and perform legitimate synthetic service proof through normal lifecycle.';save();console.log('Existing isolated Finance eligibility read complete; no payment or provider mutation.');
 }catch(error){receipt.ok=false;receipt.failure=/^[a-zA-Z0-9_]+$/.test(error.message)?error.message:'read_failed_private_details_withheld';save();throw Error(receipt.failure)}
 return receipt;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)run().catch(e=>{console.error(e.message);process.exitCode=1});
