import {routeTelemetryToHealthcare,routeVisionToOps} from "./moonshot-event-router";
import {executeMoonshotRpaAction,MOONSHOT_RPA_ALLOWLIST} from "./moonshot-rpa-core";
type Db=D1Database;
type RateLimitBinding={limit(input:{key:string}):Promise<{success:boolean}>};
type AiBinding={run(model:string,input:Record<string,unknown>):Promise<unknown>};
type BrowserBinding={fetch(input:RequestInfo|URL,init?:RequestInit):Promise<Response>};
export type MoonshotEnv=Record<string,unknown>&{DB?:Db;AI?:AiBinding;MOONSHOT_TELEMETRY_RATE_LIMITER?:RateLimitBinding;MOONSHOT_VISION_RATE_LIMITER?:RateLimitBinding;MOONSHOT_RPA_RATE_LIMITER?:RateLimitBinding;BROWSER?:BrowserBinding};
const truthy=(v:unknown)=>["1","true","on","yes"].includes(String(v??"").trim().toLowerCase());
const text=(v:unknown,max=160)=>String(v??"").trim().slice(0,max);
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"cache-control":"no-store"}});
const ip=(r:Request)=>text(r.headers.get("cf-connecting-ip")||r.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",80);
const limit=async(binding:RateLimitBinding|undefined,key:string)=>!binding||(await binding.limit({key})).success;
const authorized=(request:Request,secret:unknown)=>{const expected=text(secret,512);if(!expected)return false;const supplied=text(request.headers.get("authorization"),600);return supplied===`Bearer ${expected}`};
async function readJson(request:Request,maxBytes:number){const raw=await request.text();if(raw.length>maxBytes)throw new Error("payload_too_large");return JSON.parse(raw) as Record<string,unknown>;}
export async function ensureMoonshotTelemetryTable(db:Db){await db.prepare(`CREATE TABLE IF NOT EXISTS moonshot_pet_telemetry (id TEXT PRIMARY KEY,device_id TEXT NOT NULL,pet_id TEXT NOT NULL,observed_at INTEGER NOT NULL,received_at INTEGER NOT NULL,heart_rate_bpm REAL,temperature_c REAL,latitude REAL,longitude REAL,battery_percent REAL,payload_json TEXT NOT NULL,debounce_key TEXT NOT NULL UNIQUE)`).run();await db.prepare("CREATE INDEX IF NOT EXISTS idx_moonshot_pet_telemetry_pet_time ON moonshot_pet_telemetry(pet_id,observed_at DESC)").run();}
const finite=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null};
export async function handleMoonshotTelemetry(request:Request,env:MoonshotEnv){if(!truthy(env.PAWSPACE_IOT_ACTIVE))return json({error:"moonshot_iot_disabled"},503);if(request.method!=="POST")return json({error:"method_not_allowed"},405);if(!authorized(request,env.PAWSPACE_IOT_INGEST_TOKEN))return json({error:"telemetry_auth_failed"},403);if(!await limit(env.MOONSHOT_TELEMETRY_RATE_LIMITER,`telemetry:${ip(request)}`))return json({error:"rate_limited"},429);if(!env.DB)return json({error:"telemetry_storage_unavailable"},503);let body:Record<string,unknown>;try{body=await readJson(request,64_000)}catch(e){return json({error:e instanceof Error&&e.message==="payload_too_large"?"payload_too_large":"invalid_json"},e instanceof Error&&e.message==="payload_too_large"?413:400)}
 const rawEvents=Array.isArray(body.events)?body.events:[body];if(rawEvents.length<1||rawEvents.length>50)return json({error:"telemetry_batch_size_invalid",maxBatchSize:50},400);const accepted:Array<Record<string,unknown>>=[],seen=new Set<string>();
 for(const raw of rawEvents){if(!raw||typeof raw!=="object")return json({error:"invalid_telemetry_event"},400);const event=raw as Record<string,unknown>,deviceId=text(event.deviceId,80),petId=text(event.petId,80),observed=Date.parse(text(event.observedAt,64));if(!deviceId||!petId||!Number.isFinite(observed))return json({error:"invalid_telemetry_identity"},400);const heart=finite(event.heartRateBpm),temp=finite(event.temperatureC),lat=finite(event.latitude),lng=finite(event.longitude),battery=finite(event.batteryPercent);if((lat!==null&&(lat<-90||lat>90))||(lng!==null&&(lng<-180||lng>180)))return json({error:"invalid_coordinates"},400);const bucket=Math.floor(observed/5000)*5000,debounceKey=`${deviceId}:${petId}:${bucket}`;if(seen.has(debounceKey))continue;seen.add(debounceKey);accepted.push({id:`mt_${crypto.randomUUID()}`,deviceId,petId,observed,receivedAt:Date.now(),heart,temp,lat,lng,battery,payload:JSON.stringify({heartRateBpm:heart,temperatureC:temp,latitude:lat,longitude:lng,batteryPercent:battery}),debounceKey});}
 if(accepted.length===0)return json({accepted:0,debounced:rawEvents.length,windowMs:5000},202);await ensureMoonshotTelemetryTable(env.DB);const statements=accepted.map(row=>env.DB!.prepare("INSERT OR IGNORE INTO moonshot_pet_telemetry (id,device_id,pet_id,observed_at,received_at,heart_rate_bpm,temperature_c,latitude,longitude,battery_percent,payload_json,debounce_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(row.id,row.deviceId,row.petId,row.observed,row.receivedAt,row.heart,row.temp,row.lat,row.lng,row.battery,row.payload,row.debounceKey));const results=await env.DB.batch(statements);const persisted=results.reduce((sum,result)=>sum+Number((result as {meta?:{changes?:number}}).meta?.changes??0),0);const agentWakes=await routeTelemetryToHealthcare(env.DB,env,accepted.map(row=>({petId:String(row.petId),heart:row.heart as number|null,observed:Number(row.observed)})));return json({accepted:persisted,debounced:rawEvents.length-persisted,submitted:rawEvents.length,windowMs:5000,batchSize:accepted.length,agentWakes},202);}
export async function handleMoonshotVision(request:Request,env:MoonshotEnv){if(!truthy(env.PAWSPACE_VISION_ACTIVE))return json({error:"moonshot_vision_disabled"},503);if(request.method!=="POST")return json({error:"method_not_allowed"},405);if(!authorized(request,env.PAWSPACE_VISION_INGEST_TOKEN))return json({error:"vision_auth_failed"},403);if(!await limit(env.MOONSHOT_VISION_RATE_LIMITER,`vision:${ip(request)}`))return json({error:"rate_limited"},429);if(!env.AI)return json({error:"workers_ai_unavailable"},503);let body:Record<string,unknown>;try{body=await readJson(request,1_500_000)}catch(e){return json({error:e instanceof Error&&e.message==="payload_too_large"?"payload_too_large":"invalid_json"},e instanceof Error&&e.message==="payload_too_large"?413:400)}
 const frame=text(body.frameBase64,1_400_000),sourceId=text(body.sourceId,100);if(!frame||!sourceId)return json({error:"sourceId_and_frameBase64_required"},400);let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(frame),c=>c.charCodeAt(0))}catch{return json({error:"invalid_frame_encoding"},400)}if(bytes.byteLength>1_000_000)return json({error:"frame_too_large"},413);
 const model=text(env.PAWSPACE_VISION_MODEL,120)||"@cf/llava-1.5-7b-hf";const prompt="Classify this pet-care facility frame. Return concise JSON with anomaly:boolean, labels:string[], confidence:number. Flag distressed pet, unsafe restraint, open gate/door, smoke/fire, flooding, or unattended medical emergency.";const result=await env.AI.run(model,{image:Array.from(bytes),prompt,max_tokens:220});const alert=env.DB?await routeVisionToOps(env.DB,env,{sourceId,bookingId:text(body.bookingId,100)||undefined,result}):null;return json({sourceId,model,result,alert,advisoryOnly:true,humanReviewRequired:true});}
export async function handleMoonshotRpa(request:Request,env:MoonshotEnv){if(!truthy(env.PAWSPACE_RPA_ACTIVE))return json({error:"moonshot_rpa_disabled"},503);if(request.method!=="POST")return json({error:"method_not_allowed"},405);if(!authorized(request,env.PAWSPACE_RPA_INTERNAL_TOKEN))return json({error:"rpa_auth_failed"},403);if(!await limit(env.MOONSHOT_RPA_RATE_LIMITER,`rpa:${ip(request)}`))return json({error:"rate_limited"},429);let body:Record<string,unknown>;try{body=await readJson(request,32_768)}catch{return json({error:"invalid_json"},400)}const system=text(body.system,80),action=text(body.action,100),correlationId=text(body.correlationId,120);if(!MOONSHOT_RPA_ALLOWLIST.has(system)||!action||!correlationId)return json({error:"rpa_request_not_allowlisted"},403);try{const result=await executeMoonshotRpaAction(env,{system,action,correlationId,input:body.input});return json({accepted:true,...result,externalMutation:true},202);}catch(error){if(error instanceof Response)return json({error:await error.text()},error.status);throw error;}}
