"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import css from "./marketing-control-panel.module.css";

type Campaign={id:string;name:string;objective:string;service_code:string|null;city_id:string|null;budget_amount:number;holdout_percent:number;status:string;approval_status:string};
type Promotion={id:string;name:string;promotion_type:string;vertical:string;audience:string;value:number;budget_cap:number;holdout_percent:number;status:string;coupon_code?:string|null};
type Rule={id:string;name:string;trigger_code:string;approval_mode:string;enabled:number};
type PlatformMetric={platform:string;rowCount:number;impressions:number;clicks:number;spendMinor:number;conversions:number;conversionValueMinor:number;lastPulledAt:number|null};
type Dashboard={from:string;to:string;hasLiveMetrics:boolean;lastPulledAt:number|null;totals:{impressions:number;clicks:number;spendMinor:number;conversions:number;conversionValueMinor:number;roas:number;cpaMinor:number};attribution:{leads:number;bookings:number;customers:number;bookedRevenue:number;collectedRevenue:number;contributionMargin:number};platforms:PlatformMetric[];source:string;sampleData:false};
type ConnectorState={state:string;configured?:boolean;enabled?:boolean;queryCount?:number;lastSuccessfulSync?:Record<string,unknown>|null};
type WebAnalytics={hasData:boolean;sessions:number;users:number;newUsers:number;engagedSessions:number;conversions:number;revenueMinor:number;lastPulledAt:number|null;source:string};
type Payload={campaigns:Campaign[];promotions:Promotion[];rules:Rule[];attribution:Record<string,unknown>[];dashboard:Dashboard;webAnalytics:WebAnalytics;connectorStatus:{googleAds:string;meta:string;supermetrics:string;ga4:string;communications:string};adConnectorStatus:{googleAds:ConnectorState;metaAds:ConnectorState;googleDataManager:ConnectorState;externalWritesEnabled:boolean};supermetricsStatus:ConnectorState};
const moneyMinor=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format((Number(v)||0)/100);
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)||0);
const stateLabel=(v:string)=>String(v||"not_configured").replaceAll("_"," ");
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>`${today().slice(0,7)}-01`;

export default function MarketingControlPanel({notify}:{notify:(message:string)=>void}){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[reason,setReason]=useState("Approved during marketing UAT");
 const[newCampaign,setNewCampaign]=useState({name:"",objective:"Bookings",serviceCode:"grooming",cityId:"blr",audience:"",budgetAmount:2500,holdoutPercent:10});
 const[newPromotion,setNewPromotion]=useState({name:"",promotionType:"percent_discount",vertical:"Grooming",audience:"",value:10,budgetCap:50000,marginFloorPercent:25,holdoutPercent:10});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/marketing-control?includeAdMetrics=1&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{cache:"no-store"});const b=await r.json() as {data?:Payload;error?:string};if(!r.ok||!b.data)throw new Error(b.error||"Marketing control unavailable");setData(b.data);}catch(e){notify(e instanceof Error?e.message:"Marketing control unavailable");}finally{setLoading(false)}},[from,to,notify]);
 useEffect(()=>{const timer=setTimeout(()=>{void load()},0);return()=>clearTimeout(timer)},[load]);
 const run=async(action:string,extra:Record<string,unknown>={})=>{setBusy(action);try{const r=await fetch("/api/marketing-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...extra})});const b=await r.json() as {error?:string};if(!r.ok&&r.status!==207)throw new Error(b.error||`${action} failed`);notify(`${action.replaceAll("_"," ")} completed`);await load();}catch(e){notify(e instanceof Error?e.message:`${action} failed`)}finally{setBusy("")}};
 const dashboard=data?.dashboard,attribution=dashboard?.attribution,totals=dashboard?.totals;
 const platforms=useMemo(()=>dashboard?.platforms??[],[dashboard]);
 const createCampaign=()=>run("create_campaign",{...newCampaign,audienceRule:{description:newCampaign.audience}});
 const createPromotion=()=>run("create_promotion",newPromotion);
 if(loading&&!data)return <section className={css.panel}>Loading canonical marketing data…</section>;
 return <div className={css.wrap}>
  <section className={css.hero}><div><span>MARKETING OPERATING SYSTEM · CANONICAL DATA</span><h2>Spend with proof. Promote with control.</h2><p>Every number below comes from PawSpace marketing facts, attribution, CRM or governed campaign state. No illustrative performance data is used.</p></div><aside><b>{moneyMinor(totals?.spendMinor??0)}</b><span>recorded media spend</span><small>{from} → {to}</small></aside></section>
  <section className={css.filters}><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={Boolean(busy)} onClick={()=>void load()}>Refresh</button><button disabled={Boolean(busy)} onClick={()=>void run("sync_ad_metrics",{from,to})}>Sync Google + Meta</button><button disabled={Boolean(busy)} onClick={()=>void run("sync_supermetrics_metrics",{from,to})}>Sync Supermetrics</button></section>
  <section className={css.metrics}>{[
   ["Media spend",moneyMinor(totals?.spendMinor??0),dashboard?.hasLiveMetrics?"canonical connector facts":"No connector facts in this period"],
   ["Ad conversion value",moneyMinor(totals?.conversionValueMinor??0),`${(totals?.roas??0).toFixed(2)}× platform ROAS`],
   ["Attributed bookings",String(attribution?.bookings??0),`${attribution?.leads??0} leads · ${attribution?.customers??0} customers`],
   ["Collected revenue",money(attribution?.collectedRevenue??0),"canonical attribution facts"],
   ["Contribution",money(attribution?.contributionMargin??0),"canonical contribution attribution"],
   ["CPA",moneyMinor(totals?.cpaMinor??0),`${totals?.conversions??0} recorded conversions`],
  ].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section>

  <section className={css.panel}><header><div><span>CONNECTOR READINESS</span><h3>Direct + Supermetrics ingestion</h3><p>Direct Google/Meta connectors and Supermetrics are alternative read paths into the same canonical metric table. External ad mutations remain separately gated.</p></div></header><div className={css.connectorGrid}>
   {[{name:"Google Ads direct",state:data?.connectorStatus.googleAds,detail:"campaign, keyword, search-term and demographic metrics"},{name:"Meta Ads direct",state:data?.connectorStatus.meta,detail:"campaign/ad/demographic insights"},{name:"Supermetrics",state:data?.connectorStatus.supermetrics,detail:`read-only normalized ingestion · ${data?.supermetricsStatus.queryCount??0} configured query(s)`},{name:"Google offline conversions",state:data?.adConnectorStatus.googleDataManager?.configured?"configured":"not_configured",detail:"consent-aware Data Manager conversion upload"},{name:"GA4",state:data?.connectorStatus.ga4,detail:"not yet an authoritative reporting source"},{name:"CRM + communications",state:"connected",detail:"canonical leads, bookings, customer and governed messaging"}].map(c=><article key={c.name}><span>{stateLabel(c.state||"")}</span><strong>{c.name}</strong><p>{c.detail}</p></article>)}
  </div></section>

  <section className={css.two}><div className={css.panel}><header><div><span>CHANNEL SCORECARD · REAL FACTS</span><h3>Media performance</h3></div></header>{platforms.length?platforms.map(p=><article className={css.channel} key={p.platform}><div><strong>{stateLabel(p.platform)}</strong><small>{p.impressions.toLocaleString("en-IN")} impressions · {p.clicks.toLocaleString("en-IN")} clicks</small></div><span>{moneyMinor(p.spendMinor)} spend</span><b>{p.conversions} conv.</b><em>{p.spendMinor?`${(p.conversionValueMinor/p.spendMinor).toFixed(2)}× ROAS`:"—"}</em></article>):<div className={css.empty}>No canonical ad metrics are stored for this period. Configure a direct connector or Supermetrics, then run sync.</div>}</div>
   <aside className={css.panel}><header><div><span>ATTRIBUTION + WEB TRUTH</span><h3>Lead → booking → collection</h3></div></header>{[["Leads",attribution?.leads??0],["Bookings",attribution?.bookings??0],["Customers",attribution?.customers??0],["Collected revenue",money(attribution?.collectedRevenue??0)],["GA4 sessions",data?.webAnalytics.sessions??0],["GA4 users",data?.webAnalytics.users??0],["GA4 conversions",data?.webAnalytics.conversions??0]].map(x=><p className={css.policy} key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></p>)}</aside>
  </section>

  <section className={css.panel}><header><div><span>GOVERNED CAMPAIGNS</span><h3>Draft → checker approval → audience snapshot → activation</h3></div></header><div className={css.fields}><label>Name<input value={newCampaign.name} onChange={e=>setNewCampaign({...newCampaign,name:e.target.value})}/></label><label>Objective<select value={newCampaign.objective} onChange={e=>setNewCampaign({...newCampaign,objective:e.target.value})}><option>Bookings</option><option>Qualified leads</option><option>Reactivation</option><option>Subscription renewals</option></select></label><label>Service<input value={newCampaign.serviceCode} onChange={e=>setNewCampaign({...newCampaign,serviceCode:e.target.value})}/></label><label>Audience<input value={newCampaign.audience} onChange={e=>setNewCampaign({...newCampaign,audience:e.target.value})}/></label><label>Budget<input type="number" value={newCampaign.budgetAmount} onChange={e=>setNewCampaign({...newCampaign,budgetAmount:Number(e.target.value)})}/></label><label>Holdout %<input type="number" min="0" max="100" value={newCampaign.holdoutPercent} onChange={e=>setNewCampaign({...newCampaign,holdoutPercent:Number(e.target.value)})}/></label></div><button className={css.primary} disabled={!newCampaign.name||Boolean(busy)} onClick={()=>void createCampaign()}>Create governed draft</button>{data?.campaigns.map(c=><article className={css.campaign} key={c.id}><div><strong>{c.name}</strong><small>{c.objective} · {c.service_code||"all services"} · {c.holdout_percent}% holdout</small></div><b>{money(c.budget_amount)}</b><em>{c.status} · {c.approval_status}</em><div>{c.approval_status!=="approved"&&<button onClick={()=>void run("approve_campaign",{id:c.id,reason})}>Approve</button>}<button onClick={()=>void run("snapshot_audience",{id:c.id})}>Snapshot</button>{c.approval_status==="approved"&&c.status!=="active"&&<button onClick={()=>void run("activate_campaign",{id:c.id})}>Activate</button>}{c.status==="active"&&<button onClick={()=>void run("set_status",{id:c.id,status:"paused"})}>Pause</button>}</div></article>)}</section>

  <section className={css.panel}><header><div><span>PROMOTIONS + RETENTION</span><h3>Controlled offers, holdout and margin floor</h3></div></header><div className={css.fields}><label>Name<input value={newPromotion.name} onChange={e=>setNewPromotion({...newPromotion,name:e.target.value})}/></label><label>Vertical<input value={newPromotion.vertical} onChange={e=>setNewPromotion({...newPromotion,vertical:e.target.value})}/></label><label>Audience<input value={newPromotion.audience} onChange={e=>setNewPromotion({...newPromotion,audience:e.target.value})}/></label><label>Discount %<input type="number" value={newPromotion.value} onChange={e=>setNewPromotion({...newPromotion,value:Number(e.target.value)})}/></label><label>Budget cap<input type="number" value={newPromotion.budgetCap} onChange={e=>setNewPromotion({...newPromotion,budgetCap:Number(e.target.value)})}/></label><label>Holdout %<input type="number" value={newPromotion.holdoutPercent} onChange={e=>setNewPromotion({...newPromotion,holdoutPercent:Number(e.target.value)})}/></label></div><button className={css.primary} disabled={!newPromotion.name||Boolean(busy)} onClick={()=>void createPromotion()}>Create promotion draft</button>{data?.promotions.map(p=><article className={css.campaign} key={p.id}><div><strong>{p.name}</strong><small>{p.vertical} · {p.audience} · {p.holdout_percent}% holdout</small>{p.coupon_code&&<small style={{display:"block",fontWeight:700}}>Customer coupon: {p.coupon_code}</small>}</div><b>{p.value}% · cap {money(p.budget_cap)}</b><em>{p.status}</em></article>)}</section>

  <section className={css.two}><div className={css.panel}><header><div><span>AUTOMATION</span><h3>Human-approved optimization rules</h3></div></header>{data?.rules.length?data.rules.map(r=><article className={css.rule} key={r.id}><div><strong>{r.name}</strong><small>{stateLabel(r.trigger_code)} · {stateLabel(r.approval_mode)}</small></div><button onClick={()=>void run("set_automation_rule_enabled",{id:r.id,enabled:!r.enabled,reason})}>{r.enabled?"Enabled":"Paused"}</button></article>):<div className={css.empty}>No automation rules configured.</div>}<label className={css.reason}>Mandatory approval/change reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div>
   <aside className={css.panel}><header><div><span>PRODUCTION SAFETY</span><h3>Current controls</h3></div></header>{[["Live media writes",data?.adConnectorStatus.externalWritesEnabled?"ENABLED":"DISABLED"],["Autonomous automation","DISABLED"],["Audience consent suppression","ENFORCED"],["Maker/checker campaign approval","ENFORCED"],["Supermetrics mode","READ ONLY"],["Sample dashboard data","REMOVED"]].map(x=><p className={css.policy} key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></p>)}</aside>
  </section>
 </div>;
}
