"use client";

import { useMemo, useState } from "react";
import css from "./platform-audit.module.css";

type Status = "Verified prototype" | "Partial" | "Integration-ready" | "Missing core";
type Priority = "Must have" | "Good to have" | "AI / future";
type Area = {
  area:string; owner:string; status:Status; evidence:string; gap:string; next:string;
  must:number; verified:number; partial:number; missing:number;
};

const areas:Area[] = [
  {area:"Customer app",owner:"Product",status:"Verified prototype",evidence:"Grooming, Training, Boarding and Sitting journeys; packages, coupons, referrals, wallet, GPS states and shared test booking.",gap:"No production identity, server booking write, payment, notifications or native-store release.",next:"Connect canonical booking API and run physical-device UAT.",must:18,verified:14,partial:4,missing:0},
  {area:"Provider apps",owner:"Operations",status:"Partial",evidence:"Groomer, Trainer, Host/Sitter, Walker and Driver views; job milestones, masked-call intent, earnings and proof states.",gap:"Specialist pages still use fixtures; no offline sync, real route, secure upload or one role router.",next:"Unify on one provider work-order API and offline queue.",must:16,verified:6,partial:7,missing:3},
  {area:"CRM & sales",owner:"CRM",status:"Partial",evidence:"Persistent lead creation, Customer 360, pipeline, tasks, activities, campaigns and automation concepts.",gap:"Most pipeline, inbox, campaign, forecast and SLA actions are static; phone exposure is inconsistent.",next:"Project every booking event into CRM; enforce masking and persistent activity outcomes.",must:17,verified:5,partial:9,missing:3},
  {area:"Control centre",owner:"Founder",status:"Partial",evidence:"Users/roles, approvals, cities, coupons, referrals, data import, subscriptions, BI, quality and configuration screens.",gap:"Several controls are display-only; publishing a rule does not version and enforce it server-side.",next:"Create a governed configuration registry with approval, effective dates and rollback.",must:17,verified:7,partial:8,missing:2},
  {area:"Operations & dispatch",owner:"Ops",status:"Partial",evidence:"Queues, assignment concepts, partner acceptance, travel buffers, geofences, exceptions and test lifecycle.",gap:"Availability, capacity, rerouting, SLA timers and incident tickets are not persistent or concurrency-safe.",next:"Implement work orders, dispatch offers, acceptance expiry and exception queues.",must:19,verified:5,partial:9,missing:5},
  {area:"HR",owner:"People",status:"Partial",evidence:"Worker directory, attendance, compliance risks, leave/fine concepts and role models.",gap:"No employee master, onboarding/offboarding, documents, shifts, leave balances, reviews or grievance records.",next:"Build People master and lifecycle before payroll automation.",must:14,verified:2,partial:6,missing:6},
  {area:"Payroll",owner:"People + Finance",status:"Partial",evidence:"Draft salary/commission register, incentives, deductions, dispute and approval concepts.",gap:"No statutory rule engine, payslip generation, payroll ledger, bank file, return filing or locked payroll run.",next:"Add versioned earning rules, statutory review and maker-checker payroll close.",must:15,verified:2,partial:6,missing:7},
  {area:"Finance & accounts",owner:"Finance",status:"Partial",evidence:"Persistent UAT expenses/vendor bills, duplicate checks, maker-checker approval, balanced journals, locked periods, collections, settlements, GST/TDS, banking, budgets, close and audit trail.",gap:"Opening balances and operational sources are not reconciled; bank, payroll, OCR, filing and Tally/Zoho connections remain integration-ready.",next:"Approve accounting definitions, map chart of accounts and reconcile opening/live source records.",must:20,verified:10,partial:8,missing:2},
  {area:"Grooming subscriptions",owner:"CRM + Ops",status:"Integration-ready",evidence:"Plans, GST savings, lifecycle queue, renewal days, communication history, automation rules and DB schema.",gap:"Credit reserve/use/reverse is not connected to every real booking; counters and bot delivery are not live.",next:"Connect subscription wallet ledger to booking completion and cancellation.",must:15,verified:9,partial:6,missing:0},
  {area:"Business intelligence",owner:"Founder + Finance",status:"Partial",evidence:"Overview, vertical P&L, Accounts, customer LTV/win-back, subscription economics and governed report builder.",gap:"Dashboards use a protected March snapshot rather than reconciled operational events.",next:"Bind metrics to governed sources and add freshness/reconciliation tests.",must:14,verified:7,partial:6,missing:1},
  {area:"Security & privacy",owner:"Founder + Security",status:"Partial",evidence:"Central API gateway now rejects anonymous, unprovisioned and disabled identities; enforces per-module permissions; blocks cross-origin writes; masks contact fields; and records access outcomes.",gap:"MFA/session revocation depend on the identity platform; encrypted uploads, retention/deletion jobs, rate limits and formal security testing remain open.",next:"Configure the founder identity, provision the employee allowlist, then complete DPDP retention/deletion and penetration testing.",must:22,verified:10,partial:7,missing:5},
  {area:"AI & automation",owner:"Product + Ops",status:"Integration-ready",evidence:"Trigger/action models, renewal bot controls, next-best-action concepts, feature flags and manual fallbacks.",gap:"No production event bus, consent-aware execution, human approval, evaluation, cost limits or kill switch telemetry.",next:"Launch read-only copilots first; require approval for customer or money actions.",must:13,verified:2,partial:7,missing:4},
  {area:"Reliability & release",owner:"Technology",status:"Missing core",evidence:"Build/lint/regression gates, feature-flag concepts and sandbox integration contracts.",gap:"No production monitoring, alerting, backup/restore proof, SLOs, incident runbooks, rollback drill or load test.",next:"Complete production foundation before public customer traffic.",must:16,verified:3,partial:4,missing:9},
  {area:"Native mobile readiness",owner:"Product + Technology",status:"Missing core",evidence:"Responsive web journeys and a React Native starter exist.",gap:"No signed iOS/Android builds, store privacy forms, push credentials, permission testing or device matrix sign-off.",next:"Choose wrapper/native path and complete store-release checklist.",must:12,verified:2,partial:3,missing:7},
];

const requirements:{priority:Priority; capability:string; globalPattern:string; status:Status; disposition:string}[] = [
  {priority:"Must have",capability:"One customer, pet, booking and payment record",globalPattern:"CRM single source of truth + field-service work order",status:"Partial",disposition:"API models exist; customer and operating surfaces still mix DB, fixtures and browser ledger."},
  {priority:"Must have",capability:"Availability, skills, route and capacity dispatch",globalPattern:"Field-service schedule board and resource matching",status:"Partial",disposition:"Rules are designed; real concurrency-safe calendar and rerouting are missing."},
  {priority:"Must have",capability:"Marketplace onboarding, commissions and payouts",globalPattern:"Connected-provider onboarding, ledger, refund and dispute handling",status:"Partial",disposition:"Partner acceptance and earnings are designed; KYC, settlement and dispute ledger are missing."},
  {priority:"Must have",capability:"Role, object and field-level access",globalPattern:"Least privilege, separation of duties and audited elevation",status:"Partial",disposition:"All current privileged APIs pass through a central RBAC gateway; object ownership tests and formal employee access UAT remain."},
  {priority:"Must have",capability:"Customer support and incident lifecycle",globalPattern:"Case, SLA, escalation, communication and resolution proof",status:"Partial",disposition:"Quality screens and recovery concepts exist; persistent tickets and SLA automation are missing."},
  {priority:"Must have",capability:"Finance subledger and statutory close",globalPattern:"Invoice, collection, refund, payout, tax and reconciliation traceability",status:"Partial",disposition:"Persistent UAT expense/bill approval, balanced posting, period locking and audit exist; opening/live sources are not yet reconciled."},
  {priority:"Must have",capability:"Employee master to payroll close",globalPattern:"Hire-to-retire, time, leave, earnings, deductions, approvals and payslips",status:"Partial",disposition:"Workforce/payroll screens exist but not a compliant system of record."},
  {priority:"Must have",capability:"Security, privacy, backup and recovery",globalPattern:"Consent, minimisation, authentication, audit, retention and tested restoration",status:"Partial",disposition:"Authentication, module permissions, masking and access audit are enforced; retention, secure files, backup/restore proof and formal testing remain."},
  {priority:"Good to have",capability:"Low-code workflow and report builders",globalPattern:"Admin-configured rules, reports, schedules and approval",status:"Integration-ready",disposition:"Report builder works in review mode; operational rule publishing needs server enforcement."},
  {priority:"Good to have",capability:"Omnichannel customer engagement",globalPattern:"Voice, WhatsApp, email, push and unified history",status:"Partial",disposition:"Masked contact router is ready for Exotel; other channels remain simulated."},
  {priority:"Good to have",capability:"Cohorts, LTV, attribution and next-best action",globalPattern:"Customer intelligence and revenue optimisation",status:"Partial",disposition:"Views and definitions exist; live event lineage and attribution are missing."},
  {priority:"AI / future",capability:"Renewal and win-back agent",globalPattern:"Consent-aware agent proposes and executes bounded outreach",status:"Integration-ready",disposition:"Rules and bot flags exist; require live channels, outcome capture and human escalation."},
  {priority:"AI / future",capability:"Dispatch optimiser",globalPattern:"Optimise skill, SLA, travel, fairness, quality and cost",status:"Partial",disposition:"Inputs are designed; need trusted availability and routing data before automation."},
  {priority:"AI / future",capability:"Operations copilot",globalPattern:"Summarise work orders, exceptions and next actions with evidence",status:"Integration-ready",disposition:"Safe first AI release: read-only summaries with source links and no autonomous money action."},
  {priority:"AI / future",capability:"Anomaly and fraud monitoring",globalPattern:"Detect coupon abuse, payout anomalies, fake GPS and collusion",status:"Missing core",disposition:"Event data and review workflow must exist before modelling."},
];

const blockers = [
  ["P0","Canonical production records","Bookings, payments, subscriptions, jobs and finance still span multiple stores.","Technology","Public launch"],
  ["P0","Access configuration and UAT","Set the founder identity, provision employees, test every role and prove object/field ownership.","Technology + Founder","Staff pilot"],
  ["P0","Finance reconciliation","Approve revenue/GST/commission/refund definitions and reconcile opening balances.","Finance","Paid pilot"],
  ["P0","Backup and recovery proof","Automated backup, restore drill, RPO/RTO and incident owner.","Technology","Staff pilot"],
  ["P0","Secure files and evidence","Private uploads, scanning, signed access, retention and deletion.","Technology","Service pilot"],
  ["P1","Real dispatch and capacity","Availability, travel, accept/decline expiry, reroute and replacement.","Operations","Multi-zone scale"],
  ["P1","Customer communication delivery","OTP plus consented WhatsApp/SMS/email/push with retry and opt-out.","CRM + Technology","Invited beta"],
  ["P1","HR and payroll system of record","Employee lifecycle, statutory rules, locked run, payslips and audit.","People + Finance","Payroll use"],
  ["P1","Physical-device and accessibility UAT","iOS/Android/tablet, keyboard, screen reader, safe areas and performance.","Product","Invited beta"],
];

const benchmarks = [
  {name:"Salesforce Sales Cloud",focus:"Customer single source, activity capture, lead/pipeline management, workflow, forecasting and configurable reports.",url:"https://www.salesforce.com/sales/cloud/"},
  {name:"Microsoft Dynamics 365 Field Service",focus:"Work orders, scheduling/dispatch, mobile technician workflows, ETA, inventory, billing, time and analytics.",url:"https://learn.microsoft.com/en-us/dynamics365/field-service/overview"},
  {name:"Stripe Connect marketplace pattern",focus:"Provider onboarding, payment routing, platform fees, payouts, refunds and disputes.",url:"https://docs.stripe.com/connect/marketplace/essential-tasks"},
  {name:"Workday HCM pattern",focus:"People system of record spanning workforce management, talent, time and payroll governance.",url:"https://www.workday.com/en-us/products/human-capital-management/overview.html"},
  {name:"India DPDP Rules 2025",focus:"Consent, notices, security safeguards, breach handling and data-principal rights for production design.",url:"https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa?pageTitle=Digital-Personal-Data-Protection-Rules-2025%3B"},
  {name:"NIST AI RMF GenAI Profile",focus:"AI risk governance, measurement, human oversight and safe deployment of generative AI.",url:"https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"},
];

const statusClass = (status:Status) => status.toLowerCase().replaceAll(" ","-");

export default function PlatformAuditPanel(){
  const [tab,setTab]=useState<"Coverage"|"Requirements"|"Blockers"|"AI & automation"|"Benchmarks">("Coverage");
  const [filter,setFilter]=useState<"All"|Status>("All");
  const totals=useMemo(()=>areas.reduce((a,x)=>({must:a.must+x.must,verified:a.verified+x.verified,partial:a.partial+x.partial,missing:a.missing+x.missing}),{must:0,verified:0,partial:0,missing:0}),[]);
  const shown=filter==="All"?areas:areas.filter(x=>x.status===filter);
  return <div className={css.audit}>
    <section className={css.hero}><div><span>FULL-PLATFORM CLOSURE AUDIT · 5 AUGUST 2026</span><h2>Honest readiness, evidence and next release gates.</h2><p>Every PawSpace module is classified from the build itself. “Designed” and “integration-ready” are never counted as live or production-safe.</p></div><aside><strong>{totals.verified}</strong><span>of {totals.must} audited requirements verified</span><small>{totals.partial} partial · {totals.missing} missing</small></aside></section>
    <section className={css.truth}><strong>Current release decision</strong><span>Integration-ready UAT / launch-candidate prototype</span><p>Grooming can proceed to controlled staff UAT. PawSpace is not yet approved for unattended public production traffic.</p></section>
    <section className={css.metrics}>{[["Module areas",areas.length,"App to reliability"],["Verified",totals.verified,"Evidence in current build"],["Partial",totals.partial,"Needs completion or connection"],["Missing",totals.missing,"Includes 5 P0 foundations"]].map(x=><article key={String(x[0])}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section>
    <nav className={css.tabs}>{(["Coverage","Requirements","Blockers","AI & automation","Benchmarks"] as const).map(x=><button key={x} className={tab===x?css.active:""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
    {tab==="Coverage"&&<><div className={css.filters}>{(["All","Verified prototype","Partial","Integration-ready","Missing core"] as const).map(x=><button key={x} className={filter===x?css.on:""} onClick={()=>setFilter(x)}>{x}</button>)}</div><section className={css.areaGrid}>{shown.map(x=><article key={x.area}><header><div><span>{x.owner}</span><h3>{x.area}</h3></div><b className={css[statusClass(x.status)]}>{x.status}</b></header><div className={css.coverage}><i><em style={{width:`${Math.round(x.verified/x.must*100)}%`}}/></i><span>{x.verified}/{x.must} verified</span></div><dl><div><dt>Evidence</dt><dd>{x.evidence}</dd></div><div><dt>Gap</dt><dd>{x.gap}</dd></div><div><dt>Next release action</dt><dd>{x.next}</dd></div></dl><footer><span>{x.verified} verified</span><span>{x.partial} partial</span><span>{x.missing} missing</span></footer></article>)}</section></>}
    {tab==="Requirements"&&<section className={css.requirements}><header><span>Priority</span><span>Capability</span><span>Global product pattern</span><span>Audit result</span><span>PawSpace disposition</span></header>{requirements.map(x=><article key={x.capability}><b>{x.priority}</b><strong>{x.capability}</strong><span>{x.globalPattern}</span><em className={css[statusClass(x.status)]}>{x.status}</em><p>{x.disposition}</p></article>)}</section>}
    {tab==="Blockers"&&<><section className={css.blockerIntro}><div><span>RELEASE GATE</span><h3>“Fix everything” is now a governed queue.</h3><p>P0 items block the named launch stage. P1 items block scale or automation; they do not get hidden inside future integration work.</p></div><strong>5 P0<small>4 P1</small></strong></section><section className={css.blockers}>{blockers.map(x=><article key={x[1]}><b className={x[0]==="P0"?css.p0:css.p1}>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div><span><small>Owner</small>{x[3]}</span><span><small>Blocks</small>{x[4]}</span></article>)}</section></>}
    {tab==="AI & automation"&&<section className={css.ai}><div className={css.aiRule}><span>SAFE AUTOMATION ORDER</span><h3>Suggest → approve → execute → measure → expand autonomy</h3><p>Customer messages, discounts, refunds, payouts, employee actions and pet-safety decisions always begin with consent, limits, evidence and human override.</p></div>{[
      ["Now · safe to prepare","Read-only work-order summaries, report narratives, QA checklists, lead prioritisation and suggested next actions.","No external action; show source records and confidence."],
      ["After event + channel connection","Renewal reminders, dormant-customer journeys, booking confirmations and first-response task creation.","Consent, quiet hours, frequency caps, opt-out, retry and outcome logging."],
      ["After trusted availability","Provider matching, route suggestions, capacity alerts and decline rerouting.","Ops approval during pilot; fairness, safety and SLA guardrails."],
      ["Later · high risk","Automatic refunds, payouts, payroll changes, provider penalties or medical/safety decisions.","Maker-checker approval; never autonomous in first production release."],
    ].map(x=><article key={x[0]}><strong>{x[0]}</strong><p>{x[1]}</p><span>{x[2]}</span></article>)}</section>}
    {tab==="Benchmarks"&&<><section className={css.benchmarkIntro}><h3>Reference set used for this audit</h3><p>These are capability benchmarks, not a recommendation to copy another company’s interface or buy all of these products.</p></section><section className={css.benchmarks}>{benchmarks.map(x=><a href={x.url} target="_blank" rel="noreferrer" key={x.name}><div><strong>{x.name}</strong><p>{x.focus}</p></div><span>Official source ↗</span></a>)}</section></>}
    <section className={css.footerNote}><strong>Release truth rule</strong><p>A screen, button, fixture or sandbox adapter is not “complete” until its record persists, permissions are enforced, failures recover, audit evidence exists and the regression gate proves the workflow.</p></section>
  </div>;
}
