"use client";

import { useState } from "react";
import { readOfferConfig, saveOfferConfig, type CustomerKind, type PawspaceCity, type PawspaceService } from "../../lib/offer-engine";
import baseStyles from "./control.module.css";
import offerStyles from "./offers-control-panel.module.css";
const styles={...baseStyles,...offerStyles};
const services:PawspaceService[]=["Grooming","Dog Training","Boarding","Pet Sitting"];
const cities:PawspaceCity[]=["Bengaluru","Mumbai","Delhi NCR","Hyderabad","Chennai","Pune"];
const customerKinds:{id:CustomerKind;label:string}[]=[{id:"new",label:"New"},{id:"existing",label:"Existing"},{id:"subscriber",label:"Subscriber"}];
const money=(value:number)=>`₹${value.toLocaleString("en-IN")}`;
const referralLedger=[
  ["REF-24081","Karthik P","Ananya Rao","Grooming","Completed","₹500 released"],
  ["REF-24082","Shweta S","Rohan Mehta","Dog Training","In service","₹600 pending"],
  ["REF-24083","Ananya Rao","Divya N","Boarding","Confirmed","₹400 pending"],
  ["REF-24084","Rahul K","Vikram S","Pet Sitting","Refunded","Reversed"],
];

export default function ReferralsControlPanel({notify}:{notify:(message:string)=>void}){
  const [config,setConfig]=useState(()=>readOfferConfig());
  const [tab,setTab]=useState<"programme"|"ledger"|"fraud">("programme");
  const policy=config.referral;
  const update=(patch:Partial<typeof policy>,message="Referral programme draft saved")=>{const next={...config,referral:{...policy,...patch}};setConfig(next);saveOfferConfig(next);notify(message);};
  const toggle=<T,>(list:T[],value:T)=>list.includes(value)?list.filter(x=>x!==value):[...list,value];
  return <>
    <section className={styles.referralHero}><div><span>REFERRAL MANAGEMENT · TEST MODE</span><h2>Control how pet parents refer, qualify and earn.</h2><p>Keep referral rewards separate from coupons, with clear qualification, settlement, expiry, reversal and fraud-review rules.</p></div><button className={policy.active?styles.pauseButton:""} onClick={()=>update({active:!policy.active},policy.active?"Referral programme paused":"Referral programme activated")}>{policy.active?"Pause programme":"Activate programme"}</button></section>
    <section className={styles.metrics}>{[["Successful referrals","184","Last 30 days"],["Pending rewards","₹42,600","Release after completion"],["Released rewards","₹71,300","Next-booking credits"],["Fraud review","6","Duplicate device/payment signals"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section>
    <div className={styles.subnav}><button className={tab==="programme"?styles.subnavActive:""} onClick={()=>setTab("programme")}>Programme rules</button><button className={tab==="ledger"?styles.subnavActive:""} onClick={()=>setTab("ledger")}>Referral & reward ledger</button><button className={tab==="fraud"?styles.subnavActive:""} onClick={()=>setTab("fraud")}>Fraud controls</button></div>
    {tab==="programme"&&<section className={styles.referralWorkspace}>
      <div className={styles.panel}><div className={styles.head}><div><span>PROGRAMME DESIGN</span><h2>{policy.programmeName}</h2></div><button onClick={()=>notify("Programme preview opened")}>Customer preview</button></div>
        <div className={styles.formPair}><label>Programme name<input value={policy.programmeName} onChange={e=>update({programmeName:e.target.value})}/></label><label>Friend’s first-booking saving<input type="number" min="300" max="600" step="100" value={policy.friendDiscount} onChange={e=>update({friendDiscount:Number(e.target.value)})}/></label><label>Referrer earns<select value={policy.referrerReward} onChange={e=>update({referrerReward:Number(e.target.value) as 300|400|500|600})}>{policy.rewardChoices.map(v=><option value={v} key={v}>{money(v)}</option>)}</select></label><label>Minimum first order<input type="number" min="0" value={policy.minFirstOrder} onChange={e=>update({minFirstOrder:Number(e.target.value)})}/></label></div>
        <h3 className={styles.sectionTitle}>Who can refer</h3><div className={styles.choiceGrid}>{customerKinds.map(x=><button key={x.id} className={policy.referrerKinds.includes(x.id)?styles.selectedChoice:""} onClick={()=>update({referrerKinds:toggle(policy.referrerKinds,x.id)})}>{x.label} customer</button>)}</div>
        <h3 className={styles.sectionTitle}>Friend’s qualifying first-booking services</h3><div className={styles.choiceGrid}>{services.map(x=><button key={x} className={policy.eligibleServices.includes(x)?styles.selectedChoice:""} onClick={()=>update({eligibleServices:toggle(policy.eligibleServices,x)})}>{x}</button>)}</div>
        <h3 className={styles.sectionTitle}>Where the referrer may use the reward</h3><div className={styles.choiceGrid}>{services.map(x=><button key={x} className={policy.rewardUseServices.includes(x)?styles.crossChoice:""} onClick={()=>update({rewardUseServices:toggle(policy.rewardUseServices,x)})}>{x}</button>)}</div>
        <h3 className={styles.sectionTitle}>Eligible cities</h3><div className={styles.choiceGrid}>{cities.map(x=><button key={x} className={policy.eligibleCities.includes(x)?styles.selectedChoice:""} onClick={()=>update({eligibleCities:toggle(policy.eligibleCities,x)})}>{x}</button>)}</div>
      </div>
      <aside className={styles.panel}><div className={styles.head}><div><span>QUALIFICATION & SETTLEMENT</span><h2>Reward lifecycle</h2></div></div><div className={styles.referralFlow}><article><i>1</i><div><b>Personal code shared</b><span>One code per verified PawSpace account</span></div></article><article><i>2</i><div><b>New friend books</b><span>First booking · min {money(policy.minFirstOrder)} · no stacking</span></div></article><article><i>3</i><div><b>Service completed</b><span>Payment and booking status verified</span></div></article><article><i>4</i><div><b>Reward released</b><span>{money(policy.referrerReward)} credit for the next eligible booking</span></div></article></div>
        <div className={styles.formPair}><label>Rewards per month<input type="number" min="1" value={policy.rewardsPerMonth} onChange={e=>update({rewardsPerMonth:Number(e.target.value)})}/></label><label>Reward validity (days)<input type="number" min="1" value={policy.rewardValidityDays} onChange={e=>update({rewardValidityDays:Number(e.target.value)})}/></label><label>Programme starts<input type="date" value={policy.validFrom} onChange={e=>update({validFrom:e.target.value})}/></label><label>Programme ends<input type="date" value={policy.validUntil} onChange={e=>update({validUntil:e.target.value})}/></label></div>
        <div className={styles.checkRows}><label><input type="checkbox" checked={policy.oneRewardPerFriend} onChange={e=>update({oneRewardPerFriend:e.target.checked})}/> One reward per referred friend</label><label><input type="checkbox" checked={!policy.stackable} onChange={e=>update({stackable:!e.target.checked})}/> Block coupon stacking</label><label><input type="checkbox" checked={policy.reversalOnRefund} onChange={e=>update({reversalOnRefund:e.target.checked})}/> Reverse on cancellation/refund</label></div><button className={styles.savePolicy} onClick={()=>notify("Referral policy submitted with audit note")}>Submit programme for approval</button>
      </aside>
    </section>}
    {tab==="ledger"&&<section className={styles.panel}><div className={styles.toolbar}><div><span>REFERRAL & REWARD LEDGER</span><h2>Every invite, booking and credit</h2></div><input placeholder="Search customer or referral ID"/><select><option>All reward states</option><option>Pending</option><option>Released</option><option>Reversed</option></select></div><div className={styles.ledgerHead}><span>Referral</span><span>Referrer</span><span>Friend</span><span>First service</span><span>Booking state</span><span>Reward state</span></div>{referralLedger.map(row=><article className={styles.ledgerRow} key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===0?styles.ledgerId:i===5?styles.ledgerReward:""}>{cell}</span>)}</article>)}<div className={styles.ledgerFooter}><span>All values are synthetic test records.</span><button onClick={()=>notify("Referral ledger exported")}>Export ledger</button></div></section>}
    {tab==="fraud"&&<section className={styles.referralWorkspace}><div className={styles.panel}><div className={styles.head}><div><span>ABUSE PREVENTION</span><h2>Automatic referral checks</h2></div></div>{[["Same mobile number","Block","Referrer and friend cannot share a verified number"],["Same device or payment method","Review","Hold reward for Operations review"],["Repeated cancellation/refund","Block","Reverse reward and pause the account"],["Self-referral pattern","Review","Match household, address and device signals"],["Monthly velocity",`${policy.rewardsPerMonth} max`,`Stop rewards beyond the configured customer limit`]].map(x=><article className={styles.controlRule} key={x[0]}><div><strong>{x[0]}</strong><small>{x[2]}</small></div><b>{x[1]}</b><button onClick={()=>notify(`${x[0]} rule opened`)}>Configure</button></article>)}</div><aside className={styles.panel}><span className={styles.kicker}>REVIEW QUEUE</span><h2>6 referrals need attention</h2><p className={styles.muted}>Credits remain pending until Operations clears the signals.</p>{[["REF-24076","Same UPI ID","High"],["REF-24079","Shared device","Medium"],["REF-24080","Three refunds","High"]].map(x=><article className={styles.reviewItem} key={x[0]}><div><strong>{x[0]}</strong><small>{x[1]}</small></div><b>{x[2]}</b><button onClick={()=>notify("Referral evidence opened")}>Review</button></article>)}</aside></section>}
  </>;
}
