"use client";
import { useState } from "react";
import styles from "./scheduling-control-panel.module.css";

const verticals = [
  {id:"grooming",name:"Grooming",mode:"Timed appointment",rules:["Published groomer roster","Skill, city and zone eligibility","120-minute service duration","30-minute travel buffer","Overlap and daily-job limits","Full-time auto-assign / partner offer"]},
  {id:"training",name:"Training",mode:"Recurring series",rules:["Same trainer across the programme","1–12 sessions generated together","Single cadence or multi-day weekly pattern","Every occurrence checked and reserved","Travel buffer and overlap prevention","Series returned to Ops if one date fails"]},
  {id:"boarding",name:"Boarding",mode:"Date-range capacity",rules:["Verified vaccination gate","Host city and zone eligibility","All stay dates checked","Pet capacity locked across date range","Concurrent stay overlap counted","Decline reroute and Ops override"]},
  {id:"sitting",name:"Pet Sitting",mode:"Visit or overnight",rules:["Visit and overnight care modes","Sitter roster by date","Timed-visit travel buffer","Overnight capacity lock","Daily visit limit","Decline reroute and Ops override"]},
];

export default function SchedulingControlPanel({notify}:{notify:(message:string)=>void}){
  const [selected,setSelected]=useState(verticals[0]);
  const [tab,setTab]=useState<"rules"|"custom"|"uat"|"exceptions">("rules");
  const [assignmentMode,setAssignmentMode]=useState<"auto"|"admin_choice">("admin_choice");
  const [ruleName,setRuleName]=useState("Whitefield peak-hour quality gate");
  const [ruleField,setRuleField]=useState("rating");
  const [ruleValue,setRuleValue]=useState("4.7");
  const [savedRules,setSavedRules]=useState(["Boarding capacity by host and date range","Training same-trainer continuity"]);
  const [deskStatus,setDeskStatus]=useState("Not created");
  const [deskChoices,setDeskChoices]=useState([['groom_arun','Arun R.','96','Full-time · 2.8 km'],['groom_kiran','Kiran S.','92','Commission · repeat groomer'],['groom_sanjay','Sanjay P.','89','Full-time · 4.1 km']]);
  const saveRule=async()=>{const response=await fetch("/api/scheduling-rules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:ruleName,serviceCode:selected.id==="training"?"dog_training":selected.id==="sitting"?"pet_sitting":selected.id,cityId:"blr",zoneId:"blr-east",conditions:[{code:`custom_${ruleField}`,field:ruleField,operator:ruleField==="model"?"eq":"gte",value:ruleField==="model"?ruleValue:Number(ruleValue)}]})});if(response.ok){setSavedRules(current=>[ruleName,...current]);notify("Custom scheduling rule saved and activated");}else notify("Rule could not be saved");};
  const createDeskOrder=async()=>{const response=await fetch("/api/uat-scheduling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reserve",assignmentStrategy:"admin_choice",clientRequestId:"admin-demo-PS-UAT-2408",customerId:"TST-OPS",petIds:["Bruno"],serviceCode:"grooming",zoneId:"blr-east",scheduledStart:"2026-08-30T03:30:00.000Z",scheduledEnd:"2026-08-30T05:30:00.000Z"})});const body=await response.json() as {data?:{status?:string;shortlist?:Array<{provider:{id:string;name:string};score:number}>}};if(response.ok&&body.data){if(body.data.shortlist)setDeskChoices(body.data.shortlist.map(item=>[item.provider.id,item.provider.name,String(item.score),'Eligible provider']));setDeskStatus(body.data.status??"awaiting_admin");notify("Test order created with three ranked choices");}else notify("Test shortlist could not be created");};
  const deskAction=async(action:"assign"|"cancel"|"reassign"|"manual",providerId?:string)=>{const response=await fetch("/api/uat-scheduling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,groupId:"admin-demo-PS-UAT-2408",clientRequestId:"admin-demo-PS-UAT-2408",providerId,reason:action==="manual"?"Ops selected provider after customer request":`${action} by Admin`,customerId:"TST-OPS",petIds:["Bruno"],serviceCode:"grooming",zoneId:"blr-east",scheduledStart:"2026-08-30T03:30:00.000Z",scheduledEnd:"2026-08-30T05:30:00.000Z"})});const body=await response.json() as {data?:{status?:string;provider?:{name:string}};error?:string};if(response.ok){setDeskStatus(body.data?.status??action);notify(body.data?.provider?`${body.data.provider.name} assigned`: `Order ${action} completed`);}else notify(body.error??"Assignment action failed");};
  return <div className={styles.wrap}>
    <section className={styles.hero}>
      <div><span>COMMON ENGINE · FOUR RULE PACKS</span><h2>Auto-scheduling control</h2><p>One scheduling source of truth for provider rosters, live booking conflicts, capacity, recurring sessions, offers, rerouting and authorised Ops overrides.</p></div>
      <div className={styles.release}><i>READY</i><strong>Scheduling UAT</strong><small>Executable backend rules</small></div>
    </section>
    <section className={styles.metrics}>
      {[['Verticals connected','4/4'],['Rule checks','10'],['Scheduling tests','8/8'],['Assignment modes','3']].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></article>)}
    </section>
    <section className={styles.mode}><div><span>DEFAULT ASSIGNMENT MODE</span><strong>{assignmentMode==="auto"?"Auto-assign top provider":"Admin chooses from top 3"}</strong><p>Can be changed per order by authorised Admin/Ops.</p></div><button className={assignmentMode==="auto"?styles.on:""} onClick={()=>setAssignmentMode("auto")}>Auto-assign</button><button className={assignmentMode==="admin_choice"?styles.on:""} onClick={()=>setAssignmentMode("admin_choice")}>3 choices + Admin</button></section>
    <div className={styles.tabs}>{(['rules','custom','uat','exceptions'] as const).map(x=><button key={x} className={tab===x?styles.active:""} onClick={()=>setTab(x)}>{x==='rules'?'Rule packs':x==='custom'?'Custom rules':x==='uat'?'UAT scenarios':'Order assignment desk'}</button>)}</div>
    {tab==='rules'&&<section className={styles.grid}>
      <aside>{verticals.map(v=><button key={v.id} onClick={()=>setSelected(v)} className={selected.id===v.id?styles.selected:""}><i>{v.name.charAt(0)}</i><div><strong>{v.name}</strong><small>{v.mode}</small></div><b>✓</b></button>)}</aside>
      <div className={styles.panel}><header><div><span>ACTIVE RULE PACK</span><h3>{selected.name}</h3><p>{selected.mode}</p></div><em>Enabled</em></header>{selected.rules.map((rule,index)=><article key={rule}><i>{index+1}</i><span>{rule}</span><b>Enforced</b></article>)}<div className={styles.trace}><strong>Decision trace saved</strong><p>Each booking stores the schedule group, occurrence number, provider evaluation and assignment explanation for Ops review.</p></div></div>
    </section>}
    {tab==='custom'&&<section className={styles.two}><div className={styles.panel}><header><div><span>BUSINESS RULE BUILDER</span><h3>Add a scheduling constraint</h3><p>Rules are saved centrally and applied before providers are ranked.</p></div></header><label>Rule name<input value={ruleName} onChange={event=>setRuleName(event.target.value)}/></label><label>Vertical<select value={selected.id} onChange={event=>setSelected(verticals.find(item=>item.id===event.target.value)??verticals[0])}>{verticals.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Location<select><option>Bengaluru · East zone</option><option>Bengaluru · South zone</option><option>All Bengaluru</option></select></label><label>Constraint<select value={ruleField} onChange={event=>setRuleField(event.target.value)}><option value="rating">Minimum rating</option><option value="qualityScore">Minimum quality score</option><option value="capacity">Minimum capacity</option><option value="model">Provider model</option></select></label><label>Required value<input value={ruleValue} onChange={event=>setRuleValue(event.target.value)}/></label><button className={styles.save} onClick={saveRule}>Save & activate rule</button></div><div className={styles.panel}><header><div><span>ACTIVE CUSTOM RULES</span><h3>{savedRules.length} business constraints</h3></div></header>{savedRules.map((rule,index)=><article key={rule}><i>{index+1}</i><span>{rule}</span><b>Active</b></article>)}<div className={styles.trace}><strong>Future-extensible</strong><p>New city, zone, service, package, provider, rating, quality and capacity rules can be added without changing the booking screens.</p></div></div></section>}
    {tab==='uat'&&<section className={styles.panel}><header><div><span>REQUIRED TEST SET</span><h3>Auto-scheduling sign-off journeys</h3><p>Run both success and failure paths before release approval.</p></div><button onClick={()=>notify('Scheduling UAT run created')}>Create UAT run</button></header>{[
      ['Grooming','Available groomer is assigned; overlapping or travel-buffer slot is blocked.'],['Training','All recurring sessions reserve one trainer; any unavailable occurrence returns an exception.'],['Boarding','Capacity remains locked across check-in/check-out dates; excess pets are rejected.'],['Pet Sitting','Visit conflict and overnight capacity are checked separately.'],['Provider decline','Three-minute partner offer reroutes to the next eligible provider.'],['Ops recovery','Authorised reschedule or provider override requires a reason and creates an audit event.'],['Concurrency','Second request for the same resource must receive conflict/manual review, never a silent double booking.']
    ].map((x,i)=><article className={styles.scenario} key={x[0]}><i>{i+1}</i><div><strong>{x[0]}</strong><p>{x[1]}</p></div><span>{i<6?'Automated check':'Production DB gate'}</span></article>)}</section>}
    {tab==='exceptions'&&<><section className={styles.panel}><header><div><span>ORDER PS-UAT-2408 · GROOMING</span><h3>Choose one of 3 eligible providers</h3><p>All choices passed roster, location, skill, overlap, buffer and custom business rules.</p></div><em>{deskStatus}</em></header>{deskChoices.map((item,index)=><article className={styles.choice} key={item[0]}><i>{index+1}</i><div><strong>{item[1]}</strong><p>{item[3]} · score {item[2]}</p></div><button onClick={()=>deskAction("assign",item[0])}>Assign</button></article>)}<div className={styles.actions}><button onClick={createDeskOrder}>Create/reset test shortlist</button><button onClick={()=>deskAction("reassign")}>Next 3 choices</button><button onClick={()=>deskAction("manual","groom_kiran")}>Manual assign</button><button onClick={()=>deskAction("cancel")}>Cancel order</button></div></section><section className={styles.two}><div className={styles.panel}><header><div><span>AUTOMATIC RECOVERY</span><h3>Reroute order</h3></div></header>{['Exclude declined/expired provider','Recheck roster, conflicts and capacity','Rank next three eligible providers','Admin selects or system auto-assigns','Move to manual review when none pass'].map((x,i)=><article key={x}><i>{i+1}</i><span>{x}</span></article>)}</div><div className={styles.panel}><header><div><span>CONTROLLED OVERRIDE</span><h3>Ops safeguards</h3></div></header>{['Operations/Admin role required','Provider must still pass safety, skill and capacity rules','Minimum eight-character reason','Cancel, replace and reassign are retained','Decision and explanation added to audit trail'].map(x=><article key={x}><b>✓</b><span>{x}</span></article>)}</div></section></>}
    <section className={styles.note}><strong>UAT boundary</strong><p>The scheduling logic is executable and ready for functional testing. Final simultaneous-booking protection still requires the production database transaction/unique-lock layer before public launch.</p></section>
  </div>;
}
