import{refuseUnlessGatewayPermits}from"../../../lib/api-gateway";
import{findExpenseCategory}from"../../../lib/chart-of-accounts";
import{repairSchemaDrift}from"../../../lib/schema-drift-repair";

type Db = Awaited<ReturnType<typeof database>>;
async function database(){const {env}=await import("cloudflare:workers");return env.DB;}
const json=(data:unknown,status=200)=>Response.json(data,{status});
const id=(prefix:string)=>`${prefix}_${crypto.randomUUID().slice(0,12)}`;
type Row=Record<string,unknown>;

async function ensureSchema(db:Db){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS finance_expenses (id text PRIMARY KEY NOT NULL,expense_date text NOT NULL,claimant text NOT NULL,merchant text NOT NULL,category text NOT NULL,cost_centre text NOT NULL,vertical text NOT NULL,amount real NOT NULL,gst_amount real DEFAULT 0 NOT NULL,payment_mode text NOT NULL,receipt_reference text,status text DEFAULT 'submitted' NOT NULL,duplicate_risk integer DEFAULT 0 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_vendors (id text PRIMARY KEY NOT NULL,name text NOT NULL,gstin text,pan text,payment_terms_days integer DEFAULT 30 NOT NULL,bank_reference text,tds_section text,status text DEFAULT 'active' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_bills (id text PRIMARY KEY NOT NULL,vendor_id text NOT NULL,bill_number text NOT NULL,bill_date text NOT NULL,due_date text NOT NULL,cost_centre text NOT NULL,vertical text NOT NULL,taxable_amount real NOT NULL,gst_amount real NOT NULL,tds_amount real DEFAULT 0 NOT NULL,total_amount real NOT NULL,status text DEFAULT 'draft' NOT NULL,purchase_order_id text,attachment_reference text,created_at integer NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_journal_entries (id text PRIMARY KEY NOT NULL,entry_date text NOT NULL,source_type text NOT NULL,source_id text NOT NULL,account_code text NOT NULL,cost_centre text,vertical text,debit real DEFAULT 0 NOT NULL,credit real DEFAULT 0 NOT NULL,narration text NOT NULL,period_code text NOT NULL,posted integer DEFAULT 0 NOT NULL,created_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_bank_transactions (id text PRIMARY KEY NOT NULL,bank_account text NOT NULL,transaction_date text NOT NULL,reference text NOT NULL,description text NOT NULL,amount real NOT NULL,match_type text,matched_source_id text,status text DEFAULT 'unmatched' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_budgets (id text PRIMARY KEY NOT NULL,period_code text NOT NULL,cost_centre text NOT NULL,vertical text NOT NULL,category text NOT NULL,budget_amount real NOT NULL,alert_threshold real DEFAULT 90 NOT NULL,approved_by text,created_at integer NOT NULL,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_close_periods (period_code text PRIMARY KEY NOT NULL,status text DEFAULT 'open' NOT NULL,checklist_json text NOT NULL,locked_at integer,locked_by text,updated_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS finance_audit_events (id text PRIMARY KEY NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,action text NOT NULL,before_json text,after_json text NOT NULL,actor_id text NOT NULL,reason text NOT NULL,created_at integer NOT NULL)"),
]);
 for(const table of ["finance_expenses","finance_bills"]){
  const columns=await db.prepare(`PRAGMA table_info(${table})`).all<Row>();
  if(!columns.results.some(row=>String(row.name)==="category_code")){
   await db.prepare(`ALTER TABLE ${table} ADD COLUMN category_code text`).run();
  }
 }
 // finance_close_periods is also declared by lib/gst-accounting.ts, which used to omit
 // checklist_json. On any database where that module created the table first, every close write here
 // failed. Repair it in place - the unified declarations only help a fresh database.
 await repairSchemaDrift(db);
}

function resolveAccountCode(categoryCode:string|undefined,fallback:string):string{
 if(!categoryCode)return fallback;
 const entry=findExpenseCategory(categoryCode);
 return entry?entry.accountCode:fallback;
}

async function audit(db:Db,entityType:string,entityId:string,action:string,after:unknown,reason:string){await db.prepare("INSERT INTO finance_audit_events (id,entity_type,entity_id,action,before_json,after_json,actor_id,reason,created_at) VALUES (?,?,?,?,NULL,?,'finance_uat',?,?)").bind(id("fin_audit"),entityType,entityId,action,JSON.stringify(after),reason,Date.now()).run();}
async function periodLocked(db:Db,date:string){const code=date.slice(0,7);const row=await db.prepare("SELECT status FROM finance_close_periods WHERE period_code=?").bind(code).first<{status:string}>();return row?.status==="locked";}
async function postBalancedJournal(db:Db,sourceType:string,sourceId:string,date:string,debitAccount:string,creditAccount:string,amount:number,narration:string,costCentre:string,vertical:string){
 if(await periodLocked(db,date))throw new Error("period_locked");
 const period=date.slice(0,7),now=Date.now(),group=id("journal");
 const lines=[{account:debitAccount,debit:amount,credit:0},{account:creditAccount,debit:0,credit:amount}];
 const debits=lines.reduce((s,x)=>s+x.debit,0),credits=lines.reduce((s,x)=>s+x.credit,0);if(Math.abs(debits-credits)>.001)throw new Error("Journal debits and credits must balance");
 for(const [i,line] of lines.entries())await db.prepare("INSERT INTO finance_journal_entries (id,entry_date,source_type,source_id,account_code,cost_centre,vertical,debit,credit,narration,period_code,posted,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(`${group}_${i+1}`,date,sourceType,sourceId,line.account,costCentre,vertical,line.debit,line.credit,narration,period,1,now).run();
}

async function seed(db:Db){await ensureSchema(db);const now=Date.now();
 const vendors=[["ven_fuel","Shell Fleet Services","29AAACS0001A1Z5","194C"],["ven_food","Happy Tails Foods","29AAHFT2201B1Z9","194Q"],["ven_software","Cloud Software India","29AABCC2233D1ZA","194J"]] as const;
 for(const v of vendors)await db.prepare("INSERT OR IGNORE INTO finance_vendors (id,name,gstin,pan,payment_terms_days,bank_reference,tds_section,status,created_at,updated_at) VALUES (?,?,?,NULL,30,'masked',?,'active',?,?)").bind(v[0],v[1],v[2],v[3],now,now).run();
 await db.prepare("INSERT OR IGNORE INTO finance_expenses (id,expense_date,claimant,merchant,category,cost_centre,vertical,amount,gst_amount,payment_mode,receipt_reference,status,duplicate_risk,created_at,updated_at) VALUES ('exp_1001','2026-08-02','Arun K','Shell','Travel & fuel','Bengaluru Ops','Grooming',2840,433,'Corporate card','RCPT-8421','approval_due',0,?,?)").bind(now,now).run();
 await db.prepare("INSERT OR IGNORE INTO finance_expenses (id,expense_date,claimant,merchant,category,cost_centre,vertical,amount,gst_amount,payment_mode,receipt_reference,status,duplicate_risk,created_at,updated_at) VALUES ('exp_1002','2026-08-01','Priya S','Quick Print','Marketing collateral','Growth','All verticals',11800,1800,'Employee paid','INV-QP-118','held',1,?,?)").bind(now,now).run();
 await db.prepare("INSERT OR IGNORE INTO finance_bills (id,vendor_id,bill_number,bill_date,due_date,cost_centre,vertical,taxable_amount,gst_amount,tds_amount,total_amount,status,purchase_order_id,attachment_reference,created_at,updated_at) VALUES ('bill_2001','ven_food','HTF-882','2026-07-28','2026-08-12','Boarding Ops','Boarding',48000,8640,0,56640,'approval_due','PO-2241','receipt://uat/htf-882',?,?)").bind(now,now).run();
 await db.prepare("INSERT OR IGNORE INTO finance_close_periods (period_code,status,checklist_json,locked_at,locked_by,updated_at) VALUES ('2026-07','review','[\"Bank reconciled\",\"GST reviewed\",\"Payroll posted\",\"Accruals approved\"]',NULL,NULL,?)").bind(now).run();
}

export async function GET(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const db=await database();await seed(db);const [expenses,bills,vendors,journals,bank,budgets,periods,audits]=await Promise.all([
 db.prepare("SELECT * FROM finance_expenses ORDER BY updated_at DESC LIMIT 50").all(),db.prepare("SELECT b.*,v.name vendor_name FROM finance_bills b LEFT JOIN finance_vendors v ON v.id=b.vendor_id ORDER BY b.updated_at DESC LIMIT 50").all(),db.prepare("SELECT * FROM finance_vendors ORDER BY name").all(),db.prepare("SELECT * FROM finance_journal_entries ORDER BY created_at DESC LIMIT 60").all(),db.prepare("SELECT * FROM finance_bank_transactions ORDER BY updated_at DESC LIMIT 50").all(),db.prepare("SELECT * FROM finance_budgets ORDER BY period_code DESC LIMIT 50").all(),db.prepare("SELECT * FROM finance_close_periods ORDER BY period_code DESC").all(),db.prepare("SELECT * FROM finance_audit_events ORDER BY created_at DESC LIMIT 30").all()]);
 return json({data:{expenses:expenses.results,bills:bills.results,vendors:vendors.results,journals:journals.results,bank:bank.results,budgets:budgets.results,periods:periods.results,audits:audits.results,sourceStatus:{bookings:"connected UAT",payroll:"integration-ready",bankFeed:"import-ready",ocr:"integration-ready",gstFiling:"integration-ready",accountingExport:"Tally / Zoho Books ready"}}});}catch(error){return json({error:error instanceof Error?error.message:"Finance control failed"},500);}}

export async function POST(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const db=await database();await seed(db);const body=await request.json() as Record<string,unknown>,entity=String(body.entity??""),now=Date.now();
 if(entity==="expense"){const amount=Number(body.amount),date=String(body.expenseDate??"");if(!date||!body.merchant||!body.category||amount<=0)return json({error:"Date, merchant, category and a positive amount are required"},400);if(await periodLocked(db,date))return json({error:"period_locked"},409);const expenseId=id("exp"),duplicate=await db.prepare("SELECT id FROM finance_expenses WHERE merchant=? AND amount=? AND expense_date=? LIMIT 1").bind(body.merchant,amount,date).first();await db.prepare("INSERT INTO finance_expenses (id,expense_date,claimant,merchant,category,category_code,cost_centre,vertical,amount,gst_amount,payment_mode,receipt_reference,status,duplicate_risk,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(expenseId,date,body.claimant??"Current user",body.merchant,body.category,body.categoryCode??null,body.costCentre??"Bengaluru Ops",body.vertical??"All verticals",amount,Number(body.gstAmount??0),body.paymentMode??"Employee paid",body.receiptReference??null,duplicate?"held":"submitted",duplicate?1:0,now,now).run();await audit(db,"expense",expenseId,"created",body,"Expense submitted");return json({data:{id:expenseId,status:duplicate?"held":"submitted",duplicateRisk:Boolean(duplicate)}},201);}
 if(entity==="bill"){const total=Number(body.totalAmount),date=String(body.billDate??"");if(!date||!body.vendorId||!body.billNumber||total<=0)return json({error:"Vendor, bill number, date and total are required"},400);if(await periodLocked(db,date))return json({error:"period_locked"},409);const billId=id("bill");await db.prepare("INSERT INTO finance_bills (id,vendor_id,bill_number,bill_date,due_date,cost_centre,vertical,taxable_amount,gst_amount,tds_amount,total_amount,status,purchase_order_id,attachment_reference,category_code,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(billId,body.vendorId,body.billNumber,date,body.dueDate??date,body.costCentre??"Bengaluru Ops",body.vertical??"All verticals",Number(body.taxableAmount??total),Number(body.gstAmount??0),Number(body.tdsAmount??0),total,"draft",body.purchaseOrderId??null,body.attachmentReference??null,body.categoryCode??null,now,now).run();await audit(db,"bill",billId,"created",body,"Vendor bill created");return json({data:{id:billId,status:"draft"}},201);}
 return json({error:"Unsupported finance entity"},400);
 }catch(error){return json({error:error instanceof Error?error.message:"Finance save failed"},500);}}

export async function PATCH(request:Request){const denied=await refuseUnlessGatewayPermits(request);if(denied)return denied;try{const db=await database();await seed(db);const body=await request.json() as {entity?:string;id?:string;action?:string;reason?:string;actorRole?:string};if(!body.id||!body.action||!body.reason||body.reason.trim().length<5)return json({error:"A reason of at least 5 characters is required"},400);if(body.actorRole==="maker")return json({error:"Maker cannot approve their own transaction"},403);const now=Date.now();
 if(body.entity==="expense"){const row=await db.prepare("SELECT * FROM finance_expenses WHERE id=?").bind(body.id).first<Record<string,unknown>>();if(!row)return json({error:"Expense not found"},404);const status=body.action==="approve"?"approved":body.action==="reject"?"rejected":body.action==="pay"?"paid":"held";await db.prepare("UPDATE finance_expenses SET status=?,updated_at=? WHERE id=?").bind(status,now,body.id).run();if(status==="approved")await postBalancedJournal(db,"expense",body.id,String(row.expense_date),resolveAccountCode(row.category_code?String(row.category_code):undefined,"6200-Operating expense"),"2100-Expense payable",Number(row.amount),String(row.merchant),String(row.cost_centre),String(row.vertical));await audit(db,"expense",body.id,body.action,{status},body.reason);return json({data:{id:body.id,status}});}
 if(body.entity==="bill"){const row=await db.prepare("SELECT * FROM finance_bills WHERE id=?").bind(body.id).first<Record<string,unknown>>();if(!row)return json({error:"Bill not found"},404);const status=body.action==="approve"?"approved":body.action==="pay"?"paid":"rejected";await db.prepare("UPDATE finance_bills SET status=?,updated_at=? WHERE id=?").bind(status,now,body.id).run();if(status==="approved")await postBalancedJournal(db,"vendor_bill",body.id,String(row.bill_date),resolveAccountCode(row.category_code?String(row.category_code):undefined,"6300-Vendor expense"),"2200-Accounts payable",Number(row.total_amount),String(row.bill_number),String(row.cost_centre),String(row.vertical));await audit(db,"bill",body.id,body.action,{status},body.reason);return json({data:{id:body.id,status}});}
 if(body.entity==="period"&&body.action==="lock"){await db.prepare("INSERT INTO finance_close_periods (period_code,status,checklist_json,locked_at,locked_by,updated_at) VALUES (?,'locked','[]',?,'finance_uat',?) ON CONFLICT(period_code) DO UPDATE SET status='locked',locked_at=excluded.locked_at,locked_by=excluded.locked_by,updated_at=excluded.updated_at").bind(body.id,now,now).run();await audit(db,"period",body.id,"locked",{status:"locked"},body.reason);return json({data:{id:body.id,status:"locked"}});}
 return json({error:"Unsupported finance change"},400);
 }catch(error){const message=error instanceof Error?error.message:"Finance update failed";return json({error:message},message==="period_locked"?409:500);}}
