import{authError,database,requirePermission,resolveActor,securityAudit}from"../../../lib/server-auth";
import{resolvePlatformSession}from"../../../lib/platform-session";
import{resolveLivePrice}from"../../../lib/live-pricing-resolver";
import{listProviderServiceRates,saveProviderServiceRate}from"../../../lib/provider-service-pricing";
import{resolveCommercialTerm}from"../../../lib/provider-commercial-terms";
import{listLiveBoardingPackages,listLiveSittingPackages}from"../../../lib/live-commercial-quotes";
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{"cache-control":"no-store"}});
function sameOrigin(r:Request){const o=r.headers.get("origin");if(o&&o!==new URL(r.url).origin)throw new Response("Cross-origin provider pricing write blocked",{status:403});}
export async function GET(request:Request){try{const db=await database(),session=await resolvePlatformSession(db,request),actor=await resolveActor(request);let providerId=String(new URL(request.url).searchParams.get("providerId")||"").trim();if(session?.subjectType==="provider")providerId=session.subjectId;else requirePermission(actor,"pricing.manage");if(!providerId)return json({error:"Provider is required"},400);const profile=await db.prepare("SELECT city_id,zones_json FROM provider_capacity_profiles WHERE id=?").bind(providerId).first<{city_id?:string;zones_json?:string}>().catch(()=>null),cityId=String(profile?.city_id||"blr").toLowerCase();let zones:string[]=[];try{zones=JSON.parse(String(profile?.zones_json||"[]"));}catch{}const zoneId=String(zones[0]||`${cityId}-east`).toLowerCase(),options:Array<Record<string,unknown>>=[];for(const serviceCode of ["boarding","pet_sitting"]){const term=await resolveCommercialTerm(db,{serviceCode,providerId});if(String(term?.engagement_model||"")!=="commission_standard")continue;const packages=serviceCode==="boarding"?await listLiveBoardingPackages(db,{cityId,zoneId}):await listLiveSittingPackages(db,{cityId,zoneId});for(const raw of packages){const item=raw as Record<string,unknown>;if(serviceCode==="pet_sitting"){if(String(item.mode)==="visit"){options.push({serviceCode,packageCode:"sitting-4h",name:"Pet Sitting · 4 hours",floorPrice:Number(item.base_price_per_pet),cityId,zoneId},{serviceCode,packageCode:"sitting-12h",name:"Pet Sitting · 12 hours",floorPrice:Number(item.base_price_per_pet),cityId,zoneId});}else options.push({serviceCode,packageCode:"sitting-24h",name:"Pet Sitting · 24 hours / overnight",floorPrice:Number(item.base_price_per_pet),cityId,zoneId});}else options.push({serviceCode,packageCode:String(item.package_code),name:String(item.name),floorPrice:Number(item.base_price_per_pet),cityId,zoneId});}}return json({data:{rates:await listProviderServiceRates(db,providerId),options,cityId,zoneId}});}catch(error){return authError(error,"Unable to load provider service rates");}}
export async function POST(request:Request){try{sameOrigin(request);const db=await database(),session=await resolvePlatformSession(db,request),actor=await resolveActor(request),body=await request.json() as{providerId?:string;serviceCode?:string;packageCode?:string;cityId?:string;zoneId?:string;rate?:number;effectiveFrom?:string};let providerId=String(body.providerId||"").trim();if(session?.subjectType==="provider"){if(providerId&&providerId!==session.subjectId)return json({error:"You can only change your own rates"},403);providerId=session.subjectId;}else requirePermission(actor,"pricing.manage");const serviceCode=String(body.serviceCode||""),packageCode=String(body.packageCode||""),cityId=String(body.cityId||"blr").toLowerCase(),zoneId=String(body.zoneId||"blr-east").toLowerCase();if(!providerId||!serviceCode||!packageCode||!Number.isFinite(Number(body.rate)))return json({error:"Provider, service, package and rate are required"},400);const table=serviceCode==="boarding"?"boarding_commercial_packages":serviceCode==="pet_sitting"?"sitting_commercial_packages":"";if(!table)return json({error:"Self-pricing is enabled only for Boarding and Pet Sitting"},409);const floorPackageCode=serviceCode==="pet_sitting"?(packageCode==="sitting-24h"?"sitting-overnight":"sitting-visit-60"):packageCode;const base=await db.prepare(`SELECT base_price_per_pet FROM ${table} WHERE package_code=? AND active=1 ORDER BY version DESC LIMIT 1`).bind(floorPackageCode).first<{base_price_per_pet:number}>();if(!base)return json({error:"PawSpace minimum price is not configured for this package"},409);const floor=await resolveLivePrice(db,{packageCode:floorPackageCode,fallbackPrice:Number(base.base_price_per_pet),scheduledStart:new Date().toISOString(),cityId,zoneId});const data=await saveProviderServiceRate(db,{providerId,serviceCode,packageCode,cityId,zoneId,rate:Number(body.rate),floorPrice:floor.price,effectiveFrom:body.effectiveFrom,actorId:session?.subjectType==="provider"?providerId:actor.email});await securityAudit(db,actor,"provider_service_rate.save","provider",providerId,"completed",{serviceCode,packageCode,rate:data.rate,floorPrice:data.floorPrice});return json({data},201);}catch(error){return authError(error,"Unable to save provider service rate");}}
