import{authError,authorize,database,securityAudit}from"../../../lib/server-auth";
import{activateLeadSlaPolicy,leadSlaDirectory,pauseLeadSlaClock,recordLeadSlaAction,resumeLeadSlaClock,runLeadSlaGovernance,saveLeadSlaPolicy,startLeadSlaClock}from"../../../lib/lead-sla-governance";

type Row=Record<string,unknown>;
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});

export async function GET(request:Request){try{await authorize(request,"customers.view");const db=await database(),url=new URL(request.url),asOf=url.searchParams.get("asOf");return json({directory:await leadSlaDirectory(db,asOf?Number(asOf):Date.now()),productionReady:false});}catch(error){return authError(error,"Unable to load lead SLA governance");}}

export async function POST(request:Request){try{const db=await database(),body=await request.json() as Row,action=String(body.action||"").trim();
 if(action==="record_action"){const actor=await authorize(request,"customers.view");const data=await recordLeadSlaAction(db,{leadId:String(body.leadId||""),actionType:String(body.actionType||""),outcome:String(body.outcome||""),nextClockType:String(body.nextClockType||"")?String(body.nextClockType) as "follow_up"|"quote_follow_up"|"high_intent":null,idempotencyKey:String(body.idempotencyKey||""),actorId:actor.email,asOf:body.asOf==null?undefined:Number(body.asOf)});await securityAudit(db,actor,"lead.sla.action","lead",String(body.leadId||""),"completed",{outcome:String(body.outcome||""),nextClockType:body.nextClockType||null});return json({data,productionReady:false});}
 const actor=await authorize(request,"customers.manage");
 if(action==="save_policy"){const data=await saveLeadSlaPolicy(db,{id:String(body.id||"")||undefined,name:String(body.name||""),teamCode:String(body.teamCode||""),serviceCodes:Array.isArray(body.serviceCodes)?body.serviceCodes.map(String):[],cityIds:Array.isArray(body.cityIds)?body.cityIds.map(String):[],timezone:String(body.timezone||"Asia/Kolkata"),businessHours:(body.businessHours&&typeof body.businessHours==="object"?body.businessHours:{mode:"elapsed"}) as {mode:"elapsed"|"windowed";weekdays?:Record<string,{startMinute:number;endMinute:number}>},firstResponseMinutes:body.firstResponseMinutes==null?null:Number(body.firstResponseMinutes),followUpMinutes:body.followUpMinutes==null?null:Number(body.followUpMinutes),quoteFollowUpMinutes:body.quoteFollowUpMinutes==null?null:Number(body.quoteFollowUpMinutes),highIntentMinutes:body.highIntentMinutes==null?null:Number(body.highIntentMinutes),managerEscalationAfterMinutes:body.managerEscalationAfterMinutes==null?null:Number(body.managerEscalationAfterMinutes),reassignmentAfterMinutes:body.reassignmentAfterMinutes==null?null:Number(body.reassignmentAfterMinutes),requireNextAction:Boolean(body.requireNextAction),terminalOutcomes:Array.isArray(body.terminalOutcomes)?body.terminalOutcomes.map(String):[],effectiveFrom:Number(body.effectiveFrom),effectiveUntil:body.effectiveUntil==null?null:Number(body.effectiveUntil),reason:String(body.reason||""),actorId:actor.email});await securityAudit(db,actor,"lead.sla.policy.save","lead_sla_policy",data.id,"completed",{version:data.version,status:data.status});return json({data,productionReady:false},201);}
 if(action==="activate_policy"){const data=await activateLeadSlaPolicy(db,{policyId:String(body.policyId||""),approvalReference:String(body.approvalReference||""),reason:String(body.reason||""),actorId:actor.email});await securityAudit(db,actor,"lead.sla.policy.activate","lead_sla_policy",data.id,"completed",{version:data.version,status:data.status});return json({data,productionReady:false});}
 if(action==="start_clock"){const data=await startLeadSlaClock(db,{leadId:String(body.leadId||""),clockType:String(body.clockType||"") as "first_response"|"follow_up"|"quote_follow_up"|"high_intent",idempotencyKey:String(body.idempotencyKey||""),actorId:actor.email,asOf:body.asOf==null?undefined:Number(body.asOf),cycle:body.cycle==null?undefined:Number(body.cycle)});await securityAudit(db,actor,"lead.sla.clock.start","lead",String(body.leadId||""),"completed",{clockType:String(body.clockType||"")});return json({data,productionReady:false});}
 if(action==="pause_clock"){const data=await pauseLeadSlaClock(db,{clockId:String(body.clockId||""),reason:String(body.reason||""),actorId:actor.email,asOf:body.asOf==null?undefined:Number(body.asOf)});await securityAudit(db,actor,"lead.sla.clock.pause","lead_sla_clock",String(body.clockId||""),"completed",data);return json({data,productionReady:false});}
 if(action==="resume_clock"){const data=await resumeLeadSlaClock(db,{clockId:String(body.clockId||""),reason:String(body.reason||""),actorId:actor.email,asOf:body.asOf==null?undefined:Number(body.asOf)});await securityAudit(db,actor,"lead.sla.clock.resume","lead_sla_clock",String(body.clockId||""),"completed",data);return json({data,productionReady:false});}
 if(action==="run_governance"){const data=await runLeadSlaGovernance(db,{actorId:actor.email,asOf:body.asOf==null?undefined:Number(body.asOf)});await securityAudit(db,actor,"lead.sla.run","lead_sla","scheduler","completed",data);return json({data,productionReady:false});}
 return json({error:"Unknown lead SLA governance action"},400);
}catch(error){return authError(error,"Unable to update lead SLA governance");}}
