"use client";
import Link from"next/link";
import{useEffect,useState}from"react";
import{loadWalkingProof,updateWalkingProof}from"../../../lib/walking-proof-client";

export default function WalkingProofWorkspace({bookingId}:{bookingId:string}){
 const[data,setData]=useState<{media:Array<Record<string,unknown>>;incidents:Array<Record<string,unknown>>}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[lastGrant,setLastGrant]=useState("");
 async function refresh(){if(!bookingId)return;try{setError("");setData(await loadWalkingProof({bookingId}))}catch(problem){setError(problem instanceof Error?problem.message:"Unable to load Walking proof")}}
 useEffect(()=>{if(!bookingId)return;let active=true;void loadWalkingProof({bookingId}).then(result=>{if(active)setData(result)}).catch(problem=>{if(active)setError(problem instanceof Error?problem.message:"Unable to load Walking proof")});return()=>{active=false}},[bookingId]);
 async function request(purpose:"walk_photo"|"route_proof"|"incident_evidence"){setBusy(true);setError("");try{const result=await updateWalkingProof({bookingId,action:"request_upload",idempotencyKey:`walk-proof:${bookingId}:${purpose}:${crypto.randomUUID()}`,purpose});setLastGrant(`${String(result.mediaId)} · private UAT grant issued`);await refresh()}catch(problem){setError(problem instanceof Error?problem.message:"Unable to request Walking proof")}finally{setBusy(false)}}
 async function incident(){setBusy(true);setError("");try{await updateWalkingProof({bookingId,action:"record_incident",idempotencyKey:`walk-incident:${bookingId}:${crypto.randomUUID()}`,incidentSeverity:"attention",incidentType:"care_attention",description:"Walker recorded a UAT care attention incident requiring Operations visibility."});await refresh()}catch(problem){setError(problem instanceof Error?problem.message:"Unable to record Walking incident")}finally{setBusy(false)}}
 if(!bookingId)return <main style={{padding:24,fontFamily:"system-ui"}}><h1>Walking proof workspace</h1><p>Open this from a canonical Walker booking.</p><Link href="/walking">Walking</Link></main>;
 return <main style={{maxWidth:900,margin:"0 auto",padding:24,fontFamily:"system-ui",display:"grid",gap:16}}><Link href={`/walker?bookingId=${encodeURIComponent(bookingId)}`}>← Walker workspace</Link><h1>Walking proof & incidents</h1><p>Booking <strong>{bookingId}</strong></p><p>Private media stays metadata-only until external object storage and scanner adapters are connected. Live GPS is not asserted.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={busy} onClick={()=>void request("walk_photo")}>Request walk-photo grant</button><button disabled={busy} onClick={()=>void request("route_proof")}>Request route-proof grant</button><button disabled={busy} onClick={()=>void request("incident_evidence")}>Request incident-evidence grant</button><button disabled={busy} onClick={()=>void incident()}>Record attention incident</button></div>{lastGrant&&<p>{lastGrant}</p>}{error&&<p role="alert">{error}</p>}<section><h2>Media trust states</h2>{data?.media?.length?data.media.map((item,index)=><p key={String(item.id||index)}><strong>{String(item.purpose)}</strong> · {String(item.state)} · scan {String(item.scan_status)}</p>):<p>No media records.</p>}</section><section><h2>Incidents</h2>{data?.incidents?.length?data.incidents.map((item,index)=><p key={String(item.id||index)}><strong>{String(item.severity)}</strong> · {String(item.incident_type)} · {String(item.status)}</p>):<p>No incidents.</p>}</section></main>;
}
