"use client";
import{useEffect,useState}from"react";
import{Badge,Button,StatCard,TeamAlert,TeamSection,TeamShell,TeamStatGrid,TeamTable}from"../../../components/ui";
type Readiness={enabled:boolean;mode:string;approved:boolean;allowlistSize:number;singleRecipient:boolean;telephonyConfigured:boolean;aiBindingConfigured:boolean;reason:string|null;recording:false;maxCallSeconds:number};
type StartResult={callId:string;providerCallId:string;providerStatus:string;phoneLast4:string;quietHoursBypassed:boolean;recording:false;maxCallSeconds:number};
async function readiness(){const response=await fetch("/api/voice-outbound?scope=ai_self_test",{cache:"no-store"}),body=await response.json()as{data?:Readiness;error?:string};if(!response.ok||!body.data)throw new Error(body.error||`Unable to load AI voice self-test (${response.status})`);return body.data;}
async function start(){const response=await fetch("/api/voice-outbound",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"uat_ai_self_test"})}),body=await response.json()as{data?:StartResult;error?:string};if(!response.ok||!body.data)throw new Error(body.error||`AI voice self-test was refused (${response.status})`);return body.data;}
export default function AiVoiceSelfTestPage(){const[state,setState]=useState<Readiness|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");useEffect(()=>{let cancelled=false;readiness().then(data=>{if(!cancelled)setState(data);},caught=>{if(!cancelled)setError(caught instanceof Error?caught.message:String(caught));});return()=>{cancelled=true;};},[]);const refresh=async()=>{try{setState(await readiness());}catch(caught){setError(caught instanceof Error?caught.message:String(caught));}};const callMe=async()=>{if(!state?.enabled||busy)return;setBusy(true);setError("");setNotice("");try{const result=await start();setNotice(`AI self-test ${result.callId} started for the allow-listed number ending ${result.phoneLast4}. Answer the call and speak normally; you can interrupt the bot and ask follow-up questions.`);await refresh();}catch(caught){setError(caught instanceof Error?caught.message:String(caught));}finally{setBusy(false);}};return <TeamShell eyebrow="PAWSPACE TEAM · VOICE UAT" title="Call me with the AI bot" description="UAT self-test for exactly one server-side allow-listed number. It never accepts an arbitrary recipient, never records the call, and does not weaken normal customer quiet-hours policy." nav={[{href:"/team/voice",label:"Voice operations",primary:true},{href:"/team/ai",label:"AI governance"},{href:"/team",label:"Team home"}]} status={<><TeamAlert tone="error">{error}</TeamAlert><TeamAlert tone="info">{notice}</TeamAlert></>}>
<TeamStatGrid><StatCard label="Self-test" value={state?(state.enabled?"READY":"BLOCKED"):"…"} meta={state?.reason||"UAT-only self-test lane"}/><StatCard label="Allow-listed numbers" value={state?.allowlistSize??"…"} meta="must be exactly one"/><StatCard label="Voice AI" value={state?.aiBindingConfigured?"CONNECTED":"MISSING"} meta="STT + Q&A + TTS"/><StatCard label="Call limit" value={state?`${Math.round(state.maxCallSeconds/60)} min`:"…"} meta="recording always off"/></TeamStatGrid>
<TeamSection title="Safety boundary" note="This path is separate from ordinary outbound customer calls."><TeamTable head={["Control","State","Meaning"]} rows={state?[["Environment",<Badge key="e" tone={state.mode==="uat"?"success":"danger"}>{state.mode}</Badge>,"Live/production mode cannot use this self-test."],["Explicit approval",<Badge key="a" tone={state.approved?"success":"danger"}>{state.approved?"yes":"no"}</Badge>,"Server-side only."],["Recipient",<Badge key="r" tone={state.singleRecipient?"success":"danger"}>{state.singleRecipient?"one allow-listed number":"blocked"}</Badge>,"The browser does not send a phone number."],["Telephony",<Badge key="t" tone={state.telephonyConfigured?"success":"danger"}>{state.telephonyConfigured?"configured":"incomplete"}</Badge>,"Exotel AgentStream places the call."],["Quiet hours",<Badge key="q" tone="warning">audited override</Badge>,"One-contact UAT callback only."],["Recording",<Badge key="rec" tone="success">off</Badge>,"No recording is requested."]]:[]} empty="Loading readiness…"/></TeamSection>
<TeamSection title="Start the test" note="Answer and ask questions naturally. You can interrupt the bot while it is speaking.">{!state?.enabled&&<TeamAlert tone="error">{state?.reason||"AI voice self-test is not ready."}</TeamAlert>}<Button onClick={()=>void callMe()} disabled={!state?.enabled||busy}>{busy?"Calling…":"Call my allow-listed number now"}</Button></TeamSection></TeamShell>;}
