/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from"node:assert/strict";
import{DatabaseSync}from"node:sqlite";
import{acknowledgeEscrowSettlement,arbitrateEscrow,claimNextEscrowSettlement,freezeEscrowForDispute,markEscrowSettlementFailed,reconcileEscrowInvariants,requireEscrowProviderReleaseForPayout,reserveEscrowForProviderPayout}from"../lib/escrow-custody-engine";
assert.equal(process.env.PAWSPACE_PAYMENT_ENV,"sandbox");assert.equal(process.env.FORBID_PRODUCTION,"true");assert.notEqual(process.env.PAWSPACE_PAYMENT_LIVE_APPROVED,"true");process.env.PAWSPACE_PAYMENT_LIVE_APPROVED="false";
type R={meta:{changes:number}};
class S{constructor(readonly d:D,readonly sql:string,readonly args:any[]=[]){ }bind(...args:any[]){return new S(this.d,this.sql,args)}async first<T=Record<string,unknown>>(){return(this.d.s.prepare(this.sql).get(...this.args)as T|undefined)??null}async run():Promise<R>{this.d.fail(this.sql);const r=this.d.s.prepare(this.sql).run(...this.args);return{meta:{changes:Number(r.changes)}}}async all<T=Record<string,unknown>>(){return{results:this.d.s.prepare(this.sql).all(...this.args)as T[]}}}
class D{pattern:RegExp|null=null;tail:Promise<void>=Promise.resolve();constructor(readonly s=new DatabaseSync(":memory:")){ }prepare(sql:string){return new S(this,sql)}async batch(list:S[]){let unlock!:()=>void;const previous=this.tail;this.tail=new Promise<void>(resolve=>unlock=resolve);await previous;this.s.exec("BEGIN IMMEDIATE");try{const out=[];for(const item of list)out.push(await item.run());this.s.exec("COMMIT");return out}catch(e){this.s.exec("ROLLBACK");throw e}finally{unlock()}}async exec(sql:string){this.s.exec(sql);return{count:0,duration:0}}failNext(pattern:RegExp){this.pattern=pattern}fail(sql:string){if(this.pattern?.test(sql)){this.pattern=null;throw new Error(`fault_injected:${sql.slice(0,60)}`)}}}
function world(amount=199.99){const d=new D();d.s.exec("CREATE TABLE booking_payments(id TEXT PRIMARY KEY,booking_id TEXT,customer_id TEXT,amount REAL,currency TEXT,status TEXT);CREATE TABLE payment_reconciliation_records(payment_id TEXT PRIMARY KEY,captured_amount REAL,refunded_amount REAL);CREATE TABLE provider_order_commissions(booking_id TEXT PRIMARY KEY,commission_amount REAL,commission_source TEXT,override_reason TEXT,status TEXT,updated_at INTEGER);");d.s.prepare("INSERT INTO booking_payments VALUES('PAY-A','BK-A','CUS-A',?,'INR','captured')").run(amount);d.s.prepare("INSERT INTO payment_reconciliation_records VALUES('PAY-A',?,0)").run(amount);d.s.prepare("INSERT INTO provider_order_commissions VALUES('BK-A',?,'provider_default',NULL,'awaiting_approval_2',?)").run(amount,Date.now());return d;}
const asDb=(d:D)=>d as unknown as D1Database;const reserve=(d:D,amount=199.99)=>reserveEscrowForProviderPayout(asDb(d),{bookingId:"BK-A",providerId:"PRV-A",amount,actorId:"finance@pawspace.in"});
async function main(){let checks=0;{const d=world();await reserve(d);d.failNext(/INSERT INTO dispute_freezes/);await assert.rejects(()=>freezeEscrowForDispute(asDb(d),{bookingId:"BK-A",disputeReference:"DSP-FAULT-FREEZE",reason:"Customer disputes service quality",actorId:"ops@pawspace.in"}),/fault_injected/);const a=d.s.prepare("SELECT state,active_dispute_id FROM escrow_custodial_accounts WHERE booking_id='BK-A'").get()as any;assert.equal(a.state,"CUSTODY_HELD");assert.equal(a.active_dispute_id,null);assert.equal((d.s.prepare("SELECT COUNT(*) n FROM dispute_freezes").get()as any).n,0);checks+=4;}
 const d=world();await reserve(d);await freezeEscrowForDispute(asDb(d),{bookingId:"BK-A",disputeReference:"DSP-AUDIT-1",reason:"Customer supplied evidence for arbitration",actorId:"ops@pawspace.in"});d.failNext(/INSERT INTO finance_refund_payables/);await assert.rejects(()=>arbitrateEscrow(asDb(d),{bookingId:"BK-A",decision:"PARTIAL_SPLIT",customerPercentage:33.33,reason:"Evidence supports a measured partial split",actorId:"arb@pawspace.in"}),/fault_injected/);let a=d.s.prepare("SELECT * FROM escrow_custodial_accounts WHERE booking_id='BK-A'").get()as any,dispute=d.s.prepare("SELECT * FROM dispute_freezes").get()as any;assert.equal(a.state,"DISPUTE_FROZEN");assert.equal(a.settlement_state,"NONE");assert.equal(dispute.status,"OPEN");assert.equal((d.s.prepare("SELECT COUNT(*) n FROM escrow_settlement_outbox").get()as any).n,0);assert.equal((d.s.prepare("SELECT COUNT(*) n FROM finance_journal_entries WHERE source_type='escrow_release'").get()as any).n,0);checks+=6;
 const input={bookingId:"BK-A",decision:"PARTIAL_SPLIT"as const,customerPercentage:33.33,reason:"Evidence supports a measured partial split",actorId:"arb@pawspace.in"};const[a1,a2]=await Promise.all([arbitrateEscrow(asDb(d),input),arbitrateEscrow(asDb(d),input)]);const resolved=a1.duplicatePrevented?a2:a1;assert.equal(resolved.customerAmount,66.66);assert.equal(resolved.providerAmount,133.33);assert.equal(resolved.customerAmount+resolved.providerAmount,199.99);assert.equal((d.s.prepare("SELECT COUNT(*) n FROM escrow_ledger_transactions WHERE event_type='ARBITRATION_DECISION'").get()as any).n,1);checks+=4;
 a=d.s.prepare("SELECT * FROM escrow_custodial_accounts WHERE booking_id='BK-A'").get()as any;dispute=d.s.prepare("SELECT * FROM dispute_freezes").get()as any;assert.equal(dispute.status,"RESOLVED");assert.equal(a.settlement_state,"PARTIAL_SETTLEMENT_PENDING");assert.equal(a.held_amount,199.99);assert.equal(a.released_provider_amount,0);assert.equal(a.refunded_customer_amount,0);assert.equal((d.s.prepare("SELECT COUNT(*) n FROM escrow_settlement_outbox").get()as any).n,2);await assert.rejects(()=>requireEscrowProviderReleaseForPayout(asDb(d),{bookingId:"BK-A",maximumAmount:133.33}),/escrow_settlement_not_confirmed/);checks+=7;
 const now=Date.now()+10000,first=await claimNextEscrowSettlement(asDb(d),{workerId:"worker-a",now})as any;const failed=await markEscrowSettlementFailed(asDb(d),{outboxId:first.id,workerId:"worker-a",error:"sandbox gateway timeout",maxAttempts:5,now});assert.equal(failed.status,"RETRY");const second=await claimNextEscrowSettlement(asDb(d),{workerId:"worker-b",now:now+1})as any;assert.notEqual(second.id,first.id);await acknowledgeEscrowSettlement(asDb(d),{outboxId:second.id,workerId:"worker-b",externalReference:`SBX-${second.kind}-2`,now:now+2});const retry=await claimNextEscrowSettlement(asDb(d),{workerId:"worker-a",now:failed.nextAttemptAt+1})as any;assert.equal(retry.id,first.id);await acknowledgeEscrowSettlement(asDb(d),{outboxId:retry.id,workerId:"worker-a",externalReference:`SBX-${retry.kind}-1`,now:failed.nextAttemptAt+2});checks+=3;
 a=d.s.prepare("SELECT * FROM escrow_custodial_accounts WHERE booking_id='BK-A'").get()as any;assert.equal(a.settlement_state,"PARTIAL_SETTLED");assert.equal(a.held_amount,0);assert.equal(a.released_provider_amount,133.33);assert.equal(a.refunded_customer_amount,66.66);assert.equal((await requireEscrowProviderReleaseForPayout(asDb(d),{bookingId:"BK-A",maximumAmount:133.33})).providerAmount,133.33);const duplicate=await acknowledgeEscrowSettlement(asDb(d),{outboxId:retry.id,workerId:"worker-a",externalReference:`SBX-${retry.kind}-1`,now:failed.nextAttemptAt+3});assert.equal(duplicate.duplicatePrevented,true);checks+=6;
 const ledger=d.s.prepare("SELECT sequence,previous_hash,event_hash FROM escrow_ledger_transactions WHERE booking_id='BK-A' ORDER BY sequence").all()as any[];for(let i=1;i<ledger.length;i++){assert.equal(ledger[i].sequence,ledger[i-1].sequence+1);assert.equal(ledger[i].previous_hash,ledger[i-1].event_hash);checks+=2}const head=d.s.prepare("SELECT last_sequence,last_hash FROM escrow_ledger_heads WHERE custodial_account_id=?").get(a.id)as any;assert.equal(head.last_sequence,ledger.at(-1).sequence);assert.equal(head.last_hash,ledger.at(-1).event_hash);assert.throws(()=>d.s.prepare("UPDATE escrow_ledger_transactions SET reason='tamper' WHERE booking_id='BK-A'").run(),/escrow_ledger_append_only/);assert.throws(()=>d.s.prepare("DELETE FROM escrow_ledger_transactions WHERE booking_id='BK-A'").run(),/escrow_ledger_append_only/);checks+=4;
 assert.equal((await reconcileEscrowInvariants(asDb(d))).ok,true);d.s.prepare("UPDATE escrow_custodial_accounts SET settlement_state='RELEASED' WHERE booking_id='BK-A'").run();d.s.prepare("UPDATE escrow_settlement_outbox SET external_reference=NULL WHERE kind='PAYOUT'").run();const alarm=await reconcileEscrowInvariants(asDb(d));assert.equal(alarm.ok,false);assert.ok(alarm.issues.some(i=>i.alarmType==="TERMINAL_SETTLEMENT_MISSING_EXTERNAL_CONFIRMATION"));checks+=3;console.log(JSON.stringify({ok:true,checks,oddCentSplit:{customer:66.66,provider:133.33},faultRollback:true,concurrencyCAS:true,retryVerified:true,appendOnlyVerified:true,reconciliationAlarmVerified:true},null,2));}
await main();
