"use client";
import {useRef,useState} from "react";
import type {CustomerAccountRecord} from "../../../lib/customer-account";
import {customerEmailIssue} from "../../../lib/customer-email";
import {loadV2CustomerAccount,updateV2CustomerProfile} from "../../../lib/v2/customer-experience-client";
import styles from "./customer-intake.module.css";
export function groomingContactPayload(account:CustomerAccountRecord,name:string,email:string,idempotencyKey:string){return {name:name.trim(),email:email.trim()||null,primaryPhone:account.primaryPhone,secondaryPhone:account.secondaryPhone,cityId:account.cityId,idempotencyKey};}
export default function GroomingCustomerIntake({account,disabled=false,onProfileSaved}:{account:CustomerAccountRecord;disabled?:boolean;onProfileSaved:(account:CustomerAccountRecord)=>void}){
 const[editing,setEditing]=useState(false),[draft,setDraft]=useState<{name:string;email:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const saving=useRef(false);
 const contact=draft||{name:account.name,email:account.email||""};
 async function save(){if(disabled||saving.current)return;setError("");setMessage("");if(!contact.name.trim()){setError("Enter your name to save your contact details.");return;}const issue=customerEmailIssue(contact.email);if(issue){setError(issue);return;}saving.current=true;setBusy(true);try{await updateV2CustomerProfile(groomingContactPayload(account,contact.name,contact.email,"v2-profile-"+crypto.randomUUID()));const fresh=await loadV2CustomerAccount();onProfileSaved(fresh);setDraft(null);setEditing(false);setMessage("Contact details saved.");}catch(e){setError(e instanceof Error?e.message:"We could not save your contact details. Please try again.");}finally{saving.current=false;setBusy(false);}}
 return <section className={styles.panel} aria-label="Contact details"><div className={styles.header}><div><h3>Your contact details</h3><p>{account.name} · {account.primaryPhone}</p><p>{account.email||"Email not added (optional)"}</p></div><button type="button" disabled={disabled||busy} aria-expanded={editing} onClick={()=>{setEditing(old=>!old);setError("");setMessage("");}}> {editing?"Close editing":"Edit details"}</button></div>{editing&&<div className={styles.editor}><div className={styles.fields}><label>Name<input autoComplete="name" disabled={disabled||busy} value={contact.name} onChange={e=>setDraft({...contact,name:e.target.value})}/></label><label>Email (optional)<input type="email" autoComplete="email" disabled={disabled||busy} value={contact.email} onChange={e=>setDraft({...contact,email:e.target.value})}/></label></div><small>Your verified mobile number stays {account.primaryPhone}. These details are saved to your existing account.</small><button type="button" className={styles.save} disabled={disabled||busy} onClick={save}>{busy?"Saving contact details…":"Save contact details"}</button></div>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
