import{authError,database,requirePermission,resolveActor,securityAudit}from"../../../lib/server-auth";
import{completeAiVoiceCall,recordAiVoiceTranscriptSegment,recordAiVoiceTransportFailure,startAiVoiceUatCall,transferAiVoiceToAgent}from"../../../lib/ai-voice-uat";

type Body={action?:"start"|"segment"|"transfer"|"transport_failure"|"complete";customerId?:string;direction?:"inbound"|"outbound";transportProvider?:"exotel"|"sandbox_simulator";consent?:boolean;language?:string;callId?:string;segmentIndex?:number;speaker?:"customer"|"assistant";text?:string;sttProvider?:string;sttConfidence?:number;interrupted?:boolean;reason?:string;confidence?:number;reconnected?:boolean;outcome?:string;disposition?:string};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin AI voice write blocked",{status:403});}
// Boolean(body.consent) made the STRING "false" truthy, so a client sending consent:"false" satisfied
// the consent gate and produced a row stamped consent_status='verified'. Only a real boolean true counts;
// anything else - "false", 0, "yes", null, absent - is not consent.
function affirmed(value:unknown){return value===true;}

export async function POST(request:Request){try{sameOrigin(request);const actor=await resolveActor(request);requirePermission(actor,"communications.call");const db=await database(),body=await request.json()as Body,action=body.action||"start";let data:unknown;if(action==="start"){if(!body.customerId||!body.direction||!body.transportProvider)return json({error:"Customer, direction and transport provider are required"},400);data=await startAiVoiceUatCall(db,{actor,customerId:body.customerId,direction:body.direction,transportProvider:body.transportProvider,consent:affirmed(body.consent),language:body.language});}else if(action==="segment"){if(!body.callId||body.segmentIndex==null||!body.speaker||!body.text)return json({error:"Call, segment index, speaker and text are required"},400);data=await recordAiVoiceTranscriptSegment(db,{actor,callId:body.callId,segmentIndex:body.segmentIndex,speaker:body.speaker,text:body.text,sttProvider:body.sttProvider,sttConfidence:body.sttConfidence,interrupted:body.interrupted});}else if(action==="transfer"){if(!body.callId)return json({error:"Call ID is required"},400);data=await transferAiVoiceToAgent(db,{actor,callId:body.callId,reason:body.reason||"Customer requested live agent",confidence:body.confidence});}else if(action==="transport_failure"){if(!body.callId)return json({error:"Call ID is required"},400);data=await recordAiVoiceTransportFailure(db,{actor,callId:body.callId,reason:body.reason||"provider_timeout",reconnected:Boolean(body.reconnected)});}else{if(!body.callId)return json({error:"Call ID is required"},400);data=await completeAiVoiceCall(db,{actor,callId:body.callId,outcome:body.outcome||"completed",disposition:body.disposition||"completed"});}await securityAudit(db,actor,`ai.voice.${action}`,"ai_voice_call",body.callId||null,"completed",{productionTelephony:false});return json({data},action==="start"?201:200);}catch(error){if(error instanceof Response)return json({error:await error.text()},error.status);return authError(error,"Unable to process AI voice UAT action");}}
