"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {loadV2CustomerAccount,loadV2CustomerSession} from "../../../lib/v2/customer-experience-client";
import styles from "../customer-detail.module.css";

type SupportCase={id:string;title:string;status:string;severity:string;resolutionNote:string|null;createdAt:number};
export default function V2Support(){
 const[customerId,setCustomerId]=useState(""),[cases,setCases]=useState<SupportCase[]>([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(id:string){const response=await fetch(`/api/customer-support-case?customerId=${encodeURIComponent(id)}`,{cache:"no-store"}),body=await response.json() as{data?:{cases?:SupportCase[]};error?:string};if(!response.ok)throw new Error(body.error||"Unable to load support cases");setCases(body.data?.cases??[]);}
 useEffect(()=>{let active=true;(async()=>{try{const session=await loadV2CustomerSession();if(!session)return;const account=await loadV2CustomerAccount();if(!active)return;setCustomerId(account.customerId);await load(account.customerId);}catch(problem){if(active)setError(problem instanceof Error?problem.message:"Unable to load support");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]);
 async function submit(){if(!customerId||busy)return;if(!title.trim()||description.trim().length<10){setError("Add a short title and describe the issue in a little more detail.");return;}setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/customer-support-case",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerId,title:title.trim(),description:description.trim(),requestId:crypto.randomUUID()})}),body=await response.json() as{error?:string};if(!response.ok)throw new Error(body.error||"Unable to submit your report");setTitle("");setDescription("");setMessage("Your support case has been recorded.");await load(customerId);}catch(problem){setError(problem instanceof Error?problem.message:"Unable to submit your report");}finally{setBusy(false);}}
 return <main className={styles.page}><div className={styles.shell}><header className={styles.topbar}><Link href="/v2" className={styles.brand}><img src="/assets/pawspace-icon.jpeg" alt=""/><span>PawSpace</span></Link><Link href="/v2/account" className={styles.back}>← Account</Link></header><section className={styles.hero}><span className={styles.eyebrow}>PAWSPACE SUPPORT</span><h1>Report an issue and follow its resolution.</h1><p>This uses the same canonical support-case record as the V1 customer app and staff CX workspace.</p></section>{error&&<div className={styles.notice} role="alert">{error}</div>}{message&&<div className={styles.notice} role="status">{message}</div>}{loading?<section className={styles.card}>Loading support…</section>:!customerId?<section className={styles.card}><h2>Sign in to contact support.</h2><Link href="/v2" className={styles.back}>Return home</Link></section>:<div className={styles.grid}><section className={styles.card}><h2>New support case</h2><div className={styles.form}><label className={styles.field}>Title<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="What went wrong?"/></label><label className={styles.field}>Details<textarea value={description} maxLength={2000} rows={6} onChange={e=>setDescription(e.target.value)} placeholder="Describe what happened and include the booking or service context."/></label><button className={styles.primary} disabled={busy} onClick={()=>void submit()}>{busy?"Submitting…":"Submit support case"}</button></div></section><section className={styles.card}><h2>Your reported issues</h2>{cases.length?cases.map(item=><article className={styles.item} key={item.id}><b>{item.title}</b><small>{item.status.replaceAll("_"," ")} · {item.severity.replaceAll("_"," ")}</small>{item.resolutionNote&&<p>{item.resolutionNote}</p>}</article>):<p className={styles.muted}>No support cases recorded for this account.</p>}</section></div>}</div><nav className={styles.dock} aria-label="PawSpace V2 navigation"><Link href="/v2"><strong>⌂</strong>Home</Link><Link href="/v2/activity"><strong>◎</strong>Activity</Link><Link href="/v2/chat"><strong>✦</strong>AI</Link><Link href="/v2/account" className={styles.active}><strong>◉</strong>Account</Link></nav></main>;
}
