import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
export const FIXED=Object.freeze({worker:'pawspace-staging',database:'1b879a28-c8a9-40b0-830d-1ce439061a00',originalSha:'c18b15caea9551505398746dc9335a962f17e8ae',originalVersion:'66d593c5-ce73-458e-925c-ca23c92c0934',assetSha:'e6d2e59b7b5bbb0342e0fb496dfc262decbfe4426bbb7b047aec8d467d1dc6f7',normalDigest:'bbc5b5180da1d10a27a6502891158b86b15ff18b3a361373b0aa170bcbd086f4',bundleSha:'58910c59c04d91e6a57f134570fa0305c9231530d7f95659a728aebc71c80ec6',job:'Sentinel_f67e3c5a85f88191b07279e0edbe250c',origin:'https://pawspace-staging.karthik-fce.workers.dev'});
export const CRONS=[{cron:'*/5 * * * *'},{cron:'*/15 * * * *'},{cron:'15 2 * * *'}];
export const SQL={normal:'SELECT id,provider,model_ref,channel,intent,reserved_tokens,reserved_cost_micros,actual_tokens,actual_cost_micros,status,failure_class,created_at,updated_at FROM ai_provider_runtime_requests ORDER BY id LIMIT 10001',ledger:'SELECT id,job_id,rate_version,thread_id,input_upper,output_upper,reserved_micros,status,actual_upper_micros,created_at FROM atlas_text_test_requests ORDER BY id LIMIT 10001',schema:"SELECT name,type,tbl_name,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY name LIMIT 10001"};
const sha=v=>createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex');const check=(v,e)=>{if(!v)throw Error(e)};
export function uploadMetadata(config){check(config.name===FIXED.worker&&config.main==='atlas-api-review.js'&&config.d1_databases?.length===1&&config.d1_databases[0].binding==='DB'&&config.d1_databases[0].database_id===FIXED.database,'config_target_refused');check(JSON.stringify(config.triggers)==='{"crons":[]}','explicit_cron_clear_required');check(Object.keys(config).sort().join(',')==='compatibility_date,compatibility_flags,d1_databases,main,name,triggers,vars,version_metadata','config_capability_refused');check(config.version_metadata?.binding==='PAWSPACE_VERSION_METADATA'&&JSON.stringify(config.compatibility_flags)==='["nodejs_compat"]','config_runtime_refused');check(config.vars.PAWSPACE_ATLAS_TEXT_TEST_JOB_ID===FIXED.job&&config.vars.PAWSPACE_ISOLATED_FINANCE_TEST==='true'&&config.vars.FINANCE_TEST_ORIGIN===FIXED.origin&&/^[a-f0-9]{40}$/.test(config.vars.PAWSPACE_STAGING_BUILD_SHA),'config_scope_refused');const bindings=[{type:'d1',name:'DB',id:FIXED.database},{type:'version_metadata',name:'PAWSPACE_VERSION_METADATA'}];for(const[name,text]of Object.entries(config.vars)){check(!/SECRET|KEY|TOKEN|PASSWORD|ACCESS_CODE/i.test(name),'credential_plaintext_refused');check(typeof text==='string','primitive_var_required');bindings.push({type:'plain_text',name,text});}return{main_module:'atlas-api-review.js',compatibility_date:config.compatibility_date,compatibility_flags:['nodejs_compat'],bindings,keep_bindings:['secret_text','secret_key'],limits:{cpu_ms:300000}};}
export async function verifyTemporary({env,config,bundle,issueToken,transport=fetch,persist,clock=Date.now,expectedNormalDigest=FIXED.normalDigest}){
 const receipt={kind:'temporary_existing_staging_API_only_no_model',modelRequests:0,originRequests:0,mutations:[],reads:[],additionalHostingQualification:'approved_total_25c_including_applicable_taxes',hostingCapMicros:250000,preTaxWorkloadUpperMicros:152791,taxAndFeeContingencyMicros:97209,taxFeeEvidence:'Same-day itemized bills total33.97 with observed added tax and fees0; reasonable expected bound, no accountwide invoice guarantee',authDml:'existing default role upserts possible, bounded1000; no zero-DML claim',schedulePropagation:'API acknowledgement only; up to15min edge propagation',uncertain:false};
 let uploadAttempted=false,scheduleAttempted=false,primaryFailure=null;const save=()=>persist(receipt);const fail=e=>{throw Error(e)};
 const request=async(url,init={},phase)=>{if(url.startsWith(FIXED.origin)){check(init.method===undefined||init.method==='GET','origin_GET_only');check(++receipt.originRequests<=10,'origin_request_envelope');}const response=await transport(url,{...init,redirect:'manual',signal:AbortSignal.timeout(20000)});check(response.ok,'http_'+response.status+'_'+phase);return response;};
 const base=`https://api.cloudflare.com/client/v4/accounts/${env.CLOUDFLARE_ACCOUNT_ID}`,script=base+'/workers/scripts/'+FIXED.worker;
 const api=async(path,method,body,phase,mutation=false)=>{let record;if(mutation){record={phase,state:'uncertain_before_dispatch'};receipt.mutations.push(record);receipt.uncertain=true;save();}let response;try{response=await request(path,{method,headers:{authorization:'Bearer '+env.CLOUDFLARE_API_TOKEN,...(!(body instanceof FormData)?{'content-type':'application/json'}:{})},body:body instanceof FormData?body:JSON.stringify(body)},phase);}catch(error){if(record&&/^http_(?:401|403)_/.test(String(error.message))){record.state='rejected';receipt.uncertain=receipt.mutations.some(r=>r.state==='uncertain_before_dispatch');save();fail(phase+'_known_http_rejection_no_retry');}fail(phase+'_result_unknown_no_retry');}const payload=await response.json().catch(()=>null);if(payload?.success===false&&record){record.state='rejected';receipt.uncertain=receipt.mutations.some(r=>r.state==='uncertain_before_dispatch');save();}check(payload?.success===true,phase+'_api_refused_no_retry');if(record){record.state='confirmed';receipt.uncertain=receipt.mutations.some(r=>r.state==='uncertain_before_dispatch');save();}return payload.result;};
 const query=async(name)=>{const blocks=await api(base+'/d1/database/'+FIXED.database+'/query','POST',{sql:SQL[name],params:[]},'select_'+name);check(blocks?.length===1&&blocks[0].success===true&&Array.isArray(blocks[0].results)&&blocks[0].results.length<=10000,'select_contract');const b=blocks[0];check(b.meta?.rows_written===0&&b.meta?.changed_db===false&&Number.isSafeInteger(b.meta?.rows_read)&&b.meta.rows_read>=0,'native_read_metadata_required');receipt.reads.push({name,rowsReturned:b.results.length,nativeRowsRead:b.meta.rows_read,rowsWritten:0});check(receipt.reads.reduce((n,r)=>n+r.nativeRowsRead,0)<=1000000,'billed_read_envelope');return b.results;};
 let cookie;
 const originJson=async(path)=>{const r=await request(FIXED.origin+path,{headers:{cookie,origin:FIXED.origin}},'origin_read');return r.json();};
 const fixture=async(expectedSha,version)=>{const p=await originJson('/__staging/fixture-isolation?expectedSha='+expectedSha+'&scope=grooming_strict');check(p.ok===true&&p.version?.buildSha===expectedSha&&(version?p.version.id===version:/^[a-f0-9-]{36}$/.test(p.version.id??'')&&p.version.id!==FIXED.originalVersion),'fixture_version_or_isolation_refused');return{sourceSha:p.version.buildSha,versionId:p.version.id};};
 const health=async()=>{await request(FIXED.origin+'/healthz',{},'health');};
 const asset=async()=>{const r=await request(FIXED.origin+'/favicon.svg',{},'restored_asset');check((r.headers.get('content-type')??'').includes('image/svg+xml'),'assets_not_restored');check(sha(Buffer.from(await r.arrayBuffer()))===FIXED.assetSha,'asset_hash_not_restored');};
 let before;let temporaryDeadline=Infinity;
 try{
  check(env.CONFIRM==='atlas-api-only-no-model'&&/^ops\/atlas-api-only-/.test(env.GITHUB_REF_NAME??'')&&env.GITHUB_RUN_ATTEMPT==='1'&&env.EXPECTED_OPERATION_SHA===env.GITHUB_SHA&&/^[a-f0-9]{40}$/.test(env.GITHUB_SHA??''),'pinned_operation_refused');check(/^[a-f0-9]{32}$/.test(env.CLOUDFLARE_ACCOUNT_ID??'')&&env.CLOUDFLARE_API_TOKEN&&String(env.PAWSPACE_UAT_SIGNING_KEY??'').length>=32,'sealed_connection_missing');check(sha(bundle)===FIXED.bundleSha,'exact_bundle_refused');check(config.vars.PAWSPACE_STAGING_BUILD_SHA===env.EXPECTED_CANDIDATE_SOURCE_SHA,'candidate_source_pin_refused');const metadata=uploadMetadata(config);
  check(env.HOSTING_ENVELOPE_APPROVED==='bounded-hosting-25c-total-20261003-193139','hosting_qualification_required');receipt.envelope={originRequestsMaximum:10,httpCpuMillisecondsPerInvocationMaximum:300000,httpCpuMillisecondsMaximum:3000000,propagatingCronInvocationsMaximum:5,propagatingCronCpuMillisecondsPerInvocationMaximum:900000,propagatingCronCpuMillisecondsMaximum:4500000,cpuMillisecondsMaximum:7500000,totalInvocationsMaximum:15,d1RowsReadMaximum:1000000,existingRoleWritesMaximum:1000,additionalStorageBytesMaximum:1048576,newResources:0};save();
  cookie='pawspace_uat='+encodeURIComponent(await issueToken({PAWSPACE_UAT_SIGNING_KEY:env.PAWSPACE_UAT_SIGNING_KEY},'founder@pawspace.in',600));
  receipt.preflight=await fixture(FIXED.originalSha,FIXED.originalVersion);await health();await asset();
  const schema=await query('schema');for(const name of ['app_users','role_definitions','security_audit_events','security_audit_outbox','customer_identity_links','provider_identity_links','identity_bindings','identity_binding_audit','platform_identity_sessions','platform_identity_session_audit','atlas_text_test_requests','ai_provider_runtime_requests','security_audit_outbox_status_idx','idx_identity_bindings_subject','idx_platform_identity_sessions_subject'])check(schema.some(r=>r.name===name),'required_existing_schema_'+name);
  const normal=await query('normal'),ledger=await query('ledger');check(sha(normal)===expectedNormalDigest,'normal_exact_digest_changed');check(normal.length===855&&normal.reduce((n,r)=>n+Number(r.reserved_tokens),0)===7537940,'normal_baseline_changed');check(ledger.length===0,'Atlas_not_empty');before={schema:sha(schema),normal:sha(normal),ledger:sha(ledger)};receipt.before={...before,normalRows:normal.length,AtlasRows:ledger.length};save();
  scheduleAttempted=true;await api(script+'/schedules','PUT',[],'clear_schedules',true);
  const form=new FormData();form.set('metadata',new Blob([JSON.stringify(metadata)],{type:'application/json'}));form.set('atlas-api-review.js',new Blob([bundle],{type:'application/javascript+module'}),'atlas-api-review.js');
  uploadAttempted=true;temporaryDeadline=clock()+120000;receipt.temporaryWindowMaximumMs=120000;const uploaded=await api(script,'PUT',form,'temporary_upload',true);let version=uploaded?.version_id;check(version===undefined||/^[a-f0-9-]{36}$/.test(version),'uploaded_version_unproven');
  check(clock()<temporaryDeadline,'temporary_window_expired_restore');receipt.temporaryFixture=await fixture(config.vars.PAWSPACE_STAGING_BUILD_SHA,version);version=receipt.temporaryFixture.versionId;receipt.temporaryVersion=version;save();await health();
  check(clock()<temporaryDeadline,'temporary_window_expired_restore');const status=(await originJson('/api/ai-business-configuration?mode=atlas_text_admission_status')).data;check(status?.versionId===version&&Object.keys(status.bindings??{}).sort().join(',')==='deploymentMatchesStaging,descriptorMatchesApproved,isolationFlagTrue,jobIdMatchesApproved,jobIdPresent'&&Object.values(status.bindings).every(v=>v===true)&&status.approval?.jobId===FIXED.job&&status.approval.customerId==='CUS0000'&&status.approval.expiresAt==='2026-10-03T15:11:15.000Z'&&status.approval.expired===true&&status.ledger?.status==='read'&&status.ledger.present===true&&status.ledger.outstandingOrUnknown===0&&status.ledger.requests===0&&status.ledger.retainedMicros===0,'protected_status_refused');receipt.status={versionId:status.versionId,approvalExpired:true,ledgerRequests:0};save();
 }catch(error){primaryFailure=String(error.message);receipt.failure=primaryFailure;save();}
 finally{
  if(uploadAttempted){try{await api(script+'/deployments','POST',{strategy:'percentage',versions:[{version_id:FIXED.originalVersion,percentage:100}],annotations:{'workers/message':'Restore certified staging after Atlas no-model qualification'}},'restore_certified_version',true);receipt.restoredVersionConfirmed=true;}catch(error){receipt.restorationBlocker=String(error.message);save();throw Error('RESTORATION_BLOCKED_'+receipt.restorationBlocker);}}
  if(scheduleAttempted&&(uploadAttempted||receipt.mutations.find(r=>r.phase==='clear_schedules')?.state!=='rejected')){try{await api(script+'/schedules','PUT',CRONS,'restore_original_schedules',true);receipt.schedulesRestoredApiConfirmed=true;}catch(error){receipt.restorationBlocker=String(error.message);save();throw Error('RESTORATION_BLOCKED_'+receipt.restorationBlocker);}}
  if(uploadAttempted){receipt.restoredFixture=await fixture(FIXED.originalSha,FIXED.originalVersion);await health();await asset();const after={schema:sha(await query('schema')),normal:sha(await query('normal')),ledger:sha(await query('ledger'))};receipt.after=after;receipt.retainedHistoryUnchanged=JSON.stringify(after)===JSON.stringify(before);save();check(receipt.retainedHistoryUnchanged,'history_or_schema_changed_requires_reconciliation');}
  receipt.phase=primaryFailure?(uploadAttempted?'failed_restored':'failed_before_switch'):'complete_restored';receipt.ok=!primaryFailure;save();
 }
 if(primaryFailure)throw Error(primaryFailure);return receipt;
}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url){try{const {issueUatToken}=await import('./issue-uat-token.mjs');await verifyTemporary({env:process.env,config:JSON.parse(readFileSync(new URL('./api-config.json',import.meta.url),'utf8')),bundle:readFileSync(new URL('./atlas-api-review.js',import.meta.url)),issueToken:issueUatToken,persist:r=>writeFileSync(process.env.EVIDENCE_PATH||'atlas-api-only-receipt.json',JSON.stringify(r,null,2)+'\n',{flush:true})});console.log('Bounded no-model qualification and certified restoration completed.');}catch(error){console.error(error.message);process.exitCode=1;}}
