import{database,requireCustomerOwnership,resolveActor}from"../../../lib/server-auth";
import{governSittingBooking}from"../../../lib/sitting-governance";

type Row=Record<string,unknown>;
type Input={
 idempotencyKey:string;scheduleGroupId:string;sittingQuoteId:string;
 customer:{id:string;name:string;primaryPhone:string;secondaryPhone?:string;email?:string};
 pets:Array<{sourceId:string;name:string;species?:"dog"|"cat"|"other";breed?:string;vaccinationStatus?:string}>;
 cityId:string;zoneId:string;packageCode:string;packageName:string;scheduledStart:string;scheduledEnd:string;
 provider:{id:string;name:string;model:"full_time"|"commission"};
 totalAmount:number;amountDueNow:number;
 payment:{method:string;mode:string;status:string;detail:string};
};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store"}});
const petId=(customerId:string,sourceId:string)=>`PET-${customerId.replace(/[^A-Za-z0-9]/g,"").toUpperCase()}-${sourceId.replace(/[^A-Za-z0-9]/g,"").toUpperCase()}`;
function sameOriginWrite(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("Cross-origin Sitting booking blocked",{status:403});}
async function ensureTables(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS canonical_customers (id TEXT PRIMARY KEY,city_id TEXT NOT NULL,name TEXT NOT NULL,primary_phone TEXT NOT NULL,secondary_phone TEXT,email TEXT,source TEXT NOT NULL DEFAULT 'uat_customer_app',consent_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS canonical_pets (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,name TEXT NOT NULL,species TEXT NOT NULL,breed TEXT,vaccination_status TEXT NOT NULL DEFAULT 'not_provided',source_pet_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS canonical_bookings (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,customer_id TEXT NOT NULL,pet_ids_json TEXT NOT NULL,source_pet_ids_json TEXT NOT NULL,city_id TEXT NOT NULL,zone_id TEXT NOT NULL,service_code TEXT NOT NULL,package_code TEXT NOT NULL,package_name TEXT NOT NULL,schedule_group_id TEXT NOT NULL UNIQUE,provider_id TEXT NOT NULL,scheduled_start TEXT NOT NULL,scheduled_end TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'confirmed',channel TEXT NOT NULL DEFAULT 'customer_app',total_amount REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',pricing_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS provider_work_orders (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,schedule_group_id TEXT NOT NULL,provider_id TEXT NOT NULL,provider_name TEXT NOT NULL,provider_model TEXT NOT NULL,service_code TEXT NOT NULL,scheduled_start TEXT NOT NULL,scheduled_end TEXT NOT NULL,occurrence_count INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'assigned',assignment_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS booking_payments (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,customer_id TEXT NOT NULL,amount REAL NOT NULL,amount_due_now REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',method TEXT NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL,gateway TEXT NOT NULL DEFAULT 'uat_sandbox',idempotency_key TEXT NOT NULL UNIQUE,detail_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS booking_lifecycle_events (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,event_type TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,actor_id TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',occurred_at INTEGER NOT NULL)"),
]);}
function validate(input:Input){if(!input.idempotencyKey||!input.scheduleGroupId||!input.sittingQuoteId)return"Sitting quote and request identity are required";if(!input.customer?.id||!input.customer?.name||!input.customer?.primaryPhone)return"Customer identity is required";if(!Array.isArray(input.pets)||!input.pets.length)return"At least one pet is required";if(!input.packageCode||!input.packageName||!input.scheduledStart||!input.scheduledEnd)return"Complete Sitting service details are required";if(!input.provider?.id||!input.provider?.name)return"Assigned sitter is required";if(!Number.isFinite(input.totalAmount)||!Number.isFinite(input.amountDueNow))return"Valid Sitting amounts are required";return null;}
async function readBundle(db:D1Database,booking:Row,duplicatePrevented:boolean){const[workOrder,payment]=await Promise.all([db.prepare("SELECT id FROM provider_work_orders WHERE booking_id=?").bind(booking.id).first<Row>(),db.prepare("SELECT id FROM booking_payments WHERE booking_id=?").bind(booking.id).first<Row>()]);return{bookingId:String(booking.id),customerId:String(booking.customer_id),scheduleGroupId:String(booking.schedule_group_id),workOrderId:String(workOrder?.id||""),paymentId:String(payment?.id||""),status:String(booking.status),duplicatePrevented};}
async function failure(error:unknown){if(error instanceof Response){const message=await error.text().catch(()=>"");return json({error:message||"Sitting booking failed"},error.status||500);}return json({error:error instanceof Error?error.message:"Sitting booking failed"},500);}

export async function POST(request:Request){try{
 sameOriginWrite(request);const input=await request.json() as Input,problem=validate(input);if(problem)return json({error:problem},400);
 const db=await database();await ensureTables(db);const actor=await resolveActor(request);await requireCustomerOwnership(db,actor,input.customer.id);
 const prior=await db.prepare("SELECT * FROM canonical_bookings WHERE idempotency_key=? OR schedule_group_id=?").bind(input.idempotencyKey,input.scheduleGroupId).first<Row>();if(prior)return json({data:await readBundle(db,prior,true)});
 const assignment=await db.prepare("SELECT selected_provider_id,status,shortlist_json FROM scheduling_assignment_decisions WHERE group_id=?").bind(input.scheduleGroupId).first<Row>();
 if(!assignment||String(assignment.status)!=="assigned")return json({error:"Scheduling must be assigned before Sitting confirmation"},409);
 if(String(assignment.selected_provider_id)!==input.provider.id)return json({error:"The sitter does not match the scheduling decision"},409);
 const reservations=await db.prepare("SELECT id,provider_id,scheduled_start,scheduled_end,occurrence_number,status FROM scheduling_reservations WHERE group_id=? AND status!='cancelled' ORDER BY occurrence_number").bind(input.scheduleGroupId).all<Row>();
 if(reservations.results.length!==1)return json({error:"Sitting Gate 1 requires exactly one canonical care reservation"},409);
 const reservation=reservations.results[0];if(String(reservation.provider_id)!==input.provider.id)return json({error:"The Sitting reservation belongs to a different provider"},409);
 if(String(reservation.scheduled_start)!==input.scheduledStart||String(reservation.scheduled_end)!==input.scheduledEnd)return json({error:"Sitting booking window does not match the canonical reservation"},409);
 const governed=await governSittingBooking(db,{quoteId:input.sittingQuoteId,packageCode:input.packageCode,packageName:input.packageName,petCount:input.pets.length,scheduledStart:input.scheduledStart,scheduledEnd:input.scheduledEnd,submittedTotal:input.totalAmount,submittedAmountDueNow:input.amountDueNow,paymentMode:input.payment.mode,paymentStatus:input.payment.status,reservationCount:reservations.results.length});
 const now=Date.now(),bookingId=`PS-UAT-SIT-${now.toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,4).toUpperCase()}`,workOrderId=`WO-SIT-${crypto.randomUUID().slice(0,8).toUpperCase()}`,paymentId=`PAY-SIT-${crypto.randomUUID().slice(0,8).toUpperCase()}`,ids=input.pets.map(pet=>petId(input.customer.id,pet.sourceId));
 const pricingJson=JSON.stringify({sittingQuoteId:input.sittingQuoteId,catalogueVersion:governed.catalogueVersion,mode:governed.mode,billableUnits:governed.billableUnits,basePricePerPet:governed.basePricePerPet,extraPetPrice:governed.extraPetPrice,liveMoney:false});
 const statements=[
  db.prepare("INSERT INTO canonical_customers (id,city_id,name,primary_phone,secondary_phone,email,source,consent_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?, ?,?,?) ON CONFLICT(id) DO UPDATE SET city_id=excluded.city_id,name=excluded.name,primary_phone=excluded.primary_phone,secondary_phone=excluded.secondary_phone,email=excluded.email,updated_at=excluded.updated_at").bind(input.customer.id,input.cityId,input.customer.name,input.customer.primaryPhone,input.customer.secondaryPhone??null,input.customer.email??null,"uat_customer_app",JSON.stringify({serviceUpdates:true,marketing:false}),now,now),
  ...input.pets.map((pet,index)=>db.prepare("INSERT INTO canonical_pets (id,customer_id,name,species,breed,vaccination_status,source_pet_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,species=excluded.species,breed=excluded.breed,vaccination_status=excluded.vaccination_status,updated_at=excluded.updated_at").bind(ids[index],input.customer.id,pet.name,pet.species??"other",pet.breed??null,pet.vaccinationStatus??"not_provided",pet.sourceId,now,now)),
  db.prepare("INSERT INTO canonical_bookings (id,idempotency_key,customer_id,pet_ids_json,source_pet_ids_json,city_id,zone_id,service_code,package_code,package_name,schedule_group_id,provider_id,scheduled_start,scheduled_end,status,channel,total_amount,currency,pricing_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(bookingId,input.idempotencyKey,input.customer.id,JSON.stringify(ids),JSON.stringify(input.pets.map(p=>p.sourceId)),input.cityId,input.zoneId,"pet_sitting",governed.packageCode,governed.packageName,input.scheduleGroupId,input.provider.id,input.scheduledStart,input.scheduledEnd,"confirmed","customer_app",governed.totalAmount,"INR",pricingJson,actor.email,now,now),
  db.prepare("INSERT INTO provider_work_orders (id,booking_id,schedule_group_id,provider_id,provider_name,provider_model,service_code,scheduled_start,scheduled_end,occurrence_count,status,assignment_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,1,'assigned',?,?,?)").bind(workOrderId,bookingId,input.scheduleGroupId,input.provider.id,input.provider.name,input.provider.model,"pet_sitting",input.scheduledStart,input.scheduledEnd,JSON.stringify({source:"canonical_sitting_gate1",reservationId:reservation.id}),now,now),
  db.prepare("INSERT INTO booking_payments (id,booking_id,customer_id,amount,amount_due_now,currency,method,mode,status,gateway,idempotency_key,detail_json,created_at,updated_at) VALUES (?,?,?,?,?,'INR',?,?,?,'uat_sandbox',?,?,?,?)").bind(paymentId,bookingId,input.customer.id,governed.totalAmount,governed.amountDueNow,input.payment.method,input.payment.mode,input.payment.status,`sitting:${input.idempotencyKey}`,JSON.stringify({detail:input.payment.detail,liveMoney:false}),now,now),
  db.prepare("INSERT INTO booking_lifecycle_events (id,booking_id,event_type,entity_type,entity_id,actor_id,detail_json,occurred_at) VALUES (?,?,?,?,?,?,?,?)").bind(`EVT-SIT-${crypto.randomUUID().slice(0,8).toUpperCase()}`,bookingId,"sitting_booking_confirmed","booking",bookingId,actor.email,JSON.stringify({quoteId:input.sittingQuoteId,scheduleGroupId:input.scheduleGroupId,providerId:input.provider.id}),now),
  db.prepare("INSERT INTO sitting_booking_quote_links (quote_id,booking_id,created_at) VALUES (?,?,?)").bind(input.sittingQuoteId,bookingId,now),
  db.prepare("UPDATE sitting_commercial_quotes SET status='used',used_at=?,used_booking_id=? WHERE id=? AND status='open'").bind(now,bookingId,input.sittingQuoteId),
 ];
 await db.batch(statements);return json({data:{bookingId,customerId:input.customer.id,petIds:ids,scheduleGroupId:input.scheduleGroupId,workOrderId,paymentId,status:"confirmed",duplicatePrevented:false,liveMoney:false}},201);
}catch(error){return failure(error);}}
