"use client";
import{useCallback,useEffect,useMemo,useState}from"react";

type Readiness={campaign:string;label:string;requiresMarketingConsent:boolean;ready:number;refreshedAt:number|null};
type CallRow={id:string;campaign:string;contactId:string;phone:string;status:string;callRef?:string|null;reason?:string|null;requestedBy:string;createdAt:number};
type ApiResult={data?:unknown;error?:string};
async function api(path:string,init?:RequestInit){const response=await fetch(path,{...init,headers:{"content-type":"application/json",...(init?.headers||{})},cache:"no-store"});const body=await response.json()as ApiResult;if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body.data;}
const when=(value:number|null|undefined)=>value?new Date(value).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"}):"Not refreshed";

export default function HaptikOperationsPage(){const[readiness,setReadiness]=useState<Readiness[]>([]),[calls,setCalls]=useState<CallRow[]>([]),[campaign,setCampaign]=useState(""),[audience,setAudience]=useState<Record<string,unknown>[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const[r,c]=await Promise.all([api("/api/haptik-outbound?mode=readiness"),api("/api/haptik-outbound?mode=calls&limit=100")]);const ready=(r as Readiness[])||[];setReadiness(ready);setCalls((c as CallRow[])||[]);setCampaign(current=>current||ready[0]?.campaign||"");setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load Haptik operations");}finally{setLoading(false)}},[]);
 useEffect(()=>{let active=true;void Promise.all([api("/api/haptik-outbound?mode=readiness"),api("/api/haptik-outbound?mode=calls&limit=100")]).then(([r,c])=>{if(!active)return;const ready=(r as Readiness[])||[];setReadiness(ready);setCalls((c as CallRow[])||[]);setCampaign(ready[0]?.campaign||"");setError("");}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load Haptik operations")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const preview=useCallback(async(code:string)=>{try{const data=await api(`/api/haptik-outbound?mode=audience&campaign=${encodeURIComponent(code)}&limit=50`)as{audience?:Record<string,unknown>[]}|undefined;setAudience(data?.audience||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to preview campaign")}},[]);
 useEffect(()=>{if(!campaign)return;let active=true;void api(`/api/haptik-outbound?mode=audience&campaign=${encodeURIComponent(campaign)}&limit=50`).then(data=>{if(active)setAudience(((data as{audience?:Record<string,unknown>[]}|undefined)?.audience)||[])}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to preview campaign")});return()=>{active=false}},[campaign]);
 const chooseCampaign=(code:string)=>{setCampaign(code);void preview(code)};
 const totals=useMemo(()=>({ready:readiness.reduce((sum,item)=>sum+item.ready,0),dialled:calls.filter(item=>item.status==="dialled").length,failed:calls.filter(item=>item.status==="failed").length}),[readiness,calls]);
 return <main className="mx-auto max-w-7xl space-y-6 p-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-neutral-500">CRM / Communications</p><h1 className="text-3xl font-semibold">Haptik campaign operations</h1><p className="mt-2 max-w-3xl text-sm text-neutral-600">Readiness, governed audience previews and recent dial outcomes. Campaign launching remains permission-gated through the existing API and is intentionally not automated here.</p></div><button onClick={()=>void load()} className="rounded-lg border px-4 py-2 text-sm font-medium" disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></header>
 {error?<div role="alert" className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
 <section className="grid gap-3 md:grid-cols-3"><Metric label="Ready contacts" value={totals.ready}/><Metric label="Recent dialled" value={totals.dialled}/><Metric label="Recent failed" value={totals.failed}/></section>
 <section className="rounded-xl border bg-white p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Campaign readiness</h2><p className="text-sm text-neutral-500">Marketing campaigns are populated only from consented, non-opted-out contacts.</p></div><select value={campaign} onChange={e=>chooseCampaign(e.target.value)} className="rounded-lg border px-3 py-2 text-sm" aria-label="Campaign">{readiness.map(item=><option key={item.campaign} value={item.campaign}>{item.label}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-neutral-500"><th className="py-2">Campaign</th><th>Ready</th><th>Consent</th><th>Refreshed</th></tr></thead><tbody>{readiness.map(item=><tr key={item.campaign} className="border-b last:border-0"><td className="py-3"><button className="font-medium underline-offset-2 hover:underline" onClick={()=>chooseCampaign(item.campaign)}>{item.label}</button><div className="text-xs text-neutral-500">{item.campaign}</div></td><td>{item.ready}</td><td>{item.requiresMarketingConsent?"Marketing consent required":"Service follow-up"}</td><td>{when(item.refreshedAt)}</td></tr>)}</tbody></table></div></section>
 <section className="rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">Governed audience preview</h2><p className="mb-3 text-sm text-neutral-500">Showing up to 50 currently eligible contacts for {campaign||"the selected campaign"}.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-neutral-500"><th className="py-2">Contact</th><th>Name</th><th>Phone</th><th>Reason</th></tr></thead><tbody>{audience.map((row,index)=><tr key={String(row.contactId||index)} className="border-b last:border-0"><td className="py-3">{String(row.contactId||"")}</td><td>{String(row.name||"")}</td><td>{String(row.phone||"")}</td><td>{String((row.context as Record<string,unknown>|undefined)?.reason||"")}</td></tr>)}{!audience.length?<tr><td colSpan={4} className="py-6 text-center text-neutral-500">No eligible contacts in this audience.</td></tr>:null}</tbody></table></div></section>
 <section className="rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">Recent outbound ledger</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-neutral-500"><th className="py-2">Campaign</th><th>Contact</th><th>Status</th><th>Requested by</th><th>Time</th></tr></thead><tbody>{calls.map(row=><tr key={row.id} className="border-b last:border-0"><td className="py-3">{row.campaign}</td><td>{row.contactId}</td><td>{row.status}{row.reason?<div className="text-xs text-neutral-500">{row.reason}</div>:null}</td><td>{row.requestedBy}</td><td>{when(row.createdAt)}</td></tr>)}</tbody></table></div></section></main>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-white p-4"><p className="text-sm text-neutral-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
